<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.heading">
  <title>leg:heading <lnpid>id-AR03-34813</lnpid></title>
  <body>
    <section>
      
        <p><sourcexml>leg:heading</sourcexml> becomes <targetxml>heading</targetxml>. </p>
        
       
    </section>
      <example>
          <title>Source XML</title>
          <codeblock>
&lt;leg:levelbody&gt;    
    &lt;leg:level id="211999_unclassified_1"&gt;
        &lt;leg:level-vrnt subdoc="true" leveltype="unclassified" toc-caption="VISTO"&gt;
            &lt;leg:heading&gt;
                &lt;title&gt;VISTO&lt;/title&gt;
            &lt;/leg:heading&gt;
            &lt;leg:levelbody&gt;
                &lt;leg:bodytext&gt;
                    &lt;p&gt;
                        &lt;text&gt;la Ley N. 25.064 de Presupuesto General de la
                            Administración Nacional para el año 1999, y &lt;/text&gt;
                    &lt;/p&gt;
                &lt;/leg:bodytext&gt;
            &lt;/leg:levelbody&gt;
        &lt;/leg:level-vrnt&gt;
    &lt;/leg:level&gt;
&lt;/leg:levelbody&gt;
              
          </codeblock>
      </example>
              <example>
          <title>Target XML</title>
          <codeblock>
&lt;primlaw:level xml:id="211999_unclassified_1" includeintoc="true"
    alternatetoccaption="VISTO"
    leveltype="unclassified"&gt;
    &lt;heading&gt;
        &lt;title&gt;VISTO&lt;/title&gt;
    &lt;/heading&gt;
    &lt;primlaw:bodytext&gt;
        &lt;p&gt;
            &lt;text&gt;la Ley N. 25.064 de Presupuesto General de la
                Administración Nacional para el año 1999, y&lt;/text&gt;
        &lt;/p&gt;
    &lt;/primlaw:bodytext&gt;
&lt;/primlaw:level&gt;
              
          </codeblock>
      </example>
      
      <section>
          <title>Changes</title>
          <p>2014-12-05:<ph id="change_20141205_AS">Created.</ph></p>
      </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\AR03-Regulation\leg.heading.dita  -->
	<xsl:message>AR03-Regulation_leg.heading.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:heading">

		<!--  Original Target XPath:  heading   -->
		<heading>
			<xsl:apply-templates select="@* | node()"/>
		</heading>

	</xsl:template>

</xsl:stylesheet>