<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:leg="http://www.lexis-nexis.com/glp/leg" version="2.0" exclude-result-prefixes="dita leg">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.histnote-LxAdv-note">
        <title>
            <sourcexml>leg:histnote</sourcexml> to
                <targetxml>note[notetype="historical"]</targetxml>
            <lnpid>id-AU18-21411</lnpid></title>
        <body>
            <section>
                <p>The <sourcexml>leg:histnote</sourcexml> becomes
                        <targetxml>note[notetype="historical"]</targetxml></p>
                <ul>


                    <li>
                        <b>
                            <i>Example: Source XML</i>
                        </b>
                        <pre>              
                     &lt;leg:histnote&gt;
                         &lt;p&gt;&lt;text&gt;[item 2  am BCA 2011]&lt;/text&gt;&lt;/p&gt;
                     &lt;/leg:histnote&gt;
              
                    </pre>

                        <b>
                            <i>Example: Target XML</i>
                        </b>
                        <pre>
              
            	&lt;note notetype="historical"&gt;
            		&lt;bodytext&gt;
                       &lt;p&gt;&lt;text&gt;[item 2  am BCA 2011]&lt;/text&gt;&lt;/p&gt;
            		&lt;/bodytext&gt;
            	&lt;/note&gt;
                   
                 </pre>
                    </li>
                </ul>
            </section>
            <section>
                <title>Changes</title>
            </section>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU18_BRA_Regulatory\AU_BRA_leg.histnote.dita  -->
    <!--<xsl:message>AU18_BRA_Regulatory_leg.histnote.xsl requires manual development!</xsl:message>-->

    <xsl:template match="leg:histnote">      
        <note notetype="historical">
            <xsl:apply-templates select="leg:heading"/>
            <bodytext>
                <xsl:apply-templates select="@* | node() except leg:heading"/>
            </bodytext>
        </note>
    </xsl:template>

</xsl:stylesheet>
