<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
  xmlns:leg="http://www.lexis-nexis.com/glp/leg"
  xmlns:admindoc="urn:x-lexisnexis:content:administrative-document:sharedservices:1" version="2.0"
  exclude-result-prefixes="dita leg">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="AU_BRA_leg.empleg">
    <title>
      <sourcexml>leg:empleg</sourcexml> to
        <targetxml>admindoc:authority/admindoc:authorityitem/textitem</targetxml>
      <lnpid>id-AU18-21410</lnpid></title>
    <body>
      <section>
        <p>The <sourcexml>leg:empleg</sourcexml> becomes
            <targetxml>admindoc:authority/admindoc:authorityitem/textitem</targetxml></p>
        <ul>


          <li>
            <b>
              <i>Example: Source XML</i>
            </b>
            <pre>             

&lt;leg:level id="BRA.ACT.BAA04.DICT1"&gt;
     &lt;leg:level-vrnt searchtype="LEGISLATION DICTIONARY" subdoc="false" leveltype="dictionary" toc-caption="DICTIONARY"&gt;
      &lt;leg:heading&gt;
       &lt;title searchtype="DICT-TITLE"&gt;
        &lt;refpt id="BRA.ACT.BAA04.DICT1" type="ext"&gt;&lt;/refpt&gt;DICTIONARY&lt;/title&gt;
                &lt;leg:empleg&gt;(see 
&lt;remotelink dpsi="0070" remotekey1="REFPTID" service="DOC-ID" refpt="BRA.ACT.BAA04.S3" docidref="BRA.ACT.BAA04.S3"&gt;s 3&lt;/remotelink&gt;
) &lt;/leg:empleg&gt;
   &lt;leg:histnote&gt;
    &lt;p&gt;
      &lt;text&gt;[dict  am Act 36 of 2008  s 3 and Sch 1[1.64], .....&lt;/text&gt;
    &lt;/p&gt;
   &lt;/leg:histnote&gt;
  &lt;/leg:heading&gt;
  .....
  &lt;/leg:level&gt;
                    </pre>

            <b>
              <i>Example: Target XML</i>
            </b>
            <pre>

&lt;admindoc:level alternatetoccaption="DICTIONARY" includeintoc="false" leveltype="dictionary"&gt;
	&lt;ref:anchor id="BRA.ACT.BAA04.DICT1" anchortype="global"/&gt;
	&lt;heading&gt; 
	     &lt;title&gt;DICTIONARY&lt;/title&gt;
	&lt;/heading&gt;
	&lt;admindoc:authority&gt;
		&lt;admindoc:authorityitem&gt;
			&lt;textitem&gt;(see 
			     &lt;ref:crossreference crossreferencetype="see also"&gt;
			       &lt;ref:content&gt;s 3&lt;/ref:content&gt;
			         &lt;ref:locator anchoridref="BRA.ACT.BAA04.S3"&gt;
			         &lt;ref:locator-key&gt;
			          &lt;ref:key-name name="DOC-ID"/&gt;
			          &lt;ref:key-value value="0070-BRA.ACT.BAA04.S3"/&gt;
			         &lt;/ref:locator-key&gt;
			         &lt;/ref:locator&gt;
			     &lt;/ref:crossreference&gt;) 
			&lt;/textitem&gt;
		&lt;/admindoc:authorityitem&gt;
	&lt;/admindoc:authority&gt;
	&lt;note notetype="historical"&gt;
     &lt;bodytext&gt;
       &lt;p&gt;&lt;text&gt;[dict  am Act 36 of 2008  s 3 and Sch 1[1.64], .....&lt;/text&gt;&lt;/p&gt;
     &lt;/bodytext&gt;
  &lt;/note&gt;
  ......
  &lt;/admindoc:level&gt;

              
          </pre>
            <note>The <sourcexml>leg:empleg</sourcexml> comes under
                <sourcexml>leg:heading</sourcexml> element in Rosetta but as per New Lexis
                <targetxml>admindoc:authority</targetxml> should be moved between
                <targetxml>admindoc:level</targetxml> and <targetxml>heading</targetxml>
              elements.</note>
          </li>
        </ul>
      </section>
    </body>
  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU18_BRA_Regulatory\AU_BRA_leg.empleg.dita  -->
  <!--<xsl:message>AU18_BRA_Regulatory_leg.empleg.xsl requires manual development!</xsl:message>-->

  <xsl:template match="leg:empleg">

    <!--  Original Target XPath:  admindoc:authority/admindoc:authorityitem/textitem   -->
    <admindoc:authority>
      <admindoc:authorityitem>
        <textitem>
          <xsl:apply-templates select="@* | node()"/>
        </textitem>
      </admindoc:authorityitem>
    </admindoc:authority>

  </xsl:template>

  <!--<xsl:template match="leg:heading">

    <!-\-  Original Target XPath:  admindoc:authority   -\->
    <admindoc:authority>
      <xsl:apply-templates select="@* | node()"/>
    </admindoc:authority>

  </xsl:template>
-->
</xsl:stylesheet>
