<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
  xmlns:leg="http://www.lexis-nexis.com/glp/leg"
  xmlns:primlawhist="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-history/1/"
  version="2.0" exclude-result-prefixes="dita leg">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.tableofamend">
    <title>leg:tableofamend <lnpid>id-CA05-13633</lnpid></title>
    <body>
      <section>
        <p><sourcexml>leg:tableofamend</sourcexml> becomes
            <targetxml>primlawhist:primlawhist/primlawhist:histgrp[@grptype="tableofamend"]/primlawhist:histitem/bodytext</targetxml>
          <note>Add the attribute value <targetxml>@grptype="tableofamend"</targetxml> to
              <targetxml>primlawhist:histgrp</targetxml></note>
        </p>
      </section>
      <example>
        <title>Mapping of <sourcexml>leg:tableofamend</sourcexml></title>
        <codeblock> &lt;leg:tableofamend&gt; &lt;p&gt; &lt;text&gt; &lt;verbatim
          verbatimclass="verbatim"&gt;** Editor's Table **&lt;nl/&gt; &lt;nl/&gt; Provision Changed
          by In force Authority&lt;nl/&gt; &lt;nl/&gt; 487.0911 2005 c25 s11 2008 Jan 1
          SI/2007-108&lt;nl/&gt; ***** &lt;/verbatim&gt; &lt;/text&gt; &lt;/p&gt;
          &lt;/leg:tableofamend&gt; </codeblock>
        <b>becomes</b>
        <codeblock> &lt;primlawhist:primlawhist&gt; &lt;primlawhist:histgrp
          grptype="tableofamend"&gt; &lt;primlawhist:histitem&gt; &lt;bodytext&gt;
          &lt;p&gt;&lt;text&gt;&lt;verbatim verbatimclass="verbatim"&gt;** Editor's Table
          **&lt;proc:nl/&gt; &lt;proc:nl/&gt; Provision Changed by In force
          Authority&lt;proc:nl/&gt; &lt;proc:nl/&gt; 487.0911 2005 c25 s11 2008 Jan 1
          SI/2007-108&lt;proc:nl/&gt; *****&lt;/verbatim&gt;&lt;/text&gt;&lt;/p&gt;
          &lt;/bodytext&gt; &lt;/primlawhist:histitem&gt; &lt;/primlawhist:histgrp&gt;
          &lt;/primlawhist:primlawhist&gt; </codeblock>
      </example>
    </body>
  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA05-ActsNew\leg.tableofamend.dita  -->
  <!--	<xsl:message>leg.tableofamend.xsl requires manual development!</xsl:message> -->

  <xsl:template match="leg:tableofamend">

    <!--  Original Target XPath:  primlawhist:primlawhist/primlawhist:histgrp[@grptype="tableofamend"]/primlawhist:histitem/bodytext   -->
    <!--<primlawhist:primlawhist>-->
    <primlawhist:histgrp grptype="tableofamend">
      
      <primlawhist:histitem>
        <bodytext>
          <xsl:apply-templates select="@* | node()"/>
        </bodytext>
      </primlawhist:histitem>
    </primlawhist:histgrp>
    <!--</primlawhist:primlawhist>-->

  </xsl:template>

</xsl:stylesheet>
