<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

<!--	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.preamble">
  <title>leg:preamble <lnpid>id-CA05-13631</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:preamble</sourcexml> becomes <targetxml>primlaw:level[@leveltype="preamble"]</targetxml></p> 
    </section>
    <example>
      <title>Mapping of <sourcexml>leg:preamble</sourcexml></title>     
      <codeblock>
&lt;leg:preamble&gt; 
    &lt;leg:heading&gt; 
        &lt;title&gt; 
            &lt;process-ignore process="kwd"&gt;Current to B.C. Regulations Bulletin No. 31, 
                dated August 14, 2012.&lt;/process-ignore&gt; 
        &lt;/title&gt;
   &lt;/leg:heading&gt; 
    &lt;leg:bodytext&gt; 
        &lt;p&gt;&lt;text&gt; 
            The Revised Statutes of British Columbia, 1996, which came into 
            force on April 21, 1997, are a consolidation of the public general Acts of 
            British Columbia and other selected Acts. The consolidation represents the 
            law contained in those consolidated Acts as of December 31, 1996. 
        &lt;/text&gt;&lt;/p&gt;
        &lt;p&gt;&lt;text&gt;LexisNexis Canada updates this consolidation as 
            appropriate.&lt;/text&gt;&lt;/p&gt; 
    &lt;/leg:bodytext&gt; 
&lt;/leg:preamble&gt;

      </codeblock>
      <b>becomes</b>
      <codeblock>

&lt;primlaw:level leveltype="preamble"&gt;
    &lt;heading&gt; 
        &lt;title&gt;Current to B.C. Regulations Bulletin No. 31, dated August 14, 2012.&lt;/title&gt;
    &lt;/heading&gt;
    &lt;primlaw:bodytext&gt;
        &lt;p&gt;
            &lt;text&gt; 
            The Revised Statutes of British Columbia, 1996, which came into 
            force on April 21, 1997, are a consolidation of the public general Acts of 
            British Columbia and other selected Acts. The consolidation represents the 
            law contained in those consolidated Acts as of December 31, 1996. 
            &lt;/text&gt;
        &lt;/p&gt;
        &lt;p&gt;
            &lt;text&gt;LexisNexis Canada updates this consolidation as 
            appropriate.&lt;/text&gt;
        &lt;/p&gt; 
    &lt;/primlaw:bodytext&gt;
&lt;/primlaw:level&gt;
    
      </codeblock>
    </example>    
  </body>
	</dita:topic>

	<!-\-  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -\->
	<!-\-    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA05-ActsNew\leg.preamble.dita  -\->
	<xsl:message>leg.preamble.xsl requires manual development!</xsl:message> -->

	<xsl:template match="leg:preamble">

		<!--  Original Target XPath:  primlaw:level[@leveltype="preamble"]   -->
		<primlaw:level>
		    <xsl:attribute name="leveltype">
		        <xsl:text>preamble</xsl:text>
		    </xsl:attribute>
			<xsl:apply-templates select="@* | node()"/>
		</primlaw:level>

	</xsl:template>

</xsl:stylesheet>