<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"
	xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/"
	xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/" 
	xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:ci="http://www.lexis-nexis.com/ci"
	xmlns:lnci="http://www.lexisnexis.com/xmlschemas/content/shared/citations/1/"
	xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/"
	xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"
	xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/"
	xmlns:proc="http://www.lexisnexis.com/xmlschemas/content/shared/process-elements/1/"
	xmlns:classify="http://www.lexisnexis.com/xmlschemas/content/shared/classification/1/"
	xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/"
	xmlns:functx="http://www.functx.com" version="2.0" exclude-result-prefixes="#all">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.body">
		<title>leg:body <lnpid>id-CA05-13610</lnpid></title>
		<body>
			<section>
				<p><sourcexml>leg:body</sourcexml> becomes <targetxml>legis:body</targetxml>.The
					mappings for the children of <targetxml>leg:body</targetxml> are discussed as
					separate topics.</p>
			</section>
		</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA05-ActsNew\leg.body.dita  -->
	<!--<xsl:message>leg.body.xsl requires manual development!</xsl:message> -->
			
		<xsl:template match="leg:body">
		<xsl:apply-templates select="child::leg:info"/>
		<legis:body>
			<xsl:apply-templates
				select="descendant::leg:history/leg:histnote[descendant::text[starts-with(., 'REPEALED by') or starts-with(., 'ABROGÉ par') or starts-with(., 'ABROGÉE par')]]"
				mode="repealed"/>
			<xsl:apply-templates select="descendant::leg:longtitle"/>
			<xsl:apply-templates select="child::leg:level"/>
			<xsl:variable name="status_text" select="/LEGDOC/leg:body/leg:info/leg:history//leg:histnote/descendant::p/text"/>
			<xsl:variable name="dpsi" select="/LEGDOC/docinfo/docinfo:custom-metafields/docinfo:custom-metafield[@name = 'dpsi']"/>
			<xsl:variable name="doc_id" select="substring-before(/LEGDOC/docinfo/docinfo:doc-id,'-')"/>
			
			<xsl:if test="(($dpsi = $vDpsiCodes//*:code/@key) or ($doc_id = $vDpsiCodes//*:code/@key)) and not(child::leg:level or leg:level[descendant::leg:bodytext=''])">
				<xsl:choose>
					<xsl:when test="child::leg:info[not(following-sibling::*)]">
						<primlaw:level leveltype="unclassified">
						<primlaw:levelinfo>
							<primlawinfo:primlawinfo>
								<legisinfo:legisinfo>
									<legisinfo:statusgroup>
										<legisinfo:status>
											<!--RS-2017-12-08- Added  <xsl:choose> Condition in <xsl:attribute name="statuscode"> -->
											<xsl:attribute name="statuscode">
												<xsl:choose>
													<xsl:when test="$vDpsiCodes//*:code[@key = $dpsi or $doc_id]/@value = 'ANNUALS'">
														<xsl:text>annual</xsl:text>
													</xsl:when>
													
													<xsl:when test="$vDpsiCodes//*:code[@key = $dpsi or $doc_id]/@value = 'REPEALED'">
														<xsl:text>repealed</xsl:text>
													</xsl:when>
													<xsl:when test="$vDpsiCodes//*:code[@key = $dpsi or $doc_id]/@value = 'ABROGÉE'">
														<xsl:text>repealed</xsl:text>
													</xsl:when>
													<xsl:when test="$vDpsiCodes//*:code[@key = $dpsi or $doc_id]/@value = 'Prior Consolidation'">
														<xsl:text>priorconsolidation</xsl:text>
													</xsl:when>
												</xsl:choose>
												<!-- <xsl:apply-templates select="/LEGDOC/docinfo/docinfo:custom-metafields/docinfo:custom-metafield[@name = 'dpsi']"
                                            mode="DpsiCode"/>-->
											</xsl:attribute>
											<legisinfo:statustext>
												<xsl:choose>
													<xsl:when test="/LEGDOC/docinfo/docinfo:custom-metafields/docinfo:custom-metafield[@name = 'dpsi']">
														<xsl:apply-templates select="/LEGDOC/docinfo/docinfo:custom-metafields/docinfo:custom-metafield[@name = 'dpsi']"
															mode="DpsiCode"/>
													</xsl:when>
													<xsl:otherwise>
														<xsl:apply-templates select="/LEGDOC/docinfo/docinfo:doc-id[substring-before(.,'-')]"
															mode="DpsiCode_DocID"/>
													</xsl:otherwise>
												</xsl:choose>
											</legisinfo:statustext>
										</legisinfo:status>
									</legisinfo:statusgroup>
								</legisinfo:legisinfo>
							</primlawinfo:primlawinfo>
						</primlaw:levelinfo>
						</primlaw:level>
					</xsl:when>
					<xsl:otherwise>
						<primlaw:levelinfo>
							<primlawinfo:primlawinfo>
								<legisinfo:legisinfo>
									<legisinfo:statusgroup>
										<legisinfo:status>
											<!--RS-2017-12-08- Added  <xsl:choose> Condition in <xsl:attribute name="statuscode"> -->
											<xsl:attribute name="statuscode">
												<xsl:choose>
													<xsl:when test="$vDpsiCodes//*:code[@key = $dpsi or $doc_id]/@value = 'ANNUALS'">
														<xsl:text>annual</xsl:text>
													</xsl:when>
													
													<xsl:when test="$vDpsiCodes//*:code[@key = $dpsi or $doc_id]/@value = 'REPEALED'">
														<xsl:text>repealed</xsl:text>
													</xsl:when>
													<xsl:when test="$vDpsiCodes//*:code[@key = $dpsi or $doc_id]/@value = 'ABROGÉE'">
														<xsl:text>repealed</xsl:text>
													</xsl:when>
													<xsl:when test="$vDpsiCodes//*:code[@key = $dpsi or $doc_id]/@value = 'Prior Consolidation'">
														<xsl:text>priorconsolidation</xsl:text>
													</xsl:when>
												</xsl:choose>
												<!-- <xsl:apply-templates select="/LEGDOC/docinfo/docinfo:custom-metafields/docinfo:custom-metafield[@name = 'dpsi']"
                                            mode="DpsiCode"/>-->
											</xsl:attribute>
											<legisinfo:statustext>
												<xsl:choose>
													<xsl:when test="/LEGDOC/docinfo/docinfo:custom-metafields/docinfo:custom-metafield[@name = 'dpsi']">
														<xsl:apply-templates select="/LEGDOC/docinfo/docinfo:custom-metafields/docinfo:custom-metafield[@name = 'dpsi']"
															mode="DpsiCode"/>
													</xsl:when>
													<xsl:otherwise>
														<xsl:apply-templates select="/LEGDOC/docinfo/docinfo:doc-id[substring-before(.,'-')]"
															mode="DpsiCode_DocID"/>
													</xsl:otherwise>
												</xsl:choose>
											</legisinfo:statustext>
										</legisinfo:status>
									</legisinfo:statusgroup>
								</legisinfo:legisinfo>
							</primlawinfo:primlawinfo>
						</primlaw:levelinfo>
					</xsl:otherwise>
				</xsl:choose>
				
			</xsl:if>
			<xsl:if test="(not(child::leg:level) or leg:level[descendant::leg:bodytext='']) and not($dpsi = $vDpsiCodes//*:code/@key  or $doc_id = $vDpsiCodes//*:code/@key)">
				<primlaw:level leveltype="unclassified">
					<primlaw:levelinfo>
						<primlawinfo:primlawinfo>
							<legisinfo:legisinfo>
								<legisinfo:statusgroup>
									<legisinfo:status statuscode="consolidated"/> 
								</legisinfo:statusgroup>
							</legisinfo:legisinfo>
						</primlawinfo:primlawinfo>
					</primlaw:levelinfo>
				</primlaw:level>
			</xsl:if>
		</legis:body>
	</xsl:template>

</xsl:stylesheet>
