<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:leg="http://www.lexis-nexis.com/glp/leg" version="2.0" exclude-result-prefixes="dita docinfo leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.hier">
  <title>leg:hier <lnpid>id-CA06-13814</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:hier</sourcexml> and its child elements <sourcexml>leg:hierlev</sourcexml> needs to be suppressed from conversion since it has the same information as that of <sourcexml>docinfo:hier</sourcexml> and <sourcexml>docinfo:hierlev</sourcexml>
      </p> 
    </section>
    <example>         
      <codeblock>
&lt;docinfo:hier&gt;
    &lt;docinfo:hierlev role="ancestor"&gt;
        &lt;heading&gt;
            &lt;title&gt;Apprenticeship and Industry Training Act&lt;/title&gt;
        &lt;/heading&gt;
        &lt;docinfo:hierlev role="ancestor"&gt;
            &lt;heading&gt;
                &lt;title&gt;STRUCTURAL STEEL AND PLATE FITTER TRADE REGULATION&lt;/title&gt;
            &lt;/heading&gt;
            &lt;docinfo:hierlev role="me"&gt;
                &lt;heading&gt;
                    &lt;title&gt;Table of Contents&lt;/title&gt;
                &lt;/heading&gt;
            &lt;/docinfo:hierlev&gt;
        &lt;/docinfo:hierlev&gt;
    &lt;/docinfo:hierlev&gt;
&lt;/docinfo:hier&gt;
&lt;!-...-&gt;
&lt;leg:hier&gt;
    &lt;leg:hierlev leveltype="2"&gt;Table of Contents&lt;/leg:hierlev&gt;
&lt;/leg:hier&gt;

      </codeblock>      
    </example>    
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA06-Regulation\leg.hier.dita  -->
	<!--<xsl:message>CA06-Regulation_leg.hier.xsl requires manual development!</xsl:message> -->

	<xsl:template match="leg:info/leg:hier">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<!--<xsl:apply-templates select="@* | node()"/>-->
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

    <xsl:template match="leg:hierlev" mode="hier">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<!--<xsl:apply-templates select="@* | node()"/>-->
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

    <xsl:template match="docinfo:hier" mode="hier">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<!--<xsl:apply-templates select="@* | node()"/>-->
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

    <xsl:template match="docinfo:hierlev" mode="hier">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<!--<xsl:apply-templates select="@* | node()"/>-->
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>