<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.preamble">
  <title>leg:preamble <lnpid>id-CA06-13829</lnpid></title>
  <body>
    <section>
		<ul>
			<li><sourcexml>leg:preamble</sourcexml>
					<b>Becomes</b>
					<targetxml>primlaw:level[@leveltype="preamble"]</targetxml> and populated as: <pre>
              <b><i>Example: Source Markup</i></b>

&lt;leg:preamble&gt; 
	&lt;leg:heading&gt; 
		&lt;title&gt;&lt;process-ignore process="kwd"&gt;Updated on July 27, 2012.&lt;/process-ignore&gt;&lt;/title&gt; 
	&lt;/leg:heading&gt; 
    &lt;leg:bodytext&gt; 
		&lt;p&gt;
			&lt;text&gt;The purpose of this source is to hold repealed or expired 
				 Regulations which have been removed from the ABRG source (Regulations 
				 of Alberta) since January 1, 2000.  Regulations which are partially 
				 expired or repealed remain in ABRG until fully repealed.&lt;/text&gt;
		&lt;/p&gt;
	&lt;/leg:bodytext&gt; 
&lt;/leg:preamble&gt; 

             
</pre>
					<pre>

              <b><i>Example: Target Markup</i></b>
              

&lt;primlaw:level leveltype="preamble"&gt;
	&lt;heading&gt;
		&lt;title&gt;Updated on July 27, 2012.&lt;/title&gt;
	&lt;/heading&gt;
	&lt;primlaw:bodytext&gt;
		&lt;p&gt;
			&lt;text&gt;The purpose of this source is to hold repealed or expired 
				 Regulations which have been removed from the ABRG source (Regulations 
				 of Alberta) since January 1, 2000.  Regulations which are partially 
				 expired or repealed remain in ABRG until fully repealed.&lt;/text&gt;
		&lt;/p&gt;
	&lt;/primlaw:bodytext&gt;
&lt;/primlaw:level&gt;

            </pre>
					<note>"<sourcexml>leg:preamble</sourcexml>" element mapped to
							'<targetxml>primlaw:level</targetxml>' with fixed attribute value
							<targetxml>'@leveltype="preamble"</targetxml>'.</note>
					<note>If source document having
							"<sourcexml>leg:preamble/leg:bodytext</sourcexml>" then it
							<b>becomes</b>
							"<targetxml>primlaw:level[@leveltype="preamble]/primlaw:bodytext</targetxml>".</note>
					<note>If source document having "<sourcexml>title/process-ignore</sourcexml>"
						then it <b>becomes</b> "<targetxml>title</targetxml>" and
							<sourcexml>process-ignore</sourcexml> markup should be suppressed in
						target conversion.</note>
				</li>
		</ul>
    </section> 
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA06-Regulation\leg.preamble.dita  -->
	<!--<xsl:message>CA06-Regulation_leg.preamble.xsl requires manual development!</xsl:message> -->

	<xsl:template match="leg:preamble">

		<!--  Original Target XPath:  primlaw:level[@leveltype="preamble"]   -->
		<primlaw:level leveltype='preamble'>
			<xsl:apply-templates select="@* | node() except process-ignore"/>
		</primlaw:level>

	</xsl:template>

</xsl:stylesheet>