<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.preamble">
  <title>leg:preamble <lnpid>id-CA08-14228</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:preamble</sourcexml> becomes <targetxml>primlaw:level[@leveltype="preamble"]</targetxml></p> 
    </section>
    <example>
            <title>Mapping of <sourcexml>leg:preamble</sourcexml></title>
            <codeblock>
&lt;leg:preamble&gt; 
    &lt;leg:heading&gt; 
        &lt;title&gt; 
            &lt;process-ignore process="kwd"&gt;Constitutional Acts of Canada&lt;/process-ignore&gt; 
        &lt;/title&gt;
   &lt;/leg:heading&gt; 
    &lt;leg:bodytext&gt; 
        &lt;p&gt;&lt;text&gt;This source contains Constitutional Acts of Canada.&lt;/text&gt;&lt;/p&gt; 
        &lt;p&gt;&lt;text&gt;LexisNexis Canada updates this source as appropriate.&lt;/text&gt;&lt;/p&gt; 
    &lt;/leg:bodytext&gt; 
&lt;/leg:preamble&gt;

      </codeblock>
            <b>becomes</b>
            <codeblock>

&lt;primlaw:level leveltype="preamble"&gt;
    &lt;heading&gt; 
        &lt;title&gt;Constitutional Acts of Canada&lt;/title&gt;
    &lt;/heading&gt;
    &lt;primlaw:bodytext&gt;
        &lt;p&gt;&lt;text&gt;This source contains Constitutional Acts of Canada.&lt;/text&gt;&lt;/p&gt; 
        &lt;p&gt;&lt;text&gt;LexisNexis Canada updates this source as appropriate.&lt;/text&gt;&lt;/p&gt; 
    &lt;/primlaw:bodytext&gt;
&lt;/primlaw:level&gt;
    
      </codeblock>
        </example>    
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA08-Constitutions\leg.preamble.dita  -->
<!--	<xsl:message>CA08-Constitutions_leg.preamble.xsl requires manual development!</xsl:message> -->

    <xsl:template match="leg:preamble">
        
        <!--  Original Target XPath:  primlaw:level[@leveltype="preamble"]   -->
        <primlaw:level leveltype='preamble'>
            <xsl:apply-templates select="@* | node() except process-ignore"/>
        </primlaw:level>
        
    </xsl:template>

</xsl:stylesheet>