<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
  xmlns:leg="http://www.lexis-nexis.com/glp/leg"
  xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/"
  xmlns:lnci="http://www.lexisnexis.com/xmlschemas/content/shared/citations/1/"
  xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/"
  xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/"
  xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" version="2.0"
  exclude-result-prefixes="#all">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.officialnum">
    <title>leg:officialnum <lnpid>id-CA08-14227</lnpid></title>
    <body>
      <section>
        <p><sourcexml>leg:officialnum</sourcexml> becomes
            <targetxml>primlawinfo:primlawinfo/primlawinfo:identifier</targetxml> with required
          attribute <targetxml>@idtype="officialnum"</targetxml></p>
      </section>
      <example>
        <title>Mapping of <sourcexml>leg:officialnum</sourcexml></title>
        <codeblock> &lt;leg:officialnum&gt;3-4 Victoria, c. 35 (U.K.)&lt;/leg:officialnum&gt; </codeblock>
        <b>becomes</b>
        <codeblock> &lt;primlawinfo:primlawinfo&gt; &lt;primlawinfo:identifier
          idtype="officialnum"&gt;3-4 Victoria, c. 35 (U.K.)&lt;/primlawinfo:identifier&gt;
          &lt;/primlawinfo:primlawinfo&gt; </codeblock>
      </example>
      <note>
        <p>
          <b>Rule for (English) text handling:</b>
        </p>
        <p>After <sourcexml>leg:officialnum</sourcexml> drop the "<b>[Reprinted in </b>" text and
          also drop the square brackets "[ or ]" as per below input and target markup:</p>
      </note>

      <example>
        <title>Mapping of <sourcexml>leg:officialnum</sourcexml></title>
        <codeblock> &lt;leg:officialnum&gt;[Reprinted in R.S.C. 1985, App. II, No.
          10]&lt;/leg:officialnum&gt; </codeblock>
        <b>becomes</b>
        <codeblock> &lt;primlawinfo:primlawinfo&gt; &lt;primlawinfo:identifier
          idtype="officialnum"&gt;R.S.C. 1985, App. II, No. 10&lt;/primlawinfo:identifier&gt;
          &lt;/primlawinfo:primlawinfo&gt; </codeblock>
      </example>
      <note>
        <p>
          <b>Rule for (French) text handling :</b>
        </p>
        <p>After <sourcexml>leg:officialnum</sourcexml> drop the "<b>[Reproduite dans </b>" text and
          also drop the square brackets "[ or ]" as per below input and target markup:</p>
      </note>

      <example>
        <title>Mapping of <sourcexml>leg:officialnum</sourcexml></title>
        <codeblock> &lt;leg:officialnum&gt;[Reproduite dans L.R.C. 1985, app. II, no
          2]&lt;/leg:officialnum&gt; </codeblock>
        <b>becomes</b>
        <codeblock> &lt;primlawinfo:primlawinfo&gt; &lt;primlawinfo:identifier
          idtype="officialnum"&gt;L.R.C. 1985, app. II, no 2&lt;/primlawinfo:identifier&gt;
          &lt;/primlawinfo:primlawinfo&gt; </codeblock>
      </example>
      <note>
        <p>
          <b>Move first leg:officialnum to ref:parallelcite :</b>
        </p>
        <p>The first <sourcexml>leg:officialnum</sourcexml> should be converted to ref:parallelcite
          markup as follows.</p>
      </note>

      <example>
        <title>Mapping of first <sourcexml>leg:officialnum</sourcexml></title>
        <codeblock> &lt;leg:officialnum&gt;14 George III, c. 83 (U.K.)&lt;/leg:officialnum&gt;
          &lt;leg:officialnum&gt;[Reprinted in R.S.C. 1985, App. II, No. 2]&lt;/leg:officialnum&gt; </codeblock>
        <b>becomes</b>
        <codeblock> &lt;legis:head&gt; &lt;ref:citations&gt; &lt;ref:parallelcite
          citetype="parallel"&gt; &lt;lnci:cite&gt; &lt;lnci:content&gt;14 George III, c. 83
          (U.K.)&lt;/lnci:content&gt; &lt;/lnci:cite&gt; &lt;/ref:parallelcite&gt;
          &lt;/ref:citations&gt; &lt;!- ... --&gt; &lt;primlawinfo:primlawinfo&gt;
          &lt;primlawinfo:identifier idtype="officialnum"&gt;R.S.C. 1985, App. II, No.
          2&lt;/primlawinfo:identifier&gt; &lt;/primlawinfo:primlawinfo&gt; &lt;!- ... --&gt;
          &lt;/legis:head&gt; </codeblock>
      </example>
      <section>
        <title>Changes</title>
        <p>2014-06-20: <ph id="change_20140620_CSN">Added a rule to move the first
              <sourcexml>leg:officialnum</sourcexml> to ref:parallelcite markup.</ph></p>
        <p>2014-06-17: <ph id="change_20140617_ss">Instruction and example added for handling
            "English" and "French" text (means drop text "[Reprinted in " and "[Reproduite dans ")
            within <sourcexml>leg:officialnum</sourcexml> markup.</ph></p>
      </section>
    </body>
  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA08-Constitutions\leg.officialnum.dita  -->

  <xsl:variable name="first_act"
    select="lower-case(/*/docinfo/docinfo:custom-metafields/docinfo:custom-metafield[@name = 'actFirstDoc'])"/>

  <xsl:template match="leg:officialnum" mode="parallelcite">
    <xsl:if test="not(preceding-sibling::leg:officialnum)">
      <ref:parallelcite citetype="parallel">
        <lnci:cite>
          <lnci:content>
            <xsl:apply-templates select="leg:officialnum[1]"/>
            <xsl:apply-templates select="@* | node()"/>
          </lnci:content>
        </lnci:cite>
      </ref:parallelcite>
      <xsl:if test="$first_act = 'true'">
        <ref:cite4thisresource>
          <lnci:cite type="act">
            <lnci:content>
              <xsl:apply-templates select="leg:officialnum[1]"/>
              <xsl:apply-templates select="@* | node()"/>
            </lnci:content>
          </lnci:cite>
        </ref:cite4thisresource>
      </xsl:if>
    </xsl:if>
  </xsl:template>

  <xsl:template match="leg:officialnum">
    <xsl:if test="preceding-sibling::leg:officialnum">

      <primlawinfo:identifier idtype="officialnum">



        <!--<xsl:apply-templates select="@* | node()"/>-->

        <xsl:analyze-string select="." regex="^((\[Reprinted in)|(\[Reproduite dans))?\s*(.+)(\])">
          <xsl:matching-substring>
            <xsl:value-of select="regex-group(4)"/>
          </xsl:matching-substring>
          <xsl:non-matching-substring>
            <xsl:value-of select="."/>
          </xsl:non-matching-substring>
        </xsl:analyze-string>

      </primlawinfo:identifier>


    </xsl:if>



  </xsl:template>

</xsl:stylesheet>
