<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.heading">
  <title>leg:heading <lnpid>id-ST02-26413</lnpid></title>
  <body>
    <section>
      <p>
        <sourcexml>leg:heading</sourcexml> becomes <targetxml>heading</targetxml> with attributes
          <sourcexml>@subdoc</sourcexml> becomes <targetxml>@includeintoc</targetxml> and
          <sourcexml>@toc-caption</sourcexml>
        <targetxml>@alternatetoccaption</targetxml>.
      </p>
      
      <note>The attributes <targetxml>@includeintoc</targetxml> and <targetxml>@alternatetoccaption</targetxml> will be part of element 
        <targetxml>primlaw:level</targetxml>, if present in source documents.</note>
      <note>If @align attribute value is "center" (i.e. align="center") then remove the @alignattribute because
        this attribute default value is "left".</note>
    </section>
    
    <example>
      <title>Source XML 1</title>
      <codeblock>

&lt;leg:heading subdoc="true" toc-caption="Définitions"&gt;
   &lt;title align="center"&gt;Définitions&lt;/title&gt;
&lt;/leg:heading&gt;

      </codeblock>
    </example>
    
    <example>
      <title>Target XML 1</title>
      <codeblock>

&lt;heading subdoc="true" toc-caption="Définitions"&gt;
    &lt;title&gt;Définitions&lt;/title&gt;
&lt;/heading&gt;

      </codeblock>
    </example>    
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Courtrule\leg.heading.dita  -->
	<xsl:message>Courtrule_leg.heading.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:heading">

		<!--  Original Target XPath:  heading   -->
		<heading>
			<xsl:apply-templates select="@* | node()"/>
		</heading>

	</xsl:template>

	<xsl:template match="@subdoc">

		<!--  Original Target XPath:  @includeintoc   -->
		<xsl:attribute name="includeintoc">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="@toc-caption">

		<!--  Original Target XPath:  @alternatetoccaption   -->
		<xsl:attribute name="alternatetoccaption">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

</xsl:stylesheet>