<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.year">
  <title>leg:year <lnpid>id-ST02-26429</lnpid></title>
  <body>
    <section>
      <p>
        <sourcexml>leg:info/leg:year</sourcexml> becomes <targetxml>primlawinfo:dates/primlawinfo:enactdate</targetxml> with attribute <targetxml>@year</targetxml>.
        <note><sourcexml>leg:year</sourcexml> input PCDATA transforms only to target attribute <targetxml>primlawinfo:enactdate[@year]</targetxml> and there should be no PCDATA in output.</note>
        <note>For handling <b>@ln.user-displayed</b> attribute, refer the general markup
          <xref href="../../common_newest/Rosetta_leg.year_ln.user-displayed.dita">ln.user_displayed="false"</xref> section in the CI.</note>      
      </p>      
    </section>
    
    <example>
      <title>Source XML</title>
      <codeblock>

&lt;leg:year searchtype="LEGISLATION" ln.user-displayed="false"&gt;1992&lt;/leg:year&gt;

    </codeblock>
    </example>
    
    <example>
      <title>Target XML</title>
      <codeblock>

&lt;primlawinfo:dates&gt;
  &lt;primlawinfo:enactdate year="1992"/&gt;
&lt;/primlawinfo:dates&gt;

    </codeblock>
    </example>
    <section>
      <title>Changes</title>
      <p>2013-09-17: <ph id="change_20130917_VV">Instruction narrative edited for language; no changes to mappings, no impact to stylesheets.</ph></p>
     </section> 
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Courtrule\leg.year.dita  -->
	<xsl:message>Courtrule_leg.year.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:info/leg:year">

		<!--  Original Target XPath:  primlawinfo:dates/primlawinfo:enactdate   -->
		<primlawinfo:dates>
			<primlawinfo:enactdate>
				<xsl:apply-templates select="@* | node()"/>
			</primlawinfo:enactdate>
		</primlawinfo:dates>

	</xsl:template>

	<xsl:template match="leg:year">

		<!--  Original Target XPath:  primlawinfo:enactdate[@year]   -->
		<primlawinfo:enactdate>
			<xsl:apply-templates select="@* | node()"/>
		</primlawinfo:enactdate>

	</xsl:template>

</xsl:stylesheet>