<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:courtrule="http://www.lexisnexis.com/xmlschemas/content/legal/courtrule/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.relatedleg">
  <title>leg:relatedleg <lnpid>id-ST02-26427</lnpid></title>
  <body>
    <section>
      <p>
          <sourcexml>leg:relatedleg</sourcexml> with attribute <sourcexml>@type="parent"</sourcexml> becomes
        <targetxml>courtrule:head/primlaw:authority/primlaw:authority-item/textitem</targetxml>
      </p>
    </section>
    
    <example>
      <title>Source XML 1</title>
      <codeblock>

&lt;leg:relatedleg type="parent"&gt;Made under the &lt;ci:cite searchtype="LEG-REF"
                            &gt;&lt;ci:content&gt;&lt;remotelink service="DOC-ID" remotekey1="REFPTID"
                            refpt="NSW_ACT_1992-94"&gt;MEDICAL PRACTICE ACT 1992 NO
                        94&lt;/remotelink&gt;&lt;/ci:content&gt;&lt;/ci:cite&gt;.&lt;/leg:relatedleg&gt;

      </codeblock>
    </example>
    
    <example>
      <title>Target XML 1</title>
      <codeblock>

&lt;courtrule:head&gt;
    &lt;primlaw:authority&gt;
        &lt;primlaw:authority-item&gt;
            &lt;textitem&gt;Made under the &lt;lnci:cite type="legislation" citeref="NSW_ACT_1992-94"
            &gt;&lt;lnci:content&gt;&lt;ref:crossreference crossreferencetype="seeAlso"&gt;&lt;ref:content&gt;MEDICAL PRACTICE ACT 1992 NO
           94&lt;/ref:content&gt;&lt;ref:locator anchoridref="NSW_ACT_1992-94"&gt;&lt;ref:locator-key&gt;&lt;ref:key-name name="DOC-ID"/&gt;&lt;ref:key-value value="03AF-"
            /&gt;&lt;/ref:locator-key&gt;&lt;/ref:locator&gt;&lt;/ref:crossreference&gt;&lt;/lnci:content&gt;&lt;/lnci:cite&gt;.&lt;/textitem&gt;
        &lt;/primlaw:authority-item&gt;
    &lt;/primlaw:authority&gt;
&lt;/courtrule:head&gt;

      </codeblock>
    </example>   
    
    <example>
      <title>Source XML 2</title>
      <codeblock>

&lt;leg:relatedleg type="parent"&gt;Category 1 -- Procedure and Related Matters&lt;/leg:relatedleg&gt;

      </codeblock>
    </example>
    
    <example>
      <title>Target XML 2</title>
      <codeblock>

&lt;courtrule:head&gt;
    &lt;primlaw:authority&gt;
      &lt;primlaw:authority-item&gt;
          &lt;textitem&gt;Category 1 -- Procedure and Related Matters&lt;/textitem&gt;
      &lt;/primlaw:authority-item&gt;
    &lt;/primlaw:authority&gt;
&lt;/courtrule:head&gt;

      </codeblock>
    </example>     
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Courtrule\leg.relatedleg.dita  -->
	<xsl:message>Courtrule_leg.relatedleg.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:relatedleg">

		<!--  Original Target XPath:  courtrule:head/primlaw:authority/primlaw:authority-item/textitem   -->
		<courtrule:head>
			<primlaw:authority xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/">
				<primlaw:authority-item>
					<textitem>
						<xsl:apply-templates select="@* | node()"/>
					</textitem>
				</primlaw:authority-item>
			</primlaw:authority>
		</courtrule:head>

	</xsl:template>

	<xsl:template match="@type=&#34;parent&#34;">

		<!--  Original Target XPath:  courtrule:head/primlaw:authority/primlaw:authority-item/textitem   -->
		<courtrule:head>
			<primlaw:authority xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/">
				<primlaw:authority-item>
					<textitem>
						<xsl:apply-templates select="@* | node()"/>
					</textitem>
				</primlaw:authority-item>
			</primlaw:authority>
		</courtrule:head>

	</xsl:template>

</xsl:stylesheet>