<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:admindoc="urn:x-lexisnexis:content:administrative-document:sharedservices:1" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="GPL_PH03_leg-officialnum">
    <title>leg:officialnum <lnpid>id-PH03-34619</lnpid></title>
 <body>
     <p>
            <sourcexml>leg:officialnum</sourcexml> becomes
                <targetxml>admindoc:officialnum</targetxml>
            <note> Elements that contain the attribute
                    <sourcexml>@ln.user-displayed="false"</sourcexml> are used for certain
                functionality in Rosetta that does not exist in Lexis Advance. Each of the following
                elements have mappings described elsewhere in this CI for when this attribute does
                not exist. The examples here are ONLY for when this
                    <sourcexml>@ln.user-displayed="false"</sourcexml> appears. (This attribute never
                has a "true" value, i.e. @ln.user-displayed="true".) </note>
            <note> In order to enable searching and indexing while retaining the display integrity
                of the information. The <sourcexml>@source</sourcexml> attribute will be populated with
                "editoriallyassigned" indicating these fields were assigned their value. The
                viewspec will utilize the <sourcexml>@source</sourcexml> attribute to choose whether to display this
                information differently or not at all depending on the needs of the LBU users.
            </note>
        </p>
     <note>If <sourcexml>leg:officialnum</sourcexml> has attribute
                <sourcexml>@ln.user-displayed="false"</sourcexml> will be mapped to
                <targetxml>admindoc:officialnum/@source="editoriallyassigned"</targetxml> in target
            documents</note>
  <section>
   <title>Source XML</title>
   <pre>
   
         &lt;leg:info&gt;
            .....
             &lt;leg:officialnum ln.user-displayed="false" searchtype="LEGISLATION"&gt;Act No. 37, 2001&lt;/leg:officialnum&gt;
            ....
        &lt;/leg:info&gt;
   
   </pre>
  </section>
  <p>Becomes</p>
  <section>
   <title>Target XML</title>
   <pre>
   
    &lt;admindoc:info&gt;
        .....
        &lt;admindoc:officialnum source="editoriallyassigned"&gt;Act No. 37, 2001&lt;/admindoc:officialnum&gt;
        .....
    &lt;/admindoc:info&gt;
   
   </pre>
  </section>
  
 </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\PH03-Regulation\GPL_PH03_leg-officialnum.dita  -->
	<xsl:message>GPL_PH03_leg-officialnum.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:officialnum">

		<!--  Original Target XPath:  admindoc:officialnum   -->
		<admindoc:officialnum>
			<xsl:apply-templates select="@* | node()"/>
		</admindoc:officialnum>

	</xsl:template>

	<xsl:template match="@ln.user-displayed=&#34;false&#34;">

		<!--  Original Target XPath:  admindoc:officialnum/@source="editoriallyassigned"   -->
		<admindoc:officialnum>
			<xsl:attribute name="source">
				<xsl:text>editoriallyassigned</xsl:text>
			</xsl:attribute>
		</admindoc:officialnum>

	</xsl:template>

	<xsl:template match="@source">

		<!--  Original Target XPath:  admindoc:officialnum/@source="editoriallyassigned"   -->
		<admindoc:officialnum>
			<xsl:attribute name="source">
				<xsl:text>editoriallyassigned</xsl:text>
			</xsl:attribute>
		</admindoc:officialnum>

	</xsl:template>

</xsl:stylesheet>