<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:admindoc="urn:x-lexisnexis:content:administrative-document:sharedservices:1" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="GPL_PH03_leg-bodytext">
  <title>leg:levelbody/leg:bodytext <lnpid>id-PH03-34610</lnpid></title>
 <body>
   <section>
   <p><sourcexml>leg:levelbody/leg:bodytext</sourcexml> becomes
          <targetxml>admindoc:bodytext</targetxml>.</p>
   <p>Follow the Instruction of <b>General Markup</b> for the handling of children of <sourcexml>leg:bodytext</sourcexml></p>
   </section>
  <section>
   <title>Source XML</title>
   <pre>
    
    &lt;leg:levelbody&gt;
                    &lt;leg:bodytext&gt;
                        &lt;p&gt;
                            &lt;text&gt;WHEREAS, the Philippines is a signatory or a party to various
                                international agreements on the seas and oceans. principally the
                                1982 United Nations Law of the Sea Convention (LOSC) which entered
                                into force on November 16, 1994, as well as non-binding instruments
                                such as the Rio Declaration and Agenda 21; &lt;/text&gt;
                            &lt;text&gt;WHEREAS, the seas and oceans have in recent times continually
                                increased in importance as the primary source of food, minerals,
                                petroleum and ocean energy, and other resources, as well as the
                                focus of many economic uses as transportation and tourism;&lt;/text&gt;
                            &lt;text&gt;WHEREAS, the present administration is resolutely committed to win
                                the battle against poverty in one decade and has directed all
                                concerned agencies to gear their programs to utilize marine and
                                other resources wisely and equitably towards achieving that
                                over-arching objective;&lt;/text&gt;
                            &lt;text&gt;WHEREAS, Cabinet Secretaries should do less cluster and
                                inter-agency committee work so that they can concentrate on running
                                their department;&lt;/text&gt;
                            &lt;text&gt;NOW, THEREFORE, I, GLORIA MACAPAGAL-ARROYO&lt;emph typestyle="it"
                                    &gt;,&lt;/emph&gt; President of the Philippines, by virtue of the powers
                                vested upon me by law, do hereby order:&lt;/text&gt;
                        &lt;/p&gt;
               &lt;/leg:bodytext&gt;
      &lt;/leg:levelbody&gt;
    
   </pre>
  </section>
  <p>
   Becomes
  </p>
  <section>
   <title>Target XML</title>
   <pre>

&lt;admindoc:bodytext&gt;
    &lt;p&gt;
        &lt;text&gt;WHEREAS, the Philippines is a signatory or a party to various
            international agreements on the seas and oceans. principally the
            1982 United Nations Law of the Sea Convention (LOSC) which entered
            into force on November 16, 1994, as well as non-binding instruments
            such as the Rio Declaration and Agenda 21; &lt;/text&gt;
        &lt;text&gt;WHEREAS, the seas and oceans have in recent times continually
            increased in importance as the primary source of food, minerals,
            petroleum and ocean energy, and other resources, as well as the
            focus of many economic uses as transportation and tourism;&lt;/text&gt;
        &lt;text&gt;WHEREAS, the present administration is resolutely committed to win
            the battle against poverty in one decade and has directed all
            concerned agencies to gear their programs to utilize marine and
            other resources wisely and equitably towards achieving that
            over-arching objective;&lt;/text&gt;
        &lt;text&gt;WHEREAS, Cabinet Secretaries should do less cluster and
            inter-agency committee work so that they can concentrate on running
            their department;&lt;/text&gt;
        &lt;text&gt;NOW, THEREFORE, I, GLORIA MACAPAGAL-ARROYO&lt;emph typestyle="it"
            &gt;,&lt;/emph&gt; President of the Philippines, by virtue of the powers
            vested upon me by law, do hereby order:&lt;/text&gt;
    &lt;/p&gt;
&lt;/admindoc:bodytext&gt;

   </pre>
  </section>
  
 </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\PH03-Regulation\GPL_PH03_leg-bodytext.dita  -->
	<xsl:message>GPL_PH03_leg-bodytext.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:levelbody/leg:bodytext">

		<!--  Original Target XPath:  admindoc:bodytext   -->
		<admindoc:bodytext>
			<xsl:apply-templates select="@* | node()"/>
		</admindoc:bodytext>

	</xsl:template>

	<xsl:template match="leg:bodytext">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>