<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.bodytext">
   <title>leg:bodytext <lnpid>id-IN01-15413</lnpid></title>
   <body>
      <section>
        <ul>
          <li class="- topic/li ">
            <sourcexml>leg:bodytext</sourcexml> becomes <targetxml>primlaw:bodytext</targetxml>.
          </li>
        </ul>
      </section>

           <example>
             <title>Source XML</title>
             <codeblock>

&lt;leg:bodytext&gt;
  &lt;pgrp&gt;
    &lt;p&gt;&lt;text&gt;An Act to amend the Farmers&amp;#x0027; Organization Act 1973.&lt;/text&gt;&lt;/p&gt;
    &lt;p&gt;&lt;text align="center"&gt;&amp;#x005B;1 November 1973&amp;#x005D;&lt;/text&gt;&lt;/p&gt;
  &lt;/pgrp&gt;
&lt;/leg:bodytext&gt;

                 </codeblock>
           </example>
           
           <example>
             <title>Target XML</title>
             <codeblock>

&lt;primlaw:bodytext&gt;
  &lt;pgrp&gt;
    &lt;p&gt;&lt;text&gt;An Act to amend the Farmers&amp;#x0027; Organization Act 1973.&lt;/text&gt;&lt;/p&gt;
    &lt;p&gt;&lt;text align="center"&gt;&amp;#x005B;1 November 1973&amp;#x005D;&lt;/text&gt;&lt;/p&gt;
  &lt;/pgrp&gt;
&lt;/primlaw:bodytext&gt;

             </codeblock>
           </example>
 <section>
       <title>Changes</title>
       <p>2014-03-21: <ph id="change_20140321_SSX">Created</ph>.</p>
 </section>
     </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\IN01_Legislation\leg.bodytext.dita  -->
	<xsl:message>IN01_Legislation_leg.bodytext.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:bodytext">

		<!--  Original Target XPath:  primlaw:bodytext   -->
		<primlaw:bodytext>
			<xsl:apply-templates select="@* | node()"/>
		</primlaw:bodytext>

	</xsl:template>

</xsl:stylesheet>