<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.info">
    <title>leg:info <lnpid>id-st07-31413</lnpid></title>
    <body>
        <section>
            <p><sourcexml>leg:info</sourcexml> becomes <targetxml>/funddoc:fundamentallegaldocument/funddoc:body/
                primlaw:level[@leveltype="unclassified"]/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo</targetxml> and create attribute <targetxml>primlaw:level[@leveltype="unclassified"]</targetxml>.The mappings for the children of <targetxml>leg:info</targetxml> are discussed as separate topics.</p>
           
            <pre>
  
&lt;leg:info&gt;
...
&lt;/leg:info&gt;
    
</pre>
            <b>Becomes</b>
            <pre>
      
&lt;primlaw:level leveltype="unclassified"&gt;
  &lt;primlaw:levelinfo&gt;
    &lt;primlawinfo:primlawinfo&gt;
        &lt;legisinfo:legisinfo&gt;
          ...
        &lt;/legisinfo:legisinfo&gt;
    &lt;/primlawinfo:primlawinfo&gt;
  &lt;/primlaw:levelinfo&gt;
&lt;/primlaw:level&gt;


</pre>
        </section>  
        <section>
            <title>Changes</title>
            
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\International_Instruments\leg.info.dita  -->
	<xsl:message>International_Instruments_leg.info.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:info">

		<!--  Original Target XPath:  /funddoc:fundamentallegaldocument/funddoc:body/primlaw:level[@leveltype="unclassified"]/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo   -->
		<funddoc:fundamentallegaldocument xmlns:funddoc="urn:x-lexisnexis:content:fundamentallegaldocument:sharedservices:1">
			<funddoc:body>
				<primlaw:level>
					<primlaw:levelinfo>
						<primlawinfo:primlawinfo xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/">
							<legisinfo:legisinfo xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/">
								<xsl:apply-templates select="@* | node()"/>
							</legisinfo:legisinfo>
						</primlawinfo:primlawinfo>
					</primlaw:levelinfo>
				</primlaw:level>
			</funddoc:body>
		</funddoc:fundamentallegaldocument>

	</xsl:template>

</xsl:stylesheet>