<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.heading">
    <title>leg:heading <lnpid>id-st07-31411</lnpid></title>
    <body>
        <section>
            <p>
                <ul>
                    <li><sourcexml>leg:heading</sourcexml> becomes <targetxml>heading</targetxml>
                        with attributes <sourcexml>@align</sourcexml> becames
                            <targetxml>@align</targetxml>
                        <sourcexml>@inline</sourcexml> becomes <targetxml>@inline</targetxml> which
                        has tokenized values and populated as: <ul>
                            <li><targetxml>heading[@inline="true"]</targetxml></li>
                            <li><targetxml>heading[@inline="false"]</targetxml></li>
                        </ul>
                        <note>For handling <b>@ln.user-displayed</b> attribute, refer the general
                            markup <xref href="../../common_newest/Rosetta_leg.heading_ln.user-displayed.dita">ln.user_displayed="false"</xref> section in the CI.</note><pre>
 
&lt;leg:level id="IMM.IA.CRSR.BODY"&gt;
    &lt;leg:level-vrnt searchtype="LEGISLATION TREATY-CONV" leveltype="treaty-conv"&gt;
        &lt;leg:heading&gt;
          &lt;title searchtype="CONV-TITLE"&gt;
            &lt;refpt id="IMM.IA.CRSR" type="ext"&gt;&lt;/refpt&gt;Convention Relating to the Status of Refugees of 28 July 1951&lt;/title&gt;
        &lt;/leg:heading&gt;
        .......
    &lt;/leg:level-vrnt&gt;
 &lt;/leg:level&gt;

</pre>
                        <b>Becomes</b>
                        <pre>

&lt;primlaw:level xml:id="IMM.IA.CRSR.BODY" leveltype="treaty"&gt;
     &lt;ref:anchor id="IMM.IA.CRSR" anchortype="global"/&gt;
        &lt;heading&gt;
            &lt;title&gt;Convention Relating to the Status of Refugees of 28 July 1951&lt;/title&gt;
        &lt;/heading&gt;
        ......
&lt;/primlaw:level&gt;

</pre>
                        <p>heading element with <sourcexml>@inline</sourcexml> attribute</p>
                        <pre>

 &lt;leg:level id="IMM.IA.CRSR.ART7.1"&gt;
      &lt;leg:level-vrnt searchtype="LEGISLATION SUBARTICLE" leveltype="subarticle"&gt;
           &lt;leg:heading inline="true"&gt;
               &lt;desig&gt;
                &lt;designum&gt;
                  &lt;refpt id="IMM.IA.CRSR.ART7.1" type="ext"&gt;&lt;/refpt&gt;1&lt;/designum&gt;
               &lt;/desig&gt;
          &lt;/leg:heading&gt;
          ........
      &lt;/leg:level-vrnt&gt;
 &lt;/leg:level&gt;
              
            </pre>
                        <b>Becomes</b>
                        <pre>

&lt;primlaw:level leveltype="subarticle"&gt;
     &lt;ref:anchor id="IMM.IA.CRSR.ART7.1" anchortype="global"/&gt;
            &lt;heading inline="true"&gt;
              &lt;desig&gt;1&lt;/desig&gt;
            &lt;/heading&gt;
       ....... 
&lt;/primlaw:level&gt;
            
</pre>
                    </li>
                </ul>
            </p>  
        </section>  
        <section>
            <title>Changes</title>
            
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\International_Instruments\leg.heading.dita  -->
	<xsl:message>International_Instruments_leg.heading.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:heading">

		<!--  Original Target XPath:  heading   -->
		<heading>
			<xsl:apply-templates select="@* | node()"/>
		</heading>

	</xsl:template>

	<xsl:template match="@align">

		<!--  Original Target XPath:  @align   -->
		<xsl:attribute name="align">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="@inline">

		<!--  Original Target XPath:  @inline   -->
		<xsl:attribute name="inline">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

</xsl:stylesheet>