<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.officialname">
    <title>leg:officialname <lnpid>id-st07-31417</lnpid></title>
    <body>
        <section>
            <p><sourcexml>/LEGDOC/leg:body/leg:info/leg:officialname</sourcexml> becomes
                    <targetxml>/funddoc:fundamentallegaldocument/
                    funddoc:body/primlaw:level[@leveltype="unclassified"]/primlaw:levelinfo/primlawinfo:primlawinfo/
                    legisinfo:legisinfo/legisinfo:names/legisinfo:officialtitle</targetxml>,attribute
                @searchtype will be suppressed. Conversion will be populated as below: <pre>
  
&lt;leg:body&gt;
    &lt;leg:info&gt;
        &lt;leg:officialname searchtype="LEGISLATION"&gt;The Hague Agreement
            concerning the international registration of industrial designs&lt;/leg:officialname&gt;
    &lt;/leg:info&gt;
    ..........
    ..........
&lt;/leg:body&gt;
    
</pre>
                <b>Becomes</b>
                <pre>
      
&lt;funddoc:body&gt;
    &lt;primlaw:level leveltype="unclassified"&gt;
        &lt;primlaw:levelinfo&gt;
            &lt;primlawinfo:primlawinfo&gt;
                &lt;legisinfo:legisinfo&gt;
                    &lt;legisinfo:names&gt;
                        &lt;legisinfo:officialtitle&gt;The Hague Agreement concerning the international registration of industrial designs&lt;/legisinfo:officialtitle&gt;
                    &lt;/legisinfo:names&gt;
                &lt;/legisinfo:legisinfo&gt;
            &lt;/primlawinfo:primlawinfo&gt;
        &lt;/primlaw:levelinfo&gt;
    &lt;/primlaw:level&gt;
    ................
    ................
&lt;/funddoc:body&gt;


            </pre>
                <note>If Rosetta element <sourcexml>leg:officialname</sourcexml> contains attribute
                        <sourcexml>/leg:officialname[@ln.user-displayed="false"]</sourcexml>, then
                    please refer to General Markup instruction <xref href="../../common_newest/Rosetta_leg.officialname_ln.user-displayed-LxAdv-legisinfo.officialtitle.dita">ln.user_displayed="false"</xref> section in the CI.</note>
            </p>
        </section>  
        <section>
            <title>Changes</title>
            
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\International_Instruments\leg.officialname.dita  -->
	<xsl:message>International_Instruments_leg.officialname.xsl requires manual development!</xsl:message> 

	<xsl:template match="/LEGDOC/leg:body/leg:info/leg:officialname">

		<!--  Original Target XPath:  /funddoc:fundamentallegaldocument/funddoc:body/primlaw:level[@leveltype="unclassified"]/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo/legisinfo:names/legisinfo:officialtitle   -->
		<funddoc:fundamentallegaldocument xmlns:funddoc="urn:x-lexisnexis:content:fundamentallegaldocument:sharedservices:1">
			<funddoc:body>
				<primlaw:level xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/">
					<primlaw:levelinfo>
						<primlawinfo:primlawinfo xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/">
							<legisinfo:legisinfo xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/">
								<legisinfo:names>
									<legisinfo:officialtitle>
										<xsl:apply-templates select="@* | node()"/>
									</legisinfo:officialtitle>
								</legisinfo:names>
							</legisinfo:legisinfo>
						</primlawinfo:primlawinfo>
					</primlaw:levelinfo>
				</primlaw:level>
			</funddoc:body>
		</funddoc:fundamentallegaldocument>

	</xsl:template>

	<xsl:template match="leg:officialname">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="/leg:officialname[@ln.user-displayed=&#34;false&#34;]">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>