<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:admindoc="urn:x-lexisnexis:content:administrative-document:sharedservices:1" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.effdate-admindoc.effdate">
  <title>leg:effdate <lnpid>id-CN02-31816</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:dates/leg:effdate</sourcexml> becomes
          <targetxml>admindoc:effdate</targetxml> with attributes
          <targetxml>@year</targetxml><targetxml>@month</targetxml><targetxml>@day</targetxml>.</p>
    </section>
    <example>
      <title>Mapping of <sourcexml>leg:effdate</sourcexml></title>
      <codeblock>

  &lt;leg:dates&gt;
       &lt;leg:effdate&gt;2007-06-01&lt;/leg:effdate&gt;
&lt;/leg:dates&gt;

      </codeblock>
      <b>becomes</b>
      <codeblock>

 &lt;admindoc:effdate year="2007" day="01" month="06"&gt;2007-06-01&lt;/admindoc:effdate&gt;

       </codeblock>
    </example>
    <section>
      <title>Changes</title>
      <p>2014-05-05: <ph id="change_20140410_brt">Created</ph>.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\CN02-Regulations\leg.effdate_admindoc.effdate.dita  -->
	<xsl:message>leg.effdate_admindoc.effdate.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:dates/leg:effdate">

		<!--  Original Target XPath:  admindoc:effdate   -->
		<admindoc:effdate>
			<xsl:apply-templates select="@* | node()"/>
		</admindoc:effdate>

	</xsl:template>

	<xsl:template match="leg:effdate">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>