<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.comntry-source1">
 <title>Source XML 1 : <sourcexml>leg:level/leg:level-vrnt/leg:levelbody/leg:bodytext/leg:comntry</sourcexml></title>
  <body>
    <codeblock>

&lt;leg:body&gt;
 &lt;!-- ETC. --&gt;
 &lt;leg:level id="ASM.0257E.S7"&gt;
  &lt;leg:level-vrnt leveltype="sect" searchtype="LEGISLATION SECT" subdoc="true" toc-caption="7 Terms and conditions of order"&gt;
   &lt;leg:heading inline="true"&gt;
    &lt;desig inline="true" searchtype="SECT-NUM"&gt;
     &lt;designum&gt;7&lt;/designum&gt;
    &lt;/desig&gt;
    &lt;title inline="true" searchtype="SECT-TITLE"&gt;&lt;refpt id="ASM.0257E.S7" type="ext"/&gt;Terms and conditions of order&lt;/title&gt;
   &lt;/leg:heading&gt;
   &lt;leg:levelbody&gt;
    &lt;leg:bodytext&gt;
     &lt;!-- ETC. --&gt;
     &lt;leg:comntry subdoc="true" toc-caption="Commentary"&gt;
      &lt;level id="ASM.0257E.S7.COMNTRY_7-01" leveltype="para0"&gt;
       &lt;heading searchtype="COMMENTARY"&gt;
        &lt;edpnum ln.user-displayed="false"&gt;&lt;refpt id="ASM.0257E.S7.COMNTRY_7-01" type="ext"/&gt;7-01&lt;/edpnum&gt;
       &lt;/heading&gt;
       &lt;bodytext searchtype="COMMENTARY"&gt;
        &lt;!-- ETC. --&gt;
       &lt;/bodytext&gt;
      &lt;/level&gt;
      &lt;!-- ETC. --&gt;
     &lt;/leg:comntry&gt;
    &lt;/leg:bodytext&gt;
   &lt;/leg:levelbody&gt;
  &lt;/leg:level-vrnt&gt;
 &lt;/leg:level&gt;
&lt;/leg:body&gt;

    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY04-Annotated_legislation\leg.comntry-source1.dita  -->
	<xsl:message>leg.comntry-source1.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:level/leg:level-vrnt/leg:levelbody/leg:bodytext/leg:comntry">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>