<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:location="http://www.lexisnexis.com/xmlschemas/content/shared/location/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="docinfo.topiccode-pubinfo.pubdate">
    <title><sourcexml>leg:categories</sourcexml> to <targetxml>dc:coverage</targetxml>
        <lnpid>id-CN01-15226</lnpid></title>
    <body>
        <section>
            <title>Instructions</title>
            <p><sourcexml>leg:categories</sourcexml> becomes <targetxml>dc:coverage</targetxml> as
                    follows:<ul id="ul_m2x_2dv_14">
                    <li>Within  <targetxml>dc:coverage</targetxml>,  create
                            <targetxml>location:country</targetxml> with
                            <targetxml>@codescheme="ISO-3166-1"</targetxml> and
                            <targetxml>@countrycode="CN"/&gt;</targetxml>
                    </li>
                    <li><sourcexml>leg:categories/leg:heading/title</sourcexml> becomes
                            <targetxml>dc:coverage/location:region</targetxml>.</li>
                </ul></p>
        </section>

        <example>
            <title>Source XML</title>
            <codeblock>

&lt;leg:categories&gt;
   &lt;leg:heading searchtype="LEGISLATION"&gt;
       &lt;title&gt;NATIONAL&lt;/title&gt;
   &lt;/leg:heading&gt;
&lt;/leg:categories&gt;

	</codeblock>
        </example>

        <example>
            <title>Target XML</title>
            <codeblock>

&lt;dc:metadata&gt;
   &lt;dc:coverage&gt;
      &lt;location:country codescheme="ISO-3166-1" countrycode="CN"/&gt;
      &lt;location:region&gt;NATIONAL&lt;/location:region&gt;
  &lt;/dc:coverage&gt;
&lt;/dc:metadata&gt;

	</codeblock>
        </example> 
      </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\CN01-Legislation\leg.categories_dc.coverage.dita  -->
	<xsl:message>leg.categories_dc.coverage.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:categories">

		<!--  Original Target XPath:  dc:coverage   -->
		<dc:coverage>
			<xsl:apply-templates select="@* | node()"/>
		</dc:coverage>

	</xsl:template>

	<xsl:template match="leg:categories/leg:heading/title">

		<!--  Original Target XPath:  dc:coverage/location:region   -->
		<dc:coverage>
			<location:region>
				<xsl:apply-templates select="@* | node()"/>
			</location:region>
		</dc:coverage>

	</xsl:template>

</xsl:stylesheet>