<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.hier_leg.hierlev">
  <title>leg:hier <lnpid>id-ST04-26822</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:hier</sourcexml> and its child elements <sourcexml>leg:hierlev</sourcexml>
          mapping with <targetxml>doc:legacy-metadata/meta/metaitem</targetxml> and populated as below:</p>
        <note>The <sourcexml>leg:hierlev@leveltype</sourcexml> attribute will be dropped from conversion.</note>

      
    <pre>
            <b><i>Below snippet based on Canada content</i></b>
            
&lt;docinfo:hier&gt;
    &lt;docinfo:hierlev role="ancestor"&gt;
        &lt;heading&gt;
            &lt;title&gt;Apprenticeship and Industry Training Act&lt;/title&gt;
        &lt;/heading&gt;
        &lt;docinfo:hierlev role="ancestor"&gt;
            &lt;heading&gt;
                &lt;title&gt;STRUCTURAL STEEL AND PLATE FITTER TRADE REGULATION&lt;/title&gt;
            &lt;/heading&gt;
            &lt;docinfo:hierlev role="me"&gt;
                &lt;heading&gt;
                    &lt;title&gt;Table of Contents&lt;/title&gt;
                &lt;/heading&gt;
            &lt;/docinfo:hierlev&gt;
        &lt;/docinfo:hierlev&gt;
    &lt;/docinfo:hierlev&gt;
&lt;/docinfo:hier&gt;
&lt;!-...-&gt;
&lt;leg:hier&gt;
    &lt;leg:hierlev leveltype="2"&gt;Table of Contents&lt;/leg:hierlev&gt;
&lt;/leg:hier&gt;

    </pre>
        <pre>
            <b><i>Target Example</i></b>
            

&lt;doc:metadata&gt;
    &lt;doc:docinfo doc-content-country="CA"&gt;
        ...
        &lt;doc:legacy-metadata metadatasource="lbu-meta"&gt;
            &lt;meta&gt;
                &lt;metaitem name="leg:hierlev" value="Table of Contents"/&gt;
            &lt;/meta&gt;
        &lt;/doc:legacy-metadata&gt;
    &lt;/doc:docinfo&gt;
&lt;/doc:metadata&gt;

        
        </pre>    
<pre>
            <b><i>Source example based on UK content</i></b>
            
&lt;docinfo:hier&gt;
            &lt;docinfo:hierlev role="me"&gt;
                &lt;heading&gt;
                    &lt;title&gt;SCHEDULE&lt;/title&gt;
                &lt;/heading&gt;
            &lt;/docinfo:hierlev&gt;
&lt;/docinfo:hier&gt;
&lt;!-...-&gt;
&lt;leg:hier&gt;
    &lt;leg:hierlev searchtype="SCH-NUM"&gt;SCHEDULE&lt;/leg:hierlev&gt;
&lt;/leg:hier&gt;

</pre>
        <pre>
            <b><i>Target Example</i></b>
            

&lt;doc:metadata&gt;
    &lt;doc:docinfo doc-content-country="GB"&gt;
        ...
        &lt;doc:legacy-metadata metadatasource="lbu-meta"&gt;
            &lt;meta&gt;
                &lt;metaitem name="leg:hierlev" value="SCHEDULE"/&gt;
            &lt;/meta&gt;
        &lt;/doc:legacy-metadata&gt;
    &lt;/doc:docinfo&gt;
&lt;/doc:metadata&gt;


</pre>
    </section>
    <section>
      <title>Changes</title>
      <p>YYYY-MM-DD: ______________________________________________________________________.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Regulation\leg.hier_leg.hierlev.dita  -->
	<xsl:message>leg.hier_leg.hierlev.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:hier">

		<!--  Original Target XPath:  doc:legacy-metadata/meta/metaitem   -->
		<doc:legacy-metadata>
			<meta>
				<metaitem>
					<xsl:apply-templates select="@* | node()"/>
				</metaitem>
			</meta>
		</doc:legacy-metadata>

	</xsl:template>

	<xsl:template match="leg:hierlev">

		<!--  Original Target XPath:  doc:legacy-metadata/meta/metaitem   -->
		<doc:legacy-metadata>
			<meta>
				<metaitem>
					<xsl:apply-templates select="@* | node()"/>
				</metaitem>
			</meta>
		</doc:legacy-metadata>

	</xsl:template>

	<xsl:template match="leg:hierlev@leveltype">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>