<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.dates_leg.effdate">
  <title>leg:effdate <lnpid>id-MY05LL-17011</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:dates/leg:effdate</sourcexml> becomes
        <targetxml>primlawinfo:primlawinfo/primlawinfo:dates/primlawinfo:effdate</targetxml> with optional attributes <targetxml>@year</targetxml>, <targetxml>@month</targetxml> and <targetxml>@day</targetxml>.</p> 
      
    </section>
    <example>
      <title>Mapping of <sourcexml>leg:effdate</sourcexml></title>
      <codeblock>

&lt;leg:info&gt;
  &lt;leg:dates&gt;
      &lt;leg:effdate&gt;
        &lt;date&gt;1 June 2012&lt;/date&gt;
      &lt;/leg:effdate&gt;
  &lt;/leg:dates&gt;
&lt;/leg:info&gt;

      </codeblock>
      <b>becomes</b>
      <codeblock>

&lt;primlaw:levelinfo&gt;
   &lt;primlawinfo:primlawinfo&gt;
      &lt;primlawinfo:dates&gt;
        &lt;primlawinfo:effdate month="06" day="01" year="2012"&gt;
           &lt;date-text&gt;1 June 2012&lt;/date-text&gt;
        &lt;/primlawinfo:effdate&gt;
      &lt;/primlawinfo:dates&gt;
   &lt;/primlawinfo:primlawinfo&gt;
&lt;/primlaw:levelinfo&gt;

       </codeblock>
    </example>
 <section>
       <title>Changes</title>
       <p>2013-11-14: <ph id="change_20131114_SS">Created</ph>.</p>
</section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY05LL_Acts\leg.dates_leg.effdate.dita  -->
<!--	<xsl:message>leg.dates_leg.effdate.xsl requires manual development!</xsl:message> -->



  <xsl:template match="leg:dates/leg:effdate">
    <primlawinfo:effdate>
      <xsl:apply-templates select="./date/@*"/>     
      <xsl:apply-templates select="node()"/>      
    </primlawinfo:effdate>
  </xsl:template>
  
</xsl:stylesheet>