<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:leg="http://www.lexis-nexis.com/glp/leg"
	xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/"
	xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/"
	xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/" version="2.0"
	exclude-result-prefixes="#all">

		<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.info">
  <title>leg:info <lnpid>id-CA05-13619</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:info</sourcexml> becomes <targetxml>legis:legis/legis:head/primlawinfo:primlawinfo/legisinfo:legisinfo</targetxml>. The mappings for the children of <targetxml>leg:info</targetxml> are discussed as separate topics.</p>
      <note>The attribute <sourcexml>leg:info/@subseqdoc</sourcexml> will be suppressed from conversion.</note>
      <note>If the input documents is having no legislative information i.e. <sourcexml>leg:info</sourcexml> then conversion
      will create an empty output structure shown below:</note>
      
      <codeblock>
        
&lt;legis:head&gt;
    &lt;jurisinfo:legisbodyinfo&gt;
        &lt;jurisinfo:jurisdiction&gt;
            &lt;jurisinfoystem&gt;
                &lt;!--leg:info is not present in Document which creates Head part. As 'Head' is mandatory, creating empty head structure--&gt;
                &lt;/jurisinfoystem&gt;
        &lt;/jurisinfo:jurisdiction&gt;
    &lt;/jurisinfo:legisbodyinfo&gt;
&lt;/legis:head&gt;

      </codeblock>      
    </section>
    <section>
      <title>Changes</title>
      <p>2013-04-24: <ph id="change_20130424_VV">Added instruction and example for handling where document is having no legislative information i.e.leg:info.</ph></p>
    </section>    
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA05-ActsNew\leg.info.dita  -->
<!--	<xsl:message>leg.info.xsl requires manual development!</xsl:message> -->

<!--	<xsl:template match="leg:info">

		<!-\-  Original Target XPath:  legis:legis/legis:head/primlawinfo:primlawinfo/legisinfo:legisinfo   -\->
		<legis:legis>
			<legis:head>
				<primlawinfo:primlawinfo xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/">
					<legisinfo:legisinfo xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/">
						<xsl:apply-templates select="@* | node()"/>
					</legisinfo:legisinfo>
				</primlawinfo:primlawinfo>
			</legis:head>
		</legis:legis>

	</xsl:template>-->


	<xsl:template match="leg:info">
		<legis:head>
			<xsl:apply-templates select="child::leg:num"/>	
			<xsl:apply-templates select="child::leg:juris"/>
			<!--<xsl:if test="child::leg:history">
			<primlawinfo:primlawinfo>
				<xsl:apply-templates select="child::leg:history"/>
			</primlawinfo:primlawinfo>
			</xsl:if>-->
		</legis:head>
	</xsl:template>
</xsl:stylesheet>
