<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.year">
  <title>leg:year <lnpid>id-IN02-15622</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:year</sourcexml> becomes <targetxml>primlawinfo:primlawinfo/primlawinfo:dates/primlawinfo:enactdate</targetxml> with attribute <targetxml>@year</targetxml>. 
        </p> 
      
    </section>
    <example>
      <title>Mapping of <sourcexml>leg:year</sourcexml></title>
      <codeblock>

&lt;leg:year ln.user-displayed="false" searchtype="LEGISLATION"&gt;1961&lt;/leg:year&gt;

      </codeblock>
      <b>becomes</b>
      <codeblock>

 &lt;primlawinfo:primlawinfo&gt;
   &lt;primlawinfo:dates&gt;
      &lt;primlawinfo:enactdate year="1961"/&gt;
    &lt;/primlawinfo:dates&gt;
 &lt;/primlawinfo:primlawinfo&gt;   

       </codeblock>
    </example>  
   
    <note>For handling <b>@ln.user-displayed</b> attribute, refer the
      general markup <xref href="../../common_newest/Rosetta_leg.year_ln.user-displayed.dita">ln.user_displayed="false"</xref> section in the CI.</note>
    <note>The <sourcexml>@searchtype</sourcexml> attribute will be suppressed from conversion except for the citation element.</note>
 
  </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\IN02-Regulations\leg.year.dita  -->
	<xsl:message>leg.year.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:year">

		<!--  Original Target XPath:  primlawinfo:primlawinfo/primlawinfo:dates/primlawinfo:enactdate   -->
		<primlawinfo:primlawinfo>
			<primlawinfo:dates>
				<primlawinfo:enactdate>
					<xsl:apply-templates select="@* | node()"/>
				</primlawinfo:enactdate>
			</primlawinfo:dates>
		</primlawinfo:primlawinfo>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>