<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlawhist="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-history/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legis-leg.tableofamend">
 <title>leg:tableofamend <lnpid>id-ST03-26650</lnpid></title>
 <body>
  <section>
   <p><sourcexml>leg:tableofamend</sourcexml> becomes <targetxml>primlawhist:primlawhist/primlawhist:histgrp[@grptype="tableofamend"]/primlawhist:histitem/bodytext</targetxml></p>
   <note>Add the attribute value <targetxml>@grptype="tableofamend"</targetxml> to <targetxml>primlawhist:histgrp</targetxml></note>
   <p><sourcexml>leg:tableofamend/heading</sourcexml> becomes <targetxml>primlawhist:primlawhist/primlawhist:histgrp[@grptype="tableofamend"]/heading</targetxml></p>
  </section>
  <example>
   <title>CANADA SOURCE XML 1: Mapping of <sourcexml>leg:tableofamend</sourcexml></title>
   <codeblock>

&lt;leg:tableofamend&gt;
 &lt;p&gt;
  &lt;text&gt;
   &lt;verbatim verbatimclass="verbatim"&gt;** Editor's Table **&lt;nl/&gt;
    &lt;nl/&gt;
    Provision      Changed by     In force       Authority&lt;nl/&gt;
    &lt;nl/&gt;
    487.0911       2005 c25 s11   2008 Jan 1     SI/2007-108&lt;nl/&gt;
    *****
   &lt;/verbatim&gt;
  &lt;/text&gt;
 &lt;/p&gt;
&lt;/leg:tableofamend&gt;

   </codeblock>
   <b>Becomes</b>
   <title>CANADA TARGET XML 1: Mapping of <sourcexml>leg:tableofamend</sourcexml></title>
   <codeblock>

&lt;primlawhist:primlawhist&gt;
 &lt;primlawhist:histgrp grptype="tableofamend"&gt;
  &lt;primlawhist:histitem&gt;
   &lt;bodytext&gt;
    &lt;p&gt;
     &lt;text&gt;
      &lt;verbatim verbatimclass="verbatim"&gt;** Editor's Table **&lt;proc:nl/&gt;
       &lt;proc:nl/&gt;
       Provision      Changed by     In force       Authority&lt;proc:nl/&gt;
       &lt;proc:nl/&gt;
       487.0911       2005 c25 s11   2008 Jan 1     SI/2007-108&lt;proc:nl/&gt;
       *****
      &lt;/verbatim&gt;
     &lt;/text&gt;
    &lt;/p&gt;
   &lt;/bodytext&gt;
  &lt;/primlawhist:histitem&gt;
 &lt;/primlawhist:histgrp&gt;
&lt;/primlawhist:primlawhist&gt;

   </codeblock>
  </example>
  <example>
   <title>New Zealand SOURCE XML 2: Mapping of <sourcexml>leg:tableofamend/heading</sourcexml></title>
   <codeblock>

&lt;leg:tableofamend&gt;
 &lt;leg:heading&gt;
  &lt;title&gt;&lt;refpt id="VIC_ACT_1998-25_LEGHIST_PRE-YEAR" type="ext"/&gt;&lt;emph typestyle="bf"&gt;Pre-2000 Act&lt;/emph&gt;&lt;/title&gt;
 &lt;/leg:heading&gt;
 &lt;p&gt;
  &lt;text&gt;This Act history only includes events from 2000. Details of events affecting the Act before 2000 may be found in the &lt;remotelink refpt="VIC_ACT_1998-25_NOTES" dpsi="1111" docidref="EFGH_2468" remotekey1="REFPTID" service="DOC-ID"&gt;Notes&lt;/remotelink&gt; at the end of the Act.&lt;/text&gt;
 &lt;/p&gt;
&lt;/leg:tableofamend&gt;

   </codeblock>
   <b>Becomes</b>
   <title>New Zealand TARGET XML 2: Mapping of <sourcexml>leg:tableofamend/heading</sourcexml></title>
   <codeblock>

&lt;primlawhist:primlawhist&gt;
 &lt;primlawhist:histgrp grptype="tableofamend"&gt;
  &lt;ref:anchor id="VIC_ACT_1998-25_LEGHIST_PRE-YEAR" anchortype="global"/&gt;
  &lt;heading&gt;
   &lt;title&gt;&lt;emph typestyle="bf"&gt;Pre-2000 Act&lt;/emph&gt;&lt;/title&gt;
  &lt;/heading&gt;
  &lt;primlawhist:histitem&gt;
   &lt;bodytext&gt;
    &lt;p&gt;
     &lt;text&gt;This Act history only includes events from 2000. Details of events affecting the Act before 2000 may be found in the &lt;ref:crossreference crossreferencetype="seeAlso"&gt;&lt;ref:content&gt;Notes&lt;/ref:content&gt;&lt;ref:locator anchoridref="VIC_ACT_1998-25_NOTES"&gt;&lt;ref:locator-key&gt;&lt;ref:key-name name="DOC-ID"/&gt;&lt;ref:key-value value="1111-EFGH_2468"/&gt;&lt;/ref:locator-key&gt;&lt;/ref:locator&gt;&lt;/ref:crossreference&gt; at the end of the Act.&lt;/text&gt;
    &lt;/p&gt;
   &lt;/primlawhist:histitem&gt;
  &lt;/primlawhist:histgrp&gt;
&lt;/primlawhist:primlawhist&gt;

   </codeblock>
  </example>
  <section>
   <title>Changes</title>
   <p>2013-07-16: <ph id="change_20130716_SK">Instruction narrative edited for language; no changes to mappings, no impact to stylesheets.</ph></p>
   <p>2013-07-08: <ph id="change_20130708_AB">Created.</ph></p>
  </section>
 </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Legislation\legis-leg.tableofamend.dita  -->
	<xsl:message>legis-leg.tableofamend.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:tableofamend">

		<!--  Original Target XPath:  primlawhist:primlawhist/primlawhist:histgrp[@grptype="tableofamend"]/primlawhist:histitem/bodytext   -->
		<primlawhist:primlawhist>
			<primlawhist:histgrp>
				<primlawhist:histitem>
					<bodytext>
						<xsl:apply-templates select="@* | node()"/>
					</bodytext>
				</primlawhist:histitem>
			</primlawhist:histgrp>
		</primlawhist:primlawhist>

	</xsl:template>

	<xsl:template match="leg:tableofamend/heading">

		<!--  Original Target XPath:  primlawhist:primlawhist/primlawhist:histgrp[@grptype="tableofamend"]/heading   -->
		<primlawhist:primlawhist>
			<primlawhist:histgrp>
				<heading>
					<xsl:apply-templates select="@* | node()"/>
				</heading>
			</primlawhist:histgrp>
		</primlawhist:primlawhist>

	</xsl:template>

</xsl:stylesheet>