<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legis-leg.levelstatus">
 <title>leg:levelstatus <lnpid>id-ST03-26637</lnpid></title>
 <body>
  <section>
   <p>The conversion for <sourcexml>leg:levelstatus</sourcexml> is based on the following scenarios:
    <ul>
     <li>If <sourcexml>leg:level/leg:level-vrnt/leg:levelinfo/leg:levelstatus[@isrepealed="true"]</sourcexml> contains text it becomes <targetxml>primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo/legisinfo:statusgroup/legisinfo:status[@statuscode="repealed"]/legisinfo:statustext</targetxml>
      <note>Include the <targetxml>@statuscode</targetxml> in element <targetxml>legisinfo:status</targetxml> to represent repealed legislation.</note>
     </li>
    </ul>
   </p>
  </section>
  <example>
   <title>SOURCE XML 1 : Mapping for <sourcexml>leg:levelstatus</sourcexml> with text</title>
   <codeblock>
    
&lt;leg:level id="ABCE.LEG.ECN97.BODY"&gt;
 &lt;leg:level-vrnt searchtype="LEGISLATION ACT" leveltype="act"&gt;
  &lt;leg:levelinfo&gt;
   &lt;leg:levelstatus isrepealed="true"&gt;(Repealed)&lt;/leg:levelstatus&gt;
  &lt;/leg:levelinfo&gt;
  &lt;!-- ETC. --&gt;
 &lt;/leg:level-vrnt&gt;
&lt;/leg:level&gt;

   </codeblock>
   <b>Becomes</b>
   <title>TARGET XML 1 : Mapping for <sourcexml>leg:levelstatus</sourcexml> with text</title>
   <codeblock>
    
&lt;primlaw:level xml:id="ABCE.LEG.ECN97.BODY" leveltype="act"&gt;
 &lt;primlaw:levelinfo&gt;
  &lt;primlawinfo:primlawinfo&gt;
   &lt;legisinfo:legisinfo&gt;
    &lt;legisinfo:statusgroup&gt;
     &lt;legisinfo:status statuscode="repealed"&gt;
      &lt;legisinfo:statustext&gt;&amp;#x0028;Repealed&amp;#x0029;&lt;/legisinfo:statustext&gt;
     &lt;/legisinfo:status&gt;
    &lt;/legisinfo:statusgroup&gt;
   &lt;/legisinfo:legisinfo&gt;
  &lt;/primlawinfo:primlawinfo&gt;
 &lt;/primlaw:levelinfo&gt;
 &lt;!-- ETC. --&gt;
&lt;/primlaw:level&gt;

   </codeblock>
  </example>
  <section>
   <p>
    <ul>
     <li>If <sourcexml>leg:level/leg:levelinfo/leg:levelstatus[@isrepealed="true"]</sourcexml> does not contain text it becomes <targetxml>primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo/legisinfo:statusgroup/legisinfo:status[@statuscode="repealed"]</targetxml></li>
    </ul>
   </p>
  </section>
  <example>
   <title>SOURCE XML 1: Mapping for <sourcexml>leg:levelstatus</sourcexml> without text</title>
   <codeblock>
    
&lt;leg:level id="ACLL.SCRN.SCCR70.PT80.R5.4"&gt;
 &lt;leg:level-vrnt searchtype="LEGISLATION SUBRUL" leveltype="subrul"&gt;
  &lt;leg:levelinfo&gt;
   &lt;leg:levelstatus isrepealed="true"/&gt;
  &lt;/leg:levelinfo&gt;
  &lt;!-- ETC. --&gt;
 &lt;/leg:level-vrnt&gt;
&lt;/leg:level&gt;

   </codeblock>
   <b>Becomes</b>
   <title>TARGET XML 2: Mapping for <sourcexml>leg:levelstatus</sourcexml> with text</title>
   <codeblock>
    
&lt;primlaw:level xml:id="ACLL.SCRN.SCCR70.PT80.R5.4" leveltype="subrule"&gt;
 &lt;primlaw:levelinfo&gt;
  &lt;primlawinfo:primlawinfo&gt;
   &lt;legisinfo:legisinfo&gt;
    &lt;legisinfo:statusgroup&gt;
     &lt;legisinfo:status statuscode="repealed"/&gt;
    &lt;/legisinfo:statusgroup&gt;
   &lt;/legisinfo:legisinfo&gt;
  &lt;/primlawinfo:primlawinfo&gt;
 &lt;/primlaw:levelinfo&gt;
 &lt;!-- ETC. --&gt;
&lt;/primlaw:level&gt;

   </codeblock>
  </example>
  <section>
   <p>
    <ul>
     <li>If <sourcexml>leg:levelstatus[@isrepealed="false"]</sourcexml> then supress the element.</li>
    </ul>
   </p>
  </section>
  <section>
    <title>Changes</title>
   <p>2013-07-16: <ph id="change_20130716_SK">Instruction narrative edited for language; no changes to mappings, no impact to stylesheets.</ph></p>
    <p>2013-07-08: <ph id="change_20130708_AB">Created.</ph></p>
   </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Legislation\legis-leg.levelstatus.dita  -->
	<xsl:message>legis-leg.levelstatus.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:levelstatus">

		<!--  Original Target XPath:  primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo/legisinfo:statusgroup/legisinfo:status[@statuscode="repealed"]/legisinfo:statustext   -->
		<primlaw:level>
			<primlaw:levelinfo>
				<primlawinfo:primlawinfo xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/">
					<legisinfo:legisinfo>
						<legisinfo:statusgroup>
							<legisinfo:status>
								<legisinfo:statustext>
									<xsl:apply-templates select="@* | node()"/>
								</legisinfo:statustext>
							</legisinfo:status>
						</legisinfo:statusgroup>
					</legisinfo:legisinfo>
				</primlawinfo:primlawinfo>
			</primlaw:levelinfo>
		</primlaw:level>

	</xsl:template>

	<xsl:template match="leg:level/leg:level-vrnt/leg:levelinfo/leg:levelstatus[@isrepealed=&#34;true&#34;]">

		<!--  Original Target XPath:  primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo/legisinfo:statusgroup/legisinfo:status[@statuscode="repealed"]/legisinfo:statustext   -->
		<primlaw:level>
			<primlaw:levelinfo>
				<primlawinfo:primlawinfo xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/">
					<legisinfo:legisinfo>
						<legisinfo:statusgroup>
							<legisinfo:status>
								<legisinfo:statustext>
									<xsl:apply-templates select="@* | node()"/>
								</legisinfo:statustext>
							</legisinfo:status>
						</legisinfo:statusgroup>
					</legisinfo:legisinfo>
				</primlawinfo:primlawinfo>
			</primlaw:levelinfo>
		</primlaw:level>

	</xsl:template>

	<xsl:template match="leg:level/leg:levelinfo/leg:levelstatus[@isrepealed=&#34;true&#34;]">

		<!--  Original Target XPath:  primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo/legisinfo:statusgroup/legisinfo:status[@statuscode="repealed"]   -->
		<primlaw:level>
			<primlaw:levelinfo>
				<primlawinfo:primlawinfo xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/">
					<legisinfo:legisinfo>
						<legisinfo:statusgroup>
							<legisinfo:status>
								<xsl:apply-templates select="@* | node()"/>
							</legisinfo:status>
						</legisinfo:statusgroup>
					</legisinfo:legisinfo>
				</primlawinfo:primlawinfo>
			</primlaw:levelinfo>
		</primlaw:level>

	</xsl:template>

	<xsl:template match="leg:levelstatus[@isrepealed=&#34;false&#34;]">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>