<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legis-leg.companion">
 <title>leg:companion <lnpid>id-ST03-26619</lnpid></title>
  <body>
    <section>
     <p><sourcexml>leg:companion</sourcexml> becomes <targetxml>primlaw:level</targetxml> with <targetxml>@leveltype="companion"</targetxml>.</p>
    </section>
    <example>
     <title>AUSTRALIA SOURCE XML 1: Mapping of <sourcexml>leg:companion</sourcexml></title>
      <codeblock>

&lt;leg:companion searchtype="LEGISLATION"&gt;
 &lt;leg:level id="QLD_ACT_1895-15_SD1"&gt;
  &lt;leg:level-vrnt leveltype="subdoc" subdoc="true" toc-caption="Anglican Church of Australia Act 1895 Amendment Act 1901"&gt;
   &lt;leg:heading&gt;
    &lt;title align="center"&gt;
     &lt;emph typestyle="bf"&gt;Anglican Church of Australia Act 1895 Amendment Act 1901&lt;/emph&gt;
    &lt;/title&gt;
   &lt;/leg:heading&gt;
   &lt;leg:levelbody&gt;
    &lt;leg:bodytext searchtype="LEGISLATION"&gt;
     &lt;refpt id="QLD_ACT_1895-15_COMP1" type="ext"/&gt;
     &lt;refpt id="QLD_ACT_1895-15_SD1" type="ext"/&gt;
     &lt;p&gt;&lt;text&gt;Queensland&lt;/text&gt;&lt;/p&gt;&lt;p&gt;&lt;text&gt;[shield]&lt;/text&gt;&lt;/p&gt;
     &lt;h&gt;&lt;emph typestyle="bf"&gt;Anglican Church of Australia Act 1895 Amendment Act 1901&lt;/emph&gt;&lt;/h&gt;
    &lt;/leg:bodytext&gt;
   &lt;/leg:levelbody&gt;
  &lt;/leg:level-vrnt&gt;
 &lt;/leg:level&gt;
&lt;/leg:companion&gt;

      </codeblock>
      <b>Becomes</b>
     <title>AUSTRALIA TARGET XML 1: Mapping of <sourcexml>leg:companion</sourcexml></title>
     <codeblock>

&lt;primlaw:level leveltype="companion"&gt;
 &lt;primlaw:level leveltype="unclassified" includeintoc="true" alternatetoccaption="Anglican Church of Australia Act 1895 Amendment Act 1901"&gt;
  &lt;ref:anchor id="QLD_ACT_1895-15_COMP1" anchortype="global"/&gt;
  &lt;ref:anchor id="QLD_ACT_1895-15_SD1" anchortype="global"/&gt;
  &lt;heading&gt;
   &lt;title align="center"&gt;Anglican Church of Australia Act 1895 Amendment Act 1901&lt;/title&gt;
  &lt;/heading&gt;
  &lt;primlaw:bodytext&gt;
   &lt;p&gt;&lt;text&gt;Queensland&lt;/text&gt;&lt;/p&gt;&lt;p&gt;&lt;text&gt;[shield]&lt;/text&gt;&lt;/p&gt;
   &lt;h&gt;Anglican Church of Australia Act 1895 Amendment Act 1901&lt;/h&gt;
  &lt;/primlaw:bodytext&gt;
 &lt;/primlaw:level&gt;
&lt;/primlaw:level&gt;

     </codeblock>
    </example>
   <section>
    <title>Changes</title>
    <p>2013-07-16: <ph id="change_20130716_SK">Instruction narrative edited for language; no changes to mappings, no impact to stylesheets.</ph></p>
    
    <p>2013-07-08: <ph id="change_20130708_AB">Created.</ph></p>
   </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Legislation\legis-leg.companion.dita  -->
	<xsl:message>legis-leg.companion.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:companion">

		<!--  Original Target XPath:  primlaw:level   -->
		<primlaw:level>
			<xsl:apply-templates select="@* | node()"/>
		</primlaw:level>

	</xsl:template>

</xsl:stylesheet>