<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.revisedate">
  <title>leg:revisedate <lnpid>id-ST03-26647</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:revisedate</sourcexml> becomes <targetxml>primlawinfo:amenddate</targetxml>.
        <ul>
          <li><sourcexml>date</sourcexml> becomes <targetxml>date-text</targetxml> and the attributes will be moved in the parent <targetxml>primlawinfo:amenddate</targetxml> element and populated as below:
            <ul>
              <li><sourcexml>date/@day</sourcexml> becomes <targetxml>primlawinfo:amenddate/@day</targetxml></li>
              <li><sourcexml>date/@month</sourcexml> becomes <targetxml>primlawinfo:amenddate/@month</targetxml></li>
              <li><sourcexml>date/@year</sourcexml> becomes <targetxml>primlawinfo:amenddate/@year</targetxml></li>
            </ul>
          </li>
        </ul>
       <note>The formatting of the <targetxml>date-text</targetxml> should not be normalized to <b>YYYY-MM-DD</b>. The attributes are used for normalization, but the element <targetxml>primlawinfo:amenddate</targetxml> content should remain the same.</note>
        <note>Multiple <sourcexml>date</sourcexml> elements occuring within <sourcexml>leg:revisedate</sourcexml> are mark-up errors and only the element around the actual date text will be used in conversion. Remaining <sourcexml>date</sourcexml> elements will be suppressed (not content) from conversion.</note>
        <note>If <sourcexml>leg:revisedate</sourcexml> has only PCDTA then convert <sourcexml>leg:revisedate</sourcexml> into <targetxml>primlawinfo:amenddate</targetxml>.</note>
      </p>
    </section>
    <example>
     <title>CANADA SOURCE XML 1: Mapping of <sourcexml>leg:revisedate</sourcexml></title>
     <codeblock>

&lt;leg:body&gt;
 &lt;leg:info subseqdoc="false"&gt;
  &lt;!-- ETC. --&gt;
  &lt;leg:dates&gt;
   &lt;leg:currencydate&gt;&lt;/leg:currencydate&gt;
   &lt;leg:revisedate&gt;Last changed: &lt;date year="2012" month="02" day="07"&gt;7 February 2012&lt;/date&gt;&lt;/leg:revisedate&gt;
  &lt;/leg:dates&gt;
  &lt;!-- ETC. --&gt;
 &lt;/leg:info&gt;
 &lt;!-- ETC. --&gt;
&lt;/leg:body&gt; 

     </codeblock>
     <b>Becomes</b>
     <title>CANADA TARGET XML 1: Mapping of <sourcexml>leg:revisedate</sourcexml></title>
     <codeblock>

&lt;legis:head&gt;
 &lt;primlawinfo:primlawinfo&gt;
  &lt;!-- ETC. --&gt;
  &lt;primlawinfo:dates&gt;
   &lt;primlawinfo:amenddate year="2012" month="02" day="07"&gt;Last changed:
    &lt;date-text&gt;7 February 2012&lt;/date-text&gt;
   &lt;/primlawinfo:amenddate&gt;
  &lt;/primlawinfo:dates&gt;
  &lt;!-- ETC. --&gt;
 &lt;/primlawinfo:primlawinfo&gt;
&lt;/legis:head&gt;
&lt;legis:body&gt;
 &lt;!-- ETC. --&gt;
&lt;/legis:body&gt;

    </codeblock>
    </example>
   <section>
    <title>Changes</title>
    <p>2013-08-14: <ph id="change_20130814_AB">Instruction narrative edited for language; no changes to mappings, no impact to stylesheets.</ph></p>
    <p>2013-07-16: <ph id="change_20130716_SK">Instruction narrative edited for language; no changes to mappings, no impact to stylesheets.</ph></p>
    <p>2013-07-08: <ph id="change_20130708_AB">Created.</ph></p>
   </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Legislation\legis-leg.revisedate.dita  -->
	<xsl:message>legis-leg.revisedate.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:revisedate">

		<!--  Original Target XPath:  primlawinfo:amenddate   -->
		<primlawinfo:amenddate>
			<xsl:apply-templates select="@* | node()"/>
		</primlawinfo:amenddate>

	</xsl:template>

	<xsl:template match="date">

		<!--  Original Target XPath:  date-text   -->
		<date-text>
			<xsl:apply-templates select="@* | node()"/>
		</date-text>

	</xsl:template>

	<xsl:template match="date/@day">

		<!--  Original Target XPath:  primlawinfo:amenddate/@day   -->
		<primlawinfo:amenddate>
			<xsl:attribute name="day">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</primlawinfo:amenddate>

	</xsl:template>

	<xsl:template match="date/@month">

		<!--  Original Target XPath:  primlawinfo:amenddate/@month   -->
		<primlawinfo:amenddate>
			<xsl:attribute name="month">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</primlawinfo:amenddate>

	</xsl:template>

	<xsl:template match="date/@year">

		<!--  Original Target XPath:  primlawinfo:amenddate/@year   -->
		<primlawinfo:amenddate>
			<xsl:attribute name="year">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</primlawinfo:amenddate>

	</xsl:template>

</xsl:stylesheet>