<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legis-leg.endmatter">
 <title>leg:endmatter <lnpid>id-ST03-26625</lnpid></title>
  <body>
    <section>
     <p><sourcexml>/LEGDOC/leg:body/leg:endmatter</sourcexml> becomes <targetxml>legis:legis/legis:body/primlaw:level</targetxml> with <targetxml>@leveltype="endnote"</targetxml>.
      <ul>
       <li><sourcexml>leg:level/leg:level-vrnt</sourcexml> becomes <targetxml>primlaw:level</targetxml> with attribute <targetxml>@leveltype</targetxml></li>
      </ul>
     </p>
    </section>
    <example>
      <title>AUSTRALIA SOURCE XML 1: Mapping of <sourcexml>leg:endmatter</sourcexml></title>
      <codeblock>

&lt;leg:endmatter&gt;
 &lt;leg:level id="NSW_ACT_2009-1_NOTES"&gt;
  &lt;leg:level-vrnt leveltype="notes" subdoc="true" toc-caption="Historical notes"&gt;
   &lt;leg:heading&gt;
    &lt;title align="left"&gt;&lt;refpt id="NSW_ACT_2009-1_NOTES" type="ext"/&gt;Historical notes&lt;/title&gt;
   &lt;/leg:heading&gt;
   &lt;leg:levelbody&gt;
    &lt;leg:bodytext&gt;
     &lt;p&gt;
      &lt;text&gt;The following abbreviations are used in the Historical notes:&lt;/text&gt;
      &lt;table&gt;
       &lt;tgroup cols="6"&gt;
        &lt;colspec colwidth="12*" colname="c1"/&gt;
        &lt;colspec colwidth="12*" colname="c2"/&gt;
        &lt;colspec colwidth="12*" colname="c3"/&gt;
        &lt;colspec colwidth="12*" colname="c4"/&gt;
        &lt;colspec colwidth="12*" colname="c5"/&gt;
        &lt;colspec colwidth="12*" colname="c6"/&gt;
        &lt;tbody&gt;
         &lt;row&gt;
          &lt;entry colname="c1"&gt;Am&lt;/entry&gt;
          &lt;entry colname="c2"&gt;amended&lt;/entry&gt;
          &lt;entry colname="c3"&gt;LW&lt;/entry&gt;
          &lt;entry colname="c4"&gt;legislation website&lt;/entry&gt;
          &lt;entry colname="c5"&gt;Sch&lt;/entry&gt;
          &lt;entry colname="c6"&gt;Schedule&lt;/entry&gt;
         &lt;/row&gt;
         &lt;!-- ETC. --&gt;
        &lt;/tbody&gt;
       &lt;/tgroup&gt;
      &lt;/table&gt;
     &lt;/p&gt;
    &lt;/leg:bodytext&gt;
   &lt;/leg:levelbody&gt;
  &lt;/leg:level-vrnt&gt;
 &lt;/leg:level&gt;
&lt;/leg:endmatter&gt;

      </codeblock>
     <b>Becomes</b>
     <title>AUSTRALIA TARGET XML 1: Mapping of <sourcexml>leg:endmatter</sourcexml></title>
     <codeblock>

&lt;primlaw:level leveltype="endnote"&gt;
 &lt;primlaw:level leveltype="endnote" includeintoc="true" alternatetoccaption="Historical notes"&gt;
  &lt;ref:anchor id="SW_ACT_2009-1_NOTES" anchortype="global"/&gt;
  &lt;heading&gt;
   &lt;title align="left"&gt;Historical notes&lt;/title&gt;
  &lt;/heading&gt;
  &lt;primlaw:bodytext&gt;
   &lt;p&gt;
    &lt;text&gt;The following abbreviations are used in the Historical notes:&lt;/text&gt;
    &lt;table&gt;
     &lt;tgroup cols="6"&gt;
      &lt;colspec colwidth="12*" colname="c1"/&gt;
      &lt;colspec colwidth="12*" colname="c2"/&gt;
      &lt;colspec colwidth="12*" colname="c3"/&gt;
      &lt;colspec colwidth="12*" colname="c4"/&gt;
      &lt;colspec colwidth="12*" colname="c5"/&gt;
      &lt;colspec colwidth="12*" colname="c6"/&gt;
      &lt;tbody&gt;
       &lt;row&gt;
        &lt;entry colname="c1"&gt;Am&lt;/entry&gt;
        &lt;entry colname="c2"&gt;amended&lt;/entry&gt;
        &lt;entry colname="c3"&gt;LW&lt;/entry&gt;
        &lt;entry colname="c4"&gt;legislation website&lt;/entry&gt;
        &lt;entry colname="c5"&gt;Sch&lt;/entry&gt;
        &lt;entry colname="c6"&gt;Schedule&lt;/entry&gt;
       &lt;/row&gt;
       &lt;!-- ETC. --&gt;
      &lt;/tbody&gt;
     &lt;/tgroup&gt;
    &lt;/table&gt;
   &lt;/p&gt;
  &lt;/primlaw:bodytext&gt;
 &lt;/primlaw:level&gt;
&lt;/primlaw:level&gt;

      </codeblock>
     <note>Refer to <xref href="../../common_newest/Rosetta_refpt-Chof-leg.endmatter_index_heading_title-LxAdv-primlaw.level_ref.anchor.dita">refpt</xref> for handling of the same.</note>
    </example>
   <section>
    <title>Changes</title>
    <p>2013-07-16: <ph id="change_20130716_SK">Instruction narrative edited for language; no changes to mappings, no impact to stylesheets.</ph></p>
    
    <p>2013-07-08: <ph id="change_20130708_AB">Created.</ph></p>
   </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Legislation\legis-leg.endmatter.dita  -->
	<xsl:message>legis-leg.endmatter.xsl requires manual development!</xsl:message> 

	<xsl:template match="/LEGDOC/leg:body/leg:endmatter">

		<!--  Original Target XPath:  legis:legis/legis:body/primlaw:level   -->
		<legis:legis>
			<legis:body>
				<primlaw:level>
					<xsl:apply-templates select="@* | node()"/>
				</primlaw:level>
			</legis:body>
		</legis:legis>

	</xsl:template>

	<xsl:template match="leg:level/leg:level-vrnt">

		<!--  Original Target XPath:  primlaw:level   -->
		<primlaw:level>
			<xsl:apply-templates select="@* | node()"/>
		</primlaw:level>

	</xsl:template>

	<xsl:template match="leg:endmatter">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>