<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legis-leg.longtitle">
 <title>leg:longtitle <lnpid>id-ST03-26638</lnpid></title>
 <body>
  <section>
   <p><sourcexml>leg:longtitle</sourcexml> becomes <targetxml>primlaw:prelim/primlaw:synopsis</targetxml> with child as <targetxml>bodytext</targetxml>.
    <note>The target element <targetxml>primlaw:prelim/primlaw:synopsis</targetxml> is coming under <targetxml>legis:body</targetxml> and not in <targetxml>legis:head/primlawinfo:primlawinfo/legisinfo:legisinfo</targetxml>.</note>
   </p>
  </section>
  <example>
   <title>UK SOURCE XML 1: Mapping of <sourcexml>leg:longtitle</sourcexml></title>
   <codeblock>

&lt;leg:body&gt;
 &lt;leg:info subseqdoc="false"&gt;
  &lt;!-- ETC. --&gt;
  &lt;leg:longtitle align="left"&gt;
   &lt;p&gt;&lt;text&gt;&lt;emph typestyle="it"&gt;&lt;emph typestyle="it"&gt;STATUTES &lt;emph typestyle="smcaps"&gt;OF&lt;/emph&gt; KING EDWARD Made at WESTMINSTER in his PARLIAMENT, at EASTER, in the THIRTEENTH YEAR of his Reign&lt;/emph&gt;&lt;/emph&gt;&lt;/text&gt;&lt;/p&gt;
  &lt;/leg:longtitle&gt;
  &lt;!-- ETC. --&gt;
 &lt;/leg:info&gt;
 &lt;!-- ETC. --&gt;
&lt;/leg:body&gt;

   </codeblock>
   <b>Becomes</b>
   <title>UK TARGET XML 1: Mapping of <sourcexml>leg:longtitle</sourcexml></title>
   <codeblock>

&lt;legis:head&gt;
 &lt;primlawinfo:primlawinfo&gt;
  &lt;legisinfo:legisinfo&gt;
   &lt;!-- ETC. --&gt;
  &lt;/legisinfo:legisinfo&gt;
 &lt;/primlawinfo:primlawinfo&gt;
&lt;/legis:head&gt;
&lt;legis:body&gt;
 &lt;primlaw:prelim&gt;
  &lt;primlaw:synopsis&gt;
   &lt;bodytext&gt;
    &lt;p&gt;&lt;text&gt;&lt;emph typestyle="it"&gt;&lt;emph typestyle="it"&gt;STATUTES &lt;emph typestyle="smcaps"&gt;OF&lt;/emph&gt; KING EDWARD Made at WESTMINSTER in his PARLIAMENT, at EASTER, in the THIRTEENTH YEAR of his Reign&lt;/emph&gt;&lt;/emph&gt;&lt;/text&gt;&lt;/p&gt;
   &lt;/bodytext&gt;
  &lt;/primlaw:synopsis&gt;
 &lt;/primlaw:prelim&gt;
 &lt;!-- ETC. --&gt;
&lt;/legis:body&gt;

   </codeblock>
  </example>
  <example>
   <title>AUSTRALIA SOURCE XML 2: Mapping of <sourcexml>leg:longtitle/glp:note</sourcexml></title>
   <codeblock>

&lt;leg:longtitle searchtype="LEGISLATION"&gt;
 &lt;glp:note&gt;
  &lt;heading&gt;
   &lt;title align="left"&gt;Editorial note.&lt;/title&gt;
  &lt;/heading&gt;
  &lt;p&gt;
   &lt;text&gt;&lt;emph typestyle="it"&gt;The long title was repealed by the &lt;emph typestyle="it"&gt;Marine Safety Act 1998&lt;/emph&gt;.&lt;/emph&gt;&lt;/text&gt;
  &lt;/p&gt;
 &lt;/glp:note&gt;
&lt;/leg:longtitle&gt;

   </codeblock>
   <b>Becomes</b>
   <title>AUSTRALIA TARGET XML 2: Mapping of <sourcexml>leg:longtitle/glp:note</sourcexml></title>
   <codeblock>
   
&lt;primlaw:prelim&gt;
 &lt;primlaw:synopsis&gt;
  &lt;bodytext&gt;
   &lt;note&gt;
    &lt;heading&gt;
     &lt;title align="left"&gt;Editorial note.&lt;/title&gt;
    &lt;/heading&gt;
    &lt;bodytext&gt;
     &lt;p&gt;
      &lt;text&gt;&lt;emph typestyle="it"&gt;The long title was repealed by the &lt;emph typestyle="it"&gt;Marine Safety Act 1998&lt;/emph&gt;.&lt;/emph&gt;&lt;/text&gt;
     &lt;/p&gt;
    &lt;/bodytext&gt;
   &lt;/note&gt;
  &lt;/bodytext&gt;
 &lt;/primlaw:synopsis&gt;
&lt;/primlaw:prelim&gt;

   </codeblock>
  </example>
  <section>
   <title>Changes</title>
   <p>2013-07-16: <ph id="change_20130716_SK">Instruction narrative edited for language; no changes to mappings, no impact to stylesheets.</ph></p>
   <p>2013-07-08: <ph id="change_20130708_AB">Created.</ph></p>
  </section>
 </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Legislation\legis-leg.longtitle.dita  -->
	<xsl:message>legis-leg.longtitle.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:longtitle">

		<!--  Original Target XPath:  primlaw:prelim/primlaw:synopsis   -->
		<primlaw:prelim>
			<primlaw:synopsis>
				<xsl:apply-templates select="@* | node()"/>
			</primlaw:synopsis>
		</primlaw:prelim>

	</xsl:template>

	<xsl:template match="leg:longtitle/glp:note">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>