<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:statcode="http://www.lexisnexis.com/xmlschemas/content/legal/statutorycode/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.dates">
  <title>leg:dates <lnpid>id-MX03-34210</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:info/leg:dates</sourcexml> becomes
                    <targetxml>statcode:body/primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/primlawinfo:dates</targetxml></p>

    </section>
    <example>
            <title>SOURCE XML 1: Mapping of <sourcexml>leg:dates</sourcexml></title>
            <codeblock>

&lt;leg:body&gt;
    &lt;leg:info&gt;
        &lt;leg:dates&gt;
            &lt;!-- ... --&gt;
        &lt;/leg:dates&gt;
    &lt;/leg:info&gt;
&lt;/leg:body&gt;

      </codeblock>
            <b>Becomes</b>
            <title>SOURCE XML 1: Mapping of <sourcexml>leg:dates</sourcexml></title>
            <codeblock>

&lt;statcode:body&gt;
    &lt;primlaw:level leveltype="unclassified"&gt;
           &lt;primlaw:levelinfo&gt;
              &lt;primlawinfo:primlawinfo&gt;
                  &lt;primlawinfo:dates&gt;
                        &lt;!-- ... --&gt;
                  &lt;/primlawinfo:dates&gt;
              &lt;/primlawinfo:primlawinfo&gt;
        &lt;/primlaw:levelinfo&gt;
    &lt;/primlaw:level&gt;
&lt;/statcode:body&gt;

        </codeblock>
        </example>
    <section>
      <title>Changes:</title>
      <p>2014-10-13: Created</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\MX03-Statcode\leg.dates.dita  -->
	<xsl:message>MX03-Statcode_leg.dates.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:info/leg:dates">

		<!--  Original Target XPath:  statcode:body/primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/primlawinfo:dates   -->
		<statcode:body>
			<primlaw:level xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/">
				<primlaw:levelinfo>
					<primlawinfo:primlawinfo xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/">
						<primlawinfo:dates>
							<xsl:apply-templates select="@* | node()"/>
						</primlawinfo:dates>
					</primlawinfo:primlawinfo>
				</primlaw:levelinfo>
			</primlaw:level>
		</statcode:body>

	</xsl:template>

	<xsl:template match="leg:dates">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>