<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.officialnum">
  <title>leg:officialnum <lnpid>id-MY06-17222</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:info/leg:officialnum</sourcexml> becomes <targetxml>primlaw:levelinfo/primlawinfo:primlawinfo/primlawinfo:identifier</targetxml> with required attribute <targetxml>@idtype="officialnum"</targetxml></p> 
      <note>For handling <b>@ln.user-displayed</b> attribute, refer the
        general markup <xref href="../../common_newest/Rosetta_leg.officialnum_ln.user-displayed-LxAdv-primlawinfo.identifier_source.dita">ln.user_displayed="false"</xref> section in the CI.</note>
    </section>
    <example>
      <title>Mapping of <sourcexml>leg:officialnum</sourcexml></title>
      <codeblock>

&lt;leg:officialnum&gt;USM_A000767y1990e&lt;/leg:officialnum&gt;

      </codeblock>
      <b>becomes</b>
      <codeblock>

 &lt;primlawinfo:primlawinfo&gt;
    &lt;primlawinfo:identifier idtype="officialnum"&gt;USM_A000767y1990e&lt;/primlawinfo:identifier&gt;
 &lt;/primlawinfo:primlawinfo&gt;   

       </codeblock>
    </example>  
    <example>
      <title>Mapping of <sourcexml>leg:officialnum with attribute
          [@ln.user-displayed="false"]</sourcexml></title>
      <codeblock>

&lt;leg:officialnum ln.user-displayed="false" searchtype="LEGISLATION"&gt;USM_A000009y1963e&lt;/leg:officialnum&gt;

      </codeblock>
      <b>becomes</b>
      <codeblock>

 &lt;primlawinfo:primlawinfo&gt;
    &lt;primlawinfo:identifier idtype="officialnum" source="editoriallyassigned"&gt;USM_A000009y1963e&lt;/primlawinfo:identifier&gt;
 &lt;/primlawinfo:primlawinfo&gt;   

       </codeblock>
    </example>    
    <note>The <sourcexml>@searchtype</sourcexml> attribute will be suppressed from conversion except for the citation element.</note>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY06_Regulations\leg.officialnum.dita  -->
<!--	<xsl:message>MY06_Regulations_leg.officialnum.xsl requires manual development!</xsl:message> -->

  <xsl:template match="leg:info/leg:officialnum[not(@ln.user-displayed)]">
    <!--  Original Target XPath:  primlaw:levelinfo/primlawinfo:primlawinfo/primlawinfo:identifier   -->
    <primlawinfo:identifier>
      <xsl:apply-templates select="@* | node() except leg:year"/>
    </primlawinfo:identifier>
  </xsl:template>

</xsl:stylesheet>