<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.levelbody">
   <title>leg:levelbody <lnpid>id-MY06-17219</lnpid></title>
   <body>
      <section>
        <ul>
          <li class="- topic/li ">
            The conversion of <sourcexml>leg:levelbody</sourcexml> depends upon its child elements:
            <ul>
              <li>
                If <sourcexml>leg:level</sourcexml> is the immediate child of <sourcexml>leg:levelbody</sourcexml> then it will become <targetxml>primlaw:level</targetxml> i.e, 
                <sourcexml>leg:levelbody/leg:level</sourcexml> becomes <targetxml>primlaw:level</targetxml>.
              </li>
              <li>
                If <sourcexml>leg:bodytext</sourcexml> is the immediate child of <sourcexml>leg:levelbody</sourcexml> then it will become <targetxml>primlaw:bodytext</targetxml> i.e,
                <sourcexml>leg:levelbody/leg:bodytext</sourcexml> becomes <targetxml>primlaw:bodytext</targetxml>.
              </li>
            </ul>
          </li>
        </ul>
      </section>

           <example>
             <title>Source XML 1 : For <sourcexml>leg:levelbody/leg:level</sourcexml></title>
             <codeblock>

&lt;leg:levelbody&gt;
  &lt;leg:level id="USM.A000001y1961e.SCH1"&gt;
     &lt;leg:level-vrnt toc-caption="SCHEDULE" subdoc="true" searchtype="LEGISLATION SCHEDULE" leveltype="schedule"&gt;
        &lt;leg:heading align="center"&gt;
          &lt;desig searchtype="SCH-NUM"&gt;
              &lt;designum&gt;&lt;refpt type="ext" id="USM.A000001y1961e.SCH1"/&gt;S&lt;emph typestyle="smcaps"&gt;CHEDULE&lt;/emph&gt;&lt;/designum&gt;
          &lt;/desig&gt;
&lt;/leg:heading&gt;


                 </codeblock>
           </example>
           
           <example>
             <title>Target XML 1 : For <sourcexml>leg:levelbody/leg:level</sourcexml></title>
             <codeblock>

&lt;primlaw:level leveltype="schedule" alternatetoccaption="SCHEDULE" includeintoc="true"&gt;
    &lt;ref:anchor id="USM.A000001y1961e.SCH1" anchortype="global"/&gt;
    &lt;heading&gt;
        &lt;desig&gt;1.&lt;/desig&gt; 
        &lt;title&gt;Short title and commencement&lt;/title&gt;
    &lt;/heading&gt;                       
    ....
&lt;/primlaw:level&gt;

             </codeblock>
           </example>
     
     <example>
       <title>Source XML 2 : For <sourcexml>leg:levelbody/leg:bodytext</sourcexml></title>
       <codeblock>

&lt;leg:levelbody&gt;
  &lt;leg:bodytext&gt;
    &lt;pgrp&gt;
      &lt;p&gt;
        &lt;text&gt;An Act to amend the Pineapple Industry Ordinance, 1957.&lt;/text&gt;
      &lt;/p&gt;
    &lt;/pgrp&gt;
  &lt;/leg:bodytext&gt;
    ...
&lt;/leg:levelbody&gt;

                 </codeblock>
     </example>
     
     <example>
       <title>Target XML 2: For <sourcexml>leg:levelbody/leg:bodytext</sourcexml></title>
       <codeblock>

&lt;primlaw:bodytext&gt;
   &lt;pgrp&gt;
      &lt;p&gt;
          &lt;text&gt;An Act to amend the Pineapple Industry Ordinance, 1957.&lt;/text&gt;
      &lt;/p&gt;
  &lt;/pgrp&gt;  
&lt;/primlaw:bodytext&gt;

             </codeblock>
     </example>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY06_Regulations\leg.levelbody.dita  -->
<!--	<xsl:message>MY06_Regulations_leg.levelbody.xsl requires manual development!</xsl:message> -->

  <xsl:template match="leg:levelbody">
    <xsl:apply-templates select="@* | node()"/>
  </xsl:template>
</xsl:stylesheet>