<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.empleg">
   <title>leg:empleg <lnpid>id-MY06-17212</lnpid></title>
   <body>
      <section>
        <ul>
        	<li><sourcexml>leg:empleg</sourcexml> <b>Becomes</b> <targetxml>primlaw:authority/primlaw:authority-item/textitem</targetxml> and populated as: 
        		
        		<pre>
              <b>Source XML</b>

&lt;leg:level id="USM.PUA0223y1984e.SCH1.FORM1"&gt;
    &lt;leg:level-vrnt toc-caption="Form 1" subdoc="true" searchtype="LEGISLATION FORM" leveltype="form"&gt;
        &lt;leg:heading&gt;
            &lt;desig searchtype="FORM-NUM"&gt;
                &lt;designum&gt;&lt;refpt type="ext" id="USM.PUA0223y1984e.SCH1.FORM1"/&gt;Form 1&lt;/designum&gt;
            &lt;/desig&gt;
            &lt;leg:empleg&gt;CONTROL OF DRUGS AND COSMETICS REGULATIONS 1984&lt;/leg:empleg&gt;
        &lt;/leg:heading&gt;
        .........
        .........
    &lt;/leg:level-vrnt&gt;
&lt;/leg:level&gt;

        		</pre>
        		<pre>
              <b>Target XML</b>


&lt;primlaw:level leveltype="form" includeintoc="true" alternatetoccaption="Form 1"&gt;
    &lt;ref:anchor id="USM.PUA0223y1984e.SCH1.FORM1" anchortype="global"/&gt;
    &lt;heading&gt;
        &lt;desig&gt;Form 1&lt;/desig&gt;
    &lt;/heading&gt;
    &lt;primlaw:authority&gt;
        &lt;primlaw:authority-item&gt;
            &lt;textitem&gt;CONTROL OF DRUGS AND COSMETICS REGULATIONS 1984&lt;/textitem&gt;
        &lt;/primlaw:authority-item&gt;
    &lt;/primlaw:authority&gt;
    .........
    .........
&lt;/primlaw:level&gt;

            </pre>
        		<note>The <sourcexml>leg:empleg</sourcexml> comes under <sourcexml>leg:heading</sourcexml> element in Rosetta but as per New Lexis <targetxml>primlaw:authority</targetxml> should be moved between <targetxml>primlaw:level</targetxml> and <targetxml>heading</targetxml> elements.</note>
        	</li>
		</ul>
      </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY06_Regulations\leg.empleg.dita  -->
<!--	<xsl:message>MY06_Regulations_leg.empleg.xsl requires manual development!</xsl:message> -->

    <xsl:template match="leg:empleg">
        <primlaw:authority>
            <primlaw:authority-item>
                <textitem>
                    <xsl:apply-templates select="node()"/>
                </textitem>
            </primlaw:authority-item>
        </primlaw:authority>
    </xsl:template>


</xsl:stylesheet>