<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="MY07_Rosetta_leg.enactdate-LxAdv-primlawinfo.enactdate">
  <title>leg.enactdate <lnpid>id-MY07-17417</lnpid></title>
 <body>
   <section>
     <p><sourcexml>leg:dates/leg:enactdate</sourcexml> becomes
       <targetxml>primlawinfo:primlawinfo/primlawinfo:dates/primlawinfo:enactdate</targetxml> with optional attributes <targetxml>@year</targetxml>,
       <targetxml>@month</targetxml> and <targetxml>@day</targetxml> and children are described as below: <ul>
          <li><sourcexml>date</sourcexml> becomes <targetxml>date-text</targetxml> and the attributes
            will be moved in the parent <targetxml>primlawinfo:enactdate</targetxml> element and
            populated as below: <ul>
              
              <li><sourcexml>date/@day</sourcexml> becomes
                  <targetxml>primlawinfo:enactdate/@day</targetxml></li>
              <li><sourcexml>date/@month</sourcexml> becomes
                  <targetxml>primlawinfo:enactdate/@month</targetxml></li>
              <li><sourcexml>date/@year</sourcexml> becomes
                  <targetxml>primlawinfo:enactdate/@year</targetxml></li>
            </ul></li>
        </ul></p>
     <note>When <sourcexml>leg:enactdate</sourcexml> has attribute <sourcexml>@ln.user-displayed="false"</sourcexml> (i.e. <sourcexml>leg:enactdate[@ln.user-displayed="false"</sourcexml>]), that element is translated into the target but with the element
     content omitted. Only the attributes are populated. So there is no displayable content.</note>
     
      
      <pre>
       
       &lt;leg:dates&gt;
             &lt;leg:enactdate ln.user-displayed="false" display-name="Enactment date"&gt;
                  &lt;date day="01" month="07" year="1959"&gt;1 July 1959&lt;/date&gt;
            &lt;/leg:enactdate&gt;
       &lt;/leg:dates&gt;
       
     </pre> Becomes <pre>
     
     &lt;primlawinfo:primlawinfo&gt;
              &lt;primlawinfo:dates&gt;
                    &lt;primlawinfo:enactdate year="1959" month="07" day="01"/&gt;
              &lt;/primlawinfo:dates&gt;
     &lt;/primlawinfo:primlawinfo&gt;
     
     </pre>
   </section>
   <note>If input having <sourcexml>leg:enactdate</sourcexml> without
     <sourcexml>@ln.user-displayed</sourcexml> attribute then its mapped with
     <targetxml>primlawinfo:primlawinfo/primlawinfo:dates/primlawinfo:enactdate</targetxml> and content should be captured in <targetxml>date-text</targetxml>
     markup with added text "<b>Enactment date: </b>"..</note>
   <section>
     <title>Changes</title>
     <p>2013-11-14: <ph id="change_20131114_SSX">Created</ph>.</p>
   </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY07_CourtRule\MY07_Rosetta_leg.enactdate-LxAdv-primlawinfo.enactdate.dita  -->
	<!--<xsl:message>MY07_Rosetta_leg.enactdate-LxAdv-primlawinfo.enactdate.xsl requires manual development!</xsl:message>--> 

	<xsl:template match="leg:dates/leg:enactdate[@ln.user-displayed != 'false' or not(@ln.user-displayed)]">

		<!--  Original Target XPath:  primlawinfo:primlawinfo/primlawinfo:dates/primlawinfo:enactdate   -->
		<primlawinfo:primlawinfo>
			<primlawinfo:dates>
				<primlawinfo:enactdate>
					<xsl:apply-templates select="@* | node()"/>
				</primlawinfo:enactdate>
			</primlawinfo:dates>
		</primlawinfo:primlawinfo>

	</xsl:template>

	<xsl:template match="date">

		<!--  Original Target XPath:  date-text   -->
		<date-text>
			<xsl:apply-templates select="@* | node()"/>
		</date-text>

	</xsl:template>

	<xsl:template match="date/@day">

		<!--  Original Target XPath:  primlawinfo:enactdate/@day   -->
		<primlawinfo:enactdate>
			<xsl:attribute name="day">
				<xsl:apply-templates select="."/>
			</xsl:attribute>
		</primlawinfo:enactdate>

	</xsl:template>

	<xsl:template match="date/@month">

		<!--  Original Target XPath:  primlawinfo:enactdate/@month   -->
		<primlawinfo:enactdate>
			<xsl:attribute name="month">
				<xsl:apply-templates select="."/>
			</xsl:attribute>
		</primlawinfo:enactdate>

	</xsl:template>

	<xsl:template match="date/@year">

		<!--  Original Target XPath:  primlawinfo:enactdate/@year   -->
		<primlawinfo:enactdate>
			<xsl:attribute name="year">
				<xsl:apply-templates select="."/>
			</xsl:attribute>
		</primlawinfo:enactdate>

	</xsl:template>

	
	<xsl:template match="leg:enactdate[@ln.user-displayed = 'false']">

		<!--  Original Target XPath:  primlawinfo:primlawinfo/primlawinfo:dates/primlawinfo:enactdate   -->
		<primlawinfo:primlawinfo>
			<primlawinfo:dates>
				<primlawinfo:enactdate>
					<xsl:attribute name="year" select="child::date/@year"></xsl:attribute>
					<xsl:attribute name="month" select="child::date/@month"></xsl:attribute>
					<xsl:attribute name="day" select="child::date/@day"></xsl:attribute>
					<!--<xsl:copy-of select="@*"/>-->
					<!--<xsl:apply-templates select="@*"/>-->
				</primlawinfo:enactdate>
			</primlawinfo:dates>
		</primlawinfo:primlawinfo>

	</xsl:template>

	

</xsl:stylesheet>