<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
  xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"
  xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:leg="http://www.lexis-nexis.com/glp/leg"
  xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/"
  xmlns:location="http://www.lexisnexis.com/xmlschemas/content/shared/location/1/"
  xmlns:regulation="urn:x-lexisnexis:content:regulation:sharedservices:1" version="2.0"
  exclude-result-prefixes="dita">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="NZ-Regs-Services-leg_juris">
    <title>leg:juris <lnpid>id-NZ10-24414</lnpid></title>
    <body>

      <p><targetxml>regulation:regulation/regulation:head</targetxml> is created as described in the
        Introduction.</p>
      <section>
        <title>regulation:head</title>

        <p>

          <ul>
            <li>
              <sourcexml>LEGDOC/leg:body/leg:info/leg:juris</sourcexml> becomes
                <targetxml>regulation:regulation/regulation:head/jurisinfo:legisbodyinfo/jurisinfo:jurisdiction/jurisinfo:system</targetxml>
              and create<targetxml>dc:metadata/dc:coverage/location:country</targetxml> with
              attributes @codescheme="ISO-3166-1" and @countrycode="NZ".
              <pre>
&lt;leg:juris @ln.user-displayed="false"&gt;NZ&lt;/leg:juris&gt;

  <b>Becomes</b>
			        


&lt;regulation:regulation&gt;
    &lt;regulation:head&gt;
        &lt;jurisinfo:legisbodyinfo&gt;
          &lt;jurisinfo:jurisdiction&gt;
            &lt;jurisinfo:system&gt;NZ&lt;/jurisinfo:system&gt;
          &lt;/jurisinfo:jurisdiction&gt;
       &lt;/jurisinfo:legisbodyinfo&gt;
    &lt;/regulation:head&gt;
    &lt;regulation:body/&gt; 
&lt;/regulation:regulation&gt; 
  

   &lt;dc:metadata&gt;
      &lt;dc:coverage&gt;
          &lt;location:country codescheme="ISO-3166-1" countrycode="NZ"/&gt;
      &lt;/dc:coverage&gt;
   &lt;/dc:metadata&gt;

  
                </pre>
            </li>
          </ul>
        </p>
      </section>
    </body>
  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ10_Regulation_From_Services\NZ-Regs-Services-leg_juris.dita  -->
  <!--<xsl:message>NZ-Regs-Services-leg_juris.xsl requires manual development!</xsl:message>-->

  <xsl:template match="LEGDOC/leg:body/leg:info/leg:juris">
    <!--  Original Target XPath:  regulation:regulation/regulation:head/jurisinfo:legisbodyinfo/jurisinfo:jurisdiction/jurisinfo:system   -->
    <jurisinfo:legisbodyinfo>
      <jurisinfo:jurisdiction>
        <jurisinfo:system>
          <xsl:apply-templates select="@* | node()"/>
        </jurisinfo:system>
      </jurisinfo:jurisdiction>
    </jurisinfo:legisbodyinfo>
  </xsl:template>
  
  <xsl:template match="LEGDOC/leg:body/leg:info/leg:juris" mode="metadata">
    <!--  Original Target XPath:  regulation:regulation/regulation:head/jurisinfo:legisbodyinfo/jurisinfo:jurisdiction/jurisinfo:system   -->
    <dc:coverage>
      <location:country>
        <xsl:attribute name="codescheme">
          <xsl:text>ISO-3166-1</xsl:text>
        </xsl:attribute>
        <xsl:attribute name="countrycode">
          <xsl:value-of select="."/>
        </xsl:attribute>
      </location:country>
    </dc:coverage>
  </xsl:template>
  
  <xsl:template match="LEGDOC/leg:body/leg:info/leg:juris/@searchtype"/>
<!--  <xsl:template match="LEGDOC/docinfo/docinfo:doc-id"/>-->
 
  

</xsl:stylesheet>
