<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.officialname">
  <title>leg:officialname <lnpid>id-PH01-33416</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:officialname</sourcexml> becomes
        <targetxml>legis:body/primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo/legisinfo:names/legisinfo:officialtitle</targetxml>.</p>

<pre>
&lt;leg:info&gt;
    &lt;leg:officialname ln.user-displayed="false" searchtype="LEGISLATION"&gt;ACT NO. 9 AN ACT PROVIDING
        FOR AN ALLOWANCE IN ESTIMATING AND ASSESSING DUTIABLE GOODS IN CASE OF LOSS OR DESTRUCTION
        OF THE SAME&lt;/leg:officialname&gt;
&lt;/leg:info&gt;

<b>Becomes</b>

&lt;legis:body&gt;
    &lt;primlaw:level leveltype="unclassified"&gt;
        &lt;primlaw:levelinfo&gt;
            &lt;primlawinfo:primlawinfo&gt;
                &lt;legisinfo:legisinfo&gt;
                    &lt;legisinfo:names&gt;
                        &lt;legisinfo:officialtitle source="editoriallyassigned"&gt;ACT NO. 9 AN ACT
                            PROVIDING FOR AN ALLOWANCE IN ESTIMATING AND ASSESSING DUTIABLE GOODS IN
                            CASE OF LOSS OR DESTRUCTION OF THE SAME&lt;/legisinfo:officialtitle&gt;
                    &lt;/legisinfo:names&gt;
                &lt;/legisinfo:legisinfo&gt;
            &lt;/primlawinfo:primlawinfo&gt;
        &lt;/primlaw:levelinfo&gt;
    &lt;/primlaw:level&gt;
&lt;/legis:body&gt;
       </pre>

      <note><p>The <sourcexml>@searchtype</sourcexml> and <sourcexml>@ln.user-displayed</sourcexml> attribute
        will be dropped from conversion.</p></note>
    </section>
    
        <section>
            <title>Changes</title>
            <p>2014-08-07: Created.</p>
        </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\PH01-Legislation\leg.officialname.dita  -->
	<xsl:message>PH01-Legislation_leg.officialname.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:officialname">

		<!--  Original Target XPath:  legis:body/primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo/legisinfo:names/legisinfo:officialtitle   -->
		<legis:body>
			<primlaw:level xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/">
				<primlaw:levelinfo>
					<primlawinfo:primlawinfo xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/">
						<legisinfo:legisinfo xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/">
							<legisinfo:names>
								<legisinfo:officialtitle>
									<xsl:apply-templates select="@* | node()"/>
								</legisinfo:officialtitle>
							</legisinfo:names>
						</legisinfo:legisinfo>
					</primlawinfo:primlawinfo>
				</primlaw:levelinfo>
			</primlaw:level>
		</legis:body>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="@ln.user-displayed">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>