<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.officialnum">
  <title>leg:officialnum <lnpid>id-PH01-33417</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:officialnum</sourcexml> becomes
          <targetxml>legis:body/primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/primlawinfo:identifier</targetxml>
        with required attribute <targetxml>@idtype="officialnum"</targetxml></p> 
      <note><p>For handling <b>@ln.user-displayed</b> attribute, refer the
        general markup <xref href="../../common_newest/Rosetta_leg.officialnum_ln.user-displayed-LxAdv-primlawinfo.identifier_source.dita">ln.user_displayed="false"</xref> section in the CI.</p></note>
    
    <note><p>Suppress <sourcexml>@searchtype</sourcexml> attribute.</p></note>
    <pre>
&lt;leg:body&gt;
    &lt;leg:info&gt;
        ...
        &lt;leg:officialnum ln.user-displayed="false" searchtype="LEGISLATION"&gt;Act No. 9,
            1900&lt;/leg:officialnum&gt;
    &lt;/leg:info&gt;
&lt;/leg:body&gt;

<b>becomes</b>

&lt;legis:body&gt;
    &lt;primlaw:level leveltype="unclassified"&gt;
        &lt;primlaw:levelinfo&gt;
            &lt;primlawinfo:primlawinfo&gt;
                ...
                &lt;primlawinfo:identifier idtype="officialnum"
                    source="editoriallyassigned"&gt;Act No. 9, 1900&lt;/primlawinfo:identifier&gt;
            &lt;/primlawinfo:primlawinfo&gt;
        &lt;/primlaw:levelinfo&gt;
    &lt;/primlaw:level&gt;
&lt;/legis:body&gt;
    </pre>
		</section>
        <section>
            <title>Changes</title>
            <p>2014-08-07: Created.</p>
        </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\PH01-Legislation\leg.officialnum.dita  -->
	<xsl:message>PH01-Legislation_leg.officialnum.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:officialnum">

		<!--  Original Target XPath:  legis:body/primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/primlawinfo:identifier   -->
		<legis:body>
			<primlaw:level xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/">
				<primlaw:levelinfo>
					<primlawinfo:primlawinfo xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/">
						<primlawinfo:identifier>
							<xsl:apply-templates select="@* | node()"/>
						</primlawinfo:identifier>
					</primlawinfo:primlawinfo>
				</primlaw:levelinfo>
			</primlaw:level>
		</legis:body>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>