<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.marginal-note">
  <title>leg:marginal-note <lnpid>id-ST04-26837</lnpid></title>
  <body>
    <section>
		<ul>
			<li>
          <sourcexml>leg:level/leg:level-vrnt/leg:marginal-note</sourcexml>
          <b>Becomes</b>
          <targetxml>primlaw:level/primlaw:bodytext/p/text/marginnote/bodytext/p/text</targetxml>
          <note>Create a random unique <targetxml>ref:anchor</targetxml> within marginnote if the
            source document does not contain one and <sourcexml>ID</sourcexml> of
              <sourcexml>ref:anchor</sourcexml> should be generated by given format
              "<targetxml>CountryCode_FileName_NumDigit</targetxml>" (i.e. CA_13107_001). </note>
          <pre>
            
              <b><i>Source example based on CA content</i></b>

&lt;leg:level&gt;
  &lt;leg:level-vrnt leveltype="3"&gt;
    &lt;leg:marginal-note&gt;Term of the apprenticeship program&lt;/leg:marginal-note&gt;
  &lt;/leg:level-vrnt&gt;
&lt;/leg:level&gt;

		</pre>
          <pre>
              <b><i>Example: Target Markup</i></b>
            

&lt;primlaw:level leveltype="unclassified"&gt;
  &lt;primlaw:bodytext&gt;
    &lt;p&gt;
      &lt;text&gt;
        &lt;marginnote&gt;&lt;ref:anchor id="CA_13107_001"/&gt;
          &lt;bodytext&gt;&lt;p&gt;&lt;text&gt;Term of the apprenticeship program&lt;/text&gt;&lt;/p&gt;&lt;/bodytext&gt;
        &lt;/marginnote&gt;
      &lt;/text&gt;
    &lt;/p&gt;
  &lt;/primlaw:bodytext&gt;
&lt;/primlaw:level&gt;

</pre>
        </li>
		</ul>
    </section> 
    <section>
      <title>Changes</title>
      <p>YYYY-MM-DD: ______________________________________________________________________.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Regulation\leg.marginal-note.dita  -->
	<xsl:message>Regulation_leg.marginal-note.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:level/leg:level-vrnt/leg:marginal-note">

		<!--  Original Target XPath:  primlaw:level/primlaw:bodytext/p/text/marginnote/bodytext/p/text   -->
		<primlaw:level>
			<primlaw:bodytext>
				<p>
					<text>
						<marginnote>
							<bodytext>
								<p>
									<text>
										<xsl:apply-templates select="@* | node()"/>
									</text>
								</p>
							</bodytext>
						</marginnote>
					</text>
				</p>
			</primlaw:bodytext>
		</primlaw:level>

	</xsl:template>

	<xsl:template match="ID">

		<!--  Original Target XPath:  CountryCode_FileName_NumDigit   -->
		<CountryCode_FileName_NumDigit>
			<xsl:apply-templates select="@* | node()"/>
		</CountryCode_FileName_NumDigit>

	</xsl:template>

	<xsl:template match="ref:anchor">

		<!--  Original Target XPath:  CountryCode_FileName_NumDigit   -->
		<CountryCode_FileName_NumDigit>
			<xsl:apply-templates select="@* | node()"/>
		</CountryCode_FileName_NumDigit>

	</xsl:template>

</xsl:stylesheet>