<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.currencydate">
  <title>leg:currencydate <lnpid>id-ST04-26814</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:dates/leg:currencydate</sourcexml> becomes <targetxml>primlaw:prelim/note/currencystatement</targetxml></p> 
    </section>
      <note><b>DPSI</b> value must be captured from manifest files and using in NL target
      conversion.</note>
      <note>For handling <sourcexml>remotelink</sourcexml> refer <xref href="../../common_newest/Rosetta_remotelink-LxAdv-ref.crossreference.dita">Remotelink</xref> section in CI but drop the attribute with value
                <targetxml>ref:crossreference@crossreferencetype="seeAlso"</targetxml> in target
            markup and this rule is applicable for scenario
            "<sourcexml>leg:dates/leg:currencydate/remotelink</sourcexml>".</note>
    <example>
        <title><i>Source example based on CA content</i></title>
            <codeblock>

&lt;leg:dates&gt;
    &lt;leg:currencydate&gt;
        &lt;remotelink dpsi="03EX" remotekey1="DOC-ID" remotekey2="currentness" service="DOC-ID" xml:lang="en"&gt;Updated&amp;#x20;on&amp;#x20;July&amp;#x20;27,&amp;#x20;2012&lt;/remotelink&gt;
    &lt;/leg:currencydate&gt;
&lt;/leg:dates&gt;

      </codeblock>
        <b><i>Target Example</i></b>
            <codeblock>

&lt;primlaw:prelim&gt;
    &lt;note&gt;
        &lt;currencystatement&gt;            
            &lt;ref:crossreference&gt;
                &lt;ref:content xml:lang="en"&gt;Updated&amp;#x20;on&amp;#x20;July&amp;#x20;27,&amp;#x20;2012&lt;/ref:content&gt;
                &lt;ref:locator&gt;
                    &lt;ref:locator-key&gt;
                        &lt;ref:key-name name="DOC-ID"/&gt;
                        &lt;ref:key-value value="03EX-currentness"/&gt;
                    &lt;/ref:locator-key&gt;
                &lt;/ref:locator&gt;
            &lt;/ref:crossreference&gt;
        &lt;/currencystatement&gt;
    &lt;/note&gt;
&lt;/primlaw:prelim&gt;

        </codeblock>
    </example>
      <section>
          <title>Changes</title>
          <p>YYYY-MM-DD: ______________________________________________________________________.</p>
      </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Regulation\leg.currencydate.dita  -->
	<xsl:message>Regulation_leg.currencydate.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:dates/leg:currencydate">

		<!--  Original Target XPath:  primlaw:prelim/note/currencystatement   -->
		<primlaw:prelim>
			<note>
				<currencystatement>
					<xsl:apply-templates select="@* | node()"/>
				</currencystatement>
			</note>
		</primlaw:prelim>

	</xsl:template>

	<xsl:template match="remotelink">

		<!--  Original Target XPath:  ref:crossreference@crossreferencetype="seeAlso"   -->
		<ref:crossreference>
			<xsl:apply-templates select="@* | node()"/>
		</ref:crossreference>

	</xsl:template>

	<xsl:template match="leg:dates/leg:currencydate/remotelink">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>