<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.endmatter">
   <title>leg:endmatter <lnpid>id-ST04-26819</lnpid></title>
   <body>
      <section>
        <ul>
          <li>
            <sourcexml>/LEGDOC/leg:body/leg:endmatter</sourcexml>
            <b>Becomes</b>
            <targetxml>/regulation:regulation/regulation:body/primlaw:level</targetxml>
            with <targetxml>@leveltype["endnote"]</targetxml> with child
            elements being handled as: <ul>
              <li>
                <sourcexml>leg:level/leg:level-vrnt</sourcexml>
                <b>becomes</b>
                <targetxml>primlaw:level</targetxml> with attribute
                <targetxml>@leveltype</targetxml>
              </li>
            </ul>
            <pre>
              <b><i>Source example based on AU content</i></b>       


&lt;leg:endmatter&gt;
	&lt;leg:level id="ACT_REG_1991-10_NOTES"&gt;
		&lt;leg:level-vrnt leveltype="notes" subdoc="true" toc-caption="Endnotes"&gt;
			&lt;leg:heading&gt;
				&lt;title align="center"&gt;&lt;refpt id="ACT_REG_1991-10_NOTES" 
				type="ext"/&gt;&lt;emph typestyle="bf"&gt;Endnotes&lt;/emph&gt;&lt;/title&gt;
			&lt;/leg:heading&gt;
			....
		&lt;/leg:level-vrnt&gt;
	&lt;/leg:level&gt;
&lt;/leg:endmatter&gt;

            
</pre>
            <pre>

              <b><i>Target Example</i></b>
            

&lt;primlaw:level leveltype="endnote"&gt;
	&lt;primlaw:level leveltype="unclassified" includeintoc="true" alternatetoccaption="Endnotes"&gt;
		&lt;ref:anchor id="ACT_REG_1991-10_NOTES" anchortype="global"/&gt;
		&lt;heading&gt;
			&lt;title align="center"&gt;&lt;emph typestyle="bf"&gt;Endnotes&lt;/emph&gt;&lt;/title&gt;
		&lt;/heading&gt;
		....
	&lt;/primlaw:level&gt;
&lt;/primlaw:level&gt;

       </pre>
          </li>
        </ul>
      </section>
    <section>
      <title>Changes</title>
      <p>YYYY-MM-DD: ______________________________________________________________________.</p>
    </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Regulation\leg.endmatter.dita  -->
	<xsl:message>Regulation_leg.endmatter.xsl requires manual development!</xsl:message> 

	<xsl:template match="/LEGDOC/leg:body/leg:endmatter">

		<!--  Original Target XPath:  /regulation:regulation/regulation:body/primlaw:level   -->
		<regulation:regulation xmlns:regulation="urn:x-lexisnexis:content:regulation:sharedservices:1">
			<regulation:body>
				<primlaw:level>
					<xsl:apply-templates select="@* | node()"/>
				</primlaw:level>
			</regulation:body>
		</regulation:regulation>

	</xsl:template>

	<xsl:template match="leg:level/leg:level-vrnt">

		<!--  Original Target XPath:  primlaw:level   -->
		<primlaw:level>
			<xsl:apply-templates select="@* | node()"/>
		</primlaw:level>

	</xsl:template>

</xsl:stylesheet>