<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.effdate">
  <title>leg:effdate <lnpid>id-ST04-26816</lnpid></title>
  <body>
    <section>
		<ul>
										<li><sourcexml>leg:info/leg:dates/leg:effdate</sourcexml>
					<b>becomes</b>
					<targetxml>primlawinfo:dates/primlawinfo:effdate</targetxml> which is populated
					as follows: <pre>
              <b><i>Source example based on UK content</i></b>


&lt;leg:info&gt;
	....
	&lt;leg:dates&gt;
		&lt;leg:effdate&gt;
			Passed: &lt;date day="10" month="07" year="1979"&gt;10 July 1979&lt;/date&gt;
		&lt;/leg:effdate&gt;
	&lt;/leg:dates&gt;
&lt;/leg:info&gt;

	</pre>
					<pre>

              <b><i>Target Example</i></b>
                 

&lt;primlawinfo:dates&gt;
	&lt;primlawinfo:effdate year="1979" month="07" day="10"&gt;Passed:
		&lt;date-text&gt;10th July 1979&lt;/date-text&gt;
	&lt;/primlawinfo:effdate&gt;
&lt;/primlawinfo:dates&gt;

                </pre>
				</li>
		</ul>
    </section> 
  	<section>
  		<title>Changes</title>
  		<p>YYYY-MM-DD: ______________________________________________________________________.</p>
  	</section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Regulation\leg.effdate.dita  -->
	<xsl:message>Regulation_leg.effdate.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:info/leg:dates/leg:effdate">

		<!--  Original Target XPath:  primlawinfo:dates/primlawinfo:effdate   -->
		<primlawinfo:dates>
			<primlawinfo:effdate>
				<xsl:apply-templates select="@* | node()"/>
			</primlawinfo:effdate>
		</primlawinfo:dates>

	</xsl:template>

</xsl:stylesheet>