<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.empleg">
  <title>leg:empleg <lnpid>id-ST04-26817</lnpid></title>
  <body>
    <section>
		<ul>
			<li><sourcexml>leg:empleg</sourcexml> Becomes <targetxml>primlaw:authority/primlaw:authority-item/textitem</targetxml> and populated as:
				<pre>
              <b><i>Source example based on AU content</i></b>

&lt;leg:level id="ACT_REG_1991-29_SCH1"&gt;
    &lt;leg:level-vrnt leveltype="schedule" searchtype="LEGISLATION"
        subdoc="true" toc-caption="Schedule&amp;#160;1 Exemptions from marking"&gt;
        &lt;leg:heading&gt;
            &lt;title align="left" searchtype="SCH-TITLE"&gt;&lt;refpt
                id="ACT_REG_1991-29_SCH1" type="ext"/&gt;&lt;emph typestyle="bf"&gt;
                    Schedule&amp;#160;1 Exemptions from marking&lt;/emph&gt;&lt;/title&gt;
            &lt;leg:empleg&gt;
                &lt;ci:cite searchtype="LEG-REF"&gt;&lt;ci:content&gt;(see s&amp;#160;4)&lt;/
                    ci:content&gt;&lt;/ci:cite&gt;
            &lt;/leg:empleg&gt;
        &lt;/leg:heading&gt; 

             
</pre>
					<pre>

              <b><i>Target Example</i></b>
              

&lt;primlaw:level leveltype="schedule" includeintoc="true"
    alternatetoccaption="Schedule&amp;#x00A0;1 Exemptions from marking"&gt;
    &lt;ref:anchor id="ACT_REG_1991-29_SCH1" anchortype="global"/&gt;
    &lt;heading&gt;
        &lt;title align="left"&gt;&lt;emph typestyle="bf"&gt;Schedule&amp;#x00A0;1
            Exemptions from marking&lt;/emph&gt;&lt;/title&gt;
    &lt;/heading&gt;
    &lt;primlaw:authority&gt;
        &lt;primlaw:authority-item&gt;
            &lt;textitem&gt;
                &lt;lnci:cite type="legislation"&gt;
                    &lt;lnci:content&gt;(see s&amp;#x00A0;4)&lt;/lnci:content&gt;
                &lt;/lnci:cite&gt;
            &lt;/textitem&gt;
        &lt;/primlaw:authority-item&gt;
    &lt;/primlaw:authority&gt;

					</pre>
				<pre>
              <b><i>Source example based on NZ content</i></b>

&lt;leg:level id="APN210704_SCHEDULE_1"&gt;
    &lt;leg:level-vrnt leveltype="schedule" searchtype="LEGISLATION"
        subdoc="true" toc-caption="Schedule 1 Maximum permissible levels for
        specified substances"&gt;
        &lt;leg:heading&gt;
            &lt;desig searchtype="SCH-NUM"&gt;&lt;refpt type="ext"
                id="APN210704_SCHEDULE_1"/&gt;Schedule 1&lt;/desig&gt;
            &lt;title align="left" searchtype="SCH-TITLE"&gt;Maximum permissible levels
                for specified substances&lt;/title&gt;
            &lt;leg:empleg&gt;
                &lt;ci:cite searchtype="LEG-REF"&gt;&lt;ci:content&gt;cl.7&lt;/ci:content&gt;&lt;/ci:cite&gt;
            &lt;/leg:empleg&gt;
        &lt;/leg:heading&gt;

             
</pre>
				<pre>

              <b><i>Target Example</i></b>
              

&lt;primlaw:level leveltype="schedule" includeintoc="true"
    alternatetoccaption="Schedule 1 Maximum permissible levels for specified
    substances"&gt;
    &lt;ref:anchor id="APN210704_SCHEDULE_1" anchortype="global"/&gt;
    &lt;heading&gt;
        &lt;desig&gt;Schedule 1&lt;/desig&gt;
        &lt;title&gt;Maximum permissible levels for specified substances&lt;/title&gt;
    &lt;/heading&gt;
    &lt;primlaw:authority&gt;
        &lt;primlaw:authority-item&gt;
            &lt;textitem&gt;
                &lt;lnci:cite type="legislation"&gt;
                    &lt;lnci:content&gt;cl.7&lt;/lnci:content&gt;
                &lt;/lnci:cite&gt;
            &lt;/textitem&gt;
        &lt;/primlaw:authority-item&gt;
    &lt;/primlaw:authority&gt;

            </pre>
				<note>The <sourcexml>leg:empleg</sourcexml> comes under <sourcexml>leg:heading</sourcexml> element in Rosetta but as per New Lexis <targetxml>primlaw:authority</targetxml> should be moved between <targetxml>primlaw:level</targetxml> and <targetxml>heading</targetxml> elements.</note>
			</li>
		</ul>
    </section> 
    <section>
      <title>Changes</title>
      <p>YYYY-MM-DD: ______________________________________________________________________.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Regulation\leg.empleg.dita  -->
	<xsl:message>Regulation_leg.empleg.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:empleg">

		<!--  Original Target XPath:  primlaw:authority/primlaw:authority-item/textitem   -->
		<primlaw:authority>
			<primlaw:authority-item>
				<textitem>
					<xsl:apply-templates select="@* | node()"/>
				</textitem>
			</primlaw:authority-item>
		</primlaw:authority>

	</xsl:template>

	<xsl:template match="leg:heading">

		<!--  Original Target XPath:  primlaw:authority   -->
		<primlaw:authority>
			<xsl:apply-templates select="@* | node()"/>
		</primlaw:authority>

	</xsl:template>

</xsl:stylesheet>