<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/" version="2.0" exclude-result-prefixes="dita docinfo leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.officialname">
  <title>leg:officialname <lnpid>id-ST04-26840</lnpid></title>
  <body>
    <section>
		<ul>
		<li><sourcexml>leg:info/leg:officialname</sourcexml>
					<b>becomes</b>
					<targetxml>legisinfo:legisinfo/legisinfo:names/legisinfo:officialtitle</targetxml>.
						<note>If emph occurs within <sourcexml>leg:officialname</sourcexml> with the
						attribute's value <sourcexml>emph[@typesytle="it"]</sourcexml> or
							<sourcexml>emph[@typesytle="un"]</sourcexml> will be retained and all
						other emph will be omitted from the NL conversion.</note>
					<pre>
              <b><i>Source example based on UK content</i></b>
                  

&lt;leg:info&gt;
&lt;leg:officialname&gt;BEE REGULATION&lt;/leg:officialname&gt;
&lt;/leg:info&gt;

	</pre>
					<pre>
                    
              <b><i>Target Example</i></b>              

&lt;legisinfo:legisinfo&gt;
	&lt;legisinfo:names&gt;
		&lt;legisinfo:officialtitle&gt;BEE REGULATION&lt;/legisinfo:officialtitle&gt;
	&lt;/legisinfo:names&gt;
&lt;/legisinfo:legisinfo&gt;

</pre>
					<note>If <sourcexml>leg:officialname</sourcexml> has attribute
							<sourcexml>@ln.user-displayed="false"</sourcexml>
						<b>becomes</b>
						<targetxml>legisinfo:officialtitle</targetxml> with attribute
							<targetxml>[@source="editoriallyassigned"]</targetxml>. Kindy refer the
						below example:</note>
					<note>The <sourcexml>@searchtype</sourcexml> attribute will be dropped from
						conversion except for the citation element.</note>
					<pre>
              <b><i>Source example based on NZ content</i></b>
                  

&lt;leg:info&gt;
&lt;leg:officialname ln.user-displayed="false" searchtype="LEGISLATION"&gt;COSTS IN CRIMINAL CASES REGULATIONS 1987&lt;/leg:officialname&gt;
&lt;/leg:info&gt;

	</pre>
					<pre>
                    
              <b><i>Target Example</i></b>              

&lt;legisinfo:legisinfo&gt;
	&lt;legisinfo:names&gt;
		&lt;legisinfo:officialtitle source="editoriallyassigned"&gt;COSTS IN CRIMINAL CASES REGULATIONS 1987&lt;/legisinfo:officialtitle&gt;
	&lt;/legisinfo:names&gt;
&lt;/legisinfo:legisinfo&gt;

</pre>
					
			<note>If the input document has scenario
				<sourcexml>leg:officialname/refpt</sourcexml> then suppress
				<sourcexml>refpt</sourcexml> from conversion since the id
				value matches with <sourcexml>docinfo:doc-id</sourcexml>.</note>
			<note>Conversion should not create adjacent
				<targetxml>legisinfo:legisinfo</targetxml>. Data should be
				merged to single
				<targetxml>legisinfo:legisinfo</targetxml>.</note>
			
				</li>

		</ul>

    </section> 
    <section>
      <title>Changes</title>
      <p>YYYY-MM-DD: ______________________________________________________________________.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Regulation\leg.officialname.dita  -->
	<xsl:message>Regulation_leg.officialname.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:info/leg:officialname">

		<!--  Original Target XPath:  legisinfo:legisinfo/legisinfo:names/legisinfo:officialtitle   -->
		<legisinfo:legisinfo>
			<legisinfo:names>
				<legisinfo:officialtitle>
					<xsl:apply-templates select="@* | node()"/>
				</legisinfo:officialtitle>
			</legisinfo:names>
		</legisinfo:legisinfo>

	</xsl:template>

	<xsl:template match="leg:officialname">

		<!--  Original Target XPath:  legisinfo:officialtitle   -->
		<legisinfo:officialtitle>
			<xsl:apply-templates select="@* | node()"/>
		</legisinfo:officialtitle>

	</xsl:template>

	<xsl:template match="emph[@typesytle=&#34;it&#34;]">

		<!--  Original Target XPath:  legisinfo:officialtitle   -->
		<legisinfo:officialtitle>
			<xsl:apply-templates select="@* | node()"/>
		</legisinfo:officialtitle>

	</xsl:template>

	<xsl:template match="emph[@typesytle=&#34;un&#34;]">

		<!--  Original Target XPath:  legisinfo:officialtitle   -->
		<legisinfo:officialtitle>
			<xsl:apply-templates select="@* | node()"/>
		</legisinfo:officialtitle>

	</xsl:template>

	<xsl:template match="@ln.user-displayed=&#34;false&#34;">

		<!--  Original Target XPath:  legisinfo:officialtitle   -->
		<legisinfo:officialtitle>
			<xsl:apply-templates select="@* | node()"/>
		</legisinfo:officialtitle>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:  legisinfo:legisinfo   -->
		<legisinfo:legisinfo>
			<xsl:apply-templates select="@* | node()"/>
		</legisinfo:legisinfo>

	</xsl:template>

	<xsl:template match="leg:officialname/refpt">

		<!--  Original Target XPath:  legisinfo:legisinfo   -->
		<legisinfo:legisinfo>
			<xsl:apply-templates select="@* | node()"/>
		</legisinfo:legisinfo>

	</xsl:template>

	<xsl:template match="refpt">

		<!--  Original Target XPath:  legisinfo:legisinfo   -->
		<legisinfo:legisinfo>
			<xsl:apply-templates select="@* | node()"/>
		</legisinfo:legisinfo>

	</xsl:template>

	<xsl:template match="docinfo:doc-id">

		<!--  Original Target XPath:  legisinfo:legisinfo   -->
		<legisinfo:legisinfo>
			<xsl:apply-templates select="@* | node()"/>
		</legisinfo:legisinfo>

	</xsl:template>

</xsl:stylesheet>