<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
  xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" 
  version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_blockquote-legfragment-leg.level-to-LexisAdvance_primlaw.excerpt-primlaw.level">
  <title><sourcexml>blockquote/legfragment/leg:level</sourcexml> to <targetxml>primlaw:excerpt/primlaw:level</targetxml> <lnpid>id-CCCC-10244</lnpid></title>
  <body>
   <section>
     <p>
       <sourcexml>legfragment</sourcexml> becomes <targetxml>primlaw:excerpt</targetxml>.
       <b>blockquote/legfragment/leg:level</b>: When legfragment is the first child of
       blockquote, drop the blockquote and convert the legfragment to primlaw:excerpt. If the
       Xpath is blockquote/legfragment/leg:level, then drop the blockquote and convert to
       primlaw:excerpt/primlaw:level. <codeblock>

&lt;leg:level id="NSW_ACT_2009-100_SCH1AMCL12"&gt;&lt;leg:level-vrnt leveltype="clause" searchtype="LEGISLATION" subdoc="true" toc-caption="[12] Section 97CB Annual greenhouse gas benchmark statements"&gt;....
&lt;leg:levelbody&gt;
&lt;leg:bodytext&gt;
&lt;p&gt;
&lt;text&gt;Omit section 97CB (1). Insert instead:&lt;/text&gt;
&lt;/p&gt;
&lt;blockquote&gt;
&lt;legfragment&gt;
&lt;leg:level&gt;
&lt;leg:level-vrnt leveltype="subclause"&gt;
&lt;leg:heading
inline="true"&gt;
&lt;desig&gt;&lt;designum&gt;(1)&lt;/designum&gt;&lt;/desig&gt;
&lt;/leg:heading&gt;
&lt;leg:levelbody&gt;
&lt;leg:bodytext&gt;
&lt;p&gt;
&lt;text&gt;A benchmark participant must lodge with the Tribunal a greenhouse gas benchmark statement:&lt;/text&gt;
&lt;l type="def"&gt;
&lt;li&gt;&lt;lilabel&gt;(a)&lt;/lilabel&gt;
&lt;p&gt;
&lt;text&gt;in respect of a compliance period (other than the final compliance period), not later than 1 March in the year immediately
following the end of that compliance period, or&lt;/text&gt;
&lt;/p&gt;
&lt;/li&gt;
&lt;li&gt;&lt;lilabel&gt;(b)&lt;/lilabel&gt;
&lt;p&gt;
&lt;text&gt;in respect of the final compliance period, not later than 3 months after the termination day.&lt;/text&gt;
&lt;/p&gt;
&lt;/li&gt;
&lt;/l&gt;

        </codeblock>
       <b>Becomes</b>
       <codeblock>      

&lt;primlaw:level xml:id="NSW_ACT_2009-100_SCH1AMCL12" leveltype="clause" subdoc="true" toc-caption="[12] Section 97CB Annual
 greenhouse gas benchmark statements"&gt;.....
 &lt;primlaw:bodytext&gt;
 &lt;p&gt;
 &lt;text&gt;Omit section 97CB (1). Insert instead:&lt;/text&gt;
  &lt;/p&gt;
  &lt;primlaw:excerpt&gt;
  &lt;primlaw:level leveltype="subclause"&gt;
  &lt;heading inline="true"&gt;&lt;desig&gt;(1)&lt;/desig&gt;&lt;/heading&gt;&lt;primlaw:bodytext&gt;
  &lt;p&gt;
  &lt;text&gt;A benchmark participant must lodge with the Tribunal a greenhouse gas benchmark statement:&lt;/text&gt;
  &lt;list&gt;
    &lt;listitem&gt;
      &lt;label&gt;(a)&lt;/label&gt;
      &lt;bodytext&gt;
      &lt;p&gt;
      &lt;text&gt;in respect of a compliance period (other than the final compliance period), not later than 1 March in the
      year immediately following the end of that compliance period, or
      &lt;/text&gt;
      &lt;/p&gt;
      &lt;/bodytext&gt;
    &lt;/listitem&gt;
   &lt;listitem&gt;
      &lt;label&gt;(b)&lt;/label&gt;
      &lt;bodytext&gt;
      &lt;p&gt;
      &lt;text&gt;in respect of the final compliance period, not later than 3 months after the termination
        day.
      &lt;/text&gt;
      &lt;/p&gt;
      &lt;/bodytext&gt;
    &lt;/listitem&gt; 
  &lt;/list&gt;

        </codeblock>
     </p>
   </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_blockquote-legfragment-leg.level-LxAdv-primlaw.excerpt-primlaw.level.dita  -->
	 
	 <!-- JL separated out the templates because I need to convert legfragment without leg:level in it for other modules 
	 blockquote passthrough is effected in the blockquote module 
	 -->

	<xsl:template match="legfragment//leg:level" priority="25">
		<!--  Original Target XPath:  primlaw:excerpt/primlaw:level   -->
			<primlaw:level>
			  <xsl:if test="not(leg:level-vrnt/@leveltype)">
			    <xsl:attribute name="leveltype">unclassified</xsl:attribute>
			  </xsl:if>
			  <xsl:apply-templates select="leg:level-vrnt/@*"/>
			  <!-- 2017-09-25 - MDS removed 'leg:level-vrnt/leg:heading/desig/designum/refpt' from A-T to stop duplication due to handling of leg:level-vrnt in 
			  /modules/leg/leg.level-LxAdv-primlaw.level.xsl-->
			  <xsl:apply-templates select="leg:heading/desig/designum/refpt"/>
				<xsl:apply-templates select="@* | node()"/>
			</primlaw:level>
	</xsl:template>
  
  <!-- I assume we want to output excerpt level children without running them through bodytext first  JL -->

	<xsl:template match="legfragment">
		<!--  Original Target XPath:  primlaw:excerpt   -->
		<primlaw:excerpt>
		  <xsl:apply-templates select="@*"/>
		  <xsl:for-each-group select="*" group-adjacent="if (self::leg:level) then 0 else 1">
		    <xsl:choose>
		      <xsl:when test="current-grouping-key()=0">
		        <xsl:apply-templates select="current-group()"/>
		      </xsl:when>
		      <xsl:otherwise>
		        <primlaw:bodytext>
		          <xsl:apply-templates select="current-group()"/>
		        </primlaw:bodytext>		        
		      </xsl:otherwise>
		    </xsl:choose>
		  </xsl:for-each-group>		 
		</primlaw:excerpt>
	</xsl:template>

</xsl:stylesheet>