<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.levelbody">
    <title>leg:levelbody <lnpid>id-UK20-35809</lnpid></title>
    <body>
        <section>
            <ul>
                <li class="- topic/li ">
                    The conversion of <sourcexml>leg:levelbody</sourcexml> depends upon its child elements:
                    <ul>
                        <li>
                            If <sourcexml>leg:level</sourcexml> is the immediate child of <sourcexml>leg:levelbody</sourcexml> then it will become <targetxml>primlaw:level</targetxml> i.e, 
                            <sourcexml>leg:levelbody/leg:level</sourcexml> becomes <targetxml>primlaw:level</targetxml>.
                        </li>
                        <li>
                            If <sourcexml>leg:bodytext</sourcexml> is the immediate child of <sourcexml>leg:levelbody</sourcexml> then it will become <targetxml>primlaw:bodytext</targetxml> i.e,
                            <sourcexml>leg:levelbody/leg:bodytext</sourcexml> becomes <targetxml>primlaw:bodytext</targetxml>.
                        </li>
                    </ul>
                </li>
            </ul>
        </section>
        
        <example>
            <title>Source XML 1 : For <sourcexml>leg:levelbody/leg:level</sourcexml></title>
            <codeblock>

&lt;leg:levelbody&gt;
    &lt;leg:level&gt;
        &lt;leg:level-vrnt leveltype="part"&gt;
            &lt;leg:heading align="center" searchtype="LEGISLATION"&gt;
                &lt;title&gt;PART I THE CASES&lt;/title&gt;
            &lt;/leg:heading&gt;
        &lt;/leg:level-vrnt&gt;
    &lt;/leg:level&gt;
    ...
&lt;/leg:levelbody&gt;

                 
<b>Becomes</b>
           

&lt;primlaw:level leveltype="part"&gt;
    &lt;heading align="center" searchtype="LEGISLATION"&gt;
        &lt;title&gt;PART I THE CASES&lt;/title&gt;
    &lt;/heading&gt;
&lt;/primlaw:level&gt;

             </codeblock>
        </example>
        
        <example>
            <title>Source XML 2 : For <sourcexml>leg:levelbody/leg:bodytext</sourcexml></title>
            <codeblock>

&lt;leg:levelbody&gt;
      &lt;leg:bodytext&gt;
        &lt;p&gt;
            &lt;text align="center"&gt;General&lt;/text&gt;
        &lt;/p&gt;
       &lt;/leg:bodytext&gt;
    ...
&lt;/leg:levelbody&gt;


 <b>Becomes</b>


&lt;primlaw:bodytext&gt;
    &lt;p&gt;
        &lt;text&gt;General&lt;/text&gt;
    &lt;/p&gt;
&lt;/primlaw:bodytext&gt;

             </codeblock>
        </example>
   
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK20_Legislative_History\leg.levelbody.dita  -->
    <!-- 20170421:  MCJ:  Commented out the message during development... but this is not yet done. -->
	<!-- <xsl:message>UK20_Legislative_History_leg.levelbody.xsl requires manual development!</xsl:message> --> 

    <!-- leg:levelbody is a passthrough. -->
	<xsl:template match="leg:levelbody">
		<xsl:apply-templates select="@* | node()"/>
	</xsl:template>

</xsl:stylesheet>