<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK22LF_leg.level">
    <title>leg:level <lnpid>id-UK22LF-36012</lnpid></title>
    <body>
        <section>
            <p><sourcexml>leg:level/leg:level-vrnt</sourcexml> becomes
                    <targetxml>primlaw:level</targetxml> which has a required attribute
                    <targetxml>@leveltype</targetxml> and its values are tokenized as below:</p>
            <ul>
                <li><sourcexml>leg:level/leg:level-vrnt[@leveltype="Section"]</sourcexml> becomes
                        <targetxml>primlaw:level[@leveltype="section"]</targetxml></li>
                <li><sourcexml>leg:level/leg:level-vrnt[@leveltype="unclassified"]</sourcexml>
                    becomes <targetxml>primlaw:level[@leveltype="unclassified"]</targetxml></li>
            </ul>
            <note>In New Lexis <targetxml>primlaw:level</targetxml> element is used instead of
                Rosetta elements <sourcexml>leg:level</sourcexml> and
                    <sourcexml>leg:level-vrnt</sourcexml>. Pick the
                    <sourcexml>@leveltype</sourcexml> value from
                    <sourcexml>leg:level-vrnt</sourcexml> and the element
                    <sourcexml>leg:level-vrnt</sourcexml> will be suppressed from conversion.</note>
            <note>If the input files are having <sourcexml>@leveltype</sourcexml> values other than
                the tokenized list as shown above, the value will be set as
                    <targetxml>@leveltype="unclassified"</targetxml>.</note>
        </section>
        <example>
            <title>Source XML 1</title>
            <codeblock>
&lt;leg:body id="1000848"&gt;
    &lt;leg:level&gt;
        &lt;leg:level-vrnt leveltype="section"&gt;
            &lt;leg:heading searchtype="LEG-TITLE"&gt;
                &lt;title&gt;Treaty establishing the European Community (Amsterdam consolidated version)
                    Part Five: Institutions of the Community Title I: Provisions governing the
                    institutions Chapter 1: The institutions Section 4: The Court of Justice
                    Article 234 Article 177 - EC Treaty (Maastricht consolidated version)
                    Article 177 - EEC Treaty&lt;/title&gt;
            &lt;/leg:heading&gt;
            &lt;leg:levelbody&gt;
                &lt;leg:bodytext&gt;
                    &lt;p&gt;
                        &lt;text&gt;OJ. No. C 340, 10.11.1997, P. 273&lt;/text&gt;
                    &lt;/p&gt;
                &lt;/leg:bodytext&gt;
            &lt;/leg:levelbody&gt;
        &lt;/leg:level-vrnt&gt;
    &lt;/leg:level&gt;
&lt;/leg:body&gt;
            </codeblock>
        </example>
        <example>
            <title>Target XML 1</title>
            <codeblock>
&lt;funddoc:body id="1000848"&gt;
    &lt;primlaw:level leveltype="section"&gt;
        &lt;heading&gt;
            &lt;title&gt;Treaty establishing the European Community (Amsterdam consolidated version)
                Part Five: Institutions of the Community Title I: Provisions governing the
                institutions Chapter 1: The institutions Section 4: The Court of Justice
                Article 234 Article 177 - EC Treaty (Maastricht consolidated version)
                Article 177 - EEC Treaty&lt;/title&gt;
        &lt;/heading&gt;
        &lt;primlaw:bodytext&gt;
            &lt;p&gt;
                &lt;text&gt;OJ. No. C 340, 10.11.1997, P. 273&lt;/text&gt;
            &lt;/p&gt;
        &lt;/primlaw:bodytext&gt;
    &lt;/primlaw:level&gt;
&lt;/funddoc:body&gt;
            </codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>2015-06-29: <ph id="change_20150629_PS">Created.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK22LF\leg.level.dita  -->
	 

    <xsl:template match="leg:level">
        <primlaw:level>
            <xsl:apply-templates select="@*"/>
            <xsl:apply-templates select="leg:level-vrnt/@*"/>            
            <xsl:if test="not(leg:level-vrnt/@leveltype or @leveltype)">
                <xsl:attribute name="leveltype"><xsl:text>unclassified</xsl:text></xsl:attribute>
            </xsl:if>
            <xsl:apply-templates select="node()"/>
        </primlaw:level>
    </xsl:template>
    
    <xsl:template match="leg:level-vrnt">
        <xsl:apply-templates select="leg:heading/descendant::refpt | leg:levelinfo/leg:levelstatus/refpt"/>
        <xsl:apply-templates select="leg:heading"/>
        <xsl:apply-templates select="leg:heading/leg:empleg"/>
        <xsl:apply-templates select="node() except (leg:heading)"/>
    </xsl:template>
    
   
    <xsl:template match="leg:level-vrnt/@leveltype | leg:level/@leveltype">
        <xsl:attribute name="leveltype">
            <xsl:choose>
                <xsl:when test=".=('section' , 'unclassified')"><xsl:value-of select="."/></xsl:when>
                <xsl:when test=".='Section'">section</xsl:when>                  
                <xsl:otherwise><xsl:text>unclassified</xsl:text></xsl:otherwise>
            </xsl:choose>
        </xsl:attribute>        
    </xsl:template>
    


</xsl:stylesheet>