<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:leg="http://www.lexis-nexis.com/glp/leg"
	xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0"
	exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legis-leg.empleg">
		<title>
			<sourcexml>leg:empleg</sourcexml>
			<lnpid>id-UK22CF-39011</lnpid>
		</title>
		<body>
			<section>
				<p><sourcexml>/COMMENTARYDOC/comm:body/level/level/bodytext/legfragment/leg:endmatter/leg:level/leg:level-vrnt/leg:heading/leg:empleg</sourcexml>
					becomes
						<targetxml>/funddoc:fundamentallegaldocument/funddoc:body/primlaw:level/primlaw:level/primlaw:bodytext/primlaw:excerpt/primlaw:level/primlaw:level/primlaw:authority/primlaw:authority-item/textitem</targetxml>.
							<note><targetxml>primlaw:authority</targetxml> is a sibling of
							<targetxml>heading</targetxml>.</note>
				</p>
			</section>
			<example>
				<codeblock>

&lt;leg:level&gt;
        &lt;leg:level-vrnt leveltype="schedule"&gt;
            &lt;leg:heading&gt;
                &lt;title&gt;Schedule&lt;/title&gt;
                &lt;leg:empleg&gt;Article 2&lt;/leg:empleg&gt;
            &lt;/leg:heading&gt;
        &lt;/leg:level-vrnt&gt;
        .......................
    &lt;/leg:level&gt;

      </codeblock>
				<b>Becomes</b>
				<codeblock>

&lt;primlaw:level leveltype="schedule"&gt;
        &lt;heading&gt;
            &lt;title&gt;Schedule&lt;/title&gt;                                  
        &lt;/heading&gt;
        &lt;primlaw:authority&gt;
            &lt;primlaw:authority-item&gt;
                &lt;textitem&gt;Article 2&lt;/textitem&gt;
            &lt;/primlaw:authority-item&gt;
        &lt;/primlaw:authority&gt;
        ......................
    &lt;/primlaw:level&gt;

    </codeblock>
			</example>
			<section>
				<title>Changes</title>
				<p>2016-09-19: <ph id="change_20160919_RS">Created</ph></p>
			</section>
		</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK22CF\legis-leg.empleg.dita  -->


	<xsl:template match="leg:empleg">

		<!--  Original Target XPath:  /funddoc:fundamentallegaldocument/funddoc:body/primlaw:level/primlaw:level/primlaw:bodytext/primlaw:excerpt/primlaw:level/primlaw:level/primlaw:authority/primlaw:authority-item/textitem   -->
		<primlaw:authority>
			<primlaw:authority-item>
				<textitem>
					<xsl:apply-templates select="@* | node()"/>
				</textitem>
			</primlaw:authority-item>
		</primlaw:authority>

	</xsl:template>



</xsl:stylesheet>
