<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/"
	xmlns:leg="http://www.lexis-nexis.com/glp/leg"
	xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/"
	version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legis-leg.status">
		<title>
			<sourcexml>leg:status</sourcexml>
			<lnpid>id-UK22CF-39021</lnpid>
		</title>
		<body>
			<section>
				<p><sourcexml>/COMMENTARYDOC/comm:body/level/bodytext/legfragment/leg:info/leg:status</sourcexml>
					becomes
						<targetxml>/funddoc:fundamentallegaldocument/funddoc:body/primlaw:level/primlaw:bodytext/primlaw:excerpt/primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo/legisinfo:statusgroup/legisinfo:status/legisinfo:statustext</targetxml></p>
				<p><sourcexml>leg:status/@statuscode</sourcexml> becomes
						<targetxml>legisinfo:status@statuscode</targetxml> the attribute value in
					the Source XML is directly converted into the target XML output as shown in the
					example below.</p>
				<note>Conversion should not create adjacent
						<targetxml>legisinfo:statusgroup</targetxml>. Data should be merged to
					single <targetxml>legisinfo:statusgroup</targetxml>.</note>
			</section>
			<example>
				<codeblock>
    &lt;leg:info&gt;
        .............
       &lt;leg:status&gt;At the Court at Buckingham Palace, the 9th day of July 2008&lt;/leg:status&gt;
        &lt;leg:status&gt;Present,&lt;/leg:status&gt;
        &lt;leg:status&gt;The Queen's Most Excellent Majesty in Council&lt;/leg:status&gt;
        .............
    &lt;/leg:info&gt;

      </codeblock>
				<b>Becomes</b>
				<codeblock>

 &lt;primlaw:levelinfo&gt;
        &lt;primlawinfo:primlawinfo&gt;
            ..........................
            &lt;legisinfo:legisinfo&gt;
                .....................
                &lt;legisinfo:statusgroup&gt;
                    &lt;legisinfo:status&gt;
                        &lt;legisinfo:statustext&gt;At the Court at Buckingham Palace, the 9th day of July 2008 Present, The Queen's Most Excellent Majesty in Council&lt;/legisinfo:statustext&gt;
                    &lt;/legisinfo:status&gt;
                &lt;/legisinfo:statusgroup&gt;
            &lt;/legisinfo:legisinfo&gt;
            ................
        &lt;/primlawinfo:primlawinfo&gt;
    &lt;/primlaw:levelinfo&gt;

      </codeblock>
			</example>
			<section>
				<title>Changes</title>
				<p>2016-09-19: <ph id="change_20160919_RS">Created</ph></p>
			</section>
		</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK22CF\legis-leg.status.dita  -->


	<xsl:template match="leg:status">

		<!--  Original Target XPath:  /funddoc:fundamentallegaldocument/funddoc:body/primlaw:level/primlaw:bodytext/primlaw:excerpt/primlaw:level/primlaw:levelinfo/primlawinfo:primlawinfo/legisinfo:legisinfo/legisinfo:statusgroup/legisinfo:status/legisinfo:statustext   -->


		<xsl:apply-templates select="@* | node()"/>
	</xsl:template>


</xsl:stylesheet>
