<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:lnv="http://www.lexis-nexis.com/lnv" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita lnv">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="RU02-lnv_PUB">
    <title>lnv:PUB <lnpid>id-RU02-32044</lnpid> </title>

    <body>
        <p>
            <sourcexml>lnv:PUB</sourcexml> becomes <targetxml>doc:metadata/pubinfo:pubinfo/pubinfo:publicationname</targetxml>
        </p>

        <example>
            <title>Source XML</title>
            <codeblock>
&lt;lnv:PUB&gt;THE CIVIL CODE OF THE RUSSIAN FEDERATION&lt;nl/&gt;PART ONE&lt;nl/&gt;&lt;nl/&gt;
    &lt;lnlink service="ATTACHMENT"&gt;&lt;lnvxe:marker&gt;VIEW PDF IN
                RUSSIAN&lt;/lnvxe:marker&gt;&lt;lnvxe:api-params&gt;&lt;lnvxe:param name="componentseq" value="1"
                /&gt;&lt;lnvxe:param name="attachment-key" value="RFCC1-CHAPTER6"/&gt;&lt;lnvxe:param
                name="attachment-type" value="PDF"/&gt;&lt;lnvxe:param name="attachment-smi" value="24703"
            /&gt;&lt;/lnvxe:api-params&gt;
    &lt;/lnlink&gt;
&lt;/lnv:PUB&gt;

	</codeblock>
        </example>

        <example>
            <title>Target XML </title>
            <codeblock>
&lt;pubinfo:pubinfo&gt;
    &lt;pubinfo:publicationname&gt;THE CIVIL CODE OF THE RUSSIAN FEDERATION&lt;proc:nl/&gt;PART ONE&lt;proc:nl/&gt;&lt;proc:nl/&gt;
        &lt;ref:lnlink service="ATTACHMENT"&gt;
            &lt;ref:marker&gt;VIEW PDF IN RUSSIAN&lt;/ref:marker&gt;
            &lt;ref:locator&gt;
                &lt;ref:locator-params&gt;
                    &lt;proc:param name="componentseq" value="1"/&gt;
                    &lt;proc:param name="attachment-key" value="RFCC1-CHAPTER6"/&gt;
                    &lt;proc:param name="attachment-type" value="PDF"/&gt;
                    &lt;proc:param name="attachment-smi" value="24703"/&gt;
                &lt;/ref:locator-params&gt;
            &lt;/ref:locator&gt;
        &lt;/ref:lnlink&gt;
    &lt;/pubinfo:publicationname&gt;
&lt;/pubinfo:pubinfo&gt;

	</codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>Created.</p>
        </section>
    </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\RU02\RU02-lnv_PUB.dita  -->
	<xsl:message>RU02-lnv_PUB.xsl requires manual development!</xsl:message> 

	<xsl:template match="lnv:PUB">

		<!--  Original Target XPath:  doc:metadata/pubinfo:pubinfo/pubinfo:publicationname   -->
		<doc:metadata>
			<pubinfo:pubinfo xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/">
				<pubinfo:publicationname>
					<xsl:apply-templates select="@* | node()"/>
				</pubinfo:publicationname>
			</pubinfo:pubinfo>
		</doc:metadata>

	</xsl:template>

</xsl:stylesheet>