<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legis-docinfo-normcite">
  <title>docinfo:normcite <lnpid>id-ST03-26608</lnpid></title>
  <body>
    <section>
      <p><sourcexml>docinfo:normcite/ci:cite/ci:content</sourcexml> becomes <targetxml>ref:citations/ref:cite4thisresource[@citetype]/ref:nonciteidentifier/[@normprotocol]</targetxml>. Attributes value should be set to:
        <ul>
          <li><targetxml>ref:cite4thisresource[@citetype="normcite"]</targetxml></li>
          <li><targetxml>ref:nonciteidentifier[@normprotocol"unspecified"]</targetxml></li>
        </ul>
        </p>
    </section>
    <example>
      <title>UK SOURCE XML 1: Mapping of <sourcexml>docinfo:normcite/ci:cite/ci:content</sourcexml></title>
      <codeblock>

&lt;docinfo:normcite&gt;
 &lt;ci:cite type="cite4thisdoc"&gt;
  &lt;ci:content&gt;1266_4a&lt;/ci:content&gt;
 &lt;/ci:cite&gt;
&lt;/docinfo:normcite&gt;

      </codeblock>
      <b>Becomes</b>
      <title>UK TARGET XML 1: Mapping of <sourcexml>docinfo:normcite/ci:cite/ci:content</sourcexml></title>
      <codeblock>

&lt;legis:head&gt;
 &lt;ref:citations&gt;
  &lt;ref:cite4thisresource citetype="normcite"&gt;
   &lt;ref:nonciteidentifier normprotocol="unspecified"&gt;1266_4a&lt;/ref:nonciteidentifier&gt;
  &lt;/ref:cite4thisresource&gt;
 &lt;/ref:citations&gt;
&lt;/legis:head&gt;

    </codeblock>
    </example>
   <section>
    <title>Changes</title>
    <p>2013-07-16: <ph id="change_20130716_SK">Instruction narrative edited for language; no changes to mappings, no impact to stylesheets.</ph></p>
    <p>2013-07-08: <ph id="change_20130708_AB">Created.</ph></p>
   </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Legislation\legis-docinfo-normcite.dita  -->
	<xsl:message>legis-docinfo-normcite.xsl requires manual development!</xsl:message> 

	<xsl:template match="docinfo:normcite/ci:cite/ci:content">

		<!--  Original Target XPath:  ref:citations/ref:cite4thisresource[@citetype]/ref:nonciteidentifier/[@normprotocol]   -->
		<ref:citations>
			<ref:cite4thisresource>
				<ref:nonciteidentifier>
					<!--  Could not determine target element or attribute name:  <[@normprotocol]>  -->						<xsl:apply-templates select="@* | node()"/>
					<!--  Could not determine target element or attribute name:  </[@normprotocol]>  -->
				</ref:nonciteidentifier>
			</ref:cite4thisresource>
		</ref:citations>

	</xsl:template>

</xsl:stylesheet>