<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:lnci="http://www.lexisnexis.com/xmlschemas/content/shared/citations/1/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legis-leg.num_ci.cite">
  <title>leg:num/ci:cite <lnpid>id-ST03-26640</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:num/ci:cite[@type="cite4thisdoc"]</sourcexml> becomes <targetxml>ref:citations/ref:cite4thisresource</targetxml> and create child element <targetxml>lnci:cite</targetxml> for handling citation markup.</p>
        <note>When text appears inside <sourcexml>leg:num</sourcexml>, conversion needs to move the pinpoint information into <targetxml>lnci:content</targetxml>. </note>
        <note>If <sourcexml>leg:num</sourcexml> does not contain any citation markup and has just text then it will be converted to <targetxml>ref:citations/ref:cite4thisresource</targetxml>, create a child <targetxml>lnci:cite/lnci:content</targetxml> to capture the text.</note>
    </section>
      <example>
       <title>CANADA SOURCE XML 1: Mapping of <sourcexml>leg:num/ci:cite</sourcexml></title>
       <codeblock>

&lt;leg:num&gt;
 &lt;ci:cite type="cite4thisdoc"&gt;
  &lt;ci:stat&gt;
   &lt;ci:statinfo spanref="stcspan1"&gt;
    &lt;ci:hier&gt;
     &lt;ci:hierlev label="year" num="1996"&gt;
      &lt;ci:hierlev label="chapter" num="1" /&gt;
     &lt;/ci:hierlev&gt;
    &lt;/ci:hier&gt;
   &lt;/ci:statinfo&gt;
   &lt;ci:statref spanref="stcspan1"&gt;
    &lt;ci:publicationname normpubcode="RSBC" value="RSBC" /&gt;
   &lt;/ci:statref&gt;
  &lt;/ci:stat&gt;
  &lt;ci:content&gt;
   &lt;ci:span spanid="stcspan1"&gt;R.S.B.C. 1996, c. 1&lt;/ci:span&gt;
  &lt;/ci:content&gt;
 &lt;/ci:cite&gt;, Preamble
&lt;/leg:num&gt;

       </codeblock>
       <b>Becomes</b>
       <title>CANADA TARGET XML 1: Mapping of <sourcexml>leg:num/ci:cite</sourcexml></title>
       <codeblock>

&lt;ref:citations&gt;
 &lt;ref:cite4thisresource&gt;
  &lt;lnci:cite&gt;
   &lt;lnci:stat&gt;
    &lt;lnci:statinfo&gt;
     &lt;lnci:hier&gt;
      &lt;lnci:hierlev label="year" num="1996"&gt;
       &lt;lnci:hierlev label="chapter" num="1" /&gt;
      &lt;/lnci:hierlev&gt;
     &lt;/lnci:hier&gt;
    &lt;/lnci:statinfo&gt;
    &lt;lnci:statref&gt;
     &lt;lnci:publicationname normpubcode="RSBC" value="RSBC" /&gt;
    &lt;/lnci:statref&gt;
   &lt;/lnci:stat&gt;
   &lt;lnci:content&gt;R.S.B.C. 1996, c. 1, Preamble&lt;/lnci:content&gt;
  &lt;/lnci:cite&gt;
 &lt;/ref:cite4thisresource&gt;
&lt;/ref:citations&gt;

       </codeblock>
      </example>
      <example>
       <title>CANADA SOURCE XML 2: Mapping of <sourcexml>leg:num</sourcexml> with text only</title>
       <codeblock>

&lt;leg:num&gt;R.S.B.C. 1996, c. 117, s. 2&lt;/leg:num&gt;

       </codeblock>
       <b>Becomes</b>
       <title>CANADA TARGET XML 2: Mapping of <sourcexml>leg:num</sourcexml> with text only</title>
       <codeblock>

&lt;ref:citations&gt;
 &lt;ref:cite4thisresource&gt;
  &lt;lnci:cite&gt;
   &lt;lnci:content&gt;R.S.B.C. 1996, c. 117, s. 2&lt;/lnci:content&gt;
  &lt;/lnci:cite&gt;
 &lt;/ref:cite4thisresource&gt;
&lt;/ref:citations&gt;

       </codeblock>
      </example>
   <section>
    <title>Changes</title>
    <p>2013-07-16: <ph id="change_20130716_SK">Instruction narrative edited for language; no changes to mappings, no impact to stylesheets.</ph></p>
    
    <p>2013-07-08: <ph id="change_20130708_AB">Created.</ph></p>
   </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Legislation\legis-leg.num_ci.cite.dita  -->
	<xsl:message>legis-leg.num_ci.cite.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:num/ci:cite[@type=&#34;cite4thisdoc&#34;]">

		<!--  Original Target XPath:  ref:citations/ref:cite4thisresource   -->
		<ref:citations>
			<ref:cite4thisresource>
				<xsl:apply-templates select="@* | node()"/>
			</ref:cite4thisresource>
		</ref:citations>

	</xsl:template>

	<xsl:template match="leg:num">

		<!--  Original Target XPath:  lnci:content   -->
		<lnci:content>
			<xsl:apply-templates select="@* | node()"/>
		</lnci:content>

	</xsl:template>

	<xsl:template match="leg:num/ci:cite">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>