<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:lnci="http://www.lexisnexis.com/xmlschemas/content/shared/citations/1/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.officialnum_ci.cite">
    <title>leg:officialnum_ci:cite <lnpid>id-ST04-26842</lnpid></title>
    <body>
        <section>
            <p>If source document having <sourcexml>leg:officialnum/ci:cite</sourcexml> becomes
                    <targetxml>ref:citations/ref:cite4thisresource</targetxml> and create child
                element <targetxml>lnci:cite</targetxml> for handling citation markup. </p>
        </section>

        <example>
            <title>Source example based on CA content</title>
            <codeblock>

&lt;leg:officialnum&gt;
    &lt;ci:cite type="cite4thisdoc"&gt;
        &lt;ci:stat&gt;
            &lt;ci:statinfo spanref="stcspan1"&gt;
                &lt;ci:hier&gt;
                    &lt;ci:hierlev label="year" num="1997"&gt;
                        &lt;ci:hierlev label="reg-no" num="175"/&gt;
                    &lt;/ci:hierlev&gt;
                &lt;/ci:hier&gt;
            &lt;/ci:statinfo&gt;
            &lt;ci:statref spanref="stcspan1"&gt;
                &lt;ci:publicationname normpubcode="CARG2" value="CARG2"/&gt;
            &lt;/ci:statref&gt;
        &lt;/ci:stat&gt;
        &lt;ci:content&gt;
            &lt;ci:span spanid="stcspan1"&gt;DORS/97-175&lt;/ci:span&gt;
        &lt;/ci:content&gt;
    &lt;/ci:cite&gt;
&lt;/leg:officialnum&gt;

      </codeblock>
            <b>Target Example</b>
            <codeblock>


&lt;ref:citations&gt;
    &lt;ref:cite4thisresource&gt;
        &lt;lnci:cite&gt;
            &lt;lnci:stat&gt;
               &lt;lnci:statinfo&gt;
                &lt;lnci:hier&gt;
                    &lt;lnci:hierlev label="year" num="1997"&gt;
                        &lt;lnci:hierlev label="reg-no" num="175"/&gt;
                    &lt;/lnci:hierlev&gt;
                &lt;/lnci:hier&gt;
            &lt;/lnci:statinfo&gt;
             &lt;lnci:statref&gt;
                &lt;lnci:publicationname normpubcode="CARG2" value="CARG2" /&gt;
            &lt;/lnci:statref&gt;
            &lt;/lnci:stat&gt;
            &lt;lnci:content&gt;DORS/97-175&lt;/lnci:content&gt;
            &lt;/lnci:cite&gt;
    &lt;/ref:cite4thisresource&gt;
&lt;/ref:citations&gt;

       </codeblock>
        </example>
    <section>
      <title>Changes</title>
      <p>YYYY-MM-DD: ______________________________________________________________________.</p>
    </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Regulation\leg.officialnum_ci.cite.dita  -->
	<xsl:message>Regulation_leg.officialnum_ci.cite.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:officialnum/ci:cite">

		<!--  Original Target XPath:  ref:citations/ref:cite4thisresource   -->
		<ref:citations>
			<ref:cite4thisresource>
				<xsl:apply-templates select="@* | node()"/>
			</ref:cite4thisresource>
		</ref:citations>

	</xsl:template>

</xsl:stylesheet>