<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:ci="http://www.lexis-nexis.com/ci" version="2.0" exclude-result-prefixes="dita ci">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_ci.cite-Chof-lilabel-LxAdv-Suppress">
    <title><sourcexml>lilabel/ci:cite</sourcexml> <lnpid>id-CCCC-10267</lnpid></title>
    <body>
        <section>
            <p>If <sourcexml>ci:cite</sourcexml> encounter in <sourcexml>lilabel</sourcexml>, then <sourcexml>ci:cite</sourcexml> will be suppressed but its content will be retained in NL conversion.</p>
        </section>
        <example>
            <title>Source XML </title>
            <codeblock>

&lt;li&gt;
 &lt;lilabel&gt;
  &lt;ci:cite searchtype="LEG-REF"&gt;
   &lt;ci:content&gt;
    &lt;remotelink dpsi="0K9G" refpt="2008A1S1" remotekey1="REFPTID" service="DOC-ID"&gt;S1 &lt;/remotelink&gt;
   &lt;/ci:content&gt;
  &lt;/ci:cite&gt;
 &lt;/lilabel&gt;
 &lt;p&gt;
  &lt;text&gt;Title&lt;/text&gt;
 &lt;/p&gt;
&lt;/li&gt;
            </codeblock>
            <title>Target XML</title>
            <codeblock>

&lt;listitem&gt;
 &lt;label&gt;S1&lt;/label&gt;
 &lt;bodytext&gt;
  &lt;p&gt;
   &lt;text&gt;Title&lt;/text&gt;
  &lt;/p&gt;
 &lt;/bodytext&gt;
&lt;/listitem&gt;
            </codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>2012-09-27: Created.</p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_ci.cite-Chof-lilabel-LxAdv-Suppress.dita  -->
	<!--<xsl:message>Rosetta_ci.cite-Chof-lilabel-LxAdv-Suppress.xsl requires manual development!</xsl:message> -->

	<xsl:template match="lilabel/ci:cite"/>


</xsl:stylesheet>