<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:glp="http://www.lexis-nexis.com/glp" version="2.0" exclude-result-prefixes="dita glp">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_glp.note_ChildOf_defterm-to-LexisAdvance_inlinenote">
  <title><sourcexml>defterm/glp:note</sourcexml> to <targetxml>defterm/inlinenote</targetxml> <lnpid>id-NZ01-22611</lnpid></title>
  <body>
    <section>
    <p>
      <ul>
      <li> If <sourcexml>glp:note</sourcexml> is the child of <sourcexml>defterm</sourcexml> then
              <sourcexml>glp:note</sourcexml> becomes <targetxml>inlinenote</targetxml> with
            attribute <targetxml>@notetype="editorial-note"</targetxml>
          </li>
      </ul>      
    </p>
    </section>
    <example>
      <title>Source XML </title>
      <codeblock>

     &lt;p&gt;  
       &lt;text&gt;
          &lt;defterm&gt;
              &lt;refpt id="1994A164SOB_1:MAORI_AUTHORITY" type="ext"&gt;&lt;/refpt&gt;
              &lt;emph typestyle="bf"&gt;[&lt;/emph&gt;Maori authority means a person who has made an effective election under 
              &lt;ci:cite searchtype="LEG-REF"&gt;
                 &lt;ci:content&gt;
                        ...
                 &lt;/ci:content&gt;
             &lt;/ci:cite&gt;
             &lt;glp:note&gt;
               &lt;p&gt;&lt;text&gt;{ Editorial Note: Former definition continues to apply until 2004&amp;#x2013;05 income year (see history note). }&lt;/text&gt;&lt;/p&gt;
             &lt;/glp:note&gt;
          &lt;/defterm&gt;
       &lt;/text&gt;
    &lt;/p&gt;

</codeblock>
      <title>Target XML</title>
      <codeblock>

    &lt;p&gt;  
       &lt;text&gt;
          &lt;defterm&gt;
            &lt;ref:anchor id="_1994A164SOB_1-MAORI_AUTHORITY" anchortype="global"/&gt;
               &lt;emph typestyle="bf"&gt;[&lt;/emph&gt;Maori authority means a person who has made an effective election under 
                  &lt;lnci:cite&gt;
                      &lt;lnci:content&gt;
                          ...
                      &lt;/lnci:content&gt;
                   &lt;/lnci:cite&gt;
                &lt;inlinenote notetype="editorial-note"&gt;
                  { Editorial Note: Former definition continues to apply until 2004&amp;#x2013;05 income year (see history note). }
                &lt;/inlinenote&gt;
           &lt;/defterm&gt;
        &lt;/text&gt;
    &lt;/p&gt;

</codeblock>
    </example>
    <section>
      <title>Changes</title>
      <p>2013-09-05: <ph id="change_20130905_WL">Created rule for
            <sourcexml>defterm/glp:note</sourcexml>  to support this xpath. NZ01 Discussion
          board/NZ01 NZ-Legislation from Acts CI Schema Issue</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ01_Legis\NZ_Legis-Rosetta_glp.note-Chof-text-LxAdv-inlinenote.dita  -->
	
	<xsl:template match="defterm/glp:note"  priority="25">
	  <inlinenote xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/">
			  <xsl:attribute name="notetype" select="'editorial-note'"/>
				<xsl:apply-templates select="@* | node()"/>
		</inlinenote>
	</xsl:template>

  <xsl:template match="text/glp:note"  priority="30">
    <inlinenote xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/">
      <xsl:attribute name="notetype" select="'editorial-note'"/>
      <xsl:apply-templates select="@* | node()"/>
    </inlinenote>
  </xsl:template>

  <xsl:template match="text/glp:note/p" priority="30">
    <xsl:apply-templates/>
  </xsl:template>
  
  <xsl:template match="text/glp:note/p/text" priority="30">
    <xsl:apply-templates/>
  </xsl:template>

</xsl:stylesheet>