<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:admindoc="urn:x-lexisnexis:content:administrative-document:sharedservices:1" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_glp.note_ChildOf_leg.heading-to-LexisAdvance_admindoc.level_note">
  <title><sourcexml>leg:heading/glp:note</sourcexml> to <targetxml>admindoc:level/note</targetxml> <lnpid>id-CCCC-10342</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:heading/glp:note</sourcexml> becomes <targetxml>admindoc:level/note</targetxml> with <targetxml>note</targetxml> placed
        after <targetxml>heading</targetxml>.</p>
    </section>
    <example>
      <title>Source XML</title>
      <codeblock>

&lt;leg:level id="2004R427-P11-D1-SD1"&gt;
 &lt;leg:level-vrnt leveltype="subdivision" searchtype="LEGISLATION SUBDIVISION" subdoc="false" toc-caption="Pedestrians and riders of mobility devices or wheeled recreational devices"&gt;
  &lt;leg:heading&gt;
   &lt;title searchtype="SUBDIV-TITLE"&gt;
    &lt;refpt id="2004R427-P11-D1-SD1" type="ext"/&gt;Pedestrians and riders of mobility devices or wheeled recreational devices&lt;/title&gt;
   &lt;glp:note&gt;
    &lt;p&gt;&lt;text&gt;Heading substituted by r 35 of the Land Transport (Road User) Amendment Rules 2009, effective 1 November 2009.&lt;/text&gt;&lt;/p&gt;
   &lt;/glp:note&gt;
  &lt;/leg:heading&gt;
    ...
&lt;/leg:level&gt;

            </codeblock>
      <title>Target XML</title>
      <codeblock>

&lt;admindoc:level alternatetoccaption="Pedestrians and riders of mobility devices or wheeled recreational devices" includeintoc="false" leveltype="subdivision"&gt;
 &lt;ref:anchor id="nz_2004R427-P11-D1-SD1" anchortype="global"/&gt;
    &lt;heading&gt;
        &lt;title&gt;Pedestrians and riders of mobility devices or wheeled recreational devices&lt;/title&gt;
    &lt;/heading&gt;
    &lt;note&gt;
        &lt;bodytext&gt;
            &lt;p&gt;&lt;text&gt;Heading substituted by r 35 of the Land Transport (Road User) Amendment Rules 2009, effective 1 November 2009.&lt;/text&gt;&lt;/p&gt;
        &lt;/bodytext&gt;
    &lt;/note&gt;
    ...
&lt;/primlaw:level&gt;

        </codeblock>
    </example>
    <section>
      <title>Changes</title>
      <p>First Draft</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_glp.note_ChildOf_leg.heading-to-LexisAdvance_admindoc.level_note.dita  -->
	<!-- this is handled in level module -->

</xsl:stylesheet>