<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:glp="http://www.lexis-nexis.com/glp" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" version="2.0" exclude-result-prefixes="dita glp">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_glp.note_ChildOf_text-to-LexisAdvance_inlinenote">
  <title><sourcexml>text/glp:note</sourcexml> to <targetxml>text/inlinenote</targetxml> <lnpid>id-CCCC-10339</lnpid></title>
  <body>
    <section>
    <p>
      <ul>
          <li>If <sourcexml>glp:note</sourcexml> is the child of <sourcexml>text</sourcexml> then
              <sourcexml>glp:note</sourcexml> becomes <targetxml>inlinenote</targetxml> with
            attribute <targetxml>@notetype="editor-note"</targetxml>
          </li>
          <li>If <sourcexml>p/text</sourcexml> is the child of <sourcexml>glp:note</sourcexml> then
            conversion should suppress <sourcexml>p/text</sourcexml> element only and PCDATA of this
            directly goes into <targetxml>inlinenote</targetxml>.</li>
      </ul>      
    </p>
    </section>
    <example>
      <title>Source XML </title>
      <codeblock>

&lt;p&gt;
  &lt;text&gt;
    &lt;glp:note&gt;
        &lt;p nl="0"&gt;
            &lt;text&gt;[Editor's note: Figure 1 could not be reproduced online. Please 
contact Quicklaw Customer Service at 1-800-387-0899 or service@quicklaw.com and request 
the following document: 07aeub57Figure1.doc]&lt;/text&gt;
      &lt;/p&gt;
    &lt;/glp:note&gt; A number of area residents expressed opposition to the proposed wells, as described below. 
  &lt;/text&gt;
&lt;/p&gt;

</codeblock>
      <title>Target XML</title>
      <codeblock>

&lt;p&gt;
  &lt;text&gt;
    &lt;inlinenote notetype="editor-note"&gt;      
        [Editor's note: Figure 1 could not be reproduced online. 
Please contact Quicklaw Customer Service at 1-800-387-0899 or service@quicklaw.com and 
request the following document: 07aeub57Figure1.doc]        
    &lt;/inlinenote&gt; A number of area residents expressed opposition to the proposed wells, as described below. 
&lt;/text&gt;
&lt;/p&gt;

</codeblock>
    </example>
    <section>
      <title>Changes</title>
      <p>2016-04-01: <ph id="change_20160401_PS">Added instruction for child elements of <sourcexml>glp:note</sourcexml> element, Applicable on CA01.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_glp.note-Chof-text-LxAdv-inlinenote.dita  -->
	 
<!-- Vikas Rohilla : Initial created the text/glp:note-->
  <!-- Sudhanshu Srivastava added CA02 Stream ID for converting glpnote to inline -->
  <xsl:template match="text/glp:note[$streamID='CA01' or $streamID='CA02CC' or $streamID='CA04' ]">
    <inlinenote>
      <xsl:attribute name="notetype">
        <xsl:text>editor-note</xsl:text>
      </xsl:attribute>
      <xsl:apply-templates/>
		</inlinenote>
	</xsl:template>


</xsl:stylesheet>