<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl" xmlns:newsitem="http://www.lexisnexis.com/xmlschemas/content/news/newsitem/1/" version="2.0" exclude-result-prefixes="dita jrnl">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journaldoc-jrnl_journalcite">
  <title>jrnl:journalcite <lnpid>id-ST09-32625</lnpid></title>

  <body>
      <p><sourcexml>jrnl:journalcite</sourcexml> becomes
                <targetxml>newsitem:head/ref:citations/ref:cite4thisresource</targetxml></p>

<pre>
    <b><i>Source example based on AU content</i></b>
    
&lt;jrnl:body&gt;
	&lt;jrnl:info&gt;
        &lt;jrnl:journalcite&gt;
        	&lt;ci:cite type="cite4thisdoc"&gt;
        		&lt;ci:lawrev&gt;
        			&lt;ci:lawrevref&gt;
        				&lt;ci:lawrevlocator&gt;
        					&lt;ci:publicationname normpubcode="ILJ" /&gt;
        					&lt;ci:volume num="17"/&gt;&lt;ci:page num="118"/&gt;
        				&lt;/ci:lawrevlocator&gt;
        			&lt;/ci:lawrevref&gt;
        		&lt;/ci:lawrev&gt;
        		&lt;ci:content&gt;(2006) 17 ILJ 118&lt;/ci:content&gt;
        	&lt;/ci:cite&gt;
        &lt;/jrnl:journalcite&gt;
	&lt;/jrnl:info&gt;
&lt;/jrnl:body&gt;

<b>Becomes</b>

&lt;newsitem:head&gt;
        &lt;ref:citations&gt;
            &lt;ref:cite4thisresource&gt;
                &lt;lnci:cite type="cite4thisdoc"&gt;
                    &lt;lnci:lawrev&gt;
                        &lt;lnci:lawrevref&gt;
                            &lt;lnci:lawrevlocator&gt;
                                &lt;lnci:publicationname normpubcode="ILJ"/&gt;
                                &lt;lnci:volume num="17"/&gt;
                                &lt;lnci:page num="118"/&gt;
                            &lt;/lnci:lawrevlocator&gt;
                        &lt;/lnci:lawrevref&gt;
                    &lt;/lnci:lawrev&gt;
                    &lt;lnci:content&gt;(2006) 17 ILJ 118&lt;/lnci:content&gt;
                &lt;/lnci:cite&gt;
            &lt;/ref:cite4thisresource&gt;
        &lt;/ref:citations&gt;
&lt;/newsitem:head&gt;
</pre>
      <section>
          <title>Changes</title>
          <p>Created.</p>
      </section>
      
</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Newsitem\Journaldoc-jrnl_journalcite.dita  -->
	<xsl:message>Journaldoc-jrnl_journalcite.xsl requires manual development!</xsl:message> 

	<xsl:template match="jrnl:journalcite">

		<!--  Original Target XPath:  newsitem:head/ref:citations/ref:cite4thisresource   -->
		<newsitem:head>
			<ref:citations xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/">
				<ref:cite4thisresource>
					<xsl:apply-templates select="@* | node()"/>
				</ref:cite4thisresource>
			</ref:citations>
		</newsitem:head>

	</xsl:template>

</xsl:stylesheet>