<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl" xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/" version="2.0" exclude-result-prefixes="dita jrnl">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journaldoc-jrnl_prelim">
  <title>jrnl:prelim <lnpid>id-ST09-32626</lnpid></title>

  <body>
			<p><sourcexml>jrnl:prelim</sourcexml> becomes <targetxml>nitf:body/nitf:body.head</targetxml></p>
    
      <p><sourcexml>jrnl:prelim/heading/title</sourcexml> becomes
                <targetxml>nitf:body/nitf:body.head/nitf:hedline/nitf:hl1</targetxml></p>
      
      <p>Drop <sourcexml>@searchtype</sourcexml> attribute from <sourcexml>heading</sourcexml> element.</p>
    
<pre>
        <b><i>Source example based on AU content</i></b>
    
&lt;jrnl:body&gt;
    &lt;jrnl:prelim&gt;
        &lt;heading&gt;
            &lt;title&gt;Carter's Criminal Law News Queensland&lt;/title&gt;
        &lt;/heading&gt;
        &lt;contrib&gt;Editor: 
            &lt;person&gt;
                &lt;name.text&gt;&lt;emph typestyle="bf"&gt;S Ryan&lt;/emph&gt;&lt;/name.text&gt;
            &lt;/person&gt; BCom LLB (HONS) Barrister, Legal Aid Queensland
        &lt;/contrib&gt;
    &lt;/jrnl:prelim&gt;
&lt;/jrnl:body&gt;

<b>Becomes</b>

&lt;nitf:body&gt;
    &lt;nitf:body.head&gt;
        &lt;nitf:hedline&gt;
            &lt;nitf:hl1&gt;Carter's Criminal Law News Queensland&lt;/nitf:hl1&gt;
        &lt;/nitf:hedline&gt;
        &lt;nitf:byline&gt;
            &lt;person:contributor&gt;Editor: &lt;person:person&gt;
                    &lt;person:name.text&gt;&lt;emph typestyle="bf"&gt;S Ryan&lt;/emph&gt;&lt;/person:name.text&gt;
                &lt;/person:person&gt; BCom LLB (HONS) Barrister, Legal Aid Queensland
            &lt;/person:contributor&gt;
        &lt;/nitf:byline&gt;
    &lt;/nitf:body.head&gt;
&lt;/nitf:body&gt;
</pre>

      <p><sourcexml>jrnl:prelim/heading/subtitle</sourcexml> becomes
                <targetxml>nitf:body/nitf:body.head/nitf:hedline/nitf:hl2</targetxml></p>
<pre>
        <b><i>Source example based on AU content</i></b>

&lt;jrnl:prelim&gt;
    &lt;heading searchtype="JOURNAL-HEADING"&gt;&lt;title&gt;Making the right decision &amp;mdash; The right way&lt;/title&gt;
        &lt;subtitle&gt;&lt;emph typestyle="bf"&gt;&lt;emph typestyle="it"&gt;Christine Deborah Anderson v&amp;nbsp;The Council of the City of Lismore&lt;/emph&gt;&lt;/emph&gt;&lt;/subtitle&gt;
    &lt;/heading&gt;
    ...
&lt;/jrnl:prelim&gt;
    
<b>Becomes</b>
    
&lt;nitf:body&gt;
    &lt;nitf:body.head&gt;
        &lt;nitf:hedline&gt;
            &lt;nitf:hl1&gt;Making the right decision &amp;mdash; The right way&lt;/nitf:hl1&gt;
            &lt;nitf:hl2&gt;
                &lt;emph typestyle="bf"&gt;
                    &lt;emph typestyle="it"&gt;Christine Deborah Anderson v&amp;nbsp;The Council of the City
                        of Lismore&lt;/emph&gt;
                &lt;/emph&gt;
            &lt;/nitf:hl2&gt;
        &lt;/nitf:hedline&gt;
    &lt;/nitf:body.head&gt;
&lt;/nitf:body&gt;
</pre>

      <section>
          <title>Changes</title>
          <p>Created.</p>
      </section>
  </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Newsitem\Journaldoc-jrnl_prelim.dita  -->
	<xsl:message>Journaldoc-jrnl_prelim.xsl requires manual development!</xsl:message> 

	<xsl:template match="jrnl:prelim">

		<!--  Original Target XPath:  nitf:body/nitf:body.head   -->
		<nitf:body>
			<nitf:body.head>
				<xsl:apply-templates select="@* | node()"/>
			</nitf:body.head>
		</nitf:body>

	</xsl:template>

	<xsl:template match="jrnl:prelim/heading/title">

		<!--  Original Target XPath:  nitf:body/nitf:body.head/nitf:hedline/nitf:hl1   -->
		<nitf:body>
			<nitf:body.head>
				<nitf:hedline>
					<nitf:hl1>
						<xsl:apply-templates select="@* | node()"/>
					</nitf:hl1>
				</nitf:hedline>
			</nitf:body.head>
		</nitf:body>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:  nitf:body/nitf:body.head/nitf:hedline/nitf:hl2   -->
		<nitf:body>
			<nitf:body.head>
				<nitf:hedline>
					<nitf:hl2>
						<xsl:apply-templates select="@* | node()"/>
					</nitf:hl2>
				</nitf:hedline>
			</nitf:body.head>
		</nitf:body>

	</xsl:template>

	<xsl:template match="heading">

		<!--  Original Target XPath:  nitf:body/nitf:body.head/nitf:hedline/nitf:hl2   -->
		<nitf:body>
			<nitf:body.head>
				<nitf:hedline>
					<nitf:hl2>
						<xsl:apply-templates select="@* | node()"/>
					</nitf:hl2>
				</nitf:hedline>
			</nitf:body.head>
		</nitf:body>

	</xsl:template>

	<xsl:template match="jrnl:prelim/heading/subtitle">

		<!--  Original Target XPath:  nitf:body/nitf:body.head/nitf:hedline/nitf:hl2   -->
		<nitf:body>
			<nitf:body.head>
				<nitf:hedline>
					<nitf:hl2>
						<xsl:apply-templates select="@* | node()"/>
					</nitf:hl2>
				</nitf:hedline>
			</nitf:body.head>
		</nitf:body>

	</xsl:template>

</xsl:stylesheet>