<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl" xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/" version="2.0" exclude-result-prefixes="dita jrnl">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journaldoc-jrnl_bodytext">
  <title>jrnl:bodytext <lnpid>id-ST09-32622</lnpid></title>

  <body>
    <p><sourcexml>jrnl:bodytext</sourcexml> becomes <targetxml>nitf:body.content/bodytext</targetxml></p>

    <p>The attribute <sourcexml>@searchtype</sourcexml> should be dropped.</p>

<pre>
&lt;jrnl:body&gt;
    &lt;jrnl:bodytext searchtype="ARTICLE"&gt;
        &lt;level&gt;
            &lt;bodytext&gt;
                &lt;h l="2" align="left" searchtype="HEADING"&gt;&lt;emph typestyle="bf"&gt;A Introduction&lt;/emph&gt;&lt;/h&gt;
                &lt;p&gt;
                    &lt;text&gt;This study was commissioned by the Insurance Bureau of Canada to identify 
                        legal developments, principally court decisions but also legislation, which could 
                        have had an impact on the cost of liability insurance. We say 'could have' to underline 
                        the limits of the study. We are neither economists nor actuaries and make no claims about 
                        definitive causal connections between cases or statutes and the cost of insurance.  
                        Rather, we examine cases and statutes as lawyers, pointing out where we believe that changes 
                        in the law have increased the exposure of insurers. The quantification of the increase in 
                        cost, if any, we leave to others.&lt;/text&gt;
                &lt;/p&gt;
            &lt;/bodytext&gt;
        &lt;/level&gt;
    &lt;/jrnl:bodytext&gt;
&lt;/jrnl:body&gt;

<b>Becomes</b>

&lt;nitf:body&gt;
  &lt;nitf:body.content&gt;
      &lt;bodytext&gt;
          &lt;section&gt;
              &lt;bodytext&gt;
                  &lt;h level="2" align="left"&gt;&lt;emph typestyle="bf"&gt;A Introduction&lt;/emph&gt;&lt;/h&gt;
                  &lt;p&gt;
                      &lt;text&gt;This study was commissioned by the Insurance Bureau of Canada to identify 
                      legal developments, principally court decisions but also legislation, which could 
                      have had an impact on the cost of liability insurance. We say 'could have' to underline 
                      the limits of the study. We are neither economists nor actuaries and make no claims about 
                      definitive causal connections between cases or statutes and the cost of insurance.  
                      Rather, we examine cases and statutes as lawyers, pointing out where we believe that changes 
                      in the law have increased the exposure of insurers. The quantification of the increase in 
                      cost, if any, we leave to others.&lt;/text&gt;
                  &lt;/p&gt;
              &lt;/bodytext&gt;
          &lt;/section&gt;
      &lt;/bodytext&gt;
  &lt;/nitf:body.content&gt;  
&lt;/nitf:body&gt;
</pre>
      <section>
          <title>Changes</title>
          <p>Created.</p>
      </section>
      
</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Newsitem\Journaldoc-jrnl_bodytext.dita  -->
	<xsl:message>Journaldoc-jrnl_bodytext.xsl requires manual development!</xsl:message> 

	<xsl:template match="jrnl:bodytext">

		<!--  Original Target XPath:  nitf:body.content/bodytext   -->
		<nitf:body.content>
			<bodytext>
				<xsl:apply-templates select="@* | node()"/>
			</bodytext>
		</nitf:body.content>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>