<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl" xmlns:newsitem="http://www.lexisnexis.com/xmlschemas/content/news/newsitem/1/" version="2.0" exclude-result-prefixes="dita jrnl">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="jrnl.info">
  <title>jrnl:info <lnpid>id-MY02-16218</lnpid></title>

  <body>
      <p><sourcexml>jrnl:body/jrnl:info</sourcexml> becomes <targetxml>newsitem:head</targetxml>. The child elements of <sourcexml>jrnl:info</sourcexml> are discussed as individual topics.</p>

<pre>
  
 &lt;jrnl:body&gt;
	&lt;jrnl:info&gt;
          ...
    &lt;/jrnl:info&gt;
&lt;/jrnl:body&gt;
  


<b>Becomes</b>


&lt;newsitem:newsitem&gt;
    &lt;newsitem:head&gt;
       ...
    &lt;/newsitem:head&gt;   
&lt;/newsitem:newsitem&gt;

</pre>
    
</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY02_Journals\jrnl.info.dita  -->
<!--	<xsl:message>jrnl.info.xsl requires manual development!</xsl:message> -->


	<xsl:template match="jrnl:info">
		<newsitem:head>
			<xsl:apply-templates select="node()"/>
		</newsitem:head>
	</xsl:template>

</xsl:stylesheet>