<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl" xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/" version="2.0" exclude-result-prefixes="dita jrnl">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="jrnl.body">
  <title>jrnl:body <lnpid>id-MY02-16216</lnpid></title>

  <body>
    <p><sourcexml>jrnl:body</sourcexml> becomes <targetxml>nitf:body</targetxml>. The child elements of <sourcexml>jrnl:body</sourcexml> are discussed as individual topics.</p>

    <p><targetxml>nitf:body.head</targetxml>, and
        <targetxml>nitf:body.content</targetxml> are created as children of
        <targetxml>nitf:body</targetxml>
    </p>

<pre>
 
 &lt;jrnl:body&gt;
   	...
&lt;/jrnl:body&gt;
 
 


<b>Becomes</b>


&lt;nitf:body&gt;
   &lt;nitf:body.head&gt;
    ...
   &lt;/nitf:body.head&gt;
   &lt;nitf:body.content&gt;
    ...
   &lt;/nitf:body.content&gt;
&lt;/nitf:body&gt;

</pre>
</body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY02_Journals\jrnl.body.dita  -->
<!--	<xsl:message>jrnl.body.xsl requires manual development!</xsl:message> -->

  <xsl:template match="jrnl:body">
    <nitf:body>
      <xsl:apply-templates select="@* | node() except jrnl:info"/>
    </nitf:body>
  </xsl:template>

</xsl:stylesheet>