<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita jrnl">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journal-Newsletter-Bulletins_jrnl_info">
  <title>jrnl:info <lnpid>id-NZ08-24014</lnpid></title>

  <body>
      <p><sourcexml class="+ topic/keyword xml-d/sourcexml ">jrnl:info</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">doc:metadata/pubinfo:pubinfo</targetxml></p>

<pre xml:space="preserve" class="- topic/pre ">
&lt;jrnl:body&gt;
	&lt;jrnl:info&gt;
        &lt;pubdate ln.user-displayed="false"&gt;
            &lt;date month="09" year="1997"&gt;September 1997&lt;/date&gt;
            ...
        &lt;/pubdate&gt;
	&lt;/jrnl:info&gt;
&lt;/jrnl:body&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;doc:metadata&gt;
	&lt;pubinfo:pubinfo&gt;
	   &lt;pubinfo:dates&gt;
            &lt;pubinfo:pubdate month="09" year="1997"/&gt;
            ...
       &lt;/pubinfo:dates&gt;
	&lt;/pubinfo:pubinfo&gt;
&lt;/doc:metadata&gt;
</pre>
      <note>When <b>ln.user-displayed="false"</b> appears on any date element (i.e. <b>pubdate
          ln.user-displayed="false"</b>), that element is translated into the target but with the
          element content omitted.</note>
</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ08_NewsLetter_and_Journals\Journal-Newsletter-Bulletins_jrnl_info.dita  -->
	<!-- <xsl:message>NZ08_NewsLetter_and_Journals_Journal-Newsletter-Bulletins_jrnl_info.xsl requires manual development!</xsl:message> --> 

	<xsl:template match="jrnl:info"/>

</xsl:stylesheet>