<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita jrnl">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK09LegalNews_jrnl_pubsection">
    <title>jrnl:pubsection <lnpid>id-UK09-29017</lnpid></title>
    <body>
        <p><sourcexml>jrnl:pubsection</sourcexml> becomes
                <targetxml>doc:metadata/pubinfo:pubinfo/pubinfo:publicationsubtitle</targetxml></p>
        <example>
            <title>Source XML</title>
            <codeblock>

&lt;jrnl:info&gt;
    &lt;publication&gt;Electronic Business Law&lt;/publication&gt;
    &lt;jrnl:pubsection&gt;The Legal Issues Of Electronic Commerce And Communications&lt;/jrnl:pubsection&gt;
    ...
&lt;/jrnl:info&gt;

           </codeblock>
            <title>Target XML</title>
            <codeblock>

&lt;doc:metadata&gt;
    &lt;pubinfo:pubinfo&gt;
        &lt;pubinfo:publicationname&gt;Electronic Business Law&lt;/pubinfo:publicationname&gt;
        &lt;pubinfo:publicationsubtitle&gt;The Legal Issues Of Electronic Commerce And 
        Communications&lt;/pubinfo:publicationsubtitle&gt;
        ...
    &lt;/pubinfo:pubinfo&gt;
&lt;/doc:metadata&gt;

           </codeblock>
        </example>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK09-LegalNews\UK09LegalNews_jrnl_pubsection.dita  -->
	<!--<xsl:message>UK09LegalNews_jrnl_pubsection.xsl requires manual development!</xsl:message> -->

	<xsl:template match="jrnl:pubsection">

		<!--  Original Target XPath:  doc:metadata/pubinfo:pubinfo/pubinfo:publicationsubtitle   -->
		<!--<doc:metadata>
			<pubinfo:pubinfo >-->
	           <pubinfo:publicationsubtitle xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/">
					<xsl:apply-templates select="@* | node()"/>
				</pubinfo:publicationsubtitle>
			<!--</pubinfo:pubinfo>
		</doc:metadata>-->

	</xsl:template>

</xsl:stylesheet>