<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:admindoc="urn:x-lexisnexis:content:administrative-document:sharedservices:1" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Admindecisions_Introduction">
  <title>Introduction <lnpid>id-CA04-13408</lnpid></title>

  <body>
    <p>This Conversion Instruction describes the conversion of Rosetta CASEDOC DTD to Admindoc 3.10
      PROD schema in the document.</p>
    
    <p>Administrative Decisions are identified using the root element <sourcexml>CASEDOC</sourcexml> with attribute <sourcexml>@type="fulltext"</sourcexml> and also "FOLDER NAME" i.e. "CA_Boards_Tribunals".</p>

    <p><sourcexml>CASEDOC</sourcexml> becomes <targetxml>admindoc:admindoc</targetxml>. Its a root element for Administrative Decisions. The source attribute is: 
      <sourcexml>@type</sourcexml> becomes <targetxml>@admindoctype</targetxml> with value set as <b>administrative-decision</b>.
   </p>
    
    <note>The attribute <sourcexml>@searchtype</sourcexml> will be suppressed from the conversion except citation markup.</note>

<pre>

&lt;CASEDOC type="fulltext"&gt;
        ...
        &lt;docinfo:doc-lang lang="en"/&gt;
        &lt;docinfo:doc-country iso-cc="CA"/&gt;
        ...
&lt;/CASEDOC&gt;
<b>Becomes</b>

&lt;admindoc:admindoc xml:lang="en-CA" type="administrative-decision"&gt;
      
      &lt;admindoc:head&gt;...&lt;/admindoc:head&gt;

      &lt;admindoc:body&gt;...&lt;/admindoc:body&gt;

      &lt;doc:metadata&gt;...&lt;/doc:metadata&gt;
      
&lt;/admindoc:admindoc&gt;
</pre>

    <p><targetxml>admindoc:head</targetxml>, <targetxml>admindoc:body</targetxml>, and <targetxml>doc:metadata</targetxml> are created as required children of <targetxml>admindoc:admindoc</targetxml></p>

    <section>
      <title>Note:</title>
      <p>Source elements and attributes are highlighted like this: <sourcexml>SOURCEXML</sourcexml></p>
      <p>Target elements and attributes are highlighted like this: <targetxml>TARGETXML</targetxml></p>
      <p>Copy source attributes to target attributes unless otherwise specified.</p>
      <p>Every example is represented like "EXAMPLE" in all the dita's and is captured
        under <pre>pre</pre>  tag.</p>
    </section>
  </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA04-Administrative_Decisions\Admindecisions_Introduction.dita  -->
	<!--<xsl:message>Admindecisions_Introduction.xsl requires manual development!</xsl:message>--> 
  <xsl:param name="outputSchemaLoc"
    select="'urn:x-lexisnexis:content:administrative-document:sharedservices:1 sch_admindoc.xsd'"/>
  
  <!-- map  CA04 Rosetta CASEDOC to LexAdv Admindoc  -->
  <xsl:output indent="yes" method="xml"/>
  <xsl:key name="idTypeValue" match="*[@id]" use="@id"/>
  <xsl:key name="idTypeValue" match="*[@ID]" use="@ID"/>
  <xsl:key name="idTypeValue" match="footnote" use="@fntoken"/>
  <xsl:key name="idTypeValue" match="fnr" use="@fnrtoken"/>
  <xsl:key name="fnr-footnote-tokens" match="fnr" use="@fntoken"/>
  
  <xsl:variable name="streamID" as="xs:string" select="'CA04'"/>
  <xsl:param name="dpsi" as="xs:string" select="'From LBU Manifest File'"/>
  <xsl:param name="smi" as="xs:string" select="'From LBU Manifest File'"/>
  
  <xsl:param name="inlineobjBoilerplateFiles"/>
  <xsl:param name="inlineobjFilesToSuppress" select="('1.gif', '2.gif', '3.gif', '4.gif', '5.gif', 'IconSignalPositive.gif', 'IconSignalNegative.gif', 'IconSignalNeutral.gif', 'IconSignalPossibleNegative.gif', 'IconSignalCiteInfoOnly.gif', 'cbcc.gif', 'leg1.gif', 'mb.gif', 'au_repealed.gif', 'au_exclaim.gif', '1.png', '2.png', '3.png', '4.png', '5.png', 'IconSignalPositive.png', 'IconSignalNegative.png', 'IconSignalNeutral.png', 'IconSignalPossibleNegative.png', 'IconSignalCiteInfoOnly.png', 'cbcc.png', 'leg1.png', 'mb.png', 'au_repealed.png', 'au_exclaim.png')"/>
  
	<xsl:template match="CASEDOC">

		
		<admindoc:admindoc>
		  <xsl:call-template name="generateNSGlobalBindings"/>
		  
		  <xsl:attribute name="xsi:schemaLocation" select="$outputSchemaLoc"/>
		  <xsl:call-template name="xml_lang"/>
			<xsl:apply-templates select="@*"/>
		  <admindoc:head>
		    <xsl:apply-templates select="case:body/case:headnote/case:info[1]" />
		    <xsl:apply-templates select="case:body/case:headnote/case:priorhist" />
		    <xsl:apply-templates select="case:body/case:headnote/case:decisionsummary|/CASEDOC/case:body/case:headnote/catchwordgrp|/CASEDOC/case:body/case:headnote/case:references"/>
		  </admindoc:head>
			
		  
		  <admindoc:body>
		    <xsl:apply-templates select="case:body/case:headnote/case:info/case:constituents|case:body/case:content"/>
		  </admindoc:body>
		  
			<doc:metadata>
				<xsl:apply-templates select="docinfo"/>
			</doc:metadata>
		</admindoc:admindoc>
	</xsl:template>

  <xsl:template match="CASEDOC/@type">
    <xsl:attribute name="admindoctype">
      <xsl:text>administrative-decision</xsl:text>
    </xsl:attribute>
  </xsl:template>
	
</xsl:stylesheet>