<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:casedigest="http://www.lexisnexis.com/xmlschemas/content/legal/case-digest/1/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:dig="http://www.lexis-nexis.com/glp/dig" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" 
  xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Case-Summaries_Introduction">
  <title>Introduction <lnpid>id-CA02DC-12636</lnpid></title>
  <shortdesc>This Conversion Instructions describes the conversion of the Rosetta DIGESTDOC DTD to
    <b>casedigest Version 7.5_PROD</b> schema.</shortdesc>
  <body>
    
    <p>CA Case Summaries DIGESTDOC based samples are identified using the root element <sourcexml>DIGESTDOC</sourcexml> 
      and without any <sourcexml>DIGESTDOC/@type</sourcexml> attribute.</p>

    <section>
      <sourcexml>DIGESTDOC</sourcexml> becomes <targetxml>casedigest:casedigest</targetxml>. The source attribute <sourcexml>@xml:lang</sourcexml>, if present, can be dropped, 
      as a separate rule has been defined to populate <targetxml>casedigest:casedigest/@xml:lang</targetxml>. 
    </section>
    <section>
      <note>The attribute <sourcexml>@searchtype</sourcexml> will be suppressed from the conversion
        except citation markup.</note>
      <pre>

&lt;DIGESTDOC&gt;
    ......
    &lt;docinfo:doc-lang lang="en"/&gt;
    &lt;docinfo:doc-country iso-cc="CA"/&gt;
    ......          
&lt;/DIGESTDOC&gt;


          <b>Becomes</b>


&lt;casedigest:casedigest xml:lang="en-CA"&gt;
    ......
&lt;/casedigest:casedigest&gt;

      </pre>
      <note>Elements <targetxml>casedigest:head</targetxml>, <targetxml>casedigest:body</targetxml>
        and <targetxml>doc:metadata</targetxml> are created as required children of root element
        <targetxml>casedigest:casedigest</targetxml> during conversion</note>      
      <note>If there is empty element found in Rosetta input, then conversion need <b>not</b> to create target empty element.</note>
      <note>If there is no head related information found in input document, then conversion
        will create an empty tag of <targetxml>casedigest:head</targetxml> in output.</note>
      

&lt;casedigest:head&gt;
    .......
&lt;/casedigest:head&gt;

      
      <p><b>Note:</b></p>
      <p>Source elements and attributes are highlighted like this:
        <sourcexml>SOURCEXML</sourcexml></p>
      <p>Target elements and attributes are highlighted like this:
        <targetxml>TARGETXML</targetxml></p>
      <p>Copy source attributes to target attributes unless otherwise specified.</p>
      <p>Every example is represented like EXAMPLE in all the Conversion Instructions
        and is captured under <pre>pre</pre> tag.</p>
    </section>
  </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA02-Case_Summaries\CA02DC_DIGESTDOC_to_casedigest\Introduction.dita  -->
 <xsl:variable name="xml_lang">
   <xsl:value-of select="concat(/DIGESTDOC/docinfo/docinfo:doc-lang/@lang,'-',/DIGESTDOC/docinfo/docinfo:doc-country/@iso-cc)"/>
 </xsl:variable>

  <xsl:template match="DIGESTDOC">    
    <!--  Original Target XPath:  courtcase:courtcase   -->
    <xsl:element name="casedigest:casedigest">
    
      <xsl:call-template name="generateNSGlobalBindings"/>
  
      <xsl:attribute name="xsi:schemaLocation" select="$outputSchemaLoc"/>
      <xsl:attribute name="xml:lang" select="$xml_lang"/>      
      <xsl:element name="casedigest:head">
        <xsl:apply-templates select="dig:body/dig:info[1]/case:info"/>     
      </xsl:element>
      
      <xsl:apply-templates select="dig:body"/>
      <!-- doc:metadata   -->
      
      <xsl:element name="doc:metadata">
        <xsl:apply-templates select="docinfo"/>
      </xsl:element>
    </xsl:element>
    
  </xsl:template>


	<xsl:template match="DIGESTDOC/@type">
			<xsl:copy-of select="."/>
	</xsl:template>



</xsl:stylesheet>