<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="unemployment-duration">
   <title>unemployment-duration <lnpid>id-CA02DC-12639</lnpid></title>
   <body>
      <section>
<ul>
         <li><sourcexml>unemployment-duration</sourcexml> becomes
                        <targetxml>person:person/person:bio/person:bio.detail/person:bio.unemployment</targetxml>,
                    and create children <targetxml>bodytext/textitem</targetxml> within
                        <targetxml>person:bio.unemployment</targetxml>. <pre>


&lt;dig:action-party&gt;
    .........
    .........
    &lt;unemployment-duration&gt;
        &lt;duration&gt;18 months unemployment&lt;/duration&gt;
    &lt;/unemployment-duration&gt;
&lt;/dig:action-party&gt;

                    </pre>
                    <b>Becomes</b>
                    <pre>

&lt;casedigest:actionparty partyrole="unknown"&gt;
    ...........
    ...........
    &lt;person:person&gt;
        &lt;person:bio&gt;
            &lt;person:bio.detail&gt;
                &lt;person:bio.unemployment&gt;
                    &lt;bodytext&gt;
                        &lt;textitem&gt;
                            &lt;duration&gt;18 months unemployment&lt;/duration&gt;
                        &lt;/textitem&gt;
                    &lt;/bodytext&gt;
                &lt;/person:bio.unemployment&gt;
            &lt;/person:bio.detail&gt;
        &lt;/person:bio&gt;
    &lt;/person:person&gt; 
&lt;/casedigest:actionparty&gt;
    

               </pre>
                    
                </li>
    
      </ul>
</section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA02-Case_Summaries\CA02DC_DIGESTDOC_to_casedigest\unemployment-duration.dita  -->
 
    <!-- Vikas Rohilla : Updated the template -->
    <xsl:template match="unemployment-duration">
        <person:person>
            <person:bio>
                <person:bio.detail>
                    <person:bio.unemployment>
                        <bodytext>
                            <textitem>
                                <xsl:apply-templates select="@* | node()"/>
                            </textitem>
                        </bodytext>
                    </person:bio.unemployment>
                </person:bio.detail>
            </person:bio>
        </person:person>
    </xsl:template>

</xsl:stylesheet>