<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" xmlns:dita="http://dita.oasis-open.org/architecture/2005/"  version="2.0" exclude-result-prefixes="dita caseinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="abbrvname">
   <title>abbrvname <lnpid>id-CA02DS-12807</lnpid></title>
   <body>
      <section>
            <ul>
                <li>
                    <sourcexml>abbrvname</sourcexml> becomes <targetxml>jurisinfo:courtname@normshortname</targetxml> and also
                        <targetxml>jurisinfo:alternatecourtcode@alternatecourtcode</targetxml>. <pre>
&lt;dig:body&gt;
  &lt;dig:collection&gt;
    &lt;dig:level&gt;
      &lt;dig:item&gt;
        &lt;dig:info&gt;
          &lt;case:info&gt;
            &lt;case:courtinfo&gt;
              &lt;abbrvname ln.user-displayed="false"&gt;SKProvCt&lt;/abbrvname&gt;
            &lt;/case:courtinfo&gt;
          &lt;/case:info&gt;
        &lt;/dig:info&gt;
      &lt;/dig:item&gt;
    &lt;/dig:level&gt;
  &lt;/dig:collection&gt;
&lt;/dig:body&gt;
</pre>
                    <b>Becomes</b>
                    <pre>
&lt;seclaw:body&gt;
  &lt;seclaw:level&gt;
    &lt;seclaw:bodytext&gt;
      &lt;seclaw:digestgrp&gt;
        &lt;seclaw:digest&gt;
          &lt;seclaw:digestinfo&gt;
            &lt;caseinfo:caseinfo&gt;
              &lt;jurisinfo:courtinfo&gt;
                &lt;jurisinfo:alternatecourtcode alternatecourtcode="SKProvCt"/&gt;
                &lt;jurisinfo:courtname normshortname="SKProvCt"&gt;Saskatchewan Provincial Court Small Claims Court&lt;/jurisinfo:courtname&gt;
              &lt;/jurisinfo:courtinfo&gt;
            &lt;/caseinfo:caseinfo&gt;
          &lt;/seclaw:digestinfo&gt;
        &lt;/seclaw:digest&gt;
      &lt;/seclaw:digestgrp&gt;
    &lt;/seclaw:bodytext&gt;
  &lt;/seclaw:level&gt;
&lt;/seclaw:body&gt;
</pre>
                    <note>@ln.user-displayed is ignored in the conversion of this element.</note>
                </li>
            </ul>
        </section>
       <section><title>Changes</title>
           <p>2014-10-22<ph id="change_20141022"> Updated CI for <sourcexml>abbrvname</sourcexml> to also be placed in
                        <targetxml>jurisinfo:alternatecourtcode@alternatecourtcode</targetxml>...R4.5 Db issue #1987</ph></p>
       </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA02-Case_Summaries\CA02DS_DIGESTDOC_to_seclaw\abbrvname.dita  -->
	 
  <!--	 Vikas Rohilla : Template to match the abbrvname and creates the caseinfo:casename/caseinfo:shortcasename-->
  <xsl:template match="abbrvname">
    <caseinfo:casename>
      <caseinfo:shortcasename>
        <xsl:apply-templates select="@* | node()"/>
      </caseinfo:shortcasename>
    </caseinfo:casename>
  </xsl:template>

</xsl:stylesheet>