<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
  xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"
  xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"
  xmlns:lnci="http://www.lexisnexis.com/xmlschemas/content/shared/citations/1/"
  xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/"
  xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/"
  xmlns:dig="http://www.lexis-nexis.com/glp/dig"
  xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0"
  exclude-result-prefixes="dita dig doc seclaw docinfo">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Introduction">
    <title>Introduction <lnpid>id-CA02DS-12835</lnpid></title>
    <shortdesc>This Conversion Instructions describes the conversion of the Rosetta DIGESTDOC DTD to
        <b>Seclaw 8.6_PROD</b> schema.</shortdesc>
    <body>

      <p>CA Case Summaries DIGESTDOC based samples are identified using the root element
          <sourcexml>DIGESTDOC</sourcexml> with attribute
          <sourcexml>DIGESTDOC/@type="case-summary"</sourcexml> and with
          <sourcexml>dig:collection</sourcexml>, <sourcexml>dig:level</sourcexml>, and
          <sourcexml>dig:item</sourcexml> elements.</p>

      <section>
        <sourcexml>DIGESTDOC</sourcexml> becomes <targetxml>seclaw:seclaw</targetxml> which has a
        required attribute <targetxml>@seclawtype</targetxml>, the value of this attribute will be
          <targetxml>@seclawtype="digest"</targetxml>. The source attribute
          <sourcexml>@xml:lang</sourcexml>, if present, can be dropped, as a separate rule has been
        defined to populate <targetxml>seclaw:seclaw/@xml:lang</targetxml>. </section>
      <section>
        <note>The attribute <sourcexml>@searchtype</sourcexml> will be suppressed from the
          conversion except citation markup.</note>
        <pre>
          &lt;DIGESTDOC type="case-summary"&gt;
                      ...
                      &lt;docinfo:doc-lang lang="en"/&gt;
                      &lt;docinfo:doc-country iso-cc="CA"/&gt;
                      ...          
           &lt;/DIGESTDOC&gt;

          <b>Becomes</b>

              &lt;seclaw:seclaw seclawtype="digest" xml:lang="en-CA"&gt;
                        ...
               &lt;/seclaw:seclaw&gt;
      </pre>
        <note>Elements <targetxml>seclaw:head</targetxml>, <targetxml>seclaw:body</targetxml> and
            <targetxml>doc:metadata</targetxml> are created as required children of root element
            <targetxml>seclaw:seclaw</targetxml> during conversion.</note>
        <p>
          <b>Note:</b>
        </p>
        <p>Source elements and attributes are highlighted like this:
            <sourcexml>SOURCEXML</sourcexml></p>
        <p>Target elements and attributes are highlighted like this:
            <targetxml>TARGETXML</targetxml></p>
        <p>Copy source attributes to target attributes unless otherwise specified.</p>
        <p>Every example is represented like EXAMPLE in all the Conversion Instructions and is
          captured under <pre>pre</pre> tag.</p>
      </section>
    </body>

  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA02-Case_Summaries\CA02DS_DIGESTDOC_to_seclaw\Introduction.dita  -->

  <!-- Vikas Rohilla : Creted the template to match the  DIGESTDOC-->
  
  <xsl:param name="outputSchemaLoc"
    select="'http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/ sch_seclaw.xsd'"/>
  
  
  <!-- Vikas Rohilla: Added	-->
  <!-- map  CA01 Rosetta CASEDOC to LxAdv courtcase  -->
  <xsl:key name="idTypeValue" match="*[@id]" use="@id"/>
  <xsl:key name="idTypeValue" match="*[@ID]" use="@ID"/>
  <xsl:key name="idTypeValue" match="footnote" use="@fntoken"/>
  <xsl:key name="idTypeValue" match="fnr" use="@fnrtoken"/>
  <xsl:key name="fnr-footnote-tokens" match="fnr" use="@fntoken"/>
  
  <xsl:variable name="streamID" as="xs:string" select="'CA02DS'"/>
  <xsl:param name="dpsi" as="xs:string" select=" 'From LBU Manifest File' "/>
  <xsl:param name="smi" as="xs:string" select=" 'From LBU Manifest File' "/>
  
  <xsl:param name="inlineobjBoilerplateFiles"/>
  <xsl:param name="inlineobjFilesToSuppress" select="('1.gif', '2.gif', '3.gif', '4.gif', '5.gif', 'IconSignalPositive.gif', 'IconSignalNegative.gif', 'IconSignalNeutral.gif', 'IconSignalPossibleNegative.gif', 'IconSignalCiteInfoOnly.gif', 'cbcc.gif', 'leg1.gif', 'mb.gif', 'au_repealed.gif', 'au_exclaim.gif', '1.png', '2.png', '3.png', '4.png', '5.png', 'IconSignalPositive.png', 'IconSignalNegative.png', 'IconSignalNeutral.png', 'IconSignalPossibleNegative.png', 'IconSignalCiteInfoOnly.png', 'cbcc.png', 'leg1.png', 'mb.png', 'au_repealed.png', 'au_exclaim.png')"/>
  
  <xsl:template match="DIGESTDOC">
    <!--  Original Target XPath:  courtcase:courtcase   -->
    <xsl:element name="seclaw:seclaw">
      <xsl:call-template name="generateNSGlobalBindings"/>
   
      <xsl:attribute name="xsi:schemaLocation" select="$outputSchemaLoc"/>

      <!--	@attribute xml:lang	  -->
      <!-- Awantika:2017-11-10- updated the call template from xml_lang_HK to xml_lang -->
      <xsl:call-template name="xml_lang"/>

      <!--Attribute seclawtype-->
      <xsl:attribute name="seclawtype">
        <xsl:text>digest</xsl:text>
      </xsl:attribute>

      <!-- seclaw:head			-->
      <xsl:element name="seclaw:head">
        <ref:citations>
          <xsl:apply-templates select="dig:body/dig:collection/dig:level/dig:info/dig:cite"/>
        </ref:citations>
      </xsl:element>

      <!--seclaw:body			-->
      <xsl:apply-templates select="dig:body"/>
      <!-- doc:metadata   -->

      <!-- doc:metadata			-->
      <xsl:element name="doc:metadata">
        <xsl:element name="pubinfo:pubinfo">
          <xsl:apply-templates select="dig:body/dig:collection/dig:level/dig:info/publication"/>
        </xsl:element>
        <xsl:apply-templates select="docinfo"/>
      </xsl:element>
    </xsl:element>
  </xsl:template>

  <!-- Supressed @type	-->
  <xsl:template match="DIGESTDOC/@type"/>

</xsl:stylesheet>
