<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/"
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" version="2.0"
    exclude-result-prefixes="dita">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="employment-duration">
        <title>employment-duration <lnpid>id-CA02DC-12635</lnpid></title>
        <body>
            <section>
                <ul>
                    <li>
                        <sourcexml>occupation/employment-duration</sourcexml> becomes
                            <targetxml>person:person/person:bio/person:bio.detail/person:bio.employment</targetxml>,
                        and create children <targetxml>bodytext/textitem</targetxml> within
                            <targetxml>person:bio.employment</targetxml>. <note>In this scenario
                            Rosetta element <sourcexml>occupation</sourcexml> will be omitted during
                            conversion, So Rosetta XPATH scenario:
                                <sourcexml>/dig:cause-of-action/dig:action-party/occupation/employment-duration/duration</sourcexml>
                            will become
                                <targetxml>/casedigest:causeofaction/casedigest:actionparty/person:person/person:bio/person:bio.detail/person:bio.employment/bodytext/textitem/duration
                            </targetxml></note>
                        <pre>


&lt;dig:cause-of-action&gt;
    &lt;dig:action-party&gt;
        .........
        .........
        &lt;occupation&gt;
            &lt;employment-duration&gt;
                &lt;duration searchtype="YEARS-EMPLOYED"&gt;15 years service&lt;/duration&gt;
            &lt;/employment-duration&gt;
        &lt;/occupation&gt;
    &lt;/dig:action-party&gt;
&lt;/dig:cause-of-action&gt;

                    </pre>
                        <b>Becomes</b>
                        <pre>

&lt;casedigest:causeofaction partyrole="unknown"&gt;
    &lt;casedigest:actionparty&gt;
        ...........
        ...........
        &lt;person:person&gt;
            &lt;person:bio&gt;
                &lt;person:bio.detail&gt;
                    &lt;person:bio.employment&gt;
                        &lt;bodytext&gt;
                            &lt;textitem&gt;
                                &lt;duration&gt;15 years service&lt;/duration&gt;
                            &lt;/textitem&gt;
                        &lt;/bodytext&gt;
                    &lt;/person:bio.employment&gt;
                &lt;/person:bio.detail&gt;
            &lt;/person:bio&gt;
        &lt;/person:person&gt; 
    &lt;/casedigest:actionparty&gt;
&lt;/casedigest:causeofaction&gt; 
    

               </pre>
                    </li>

                </ul>
            </section>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA02-Case_Summaries\CA02DC_DIGESTDOC_to_casedigest\employment-duration.dita  -->

    <!-- Vikas Rohilla : Updated the template Initial-->
    <xsl:template match="occupation/employment-duration">
        <bodytext>
            <textitem>
                <xsl:apply-templates select="@* | node()"/>
            </textitem>
        </bodytext>
    </xsl:template>




</xsl:stylesheet>
