<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"
	xmlns:leg="http://www.lexis-nexis.com/glp/leg"
	xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"
	xmlns:regulation="urn:x-lexisnexis:content:regulation:sharedservices:1" version="2.0"
	exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Introduction">
		<title>Introduction <lnpid>id-CA06-13809</lnpid></title>
		<body>
			<p>
				<u>This Conversion Instruction describes the conversion of the <sourcexml>Rosetta
						LEGDOC DTD</sourcexml> to <targetxml>Regulation Schema (Version 8.2
						PROD)</targetxml>.</u>
			</p>
			<section>
				<title>Root Element</title>
				<p>Identification Criteria for <b>CA06 Regulation</b> content stream is root element
						<sourcexml>LEGDOC</sourcexml> and <sourcexml>docinfo:selector</sourcexml>
					having value as "REGULATIONS" (case-sensitive):- <sourcexml>LEGDOC</sourcexml>
					<b>becomes</b>
					<targetxml>regulation:regulation</targetxml>. This is the root element for the
					regulation schema, attributes are populated as follows:</p>
				<p> If document contains <sourcexml>LEGDOC[@id]</sourcexml>
					<b>becomes</b>
					<targetxml>regulation:regulation[@xml:id]</targetxml> and provides a unique
					identifier for this document.</p>
				<p>Create <targetxml>regulation:regulation[@xml:lang]</targetxml> which is used to
					specify the language that is being used in the content/document. The presence or
					absence of attribute value will not affect delivery product behavior and default
					value is 'none'. <pre>
              <b><i>Example: Source XML 1</i></b>


&lt;LEGDOC &gt;
	&lt;docinfo:doc-lang lang="en"/&gt;
	&lt;docinfo:doc-country iso-cc="CA"/&gt;
	...
&lt;/LEGDOC&gt;



	</pre>
					<pre>

              <b><i>Example: Target XML 1</i></b>


&lt;regulation:regulation xml:lang="en-CA"&gt;
    ...
&lt;/regulation:regulation&gt;

            </pre>
				</p>

				<p>
					<targetxml>regulation:head</targetxml>, <targetxml>regulation:body</targetxml>,
					and <targetxml>doc:metadata</targetxml> are created as required children of
						<targetxml>regulation:regulation</targetxml>. </p>

				<p>The <sourcexml>@searchtype</sourcexml> attribute will be dropped from conversion
					except for the citation element.</p>

			</section>

			<section>
				<title>Notes</title>
				<p>The following information is meant to help the user understand the conventions
					used in this document.</p>
				<p>Source elements and attributes are highlighted like this: <sourcexml>XML
						SOURCE</sourcexml></p>
				<p>Target elements and attributes are highlighted like this: <targetxml>XML
						TARGET</targetxml></p>
				<p>Verify content of following target attributes: <ul>
						<li><sourcexml>@year</sourcexml> becomes <targetxml>@year</targetxml> is 4
							digits in length. Any other lengths, do not output
								<targetxml>@year</targetxml>.</li>
						<li><sourcexml>@month</sourcexml> becomes <targetxml>@month</targetxml> is
							between 01-12. Any numbers outside this range, do not output a
								<targetxml>@month</targetxml>.</li>
						<li><sourcexml>@day</sourcexml> becomes <targetxml>@day</targetxml> is
							between 01-31. Any numbers outside this range, do not output
								<targetxml>@day</targetxml>.</li> </ul>
				</p>
			</section>
		</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA06-Regulation\Introduction.dita  -->
	<!--	<xsl:message>CA06-Regulation_Introduction.xsl requires manual development!</xsl:message> -->
	<!--
	<xsl:template match="Rosetta LEGDOC&#xA;                    DTD">

		<!-\-  Original Target XPath:  RegulationSchema(Version8.2PROD)   -\->
		<!-\-  Could not determine target element or attribute name:  <RegulationSchema(Version8.2PROD)>  -\->			<xsl:apply-templates select="@* | node()"/>
		<!-\-  Could not determine target element or attribute name:  </RegulationSchema(Version8.2PROD)>  -\->

	</xsl:template>-->

	<xsl:template match="LEGDOC">

		<!--  Original Target XPath:  regulation:regulation   -->
		<regulation:regulation>
			<xsl:for-each select="$lexisAdvNamespaces/*">
				<xsl:sort/>
				<xsl:namespace name="{substring-after(substring-before(., '='), ':')}"
					select="substring-after(translate(., '&#034;', ''), '=')"/>
			</xsl:for-each>
			
			<xsl:call-template name="xml_lang"/>
			<xsl:apply-templates select="leg:body/leg:info"/>
			<doc:metadata>
				<xsl:apply-templates select="docinfo"/>
			</doc:metadata>
		</regulation:regulation>

	</xsl:template>

	<!--	<xsl:template match="docinfo:selector">

		<!-\-  Original Target XPath:  regulation:regulation   -\->
		<regulation:regulation>
			<xsl:apply-templates select="@* | node()"/>
		</regulation:regulation>

	</xsl:template>

	<xsl:template match="LEGDOC[@id]">

		<!-\-  Original Target XPath:  regulation:regulation[@xml:id]   -\->
		<regulation:regulation>
			<xsl:apply-templates select="@* | node()"/>
		</regulation:regulation>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!-\-  Original Target XPath:  XMLTARGET   -\->
		<XMLTARGET>
			<xsl:apply-templates select="@* | node()"/>
		</XMLTARGET>

	</xsl:template>

	<xsl:template match="XML SOURCE">

		<!-\-  Original Target XPath:  XMLTARGET   -\->
		<XMLTARGET>
			<xsl:apply-templates select="@* | node()"/>
		</XMLTARGET>

	</xsl:template>

	<xsl:template match="@year">

		<!-\-  Original Target XPath:  @year   -\->
		<xsl:attribute name="year">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="@month">

		<!-\-  Original Target XPath:  @month   -\->
		<xsl:attribute name="month">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="@day">

		<!-\-  Original Target XPath:  @day   -\->
		<xsl:attribute name="day">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>-->

</xsl:stylesheet>
