<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="CA10_Rosetta_remotelink-Chof-bodytext-LxAdv-p_text_ref.crossreference">
    <title>When <sourcexml>remotelink</sourcexml> is a child of <sourcexml>bodytext</sourcexml> <lnpid>id-CA10-14629</lnpid></title>
 <body>
     <section>
         <p>When <sourcexml>remotelink</sourcexml> is a child of <sourcexml>bodytext</sourcexml> then
             conversion should generate <targetxml>ref:crossreference</targetxml> inside previous <targetxml>p</targetxml> element.</p></section>
  <example>
   <title>Source XML </title>
   <codeblock>
&lt;bodytext&gt;
    &lt;p&gt;
        &lt;text&gt;maladie professionnelle &lt;remotelink dpsi="0UNL" refpt="18-120" remotekey1="REFPTID"
                service="DOC-ID" status="valid"&gt;18-120&lt;/remotelink&gt;;&lt;/text&gt;
    &lt;/p&gt;
    &lt;remotelink dpsi="0UNL" refpt="18-402" remotekey1="REFPTID" service="DOC-ID" status="valid"
        &gt;18-402&lt;/remotelink&gt;
&lt;/bodytext&gt;
            </codeblock>
   <title>Target XML</title>
   <codeblock>
&lt;seclaw:bodytext&gt;
    &lt;p&gt;
        &lt;text&gt;maladie professionnelle &lt;ref:crossreference crossreferencetype="seeAlso"&gt;
                &lt;ref:content&gt;18-120&lt;/ref:content&gt;
                &lt;ref:locator&gt;
                    &lt;ref:locator-key&gt;
                        &lt;ref:key-name name="DOC-ID"/&gt;
                        &lt;ref:key-value value="0UNL-18-120"/&gt;
                    &lt;/ref:locator-key&gt;
                &lt;/ref:locator&gt;
            &lt;/ref:crossreference&gt;
            &lt;ref:crossreference crossreferencetype="seeAlso"&gt;
                &lt;ref:content&gt;18-402&lt;/ref:content&gt;
                &lt;ref:locator&gt;
                    &lt;ref:locator-key&gt;
                        &lt;ref:key-name name="DOC-ID"/&gt;
                        &lt;ref:key-value value="0UNL-18-402"/&gt;
                    &lt;/ref:locator-key&gt;
                &lt;/ref:locator&gt;
            &lt;/ref:crossreference&gt;
        &lt;/text&gt;
    &lt;/p&gt;
&lt;/seclaw:bodytext&gt;
            </codeblock>
  </example>
  <section>
   <title>Changes</title>
   <p>2016-04-28: <ph id="change_20160428_PS">Created.</ph></p>
  </section>
 </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA10-Treatise_Textbook_Forms\Rosetta_remotelink-Chof-bodytext-LxAdv-p_text_ref.crossreference.dita  -->
	<!--<xsl:message>CA10-Treatise_Textbook_Forms_Rosetta_remotelink-Chof-bodytext-LxAdv-p_text_ref.crossreference.xsl requires manual development!</xsl:message> -->
	

</xsl:stylesheet>