<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="CA10_remotelink">
  <title><sourcexml>remotelink[@service='QUERY']</sourcexml> for CA10 <lnpid>id-CA10-14618</lnpid></title>
  <body>
    <section>
      <p>When <sourcexml>remotelink[@service='QUERY']</sourcexml>, the mark-up shall be suppressed.
                However, for this conversion, <sourcexml>remotelink</sourcexml> children and/or
                content shall be retained.</p>
    </section>
    <example>
      <title>Source XML</title>
      <codeblock>

&lt;bodytext searchtype="COMMENTARY"&gt;
    &lt;p&gt;
        &lt;text&gt;Editor's note: For current versions of legislation, regulations and
            treaties, please see the Legislation sources.&lt;/text&gt;
    &lt;/p&gt;
    &lt;p&gt;
        &lt;text&gt;
            &lt;remotelink service="QUERY" dpsi="03JC"
                remotekey1="LEG-NUM(R.S.C. 1985 c C-44)"&gt;
                Canada Business Corporations Act, R.S.C. 1985, c. C-44
            &lt;/remotelink&gt;
        &lt;/text&gt;
    &lt;/p&gt;
&lt;/bodytext&gt;

	</codeblock>
    </example>
    <example>
      <title>Target XML</title>
      <codeblock>

&lt;bodytext&gt;
    &lt;p&gt;
        &lt;text&gt;Editor's note: For current versions of legislation, regulations and
            treaties, please see the Legislation sources.&lt;/text&gt;
    &lt;/p&gt;
    &lt;p&gt;
        &lt;text&gt;            
            Canada Business Corporations Act, R.S.C. 1985, c. C-44
        &lt;/text&gt;
    &lt;/p&gt;
&lt;/bodytext&gt;

	</codeblock>
    </example>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA10-Treatise_Textbook_Forms\CA10_remotelink.dita  -->
	<!--<xsl:message>CA10_remotelink.xsl requires manual development!</xsl:message> -->
<!-- This is handled in CA10_Body.xsl -->
	<!--<xsl:template match="remotelink[@service='QUERY']">
			<xsl:apply-templates select="node()"/>
	</xsl:template>-->



</xsl:stylesheet>