<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="CA10_note-level">
    <title>note as direct child of level <lnpid>id-CA10-14626</lnpid></title>
    <body>
        <section>
            <sectiondiv>
                <p>If the <sourcexml>level</sourcexml> contains a child <sourcexml>note</sourcexml> that is empty, the child <sourcexml>note</sourcexml> should be suppressed.</p>
            </sectiondiv>
            <sectiondiv>
                <p>If the <sourcexml>level</sourcexml> contains a child <sourcexml>note</sourcexml> that only contains a <sourcexml>refpt</sourcexml>, then a <targetxml>ref:anchor</targetxml> should be created as a direct child of the <targetxml>seclaw:level</targetxml>.</p>
                <sectiondiv>
                    <p><sourcexml>note/refpt/@id</sourcexml> becomes <targetxml>note/ref:anchor/@id</targetxml>.  The datatype of the target @id attribute is of type ID so the value must be made to adhere.  If the value of @id does not begin with an underscore, prepend the value with an underscore.</p>
                    <p>The value of <sourcexml>note/refpt/@type</sourcexml> is used to derive the value for <targetxml>note/ref:anchor/@anchortype</targetxml>.  
                        <ul>
                            <li>If the value of @type is 'ext', use value of 'global' to populate @anchortype.</li>
                            <li>Otherwise, use value of 'local' to populate @anchortype.</li>
                        </ul>.</p>
                </sectiondiv>
            </sectiondiv>
        </section>
        <example>
            <title>Source XML</title>
            <codeblock>

&lt;level leveltype="3"&gt;
  &lt;note&gt;
    &lt;refpt id="4.1" type="ext"/&gt;
  &lt;/note&gt;
  ...

	        </codeblock>
        </example>
        <example>
            <title>Target XML</title>
            <codeblock>

&lt;seclaw:level&gt;
  &lt;ref:anchor id="_141" anchortype="global" /&gt;

	        </codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>2016-03-22: <ph id="change_20160322_note_1">Added instructions for handling <sourcexml>note</sourcexml> when it occurs as a direct child of <sourcexml>level</sourcexml>.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA10-Treatise_Textbook_Forms\CA10_note-level.dita  -->
	<!--<xsl:message>CA10_note-level.xsl requires manual development!</xsl:message> -->

<xsl:template match="level/note">
	<xsl:choose>
		<xsl:when test="not(child::*)"/>
		<xsl:when test="child::refpt">
			<xsl:apply-templates select="refpt"/>
		</xsl:when>
		<xsl:otherwise>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:otherwise>
	</xsl:choose>
</xsl:template>

	<xsl:template match="note/refpt">
		<ref:anchor>
			<xsl:apply-templates select="@*"/>
		</ref:anchor>
	</xsl:template>
	
	<xsl:template match="note/refpt/@id">
		<xsl:attribute name="id">
			<xsl:choose>
				<xsl:when test="starts-with(.,'_')">
					<xsl:value-of select="."/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:text>_</xsl:text>
					<xsl:value-of select="."/>
				</xsl:otherwise>
			</xsl:choose>	
		</xsl:attribute>
	</xsl:template>

	<xsl:template match="note/refpt/@type" priority="25">
		<xsl:attribute name="anchortype">
			<xsl:choose>
				<xsl:when test="contains(.,'ext')">
					<xsl:text>global</xsl:text>
				</xsl:when>
				<xsl:otherwise>
					<xsl:text>local</xsl:text>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:attribute>
		
	</xsl:template>
</xsl:stylesheet>