<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns:ci="http://www.lexis-nexis.com/ci"
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:dict="urn:x-lexisnexis:content:dict:sharedservices:1" version="2.0"
    exclude-result-prefixes="dita">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
        id="CA12_CA-Dictionaries_references">
        <title>references <lnpid>id-CA12-15018</lnpid></title>

        <body>
            <p><sourcexml class="+ topic/keyword xml-d/sourcexml ">references</sourcexml> becomes
                    <targetxml class="+ topic/keyword xml-d/targetxml "
                    >dict:body/dict:additionalmaterials/@materialstype="references"</targetxml>.</p>

            <p>Create <targetxml>bodytext</targetxml> as a child of <targetxml
                    class="+ topic/keyword xml-d/targetxml "
                >dict:additionalmaterials</targetxml>.</p>
            <pre xml:space="preserve" class="- topic/pre ">&lt;references&gt;
    &lt;heading&gt;
        &lt;title&gt;Other reference(s)/Autre(s) r&amp;#233;f&amp;#233;rence(s):&lt;/title&gt;
    &lt;/heading&gt;
    &lt;p&gt;
        &lt;text&gt;
            &lt;ci:cite searchtype="SUMM-CASE-REF"&gt;
                &lt;ci:case&gt;
                    &lt;ci:caseref ID="cref00000105" spanref="cspan00000105"&gt;
                        &lt;ci:reporter value="BCES"/&gt;
                        &lt;ci:edition&gt;
                            &lt;ci:date year="2000"/&gt;
                        &lt;/ci:edition&gt;
                        &lt;ci:refnum num="446"/&gt;
                    &lt;/ci:caseref&gt;
                &lt;/ci:case&gt;
                &lt;ci:content&gt;
                    &lt;ci:span spanid="cspan00000105"&gt;[2000] B.C.E.S.T.D. No. 446&lt;/ci:span&gt;
                &lt;/ci:content&gt;
            &lt;/ci:cite&gt; ... &lt;/text&gt;
    &lt;/p&gt;
&lt;/references&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;dict:body&gt;
    &lt;dict:additionalmaterials materialstype="references"&gt;
        &lt;heading&gt;
            &lt;title&gt;Other reference(s)/Autre(s) r&amp;#233;f&amp;#233;rence(s):&lt;/title&gt;
        &lt;/heading&gt;
        &lt;bodytext&gt;
            &lt;p&gt;
                &lt;text&gt;
                    &lt;lnci:cite&gt;
                        &lt;lnci:case&gt;
                            &lt;lnci:caseref ID="cref00000105"&gt;
                                &lt;lnci:reporter value="BCES"/&gt;
                                &lt;lnci:edition&gt;
                                    &lt;lnci:date year="2000"/&gt;
                                &lt;/lnci:edition&gt;
                                &lt;lnci:refnum num="446"/&gt;
                            &lt;/lnci:caseref&gt;
                        &lt;/lnci:case&gt;
                        &lt;lnci:content&gt;[2000] B.C.E.S.T.D. No. 446&lt;/lnci:content&gt;
                    &lt;/lnci:cite&gt; ... &lt;/text&gt;
            &lt;/p&gt;
        &lt;/bodytext&gt;
    &lt;/dict:additionalmaterials&gt;
    &lt;/dict:body&gt;</pre>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA12-Dictionaries\CA12_CA-Dictionaries_references.dita  -->
    <!--<xsl:message>CA12_CA-Dictionaries_references.xsl requires manual development!</xsl:message> -->

    <xsl:template match="references">
        <!--  Original Target XPath:  dict:body/dict:additionalmaterials/@materialstype="references"   -->

        <dict:additionalmaterials>
            <xsl:attribute name="materialstype">
                <xsl:text>references</xsl:text>
            </xsl:attribute>
            <xsl:apply-templates select="heading/title" mode="ref_head"/>
            <xsl:apply-templates select="p" mode="ref_p"/>
        </dict:additionalmaterials>

    </xsl:template>

    <xsl:template match="heading/title" mode="ref_head">
        <heading>
            <title>
                <xsl:apply-templates/>                
            </title>
        </heading>
    </xsl:template>

    <xsl:template match="p" mode="ref_p">
        <bodytext>
            <p>
                <xsl:apply-templates/>
            </p>
        </bodytext>
    </xsl:template>

</xsl:stylesheet>
