<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:lnci="http://www.lexisnexis.com/xmlschemas/content/shared/citations/1/" xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/" xmlns:dig="http://www.lexis-nexis.com/glp/dig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0" exclude-result-prefixes="dita dig doc seclaw docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="CA14_CA-Emerging_Issues_Introduction">
  <title>Introduction <lnpid>id-CA14-35627</lnpid></title>

  <body>
    <p>This Conversion Instruction describes the conversion of Seclaw 8.14 PROD Schema in the
      document.</p>

    <p>CA <b>Emerging Issues</b> are identified using the root element
        <sourcexml>DIGESTDOC</sourcexml>. and element <sourcexml>docinfo:selector</sourcexml> having
      value <sourcexml>netletter</sourcexml>.</p>

    <p><sourcexml>DIGESTDOC</sourcexml> becomes <targetxml>seclaw:seclaw</targetxml>. It's a root
      element for CA Emerging Issues. The source attributes are: <sourcexml>@id</sourcexml> becomes
        <targetxml>@xml:id</targetxml>, <sourcexml>@xml:lang</sourcexml>, if present, suppress
      attribute and content, as a separate rule has been defined to populate
        <targetxml>seclaw:seclaw/@xml:lang</targetxml>. Also create the following attribute and
      value: <targetxml>seclaw:seclaw[@seclawtype="digest"]</targetxml>.</p>

    <pre>
&lt;DIGESTDOC ...&gt;
        ...
        &lt;docinfo:doc-lang lang="en"/&gt;
        &lt;docinfo:doc-country iso-cc="CA"/&gt;
        ...
&lt;/DIGESTDOC&gt;

<b>Becomes</b>

&lt;seclaw:seclaw seclawtype="digest" xml:lang="en-CA"&gt;
      
      &lt;seclaw:head&gt;...&lt;/seclaw:head&gt;
      
      &lt;seclaw:body&gt;...&lt;/seclaw:body&gt;
      
      &lt;doc:metadata&gt;...&lt;/doc:metadata&gt;

&lt;/seclaw:seclaw&gt;
</pre>

    <p><targetxml>seclaw:head</targetxml>, <targetxml>seclaw:body</targetxml>, and
        <targetxml>doc:metadata</targetxml> are created as required children of
        <targetxml>seclaw:seclaw</targetxml></p>
    <note>
      <p>The <sourcexml>@searchtype</sourcexml> attribute will be suppressed from conversion except
        for the citation elements.</p>
    </note>
    <note>
      <p>Conversion should retain empty elements <targetxml>lnci:can</targetxml> and
          <targetxml>lnci:usa</targetxml> in the target.</p>
    </note>
    <section>
      <title>Note:</title>
      <p>Source elements and attributes are highlighted like this:
        <sourcexml>SOURCEXML</sourcexml></p>
      <p>Target elements and attributes are highlighted like this:
        <targetxml>TARGETXML</targetxml></p>
      <p>Copy source attributes to target attributes unless otherwise specified.</p>
      <p>Every example is represented like "EXAMPLE" in all the dita's and is captured
        under <pre>pre</pre> tag.</p>
    </section>

    <section>
      <title>Changes</title>
      <p>2016-06-16: <ph id="change_20160616_RS">Updated schema version to 8.13 PROD.</ph></p>
      <p>2015-04-27: <ph id="change_20150427_jm2">Updated schema version to 8.5 PROD.</ph></p>
      <p>2015-04-27: <ph id="change_20150427_jm">New rule to create
            <targetxml>@seclawtype="digest"</targetxml> on the root element. RFA 21.</ph></p>
      <p>2015-03-27: <ph id="change_20150327_jm">Updated schema version to 8.3 PROD.</ph></p>
    </section>
  </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA14-Emerging_Issues\Introduction.dita  -->
	
  <!-- Template to match the root element DIGESTDOC nad create the target seclaw:seclaw 	-->
  <xsl:template match="DIGESTDOC">    
    <!--  Original Target XPath:  courtcase:courtcase   -->
    <xsl:element name="seclaw:seclaw" >
      <xsl:call-template name="generateNSGlobalBindings"/>
<!--      <xsl:for-each select="$lexisAdvNamespaces/*">
        <xsl:sort/>
        <xsl:namespace name="{substring-after(substring-before(., '='), ':')}" select="substring-after(translate(., '&#034;', ''), '=')"/>
      </xsl:for-each>-->
      
      <xsl:attribute name="xsi:schemaLocation" select="$outputSchemaLoc"/>     
      
	  <!--<xsl:call-template name="xml_lang_HK"/>     -->
      <xsl:attribute name="seclawtype">
        <xsl:text>digest</xsl:text>
      </xsl:attribute>
      
      <!-- seclaw:head  -->
      <xsl:element name="seclaw:head">
        <xsl:comment>Mandatory element according to the CI</xsl:comment>
      </xsl:element>

      <!-- seclaw:body    -->
      <xsl:apply-templates select="dig:body"/>
      
      <!-- doc:metadata   -->
      <xsl:element name="doc:metadata">
        <xsl:element name="pubinfo:pubinfo">
          <xsl:apply-templates select="dig:body/dig:info/publication | 
                                       dig:body/dig:collection/dig:info/publication | 
                                       dig:body/descendant::aboutpub |
                                       dig:body/dig:info/pubdate |
                                       dig:body/dig:collection/dig:info/pubdate |
                                       dig:body/dig:info/issue |
                                       dig:body/dig:collection/dig:info/issue"/>
        </xsl:element>        
        <xsl:apply-templates select="docinfo"/>
      </xsl:element>
    </xsl:element>    
  </xsl:template>
  
<!-- supressed the @type  -->
  <xsl:template match="DIGESTDOC/@type"/>

</xsl:stylesheet>
