<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"
    xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"
    xmlns:dig="http://www.lexis-nexis.com/glp/dig"
    xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/"
    version="2.0" exclude-result-prefixes="dita dig docinfo">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="issue">
        <title>issue <lnpid>id-CA14-35628</lnpid></title>

        <body>
            <section>
                <p><sourcexml>issue</sourcexml> becomes
                        <targetxml>doc:metadata/pubinfo:pubinfo/pubinfo:issue[@xml:lang]</targetxml>.</p>
                <p>Generate <targetxml>@xml:lang</targetxml> value, as follows:<ul>
                        <li>There are only two possible values: <targetxml>"en-CA"</targetxml> or
                                <targetxml>"fr-CA"</targetxml></li>
                        <li>Use the value from <sourcexml>docinfo:doc-lang[@lang]</sourcexml> and
                            append -CA. For example,
                                <sourcexml>docinfo:doc-lang[@lang="fr"]</sourcexml>, then
                                <sourcexml>issue</sourcexml> becomes
                                <targetxml>pubinfo:issue[@xml:lang="fr-CA"]</targetxml>.</li>
                        <li>If there are two <sourcexml>issue</sourcexml>, the first is same
                            language as <sourcexml>docinfo:doc-lang[@lang]</sourcexml> and the
                            second is the other language. For example,
                                <sourcexml>docinfo:doc-lang[@lang="en"]</sourcexml>, then first
                                <sourcexml>issue</sourcexml> becomes
                                <targetxml>pubinfo:issue[@xml:lang="en-CA"]</targetxml> and second
                                <sourcexml>issue</sourcexml> becomes
                                <targetxml>pubinfo:issue[@xml:lang="fr-CA"]</targetxml></li>
                    </ul><note>The same language rules are present in instructions for
                            <sourcexml>pubdate</sourcexml>. Maintain input sequence when there are
                        multiple <sourcexml>pubdate</sourcexml> and
                        <sourcexml>issue</sourcexml>.</note></p>
            </section>

            <example>
                <title>Example 1</title>
                <codeblock> &lt;dig:info&gt; ... &lt;issue&gt;Issue 586&lt;/issue&gt; ...
                    &lt;issue&gt;numéro 586&lt;/issue&gt; ... &lt;/dig:info&gt; &lt;!-- language
                    value is derived fron metadata --&gt; &lt;docinfo&gt; &lt;docinfo:doc-lang
                    lang="en"/&gt; &lt;/docinfo&gt; </codeblock>
                <b>becomes</b>
                <codeblock> &lt;doc:metadata&gt; &lt;pubinfo:pubinfo&gt; ... &lt;pubinfo:issue
                    xml:lang="en-CA"&gt;Issue 586&lt;/pubinfo:issue&gt; ... &lt;pubinfo:issue
                    xml:lang="fr-CA"&gt;numéro 586&lt;/pubinfo:issue&gt; ...
                    &lt;/pubinfo:pubinfo&gt; &lt;/doc:metadata&gt; </codeblock>
            </example>
            <note>Conversion should not create consecutive <targetxml>pubinfo:pubinfo</targetxml>
                elements. When 2 or more consecutive sibling source elements map to
                    <targetxml>pubinfo:pubinfo</targetxml>, data should be merged to a single
                    <targetxml>pubinfo:pubinfo</targetxml> element unless this would hamper content
                ordering.</note>
            <section>
                <title>Changes</title>
                <p>2015-09-15: <ph id="change_20150915_jm">Added rules to generate language
                        attribute <targetxml>@xml:lang</targetxml>. RFA 135.</ph></p>
                <p>2015-02-20: <ph id="change_20150220_PS">Created.</ph></p>
            </section>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA14-Emerging_Issues\issue.dita  -->

    <!--Vikas rohilla : Template match the issue and creates the pubinfo:issue -->
    <xsl:template match="issue">
        <pubinfo:issue>
            <xsl:attribute name="xml:lang">
                <xsl:value-of
                    select="concat(parent::dig:info/parent::dig:collection/parent::dig:body/preceding-sibling::docinfo/docinfo:doc-lang/@lang, '-', parent::dig:info/parent::dig:collection/parent::dig:body/preceding-sibling::docinfo/docinfo:doc-country/@iso-cc)"
                />
            </xsl:attribute>
            <xsl:apply-templates select="@* | node()"/>
        </pubinfo:issue>
    </xsl:template>


</xsl:stylesheet>
