<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0"
    exclude-result-prefixes="dita">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="abbrvname">
        <title>abbrvname <lnpid>id-CA14-35607</lnpid></title>
        <body>
            <section>
                <p><sourcexml>abbrvname</sourcexml> becomes
                        <targetxml>seclaw:body/seclaw:digestgrp/seclaw:digest/seclaw:digestinfo/caseinfo:caseinfo/caseinfo:casename/caseinfo:shortcasename</targetxml>.</p>
            </section>
            <example>
                <title>Example 1</title>
                <codeblock> &lt;dig:item&gt; &lt;dig:info&gt; &lt;case:info&gt;
                    &lt;abbrvname&gt;Bollman v. Soenen&lt;/abbrvname&gt; &lt;/case:info&gt;
                    &lt;/dig:info&gt; &lt;/dig:item&gt; </codeblock>
                <b>Becomes</b>
                <codeblock> &lt;seclaw:body&gt; &lt;seclaw:digestgrp&gt; &lt;seclaw:digest&gt;
                    &lt;seclaw:digestinfo&gt; &lt;caseinfo:caseinfo&gt; &lt;caseinfo:casename&gt;
                    &lt;caseinfo:shortcasename&gt;Bollman v. Soenen&lt;/caseinfo:shortcasename&gt;
                    &lt;/caseinfo:casename&gt; &lt;/caseinfo:caseinfo&gt; &lt;/seclaw:digestinfo&gt;
                    &lt;/seclaw:digest&gt; &lt;/seclaw:digestgrp&gt; &lt;/seclaw:body&gt;
                </codeblock>
            </example>

            <section>
                <title>Changes</title>
                <p>2015-02-20: <ph id="change_20150220_PS">Created.</ph></p>
            </section>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA14-Emerging_Issues\abbrvname.dita  -->
    <!--<xsl:message>CA14-Emerging_Issues_abbrvname.xsl requires manual development!</xsl:message>-->

    <!--Vikas Rohilla : Tempalte to match the abbrvname and creates the caseinfo:casename/caseinfo:shortcasename-->
    <xsl:template match="abbrvname">
        <caseinfo:casename>
            <caseinfo:shortcasename>
                <xsl:apply-templates select="@* | node()"/>
            </caseinfo:shortcasename>
        </caseinfo:casename>
    </xsl:template>

</xsl:stylesheet>
