<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"
    xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/" version="2.0" exclude-result-prefixes="dita">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="CA15_Rosetta__abstract">
        <title>abstract <lnpid>id-CA15-35409</lnpid></title>
        <body>
            <p><sourcexml>abstract</sourcexml> becomes
                    <targetxml>nitf:body.head/abstract/bodytext</targetxml>,
                    <targetxml>bodytext</targetxml> is the required child element.</p>
            <example>
                <title>Source XML</title>
                <codeblock> &lt;jrnl:prelim&gt; ... &lt;abstract&gt; &lt;heading&gt;
                    &lt;title&gt;RÉSUMÉ/ABSTRACT:&lt;/title&gt; &lt;/heading&gt; &lt;p&gt;
                    &lt;text&gt;[The English abstract follows the French.]&lt;/text&gt; &lt;/p&gt;
                    &lt;/abstract&gt; ... &lt;/jrnl:prelim&gt; </codeblock>
                <title>Target XML</title>
                <codeblock> &lt;nitf:body&gt; &lt;nitf:body.head&gt; &lt;abstract&gt;
                    &lt;heading&gt; &lt;title&gt;RÉSUMÉ/ABSTRACT:&lt;/title&gt; &lt;/heading&gt;
                    &lt;bodytext&gt; &lt;p&gt; &lt;text&gt;[The English abstract follows the
                    French.]&lt;/text&gt; &lt;/p&gt; &lt;/bodytext&gt; &lt;/abstract&gt;
                    &lt;/nitf:body.head&gt; &lt;/nitf:body&gt; </codeblock>
            </example>
            <section>
                <title>Changes</title>
                <p>2015-02-17: <ph id="change_20150217_AS">Created.</ph></p>
            </section>
        </body>

    </dita:topic>
    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA15-Journal_Articles\CA15_Rosetta_abstract.dita  -->
    <!--	<xsl:message>CA15_Rosetta_abstract.xsl requires manual development!</xsl:message> -->

    <xsl:template match="abstract">
        <abstract>
            <xsl:apply-templates select="heading"/>
            <bodytext>
                <xsl:apply-templates select="@* | node() except heading"/>
            </bodytext>
        </abstract>
    </xsl:template>





</xsl:stylesheet>
