<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="CA15_Rosetta_pubdate">
    <title>pubdate <lnpid>id-CA15-35421</lnpid></title>
    <body>
        <ul>
            <li><sourcexml>pubdate[@ln.user-displayed]</sourcexml> becomes
                    <targetxml>doc:metadata/pubinfo:pubinfo/pubinfo:dates</targetxml>. The attribute
                is suppressed. However, the attribute value affects the conversion of pcdata for
                child <sourcexml>date</sourcexml>, as described below. <ul>
                    <li><sourcexml>date[@day @month @year]</sourcexml> becomes
                            <targetxml>pubinfo:pubdate[@day @month @year]/date-text</targetxml>. The
                        attributes are optional. Often, only <sourcexml>@year</sourcexml> is present.<ul>
                            <li>Conversion of pcdata depends on parent attribute value, as follows:<ul>
                                    <li>If <sourcexml>pubdate[@ln.user-displayed="true"]</sourcexml>
                                        then <sourcexml>date</sourcexml> pcdata is mapped to
                                            <targetxml>date-text</targetxml>.</li>
                                    <li>If
                                            <sourcexml>pubdate[@ln.user-displayed="false"]</sourcexml>
                                        then <sourcexml>date</sourcexml> pcdata is suppressed for
                                        target (and so do not generate
                                            <targetxml>date-text</targetxml>).</li>
                                </ul></li>
                        </ul></li>
                </ul></li>
        </ul>
        <example>
            <title>Source XML - <sourcexml>pubdate[@ln.user-displayed="true"]</sourcexml></title>
            <codeblock>

&lt;jrnl:body&gt;
    &lt;jrnl:info&gt;
        &lt;pubdate ln.user-displayed="true"&gt;
            &lt;date year="2002"&gt;April 3, 2002&lt;/date&gt;
        &lt;/pubdate&gt;
    &lt;/jrnl:info&gt;
&lt;/jrnl:body&gt;

           </codeblock>
            <title>Target XML</title>
            <codeblock>

&lt;doc:metadata&gt;
    &lt;pubinfo:pubinfo&gt;
        &lt;pubinfo:dates&gt;
            &lt;pubinfo:pubdate year="2002"&gt;
                &lt;date-text&gt;April 3, 2002&lt;/date-text&gt;
            &lt;/pubinfo:pubdate&gt;
        &lt;/pubinfo:dates&gt;
    &lt;/pubinfo:pubinfo&gt;
&lt;/doc:metadata&gt;

           </codeblock>
        </example>
        <example>
            <title>Source XML - <sourcexml>pubdate[@ln.user-displayed="false"]</sourcexml></title>
            <codeblock>

&lt;jrnl:body&gt;
    &lt;jrnl:info&gt;
        &lt;pubdate ln.user-displayed="false"&gt;
            &lt;date year="2010"&gt;2010&lt;/date&gt;
        &lt;/pubdate&gt;
    &lt;/jrnl:info&gt;
&lt;/jrnl:body&gt;

           </codeblock>
            <title>Target XML</title>
            <codeblock>

&lt;doc:metadata&gt;
    &lt;pubinfo:pubinfo&gt;
        &lt;pubinfo:dates&gt;
            &lt;pubinfo:pubdate year="2010"/&gt;            
        &lt;/pubinfo:dates&gt;
    &lt;/pubinfo:pubinfo&gt;
&lt;/doc:metadata&gt;

           </codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>2015-10-13: <ph id="change_20151013_jhm">Added mapping to
                        <targetxml>date-text</targetxml> to hold the pcdata. RFA 59.</ph></p>
            <p>2015-10-05: <ph id="change_20151005_jhm">Revision concerning
                        <sourcexml>@ln.user-displayed</sourcexml>. When
                        <sourcexml>"true"</sourcexml>, pcdata is retained for target. When
                        <sourcexml>"false"</sourcexml>, pcdata is suppressed. RFA 59.</ph></p>
            <p>2015-09-29: <ph id="change_20150929_jhm">Revised. Previously, pcdata was not included
                    in target based on source attribute
                        <sourcexml>pubdate[@ln.user-displayed="false"]</sourcexml>. That attribute
                    is now ignored/suppressed and pcdata is carried through to target. RFA
                59.</ph></p>
            <p>2015-02-17: <ph id="change_20150217_AS">Created.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA15-Journal_Articles\CA15_Rosetta_pubdate.dita  -->
	<!--<xsl:message>CA15_Rosetta_pubdate.xsl requires manual development!</xsl:message> -->
	<xsl:template match="pubdate">

		<!--  Original Target XPath:  doc:metadata/pubinfo:pubinfo/pubinfo:dates   -->
		
				<pubinfo:dates>
				<pubinfo:pubdate>
				    <xsl:if test="date/@year">
				        <xsl:attribute name="year">
				            <xsl:value-of select="date/@year"/>
				        </xsl:attribute>
				    </xsl:if>
				    <xsl:if test="date/@month">
				        <xsl:attribute name="month">
				            <xsl:value-of select="date/@month"/>
				        </xsl:attribute> 
				    </xsl:if>
				    <xsl:if test="date/@day">
				        <xsl:attribute name="day">
				            <xsl:value-of select="date/@day"/>
				        </xsl:attribute>
				    </xsl:if>
				    <xsl:apply-templates select="date[parent::pubdate[@ln.user-displayed = 'true']]"/>
				    </pubinfo:pubdate>
				</pubinfo:dates>

	</xsl:template>

    <xsl:template match="date[parent::pubdate[@ln.user-displayed = 'true']]">
		        <date-text>
		            <xsl:apply-templates select="node()"/>
		        </date-text>
	</xsl:template>
    
    <xsl:template match="date[parent::pubdate[@ln.user-displayed = 'false']]">
       <!-- supressed-->
    </xsl:template>

</xsl:stylesheet>