<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
  xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"
  xmlns:newsitem="http://www.lexisnexis.com/xmlschemas/content/news/newsitem/1/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl"
  xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/"
  xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/" version="2.0" exclude-result-prefixes="dita">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
    id="CA15_Law_Reviews_and_Journals_Introduction">
    <title>Introduction <lnpid>id-CA15-35407</lnpid></title>

    <body>
      <p>These instructions describes the conversion of documents from the Rosetta JOURNALDOC DTD to
        the NewLexis NewsItem 4.2 PROD Schema.</p>

      <p>Legal News documents are identified by the root element
        <sourcexml>JOURNALDOC</sourcexml>.</p>

      <p><sourcexml>JOURNALDOC</sourcexml> becomes <targetxml>newsitem:newsitem</targetxml>. The
        following elements are required children of <targetxml>newsitem:newsitem</targetxml>: <ul>
          <li><targetxml>newsitem:head</targetxml></li>
          <li><targetxml>nitf:body</targetxml></li>
          <li><targetxml>doc:metadata</targetxml></li>
        </ul>
      </p>
      <example>
        <title>Source XML</title>
        <codeblock> &lt;JOURNALDOC&gt; ... &lt;/JOURNALDOC&gt; </codeblock>
        <title>Target XML</title>
        <codeblock> &lt;newsitem:newsitem xml:lang="en-CA"&gt;
          &lt;newsitem:head&gt;...&lt;/newsitem:head&gt; &lt;nitf:body&gt;...&lt;/nitf:body&gt;
          &lt;doc:metadata&gt;...&lt;/doc:metadata&gt; &lt;/newsitem:newsitem&gt; </codeblock>
      </example>

      <note>The <sourcexml>@searchtype</sourcexml> attribute will be suppressed from conversion
        except for the citation elements.</note>
      <section>
        <title>Note:</title>
        <p>Source elements and attributes are highlighted like this:
            <sourcexml>SOURCEXML</sourcexml></p>
        <p>Target elements and attributes are highlighted like this:
            <targetxml>TARGETXML</targetxml></p>
        <p>Copy source attributes to target attributes unless otherwise specified.</p>
        <p>Every example is represented like "EXAMPLE" in all the dita's and is captured under
          <pre>pre</pre> tag.</p>
      </section>
      <section>
        <title>Changes</title>
        <p>2015-03-27: <ph id="change_20150327_jm">Note that the emphasis portion of the General
            Markup section has changed. Now contains the Canada-specific rules for
              <sourcexml>emph</sourcexml> as child of <sourcexml>title</sourcexml>, see
              <sourcexml>heading/title/emph/@typestyle="bf"</sourcexml> to
              <targetxml>heading/title</targetxml> (id-CCCC-10495).</ph></p>
        <p>2015-02-17: <ph id="change_20150217_AS">Created.</ph></p>
      </section>
    </body>

  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA15-Journal_Articles\CA15JournalArticles_introduction.dita  -->
  <!--<xsl:message>CA15JournalArticles_introduction.xsl requires manual development!</xsl:message> -->

  <xsl:template match="JOURNALDOC">
    
    <!--  Original Target XPath:  newsitem:newsitem   -->
    <newsitem:newsitem>
      <xsl:call-template name="generateNSGlobalBindings"/>
      <xsl:attribute name="xsi:schemaLocation" select="$outputSchemaLoc"/> 
      <xsl:call-template name="xml_lang"/>
        <xsl:apply-templates select="jrnl:body"/>
  
    </newsitem:newsitem>

  </xsl:template>

<!--<xsl:template match="text[normalize-space(.)=''][not(child::*)]">
  <xsl:apply-templates select="@*|node()"/>
</xsl:template>-->


</xsl:stylesheet>
