<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
  xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:glp="http://www.lexis-nexis.com/glp"
  xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/"
  version="2.0" exclude-result-prefixes="dita case glp">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.body_case.content_glp.note_copyright">
  <title><sourcexml>case:content/glp:note/blockquote/p/text/copyright</sourcexml> <lnpid>id-AU07-19212</lnpid></title>
  <body>
    <section>
      <p>The element <sourcexml>case:content/glp:note/blockquote/p/text/copyright</sourcexml> becomes <targetxml>courtorder:courtorder/doc:metadata/pubinfo:pubinfo/copyright</targetxml>. If the <sourcexml>copyright</sourcexml> element contains the only non-whitespace text content within the entire <sourcexml>glp:note</sourcexml>, the rest of the child elements of the <sourcexml>glp:note</sourcexml> are dropped after the <sourcexml>copyright</sourcexml> is moved.
      </p>
    </section>

    <example>
      <title>Source XML</title>
      <codeblock>

&lt;case:content&gt;
  &lt;case:judgments&gt;
    &lt;case:judgment&gt;
      &lt;!--...--&gt;
    &lt;/case:judgment&gt;
  &lt;/case:judgments&gt;
  &lt;glp:note&gt;
    &lt;blockquote&gt;
      &lt;p&gt;
        &lt;text&gt;
          &lt;copyright&gt;© The Incorporated Council of Law Reporting for the State of Queensland, 2010.&lt;/copyright&gt;
        &lt;/text&gt;
      &lt;/p&gt;
    &lt;/blockquote&gt;
  &lt;/glp:note&gt;
&lt;/case:content&gt;

    </codeblock>
    </example>
    
    <example>
      <title>Target XML</title>
      <p>The <sourcexml>glp:note</sourcexml> is completely removed since the only text it contained was within the moved <sourcexml>copyright</sourcexml> element.
      </p>      
      <codeblock>

&lt;courtorder:body&gt;
  &lt;section&gt;
    &lt;!--...--&gt;
  &lt;/section&gt;
&lt;/courtorder:body&gt;
&lt;doc:metadata&gt;
  &lt;!--...--&gt;
  &lt;pubinfo:pubinfo&gt;
    &lt;copyright&gt;© The Incorporated Council of Law Reporting for the State of Queensland, 2010.&lt;/copyright&gt;
  &lt;/pubinfo:pubinfo&gt;
  &lt;!--...--&gt;
&lt;/doc:metadata&gt;

      </codeblock>
    </example>
    
    <section>
      <title>Changes</title>
      <p>2013-09-15: <ph id="change_20130915_JCG">Added this entirely new instruction to handle new XPaths. (Webteam #234565)</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU07_courtorder\case.body_case.content_glp.note_copyright.dita  -->
  <xsl:template match="case:body/case:content/glp:note[blockquote/p/text/copyright][not(child::*[2])]" mode="pubinfo"> 
    <xsl:apply-templates select="blockquote/p/text/copyright" mode="pubinfo"/>
  </xsl:template>
  
  <xsl:template match="copyright" mode="pubinfo">
    <pubinfo:pubinfo>
      <copyright xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/">
        <xsl:apply-templates select="@* | node()"/>
      </copyright>
    </pubinfo:pubinfo>
  </xsl:template>
  
  <xsl:template match="case:body/case:content/glp:note[blockquote/p/text/copyright][not(child::*[2])]"/>
  
  <xsl:template match="copyright"/>
  
  <xsl:template match="glp:note[not(@*|node())]" priority="40"/>

</xsl:stylesheet>