<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.info-LxAdv_caseinfo.caseinfo">
  <title>case:info <lnpid>id-ST01-26213</lnpid></title>
  <body>
    <section conref="../../common_caselaw/conref_content/Rosetta_case.info-LxAdv_caseinfo.caseinfo.dita#Rosetta_case.info-LxAdv_caseinfo.caseinfo/mapping"/>
    <example>
      <codeblock>
&lt;case:info&gt;
  ...
&lt;/case:info&gt;
      </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;caseinfo:caseinfo&gt;
  ...
&lt;/caseinfo:caseinfo&gt;
            </codeblock>
    </example>
    <section>
      <p>When <sourcexml>heading</sourcexml> occurs as direct child of
          <sourcexml>case:body</sourcexml> conversion should create <targetxml>heading</targetxml>
        as direct child of <targetxml>caseinfo:caseinfo</targetxml>, i.e.
          <sourcexml>case:body/heading</sourcexml> becomes
          <targetxml>caseinfo:caseinfo/heading</targetxml>.</p>
      <p>When <sourcexml>h</sourcexml> occurs as direct child of <sourcexml>case:info</sourcexml>
        conversion should create <targetxml>heading</targetxml> as direct child of
          <targetxml>caseinfo:caseinfo</targetxml>, i.e. <sourcexml>case:info/h</sourcexml> becomes
          <targetxml>caseinfo:caseinfo/heading</targetxml>.</p>
    </section>
    <example>
      <codeblock>
&lt;case:info&gt;
  ...
  &lt;h&gt;Application for registration of trade mark &lt;emph typestyle="smcaps"&gt;&lt;emph typestyle="ro"&gt;cedarapids&lt;/emph&gt;&lt;/emph&gt;&lt;/h&gt;
  ...
&lt;/case:info&gt;
      </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;caseinfo:caseinfo&gt;
  ...
  &lt;heading&gt;
    &lt;title&gt;Application for registration of trade mark &lt;emph typestyle="smcaps"&gt;&lt;emph typestyle="ro"&gt;cedarapids&lt;/emph&gt;&lt;/emph&gt;&lt;/title&gt;
  &lt;/heading&gt;
  ...
&lt;/caseinfo:caseinfo&gt;
            </codeblock>
    </example>
    <!--<section>
      <title>Change Log</title>
      </section>-->
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\courtcase\case.info-caseinfo.caseinfo.dita  -->
	<xsl:message>case.info-caseinfo.caseinfo.xsl requires manual development!</xsl:message> 

	<xsl:template match="heading">

		<!--  Original Target XPath:  heading   -->
		<heading>
			<xsl:apply-templates select="@* | node()"/>
		</heading>

	</xsl:template>

	<xsl:template match="case:body">

		<!--  Original Target XPath:  heading   -->
		<heading>
			<xsl:apply-templates select="@* | node()"/>
		</heading>

	</xsl:template>

	<xsl:template match="case:body/heading">

		<!--  Original Target XPath:  caseinfo:caseinfo/heading   -->
		<caseinfo:caseinfo>
			<heading>
				<xsl:apply-templates select="@* | node()"/>
			</heading>
		</caseinfo:caseinfo>

	</xsl:template>

	<xsl:template match="h">

		<!--  Original Target XPath:  heading   -->
		<heading>
			<xsl:apply-templates select="@* | node()"/>
		</heading>

	</xsl:template>

	<xsl:template match="case:info">

		<!--  Original Target XPath:  heading   -->
		<heading>
			<xsl:apply-templates select="@* | node()"/>
		</heading>

	</xsl:template>

	<xsl:template match="case:info/h">

		<!--  Original Target XPath:  caseinfo:caseinfo/heading   -->
		<caseinfo:caseinfo>
			<heading>
				<xsl:apply-templates select="@* | node()"/>
			</heading>
		</caseinfo:caseinfo>

	</xsl:template>

</xsl:stylesheet>