<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:glp="http://www.lexis-nexis.com/glp" version="2.0" exclude-result-prefixes="dita case glp">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.info_h-LxAdv_caseinfo.caseinfo_note_heading">
  <title>case:info/h[following-sibling::glp:note] <lnpid>id-ST01-26215</lnpid></title>
  <body>
    <section>
      <p>If an <sourcexml>h</sourcexml> element inside <sourcexml>case:info</sourcexml> is followed
        immediately by <sourcexml>glp:note</sourcexml>, then the <sourcexml>h</sourcexml> element
        should be treated as if it were inside the <sourcexml>glp:note</sourcexml>. Moreover, in
        this scenario <sourcexml>h</sourcexml> should map to <targetxml>heading/title</targetxml>.</p>
    </section>
    <example>
      <title>Mapping of case:info/h[following-sibling::glp:note]</title>
      <codeblock>
&lt;case:info&gt;
    ...
    &lt;h align="left"&gt;Other case details&lt;/h&gt;
    &lt;glp:note&gt;
        &lt;table&gt;
            ...
        &lt;/table&gt;
    &lt;/glp:note&gt;
    ...
&lt;/case:info&gt;
           </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;caseinfo:caseinfo&gt;
    ...
    &lt;note&gt;
        &lt;heading&gt;
            &lt;title&gt;Other case details&lt;/title&gt;
        &lt;/heading&gt;
        &lt;bodytext&gt;
            &lt;table&gt;
                ...
            &lt;/table&gt;
        &lt;/bodytext&gt;
    &lt;/note&gt;
    ...
&lt;/caseinfo:caseinfo&gt;
           </codeblock>
    </example>
    <!--section>
      <title>Changes</title>
      <p>2013-03-05: <ph id="change_20130305_DSF">Created.</ph></p>
    </section-->
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\courtcase\case.info_h-caseinfo.caseinfo_note_heading.dita  -->
	<xsl:message>case.info_h-caseinfo.caseinfo_note_heading.xsl requires manual development!</xsl:message> 

	<xsl:template match="h">

		<!--  Original Target XPath:  heading/title   -->
		<heading>
			<title>
				<xsl:apply-templates select="@* | node()"/>
			</title>
		</heading>

	</xsl:template>

	<xsl:template match="case:info">

		<!--  Original Target XPath:  heading/title   -->
		<heading>
			<title>
				<xsl:apply-templates select="@* | node()"/>
			</title>
		</heading>

	</xsl:template>

	<xsl:template match="glp:note">

		<!--  Original Target XPath:  heading/title   -->
		<heading>
			<title>
				<xsl:apply-templates select="@* | node()"/>
			</title>
		</heading>

	</xsl:template>

</xsl:stylesheet>