<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Comm-Form-Pre_level1-source">
  <title>Source XML</title>
  <body>
    <codeblock>
      
&lt;comm:body&gt; 
 &lt;level id="ACFM.I.PRACTICE" leveltype="comm.chap"&gt;
  &lt;!-- ETC. --&gt;
 &lt;/level&gt;
&lt;/comm:body&gt;
    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY03_Commentary-From-Prece\Comm-Form-Pre_level1-source.dita  -->
	<xsl:message>Comm-Form-Pre_level1-source.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>