<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Comm-Form-Pre_level2-source">
  <title>Source XML</title>
  <body>
    <codeblock>

&lt;comm:body&gt;
 &lt;level id="ACFM.I.PRECEDENTS" leveltype="prec.grp"&gt;
  &lt;heading searchtype="COMMENTARY"&gt;
   &lt;title&gt;&lt;refpt id="ACFM.I.PRECEDENTS" type="ext"/&gt;Forms&lt;/title&gt;
  &lt;/heading&gt;
  &lt;level id="ACFM.I.PRECSUBGRP1.1" leveltype="precgrp1" subdoc="false" toc-caption="ACTION FOR ADMINISTRATION "&gt;
   &lt;heading searchtype="COMMENTARY"&gt;
    &lt;title&gt;&lt;refpt id="ACFM.I.PRECSUBGRP1.1" type="ext"/&gt;ACTION FOR ADMINISTRATION&lt;/title&gt;
   &lt;/heading&gt;
   &lt;!-- ETC. --&gt;
  &lt;/level&gt;
 &lt;/level&gt;
&lt;/comm:body&gt;
    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY03_Commentary-From-Prece\Comm-Form-Pre_level2-source.dita  -->
	<xsl:message>Comm-Form-Pre_level2-source.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>