<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:entity="http://www.lexisnexis.com/xmlschemas/content/shared/identified-entities/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Comm-Form-Pre_contrib">
  <title><sourcexml>contrib</sourcexml> <lnpid>id-MY03-16410</lnpid></title>
  <body>
    <section>
      <p><sourcexml>contrib</sourcexml> becomes <targetxml>note/byline/entity:company</targetxml>
        <note><sourcexml>@searchtype</sourcexml> will be suppressed from conversion.</note>
        <note>Exception: <sourcexml>contrib</sourcexml> contains <b>N/A</b> or <b>N⁄A</b> then element <sourcexml>contrib</sourcexml> will be suppress from NewLexis conversion.</note>
        and populated as below:
      </p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY03_Commentary-From-Prece\Comm-Form-Pre_contrib.dita  -->
<!--	<xsl:message>Comm-Form-Pre_contrib.xsl requires manual development!</xsl:message> -->

	<xsl:template match="contrib">
		<note>
			<byline>
				<entity:company>
					<xsl:apply-templates select="@* | node()"/>
				</entity:company>
			</byline>
		</note>
	</xsl:template>

	<xsl:template match="contrib/@searchtype"/>
</xsl:stylesheet>