<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Comm-Form-Pre_level5-target">
  <title>Target XML</title>
  <body>
    <codeblock>

&lt;seclaw:level xml:id="HLA_5_I" leveltype="chapter" alternatetoccaption="I INTRODUCTION" includeintoc="false"&gt;
 &lt;ref:anchor id="HLA_5_I.1" anchortype="global"/&gt;
 &lt;heading&gt;
  &lt;desig&gt;I&lt;/desig&gt;
  &lt;title&gt;INTRODUCTION&lt;/title&gt;
 &lt;/heading&gt;
 &lt;seclaw:bodytext&gt;
  &lt;seclaw:level xml:id="HLA_5_I_1" leveltype="chapter" alternatetoccaption="&amp;#x0028;1&amp;#x0029; LEGAL AND HISTORICAL BACKGROUND" includeintoc="false"&gt;
   &lt;ref:anchor id="HLA_5_I_1.1" anchortype="global"/&gt;
   &lt;heading&gt;
    &lt;desig&gt;&amp;#x0028;1&amp;#x0029;&lt;/desig&gt;
    &lt;title&gt;LEGAL AND HISTORICAL BACKGROUND&lt;/title&gt;
   &lt;/heading&gt;
   &lt;!-- ETC. --&gt;
  &lt;/seclaw:level&gt;
 &lt;/seclaw:bodytext&gt;
&lt;/seclaw:level&gt;
    </codeblock>
   <note><b><targetxml>@xml:id</targetxml> should be unique within xml and white space not allow in <targetxml>@xml:id</targetxml> value. If white space encountered in the attribute value than replace with underscore(_) sign. Also <targetxml>@xml:id</targetxml> must not start with a numeric value.</b></note>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU05_Comm_Form_Prec\Comm-Form-Pre_level5-target.dita  -->
	 

</xsl:stylesheet>