<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
	xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/" xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/"
	xmlns:leg="http://www.lexis-nexis.com/glp/leg"
	xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" version="2.0" exclude-result-prefixes="dita leg docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Comm-Form-Pre_levelinfo">
  <title><sourcexml>levelinfo</sourcexml> <lnpid>id-AU05-18825</lnpid></title>
  <body>
    <section>
      <p><sourcexml>levelinfo</sourcexml> becomes <targetxml>seclaw:levelinfo</targetxml>.
        <note>If <sourcexml>levelinfo</sourcexml> comes under the xpath <sourcexml>level[@leveltype="prec"]/levelinfo</sourcexml> becomes <targetxml>form:form/form:document/form:info</targetxml></note>
        <note>In the source, <sourcexml>levelinfo</sourcexml> is used before the <sourcexml>heading</sourcexml> element under the <sourcexml>level</sourcexml>. But in NewLexis schema, <targetxml>seclaw:levelinfo</targetxml> and <targetxml>form:info</targetxml> is not allowed before the <targetxml>heading</targetxml> element. That is why <targetxml>seclaw:levelinfo</targetxml> and <targetxml>form:info</targetxml> will appear after heading element.</note>
      </p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU05_Comm_Form_Prec\Comm-Form-Pre_levelinfo.dita  -->


	<xsl:template match="levelinfo">
		<!-- make sure it has something to output-->
		<xsl:if test="child::*[not(self::docinfo:currencystatement)][not(self::docinfo:authorattribution)] or parent::level[not(@leveltype=('prec.grp' , 'precgrp' , 'precgrp1' , 'precgrp2' , 'prec' , 'form'))][parent::level[not(@leveltype=('prec.grp' , 'precgrp' , 'precgrp1' , 'precgrp2' , 'prec' , 'form'))]]/heading/leg:empleg">
		<seclaw:levelinfo>
			<xsl:apply-templates select="@* | node()"/>
			<!-- primlaw:authority output elsewhere for forms -->
			<xsl:if test="parent::level[not(@leveltype=('prec.grp' , 'precgrp' , 'precgrp1' , 'precgrp2' , 'prec' , 'form'))]">
				<xsl:apply-templates select="parent::*/heading/leg:empleg"/>
			</xsl:if>	
		</seclaw:levelinfo>
		</xsl:if>
	</xsl:template>

	<!--<levelinfo>
            <docinfo:currencystatement>Last updated: <date year="2016" month="06" day="24">24 June
                2016</date></docinfo:currencystatement>
            <docinfo:authorattribution>
              <contrib ln.user-displayed="false">Saul Fridman LLB BCL(Oxon) and David Thorpe BA MCom
                LLB(Hons)</contrib>
            </docinfo:authorattribution>
          </levelinfo> -->

	<xsl:template match="level[starts-with(@leveltype, 'prec') or starts-with (@leveltype , 'form')]/levelinfo" priority="20">
		<form:info>
			<xsl:apply-templates select="@* | node()"/>
		</form:info>
	</xsl:template>

	

</xsl:stylesheet>