<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Comm-Form-Pre_level3-source">
  <title>Source XML</title>
  <body>
    <codeblock>

&lt;level id="WPV_WAWC.SGM_WPV.WAWC.COM8" leveltype="comm.chap"&gt;
 &lt;!-- ETC. --&gt;
 &lt;level id="WPV_WAWC.SGM_WPV.WAWC.17000" leveltype="para0" subdoc="true" toc-caption="[17,000] Introduction"&gt;
  &lt;!-- ETC. --&gt;
 &lt;/level&gt;
 &lt;!-- ETC. --&gt;
 &lt;level id="WPV_WAWC.SGM_WPV.WAWC.17055-1" leveltype="prec" subdoc="true" toc-caption="[17,055.1] Precedent &amp;mdash; Form of Benjamin Order"&gt;
  &lt;!-- ETC. --&gt;
 &lt;/level&gt;
&lt;/level&gt;
    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU05_Comm_Form_Prec\Comm-Form-Pre_level3-source.dita  -->

</xsl:stylesheet>