<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="footnotegrp-Chof-case.headnote">
  <title>footnotegrp[parent::case:headnote] <lnpid>id-ST05-28446</lnpid></title>
  <body>
    <section><p>When <sourcexml>footnotegrp</sourcexml> is a child of
          <sourcexml>case:headnote</sourcexml> the target <targetxml>footnotegroup</targetxml>
        should be wrapped in <targetxml>note</targetxml> as follows: <ul>
          <li>Create <targetxml>note</targetxml>.</li>
          <li>Inside <targetxml>note</targetxml> create <targetxml>bodytext/p/text</targetxml>.</li>
          <li>Map <sourcexml>footnotegrp</sourcexml> to <targetxml>footnotegroup</targetxml> as
            usual (see <xref href="../../common_newest/Rosetta_footnote-LxAdv-footnote.dita"/> for
            details) and place it inside the <targetxml>text</targetxml> created in the previous
            step.</li>
        </ul></p></section>
    <example>
      <title>Source XML based on AU content</title>
      <codeblock>
&lt;case:headnote&gt;
  ...
  &lt;footnotegrp&gt;
    &lt;footnote fntoken="06-20085fn001" fnrtokens="06-20085fn001-r" type="default"&gt;
      &lt;fnlabel&gt;1&lt;/fnlabel&gt;
      &lt;fnbody&gt;
        &lt;p&gt;
          &lt;text&gt;
            &lt;emph typestyle="bf"&gt;Editorial note:&lt;/emph&gt; For the sake of completeness, the decision
            of the full court of the High Court of Australia, previously appearing at 1A IPR 484,
            has been reproduced here together with the decision of Windeyer J.&lt;/text&gt;
        &lt;/p&gt;
      &lt;/fnbody&gt;
    &lt;/footnote&gt;
  &lt;/footnotegrp&gt;
&lt;/case:headnote&gt; 
      </codeblock>
    </example>
    <example>
      <title>Target XML</title>
      <codeblock>
&lt;compcase:head&gt;
  ...
  &lt;note&gt;
    &lt;bodytext&gt;
      &lt;p&gt;
        &lt;text&gt;
          &lt;footnotegroup&gt;
            &lt;footnote&gt;
              &lt;ref:anchor id="_06-20085fn001"/&gt;
              &lt;ref:returnreference&gt;
                &lt;ref:locator anchoridref="_06-20085fn001-r"/&gt;
              &lt;/ref:returnreference&gt;
              &lt;label&gt;1&lt;/label&gt;
              &lt;bodytext&gt;
                &lt;p&gt;
                  &lt;text&gt;
                    &lt;emph typestyle="bf"&gt;Editorial note:&lt;/emph&gt; For the sake of completeness, the
                    decision of the full court of the High Court of Australia, previously appearing
                    at 1A IPR 484, has been reproduced here together with the decision of
                    Windeyer J.&lt;/text&gt;
                &lt;/p&gt;
              &lt;/bodytext&gt;
            &lt;/footnote&gt;
          &lt;/footnotegroup&gt;
        &lt;/text&gt;
      &lt;/p&gt;
    &lt;/bodytext&gt;
  &lt;/note&gt;
&lt;/compcase:head&gt;
           </codeblock>
       </example>
       <section>
           <title>Changes</title>
           <p>2014-05-15: <ph id="change_20140515_SS">Created.</ph></p>
       </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Compcase\footnotegrp-Chof-case.headnote.dita  -->
	<xsl:message>footnotegrp-Chof-case.headnote.xsl requires manual development!</xsl:message> 

	<xsl:template match="footnotegrp">

		<!--  Original Target XPath:  footnotegroup   -->
		<footnotegroup>
			<xsl:apply-templates select="@* | node()"/>
		</footnotegroup>

	</xsl:template>

	<xsl:template match="case:headnote">

		<!--  Original Target XPath:  footnotegroup   -->
		<footnotegroup>
			<xsl:apply-templates select="@* | node()"/>
		</footnotegroup>

	</xsl:template>

</xsl:stylesheet>