<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:entity="http://www.lexisnexis.com/xmlschemas/content/shared/identified-entities/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="company">
    <title>govt-entity <lnpid>id-IN07-38412</lnpid></title>
  
  <body>
      <section>
    <p>
      <ul>
          <li><sourcexml>govt-entity</sourcexml> becomes <targetxml>entity:govt-entity</targetxml>.                  
        </li>       
      </ul>     
    </p>    
      </section>
      <example>
          <title>Source XML</title>
          <codeblock>
&lt;dict:definition&gt;
&lt;p&gt;&lt;text&gt;&amp;#x201C;State Bank&amp;#x201D; means the &lt;govt-entity&gt;State Bank of India&lt;/govt-entity&gt; constituted under the
&lt;/text&gt;&lt;/p&gt;
&lt;/dict:definition&gt;

</codeblock>
        </example>
        <example>
            <title>Target XML</title>
            <codeblock>

&lt;tei:entry&gt;
    &lt;tei:def&gt;
        &lt;pgrp&gt;
            &lt;p&gt;&lt;text&gt;&amp;#x201C;State Bank&amp;#x201D; means the &lt;entity:govt-entity&gt;State Bank of India&lt;/entity:govt-entity&gt; constituted under the&lt;/text&gt;&lt;/p&gt;
        &lt;/pgrp&gt;
    &lt;/tei:def&gt;   
&lt;/tei:entry&gt;
          </codeblock></example>
      <section>
          <title>Changes</title>
          <p>2016-07-05: <ph id="change_20160705_RS">Created</ph>.</p>
      </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-IN\IN07-Dictionary\govt-entity.dita  -->
	<xsl:message>govt-entity.xsl requires manual development!</xsl:message> 

	<xsl:template match="govt-entity">

		<!--  Original Target XPath:  entity:govt-entity   -->
		<entity:govt-entity>
			<xsl:apply-templates select="@* | node()"/>
		</entity:govt-entity>

	</xsl:template>

</xsl:stylesheet>