<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
	xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" 
	xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"
	xmlns:newsitem="http://www.lexisnexis.com/xmlschemas/content/news/newsitem/1/" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:case="http://www.lexis-nexis.com/glp/case"
	xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl"
	xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/"
	xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/"
	version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Articles_Introduction">
  <title>Introduction <lnpid>id-HK02-37011</lnpid></title>

  <body>
    <p>This Conversion Instruction describes the conversion of source documents to target documents using the lastest version of the New Lexis newsitem schema. 4.4 PROD</p>
    
    <p>HK Articles documents are identified using the root element <sourcexml>JOURNALDOC</sourcexml>.</p>

    <p><sourcexml>JOURNALDOC</sourcexml> becomes <targetxml>newsitem:newsitem</targetxml>. It's a
      root element for HK Articles. The source attributes are:
        <sourcexml>@id</sourcexml> becomes <targetxml>@xml:id</targetxml>,
        <sourcexml>@xml:lang</sourcexml>, if present, suppress attribute and content, as a separate
      rule has been defined to populate <targetxml>newsitem:newsitem/@xml:lang</targetxml>.</p>

<pre>

&lt;JOURNALDOC&gt;
        ...
        &lt;docinfo:doc-lang lang="en"/&gt;
        &lt;docinfo:doc-country iso-cc="AU"/&gt;
        ...
&lt;/JOURNALDOC&gt;
<b>Becomes</b>

&lt;newsitem:newsitem xml:lang="en-AU"&gt;
      
      &lt;newsitem:head&gt;...&lt;/newsitem:head&gt;
      
      &lt;nitf:body&gt;...&lt;/nitf:body&gt;
      
      &lt;doc:metadata&gt;...&lt;/doc:metadata&gt;

&lt;/newsitem:newsitem&gt;
</pre>

    <p><targetxml>newsitem:head</targetxml>, <targetxml>nitf:body</targetxml>, and <targetxml>doc:metadata</targetxml> are created as required children of 
      <targetxml>newsitem:newsitem</targetxml></p>
    <note>The <sourcexml>@searchtype</sourcexml> attribute will be suppressed from conversion except for the citation elements.</note>
    <section>
      <title>Note:</title>
      <p>Source elements and attributes are highlighted like this: <sourcexml>SOURCEXML</sourcexml></p>
      <p>Target elements and attributes are highlighted like this: <targetxml>TARGETXML</targetxml></p>
      <p>Copy source attributes to target attributes unless otherwise specified.</p>
      <p>Every example is represented like "EXAMPLE" in all the dita's and is captured under <pre>pre</pre> tag.</p>
    </section>
    <section>
      <title>newsitem:head</title>
      <p>Incase, if there is no header information found in sample documents, then conversion will create an empty tag of <targetxml>newsitem:head</targetxml> in output.</p>
    </section>
  </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-HK\HK02_Articles\HK02-Articles_Introduction.dita  -->
	<!--<xsl:message>HK02-Articles_Introduction.xsl requires manual development!</xsl:message> -->
<!--  <xsl:include href="HK02-Articles_Namespaces.xsl"/>
  <xsl:include href="file:/C:/Views/dataArch/XSLT/ContentArch/Rosetta-to-LA/modules/docinfo/Rosetta_docinfo.doc-lang-and-doc-country-LxAdv-ROOT_xml.lang.xsl"/>
  -->
  <xsl:output indent="yes" method="xml"/>
  <xsl:param name="outputSchemaLoc"
    select="'urn:x-lexisnexis:content:newsitem:sharedservices:1 sch_newsitem.xsd'"/>
  
  <xsl:template match="JOURNALDOC">
    <newsitem:newsitem>
      <!-- 2017-10-03 - MDS: Standardized the handling of the root element to mesh with current practice. -->
      <xsl:call-template name="generateNSGlobalBindings"/>
      
      <xsl:attribute name="xsi:schemaLocation" select="$outputSchemaLoc"/>
      <xsl:apply-templates select="@*"/>
      <!--<xsl:call-template name="xml_lang"/>-->
      <xsl:if test="docinfo/docinfo:doc-lang">
        <!-- Satbir :After discussion Commenting out xsl:call-template name="xml_lang" as input files have <docinfo:doc-country iso-cc="AU"/> and hard coding en-HK -->
        <xsl:attribute name="xml:lang">
          <xsl:text>en-HK</xsl:text>
        </xsl:attribute>
      </xsl:if>
      
      <newsitem:head>
        <xsl:apply-templates select="jrnl:body/jrnl:info/jrnl:journalcite"/>
      </newsitem:head>
      <xsl:apply-templates select="jrnl:body"/>
      <doc:metadata>
        <!-- Awantika:2017-11-28- Added mapping for copyright. Webstar# 7054920 -->
        <xsl:if test="jrnl:body/jrnl:info/pubdate | jrnl:body/jrnl:prelim/copyright | jrnl:body/jrnl:bodytext/case:embeddedcase/case:headnote/case:info/case:dates/case:publishdate">
          <pubinfo:pubinfo>
            <xsl:apply-templates select="jrnl:body/jrnl:info/pubdate"/>  
            <xsl:apply-templates select="jrnl:body/jrnl:prelim/copyright"/>
            <xsl:apply-templates select="jrnl:body/jrnl:bodytext/case:embeddedcase/case:headnote/case:info/case:dates/case:publishdate"/>
          </pubinfo:pubinfo>
        </xsl:if>
     
        <!--<xsl:if test="jrnl:body/jrnl:prelim/copyright">
          <pubinfo:pubinfo>
          <xsl:apply-templates select="jrnl:body/jrnl:prelim/copyright"/>
          </pubinfo:pubinfo>
        </xsl:if>-->
        <xsl:apply-templates select="docinfo"/>
      </doc:metadata>
      
      
    </newsitem:newsitem>
    
    
  </xsl:template>
    
  <!-- suppress Rosetta-dtd specific atts -->
  
  <xsl:template match="JOURNALDOC/@xml:lang"/>
  <xsl:template match="JOURNALDOC/@version"/>
  <xsl:template match="JOURNALDOC/@versionminor"/>
  <xsl:template match="JOURNALDOC/@id"/>
  
	



</xsl:stylesheet>