<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="HK03_Rosetta_case.content">
    <title>case:content <lnpid>id-HK03-37211</lnpid></title>
    <body>
        <section conref="../../common_caselaw/conref_content/Rosetta_case.content.dita#Rosetta_case.content/mapping"/>
        <note>If <sourcexml>page</sourcexml> element occurs as direct child of <sourcexml>case:content</sourcexml> then conversion need to move
            <targetxml>ref:page</targetxml> as direct child of <targetxml>courtcase:body</targetxml>, i.e,
            <sourcexml>case:content/page</sourcexml> becomes <targetxml>courtcase:body/ref:page</targetxml>.</note>
        <note>If <sourcexml>case:appendix</sourcexml> element occurs as direct child of <sourcexml>case:content</sourcexml> then conversion
            need to move <targetxml>attachments/appendix</targetxml> as direct child of <targetxml>courtcase:body</targetxml>, i.e,
            <sourcexml>case:content/case:appendix</sourcexml> becomes <targetxml>courtcase:body/attachments/appendix</targetxml>.</note>
        <!--<section
            conref="../../common_caselaw/conref_content/Rosetta_case.content.dita#Rosetta_case.content/changes"/>-->
        <!--<section>
            <title>Changes Specific to AU01</title>
        </section>-->
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-HK\HK03\HK03_Rosetta_case.content.dita  -->
	<!--<xsl:message>HK03_Rosetta_case.content.xsl requires manual development!</xsl:message>-->
	<!--WSS: Done case:content-->
<!-- Awantika: Commented to check out -->
	<!--<xsl:template match="case:content/child::page"/>
    <xsl:template match="case:content/child::appendix"/>
    <xsl:template match="case:content/child::case:typeofcase"/>-->
</xsl:stylesheet>