<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"  
    xmlns:case="http://www.lexis-nexis.com/glp/case" 
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="HK03_Rosetta_case.appendix-LxAdv_attachments_appendix">
    <title>case:appendix <lnpid>id-HK03-37209</lnpid></title>
    <body>
        <section conref="../../common_caselaw/conref_content/Rosetta_case.appendix-LxAdv_attachments_appendix.dita#Rosetta_case.appendix-LxAdv_attachments_appendix/mapping"/>
        <example>
            <codeblock>
&lt;case:body&gt;
    &lt;case:content&gt;
        &lt;case:judgments&gt;
...
            &lt;case:appendix&gt;
                &lt;pgrp&gt;
                    &lt;heading&gt;
                        &lt;title&gt;Order&lt;/title&gt;
                    &lt;/heading&gt;
                    &lt;l&gt;
                        &lt;li&gt;
                            &lt;lilabel&gt;
                                &lt;emph typestyle="ro"&gt;1.&lt;/emph&gt;
                            &lt;/lilabel&gt;
                            &lt;p&gt;
                                &lt;text&gt;That the first defendant do within 10 days of the date of the
                                    Order disclose to the plaintiffs’ solicitors (if or to the
                                    extent known or otherwise available to the first defendant and
                                    in documentary form so far as reasonably practicable and
                                    convenient to the first defendant) the full name/s, postal
                                    address/es and identity card number/s of the person/s whose
                                    Internet account/s was or were assigned the Internet Protocol
                                    address/es listed in Annex A hereto on the date/s and time/s
                                    (according to the Hong Kong time of the Hong Kong Observatory)
                                    shown therein;&lt;/text&gt;
                            &lt;/p&gt;
                        &lt;/li&gt;
                    &lt;/l&gt;
                &lt;/pgrp&gt;
            &lt;/case:appendix&gt;
...
        &lt;/case:judgments&gt;
...
    &lt;/case:content&gt;
&lt;/case:body&gt;
           </codeblock>
            <b>becomes</b>
            <codeblock>
&lt;courtcase:body&gt;
...
    &lt;courtcase:opinions&gt;
...
        &lt;attachments&gt;
            &lt;appendix&gt;
                &lt;bodytext&gt;
                    &lt;pgrp&gt;
                        &lt;heading&gt;
                            &lt;title&gt;Order&lt;/title&gt;
                        &lt;/heading&gt;
                        &lt;list&gt;
                            &lt;listitem&gt;
                                &lt;label&gt;
                                    &lt;emph typestyle="ro"&gt;1.&lt;/emph&gt;
                                &lt;/label&gt;
                                &lt;bodytext&gt;
                                    &lt;p&gt;
                                        &lt;text&gt;That the first defendant do within 10 days of the date of the Order disclose to the plaintiffs&amp;#x2019; solicitors &amp;#x0028;if or to the extent known or otherwise available to the first defendant and in documentary form so far as reasonably practicable and convenient to the first defendant&amp;#x0029; the full name/s, postal address/es and identity card number/s of the person/s whose Internet account/s was or were assigned the Internet Protocol address/es listed in Annex A hereto on the date/s and time/s &amp;#x0028;according to the Hong Kong time of the Hong Kong Observatory&amp;#x0029; shown therein;&lt;/text&gt;
                                    &lt;/p&gt;
                                &lt;/bodytext&gt;
                            &lt;/listitem&gt;
                        &lt;/list&gt;
                    &lt;/pgrp&gt;
                &lt;/bodytext&gt;
            &lt;/appendix&gt;
        &lt;/attachments&gt;
...
    &lt;/courtcase:opinions&gt;
...
&lt;/courtcase:body&gt;
           </codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>2016-02-29: <ph id="change_20160229_AS">Created</ph></p>
           
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-HK\HK03\HK03_Rosetta_case.appendix-LxAdv_attachments_appendix.dita  -->
	<!--<xsl:message>HK03_Rosetta_case.appendix-LxAdv_attachments_appendix.xsl requires manual development!</xsl:message>--> 
    <!--WSS: Done - case:appendix--> 
    
    <!-- Awantika: updated Rosetta_pgrp-LexAdv-pgrp to create bodytext wrapper around pgrp -->
    <xsl:template match="case:appendix">
        <attachments>
            <appendix> 
                <xsl:if test="child::heading">
                    <xsl:apply-templates select="heading"/>                   
                </xsl:if>
                <xsl:if test="node() except heading">
                    <bodytext>
                        <xsl:apply-templates select="@* | node() except heading"/>
                    </bodytext>
                </xsl:if>
            </appendix>
        </attachments>
    </xsl:template>
    
    <!--<xsl:template match="case:appendix[child::p]" mode="nextp">
        <xsl:variable name="name" select="local-name()"/>
        <xsl:apply-templates />
        <xsl:apply-templates select="following-sibling::*[1][local-name()=$name]" mode="next"/>
    </xsl:template>-->
   
</xsl:stylesheet>