<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
    xmlns:case="http://www.lexis-nexis.com/glp/case"
    xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/"
    version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="HK03_Rosetta_case.filenum-LxAdv_caseinfo.docketnum">
    <title>case:filenum <lnpid>id-HK03-37226</lnpid></title>
    <body>
        <section conref="../../common_caselaw/conref_content/Rosetta_case.filenum-LxAdv_caseinfo.docketnum.dita#Rosetta_case.filenum-LxAdv_caseinfo.docketnum/mapping"/>
        <example>
            <codeblock>
&lt;case:courtinfo&gt;
    ...
    &lt;case:filenum&gt;HCMP 2696/2009&lt;/case:filenum&gt;
    ...
&lt;/case:courtinfo&gt;
       </codeblock>
            <b>becomes</b>
            <codeblock>
&lt;caseinfo:caseinfo&gt;
    ...
    &lt;caseinfo:docketnum&gt;HCMP 2696/2009&lt;/caseinfo:docketnum&gt;
    ...
&lt;/caseinfo:caseinfo&gt;
       </codeblock>
        </example>
        <!--<section
            conref="../../common_caselaw/conref_content/Rosetta_case.filenum-LxAdv_caseinfo.docketnum.dita#Rosetta_case.filenum-LxAdv_caseinfo.docketnum/changes"/>-->
        <!--<section>
            <title>Changes Specific to AU01</title>
            </section>-->

    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-HK\HK03\HK03_Rosetta_case.filenum-LxAdv_caseinfo.docketnum.dita  -->
    <xsl:template match="case:filenum">
        
            <caseinfo:docketnum>
                <xsl:apply-templates select="@* | node()"/>
            </caseinfo:docketnum>
        
    </xsl:template>

</xsl:stylesheet>