<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/" 
    xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="HK07_contrib">
  <title><sourcexml>contrib</sourcexml> <lnpid>id-HK07-37409</lnpid></title>
  <body>
    <section>
      <p><sourcexml>contrib</sourcexml> becomes
          <targetxml>seclaw:bodytext/note/byline/person:contributor</targetxml> and create attribute
        <targetxml>person:contributor/contributor-type="unclassified"</targetxml>.</p>
      <p>Conversion of child elements of <sourcexml>contrib</sourcexml> are mentioed below:
      <ul>
        <li><sourcexml>person</sourcexml> becomes <targetxml>person:person</targetxml></li>
        <li><sourcexml>name.text</sourcexml> becomes <targetxml>person:name.text</targetxml></li>
        <li><sourcexml>name.detail</sourcexml> becomes <targetxml>person:name.detail</targetxml></li>
        <li><sourcexml>name.degree</sourcexml> becomes <targetxml>person:name.degree</targetxml></li>
      </ul></p>
      <pre>
&lt;bodytext&gt;
    &lt;contrib&gt;
        &lt;person&gt;
            &lt;name.text&gt;By&lt;/name.text&gt;
            &lt;name.text&gt;Dr Boyce Yung&lt;/name.text&gt;
            &lt;name.detail&gt;
                &lt;name.degree&gt; PhD in Law (Lancaster), LLM with Hons (Northwestern), LLM, LLB
                    (London), PCLL (HKU), Solicitor (Hong Kong, England and Wales), Senior
                    Government Counsel (Ag.)&lt;/name.degree&gt;
            &lt;/name.detail&gt;
        &lt;/person&gt;
    &lt;/contrib&gt;
&lt;/bodytext&gt;
      </pre>
      <p><b>becomes</b></p>
      <pre>
&lt;seclaw:bodytext&gt;
    &lt;note&gt;
        &lt;byline&gt;
            &lt;person:contributor contributor-type="unclassified"&gt;
                &lt;person:person&gt;
                    &lt;person:name.text&gt;By&lt;/person:name.text&gt;
                    &lt;person:name.text&gt;Dr Boyce Yung&lt;/person:name.text&gt;
                    &lt;person:name.detail&gt;
                        &lt;person:name.degree&gt;PhD in Law (Lancaster), LLM with Hons (Northwestern),
                            LLM, LLB (London), PCLL (HKU), Solicitor (Hong Kong, England and Wales),
                            Senior Government Counsel (Ag.)&lt;/person:name.degree&gt;
                    &lt;/person:name.detail&gt;
                &lt;/person:person&gt;
            &lt;/person:contributor&gt;
        &lt;/byline&gt;
    &lt;/note&gt;
&lt;/seclaw:bodytext&gt;
      </pre>
    </section>
    <section>
      <title>Change Log</title>
      <p>2016-04-12: <ph id="change_20160412_PS">Created.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-HK\HK07_Commentary\HK07_contrib.dita  -->
	
	<xsl:template match="contrib">

		<!--  Original Target XPath:  seclaw:bodytext/note/byline/person:contributor   -->
		<xsl:choose>
		    <xsl:when test="parent::bodytext">
		        <note>
		            <byline>
		                <person:contributor>		                    
		                    <xsl:attribute name="contributor-type">unclassified</xsl:attribute>
		                    <xsl:apply-templates select="@* | node()"/>
		                </person:contributor>
		            </byline>
		        </note>
		    </xsl:when>
		    <xsl:otherwise>
		        <seclaw:bodytext>
		            <note>
		                <byline>
		                    <person:contributor>		                        
		                        <xsl:attribute name="contributor-type">unclassified</xsl:attribute>
		                        <xsl:apply-templates select="@* | node()"/>
		                    </person:contributor>
		                </byline>
		            </note>
		        </seclaw:bodytext>
		        
		    </xsl:otherwise>
		</xsl:choose>
	    
	</xsl:template>

	<!--<xsl:template match="person">

		<!-\-  Original Target XPath:  person:person   -\->
		<person:person>
			<xsl:apply-templates select="@* | node()"/>
		</person:person>

	</xsl:template>

	<xsl:template match="name.text">

		<!-\-  Original Target XPath:  person:name.text   -\->
		<person:name.text>
			<xsl:apply-templates select="@* | node()"/>
		</person:name.text>

	</xsl:template>

	<xsl:template match="name.detail">

		<!-\-  Original Target XPath:  person:name.detail   -\->
		<person:name.detail>
			<xsl:apply-templates select="@* | node()"/>
		</person:name.detail>

	</xsl:template>

	<xsl:template match="name.degree">

		<!-\-  Original Target XPath:  person:name.degree   -\->
		<person:name.degree>
			<xsl:apply-templates select="@* | node()"/>
		</person:name.degree>

	</xsl:template>
-->
</xsl:stylesheet>