<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:location="http://www.lexisnexis.com/xmlschemas/content/shared/location/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="IN05_Rosetta_address">
  <title>address <lnpid>id-IN05-38811</lnpid></title>
  <body>
    <section>
      <p>
        <sourcexml>address</sourcexml> becomes <targetxml>location:address</targetxml>. The child
        elements of <sourcexml>address</sourcexml> are converted as following: </p>
      <p>
        <ul id="ul_rsv_wq3_zw">
          <li>
            <sourcexml>address/address.line</sourcexml> becomes
              <targetxml>location:address/location:address.line</targetxml>. </li>
          <li>
            <sourcexml>address/address.qualifier</sourcexml> becomes
              <targetxml>location:address/location:address.line</targetxml>. </li>
          <li>
            <sourcexml>address/street</sourcexml> becomes
              <targetxml>location:address/location:street</targetxml>. </li>
          <li>
            <sourcexml>address/city</sourcexml> becomes
              <targetxml>location:address/location:city</targetxml>. </li>
          <li>
            <sourcexml>address/postalcode</sourcexml> becomes
              <targetxml>location:address/location:postalcode</targetxml>. </li>
          <li>
            <sourcexml>address/phone</sourcexml> becomes
              <targetxml>location:address/contact:phone</targetxml>. </li>
        </ul>
      </p>
    </section>
    <pre>
              <b><i>Example: Source XML 1</i></b>
                  

&lt;p&gt;
    &lt;text&gt;&lt;company&gt;Presidency Transports, Ltd.&lt;/company&gt;,
        &lt;address&gt;&lt;postalcode&gt;11&amp;#x002D;A,&lt;/postalcode&gt; &lt;address.line&gt;Mount Road,&lt;/address.line&gt; &lt;city&gt;Madras&lt;/city&gt;&lt;/address&gt;.&lt;/text&gt;
&lt;/p&gt;
 
	</pre>
    <pre>          <b><i>Example: Target XML 1</i></b>

    
&lt;p&gt;
    &lt;text&gt;
        &lt;entity:company&gt;Presidency Transports, Ltd.&lt;/entity:company&gt;,
        &lt;location:address&gt;
            &lt;location:postalcode&gt;11-A,&lt;/location:postalcode&gt;
            &lt;location:address.line&gt;Mount Road,&lt;/location:address.line&gt;
            &lt;location:city&gt;Madras&lt;/location:city&gt;
        &lt;/location:address&gt;.&lt;/text&gt;
&lt;/p&gt;  

                </pre>
    
    <section>
      <title>Changes</title>
      <p>2016-08-17: <ph id="change_20160817_AS">Created.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-IN\IN05-Articles\IN05_Rosetta_address.dita  -->
	<xsl:message>IN05_Rosetta_address.xsl requires manual development!</xsl:message> 

	<xsl:template match="address">

		<!--  Original Target XPath:  location:address   -->
		<location:address>
			<xsl:apply-templates select="@* | node()"/>
		</location:address>

	</xsl:template>

	<xsl:template match="address/address.line">

		<!--  Original Target XPath:  location:address/location:address.line   -->
		<location:address>
			<location:address.line>
				<xsl:apply-templates select="@* | node()"/>
			</location:address.line>
		</location:address>

	</xsl:template>

	<xsl:template match="address/address.qualifier">

		<!--  Original Target XPath:  location:address/location:address.line   -->
		<location:address>
			<location:address.line>
				<xsl:apply-templates select="@* | node()"/>
			</location:address.line>
		</location:address>

	</xsl:template>

	<xsl:template match="address/street">

		<!--  Original Target XPath:  location:address/location:street   -->
		<location:address>
			<location:street>
				<xsl:apply-templates select="@* | node()"/>
			</location:street>
		</location:address>

	</xsl:template>

	<xsl:template match="address/city">

		<!--  Original Target XPath:  location:address/location:city   -->
		<location:address>
			<location:city>
				<xsl:apply-templates select="@* | node()"/>
			</location:city>
		</location:address>

	</xsl:template>

	<xsl:template match="address/postalcode">

		<!--  Original Target XPath:  location:address/location:postalcode   -->
		<location:address>
			<location:postalcode>
				<xsl:apply-templates select="@* | node()"/>
			</location:postalcode>
		</location:address>

	</xsl:template>

	<xsl:template match="address/phone">

		<!--  Original Target XPath:  location:address/contact:phone   -->
		<location:address>
			<contact:phone xmlns:contact="http://www.lexisnexis.com/xmlschemas/content/shared/contact/1/">
				<xsl:apply-templates select="@* | node()"/>
			</contact:phone>
		</location:address>

	</xsl:template>

</xsl:stylesheet>