<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="IN05_Rosetta_publication">
    <title>publication <lnpid>id-IN05-38830</lnpid></title>

    <body>
        <p><sourcexml>publication</sourcexml> becomes
                <targetxml>doc:metadata/pubinfo:pubinfo/pubinfo:publicationname</targetxml>.</p>
        <example>
            <title>Source XML</title>
            <codeblock>

&lt;jrnl:info&gt;
    &lt;publication&gt;ASIL&lt;/publication&gt;
&lt;/jrnl:info&gt;

           </codeblock>
            <title>Target XML</title>
            <codeblock>

&lt;doc:metadata&gt;
    &lt;pubinfo:pubinfo&gt;
        &lt;pubinfo:publicationname&gt;ASIL&lt;/pubinfo:publicationname&gt;
    &lt;/pubinfo:pubinfo&gt;
&lt;/doc:metadata&gt;

           </codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>2016-08-16: <ph id="change_20160816_AS">Created.</ph></p>           
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-IN\IN05-Articles\IN05_Rosetta_publication.dita  -->
	<xsl:message>IN05_Rosetta_publication.xsl requires manual development!</xsl:message> 

	<xsl:template match="publication">

		<!--  Original Target XPath:  doc:metadata/pubinfo:pubinfo/pubinfo:publicationname   -->
		<doc:metadata>
			<pubinfo:pubinfo xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/">
				<pubinfo:publicationname>
					<xsl:apply-templates select="@* | node()"/>
				</pubinfo:publicationname>
			</pubinfo:pubinfo>
		</doc:metadata>

	</xsl:template>

</xsl:stylesheet>