<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:funddoc="urn:x-lexisnexis:content:fundamentallegaldocument:sharedservices:1" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Introduction">
    <title>Introduction <lnpid>id-st07-31410</lnpid></title>
    
    <shortdesc>This Conversion Instructions describes the standard conversion of the Rosetta LEGDOC
        DTD to <b>funddoc 2.5_PROD</b> schema.</shortdesc>
    <prolog>
        <metadata>
            <prodinfo>
                <prodname><keyword>International Instruments</keyword></prodname>
                <vrmlist>
                    <vrm version="2.5 PROD"/>
                </vrmlist>
            </prodinfo>
        </metadata>
    </prolog>
    <body>    
        <p>International Instrument samples are identified using the root element <b>LEGDOC</b>
            with attribute <b>@legtype="treaty-conv"</b> only.</p>
        <section><title>Root Element</title>
            <p><sourcexml>LEGDOC/@legtype="treaty-conv"</sourcexml> becomes
                    <targetxml>funddoc:fundamentallegaldocument</targetxml>. It's a root element for
                International Instrument. <ul>
                    <li> Standard International Instruments documents are identified using the root
                        element <sourcexml>LEGDOC/@legtype="treaty-conv"</sourcexml> with
                            <sourcexml>docinfo:selector</sourcexml> value being set to "treaty-conv"
                        or "legislation".</li>
                    <li>If input source document has <sourcexml>LEGDOC[@id]</sourcexml> it becomes
                            <targetxml>funddoc:fundamentallegaldocument[@xml:id]</targetxml></li>
                </ul>
                <pre>
         

&lt;LEGDOC legtype="treaty-conv"&gt;
        ...
        &lt;docinfo:doc-lang lang="en"/&gt;
        &lt;docinfo:doc-country iso-cc="AU"/&gt;
        ...
&lt;/LEGDOC&gt;

<b>Becomes</b>
            

&lt;funddoc:fundamentallegaldocument xml:lang="en-AU"&gt;
      
      &lt;funddoc:head&gt;...&lt;/funddoc:head&gt;
    
      &lt;funddoc:body&gt;...&lt;/funddoc:body&gt;
    
      &lt;doc:metadata&gt;...&lt;/doc:metadata&gt;
      
&lt;/funddoc:fundamentallegaldocument&gt;

        </pre>
            </p>
        </section>
        <p>The attribute <sourcexml>@searchtype</sourcexml> will be suppressed from the conversion except citation markup.</p>         
        <p><targetxml>funddoc:head</targetxml>, <targetxml>funddoc:body</targetxml> and
                <targetxml>doc:metadata</targetxml> are created as required children of
                <targetxml>funddoc:fundamentallegaldocument</targetxml></p>
        
        <section>
            <title>Note:</title>
            <p>The following information is meant to help the user understand the conventions used in this document</p>
            <p>Source elements and attributes are highlighted like this: <sourcexml>SOURCEXML</sourcexml></p>
            <p>Target elements and attributes are highlighted like this: <targetxml>TARGETXML</targetxml></p>
            <p>Copy source attributes to target attributes unless otherwise specified.</p>
            <p>Verify content of following target attributes:
                <ul>
                    <li><sourcexml>@month</sourcexml> becomes <targetxml>@month</targetxml> is between 01-12. Any numbers outside this range, do not output a <targetxml>@month</targetxml>.</li>
                    <li><sourcexml>@day</sourcexml> becomes <targetxml>@day</targetxml> is between 01-31. Any numbers outside this range, do not output <targetxml>@day</targetxml>.</li>
                    <li><sourcexml>@year</sourcexml> becomes <targetxml>@year</targetxml> is 4 digits in length. Any other lengths, do not output <targetxml>@year</targetxml>.</li>
                </ul>
            </p>
        </section>
        <section>
            <title>Changes</title>
            <p/>
        </section>    
    </body>
    
    
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\International_Instruments\Introduction.dita  -->
	<xsl:message>International_Instruments_Introduction.xsl requires manual development!</xsl:message> 

	<xsl:template match="LEGDOC/@legtype=&#34;treaty-conv&#34;">

		<!--  Original Target XPath:  funddoc:fundamentallegaldocument   -->
		<funddoc:fundamentallegaldocument>
			<xsl:apply-templates select="@* | node()"/>
		</funddoc:fundamentallegaldocument>

	</xsl:template>

	<xsl:template match="docinfo:selector">

		<!--  Original Target XPath:  funddoc:fundamentallegaldocument[@xml:id]   -->
		<funddoc:fundamentallegaldocument>
			<xsl:apply-templates select="@* | node()"/>
		</funddoc:fundamentallegaldocument>

	</xsl:template>

	<xsl:template match="LEGDOC[@id]">

		<!--  Original Target XPath:  funddoc:fundamentallegaldocument[@xml:id]   -->
		<funddoc:fundamentallegaldocument>
			<xsl:apply-templates select="@* | node()"/>
		</funddoc:fundamentallegaldocument>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:  funddoc:head   -->
		<funddoc:head>
			<xsl:apply-templates select="@* | node()"/>
		</funddoc:head>

	</xsl:template>

	<xsl:template match="SOURCEXML">

		<!--  Original Target XPath:  TARGETXML   -->
		<TARGETXML>
			<xsl:apply-templates select="@* | node()"/>
		</TARGETXML>

	</xsl:template>

	<xsl:template match="@month">

		<!--  Original Target XPath:  @month   -->
		<xsl:attribute name="month">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="@day">

		<!--  Original Target XPath:  @day   -->
		<xsl:attribute name="day">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="@year">

		<!--  Original Target XPath:  @year   -->
		<xsl:attribute name="year">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

</xsl:stylesheet>