<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl" xmlns:newsitem="http://www.lexisnexis.com/xmlschemas/content/news/newsitem/1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/" xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journals_Introduction">
  <title>Introduction <lnpid>id-MY02-16213</lnpid></title>

  <body>
    <section>
      
      <title>Root Element</title>
    <p>This Conversion Instruction describes the conversion of <b>NewsItem 4.0 PROD</b> Schema in
        the document.</p>
    
    <p>Identification Criteria for <b>MY02-Journals</b> content stream is
        <sourcexml>JOURNALDOC</sourcexml>.</p>

    <p><sourcexml>JOURNALDOC</sourcexml> becomes <targetxml>newsitem:newsitem</targetxml>. It's a
      root element for <b>Journals</b>.</p>

<pre>

&lt;JOURNALDOC&gt;
        ...
        &lt;docinfo:doc-lang lang="en"/&gt;
        &lt;docinfo:doc-country iso-cc="MY"/&gt;
        ...
&lt;/JOURNALDOC&gt;

<b>Becomes</b>

&lt;newsitem:newsitem xml:lang="en-MY"&gt;
      
      &lt;newsitem:head&gt;...&lt;/newsitem:head&gt;
      
      &lt;nitf:body&gt;...&lt;/nitf:body&gt;
      
      &lt;doc:metadata&gt;...&lt;/doc:metadata&gt;

&lt;/newsitem:newsitem&gt;
</pre>

    <p><targetxml>newsitem:head</targetxml>, <targetxml>nitf:body</targetxml>, and <targetxml>doc:metadata</targetxml> are created as required children of <targetxml>newsitem:newsitem</targetxml></p>
    <note>The <sourcexml>@searchtype</sourcexml> attribute will be suppressed from conversion except for the citation elements.</note>
    </section>      
    <section>
      <title>Note:</title>
      <p>Source elements and attributes are highlighted like this: <sourcexml>SOURCEXML</sourcexml></p>
      <p>Target elements and attributes are highlighted like this: <targetxml>TARGETXML</targetxml></p>
      <p>Copy source attributes to target attributes unless otherwise specified.</p>
      <p>Every example is represented like "EXAMPLE" in all the dita's and is captured under &lt;pre&gt; tag.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY02_Journals\Journals_Introduction.dita  -->
<!--	<xsl:message>Journals_Introduction.xsl requires manual development!</xsl:message> -->

  
  
  <xsl:template match="JOURNALDOC">
    <newsitem:newsitem>
      <xsl:call-template name="generateNSGlobalBindings"/>
      <xsl:attribute name="xsi:schemaLocation" select="$outputSchemaLoc"/>
      <xsl:apply-templates select="@*"/>
      <xsl:call-template name="xml_lang"/>
      <newsitem:head>
        <xsl:apply-templates select="jrnl:body/jrnl:info/jrnl:journalcite"/>
      </newsitem:head>
      <xsl:apply-templates select="jrnl:body"/>
      <doc:metadata>
        <xsl:if test="jrnl:body/jrnl:info/pubdate">
          <pubinfo:pubinfo>
            <xsl:apply-templates select="jrnl:body/jrnl:info/pubdate"/>
            <xsl:apply-templates select="jrnl:body/jrnl:info/publication"/>
          </pubinfo:pubinfo>
        </xsl:if>
        <xsl:apply-templates select="docinfo"/>
      </doc:metadata>
    </newsitem:newsitem>
  </xsl:template>
  
  <!-- suppress Rosetta-dtd specific atts -->
  <xsl:template match="JOURNALDOC/@xml:lang"/>
  
  <xsl:template match="JOURNALDOC/@version"/>
  
  <xsl:template match="JOURNALDOC/@versionminor"/>
  
  <xsl:template match="JOURNALDOC/@id"/>
  
  
</xsl:stylesheet>