<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:glp="http://www.lexis-nexis.com/glp" version="2.0" exclude-result-prefixes="dita glp">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journaldoc-level">
  <title>level <lnpid>id-ST09-32630</lnpid></title>

  <body>
    <p><sourcexml>level</sourcexml> becomes <targetxml>section</targetxml>.</p>
      
      <p>If <sourcexml>level</sourcexml> has an attributes than follow below mappings:
      
      <ul>
          <li><sourcexml>@subdoc</sourcexml> becomes <targetxml>@includeintoc</targetxml>.</li>
          <li><sourcexml>@toc-caption</sourcexml> becomes <targetxml>@alternatetoccaption</targetxml>.</li>
          <li><sourcexml>@leveltype</sourcexml> attribute, it should be suppressed.</li>
      </ul>
      </p>
      
<pre>
    <b><i>Source example based on AU content</i></b>
    
&lt;level&gt;
    &lt;bodytext&gt;
        &lt;h l="2" align="left" searchtype="HEADING"&gt;&lt;emph typestyle="bf"&gt;A Introduction&lt;/emph&gt;&lt;/h&gt;
        &lt;p&gt;
            &lt;text&gt;This study was commissioned by the Insurance Bureau of Canada to identify 
                legal developments, principally court decisions but also legislation, which could 
                have had an impact on the cost of liability insurance. We say 'could have' to underline 
                the limits of the study. We are neither economists nor actuaries and make no claims about 
                definitive causal connections between cases or statutes and the cost of insurance.  
                Rather, we examine cases and statutes as lawyers, pointing out where we believe that changes 
                in the law have increased the exposure of insurers. The quantification of the increase in 
                cost, if any, we leave to others.&lt;/text&gt;
        &lt;/p&gt;
    &lt;/bodytext&gt;
&lt;/level&gt;

<b>Becomes</b>

&lt;section&gt;
    &lt;bodytext&gt;
        &lt;h level="2" align="left"&gt;&lt;emph typestyle="bf"&gt;A Introduction&lt;/emph&gt;&lt;/h&gt;
        &lt;p&gt;
            &lt;text&gt;This study was commissioned by the Insurance Bureau of Canada to identify 
                legal developments, principally court decisions but also legislation, which could 
                have had an impact on the cost of liability insurance. We say 'could have' to underline 
                the limits of the study. We are neither economists nor actuaries and make no claims about 
                definitive causal connections between cases or statutes and the cost of insurance.  
                Rather, we examine cases and statutes as lawyers, pointing out where we believe that changes 
                in the law have increased the exposure of insurers. The quantification of the increase in 
                cost, if any, we leave to others.&lt;/text&gt;
        &lt;/p&gt;
    &lt;/bodytext&gt;
&lt;/section&gt;
</pre>
      
      <p>If <sourcexml>glp:note</sourcexml> is the sibling of <sourcexml>bodytext</sourcexml> then move the <targetxml>note</targetxml> as the immediate child of <targetxml>bodytext</targetxml>.</p>
      
<pre>
    <b><i>Source example based on AU content</i></b>
    
&lt;level&gt;
    &lt;heading&gt;
        &lt;title&gt;Application for default judgment &amp;mdash; failure to appear &amp;mdash; failure to attend
            ...&lt;/title&gt;
    &lt;/heading&gt;
    &lt;glp:note&gt;
        &lt;contrib&gt;Nokia Corp v Millaras (No 3) [2010] FCA 1396; BC201009540 (Jagot&amp;nbsp;J,
            8&amp;nbsp;December 2010)&lt;/contrib&gt;
    &lt;/glp:note&gt;
    &lt;bodytext&gt;
        ...
    &lt;/bodytext&gt;
&lt;/level&gt;

<b>Becomes</b>

&lt;section&gt;
    &lt;heading&gt;
        &lt;title&gt;Application for default judgment &amp;#x2014; failure to appear &amp;#x2014; failure to
            attend ...&lt;/title&gt;
    &lt;/heading&gt;
    &lt;bodytext&gt;
        &lt;note&gt;
            &lt;bodytext&gt;
                &lt;person:contributor&gt;Nokia Corp v Millaras (No 3) [2010] FCA 1396; BC201009540
                    (Jagot&amp;#x00A0;J, 8&amp;#x00A0;December 2010)&lt;/person:contributor&gt;
            &lt;/bodytext&gt;
        &lt;/note&gt;
        ...
    &lt;/bodytext&gt;
&lt;/section&gt;          
</pre>
      
      <section>
          <title>Changes</title>
          <p>Created.</p>
      </section>
      
</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Newsitem\Journaldoc-level.dita  -->
	<xsl:message>Journaldoc-level.xsl requires manual development!</xsl:message> 

	<xsl:template match="level">

		<!--  Original Target XPath:  section   -->
		<section>
			<xsl:apply-templates select="@* | node()"/>
		</section>

	</xsl:template>

	<xsl:template match="@subdoc">

		<!--  Original Target XPath:  @includeintoc   -->
		<xsl:attribute name="includeintoc">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="@toc-caption">

		<!--  Original Target XPath:  @alternatetoccaption   -->
		<xsl:attribute name="alternatetoccaption">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="@leveltype">

		<!--  Original Target XPath:  note   -->
		<note>
			<xsl:apply-templates select="@* | node()"/>
		</note>

	</xsl:template>

	<xsl:template match="glp:note">

		<!--  Original Target XPath:  note   -->
		<note>
			<xsl:apply-templates select="@* | node()"/>
		</note>

	</xsl:template>

	<xsl:template match="bodytext">

		<!--  Original Target XPath:  note   -->
		<note>
			<xsl:apply-templates select="@* | node()"/>
		</note>

	</xsl:template>

</xsl:stylesheet>