<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journaldoc-abstract">
    <title>abstract <lnpid>id-ST09-32607</lnpid></title>
    <body>
        <p><sourcexml>abstract</sourcexml> becomes <targetxml>nitf:body.head/abstract</targetxml>.
            Any content inside <sourcexml>abstract</sourcexml> should be mapped to
                <targetxml>abstract/bodytext</targetxml>.</p>

<pre>
    <b><i>Source example based on UK content</i></b>

&lt;jrnl:prelim searchtype="ARTICLE"&gt;
    ...
    &lt;abstract&gt;
        &lt;p&gt;
            &lt;text&gt;In the final part of her series on the implications of data protection law for the insurance and financial services
                industries, Bridget Treacy, of Barlow Lyde &amp;amp; Gilbert, discusses the legal justifications for using sensitive personal
                data, such as health information and criminal convictions&lt;/text&gt;
        &lt;/p&gt;
    &lt;/abstract&gt;
&lt;/jrnl:prelim&gt;

<b>Becomes</b>

&lt;nitf:body.head&gt;
    ...
    &lt;abstract&gt;
        &lt;bodytext&gt;
            &lt;p&gt;
                &lt;text&gt;In the final part of her series on the implications of data protection law for the insurance and financial services
                    industries, Bridget Treacy, of Barlow Lyde &amp;amp; Gilbert, discusses the legal justifications for using sensitive personal
                    data, such as health information and criminal convictions&lt;/text&gt;
            &lt;/p&gt;
        &lt;/bodytext&gt;
    &lt;/abstract&gt;
&lt;/nitf:body.head&gt;
</pre>
        <section>
            <title>Changes</title>
            <p>Created.</p>
        </section>
    </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Newsitem\Journaldoc-abstract.dita  -->
	<xsl:message>Journaldoc-abstract.xsl requires manual development!</xsl:message> 

	<xsl:template match="abstract">

		<!--  Original Target XPath:  nitf:body.head/abstract   -->
		<nitf:body.head>
			<abstract>
				<xsl:apply-templates select="@* | node()"/>
			</abstract>
		</nitf:body.head>

	</xsl:template>

</xsl:stylesheet>