<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.comntry2-source">
  <title>Source XML</title>
  <body>
    <codeblock>

&lt;leg:body&gt;
 &lt;!-- ETC. --&gt;
 &lt;leg:level id="NLC.S6"&gt;
  &lt;leg:level-vrnt leveltype="prov1" searchtype="LEGISLATION SECT" subdoc="true" toc-caption="[51] 6 Director General of Lands and Mines and other Federal Officers"&gt;
   &lt;leg:heading inline="true"&gt;
    &lt;edpnum&gt;&lt;refpt id="NLC.S6" type="ext"/&gt;[51]&lt;/edpnum&gt;
    &lt;desig inline="true" searchtype="SECT-NUM"&gt;
     &lt;designum&gt;6&lt;/designum&gt;
    &lt;/desig&gt;
    &lt;title inline="true" searchtype="SECT-TITLE"&gt;Director General of Lands and Mines and other Federal Officers&lt;/title&gt;
   &lt;/leg:heading&gt;
   &lt;leg:levelbody&gt;
    &lt;leg:bodytext&gt;
     &lt;!-- ETC. --&gt;
     &lt;leg:comntry subdoc="true" toc-caption="Commentary"&gt;
      &lt;level id="NLC.VI.GROUP1" leveltype="comm30" subdoc="true" toc-caption="AMENDMENTS"&gt;
       &lt;heading searchtype="COMMENTARY"&gt;
        &lt;title&gt;&lt;emph typestyle="caps"&gt;&lt;refpt id="NLC.VI.GROUP1" type="ext"/&gt;AMENDMENTS&lt;/emph&gt;&lt;/title&gt;
       &lt;/heading&gt;
       &lt;level id="NLC.VI.52" leveltype="comm36" subdoc="true" toc-caption="[52]-[100]"&gt;
        &lt;heading searchtype="COMMENTARY"&gt;
         &lt;edpnum&gt;&lt;refpt id="NLC.VI.52" type="ext"/&gt;[52]-[100] &lt;/edpnum&gt;
        &lt;/heading&gt;
         &lt;bodytext searchtype="COMMENTARY"&gt;
          &lt;!-- ETC. --&gt;
         &lt;/bodytext&gt;
        &lt;/level&gt;
       &lt;/level&gt;
      &lt;/leg:comntry&gt;
     &lt;/leg:bodytext&gt;
    &lt;/leg:levelbody&gt;
   &lt;/leg:level-vrnt&gt;
  &lt;/leg:level&gt;
 &lt;!-- ETC. --&gt;                                           
&lt;/leg:body&gt;

    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY04-Annotated_legislation\leg.comntry2-source.dita  -->
	<xsl:message>leg.comntry2-source.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>