<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.comntry2-target">
  <title>Target XML</title>
  <body>
    <codeblock>

&lt;legis:body&gt;
 &lt;primlaw:level leveltype="section" alternatetoccaption="&amp;#x005B;51&amp;#x005D; 6 Director General of Lands and Mines and other Federal Officers" includeintoc="true"&gt;
  &lt;ref:anchor id="NLC.S6" anchortype="global"/&gt;
  &lt;heading&gt;
   &lt;altdesig&gt;&amp;#x005B;51&amp;#x005D;&lt;/altdesig&gt;
   &lt;desig inline="true"&gt;6&lt;/desig&gt;
   &lt;title inline="true"&gt;Director General of Lands and Mines and other Federal Officers&lt;/title&gt;
  &lt;/heading&gt;
  &lt;primlaw:bodytext&gt;
   &lt;!-- ETC. --&gt;
  &lt;/primlaw:bodytext&gt;
  &lt;annot:annotations&gt;
   &lt;annot:annotation-grp grptype="COMMENTARY" includeintoc="true" alternatetoccaption="Commentary"&gt;
    &lt;annot:annotation xml:id="NLC.VI.GROUP1" includeintoc="true" alternatetoccaption="AMENDMENTS"&gt;
     &lt;ref:anchor id="NLC.VI.GROUP1" anchortype="global"/&gt;
     &lt;heading&gt;
      &lt;title&gt;AMENDMENTS&lt;/title&gt;
     &lt;/heading&gt;
     &lt;annot:annotationlevel xml:id="NLC.VI.52" alternatetoccaption="&amp;#x005B;52&amp;#x005D;-&amp;#x005B;100&amp;#x005D;" includeintoc="true"&gt;
      &lt;ref:anchor id="NLC.VI.52" anchortype="global"/&gt;
      &lt;heading&gt;
       &lt;desig&gt;&amp;#x005B;52&amp;#x005D;-&amp;#x005B;100&amp;#x005D; &lt;/desig&gt;
      &lt;/heading&gt;
      &lt;annot:bodytext&gt;
       &lt;!-- ETC. --&gt;
      &lt;/annot:bodytext&gt;
     &lt;/annot:annotationlevel&gt;
    &lt;/annot:annotation&gt;
   &lt;/annot:annotation-grp&gt;
  &lt;/annot:annotations&gt;
 &lt;/primlaw:level&gt;
 &lt;!-- ETC. --&gt;
&lt;/legis:body&gt;

    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY04-Annotated_legislation\leg.comntry2-target.dita  -->
	<xsl:message>leg.comntry2-target.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>