<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.officialnum-source">
  <title>Source XML</title>
  <body>
    <codeblock>

&lt;leg:info&gt;
 &lt;!-- ETC. --&gt;
 &lt;leg:officialnum ln.user-displayed="false" searchtype="LEGISLATION"&gt;Act No. 257, 1952&lt;/leg:officialnum&gt;
 &lt;!-- ETC. --&gt;
&lt;/leg:info&gt; 

    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY04-Annotated_legislation\leg.officialnum-source.dita  -->
	<xsl:message>leg.officialnum-source.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>