<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:navaid="urn:x-lexisnexis:content:navigationaid:sharedservices:1" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="usm_landingpgs-legdoc">
  <title><sourcexml>/LEGDOC</sourcexml> (document root) <lnpid>id-MY08-17621</lnpid></title>
  <body>
    <p>The root element <sourcexml>/LEGDOC</sourcexml> becomes <targetxml>/navaid:landingpage</targetxml>. <ul>
      <li>All attributes of <sourcexml>/LEGDOC</sourcexml>, including <sourcexml>/LEGDOC/@legtype</sourcexml>, are dropped.</li>
      <li>All references to the namespace names listed in the topic <xref href="namespaces.dita"/> are creatd as attributes of <targetxml>navaid:landingpage</targetxml>.</li>
      <li>The attribute <targetxml>navaid:landingpage/@xml:lang</targetxml> is created as describe in the topic <xref href="../../common_newest/Rosetta_docinfo.doc-lang-and-doc-country-LxAdv-ROOT_xml.lang.dita"/>.</li>
    </ul>
      </p>
      <section>
        <title>Source XML</title>
        <p>The example below shows the source root element <targetxml>LEGDOC</targetxml> as well as the <sourcexml>docinfo</sourcexml> children used in the creation of the target attribute <targetxml>navaid:landingpage/@xml:lang</targetxml>.</p>
        <codeblock>

&lt;LEGDOC 
  legtype="act" 
  xmlns:case="http://www.lexis-nexis.com/glp/case"
  xmlns:ci="http://www.lexis-nexis.com/ci" 
  xmlns:comm="http://www.lexis-nexis.com/glp/comm"
  xmlns:cttr="http://www.lexis-nexis.com/glp/cttr" 
  xmlns:dict="http://www.lexis-nexis.com/glp/dict"
  ...
  xmlns:xhtml="http://www.w3c.org/1999/xhtml"
  &gt;
  &lt;docinfo partitionnum="LEG1"&gt;
    ...
    &lt;docinfo:doc-lang lang="en"/&gt;
    &lt;docinfo:doc-country iso-cc="MY"/&gt;
    ...

</codeblock>
      </section>
    <section>
      <title>Target XML</title>
        <p>The example below shows the creation of the root element <targetxml>navaid:landingpage</targetxml> and its attributes. For context, it also shows the tags for the two immediate child elements <targetxml>navaid:landingpagebody</targetxml> and <targetxml>doc:metadata</targetxml>.</p>
        <codeblock>

&lt;navaid:landingpage 
  xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  xmlns:classify="http://www.lexisnexis.com/xmlschemas/content/shared/classification/1/"
  xmlns:contact="http://www.lexisnexis.com/xmlschemas/content/shared/contact/1/"
  ...
  xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/"
  xml:lang="en-MY"
  &gt;
  &lt;navaid:landingpagebody&gt;
    ...
  &lt;/navaid:landingpagebody&gt;
  &lt;doc:metadata&gt;
    ...
  &lt;/doc:metadata&gt;
&lt;/navaid:landingpage&gt;

        </codeblock>
      </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY08_navaid\legdoc.dita  -->
	<xsl:message>legdoc.xsl requires manual development!</xsl:message> 

	<xsl:template match="/LEGDOC">

		<!--  Original Target XPath:  /navaid:landingpage   -->
		<navaid:landingpage>
			<xsl:apply-templates select="@* | node()"/>
		</navaid:landingpage>

	</xsl:template>

	<xsl:template match="/LEGDOC/@legtype">

		<!--  Original Target XPath:  navaid:landingpage   -->
		<navaid:landingpage>
			<xsl:apply-templates select="@* | node()"/>
		</navaid:landingpage>

	</xsl:template>

	<xsl:template match="docinfo">

		<!--  Original Target XPath:  navaid:landingpage/@xml:lang   -->
		<navaid:landingpage>
			<xsl:attribute name="xml:lang">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</navaid:landingpage>

	</xsl:template>

</xsl:stylesheet>