<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legfragment-target">
  <title>Target XML</title>
  <body>
    <codeblock>

&lt;primlaw:excerpt&gt;
 &lt;primlaw:bodytext&gt;
  &lt;p&gt;&lt;text&gt;143A Power of State Authority in relation to application for partition of land subject to the category &amp;#x22;agriculture&amp;#x22;&lt;/text&gt;
   &lt;!-- ETC. --&gt;
  &lt;/p&gt;
 &lt;/primlaw:bodytext&gt; 
&lt;/primlaw:excerpt&gt;
    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY04-Annotated_legislation\legfragment-target.dita  -->
	<xsl:message>legfragment-target.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>