<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:casedigest="http://www.lexisnexis.com/xmlschemas/content/legal/case-digest/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Linxplus-CaseDigest_abstract">
  <title>abstract <lnpid>id-NZ07DC-23607</lnpid></title>

  <body>
    
      <p><sourcexml>abstract</sourcexml> becomes <targetxml>casedigest:otherinfo/@infotype</targetxml>.</p>
      
      <p>When <sourcexml>p</sourcexml> is the first child of <sourcexml>abstract</sourcexml> then conversion should create <targetxml>@infotype="miscellaneous"</targetxml>.</p>
      
      <p>When <sourcexml>catchwordgrp</sourcexml> is the first child of <sourcexml>abstract</sourcexml> then conversion should create <targetxml>@infotype="abstract"</targetxml>.</p>
      
      <p><sourcexml>abstract/p</sourcexml> becomes <targetxml>casedigest:otherinfo@infotype="miscellaneous"/bodytext/p</targetxml>.</p>
      
      <p>Example when <sourcexml>p</sourcexml> is the first child of
            <sourcexml>abstract</sourcexml></p>
      <pre xml:space="preserve" class="- topic/pre ">
&lt;abstract&gt;
    &lt;p&gt;
        &lt;text&gt;&lt;process-ignore process="kwd"&gt;&lt;emph typestyle="bf"&gt;Location:
            &lt;/emph&gt;&lt;/process-ignore&gt;Auckland Wellington Canterbury Library (Members only)&lt;/text&gt;
    &lt;/p&gt;
&lt;/abstract&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;casedigest:otherinfo infotype="miscellaneous"&gt;
    &lt;bodytext&gt;
        &lt;p&gt;
            &lt;text&gt;&lt;emph typestyle="bf"&gt;Location: &lt;/emph&gt;Auckland Wellington Canterbury Library
                (Members only)&lt;/text&gt;
        &lt;/p&gt;
    &lt;/bodytext&gt;
&lt;/casedigest:otherinfo&gt;
      </pre>
      
      <p>Example when <sourcexml>catchwordgrp</sourcexml> is the first child of
                <sourcexml>abstract</sourcexml></p>
      <pre xml:space="preserve" class="- topic/pre ">
&lt;abstract&gt;
    &lt;catchwordgrp&gt;
        &lt;catchwords&gt;
            &lt;catchphrase&gt;COMPANY LAW - breach of s62 Companies Act 1955 - Government and Equiticorp
                Holdings Ltd (EHL) entered into agreement whereby Government swapped its New Zealand
                Steel (NZS) shares for Equiticorp shares - simultaneously Government and Buttle
                Wilson Ltd (BWL) entered into agreement whereby BWL agreed to underwrite the buy
                back of Equiticorp shares 5 months later for $327 million - when buy back did occur
                (through a shelf company ... &lt;/catchphrase&gt;
        &lt;/catchwords&gt;
    &lt;/catchwordgrp&gt;
    &lt;p&gt;
        &lt;text&gt;&lt;process-ignore process="kwd"&gt;&lt;emph typestyle="bf"&gt;Location:
        &lt;/emph&gt;&lt;/process-ignore&gt;Auckland Wellington Canterbury Library (Members only)&lt;/text&gt;
    &lt;/p&gt;
&lt;/abstract&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;casedigest:otherinfo infotype="abstract"&gt;
    &lt;bodytext&gt;
        &lt;p&gt;
            &lt;text&gt;COMPANY LAW - breach of s62 Companies Act 1955 - Government and Equiticorp
                Holdings Ltd (EHL) entered into agreement whereby Government swapped its New Zealand
                Steel (NZS) shares for Equiticorp shares - simultaneously Government and Buttle
                Wilson Ltd (BWL) entered into agreement whereby BWL agreed to underwrite the buy
                back of Equiticorp shares 5 months later for $327 million - when buy back did occur
                (through a shelf company ... &lt;/text&gt;
        &lt;/p&gt;
        &lt;p&gt;
            &lt;text&gt;&lt;emph typestyle="bf"&gt;Location: &lt;/emph&gt;Auckland Wellington Canterbury Library
                (Members only)&lt;/text&gt;
        &lt;/p&gt;
    &lt;/bodytext&gt;
&lt;/casedigest:otherinfo&gt;
</pre>
      
      <note>Conversion should not create consecutive <targetxml>casedigest:otherinfo</targetxml>
          elements. When 2 or more consecutive sibling source elements map to
          <targetxml>casedigest:otherinfo</targetxml>, data should be merged to a single
          <targetxml>casedigest:otherinfo</targetxml> element unless this would hamper content
          ordering.</note>
      <section>
          <title>Changes</title>
          <p>2014-01-07: <ph id="change_20140107_PS">Updated target mapping and example, Webteam #: 248880, this change directly affects NZ07-Casedigest.</ph></p>
      </section>
</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ07_Linxplus\NZ07DC_Linxplus-CaseDigest\Linxplus-CaseDigest_abstract.dita  -->
	<!--<xsl:message>Linxplus-CaseDigest_abstract.xsl requires manual development!</xsl:message>--> 
   
	<xsl:template match="abstract">
		
		    <xsl:choose>
		        <xsl:when test="child::*[1][name()='p']">
		            <casedigest:otherinfo>
		            <xsl:attribute name="infotype">
		                <xsl:text>miscellaneous</xsl:text>
		            </xsl:attribute>
		            <bodytext>
		                <xsl:apply-templates select="@* | node() | child::catchwordgrp/catchwords/catchphrase"/>
		            </bodytext>
		            </casedigest:otherinfo>
		        </xsl:when>
		        
		        <xsl:when test="child::*[1][name()='catchwordgrp']">
		            <casedigest:otherinfo>
		            <xsl:attribute name="infotype">
		                <xsl:text>abstract</xsl:text>
		            </xsl:attribute>
		            <bodytext>
		                <xsl:apply-templates select="@* | node() | child::catchwordgrp/catchwords/catchphrase"/>
		            </bodytext>
		            </casedigest:otherinfo>
		        </xsl:when>
		        <xsl:when test="normalize-space(string(.)) = ''"/>
		    </xsl:choose>
		
	</xsl:template>
    
    <xsl:template match="catchwords/catchphrase">
                <p>
                    <text>
                        <xsl:apply-templates select="@* | node()"/>
                    </text>
                </p>    
    </xsl:template>
    <xsl:template match="catchwordgrp[parent::abstract]"/>
</xsl:stylesheet>