<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:legislaturerecord="urn:x-lexisnexis:content:legislature-record:sharedservices:1" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Introduction">
  <title>Introduction <lnpid>id-MX02-33808</lnpid></title>
  <shortdesc>This Conversion Instructions describes the conversion of the Rosetta LEGDOC DTD to
      <b>Legislature Records Schema Version 1.7_PROD</b>.</shortdesc>
  <body>
    
    <p>Mexico Gazette samples are identified using the root element <sourcexml>LEGDOC</sourcexml>
      along with attribute <sourcexml>@legtype</sourcexml> which contains value
        <sourcexml>act</sourcexml> and <sourcexml>docinfo:selector</sourcexml> markup is having a
      value "<b>Gazette</b>".</p>

    <section>
      Root element <sourcexml>LEGDOC</sourcexml> becomes <targetxml>legislaturerecord:legislaturerecord</targetxml> which is the root element of Legislature Record Schema. The source attribute <sourcexml>@xml:lang</sourcexml>, if present, can be dropped, as a separate rule has been defined to populate <targetxml>legislaturerecord:legislaturerecord/@xml:lang</targetxml>.</section>
    <section>
      <note>If input document is having country code value "<b>US</b>" then it should be replaced
        with "<b>MX</b>" value.</note>
      <note>The attribute <sourcexml>@searchtype</sourcexml> will be suppressed from the conversion except citation markup.</note>
      <pre>

&lt;LEGDOC&gt;
  ...
  &lt;docinfo:doc-lang lang="en"/&gt;
  &lt;docinfo:doc-country iso-cc="US"/&gt;
  ...          
&lt;/LEGDOC&gt;


          <b>Becomes</b>


&lt;legislaturerecord:legislaturerecord xml:lang="en-MX"&gt;
  ...
&lt;/legislaturerecord:legislaturerecord&gt;

      </pre>
      
      <note>Elements <targetxml>legislaturerecord:head</targetxml>, <targetxml>legislaturerecord:body</targetxml> and <targetxml>doc:metadata</targetxml> are created as required children of root element <targetxml>legislaturerecord:legislaturerecord</targetxml> during conversion.</note>
      
      <p><b>Note:</b></p>
      <p>Source elements and attributes are highlighted like this:
        <sourcexml>SOURCEXML</sourcexml></p>
      <p>Target elements and attributes are highlighted like this:
        <targetxml>TARGETXML</targetxml></p>
      <p>Copy source attributes to target attributes unless otherwise specified.</p>
      <p>Every example is represented like EXAMPLE in all the Conversion Instructions
        and is captured under <pre>pre</pre> tag.</p>
    </section>
  </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\MX02-Gazette\Introduction.dita  -->
	<xsl:message>MX02-Gazette_Introduction.xsl requires manual development!</xsl:message> 

	<xsl:template match="LEGDOC">

		<!--  Original Target XPath:  legislaturerecord:legislaturerecord   -->
		<legislaturerecord:legislaturerecord>
			<xsl:apply-templates select="@* | node()"/>
		</legislaturerecord:legislaturerecord>

	</xsl:template>

	<xsl:template match="@legtype">

		<!--  Original Target XPath:  legislaturerecord:legislaturerecord   -->
		<legislaturerecord:legislaturerecord>
			<xsl:apply-templates select="@* | node()"/>
		</legislaturerecord:legislaturerecord>

	</xsl:template>

	<xsl:template match="act">

		<!--  Original Target XPath:  legislaturerecord:legislaturerecord   -->
		<legislaturerecord:legislaturerecord>
			<xsl:apply-templates select="@* | node()"/>
		</legislaturerecord:legislaturerecord>

	</xsl:template>

	<xsl:template match="docinfo:selector">

		<!--  Original Target XPath:  legislaturerecord:legislaturerecord   -->
		<legislaturerecord:legislaturerecord>
			<xsl:apply-templates select="@* | node()"/>
		</legislaturerecord:legislaturerecord>

	</xsl:template>

	<xsl:template match="@xml:lang">

		<!--  Original Target XPath:  legislaturerecord:legislaturerecord/@xml:lang   -->
		<legislaturerecord:legislaturerecord>
			<xsl:attribute name="xml:lang">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</legislaturerecord:legislaturerecord>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:  legislaturerecord:head   -->
		<legislaturerecord:head>
			<xsl:apply-templates select="@* | node()"/>
		</legislaturerecord:head>

	</xsl:template>

	<xsl:template match="SOURCEXML">

		<!--  Original Target XPath:  TARGETXML   -->
		<TARGETXML>
			<xsl:apply-templates select="@* | node()"/>
		</TARGETXML>

	</xsl:template>

</xsl:stylesheet>