<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="pubdate">
  <title>pubdate <lnpid>id-MX03-34222</lnpid></title>
  <body>
    <section>
      <p>
        <sourcexml>pubdate</sourcexml> becomes
          <targetxml>doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate</targetxml>
      </p>
      <p><sourcexml>pubdate/date</sourcexml> becomes <targetxml>pubinfo:pubdate/datetext</targetxml>
        and it's attribute will be mapped with <targetxml>pubinfo:pubdate</targetxml>
        <ul id="ul_axw_yzd_tp">
          <li><sourcexml>date/@day</sourcexml> becomes <targetxml>pubinfo:
              pubdate/date/@day</targetxml></li>
          <li><sourcexml>date/@month</sourcexml> becomes <targetxml>pubinfo:
              pubdate/date/@month</targetxml></li>
          <li><sourcexml>date/@year</sourcexml> becomes <targetxml>pubinfo:
              pubdate/date/@year</targetxml></li>
        </ul>
        <note><sourcexml>pubdate</sourcexml> is mapped in <targetxml>doc:metadata</targetxml></note>
      </p>
    </section>
    <example>
      <title>Mapping of <sourcexml>pubdate</sourcexml></title>
      <codeblock>
        
&lt;leg:dates&gt;
          &lt;pubdate display-name="Fecha de publicacion"&gt;
              &lt;date day="04" month="06" year="2001"&gt;04 de junio de 2001&lt;/date&gt;
          &lt;/pubdate&gt;
&lt;/leg:dates&gt;
        
      </codeblock>
      <p>becomes</p>
      <codeblock>
        
        &lt;doc:metadata&gt;
          &lt;pubinfo:pubinfo&gt;
              &lt;pubinfo:dates&gt;
                  &lt;pubinfo:pubdate day="04" month="06" year="2001"&gt;
                        &lt;date-text&gt;04 de junio de 2001&lt;/date-text&gt;
                  &lt;pubinfo:pubdate&gt;
              &lt;/pubinfo:dates&gt;
           &lt;/pubinfo:pubinfo&gt;
        &lt;/doc:metadata&gt;
        
      </codeblock>
      <note><sourcexml>@display-name</sourcexml> will be suppressed from target</note>
    </example>
    <p>Topic paragraph</p>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\MX03-Statcode\pubdate.dita  -->
	<xsl:message>MX03-Statcode_pubdate.xsl requires manual development!</xsl:message> 

	<xsl:template match="pubdate">

		<!--  Original Target XPath:  doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate   -->
		<doc:metadata>
			<pubinfo:pubinfo>
				<pubinfo:dates>
					<pubinfo:pubdate>
						<xsl:apply-templates select="@* | node()"/>
					</pubinfo:pubdate>
				</pubinfo:dates>
			</pubinfo:pubinfo>
		</doc:metadata>

	</xsl:template>

	<xsl:template match="pubdate/date">

		<!--  Original Target XPath:  pubinfo:pubdate/datetext   -->
		<pubinfo:pubdate>
			<datetext>
				<xsl:apply-templates select="@* | node()"/>
			</datetext>
		</pubinfo:pubdate>

	</xsl:template>

	<xsl:template match="date/@day">

		<!--  Original Target XPath:  pubinfo:pubdate/date/@day   -->
		<pubinfo:pubdate>
			<date>
				<xsl:attribute name="day">
					<xsl:apply-templates select="node()"/>
				</xsl:attribute>
			</date>
		</pubinfo:pubdate>

	</xsl:template>

	<xsl:template match="date/@month">

		<!--  Original Target XPath:  pubinfo:pubdate/date/@month   -->
		<pubinfo:pubdate>
			<date>
				<xsl:attribute name="month">
					<xsl:apply-templates select="node()"/>
				</xsl:attribute>
			</date>
		</pubinfo:pubdate>

	</xsl:template>

	<xsl:template match="date/@year">

		<!--  Original Target XPath:  pubinfo:pubdate/date/@year   -->
		<pubinfo:pubdate>
			<date>
				<xsl:attribute name="year">
					<xsl:apply-templates select="node()"/>
				</xsl:attribute>
			</date>
		</pubinfo:pubdate>

	</xsl:template>

	<xsl:template match="@display-name">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>