<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:statcode="http://www.lexisnexis.com/xmlschemas/content/legal/statutorycode/1/" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="MX03_Statcode-Introduction">
       <title>Introduction <lnpid>id-MX03-34220</lnpid></title>    
   
 
    <body>
        <p>This Conversion Instruction describes the conversion of Statutory Code 5.1 PROD schema in
            the document.</p>
        
        <p>MX Statutory Code (Statecode) are identified using the root element
                <sourcexml>LEGDOC</sourcexml> with <sourcexml>docinfo:selector</sourcexml> value
            being set to "Statutes".</p>
        
        <p><sourcexml>LEGDOC</sourcexml> becomes <targetxml>statcode:statcode</targetxml>. Its a root element for Statutory Code documents.</p>
        <note>The attribute <sourcexml>@searchtype</sourcexml> will be suppressed from the conversion except citation markup.</note>
        <note><sourcexml>docinfo:doc-country/@iso-cc="US"</sourcexml> should be treated like <sourcexml>docinfo:doc-country/@iso-cc="MX"</sourcexml> in target</note>
        
        <pre>

&lt;LEGDOC&gt;
        ...
        &lt;docinfo:doc-lang lang="en"/&gt;
        &lt;docinfo:doc-country iso-cc="US"/&gt;
        ...
&lt;/LEGDOC&gt;
<b>Becomes</b>

&lt;statcode:statcode xml:lang="en-MX"&gt;
      
      &lt;statcode:head&gt;...&lt;/statcode:head&gt;

      &lt;statcode:body&gt;...&lt;/statcode:body&gt;

      &lt;doc:metadata&gt;...&lt;/doc:metadata&gt;
      
&lt;/statcode:statcode&gt;
</pre>
        
        <p><targetxml>statcode:head</targetxml>, <targetxml>statcode:body</targetxml>, and <targetxml>doc:metadata</targetxml> are created as required children of <targetxml>statcode:statcode</targetxml></p>
        
        <section>
            <title>Note:</title>
            <p>Source elements and attributes are highlighted like this: <sourcexml>SOURCEXML</sourcexml></p>
            <p>Target elements and attributes are highlighted like this: <targetxml>TARGETXML</targetxml></p>
            <p>Copy source attributes to target attributes unless otherwise specified.</p>
            <p>Every example is represented like "EXAMPLE" in all the dita's and is captured
                under <pre>pre</pre>  tag.</p>
        </section>
      <section>
          <title>Changes:</title>
          <p>2014-10-13: Created</p>
      </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\MX03-Statcode\MX03_Statcode-Introduction.dita  -->
	<xsl:message>MX03_Statcode-Introduction.xsl requires manual development!</xsl:message> 

	<xsl:template match="LEGDOC">

		<!--  Original Target XPath:  statcode:statcode   -->
		<statcode:statcode>
			<xsl:apply-templates select="@* | node()"/>
		</statcode:statcode>

	</xsl:template>

	<xsl:template match="docinfo:selector">

		<!--  Original Target XPath:  statcode:statcode   -->
		<statcode:statcode>
			<xsl:apply-templates select="@* | node()"/>
		</statcode:statcode>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:  statcode:head   -->
		<statcode:head>
			<xsl:apply-templates select="@* | node()"/>
		</statcode:head>

	</xsl:template>

	<xsl:template match="docinfo:doc-country/@iso-cc=&#34;US&#34;">

		<!--  Original Target XPath:  statcode:head   -->
		<statcode:head>
			<xsl:apply-templates select="@* | node()"/>
		</statcode:head>

	</xsl:template>

	<xsl:template match="docinfo:doc-country/@iso-cc=&#34;MX&#34;">

		<!--  Original Target XPath:  statcode:head   -->
		<statcode:head>
			<xsl:apply-templates select="@* | node()"/>
		</statcode:head>

	</xsl:template>

	<xsl:template match="SOURCEXML">

		<!--  Original Target XPath:  TARGETXML   -->
		<TARGETXML>
			<xsl:apply-templates select="@* | node()"/>
		</TARGETXML>

	</xsl:template>

</xsl:stylesheet>