<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="MY01_Rosetta_case.judgments-LxAdv_courtcase.opinions">
    <title>case:judgments <lnpid>id-MY01-16024</lnpid></title>
    <body>
        <section conref="../../common_caselaw/conref_content/Rosetta_case.judgments-LxAdv_courtcase.opinions.dita#Rosetta_case.judgments-LxAdv_courtcase.opinions/mapping"/>
        <section>
            <note>The child element <targetxml>attachments</targetxml> is used to house
                    <sourcexml>inlineobject</sourcexml> information in the opinions.</note>
        </section>
        <example>
            <codeblock>
&lt;case:judgments&gt;
    ...
    &lt;inlineobject filename="g0607831d.gif" attachment="ln-server" type="image"/&gt;
    ...
&lt;/case:judgments&gt;
       </codeblock>
            <b>becomes</b>
            <codeblock>
&lt;courtcase:opinions&gt;
    ...
    &lt;attchments&gt;
        &lt;appendix&gt;
            &lt;bodytext&gt;
                &lt;figure&gt;
                    &lt;ref:inlineobject&gt;
                        &lt;ref:locator&gt;
                            &lt;ref:locator-key&gt;
                                &lt;ref:key-name name="object-key"/&gt;
                                &lt;ref:key-value value="X-Y-g0607831d"/&gt;
                            &lt;/ref:locator-key&gt;
                            &lt;ref:locator-params&gt;
								&lt;proc:param name="componentseq" value="1"/&gt;
                                &lt;proc:param name="object-type" value="image"/&gt;
								&lt;proc:param name="object-smi" value=""/&gt;
                            &lt;/ref:locator-params&gt;
                        &lt;/ref:locator&gt;
                    &lt;/ref:inlineobject&gt;
                &lt;/figure&gt;
            &lt;/bodytext&gt;
        &lt;/appendix&gt;
    &lt;/attchments&gt;
    ...
&lt;/courtcase:opinions&gt;
       </codeblock>
        </example>
        <!--<section
            conref="../../common_caselaw/conref_content/Rosetta_case.judgments-LxAdv_courtcase.opinions.dita#Rosetta_case.judgments-LxAdv_courtcase.opinions/changes"/>-->
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY01_Cases\MY01_Rosetta_case.judgments-LxAdv_courtcase.opinions.dita  -->
<!--	<xsl:message>MY01_Rosetta_case.judgments-LxAdv_courtcase.opinions.xsl requires manual development!</xsl:message> -->

    <xsl:template match="case:judgments">
        <courtcase:opinions>
            <xsl:choose>
                <xsl:when test="./@subdoc">
                    <xsl:attribute name="includeintoc">
                        <xsl:value-of select="."/>
                    </xsl:attribute>
                </xsl:when>
                <xsl:when test="./@toc-caption">
                    <xsl:attribute name="alternatetoccaption">
                        <xsl:value-of select="."/>
                    </xsl:attribute>
                </xsl:when>
                <xsl:when test="./@searchtype"/>
            </xsl:choose>
            <xsl:apply-templates select="@* | node()"/>
        </courtcase:opinions>
    </xsl:template>
    
</xsl:stylesheet>