<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="MY01_Rosetta_case.appendix-LxAdv_attachments_appendix">
    <title>case:appendix <lnpid>id-MY01-16013</lnpid></title>
    <body>
        <section conref="../../common_caselaw/conref_content/Rosetta_case.appendix-LxAdv_attachments_appendix.dita#Rosetta_case.appendix-LxAdv_attachments_appendix/mapping"/>
        <example>
            <codeblock>
&lt;case:judgments&gt;
    ...
    &lt;case:appendix&gt;
        &lt;heading&gt;
            &lt;title&gt;THIS COURT DOTH DECLARE&lt;/title&gt;
        &lt;/heading&gt;
        &lt;l&gt;
            &lt;li&gt;
                &lt;lilabel&gt;
                    &lt;emph typestyle="ro"&gt;(1)&lt;/emph&gt;
                &lt;/lilabel&gt;
                &lt;p&gt;
                    &lt;text&gt;That the shares specified in paragraph 2 of the Statement of Claim herein
                        and hereinafter called the said miscellaneous shares &lt;emph typestyle="it"
                            &gt;viz.&lt;/emph&gt;&amp;#x2014;1000 Ayer Panas shares, 500 Ayer Molek shares, 200
                        Bukit Kajang shares, 100 Tebong shares, 145 Punggor shares were the private
                        property of S. V. S. Supramanian Chetty deceased at the time of his
                        death;&lt;/text&gt;
                &lt;/p&gt;
            &lt;/li&gt;
        &lt;/l&gt;
        ...
    &lt;/case:appendix&gt;
&lt;/case:judgments&gt;
           </codeblock>
            <b>becomes</b>
            <codeblock>
&lt;courtcase:opinions&gt;
    &lt;attachments&gt;
        &lt;appendix&gt;
            &lt;heading&gt;
                &lt;title&gt;THIS COURT DOTH DECLARE&lt;/title&gt;
            &lt;/heading&gt;
            &lt;bodytext&gt;
                &lt;list&gt;
                    &lt;listitem&gt;
                        &lt;label&gt;
                            &lt;emph typestyle="ro"&gt;&amp;#x0028;1&amp;#x0029;&lt;/emph&gt;
                        &lt;/label&gt;
                        &lt;bodytext&gt;
                            &lt;p&gt;
                                &lt;text&gt;That the shares specified in paragraph 2 of the Statement of
                                    Claim herein and hereinafter called the said miscellaneous
                                    shares &lt;emph typestyle="it"&gt;viz.&lt;/emph&gt;&amp;#x2014;1000 Ayer Panas
                                    shares, 500 Ayer Molek shares, 200 Bukit Kajang shares, 100
                                    Tebong shares, 145 Punggor shares were the private property of
                                    S. V. S. Supramanian Chetty deceased at the time of his
                                    death;&lt;/text&gt;
                            &lt;/p&gt;
                        &lt;/bodytext&gt;
                    &lt;/listitem&gt;
                &lt;/list&gt;
            &lt;/bodytext&gt;
            ...
        &lt;/appendix&gt;
    &lt;/attachments&gt;
&lt;/courtcase:opinions&gt;
           </codeblock>
        </example>
        
        <!--<section
            conref="../../common_caselaw/conref_content/Rosetta_case.appendix-LxAdv_attachments_appendix.dita#Rosetta_case.appendix-LxAdv_attachments_appendix/changes"/>-->
        </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY01_Cases\MY01_Rosetta_case.appendix-LxAdv_attachments_appendix.dita  -->
<!--	<xsl:message>MY01_Rosetta_case.appendix-LxAdv_attachments_appendix.xsl requires manual development!</xsl:message> -->


    <xsl:template match="case:appendix">
        <attachments>
            <appendix>
                <xsl:if test="child::heading">
                    <xsl:apply-templates select="heading"/>
                </xsl:if>
                <xsl:if test="node() except heading">
                    <bodytext>
                        <xsl:apply-templates select="@* | node() except heading"/>
                    </bodytext>
                </xsl:if>
            </appendix>
        </attachments>
    </xsl:template>
</xsl:stylesheet>