<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/"     xmlns:casesum="http://www.lexisnexis.com/xmlschemas/content/legal/case-summary/1/" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="MY01_Rosetta_case.headnote-LxAdv_courtcase.head">
    <title>case:headnote <lnpid>id-MY01-16021</lnpid></title>
    <body>
        <section conref="../../common_caselaw/conref_content/Rosetta_case.headnote-LxAdv_courtcase.head.dita#Rosetta_case.headnote-LxAdv_courtcase.head/mapping"/>
        <example>
            <codeblock>
&lt;case:headnote&gt;
    &lt;case:reportercite&gt;
        &lt;ci:cite type="cite4thisdoc"&gt;
            &lt;ci:case&gt;
                &lt;ci:caseinfo&gt;
                    &lt;ci:decisiondate year="1965"/&gt;
                &lt;/ci:caseinfo&gt;
                &lt;ci:caseref&gt;
                    &lt;ci:reporter value="BLR"/&gt;
                    &lt;ci:volume num="1"/&gt;
                    &lt;ci:edition&gt;
                        &lt;ci:date year="1965"/&gt;
                    &lt;/ci:edition&gt;
                    &lt;ci:page num="3"/&gt;
                &lt;/ci:caseref&gt;
            &lt;/ci:case&gt;
            &lt;ci:content&gt;
                &lt;citefragment searchtype="CASE-CITE-REF"&gt; [1965-1986] 1 BLR 3&lt;/citefragment&gt;
            &lt;/ci:content&gt;
        &lt;/ci:cite&gt;
    &lt;/case:reportercite&gt;
    ...
&lt;/case:headnote&gt;
       </codeblock>
            <b>becomes</b>
            <codeblock>
&lt;courtcase:head&gt;
    &lt;caseinfo:caseinfo&gt;
        &lt;ref:citations&gt;
            &lt;ref:cite4thisresource citetype="reporter"&gt;
                &lt;lnci:cite&gt;
                    &lt;lnci:case&gt;
                        &lt;lnci:caseinfo&gt;
                            &lt;lnci:decisiondate year="1965"/&gt;
                        &lt;/lnci:caseinfo&gt;
                        &lt;lnci:caseref&gt;
                            &lt;lnci:reporter value="BLR"/&gt;
                            &lt;lnci:volume num="1"/&gt;
                            &lt;lnci:page num="3"/&gt;
                        &lt;/lnci:caseref&gt;
                    &lt;/lnci:case&gt;
                    &lt;lnci:content&gt;
                        &amp;#x005B;1965-1986&amp;#x005D; 1 BLR 3&lt;/lnci:content&gt;
                &lt;/lnci:cite&gt;
            &lt;/ref:cite4thisresource&gt;
        &lt;/ref:citations&gt;
    &lt;/caseinfo:caseinfo&gt;
    ...
&lt;/courtcase:head&gt;
       </codeblock>
        </example>
        
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY01_Cases\MY01_Rosetta_case.headnote-LxAdv_courtcase.head.dita  -->
<!--	<xsl:message>MY01_Rosetta_case.headnote-LxAdv_courtcase.head.xsl requires manual development!</xsl:message> -->

<xsl:template match="case:headnote">
    <courtcase:head>
        <xsl:for-each-group select="*" group-adjacent="if(self::case:info or self::catchwordgrp or self::case:length) then 'caseinfo' else if(self::case:factsummary or self::case:decisionsummary) then 'summries' else 'none'">
 <xsl:choose>
     <xsl:when test="current-grouping-key()='caseinfo'">
         <caseinfo:caseinfo>
             <xsl:apply-templates select="current-group()[name()!='case:length']"/>
         </caseinfo:caseinfo>
     </xsl:when>
     <xsl:when test="current-grouping-key()='summries'">
         <casesum:summaries>
             <xsl:apply-templates select="current-group()"/>
         </casesum:summaries>
     </xsl:when>
     <xsl:when test="current-grouping-key()='none'">
         <xsl:apply-templates select="current-group()"/>
     </xsl:when>
       </xsl:choose>           
        </xsl:for-each-group>
    </courtcase:head>
</xsl:template>

</xsl:stylesheet>