<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"    xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.dates_pubdate">
  <title>pubdate <lnpid>id-MY05LL-17013</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:dates/pubdate</sourcexml>  comes with optional attribute <targetxml>@display-name</targetxml> then it becomes
          <targetxml>doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate</targetxml>.</p> 
      
    </section>
    <example>
      <title>Mapping of <sourcexml>pubdate[@display-name="Published date"]</sourcexml></title>
      <codeblock>

&lt;leg:info&gt;
  &lt;leg:dates&gt;
      &lt;pubdate display-name="Published date"&gt;
        &lt;date day="28" month="10" year="1976"&gt;28 October, 1976&lt;/date&gt;
      &lt;/pubdate&gt;
  &lt;/leg:dates&gt;
&lt;/leg:info&gt;

      </codeblock>
      <b>becomes</b>
      <codeblock>

&lt;doc:metadata&gt;
   &lt;pubinfo:pubinfo&gt;
      &lt;pubinfo:dates&gt;
        &lt;pubinfo:pubdate month="10" day="28" year="1976"&gt;
           &lt;date-text&gt;28 October, 1976&lt;/date-text&gt;
        &lt;/pubinfo:pubdate&gt;
      &lt;/pubinfo:dates&gt;
   &lt;/pubinfo:pubinfo&gt;
&lt;/doc:metadata&gt;

       </codeblock>
    </example>
    <note>Drop the attribute <sourcexml>@display-name</sourcexml> with value "<b>Published date</b>"
      in target conversion.</note>    
    <note>When <sourcexml>pubdate</sourcexml> has attribute <sourcexml>@ln.user-displayed="false"</sourcexml> (i.e. <sourcexml>pubdate[@ln.user-displayed="false"</sourcexml>]), that element is translated into the target but with the element
      content omitted. Only the attributes are populated. So there is no displayable content.</note>
    <example>
      <title>Mapping of <sourcexml>pubdate [@ln.user-displayed="false" and @display-name="Published
          date"]</sourcexml></title>
      <codeblock>

&lt;leg:info&gt;
  &lt;leg:dates&gt;
      &lt;pubdate ln.user-displayed="false" display-name="Published date"&gt;
          &lt;date day="27" month="02" year="1969"&gt;27 February, 1969&lt;/date&gt;
      &lt;/pubdate&gt;
  &lt;/leg:dates&gt;
&lt;/leg:info&gt;

      </codeblock>
      <b>becomes</b>
      <codeblock>

&lt;doc:metadata&gt;
   &lt;pubinfo:pubinfo&gt;
      &lt;pubinfo:dates&gt;
        &lt;pubinfo:pubdate month="02" day="27" year="1969"/&gt;
      &lt;/pubinfo:dates&gt;
   &lt;/pubinfo:pubinfo&gt;
&lt;/doc:metadata&gt;

       </codeblock>
    </example>
 <section>
       <title>Changes</title>
       <p>2013-11-14: <ph id="change_20131114_SS">Created</ph>.</p>
</section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY05LL_Acts\leg.dates_pubdate.dita  -->
<!--	<xsl:message>MY05LL_Acts_leg.dates_pubdate.xsl requires manual development!</xsl:message> -->

  <xsl:template match="leg:dates/pubdate">
    <pubinfo:pubinfo>
      <pubinfo:dates>
        <pubinfo:pubdate>
          <xsl:attribute name="month">
            <xsl:value-of select="./date/@month"/>
          </xsl:attribute>
          <xsl:attribute name="day">
            <xsl:value-of select="./date/@day"/>
          </xsl:attribute>
          <xsl:attribute name="year">
            <xsl:value-of select="./date/@year"/>
          </xsl:attribute>
          <xsl:choose>
            <xsl:when test="./@ln.user-displayed = 'false'"/>
            <xsl:when test="./@display-name = 'Published date'">
              <date-text>
                <xsl:value-of select="./date"/>
              </date-text>
            </xsl:when>
          </xsl:choose>
        </pubinfo:pubdate>
      </pubinfo:dates>
    </pubinfo:pubinfo>
  </xsl:template>
  
</xsl:stylesheet>