<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_legfragment-to-LexisAdvance_primlaw.excerpt">    
    <title><sourcexml>legfragment</sourcexml> to <targetxml>primlaw:excerpt</targetxml> <lnpid>id-MY06-17228</lnpid></title>
    <body>
        <section>
            <p><sourcexml>legfragment</sourcexml> becomes <targetxml>primlaw:excerpt</targetxml>.</p>
                
                <codeblock>

&lt;legfragment&gt;
    &lt;leg:level id="USM.ALN0101y1960e.S1"&gt;
        &lt;leg:level-vrnt toc-caption="1. Citation and commencement" subdoc="true"
            searchtype="LEGISLATION SECT" leveltype="sect"&gt;
            &lt;leg:heading inline="true"&gt;
                &lt;desig inline="true" searchtype="SECT-NUM"&gt;
                    &lt;designum&gt;1.&lt;/designum&gt;
                &lt;/desig&gt;
                &lt;title inline="true" searchtype="SECT-TITLE"&gt;&lt;refpt type="ext"
                    id="USM.ALN0101y1960e.S1"/&gt;Citation and
                    commencement&lt;/title&gt;
            &lt;/leg:heading&gt;
            &lt;leg:levelbody&gt;
                &lt;leg:bodytext&gt;
                    &lt;p&gt;
                        &lt;text&gt;These regulations may be cited as the Territorial
                            Army &amp;#x0028;Term of Service&amp;#x0029;
                            &amp;#x0028;Amendment&amp;#x0029; Regulations, 1960, and
                            shall be deemed to have come into force on the 1st
                            day of January, 1960.&lt;/text&gt;
                    &lt;/p&gt;
                &lt;/leg:bodytext&gt;
            &lt;/leg:levelbody&gt;
        &lt;/leg:level-vrnt&gt;
    &lt;/leg:level&gt;
    ..........
    ..........
&lt;/legfragment&gt;

 </codeblock>
                <b>Becomes</b>
                
                <codeblock>

&lt;primlaw:excerpt&gt;
    &lt;primlaw:level leveltype="section" includeintoc="true"
        alternatetoccaption="1. Citation and commencement"&gt;
        &lt;ref:anchor id="USM.ALN0101y1960e.S1" anchortype="global"/&gt;
        &lt;heading inline="true"&gt;
            &lt;desig inline="true"&gt; 1. &lt;/desig&gt;
            &lt;title inline="true"&gt;Citation and commencement&lt;/title&gt;
        &lt;/heading&gt;
        &lt;primlaw:bodytext&gt;
            &lt;p&gt;
                &lt;text&gt;These regulations may be cited as the Territorial Army
                    &amp;#x0028;Term of Service&amp;#x0029; &amp;#x0028;Amendment&amp;#x0029;
                    Regulations, 1960, and shall be deemed to have come into force
                    on the 1st day of January, 1960.&lt;/text&gt;
            &lt;/p&gt;
        &lt;/primlaw:bodytext&gt;
    &lt;/primlaw:level&gt;
    ..........
    ..........
&lt;/primlaw:excerpt&gt;
    
      </codeblock>

        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY06_Regulations\legfragment.dita  -->
<!--	<xsl:message>MY06_Regulations_legfragment.xsl requires manual development!</xsl:message> -->

	<xsl:template match="legfragment">
		<primlaw:excerpt>
			<xsl:apply-templates select="@* | node()"/>
		</primlaw:excerpt>
	</xsl:template>

</xsl:stylesheet>