<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="MY07_Rosetta_pubdate_to-LexAdv-pubinfo.pubdate">
  <title>pubdate <lnpid>id-MY07-17427</lnpid></title>
 <body>
   <section>
      <p>
        <sourcexml>leg:info/pubdate</sourcexml> becomes
          <targetxml>doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate[@month, day,
          year]</targetxml> and children are described as below: <note>When
            <sourcexml>ln.user-displayed="false"</sourcexml> appears on any date element (i.e.
            <sourcexml>pubdate[@ln.user-displayed="false"]</sourcexml>), that element is translated
          into the target but with the element content omitted. Only the attributes are populated.
          So there is no displayable content.</note>
        <note>If input having <sourcexml>pubdate</sourcexml> without
            <sourcexml>@ln.user-displayed</sourcexml> attribute then its mapped with
            <targetxml>doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate[@month, day,
            year]</targetxml> and content should be captured in <targetxml>date-text</targetxml>
          markup with added text "<b>Published date: </b>"..</note>
        <ul>
          <li><sourcexml>date</sourcexml> Becomes <targetxml>date-text</targetxml> and the
            attributes will be moved in the parent <targetxml>pubinfo:pubdate</targetxml> element
            and populated as below: <ul>
              <li><sourcexml>date/@day</sourcexml> becomes
                  <targetxml>pubinfo:pubdate/@day</targetxml></li>
              <li><sourcexml>date/@month</sourcexml> becomes
                  <targetxml>pubinfo:pubdate/@month</targetxml></li>
              <li><sourcexml>date/@year</sourcexml> becomes
                  <targetxml>pubinfo:pubdate/@year</targetxml></li>
            </ul></li>
        </ul></p>
      <p>Mapping of <sourcexml>pubdate</sourcexml> with attribute
          <sourcexml>@ln.user-displayed</sourcexml></p>
      <pre>
       
       &lt;pubdate ln.user-displayed="false" display-name="Published date"&gt;
            &lt;date day="12" month="09" year="2012"&gt;12 September 2012&lt;/date&gt;
       &lt;/pubdate&gt;
       
     </pre> Becomes <pre>
     
&lt;doc:metadata&gt;
  &lt;pubinfo:pubinfo&gt;
      &lt;pubinfo:dates&gt;
          &lt;pubinfo:pubdate day="12" month="09" year="2012/&gt;
      &lt;/pubinfo:dates&gt;
  &lt;/pubinfo:pubinfo&gt;
    &lt;doc:docinfo&gt;
        &lt;!-- ... --&gt;
    &lt;/doc:docinfo&gt;
 &lt;/doc:metadata&gt;
     
     </pre>
      <p>Mapping of <sourcexml>pubdate</sourcexml> without <sourcexml>@ln.user-displayed</sourcexml>
        attribute</p>
      <pre>
  
&lt;leg:info&gt;
  &lt;pubdate display-name="Published date"&gt;
    &lt;date day="27" month="03" year="1969"&gt;27 March,1969&lt;/date&gt;
  &lt;/pubdate&gt;
&lt;/leg:info&gt;

</pre>
      <b>become</b>
      <pre>
  
  &lt;doc:metadata&gt;
   &lt;pubinfo:pubinfo&gt;
     &lt;pubinfo:dates&gt;
        &lt;pubinfo:pubdate month="03" day="27" year="1969"&gt;
          &lt;date-text&gt;Published date: 27 March,1969&lt;/date-text&gt;
      &lt;/pubinfo:dates&gt;
   &lt;/pubinfo:pubinfo&gt;
    &lt;doc:docinfo&gt;
        &lt;!-- ... --&gt;
    &lt;/doc:docinfo&gt;

&lt;/doc:metadata&gt;
  
</pre>
    </section>
   <section>
     <title>Changes</title>
     <p>2013-11-14: <ph id="change_20131114_SSX">Created</ph>.</p>
   </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY07_CourtRule\MY07_Rosetta_pubdate_to-LexAdv-pubinfo.pubdate.dita  -->
	<xsl:message>MY07_Rosetta_pubdate_to-LexAdv-pubinfo.pubdate.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:info/pubdate">

		<!--  Original Target XPath:  doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate[@month,day,year]   -->
		<doc:metadata>
			<pubinfo:pubinfo>
				<pubinfo:dates>
					<pubinfo:pubdate>
						<xsl:apply-templates select="@* | node()"/>
					</pubinfo:pubdate>
				</pubinfo:dates>
			</pubinfo:pubinfo>
		</doc:metadata>

	</xsl:template>

	<xsl:template match="ln.user-displayed=&#34;false&#34;">

		<!--  Original Target XPath:  doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate[@month,day,year]   -->
		<doc:metadata>
			<pubinfo:pubinfo>
				<pubinfo:dates>
					<pubinfo:pubdate>
						<xsl:apply-templates select="@* | node()"/>
					</pubinfo:pubdate>
				</pubinfo:dates>
			</pubinfo:pubinfo>
		</doc:metadata>

	</xsl:template>

	<xsl:template match="pubdate[@ln.user-displayed=&#34;false&#34;]">

		<!--  Original Target XPath:  doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate[@month,day,year]   -->
		<doc:metadata>
			<pubinfo:pubinfo>
				<pubinfo:dates>
					<pubinfo:pubdate>
						<xsl:apply-templates select="@* | node()"/>
					</pubinfo:pubdate>
				</pubinfo:dates>
			</pubinfo:pubinfo>
		</doc:metadata>

	</xsl:template>

	<xsl:template match="pubdate">

		<!--  Original Target XPath:  doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate[@month,day,year]   -->
		<doc:metadata>
			<pubinfo:pubinfo>
				<pubinfo:dates>
					<pubinfo:pubdate>
						<xsl:apply-templates select="@* | node()"/>
					</pubinfo:pubdate>
				</pubinfo:dates>
			</pubinfo:pubinfo>
		</doc:metadata>

	</xsl:template>

	<xsl:template match="@ln.user-displayed">

		<!--  Original Target XPath:  doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate[@month,day,year]   -->
		<doc:metadata>
			<pubinfo:pubinfo>
				<pubinfo:dates>
					<pubinfo:pubdate>
						<xsl:apply-templates select="@* | node()"/>
					</pubinfo:pubdate>
				</pubinfo:dates>
			</pubinfo:pubinfo>
		</doc:metadata>

	</xsl:template>

	<xsl:template match="date">

		<!--  Original Target XPath:  date-text   -->
		<date-text>
			<xsl:apply-templates select="@* | node()"/>
		</date-text>

	</xsl:template>

	<xsl:template match="date/@day">

		<!--  Original Target XPath:  pubinfo:pubdate/@day   -->
		<pubinfo:pubdate>
			<xsl:attribute name="day">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</pubinfo:pubdate>

	</xsl:template>

	<xsl:template match="date/@month">

		<!--  Original Target XPath:  pubinfo:pubdate/@month   -->
		<pubinfo:pubdate>
			<xsl:attribute name="month">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</pubinfo:pubdate>

	</xsl:template>

	<xsl:template match="date/@year">

		<!--  Original Target XPath:  pubinfo:pubdate/@year   -->
		<pubinfo:pubdate>
			<xsl:attribute name="year">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</pubinfo:pubdate>

	</xsl:template>

</xsl:stylesheet>