<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="usm_landingpgs-introduction">
  <title>Introduction <lnpid>id-MY08-17610</lnpid></title>
  <body>
    <section><title>These Conversion Instructions describe the conversion of Malaysia (MY) MultiTOC source
        documents containing Rosetta LEGDOC standard DTD mark-up to target documents containing New
        Lexis Navigation Aid And Landing Page Schema (navaid) mark-up.</title>
      <p>The MY MultiTOC source documents contain tables of contents, indexes, and other lists of
        links to the Unannotated Statutes of Malaysia.</p>
    </section>
    <section>
      <title>Notes</title>
      <ol>
      <li>Source elements and attributes are highlighted like this:
        <sourcexml>sourcexml</sourcexml></li>
      <li>Target elements and attributes are highlighted like this:
        <targetxml>targetxml</targetxml></li>
        <li>Verify content of the following target attributes: <ul>
        <li><sourcexml>@month</sourcexml> becomes <targetxml>@month</targetxml> and is between
          01-12. If the value is outside this range, do not output
          <targetxml>@month</targetxml>.</li>
        <li><sourcexml>@day</sourcexml> becomes <targetxml>@day</targetxml> and is between 01-31.
          If the value is outside this range, do not output <targetxml>@day</targetxml>.</li>
        <li><sourcexml>@year</sourcexml> becomes <targetxml>@year</targetxml> and is 4 digits in
          length. If the value is any other length, do not output
          <targetxml>@year</targetxml>.</li>
      </ul>
        <note>If a source <sourcexml>@day</sourcexml> or <sourcexml>@month</sourcexml> attribute
          value is only one digit, it should be output with a leading 0 to make it two
          digits.</note>
        </li>
        <li>Copy source attributes to target attributes unless otherwise specified.</li>
        <li>Whenever the terms "whitespace" or "white-space" are used, they refer to consecutive sequences of any number of spaces, tabs, newlines, and all character entities that represent spacing such as <sourcexml>&amp;nbsp;</sourcexml>, <sourcexml>&amp;ensp;</sourcexml>, <sourcexml>&amp;emsp;</sourcexml>.
        </li>
      </ol>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY08_navaid\Introduction.dita  -->
	<xsl:message>MY08_navaid_Introduction.xsl requires manual development!</xsl:message> 

	<xsl:template match="sourcexml">

		<!--  Original Target XPath:  targetxml   -->
		<targetxml>
			<xsl:apply-templates select="@* | node()"/>
		</targetxml>

	</xsl:template>

	<xsl:template match="@month">

		<!--  Original Target XPath:  @month   -->
		<xsl:attribute name="month">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="@day">

		<!--  Original Target XPath:  @day   -->
		<xsl:attribute name="day">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="@year">

		<!--  Original Target XPath:  @year   -->
		<xsl:attribute name="year">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="&amp;nbsp;">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="&amp;ensp;">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="&amp;emsp;">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>