<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="navaid-combined-table3-source">
            <title>Source XML</title>
            <body>
<codeblock>

&lt;!-- ... --&gt;
&lt;docinfo&gt;
    &lt;docinfo:doc-heading&gt;NEW SOUTH WALES LEGISLATION&lt;/docinfo:doc-heading&gt;
    &lt;docinfo:doc-id&gt;LAWNOW_LEG_DEFTERM_ACTS_D_DW_NSW&lt;/docinfo:doc-id&gt;
&lt;!-- ... --&gt;
    &lt;docinfo:hierlev role="me"&gt;
      &lt;heading&gt;
        &lt;title&gt;DW&lt;/title&gt;
      &lt;/heading&gt;
    &lt;/docinfo:hierlev&gt;
&lt;!-- ... --&gt;
  &lt;in:body&gt;
    &lt;heading&gt;
      &lt;title&gt;LawNow Legislation New South Wales&lt;/title&gt;
    &lt;/heading&gt;
    &lt;table colsep="0" frame="none" pgwide="1" rowsep="0"&gt;
&lt;!-- ... --&gt;
    &lt;/table&gt;
&lt;!-- ... --&gt;
    &lt;table colsep="0" frame="none" pgwide="1" rowsep="0"&gt;
&lt;!-- ... --&gt;
    &lt;/table&gt;
    &lt;!-- ALPHA STRIP TABLE START  --&gt;
    &lt;table colsep="0" frame="none" pgwide="1" rowsep="0"&gt;
      &lt;tgroup cols="1" colsep="0" rowsep="0"&gt;
        &lt;colspec colname="C1" colnum="1"/&gt;
        &lt;tbody&gt;
          &lt;row&gt;
            &lt;entry align="center"&gt;
              &lt;emph typestyle="bf"&gt;
                &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_NSW" service="DOC-ID"
                  &gt;D&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_DA_NSW" service="DOC-ID"
                  &gt;DA&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_DC_NSW" service="DOC-ID"
                  &gt;DC&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_DE_NSW" service="DOC-ID"
                  &gt;DE&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_DI_NSW" service="DOC-ID"
                  &gt;DI&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_DN_NSW" service="DOC-ID"
                  &gt;DN&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_DO_NSW" service="DOC-ID"
                  &gt;DO&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_DP_NSW" service="DOC-ID"
                  &gt;DP&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_DR_NSW" service="DOC-ID"
                  &gt;DR&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_DT_NSW" service="DOC-ID"
                  &gt;DT&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_DU_NSW" service="DOC-ID"
                  &gt;DU&lt;/remotelink&gt;&lt;emph typestyle="bf"&gt;   DW   &lt;/emph&gt;&lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
                  remotekey2="LAWNOW_LEG_DEFTERM_ACTS_D_DY_NSW" service="DOC-ID"&gt;DY&lt;/remotelink&gt;   
              &lt;/emph&gt;
            &lt;/entry&gt;
          &lt;/row&gt;
        &lt;/tbody&gt;
      &lt;/tgroup&gt;
    &lt;/table&gt;
    &lt;!-- ALPHA STRIP TABLE END --&gt;
            
</codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU16_navaid\navaid-combined-table3-source.dita  -->
	<!--<xsl:message>navaid-combined-table3-source.xsl requires manual development!</xsl:message> -->

</xsl:stylesheet>