<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="navaid-separate-l-target">
          <title>Target XML</title>
          <body>
<codeblock>

&lt;index:index indextype="topical"&gt;
  &lt;index:item&gt;
    &lt;index:entry&gt;
      &lt;index:locator&gt;&lt;ref:lnlink service="DOCUMENT"&gt;
        &lt;ref:marker&gt;DAIRY INDUSTRY ACT 1979 NO 208 &lt;emph typestyle="bf"
          &gt;(Repealed)&lt;/emph&gt;&lt;/ref:marker&gt;
        &lt;ref:locator anchoridref="NSW_ACT_1979-208"&gt;
          &lt;ref:locator-key&gt;
            &lt;ref:key-name name="DOC-ID"/&gt;
            &lt;ref:key-value value="005Y-EXAMPLE_DOCID1"/&gt;
          &lt;/ref:locator-key&gt;
        &lt;/ref:locator&gt;
      &lt;/ref:lnlink&gt;&lt;/index:locator&gt;
    &lt;/index:entry&gt;
  &lt;/index:item&gt;
  &lt;index:item&gt;
    &lt;index:entry&gt;
      &lt;index:locator&gt;&lt;ref:lnlink service="DOCUMENT"&gt;
        &lt;ref:marker&gt;DAIRY INDUSTRY ACT 2000 NO 54&lt;/ref:marker&gt;
        &lt;ref:locator anchoridref="NSW_ACT_2000-54"&gt;
          &lt;ref:locator-key&gt;
            &lt;ref:key-name name="DOC-ID"/&gt;
            &lt;ref:key-value value="005Y-EXAMPLE_DOCID2"/&gt;
          &lt;/ref:locator-key&gt;
        &lt;/ref:locator&gt;
      &lt;/ref:lnlink&gt;&lt;/index:locator&gt;
    &lt;/index:entry&gt;
  &lt;/index:item&gt;
  &lt;index:item&gt;
    &lt;index:entry&gt;
      &lt;index:locator&gt;&lt;ref:lnlink service="DOCUMENT"&gt;
        &lt;ref:marker&gt;DAIRY INDUSTRY AMENDMENT (TRADE PRACTICES EXEMPTION) ACT 1998 NO 28 &lt;emph
            typestyle="bf"&gt;(Repealed)&lt;/emph&gt;&lt;/ref:marker&gt;
        &lt;ref:locator anchoridref="NSW_ACT_1998-28"&gt;
          &lt;ref:locator-key&gt;
            &lt;ref:key-name name="DOC-ID"/&gt;
            &lt;ref:key-value value="005Y-EXAMPLE_DOCID3"/&gt;
          &lt;/ref:locator-key&gt;
        &lt;/ref:locator&gt;
      &lt;/ref:lnlink&gt;&lt;/index:locator&gt;
    &lt;/index:entry&gt;
  &lt;/index:item&gt;
&lt;!-- etc. --&gt;
  &lt;index:item&gt;
    &lt;index:entry&gt;
      &lt;index:locator&gt;&lt;ref:lnlink service="DOCUMENT"&gt;
        &lt;ref:marker&gt;DUTIES AMENDMENT (SENIOR'S PRINCIPAL PLACE OF RESIDENCE DUTY EXEMPTION) ACT
          2011 NO 6 &lt;emph typestyle="bf"&gt;(Repealed)&lt;/emph&gt;&lt;/ref:marker&gt;
        &lt;ref:locator anchoridref="NSW_ACT_2011-6"&gt;
          &lt;ref:locator-key&gt;
            &lt;ref:key-name name="DOC-ID"/&gt;
            &lt;ref:key-value value="005Y-EXAMPLE_DOCID4"/&gt;
          &lt;/ref:locator-key&gt;
        &lt;/ref:locator&gt;
      &lt;/ref:lnlink&gt;&lt;/index:locator&gt;
    &lt;/index:entry&gt;
  &lt;/index:item&gt;
&lt;/index:index&gt;
            
</codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU16_navaid\navaid-separate-l-target.dita  -->
	<!--<xsl:message>navaid-separate-l-target.xsl requires manual development!</xsl:message> -->

</xsl:stylesheet>