<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="navaid-combined-table1-source">
	<title>Source XML</title>
	<body>
		<p>In the example below, note the fact that the text "2008" is outside of any
				<sourcexml>remotelink</sourcexml>. </p>
<codeblock>

&lt;!-- ... --&gt;
 &lt;docinfo&gt;
    &lt;docinfo:doc-heading&gt;NEW SOUTH WALES LEGISLATION&lt;/docinfo:doc-heading&gt;
    &lt;docinfo:doc-id&gt;LAWNOW_LEG_YEARTITLE_BILLS_2008_NSW&lt;/docinfo:doc-id&gt;
&lt;!-- ... --&gt;
&lt;table colsep="0" frame="none" pgwide="1" rowsep="0"&gt;
  &lt;tgroup cols="1" colsep="0" rowsep="0"&gt;
    &lt;colspec colname="C1" colnum="1"/&gt;
    &lt;tbody&gt;
    &lt;row&gt;
      &lt;entry align="center"&gt;
        &lt;emph typestyle="bf"&gt;
          &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_NSW" service="DOC-ID"
            &gt;2011&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_2010_NSW" service="DOC-ID"
            &gt;2010&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_2009_NSW" service="DOC-ID"
            &gt;2009&lt;/remotelink&gt;   &lt;emph typestyle="ib"&gt;2008&lt;/emph&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_2007_NSW" service="DOC-ID"
            &gt;2007&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_2006_NSW" service="DOC-ID"
            &gt;2006&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_2005_NSW" service="DOC-ID"
            &gt;2005&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_2004_NSW" service="DOC-ID"
            &gt;2004&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_2003_NSW" service="DOC-ID"
            &gt;2003&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_2002_NSW" service="DOC-ID"
            &gt;2002&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_2001_NSW" service="DOC-ID"
            &gt;2001&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_2000_NSW" service="DOC-ID"
            &gt;2000&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_1999_NSW" service="DOC-ID"
            &gt;1999&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_1998_NSW" service="DOC-ID"
            &gt;1998&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_1997_NSW" service="DOC-ID"
            &gt;1997&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_1996_NSW" service="DOC-ID"
            &gt;1996&lt;/remotelink&gt;   &lt;remotelink dpsi="03AT" remotekey1="DOC-ID"
            remotekey2="LAWNOW_LEG_YEARTITLE_BILLS_1995_NSW" service="DOC-ID"
            &gt;1995&lt;/remotelink&gt;
        &lt;/emph&gt;
      &lt;/entry&gt;
    &lt;/row&gt;
    &lt;/tbody&gt;
  &lt;/tgroup&gt;
&lt;/table&gt;
            
		</codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU16_navaid\navaid-combined-table1-source.dita  -->
	<!--<xsl:message>navaid-combined-table1-source.xsl requires manual development!</xsl:message>--> 



</xsl:stylesheet>