<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="navaid-white-space-ps">
    <title>Paragraphs Are Preserved <lnpid>id-AU16-21029</lnpid></title>
    <body>
      <p>Unlike tables, empty paragraphs and those containing only white-space are usually preserved. If a
          <sourcexml>p</sourcexml> contains no character content, or the only character content of
        an entire <sourcexml>p</sourcexml> is white-space, the entire <sourcexml>p</sourcexml> is
        still converted according to the <xref href="../../common_newest/Rosetta_p-LxAdv-p.dita">common p
          element</xref>. Note that a <targetxml>bodytext</targetxml> element must be opened if one
        is not already opened, as described in <xref href="navaid-use-bodytext.dita">Use
            <targetxml>bodytext</targetxml> To Contain Other Elements</xref>
      </p>
      <note>There is one exception to the above rule: when one or more such <sourcexml>p</sourcexml> elements
        are output to the target document and form the <b>only</b> elements within an entire <b>target</b>
        <targetxml>bodytext</targetxml> element, the entire <targetxml>bodytext</targetxml> element and its contents 
        is not output but is instead dropped.</note>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU16_navaid\navaid-white-space-ps.dita  -->
	<!--<xsl:message>navaid-white-space-ps.xsl requires manual development!</xsl:message> -->
  
  <!-- MDS 2017-06-02 - AU16 This is actually not happening in the DT.  Empty paragraphs or paragrahs with only 'Â ' text() are being suppressed. -->


</xsl:stylesheet>