<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:navaid="urn:x-lexisnexis:content:navigationaid:sharedservices:1" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="navaid-separate-p">
      <title>Convert a series of <sourcexml>p</sourcexml> elements to
          <targetxml>navaid:list</targetxml> <lnpid>id-AU16-21026</lnpid></title>
      <body>
        <p>If a series of three or more sibling <sourcexml>bodytext/p</sourcexml> elements are found
          where each <sourcexml>p</sourcexml> contains only a single child
            <sourcexml>text</sourcexml> element that starts with a
          <sourcexml>remotelink</sourcexml>, the entire series of <sourcexml>p</sourcexml> elements
          is converted to a <targetxml>navaid:list</targetxml> as follows: <ul>
            <li>A <targetxml>landingpagebody/navaid:list</targetxml> is created.</li>
            <li>Within the created <sourcexml>navaid:list</sourcexml> each <sourcexml>p</sourcexml>
              becomes a <targetxml>navaid:list/index:entry</targetxml> as described in the subtopic
                <xref href="navaid-separate-details.dita">Convert One <sourcexml>p</sourcexml> Or
                  <sourcexml>entry</sourcexml> To
                <targetxml>navaid:list/index:entry</targetxml></xref> below.</li>
          </ul>
          <note>There will quite often be far more than three <sourcexml>p</sourcexml> elements in
            the series. <b>All</b> of the <sourcexml>p</sourcexml> elements that match the above
            criteria should be converted to <targetxml>navaid:list/index:entry</targetxml> elements
            within the <b>same</b>
            <targetxml>navaid:list</targetxml>.</note>
        </p>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU16_navaid\navaid-separate-p.dita  -->
	 
	
	

	<!--<xsl:template match="p[text[not(following-sibling::*)]]">

		<!-\-  Original Target XPath:  navaid:list   -\->
		<navaid:list>
			<xsl:apply-templates select="@* | node()"/>
		</navaid:list>

	</xsl:template>

	<xsl:template match="bodytext/p">

		<!-\-  Original Target XPath:  navaid:list   -\->
		<navaid:list>
			<xsl:apply-templates select="@* | node()"/>
		</navaid:list>

	</xsl:template>

	<xsl:template match="text">

		<!-\-  Original Target XPath:  navaid:list   -\->
		<navaid:list>
			<xsl:apply-templates select="@* | node()"/>
		</navaid:list>

	</xsl:template>

	<xsl:template match="remotelink">

		<!-\-  Original Target XPath:  navaid:list   -\->
		<navaid:list>
			<xsl:apply-templates select="@* | node()"/>
		</navaid:list>

	</xsl:template>

	<xsl:template match="navaid:list">

		<!-\-  Original Target XPath:  navaid:list   -\->
		<navaid:list>
			<xsl:apply-templates select="@* | node()"/>
		</navaid:list>

	</xsl:template>

	<xsl:template match="entry">

		<!-\-  Original Target XPath:  navaid:list/index:entry   -\->
		<navaid:list>
			<index:entry xmlns:index="urn:x-lexisnexis:content:publicationindex:sharedservices:1">
				<xsl:apply-templates select="@* | node()"/>
			</index:entry>
		</navaid:list>

	</xsl:template>-->

</xsl:stylesheet>