<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:casesum="http://www.lexisnexis.com/xmlschemas/content/legal/case-summary/1/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="NZ03_Rosetta_case.headnote-LxAdv_courtcase.head">
    <title>case:headnote <lnpid>id-NZ03-23021</lnpid></title>
    <body>
        <section conref="../../common_caselaw/conref_content/Rosetta_case.headnote-LxAdv_courtcase.head.dita#Rosetta_case.headnote-LxAdv_courtcase.head/mapping"/>
        <example>
            <codeblock>
&lt;case:headnote&gt;
    ...
    &lt;glp:note&gt;
        &lt;p&gt;
            &lt;text&gt;[&lt;emph typestyle="bf"&gt;Note. &lt;/emph&gt; As to the distinction between exemplary and aggravated damages, see &lt;emph typestyle="it"&gt;Luntz on Assessment of Damages &lt;/emph&gt; (2nd ed) para 1.7.01 &lt;emph typestyle="it"&gt;et seq &lt;/emph&gt; and 12 &lt;emph typestyle="it"&gt;Halsbury's Laws of England &lt;/emph&gt; (4th ed) para 1189.] &lt;/text&gt;
        &lt;/p&gt;
    &lt;/glp:note&gt;
&lt;/case:headnote&gt;
       </codeblock>
            <b>becomes</b>
            <codeblock>
&lt;courtcase:head&gt;
    ...
    &lt;note&gt;
        &lt;bodytext&gt;
            &lt;p&gt;
                &lt;text&gt;[&lt;emph typestyle="bf"&gt;Note. &lt;/emph&gt; As to the distinction between exemplary and aggravated damages, see &lt;emph typestyle="it"&gt;Luntz on Assessment of Damages &lt;/emph&gt; (2nd ed) para 1.7.01 &lt;emph typestyle="it"&gt;et seq &lt;/emph&gt; and 12 &lt;emph typestyle="it"&gt;Halsbury's Laws of England &lt;/emph&gt; (4th ed) para 1189.] &lt;/text&gt;
            &lt;/p&gt;
        &lt;/bodytext&gt;
    &lt;/note&gt;
&lt;/courtcase:head&gt;
       </codeblock>
        </example>
        <note>If <sourcexml>heading</sourcexml> occurs as a direct child of <sourcexml>case:headnote</sourcexml>, then conversion
            should create <targetxml>heading</targetxml> as direct child of <targetxml>caseinfo:caseinfo</targetxml>, i.e.
            <sourcexml>case:headnote/heading</sourcexml> becomes
            <targetxml>courtcase:head/caseinfo:caseinfo/heading</targetxml>.</note>
        <!--<section
            conref="../../common_caselaw/conref_content/Rosetta_case.headnote-LxAdv_courtcase.head.dita#Rosetta_case.headnote-LxAdv_courtcase.head/changes"/>-->
        <!--<section>
            <title>Changes Specific to NZ03</title>
            </section>-->

    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ03_CaseLaw\NZ03_Rosetta_case.headnote-LxAdv_courtcase.head.dita  -->
	<!--<xsl:message>NZ03_Rosetta_case.headnote-LxAdv_courtcase.head.xsl requires manual development!</xsl:message>--> 

    <xsl:template match="case:headnote">
       <!--  Original Target XPath:  ref:page   -->
        <courtcase:head>
        <xsl:apply-templates select="case:info/case:reportercite[@searchtype='BCNUM']" mode="search"/>
        <xsl:apply-templates select="case:info"/>
        <!--<xsl:apply-templates select="case:body/case:headnote/catchwordgrp"/>-->			 
        <xsl:if test="case:factsummary | case:body/case:headnote/case:decisionsummary | case:body/case:headnote/case:references">
            <casesum:summaries>
                <xsl:apply-templates select="case:factsummary | case:decisionsummary | case:disposition" mode="summaries"/>
                <!--<xsl:apply-templates select="case:decisionsummary" mode="summaries"/>
                <xsl:apply-templates select="case:disposition" mode="summaries"/>-->
                <!--<xsl:apply-templates select="case:body/case:content/case:typeofcase" mode="summaries-->
            </casesum:summaries>
            <xsl:apply-templates select="case:references"/>
        </xsl:if>
        </courtcase:head>
    </xsl:template>
</xsl:stylesheet>