<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"
  xmlns:newsitem="http://www.lexisnexis.com/xmlschemas/content/news/newsitem/1/" xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"
  xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl"
  version="2.0" exclude-result-prefixes="dita">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journal-Newsletter-Bulletins_Introduction">
    <title>Introduction <lnpid>id-NZ08-24011</lnpid></title>

    <body>
      <p>This Conversion Instruction describes the conversion of <b>NewsItem 4.4 PROD</b> Schema in the document.</p>

      <p>Identification Criteria for <b>NZ08-JOURNALS/BULLETINS/NEWSLETTERS</b> content stream is <sourcexml>JOURNALDOC</sourcexml>.</p>

      <p><sourcexml>JOURNALDOC</sourcexml> becomes <targetxml>newsitem:newsitem</targetxml>. It's a root element for <b>JOURNALS/BULLETINS/NEWSLETTERS</b>. The source attributes are: <sourcexml>@id</sourcexml> becomes
          <targetxml>@xml:id</targetxml>, <sourcexml>@xml:lang</sourcexml>, if present, suppress attribute and content, as a separate rule has been defined to populate
        <targetxml>newsitem:newsitem/@xml:lang</targetxml>.</p>

      <pre>

&lt;JOURNALDOC&gt;
        ...
        &lt;docinfo:doc-lang lang="en"/&gt;
        &lt;docinfo:doc-country iso-cc="NZ"/&gt;
        ...
&lt;/JOURNALDOC&gt;

<b>Becomes</b>

&lt;newsitem:newsitem xml:lang="en-NZ"&gt;
      
      &lt;newsitem:head&gt;...&lt;/newsitem:head&gt;
      
      &lt;nitf:body&gt;...&lt;/nitf:body&gt;
      
      &lt;doc:metadata&gt;...&lt;/doc:metadata&gt;

&lt;/newsitem:newsitem&gt;
</pre>

      <p><targetxml>newsitem:head</targetxml>, <targetxml>nitf:body</targetxml>, and <targetxml>doc:metadata</targetxml> are created as required children of <targetxml>newsitem:newsitem</targetxml></p>
      <note>The <sourcexml>@searchtype</sourcexml> attribute will be suppressed from conversion except for the citation elements.</note>
      <section>
        <title>Note:</title>
        <p>Source elements and attributes are highlighted like this: <sourcexml>SOURCEXML</sourcexml></p>
        <p>Target elements and attributes are highlighted like this: <targetxml>TARGETXML</targetxml></p>
        <p>Copy source attributes to target attributes unless otherwise specified.</p>
      </section>
    </body>

  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ08_NewsLetter_and_Journals\Journal-Newsletter-Bulletins_Introduction.dita  -->
  <!-- <xsl:message>NZ08_NewsLetter_and_Journals_Journal-Newsletter-Bulletins_Introduction.xsl requires manual development!</xsl:message> -->

  <xsl:template match="JOURNALDOC">
    <newsitem:newsitem>
      <xsl:call-template name="generateNSGlobalBindings"/>
      <xsl:attribute name="xsi:schemaLocation" select="$outputSchemaLoc"/>
      <xsl:if test="docinfo/docinfo:doc-lang">
        <xsl:call-template name="xml_lang"/>
      </xsl:if>

      <newsitem:head>
        <xsl:apply-templates select="jrnl:body/jrnl:info/jrnl:journalcite"/>
      </newsitem:head>
      
      <nitf:body>
        <xsl:apply-templates select="jrnl:body"/>
        <xsl:apply-templates select="jrnl:body/jrnl:bodytext"/>
      </nitf:body>

      <doc:metadata>
        <xsl:apply-templates select="jrnl:body/jrnl:info"/>
        <xsl:apply-templates select="docinfo"/>
      </doc:metadata>
    </newsitem:newsitem>
  </xsl:template>


  <!-- suppressed.  separate rule for xmllang on root  -->
  <xsl:template match="JOURNALDOC/@xml:lang"/>

  <!-- suppress Rosetta-dtd specific atts -->
  <xsl:template match="JOURNALDOC/@version"/>
  <xsl:template match="JOURNALDOC/@versionminor"/>


  <!-- suppressed "except citation" -->
  <xsl:template match="@searchtype"/>
  <!-- per Paul - doc-id standardization
  <xsl:template match="docinfo:doc-id"/>
  -->
</xsl:stylesheet>
