<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Comm-Form-Pre_level5-source">
  <title>Source XML</title>
  <body>
    <codeblock>

&lt;level&gt;
 &lt;level id="475:B005_V2:H1" leveltype="chapter" subdoc="false" toc-caption="PART III THE ADMINISTRATION OF ASSETS"&gt;
  &lt;level id="475:B005_V2:H2" leveltype="chapter" subdoc="false" toc-caption="(22) FIRST DUTIES OF REPRESENTATIVE"&gt;
   &lt;level id="475:B005_V2:H5" leveltype="group" subdoc="false" toc-caption="Advertising for Claims"&gt;
    &lt;heading searchtype="COMMENTARY"&gt;
     &lt;title&gt;Advertising for Claims&lt;/title&gt;
    &lt;/heading&gt;
    &lt;level id="475:B005:P298" leveltype="para0" subdoc="true" toc-caption="298. Issue of advertisements."&gt;
     &lt;heading inline="true" searchtype="COMMENTARY"&gt;
      &lt;edpnum&gt;&lt;refpt id="475:B005:P298" type="ext"/&gt;298.&lt;/edpnum&gt;
      &lt;title&gt;Issue of advertisements.&lt;/title&gt;
     &lt;/heading&gt;
     &lt;bodytext searchtype="COMMENTARY"&gt;
      &lt;!-- ETC. --&gt;
     &lt;/bodytext&gt;
    &lt;/level&gt;
   &lt;/level&gt;
  &lt;/level&gt;
 &lt;/level&gt;
&lt;/level&gt;
    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ09_Comm_Form_Prec_Text\Comm-Form-Pre_level5-source.dita  -->
	 

</xsl:stylesheet>