<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Comm-Form-Pre_leg.comntry-source">
  <title>Source XML</title>
  <body>
    <codeblock>

&lt;comm:body&gt;
 &lt;level id="ELC-PGS_PGS-APX-A.SGM_PRAC.NOTE.GRP_2" leveltype="prac.note.grp"&gt;
  &lt;heading searchtype="COMMENTARY"&gt;
   &lt;title&gt;Appendix A &lt;nl/&gt;Practice Directions of the Employment Court and Employment Relations Authority&lt;/title&gt;
  &lt;/heading&gt;
  &lt;bodytext searchtype="COMMENTARY"&gt;
   &lt;leg:comntry subdoc="true" toc-caption="Commentary"&gt;
    &lt;level id="ELC-PGS_PGS-APX-A.SGM_PGS-APX-A-1" leveltype="para0" subdoc="true" toc-caption="1 Introduction"&gt;
     &lt;heading searchtype="COMMENTARY"&gt;
      &lt;edpnum&gt;&lt;refpt id="PGS-APX-A-1" type="ext"/&gt;1 &lt;/edpnum&gt;
      &lt;title&gt;Introduction&lt;/title&gt;
     &lt;/heading&gt;
     &lt;bodytext searchtype="COMMENTARY"&gt;
      &lt;p&gt;
       &lt;text&gt;The Practice Directions concern the abolition of backing sheets, amended pleadings, and amended notices of appeal in the Employment Court and Employment Relations Authority.&lt;/text&gt;
      &lt;/p&gt;
     &lt;/bodytext&gt;
    &lt;/level&gt;
   &lt;/leg:comntry&gt;
  &lt;/bodytext&gt;
 &lt;/level&gt;
&lt;/comm:body&gt;
    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ09_Comm_Form_Prec_Text\Comm-Form-Pre_leg.comntry-source.dita  -->
	 

</xsl:stylesheet>