<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:funddoc="urn:x-lexisnexis:content:fundamentallegaldocument:sharedservices:1" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="NZ-Treaties-Services_Head">
  <title>Head <lnpid>id-NZ13-25008</lnpid></title>
  <body>
    <p><targetxml>funddoc:fundamentallegaldocument/funddoc:head</targetxml> is created as described
      in the Introduction.</p>

    <section>
      <title>funddoc:head</title>
      <p>If there is no header information found in input document, then conversion will create an empty tag of <targetxml>funddoc:head</targetxml> in output.</p>
      
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ13_Treaties_From_Services\Head.dita  -->
<!--	<xsl:message>NZ13_Treaties_From_Services_Head.xsl requires manual development!</xsl:message> -->
  
<!-- Empty element genrated in the Introduction -->

</xsl:stylesheet>