<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:funddoc="urn:x-lexisnexis:content:fundamentallegaldocument:sharedservices:1" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Introduction">
       <title>Introduction <lnpid>id-NZ13-25009</lnpid></title>
    
    <shortdesc>This Conversion Instructions describes the conversion of the Rosetta LEGDOC DTD to
            <b>funddoc 2.7_PROD</b> schema.</shortdesc>
    <body>
        <p>NZ-Treaties-Services samples are identified using the root element <b>LEGDOC</b> with
            attribute <b>@legtype="treaty-conv"</b></p>
        <section><title>Root Element</title>
                    
               <p>
                <sourcexml>LEGDOC</sourcexml> becomes
                    <targetxml>funddoc:fundamentallegaldocument</targetxml> which is the root
                   element for NZ-Treaties-Services inputs.  </p>                
                                 
                    
                <p>
                <targetxml>funddoc:head</targetxml>, <targetxml>funddoc:body</targetxml>, and
                    <targetxml>doc:metadata</targetxml> are created as required children of
                    <targetxml>funddoc:fundamentallegaldocument</targetxml>
                </p>
            <pre>

&lt;LEGDOC legtype="treaty-conv"&gt;
    ........
    ........
    &lt;docinfo:doc-lang lang="en"/&gt;
    &lt;docinfo:doc-country iso-cc="NZ"/&gt;
    .......
    .......
&lt;/LEGDOC&gt;

<b>Becomes</b>
                

&lt;funddoc:fundamentallegaldocument xml:lang="en-NZ"&gt;
    
    &lt;funddoc:head&gt;.....&lt;/funddoc:head&gt;
    
    &lt;funddoc:body&gt;.....&lt;/funddoc:body&gt;
    
    &lt;doc:metadata&gt;.....&lt;/doc:metadata&gt;
    
&lt;/funddoc:fundamentallegaldocument&gt;

</pre>
            
            <p>
                The <sourcexml>@searchtype</sourcexml> attribute will be suppressed from conversion except for the citation element.
            </p>
            
        </section>
                <section>
                           <title>Notes</title>
                            <p>The following information is meant to help the user to understand the
                conventions used in this document.</p>
                            <p>Source elements and attributes are highlighted like this: <sourcexml>SOURCEXML</sourcexml></p>
                            <p>Target elements and attributes are highlighted like this: <targetxml>TARGETXML</targetxml></p>
                            <p>Verify content of following target attributes: 
                                        <ul>
                                        <li><sourcexml>@month</sourcexml> becomes <targetxml>@month</targetxml> is between 01-12. Any numbers
                                            outside this range, do not output a <targetxml>@month</targetxml>.</li>
                                        <li><sourcexml>@day</sourcexml> becomes <targetxml>@day</targetxml> is between 01-31. Any numbers outside
                                            this range, do not output <targetxml>@day</targetxml>.</li>
                                        <li><sourcexml>@year</sourcexml> becomes <targetxml>@year</targetxml> is 4 digits in length. Any other
                                            lengths, do not output <targetxml>@year</targetxml>.</li>
                                        </ul>
                            </p>
                </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ13_Treaties_From_Services\Introduction.dita  -->
<!--	<xsl:message>NZ13_Treaties_From_Services_Introduction.xsl requires manual development!</xsl:message> -->

	<xsl:template match="LEGDOC">
	    <funddoc:fundamentallegaldocument>
	        <xsl:call-template name="generateNSGlobalBindings"/>
	        <xsl:attribute name="xml:lang" select="$xml_lang"/>
	            
	        <funddoc:head>
	            <xsl:text xml:space="preserve"> </xsl:text>
	        </funddoc:head>
	        
	        <xsl:apply-templates select="leg:body"/>
	        
	        <doc:metadata>
	            <xsl:apply-templates select="docinfo"/>
	        </doc:metadata>
		
		</funddoc:fundamentallegaldocument>

	</xsl:template>


</xsl:stylesheet>