<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:entity="http://www.lexisnexis.com/xmlschemas/content/shared/identified-entities/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="org">
  <title>org <lnpid>id-MY02-16223</lnpid></title>
  
  <body>
    <p>
      <ul>
        <li><sourcexml>org</sourcexml> becomes <targetxml>entity:org</targetxml>.</li>       
      </ul>     
    </p>    
    
    <pre> 

&lt;bio&gt;
    &lt;addl-info&gt;       
        &lt;p&gt;
            &lt;text&gt;
                &lt;org&gt;Middlesex University&lt;/org&gt;
            &lt;/text&gt;
        &lt;/p&gt;
    &lt;/addl-info&gt;
&lt;/bio&gt;


<b>Becomes</b>


&lt;person:bio&gt;
    &lt;person:bio.text&gt;
        &lt;bodytext&gt;
            &lt;p&gt;
                &lt;text&gt;
                    &lt;entity:org&gt;Middlesex University&lt;/entity:org&gt;
                &lt;/text&gt;
            &lt;/p&gt;
        &lt;/bodytext&gt;
    &lt;/person:bio.text&gt;
&lt;/person:bio&gt;

</pre>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY02_Journals\org.dita  -->
<!--	<xsl:message>org.xsl requires manual development!</xsl:message> -->

    <xsl:template match="org[ancestor::addl-info]">
        <entity:org>
            <xsl:apply-templates select="@* | node()"/>
        </entity:org>
    </xsl:template>

</xsl:stylesheet>