<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="primlaw.level">
  <title>primlaw:level <lnpid/></title>
  <body>
    <section>
      <p>Create <targetxml>primlaw:level</targetxml>.
      </p><p><sourcexml>/LEGDOC/leg:body/leg:level[1]/leg:level-vrnt/@leveltype</sourcexml> becomes <targetxml>primlaw:level/@leveltype</targetxml>. .</p>
      <p>Create <targetxml>primlaw:level/primlaw:levelinfo</targetxml>, and populate this element
        with <targetxml>primlawinfo:primlawinfo</targetxml> as described below.</p>
      
    </section>  
    <note>Conversion should not create adjacent
      <targetxml>primlaw:levelinfo</targetxml>. Data should be merged to
      single <targetxml>primlaw:levelinfo</targetxml>.</note>
    <p>Populate this <targetxml>primlaw:level</targetxml> with the content within
        <sourcexml>/LEGDOC/leg:body/leg:level[1</sourcexml> ] as described for each of the
        descendents. </p>
    <section>
      <title>Changes</title>
      <p>2014-06-06: <ph id="change_20140606_brt">Created new topic and moved contents in <targetxml>primlawinfo:primlawinfo</targetxml> 
        from <targetxml>legis:head</targetxml> to <targetxml>legis:body/primlaw:level/primlaw:levelinfo</targetxml></ph>.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\CN01-Legislation\primlaw.level.dita  -->
	<xsl:message>primlaw.level.xsl requires manual development!</xsl:message> 

	<xsl:template match="/LEGDOC/leg:body/leg:level[1]/leg:level-vrnt/@leveltype">

		<!--  Original Target XPath:  primlaw:level/@leveltype   -->
		<primlaw:level>
			<xsl:attribute name="leveltype">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</primlaw:level>

	</xsl:template>

	<xsl:template match="/LEGDOC/leg:body/leg:level[1">

		<!--  Original Target XPath:  primlawinfo:primlawinfo   -->
		<primlawinfo:primlawinfo>
			<xsl:apply-templates select="@* | node()"/>
		</primlawinfo:primlawinfo>

	</xsl:template>

</xsl:stylesheet>