<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	version="2.0" exclude-result-prefixes="dita xsl">
	<dita:topic>
		<dita:body><dita:section>refpt child of p/text/emph to
			p/ref:anchor id-CCCC-10457
	
		
			p/text/emph/refpt becomes p/ref:anchor.
			All occurrences of refpt[@type="ext"] should map to ref:anchor[@anchortype="global"]. If value of refpt[@type="local"], or is omitted or any other value the mapping should be ref:anchor[@anchortype="local"].
			If any text comes under the refpt then conversion needs to map in
				target ref:anchor/ref:anchortext. (i.e.
					p/text/emph/refpt becomes
					p/ref:anchor/ref:anchortext).
		
		
			Source XML
			

&lt;p&gt;
	 &lt;text&gt;
	 	&lt;emph&gt;
			 &lt;refpt id="x98-525a1"/&gt;
		 	Section 115 contains the general right of 
		 	appeal given to a defendant in proceedings 
		 	governed by the Summary Proceedings Act. 
		 	...
	 	&lt;/emph&gt;
	 &lt;/text&gt;
&lt;/p&gt;

		
		
		
			Target XML
			

&lt;p&gt;
		&lt;ref:anchor id="x98-525a1" anchortype="local"/&gt;
        &lt;text&gt;
	        Section 115 contains the general right of 
	 		appeal given to a defendant in proceedings 
	 		governed by the Summary Proceedings Act.
	 		...
	 	&lt;/text&gt;
&lt;/p&gt;
  
		
		
		
		
			Changes
			2016-07-27: Added a note for handling of text which is
					comes under the refpt in source.
			2013-10-11: Added a note and update the target examples when refpt
				comes without attribute [@type="ext"] and
				[@type="local"] in source documents.
			2012-08-30: Created. 
		
		</dita:section>
		</dita:body>
	</dita:topic>
	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	
</xsl:stylesheet>
