<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_person_searchtype-LxAdv_person.person_and_doc.legacy-metadata">
  <title><sourcexml>person[@searchtype="JUDGES"]</sourcexml> to <targetxml>person:person</targetxml>
    <b>and</b>
    <targetxml>doc:legacy-metadata[@metadatasource="lbu-meta"]</targetxml> <lnpid>id-CCCC-10430</lnpid></title>
  <body>
    <section>
      <p><sourcexml>person[@searchtype="JUDGES"]</sourcexml> maps to 2 locations in the target
        document: <ul>
          <li><sourcexml>person</sourcexml> becomes <targetxml>person:person</targetxml> as
            described in <xref href="Rosetta_person-LxAdv-person.person.dita"/>. The attribute
              <sourcexml>@searchtype="JUDGES"</sourcexml> is ignored for this mapping.</li>
          <li>In addition, create
              <targetxml>doc:metadata/doc:docinfo/doc:legacy-metadata[@metadatasource="lbu-meta"]/meta/metaitem</targetxml>
            with the attributes of <targetxml>metaitem</targetxml> populated as follows: <ul>
              <li>The value of <targetxml>metaitem/@name</targetxml> is set to "JUDGES".</li>
              <li>The value of <targetxml>metaitem/@value</targetxml> is set to the content of
                  <sourcexml>person/name.text</sourcexml>.</li>
            </ul></li>
        </ul></p>
      <note><p>Conversion should not create consecutive
            <targetxml>doc:legacy-metadata/meta</targetxml> elements. When 2 or more consecutive
          sibling source elements map to <targetxml>doc:legacy-metadata/meta</targetxml>, data
          should be merged to a single <targetxml>doc:legacy-metadata/meta</targetxml> element
          unless this would hamper content ordering.</p></note>
    </section>
    <example>
      <codeblock>
&lt;person searchtype="JUDGES"&gt;
    &lt;name.text&gt;SCARMAN L.J.&lt;/name.text&gt;
&lt;/person&gt;
            </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;person:judge&gt;
    &lt;person:person&gt;
        &lt;person:name.text&gt;SCARMAN L.J.&lt;/person:name.text&gt;
    &lt;/person:person&gt;
&lt;/person:judge&gt;
<b>and</b>
&lt;doc:legacy-metadata metadatasource="lbu-meta"&gt;
    &lt;meta&gt;
        &lt;metaitem name="JUDGES" value="SCARMAN L.J."/&gt;
    &lt;/meta&gt;
&lt;/doc:legacy-metadata&gt;
	</codeblock>
    </example>
    <section>
      <title>Changes</title>
      <p>2013-08-13: <ph id="change_20130813_DSF">Corrected the mapping.
          person[@searchtype="JUDGES"] now maps to 2 locations: person:person and
          doc:legacy-metadata[@metadatasource="lbu-meta"].</ph></p>
      <p>2013-07-09: <ph id="change_20130709_DSF">Created.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_person_searchtype-LxAdv_person.person_and_doc.legacy-metadata.dita  -->

<!-- Vikas Rohilla : Tempalteto match the person/@searchtype -->
	<xsl:template match="person/@searchtype[.='JUDGES']">
					<meta>
						<metaitem>
						  <xsl:attribute name="name" select="'JUDGES'"/>
						  <xsl:attribute name="value">
						    <xsl:value-of select="."/>
						  </xsl:attribute>
						</metaitem>
					</meta>
	</xsl:template>



</xsl:stylesheet>