<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_remotelink-Chof-p-LxAdv-p_text_ref.crossreference">
 <title><sourcexml>p/remotelink</sourcexml> to
  <targetxml>p/text/ref:crossreference</targetxml> <lnpid>id-CCCC-10463</lnpid></title>
 <body>
   <section><p><sourcexml>p/remotelink</sourcexml> becomes <targetxml>p/text/ref:crossreference</targetxml> and is converted as described in the topic <xref href="Rosetta_remotelink-LxAdv-ref.crossreference.dita"/>.</p></section>
  <example>
   <title>Source XML </title>
   <codeblock>

&lt;p&gt;
    &lt;remotelink service="DOC-ID" remotekey1="REFPTID" dpsi="0KMN"
        refpt="0KMN_2_A_ABATEMENT:HTDICT-TERM"&gt;Get a full definition of
        Abatement&lt;/remotelink&gt;
&lt;/p&gt;

            </codeblock>
   <title>Target XML</title>
   <codeblock>

&lt;p&gt;
   &lt;text&gt;
      &lt;ref:crossreference crossreferencetype="seeAlso"&gt;
          &lt;ref:content&gt;Get a full definition of
              Abatement&lt;/ref:content&gt;
          &lt;ref:locator
              anchoridref="0KMN_2_A_ABATEMENT:HTDICT-TERM"&gt;
              &lt;ref:locator-key&gt;
                  &lt;ref:key-name name="DOC-ID"/&gt;
                  &lt;ref:key-value value="0KMN"/&gt;
              &lt;/ref:locator-key&gt;
          &lt;/ref:locator&gt;
      &lt;/ref:crossreference&gt;
   &lt;/text&gt;
&lt;/p&gt;


            </codeblock>
  </example>
  <section>
   <title>Changes</title>
   <p>2013-03-07: <ph id="change_20130307_raj">Created.</ph></p>
  </section>
 </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_remotelink-Chof-p-LxAdv-p_text_ref.crossreference.dita  -->

	<xsl:template match="p[remotelink]" priority="25">
	    <xsl:element name="p"
	        namespace="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/">
	        <xsl:apply-templates select="@*"/>	        
	        <!-- create ref:anchor before other elements to meet schema ordering -->
	        <xsl:apply-templates select="refpt | text/refpt"/>
	        <xsl:for-each select="*[not(self::refpt)] | text()">
	            <xsl:choose>
	                <xsl:when test="self::remotelink">
	                    <text xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/">
	                        <xsl:apply-templates select="."/>
	                    </text>
	                </xsl:when>
	                <xsl:otherwise>
	                    <xsl:apply-templates select="."/>
	                </xsl:otherwise>
	            </xsl:choose>
	        </xsl:for-each>	       	        
	    </xsl:element>		
	</xsl:template>
</xsl:stylesheet>