<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/" xmlns:case="http://www.lexis-nexis.com/glp/case" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_case.courtcode_ln.user-displayed">
  <title><sourcexml>case:courtcode/@ln.user-displayed</sourcexml> <lnpid>id-CCCC-10257</lnpid></title>
  <body>
    <section>
      <note>Elements that contain the attribute <sourcexml>@ln.user-displayed="false"</sourcexml> are used for certain functionality in Rosetta that does not exist in Lexis
        Advance. Each of the following elements have mappings described elsewhere in this CI for when this attribute does not exist. The examples here are ONLY for when
        this <sourcexml>@ln.user-displayed="false"</sourcexml> appears. (This attribute never has a "true" value, i.e. @ln.user-displayed="true".)</note>
      
      <p>When <sourcexml>case:courtcode</sourcexml> has attribute <sourcexml>@ln.user-displayed="false"</sourcexml> (i.e. <sourcexml>case:courtcode/@ln.user-displayed="false"</sourcexml>),
        that element is translated into the target but with the element content omitted. Only the attributes are populated. So there is no displayable content.</p>
      
    </section>
    
    <example>
      <title>Source XML</title>
      <codeblock>

&lt;case:courtcode ln.user-displayed="false"&gt;CALET&lt;/case:courtcode&gt;

            </codeblock>
    </example>
    
    <example>
      <title>Target XML</title>
      <codeblock>&lt;jurisinfo:courtinfo&gt;
&lt;jurisinfo:alternatecourtcode alternatecourtcode="CALET"/&gt;
&lt;/jurisinfo:courtinfo&gt;

&lt;doc:legacy-metadata metadatasource="lbu-meta"&gt;
  &lt;meta&gt;
    &lt;metaitem name="case:courtcode" value="CALET"&gt;  
  &lt;/meta&gt;
&lt;/doc:legacy-metadata&gt;

            </codeblock>
    </example>   
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_case.courtcode_ln.user-displayed.dita  -->
	<!--<xsl:message>Rosetta_case.courtcode_ln.user-displayed.xsl requires manual development!</xsl:message>--> 
  <!--2018-03-15: RS:  Added "or" condition in below template for handling  without attribute case:courtcode -->
  <xsl:template match="case:courtcode[@ln.user-displayed='false'] | case:courtcode">
			<jurisinfo:alternatecourtcode>
				<xsl:attribute name="alternatecourtcode">
					<xsl:value-of select="."/>
				</xsl:attribute>
			</jurisinfo:alternatecourtcode>		
	</xsl:template>

	<xsl:template match="case:courtcode/@ln.user-displayed"/>
</xsl:stylesheet>