<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_defterm-Chof-text_outside_deflist-LxAdv-defterm.dita">
  <title><sourcexml>text/defterm</sourcexml> when outside <sourcexml>deflist</sourcexml>, etc. <lnpid>id-CCCC-10494</lnpid></title>
  <body>
      <p>When <sourcexml>defterm</sourcexml> has parent <sourcexml>text</sourcexml> and both of the following are true. <ol>
        <li>The source parent <sourcexml>text</sourcexml> element is not a descendant of any of these source elements:<ul>
          <li>deflist</li>
          <li>defitem</li>
          <li>defterm</li>
          <li>defdesc</li>
        </ul></li>
        <li>The source parent <sourcexml>text</sourcexml> element is converted to the target <targetxml>text</targetxml> element.</li>
      </ol>
      Then <sourcexml>text/defterm</sourcexml> becomes <targetxml>text/defterm</targetxml>.</p>
    <example>
      <title>Source XML</title>
      <codeblock>

&lt;level leveltype="section" id="DN_0S3I_250406_d4e3651"&gt;
  &lt;bodytext&gt;
    &lt;p&gt;
      &lt;text&gt;The clause referred to is clause 37.3 [1327] (Alteration of the text of the &lt;defterm&gt;Work&lt;/defterm&gt;) of this Form.&lt;/text&gt;
    &lt;/p&gt;
  &lt;/bodytext&gt;
&lt;/level&gt;

            </codeblock>
    </example>
    
    <example>
      <title>Target XML</title>
      <codeblock>

...
  &lt;bodytext&gt;
    &lt;p&gt;
      &lt;text&gt;The clause referred to is clause 37.3 [1327] (Alteration of the text of the &lt;defterm&gt;Work&lt;/defterm&gt;) of this Form.&lt;/text&gt;
    &lt;/p&gt;
  &lt;/bodytext&gt;
... 

            </codeblock>
    </example>
    <section>
      <title>Changes</title>
      <p>2014-05-23: <ph id="change_20140523_JCG">Created.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_defterm-Chof-text_outside_deflist-LxAdv-defterm.dita  -->
<!--	<xsl:message>Rosetta_defterm-Chof-text_outside_deflist-LxAdv-defterm.xsl requires manual development!</xsl:message> -->

  <!-- Ravikant: Added condition when parent is text for MY02 -->
  <xsl:template match="text/defterm[not($streamID='MY02')]">

		<!--  Original Target XPath:  text   -->
		<text>
			<xsl:apply-templates select="@* | node()"/>
		</text>

	</xsl:template>

	<xsl:template match="deflist">

		<!--  Original Target XPath:  text   -->
		<text>
			<xsl:apply-templates select="@* | node()"/>
		</text>

	</xsl:template>

	<xsl:template match="defterm">

		<!--  Original Target XPath:  text   -->
	  <defterm>
			<xsl:apply-templates select="@* | node()"/>
		</defterm>

	</xsl:template>
  

</xsl:stylesheet>