<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="common_rosetta_case.judges_emph">
        <title><sourcexml>emph</sourcexml> to  omit <sourcexml>emph</sourcexml> start-tag and end-tag <lnpid>id-CCCC-10314</lnpid></title>    
        <body>
	        <section>
		        <title>Instructions <i>[common element]</i></title>
    	        <p><b>When <sourcexml>emph</sourcexml> is inside <sourcexml>case:judges</sourcexml> and <sourcexml>@typestyle="smcaps"</sourcexml> then conversion need to omit <sourcexml>emph</sourcexml> tag.</b></p>
	        </section>
            <example>
	            <title>Source XML</title>
	            <codeblock>
					&lt;case:judgment&gt;
					  &lt;case:courtinfo&gt;
					      &lt;case:judges&gt;
					          JUDGE M 
					          &lt;emph typestyle="smcaps"&gt;c&lt;/emph&gt; 
					          ELREA. 
					      &lt;/case:judges&gt;
					  &lt;/case:courtinfo&gt;
					  ...
					&lt;/case:judgment&gt;
        	    </codeblock>
	        </example>
	        <example>
	            <title>Target XML</title>
	            <codeblock>
					&lt;courtcase:opinion&gt;
					  &lt;courtcase:opinionby&gt;
					    JUDGE M 
					    c
					    ELREA. 
					  &lt;/courtcase:opinion&gt;
					&lt;/courtcase:opinion&gt;
        	    </codeblock>
	        </example>
            <section>
		        <title>Changes</title>
		        <p>2011-12-15: Created.</p>
                <p>Added instructions for handling of <sourcexml>case:judges/emph/@typestyle="smcaps"</sourcexml>.</p>
            </section>
        </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated (although the DITA file already has embedded XSLT).  Remove this comment after manual development complete!  (also remove the embedded XSLT within the DITA above) @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_emph-Chof-case.judges-LxAdv-omit_tag.dita  -->

    <!-- 20170424:  MCJ:  Handled to match the conversion instructions.  However, it feels like this would be better placed in a single module that handles emph to avoid spreading the instructions
    	                  across many modules. -->
	<!-- 20170424:  MCJ:  Also don't know if the XSLT that is embedded in the DITA needs to be changed. -->
	<xsl:template match="emph[parent::case:judges and ./@typestyle='smcaps']">
        <xsl:apply-templates />
	</xsl:template>

</xsl:stylesheet>