<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:ci="http://www.lexis-nexis.com/ci" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita ci">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_remotelink-Chof-ci.content_url-LxAdv-url">
    <title><sourcexml>ci:cite/ci:content/url/remotelink</sourcexml> <lnpid>id-CCCC-10513</lnpid></title>
    <body>
        <p>This rule only applies when the XPaths
                <sourcexml>text/ci:cite/ci:content/url/remotelink</sourcexml> or
                <sourcexml>entry/ci:cite/ci:content/url/remotelink</sourcexml> occur. In this
            scenario, each <sourcexml>url</sourcexml> (the direct child of
                <sourcexml>ci:content</sourcexml>) is moved outside the
                <sourcexml>ci:cite</sourcexml> so that the <sourcexml>url</sourcexml> becomes the
                <sourcexml>ci:cite</sourcexml> element's immediate next sibling (and also now a
            direct child of <sourcexml>text</sourcexml> or <sourcexml>entry</sourcexml>). Conversion
            is then done on the <sourcexml>ci:cite</sourcexml> element as described in the section
                    <b><i>General Markup</i></b>. The moved <sourcexml>url</sourcexml> element and
            its child <sourcexml>remotelink</sourcexml> are converted as described in the topic
                <xref href="Rosetta_remotelink-Chof-url-LxAdv-url.dita"/>.</p> 
        <note>Depending on the attribute values and contents of the <sourcexml>remotelink</sourcexml>, it is converted to <targetxml>ref:lnlink</targetxml> or <targetxml>url</targetxml>.</note>
        <example>
            <title>Source XML </title>
            <codeblock>

&lt;text&gt;
    ...
    &lt;ci:cite searchtype="LEG-REF" status="invalid"&gt;
        &lt;ci:sesslaw&gt;
            &lt;ci:sesslawinfo&gt;
                &lt;ci:sesslawnum num="1970_9a"/&gt;
                &lt;ci:hierpinpoint&gt;
                    &lt;ci:hierlev label="section" num="109BCT"/&gt;
                &lt;/ci:hierpinpoint&gt;
            &lt;/ci:sesslawinfo&gt;
            &lt;ci:sesslawref&gt;
                &lt;ci:standardname normpubcode="UK_ACTS"/&gt;
            &lt;/ci:sesslawref&gt;
        &lt;/ci:sesslaw&gt;
        &lt;ci:content&gt;
            &lt;url&gt;
                &lt;remotelink hrefclass="http" href="www.somedomain.com/practice-statments/cpi"&gt;Statement of Practice 2/90, page 97&lt;/remotelink&gt;
            &lt;/url&gt;CT
        &lt;/ci:content&gt;
    &lt;/ci:cite&gt;
    ...
&lt;/text&gt;

            </codeblock>
            <title>Target XML</title>
            <codeblock>

&lt;text&gt;
    ...
    &lt;lnci:cite&gt;
        &lt;lnci:sesslaw&gt;
            &lt;lnci:sesslawinfo&gt;
                &lt;lnci:sesslawnum num="1970_9a"/&gt;
                &lt;lnci:hierpinpoint&gt;
                    &lt;lnci:hierlev label="section" num="109BCT"/&gt;
                &lt;/lnci:hierpinpoint&gt;
            &lt;/lnci:sesslawinfo&gt;
            &lt;lnci:sesslawref&gt;
                &lt;lnci:standardname normpubcode="UK_ACTS"/&gt;
            &lt;/lnci:sesslawref&gt;
        &lt;/lnci:sesslaw&gt;
        &lt;lnci:content&gt;CT&lt;/lnci:content&gt;
    &lt;/lnci:cite&gt;
    &lt;ref:lnlink service="URL"&gt;
        &lt;ref:marker&gt;Statement of Practice 2/90, page 97&lt;/ref:marker&gt;
        &lt;ref:locator&gt;
            &lt;ref:locator-key&gt;
                &lt;ref:key-name name="URL"/&gt;
                &lt;ref:key-value value="http://www.somedomain.com/practice-statments/cpi"/&gt;
            &lt;/ref:locator-key&gt;
        &lt;/ref:locator&gt;
    &lt;/ref:lnlink&gt;
    ...
&lt;/text&gt;

            </codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>2014-10-24: <ph id="change_20141024_JCG">Added this instruction. (R4.5 Content Issue List #1997)</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_url-Chof-ci.content-LxAdv-url.dita  -->
<!--	<xsl:message>Rosetta_url-Chof-ci.content-LxAdv-url.xsl requires manual development!</xsl:message> -->

	<xsl:template match="ci:cite/ci:content/url/remotelink">

		<!--  Original Target XPath:  ref:lnlink   -->
		<ref:lnlink>
			<xsl:apply-templates select="@* | node()"/>
		</ref:lnlink>

	</xsl:template>

	<xsl:template match="text/ci:cite/ci:content/url/remotelink">

		<!--  Original Target XPath:  ref:lnlink   -->
		<ref:lnlink>
			<xsl:apply-templates select="@* | node()"/>
		</ref:lnlink>

	</xsl:template>

	<xsl:template match="entry/ci:cite/ci:content/url/remotelink">

		<!--  Original Target XPath:  ref:lnlink   -->
		<ref:lnlink>
			<xsl:apply-templates select="@* | node()"/>
		</ref:lnlink>

	</xsl:template>

	<xsl:template match="url">

		<!--  Original Target XPath:  ref:lnlink   -->
		<ref:lnlink>
			<xsl:apply-templates select="@* | node()"/>
		</ref:lnlink>

	</xsl:template>

	<xsl:template match="ci:content">

		<!--  Original Target XPath:  ref:lnlink   -->
		<ref:lnlink>
			<xsl:apply-templates select="@* | node()"/>
		</ref:lnlink>

	</xsl:template>

	<xsl:template match="ci:cite">

		<!--  Original Target XPath:  ref:lnlink   -->
		<ref:lnlink>
			<xsl:apply-templates select="@* | node()"/>
		</ref:lnlink>

	</xsl:template>

	<xsl:template match="text">

		<!--  Original Target XPath:  ref:lnlink   -->
		<ref:lnlink>
			<xsl:apply-templates select="@* | node()"/>
		</ref:lnlink>

	</xsl:template>

	<xsl:template match="entry">

		<!--  Original Target XPath:  ref:lnlink   -->
		<ref:lnlink>
			<xsl:apply-templates select="@* | node()"/>
		</ref:lnlink>

	</xsl:template>

	<xsl:template match="remotelink">

		<!--  Original Target XPath:  ref:lnlink   -->
		<ref:lnlink>
			<xsl:apply-templates select="@* | node()"/>
		</ref:lnlink>

	</xsl:template>

</xsl:stylesheet>