<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
	xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0"
	exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
		id="Rosetta_refpt-Chof-p_edpnum-LxAdv-p_ref.anchor">
		<title><sourcexml>refpt</sourcexml> child of <sourcexml>p/edpnum</sourcexml> to
				<targetxml>p/ref:anchor</targetxml>
			<lnpid>id-CCCC-10455</lnpid></title>
		<body>
			<section>
				<p>If <sourcexml>refpt</sourcexml> is child of <sourcexml>p/edpnum</sourcexml> then
						<targetxml>ref:anchor</targetxml> will become the first child of
						<targetxml>p</targetxml>.</p>
			</section>
			<example>
				<title>Source XML</title>
				<codeblock> &lt;p&gt; &lt;edpnum value="29" inline="false"&gt;[29]&lt;refpt
					id="02FO_1_PII:HTCOMM-DIV_29:HTCOMM-PARA" type="ext"/&gt;&lt;/edpnum&gt;
					&lt;text&gt;The Union and the Member States, having in mind fundamental
					...&lt;/text&gt; &lt;/p&gt; </codeblock>
			</example>
			<example>
				<title>Target XML</title>
				<codeblock> &lt;p&gt; &lt;ref:anchor id="_02FO_1_PII:HTCOMM-DIV_29:HTCOMM-PARA"
					anchortype="global"/&gt; &lt;desig value="29"
					inline="false"&gt;[29]&lt;/desig&gt; &lt;text&gt;The Union and the Member
					States, having in mind fundamental ...&lt;/text&gt; &lt;/p&gt; </codeblock>
			</example>
			<section>
				<title>Changes</title>
				<p>2014-01-13: <ph id="change_20140113_jm">New module. Immediately applies to
						UK12-Treatise (Dec 2013 redelivery, dpsi 02FO) and expected to apply to any
						future stream if the use case occurs.</ph></p>
			</section>
		</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_refpt-Chof-p_edpnum-LxAdv-p_ref.anchor.dita  -->
	<!--	<xsl:message>Rosetta_refpt-Chof-p_edpnum-LxAdv-p_ref.anchor.xsl requires manual development!</xsl:message> -->



	<xsl:template match="p/edpnum">
		<desig>
			<xsl:apply-templates select="@* | node()"/>
		</desig>
	</xsl:template>
	
	<xsl:template match="p/edpnum/@value">
		<xsl:attribute name="value">
			<xsl:analyze-string select="." regex="\[(.+)\]">
				<xsl:matching-substring>
					<xsl:value-of select="regex-group(1)"/>
				</xsl:matching-substring>
				<xsl:non-matching-substring>
					<xsl:value-of select="."/>
				</xsl:non-matching-substring>
			</xsl:analyze-string>
		</xsl:attribute>
	</xsl:template>

	<xsl:template match="p/edpnum/@inline">
		<xsl:attribute name="inline">
			<xsl:value-of select="."/>
		</xsl:attribute>
	</xsl:template>

</xsl:stylesheet>
