<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns:base="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/"
    version="2.0" exclude-result-prefixes="dita">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
        id="AU_NZ_Rosetta_copyright-to-LexisAdvance_copyright">
        <title>(AU/NZ) <sourcexml>copyright</sourcexml> to <targetxml>copyright</targetxml>
            <lnpid>id-CCCC-10242</lnpid></title>
        <body>
            <section>
                <p>
                    <sourcexml>copyright</sourcexml> becomes <targetxml>copyright</targetxml> with
                    optional child <ul>
                        <li>
                            <sourcexml>copyright.holder</sourcexml> becomes
                                <targetxml>copyright-holder</targetxml>. </li>
                    </ul>
                </p>
                <p>Keep <targetxml>copyright</targetxml> within
                        <targetxml>pubinfo:pubinfo</targetxml> in output documents and let the
                    stylesheet handle this for AU/NZ cases.</p>
            </section>

            <example> Source XML <codeblock> &lt;case:judgmentbody&gt; ... &lt;h align="left"&gt;
                    &lt;copyright&gt; © &lt;copyright.holder&gt;Crown
                    Copyright&lt;/copyright.holder&gt; &lt;/copyright&gt; &lt;/h&gt; ...
                    &lt;/case:judgmentbody&gt; </codeblock>
            </example>

            <example> Target XML <codeblock> &lt;doc:metadata&gt; … &lt;pubinfo:pubinfo&gt;
                    &lt;copyright&gt; © &lt;copyright-holder&gt;Crown
                    Copyright&lt;/copyright-holder&gt; &lt;/copyright&gt; &lt;/pubinfo:pubinfo&gt;
                    ... &lt;/doc:metadata&gt; </codeblock>
            </example>

            <example> Source XML <codeblock> &lt;glp:note&gt; &lt;blockquote&gt; &lt;p&gt;
                    &lt;text&gt; &lt;copyright&gt;© The Incorporated Council of Law Reporting for
                    the State of Queensland, 2010.&lt;/copyright&gt; &lt;/text&gt; &lt;/p&gt;
                    &lt;/blockquote&gt; &lt;/glp:note&gt; </codeblock>
            </example>

            <example> Target XML <codeblock> &lt;doc:metadata&gt; ... &lt;pubinfo:pubinfo&gt;
                    &lt;copyright&gt;© The Incorporated Council of Law Reporting for the State of
                    Queensland, 2010.&lt;/copyright&gt; &lt;/pubinfo:pubinfo&gt;
                    &lt;/doc:metadata&gt; </codeblock>
            </example>

            <section>
                <title>Changes</title>
                <p>2013-11-12: <ph id="change_20131112_PS">Added example for AU Cases. Webstar #:
                        5093906. This change immediately applies to AU01 Caselaw.</ph></p>
            </section>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_AU_NZ_copyright-LxAdv-copyright.dita  -->
    <!-- <xsl:message>Rosetta_AU_NZ_copyright-LxAdv-copyright.xsl requires manual
        development!</xsl:message> -->

    <!-- 20150515:  MCJ:  Not sure these templates will hold up. -->
    
    <xsl:template match="copyright">
        <!--  Original Target XPath:  copyright   -->
        <base:copyright>
            <xsl:apply-templates select="@* | node()"/>
        </base:copyright>
    </xsl:template>

    <xsl:template match="copyright.holder">
        <!--  Original Target XPath:  copyright-holder   -->
        <base:copyright-holder>
            <xsl:apply-templates select="@* | node()"/>
        </base:copyright-holder>
    </xsl:template>

</xsl:stylesheet>