<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="common_rosetta_char-line_form-chars">

<title><sourcexml>case:judgmentbody/char-line</sourcexml> to  <targetxml>bodytext/p/text/proc:formchars</targetxml> <lnpid>id-CCCC-10262</lnpid></title>    

    <body>
	 <ul>
	     <li>
	    <p><b><sourcexml>case:judgmentbody/char-line</sourcexml> will become <targetxml>bodytext/p/text/proc:formchars</targetxml></b>.</p>
	     </li>
	 </ul>
	    <section>
	        <title>Source XML</title>
	        <codeblock>

&lt;case:judgmentbody&gt;
    ...
    &lt;form-chars character="." /&gt;
&lt;/case:judgmentbody&gt;

	</codeblock>
	    </section>
	    
	    <section>
	        <title>Target XML</title>
	        <codeblock>

&lt;bodytext&gt;
    ...
    &lt;p&gt;
        &lt;text&gt;
            &lt;proc:formchars formchar="dot" fromcharuse="leaderfill"/&gt;
        &lt;/text&gt;
    &lt;/p&gt;
&lt;/bodytext&gt;

	</codeblock>
	    </section> 
      <section>
		<title>Changes</title>
		<p>2012-08-30: Created.</p>
	</section>
</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_case.judgmentbody_char-line-LxAdv-proc.formchars.dita  -->
	<xsl:message>Rosetta_case.judgmentbody_char-line-LxAdv-proc.formchars.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:judgmentbody/char-line">

		<!--  Original Target XPath:  bodytext/p/text/proc:formchars   -->
		<bodytext>
			<p>
				<text>
					<proc:formchars xmlns:proc="http://www.lexisnexis.com/xmlschemas/content/shared/process-elements/1/">
						<xsl:apply-templates select="@* | node()"/>
					</proc:formchars>
				</text>
			</p>
		</bodytext>

	</xsl:template>

</xsl:stylesheet>