<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_lilabel-fnr-to-LexisAdvance_label-footnote">
  <title><sourcexml>lilabel/fnr</sourcexml> to  <targetxml>label/footnote</targetxml> <lnpid>id-CCCC-10321</lnpid></title>
  <body>
    <section>
      <p><sourcexml>lilabel/fnr</sourcexml> becomes <targetxml>label/footnote</targetxml></p>
    </section>
      <example>
        <title>Source XML having lilabel/fnr:</title>
        <codeblock>
         &lt;li id="AFL.FL.FLA75.S31.1.C"&gt;    
             &lt;lilabel&gt;        
                 &lt;refpt id="AFL.FL.FLA75.S31.1.C" type="ext"/&gt;        
                 &lt;fnr fnrtoken="AFL.FL.FLA75.S31.1.C.FTN1-R" fntoken="AFL.FL.FLA75.S31.1.C.FTN1"&gt;*&lt;/fnr&gt;(c)        
             &lt;/lilabel&gt;    
             . . .     
         &lt;/li&gt; 
     </codeblock>
      </example>
    
    <example>
      <title>Target XML </title>
      <codeblock>

&lt;listitem&gt;
    &lt;ref: anchor id=" AFL.FL.FLA75.S31.1.C " anchortype="global"/&gt;
    &lt;bodytext&gt;
        ...
    &lt;/bodytext&gt;
    &lt;label&gt;(c)
        &lt;footnote&gt;
            &lt;ref:anchor id="AFL.FL.FLA75.S31.1.C.FTN1" anchortype="global"/&gt;
            &lt;label&gt;*&lt;/label&gt;
            &lt;bodytext&gt;
                ....
            &lt;/bodytext&gt;
        &lt;/footnote&gt;
    &lt;/label&gt;
&lt;/listitem&gt;

</codeblock>
    </example>
    
    
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_fnr-Chof-lilabel-LxAdv-label_footnote.dita  -->
	 
    <!-- Vikas Rohilla : initila updated may by changed if required-->
    <!-- 20170531:  MCJ:  Enforced order of processing attributes since some create elements. --> 
    <xsl:template match="lilabel/fnr">
        <footnote>
            <xsl:choose>
                <xsl:when test="$streamID=('AU18', 'UK12')">
                    <xsl:element name="ref:anchor">
                        <xsl:attribute name="id">
                            <xsl:value-of select="@fnrtoken"/>
                        </xsl:attribute>
                        <xsl:attribute name="anchortype">
                            <xsl:text>global</xsl:text>
                        </xsl:attribute>
                    </xsl:element>
                    <label><xsl:apply-templates select="node()"/></label>
                    <bodytext><xsl:text><!--Mandatory element per the target schema--></xsl:text></bodytext>
                </xsl:when>
                <xsl:otherwise>
                    <!-- Process all attributes except @fnrtoken because fnrtoken produces an element.  This does assume that no other
		         attributes produce elements. -->
                    <xsl:apply-templates select="@* except @fnrtoken" />
                    <!-- Now process @fnrtoken as the last attribute since it produces an element. -->
                    <xsl:apply-templates select="@fnrtoken" />
                    <xsl:apply-templates select="node()"/>
                </xsl:otherwise>
            </xsl:choose>
            
        </footnote>
    </xsl:template>

</xsl:stylesheet>