<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_case.judges_ln.user-displayed">
  <title><sourcexml>case:judges/@ln.user-displayed="false"</sourcexml> <lnpid>id-CCCC-10261</lnpid></title>
  <body>
    <section>
      <note>Elements that contain the attribute <sourcexml>@ln.user-displayed="false"</sourcexml> are used for certain functionality in Rosetta that does not exist in Lexis
        Advance. Each of the following elements have mappings described elsewhere in this CI for when this attribute does not exist. The examples here are ONLY for when
        this <sourcexml>@ln.user-displayed="false"</sourcexml> appears. (This attribute never has a "true" value, i.e. @ln.user-displayed="true".)</note>
      
      <p>If <b><sourcexml>case:judges</sourcexml> has attribute <sourcexml>@ln.user-displayed="false"</sourcexml></b>: data has been fixed by LBU so it won't occur in updated data.  In
        meantime conversion can suppress it.</p>      
    </section>
    
    <example>
      <title>Source XML</title>
      <codeblock>

&lt;case:judges ln.user-displayed="false"&gt;
    &lt;emph typestyle="bf"&gt;WILLIAMS J&lt;/emph&gt;
&lt;/case:judges&gt;

</codeblock>
    </example>
    
    <example>
      <title>Target XML</title>
      <codeblock>

&lt;!-- output Suppressed --&gt;

	</codeblock>
    </example>
    
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_case.judges_ln.user-displayed.dita  -->
	 
<!-- Vikas Rohilla : compleated -->
	<xsl:template match="case:judges/@ln.user-displayed[.='false']"/>

</xsl:stylesheet>