<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"  version="2.0"
    exclude-result-prefixes="dita">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
        id="Rosetta_pgrp_searchtype-LxAdv-pgrp">
        <title>pgrp/@searchtype="QUOTED-TEXT" <lnpid>id-CCCC-10432</lnpid></title>

        <body>
            <p><sourcexml class="+ topic/keyword xml-d/sourcexml "
                    >pgrp/@searchtype="QUOTED-TEXT"</sourcexml> becomes <targetxml
                    class="+ topic/keyword xml-d/targetxml ">pgrp</targetxml>.</p>

            <pre xml:space="preserve" class="- topic/pre ">&lt;pgrp searchtype="QUOTED-TEXT"&gt;
    &lt;p&gt;
        &lt;pnum count="34"&gt;34&lt;/pnum&gt;
        &lt;text&gt;Deux collègues de notre Cour ont déjà circonscrit l'infraction commise avec violence
            comme étant celle au cours de laquelle il y a eu l'utilisation d'une force intense,
            extrême et brutale [Voir Note 2 ci-dessous].&lt;/text&gt;
    &lt;/p&gt;
    &lt;hrule align="left" width="30%"/&gt;
    ...
&lt;/pgrp&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;pgrp&gt;
    &lt;p&gt;
        &lt;desig value="34" inline="true"&gt;34&lt;/desig&gt;
        &lt;text&gt;Deux collègues de notre Cour ont déjà circonscrit l'infraction commise avec violence
            comme étant celle au cours de laquelle il y a eu l'utilisation d'une force intense,
            extrême et brutale [Voir Note 2 ci-dessous].&lt;/text&gt;
    &lt;/p&gt;
    &lt;hrule/&gt;
    ...
&lt;/pgrp&gt;
</pre>

            <section>
                <title>Changes</title>
                <p>2015-03-17: <ph id="change_20150317_AK">An attribute
                            <targetxml>@inline</targetxml> get added with
                            <targetxml>desig</targetxml> element even when the
                            source<sourcexml>pnum</sourcexml> is not having that
                            attribute<sourcexml>@inline</sourcexml> Applicable on CA12
                    only.</ph></p>
                <p>2015-02-24: <ph id="change_20150224_AK">Example updated as per new rule an
                        attribute <targetxml>@inline</targetxml>get added with
                            <targetxml>desig</targetxml>element when the
                            source<sourcexml>pnum</sourcexml>is not having that
                            attribute<sourcexml>@inline</sourcexml>
                    </ph></p>
                <p>2014-07-31: <ph id="change_20140731_PS">Updated target mapping and snippet, R4.5
                        Issue #1764, this immediately applies to CA12.</ph></p>
                <p>2013-01-28: <ph id="change_20130128_jd">Removed CR number to allow
                            <targetxml>hrule</targetxml> to the content model of
                            <targetxml>blockquote</targetxml></ph>.</p>
                <p>2013-01-08: <ph id="change_20130108_jd">Created.</ph></p>
            </section>
           <!-- <xsltinclusion>
                <xsl:stylesheet version="2.0">
                    <!-\- BRT: this template IS NOT in base.xsl, and exists only in CA12 ditamap. This rule conflicts with another topic in which pggrp is converted to blockquote
             (Rosetta_pgrp_searchtype-LxAdv-blockquote.dita). In this latter conversion, the template is in base.xsl -\->
                    <xsl:template match="pgrp[@searchtype = 'QUOTED-TEXT']">
                        <xsl:element name="pgrp">
                            <xsl:apply-templates/>
                        </xsl:element>
                    </xsl:template>
                </xsl:stylesheet>
            </xsltinclusion>-->
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated (although the DITA file already has embedded XSLT).  Remove this comment after manual development complete!  (also remove the embedded XSLT within the DITA above) @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_pgrp_searchtype-LxAdv-pgrp.dita  -->
    <!--<xsl:message>Rosetta_pgrp_searchtype-LxAdv-pgrp.xsl requires manual development!</xsl:message> -->

    <!-- BRT: this template IS NOT in base.xsl, and exists only in CA12 ditamap. This rule conflicts with another topic in which pggrp is converted to blockquote
             (Rosetta_pgrp_searchtype-LxAdv-blockquote.dita). In this latter conversion, the template is in base.xsl -->
    <xsl:template match="pgrp[@searchtype = 'QUOTED-TEXT']">
        <xsl:element name="pgrp">
            <xsl:apply-templates/>
        </xsl:element>
    </xsl:template>

</xsl:stylesheet>
