<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	version="2.0">
	<dita:topic>
		<dita:body><dita:section>refpt child of
			leg:level/leg:level-vrnt/leg:heading/desig/designum to admindoc:level/ref:anchor or
			primlaw:level/ref:anchor id-CCCC-10445
	
		
			If refpt comes within
					leg:level/leg:level-vrnt/leg:heading/desig/designum then
					ref:anchor will become the first child of
					primlaw:level or admindoc:level
				depending on the target schema.
		
		
			Source XML
			

&lt;leg:level id="WA_ACT_2011-16_PROV1"&gt;
	&lt;leg:level-vrnt leveltype="sect" searchtype="LEGISLATION" subdoc="true" toc-caption="1. Short title"&gt;
	 &lt;leg:heading&gt;
		&lt;desig searchtype="SECT-NUM"&gt;
			&lt;designum&gt;&lt;refpt id="WA_ACT_2011-16_PROV1" type="ext"/&gt;&lt;emph typestyle="bf"&gt;1.&lt;/emph&gt;&lt;/designum&gt;
		&lt;/desig&gt;
	....
	&lt;/leg:heading&gt;
 &lt;/leg:level-vrnt&gt;
&lt;/leg:level&gt;

		
		
		
			Target XML
			

&lt;primlaw:level leveltype="section" includeintoc="true" alternatetoccaption="1. Short title"&gt;
    &lt;ref:anchor id="WA_ACT_2011-16_PROV1" anchortype="global"/&gt;    
        &lt;heading&gt;
            &lt;desig value="1"&gt;&lt;emph typestyle="bf"&gt;1.&lt;/emph&gt;&lt;/desig&gt;
            ....
        &lt;/heading&gt;    
&lt;/primlaw:level&gt;
  
		
		
		
			Changes
			2012-08-30: Created. 
		</dita:section>
		</dita:body>
	</dita:topic>
	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
<!--	<xsl:message>Requires manual development!</xsl:message> 
-->	<!--
		**********************************
		Paul: this will need to be implemented in your leg:level template
		in AU08 implemented in courtrule_body.xsl
		**********************************
-->	</xsl:stylesheet>
	
