<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_copyright-to-LexisAdvance_copyright">
    <title><sourcexml>copyright</sourcexml> to  <targetxml>copyright</targetxml> <lnpid>id-CCCC-10272</lnpid></title>
    <body>
        <section>
            <p>
                <sourcexml>copyright</sourcexml> becomes <targetxml>copyright</targetxml> with optional child
                <ul>
		          <li>
		            <sourcexml>copyright.holder</sourcexml> becomes <targetxml>copyright-holder</targetxml>.
		          </li>
                </ul>
            </p>
        </section>


    <example>
		<title>Source XML</title>
		<codeblock>

&lt;copyright&gt;
    ©  
    &lt;copyright.holder&gt;Crown Copyright&lt;/copyright.holder&gt; 
&lt;/copyright&gt;

		</codeblock>
    </example>
	
    <example>
		<title>Target XML</title>
		<codeblock>

&lt;copyright&gt;
     ©  
     &lt;copyright-holder&gt;Crown Copyright&lt;/copyright-holder&gt; 
&lt;/copyright&gt;

		</codeblock>
    </example>

        <example>
            <title>Source XML</title>
            <codeblock>

&lt;copyright&gt;
   Copyright © Times Newspapers Ltd and Reed Elsevier (UK) Ltd 2007
&lt;/copyright&gt;

		</codeblock>
        </example>
        
        <example>
            <title>Target XML</title>
            <codeblock>

&lt;copyright&gt;
     Copyright © Times Newspapers Ltd and Reed Elsevier (UK) Ltd 2007
&lt;/copyright&gt;

		</codeblock>
        </example>
        
        <section>
    		<title>Changes</title>
            <p>2013-06-17: <ph id="change_20130617_SP">Added an example when <sourcexml>copyright-holder</sourcexml> is not present in the source.</ph></p>
        </section>
        
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_copyright-LxAdv-copyright.dita  -->
	 

	<!-- Vikas Rohilla : Initial updated may be changed if required-->
	<xsl:template match="copyright">
		<copyright>
			<xsl:apply-templates select="@* | node()"/>
		</copyright>

	</xsl:template>

	<xsl:template match="copyright.holder">
		<copyright-holder>
			<xsl:apply-templates select="@* | node()"/>
		</copyright-holder>
	</xsl:template>

	
</xsl:stylesheet>