<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_level-to-LexisAdvance_section">
  <title><sourcexml>level</sourcexml>to <targetxml>section</targetxml> <lnpid>id-IN08-38212</lnpid></title>
  <body>
    <p>
      <sourcexml>level</sourcexml> becomes <targetxml>section</targetxml>. <ul>
        <li><sourcexml>level/@leveltype</sourcexml> becomes
            <targetxml>section/@sectiontype</targetxml></li>
        <li><sourcexml>level/@subdoc</sourcexml> becomes
            <targetxml>section/@includeintoc</targetxml></li>
        <li><sourcexml>level/@toc-caption</sourcexml> becomes
            <targetxml>section/@alternatetoccaption</targetxml></li>
      </ul>
      <note> If any source attribute comes EMPTY inside the <sourcexml>level</sourcexml> (i.e.
          <sourcexml>@toc-caption</sourcexml>) then conversion needs to be dropped in target. </note>
      <pre>
&lt;DIGESTDOC&gt;
  &lt;dig:body&gt;
    &lt;level id="MLJ_VOL7.0503.subpara0" leveltype="subpara0" toc-caption="" subdoc="false"&gt;
      &lt;bodytext&gt;...
      &lt;/bodytext&gt;
    &lt;/level&gt;
  &lt;/dig:body&gt;
&lt;/DIGESTDOC&gt;

<b>Becomes</b>
&lt;casedigest:casedigest&gt;
  &lt;casedigest:body&gt;
    &lt;section sectiontype="subpara0" includeintoc="false"&gt;
      &lt;bodytext&gt;...
      &lt;/bodytext&gt;
    &lt;/section&gt;
  &lt;/casedigest:body&gt;  
&lt;/casedigest:casedigest&gt;
</pre>
    </p>
    <section>
      <title>Changes</title>
      <p>2016-06-16: <ph id="change_20160616_HP">Created.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-IN\IN08-Digest\Rosetta_level-to-LexisAdvance_section.dita  -->
	<xsl:message>Rosetta_level-to-LexisAdvance_section.xsl requires manual development!</xsl:message> 

	<xsl:template match="level">

		<!--  Original Target XPath:  section   -->
		<section>
			<xsl:apply-templates select="@* | node()"/>
		</section>

	</xsl:template>

	<xsl:template match="level/@leveltype">

		<!--  Original Target XPath:  section/@sectiontype   -->
		<section>
			<xsl:attribute name="sectiontype">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</section>

	</xsl:template>

	<xsl:template match="level/@subdoc">

		<!--  Original Target XPath:  section/@includeintoc   -->
		<section>
			<xsl:attribute name="includeintoc">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</section>

	</xsl:template>

	<xsl:template match="level/@toc-caption">

		<!--  Original Target XPath:  section/@alternatetoccaption   -->
		<section>
			<xsl:attribute name="alternatetoccaption">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</section>

	</xsl:template>

	<xsl:template match="@toc-caption">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>