<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_legfragment-toc-to-LexisAdvance_primlaw.excerpt-primlaw.bodytext-toc">    
    <title><sourcexml>legfragment/toc</sourcexml> to <targetxml>primlaw:excerpt/primlaw:bodytext/toc</targetxml> <lnpid>id-CCCC-10391</lnpid></title>
    <body>
        <section>
            <p>
                <b>legfragment/toc:</b> Handling of toc when it occurs within
                legfragment:
                <codeblock>
&lt;blockquote&gt;
            &lt;legfragment&gt;
             &lt;toc&gt;
            &lt;heading&gt;
                &lt;title&gt;
                    &lt;emph typestyle="bf"&gt;Table of sections&lt;/emph&gt;
                &lt;/title&gt;
            &lt;/heading&gt;
    &lt;toc-entry&gt;
        &lt;heading&gt;
            &lt;desig&gt;
                &lt;designum&gt;84-5&lt;/designum&gt;
            &lt;/desig&gt;
            &lt;title&gt;Meaning of 
                &lt;emph typestyle="it"&gt;personal services income&lt;/emph&gt;&lt;/title&gt;
        &lt;/heading&gt;
    &lt;/toc-entry&gt;
    &lt;toc-entry&gt;
        &lt;heading&gt;
            &lt;desig&gt;
                &lt;designum&gt;84-10&lt;/designum&gt;
            &lt;/desig&gt;
            &lt;title&gt;This Part does not imply that individuals are employees&lt;/title&gt;
        &lt;/heading&gt;
    &lt;/toc-entry&gt;
        &lt;/toc&gt;
     &lt;/legfragment&gt;
&lt;/blockquote&gt;

 </codeblock>
                <b>Becomes</b>
                
                <codeblock>
&lt;primlaw:excerpt&gt;
            &lt;primlaw:bodytext&gt;            
             &lt;toc&gt;
            &lt;heading&gt;
                &lt;title&gt;
                    &lt;emph typestyle="bf"&gt;Table of sections&lt;/emph&gt;
                &lt;/title&gt;
            &lt;/heading&gt;
    &lt;toc-entry&gt;
        &lt;heading&gt;
            &lt;desig&gt;84-5&lt;/desig&gt;
            &lt;title&gt;Meaning of &lt;emph typestyle="it"&gt;personal services income&lt;/emph&gt;&lt;/title&gt;
        &lt;/heading&gt;
    &lt;/toc-entry&gt;
    &lt;toc-entry&gt;
        &lt;heading&gt;
            &lt;desig&gt;84-10&lt;/desig&gt;
            &lt;title&gt;This Part does not imply that individuals are employees&lt;/title&gt;
        &lt;/heading&gt;
    &lt;/toc-entry&gt;
      &lt;/toc&gt;
     &lt;/primlaw:bodytext&gt;
  &lt;/primlaw:excerpt&gt;
    
      </codeblock>
            </p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_legfragment-toc-to-LxAdv-primlaw.excerpt-primlaw.bodytext-toc.dita  -->
	 
    <!-- Vikas Rohilla : Initial updated may be changed if required-->
	<xsl:template match="legfragment/toc">
		<primlaw:excerpt>
			<primlaw:bodytext>
				<toc>
					<xsl:apply-templates select="@* | node()"/>
				</toc>
			</primlaw:bodytext>
		</primlaw:excerpt>

	</xsl:template>

</xsl:stylesheet>