<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="RU02-p">
    <title>p <lnpid>id-RU02-32051</lnpid>
    </title>

    <body>
        <p>
            <sourcexml>p</sourcexml> becomes <targetxml>p</targetxml>. </p>

        <pre>&lt;lnv:TEXT-1&gt;
        &lt;lnvxe:bodytext&gt;
            &lt;p&gt;
                &lt;lnvxe:text&gt;The general rules on property shall also apply to animals, unless
                    otherwise prescribed by the Law or other legal acts.&lt;/lnvxe:text&gt;
            &lt;/p&gt;
            &lt;p&gt;
                &lt;lnvxe:text&gt;The exercise of such rights in respect of animals shall not involve acts
                    of cruelty to animals that contradict the principles of humanity.&lt;/lnvxe:text&gt;
            &lt;/p&gt;
        &lt;/lnvxe:bodytext&gt;
&lt;/lnv:TEXT-1&gt;

<b>Becomes</b>


&lt;statcode:body&gt;  
   &lt;primlaw:level leveltype="unclassified"&gt;
       &lt;primlaw:bodytext&gt;
            &lt;p&gt;
            &lt;text&gt;The general rules on property shall also apply to animals, unless otherwise
                prescribed by the Law or other legal acts.&lt;/text&gt;
            &lt;/p&gt;
            &lt;p&gt;
            &lt;text&gt;The exercise of such rights in respect of animals shall not involve acts of
                cruelty to animals that contradict the principles of humanity.&lt;/text&gt;
            &lt;/p&gt;
       &lt;/primlaw:bodytext&gt;
   &lt;/primlaw:level&gt;
&lt;/statcode:body&gt;</pre>

        <section>
            <title>Changes</title>
            <p>Created.</p>
        </section>
    </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\RU02\RU02-p.dita  -->
	<xsl:message>RU02-p.xsl requires manual development!</xsl:message> 

	<xsl:template match="p">

		<!--  Original Target XPath:  p   -->
		<p>
			<xsl:apply-templates select="@* | node()"/>
		</p>

	</xsl:template>

</xsl:stylesheet>