<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:statcode="http://www.lexisnexis.com/xmlschemas/content/legal/statutorycode/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Case-Summaries_Introduction">
    <title>Introduction <lnpid>id-RU02-32007</lnpid>
    </title>
    <shortdesc>This Conversion Instructions describes the conversion of the CRE DIGESTDOC DTD to
            <b>statcode Version 4.0_PROD</b> schema.</shortdesc>
    <body>

        <p>Russia COMMENTARYDOC-LDC based samples are identified using the root element
                <sourcexml>COMMENTARYDOC-LDC</sourcexml>
        </p>

        <section>
            <sourcexml>COMMENTARYDOC-LDC</sourcexml> becomes
                <targetxml>statcode:statcode</targetxml>. </section>

        <note>Elements <targetxml>statcode:head</targetxml>, <targetxml>statcode:body</targetxml>
            and <targetxml>doc:metadata</targetxml> are created as required children of root element
            statcode:statcode during conversion.</note>

        <pre>
&lt;COMMENTARYDOC-LDC xmlns:lnci="http://www.lexis-nexis.com/lnci"
   ......
    &lt;lndocmeta:docinfo&gt;
        &lt;lndocmeta:lnlni lnlni="59FC-RSM1-JC1N-Y18H-00000-00"/&gt;
        &lt;lndocmeta:lnuserlni lnuserlni="59FC-RSM1-JC1N-Y18H"/&gt;
        ......
    &lt;/lndocmeta:docinfo&gt;
    .....
&lt;/COMMENTARYDOC-LDC&gt;


<b>Becomes</b>

&lt;statcode:statcode xml:lang="en-RU"&gt;

    &lt;statcode:head&gt; ... &lt;/statcode:head&gt;
    &lt;statcode:body&gt; ... &lt;/statcode:body&gt;
    &lt;doc:metadata&gt; ... &lt;/doc:metadata&gt;

&lt;/statcode:statcode&gt;

      </pre>

        <p><b>Note:</b></p>
        <p>Source elements and attributes are highlighted like this:
                <sourcexml>SOURCEXML</sourcexml></p>
        <p>Target elements and attributes are highlighted like this:
                <targetxml>TARGETXML</targetxml></p>



    </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\RU02\RU02-Introduction.dita  -->
	<xsl:message>RU02-Introduction.xsl requires manual development!</xsl:message> 

	<xsl:template match="COMMENTARYDOC-LDC">

		<!--  Original Target XPath:  statcode:statcode   -->
		<statcode:statcode>
			<xsl:apply-templates select="@* | node()"/>
		</statcode:statcode>

	</xsl:template>

	<xsl:template match="SOURCEXML">

		<!--  Original Target XPath:  TARGETXML   -->
		<TARGETXML>
			<xsl:apply-templates select="@* | node()"/>
		</TARGETXML>

	</xsl:template>

</xsl:stylesheet>