<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="ST11_Commentary_leg.histnote2-target">
  <title>Target XML</title>
  <body>
    <codeblock>

&lt;note notetype="historical"&gt;
 &lt;bodytext&gt;
  &lt;p&gt;&lt;text&gt;&amp;#x005B;199&amp;#x005D;&lt;/text&gt;&lt;/p&gt;
 &lt;/bodytext&gt;
&lt;/note&gt;
    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Seclaw\ST11_Commentary_leg.histnote2-target.dita  -->
	<xsl:message>ST11_Commentary_leg.histnote2-target.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>