<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="ST11_Commentary_level-bodytext">
  <title>level and bodytext <lnpid>id-ST11-37823</lnpid></title>
  <body>
    <section>
      <p><sourcexml>level[@leveltype]</sourcexml> becomes
          <targetxml>seclaw:level[@leveltype]</targetxml>.</p><p>Child
          <sourcexml>bodytext</sourcexml> becomes
      <targetxml>seclaw:bodytext</targetxml>.</p></section>
    <section><p><u>Special Rule for <sourcexml>@leveltype</sourcexml></u>. Value of
          <sourcexml>@leveltype</sourcexml> carries through unchanged except for the following
        special mapping: When content of <sourcexml>level/heading/title</sourcexml> is "All
        Questions" (without quotes) then <sourcexml>level[@leveltype="title"]</sourcexml> becomes
          <targetxml>seclaw:level[@leveltype="questionanswergroup"]</targetxml>. This use case is
        known to occur in directory/dpsi 0NF9.</p></section>
    <note><targetxml>seclaw:bodytext</targetxml> is a required child of
        <targetxml>seclaw:level</targetxml>. Generate <targetxml>seclaw:bodytext</targetxml> if
        <sourcexml>bodytext</sourcexml> not present. Usual scenario is
        <sourcexml>level/level</sourcexml> becomes
      <targetxml>seclaw:level/seclaw:bodytext/seclaw:level/seclaw:bodytext</targetxml>.</note>
    <pre>
        <b>EXAMPLE</b>
            
<b><i>Source XML</i></b>

&lt;COMMENTARYDOC&gt;
  &lt;comm:body&gt;
    &lt;level leveltype="topic"&gt;
      &lt;heading&gt;
        &lt;title&gt;Albania&lt;/title&gt;
      &lt;/heading&gt;
      &lt;level leveltype="title"&gt;
        &lt;heading&gt;
          &lt;title&gt;Construction 2012&lt;/title&gt;
        &lt;/heading&gt;
        &lt;level leveltype="title"&gt;
          &lt;heading&gt;
            &lt;title&gt;All Questions&lt;/title&gt;
          &lt;/heading&gt;
          &lt;level leveltype="question"&gt;
            &lt;bodytext&gt;
              &lt;p&gt;
                &lt;text&gt;Must foreign designers...control the joint venture?&lt;/text&gt;
              &lt;/p&gt;
            &lt;/bodytext&gt;
          &lt;/level&gt;
          &lt;level leveltype="answer"&gt;
            &lt;bodytext&gt;
              &lt;p&gt;
                &lt;text&gt;Foreign designers or contractors do not...&lt;/text&gt;
              &lt;/p&gt;
            &lt;/bodytext&gt;
          &lt;/level&gt;
        &lt;/level&gt;
      &lt;/level&gt;
    &lt;/level&gt;
  &lt;/comm:body&gt;
&lt;/COMMENTARYDOC&gt;
 
<b><i>Target XML</i></b>

&lt;seclaw:seclaw&gt;
  &lt;seclaw:body&gt;
    &lt;seclaw:level leveltype="topic"&gt;
      &lt;heading&gt;
        &lt;title&gt;Albania&lt;/title&gt;
      &lt;/heading&gt;
      &lt;seclaw:bodytext&gt;
        &lt;seclaw:level leveltype="title"&gt;
          &lt;heading&gt;
            &lt;title&gt;Construction 2012&lt;/title&gt;
          &lt;/heading&gt;
          &lt;seclaw:bodytext&gt;
            &lt;seclaw:level leveltype="questionanswergroup"&gt;
              &lt;heading&gt;
                &lt;title&gt;All Questions&lt;/title&gt;
              &lt;/heading&gt;
              &lt;seclaw:bodytext&gt;
                &lt;seclaw:level leveltype="question"&gt;
                  &lt;seclaw:bodytext&gt;
                    &lt;p&gt;
                      &lt;text&gt;Must foreign designers...control the joint
                            venture?&lt;/text&gt;
                    &lt;/p&gt;
                  &lt;/seclaw:bodytext&gt;
                &lt;/seclaw:level&gt;
                &lt;seclaw:level leveltype="answer"&gt;
                  &lt;seclaw:bodytext&gt;
                    &lt;p&gt;
                      &lt;text&gt;Foreign designers or contractors do
                      not...&lt;/text&gt;
                    &lt;/p&gt;
                  &lt;/seclaw:bodytext&gt;
                &lt;/seclaw:level&gt;
              &lt;/seclaw:bodytext&gt;
            &lt;/seclaw:level&gt;
          &lt;/seclaw:bodytext&gt;
        &lt;/seclaw:level&gt;
      &lt;/seclaw:bodytext&gt;
    &lt;/seclaw:level&gt;
  &lt;/seclaw:body&gt;
&lt;/seclaw:seclaw&gt;

                </pre>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Seclaw\ST11_Commentary_level-bodytext.dita  -->
	<xsl:message>ST11_Commentary_level-bodytext.xsl requires manual development!</xsl:message> 

	<xsl:template match="level[@leveltype]">

		<!--  Original Target XPath:  seclaw:level[@leveltype]   -->
		<seclaw:level>
			<xsl:apply-templates select="@* | node()"/>
		</seclaw:level>

	</xsl:template>

	<xsl:template match="bodytext">

		<!--  Original Target XPath:  seclaw:bodytext   -->
		<seclaw:bodytext>
			<xsl:apply-templates select="@* | node()"/>
		</seclaw:bodytext>

	</xsl:template>

	<xsl:template match="@leveltype">

		<!--  Original Target XPath:  seclaw:level[@leveltype="questionanswergroup"]   -->
		<seclaw:level>
			<xsl:apply-templates select="@* | node()"/>
		</seclaw:level>

	</xsl:template>

	<xsl:template match="level/heading/title">

		<!--  Original Target XPath:  seclaw:level[@leveltype="questionanswergroup"]   -->
		<seclaw:level>
			<xsl:apply-templates select="@* | node()"/>
		</seclaw:level>

	</xsl:template>

	<xsl:template match="level[@leveltype=&#34;title&#34;]">

		<!--  Original Target XPath:  seclaw:level[@leveltype="questionanswergroup"]   -->
		<seclaw:level>
			<xsl:apply-templates select="@* | node()"/>
		</seclaw:level>

	</xsl:template>

	<xsl:template match="level/level">

		<!--  Original Target XPath:  seclaw:level/seclaw:bodytext/seclaw:level/seclaw:bodytext   -->
		<seclaw:level>
			<seclaw:bodytext>
				<seclaw:level>
					<seclaw:bodytext>
						<xsl:apply-templates select="@* | node()"/>
					</seclaw:bodytext>
				</seclaw:level>
			</seclaw:bodytext>
		</seclaw:level>

	</xsl:template>

</xsl:stylesheet>