<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="ST11_Commentary_levelprelim-abstract">
  <title>levelprelim and abstract <lnpid>id-ST11-37827</lnpid></title>
  <body>    
      <p><sourcexml>levelprelim</sourcexml> becomes
        <targetxml>seclaw:prelim</targetxml>.</p><p>Child <sourcexml>abstract</sourcexml> becomes
          <targetxml>abstract/bodytext</targetxml>.</p>
    <pre>
        <b>EXAMPLE</b>
            
<b><i>Source XML</i></b>

&lt;COMMENTARYDOC&gt;
  &lt;comm:body&gt;
    &lt;level leveltype="title"&gt;
      &lt;heading&gt;
        &lt;title&gt;Equality and human rights - overview&lt;/title&gt;
      &lt;/heading&gt;
      &lt;levelprelim&gt;
        &lt;abstract&gt;
          &lt;p&gt;
            &lt;text&gt;This document is an overview of...&lt;/text&gt;
          &lt;/p&gt;
        &lt;/abstract&gt;
      &lt;/levelprelim&gt;
      &lt;bodytext&gt;
        &lt;p&gt;
          &lt;text&gt;In the UK, the legislation governing...&lt;/text&gt;
        &lt;/p&gt;
      &lt;/bodytext&gt;
    &lt;/level&gt;
  &lt;/comm:body&gt;
&lt;/COMMENTARYDOC&gt;
 
<b><i>Target XML</i></b>

&lt;seclaw:seclaw&gt;
  &lt;seclaw:body&gt;
    &lt;seclaw:level leveltype="title"&gt;
      &lt;heading&gt;
        &lt;title&gt;Equality and human rights - overview&lt;/title&gt;
      &lt;/heading&gt;
      &lt;seclaw:prelim&gt;
        &lt;abstract&gt;
          &lt;bodytext&gt;
            &lt;p&gt;
              &lt;text&gt;This document is an overview of...&lt;/text&gt;
            &lt;/p&gt;
          &lt;/bodytext&gt;
        &lt;/abstract&gt;
      &lt;/seclaw:prelim&gt;
      &lt;seclaw:bodytext&gt;
        &lt;p&gt;
          &lt;text&gt;In the UK, the legislation governing...&lt;/text&gt;
        &lt;/p&gt;
      &lt;/seclaw:bodytext&gt;
    &lt;/seclaw:level&gt;
  &lt;/seclaw:body&gt;
&lt;/seclaw:seclaw&gt;

                </pre>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Seclaw\ST11_Commentary_levelprelim-abstract.dita  -->
	<xsl:message>ST11_Commentary_levelprelim-abstract.xsl requires manual development!</xsl:message> 

	<xsl:template match="levelprelim">

		<!--  Original Target XPath:  seclaw:prelim   -->
		<seclaw:prelim>
			<xsl:apply-templates select="@* | node()"/>
		</seclaw:prelim>

	</xsl:template>

	<xsl:template match="abstract">

		<!--  Original Target XPath:  abstract/bodytext   -->
		<abstract>
			<bodytext>
				<xsl:apply-templates select="@* | node()"/>
			</bodytext>
		</abstract>

	</xsl:template>

</xsl:stylesheet>