<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet 
  xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="courtorder-note-chof-case.headnote">
  <title>note <lnpid>id-UK04-27632</lnpid></title>
  <body>
    <p>The element <sourcexml>case:headnote/note</sourcexml> becomes <targetxml>/courtorder:courtorder/courtorder:body/section/bodytext/note</targetxml> with source attribute <sourcexml>note/@notetype</sourcexml> becoming target attribute <targetxml>note/@notetype</targetxml>. Then a child element <targetxml>bodytext</targetxml> is created within note, and the <sourcexml>note</sourcexml> element's children are converted as described in the <b>"General Markup"</b> section and placed within the created <targetxml>bodytext</targetxml>.
    </p>
    <p><b>Explanation regarding this conversion instruction.</b> These notes currently always have a <sourcexml>note</sourcexml> that has a <sourcexml>@notetype</sourcexml> attribute with a value of "commentary". According to the LBU (Hanna) these notes should not be in the <sourcexml>case:headnote</sourcexml> element (data error), but instead should be part of <sourcexml>case:content</sourcexml>. Thus, they are being moved to <targetxml>courtorder:body</targetxml> by this conversion instruction.</p>
    <note>A <sourcexml>case:headnote/note</sourcexml> element often occurs in a document that also contains <sourcexml>case:judgments/note</sourcexml> elements. A separate <targetxml>courtorder:body/section</targetxml> is created for each separate <sourcexml>note</sourcexml>, and the child <targetxml>bodytext/note/bodytext</targetxml> elements are created within this <targetxml>section</targetxml>. See the subtopic <xref href="case.judgments-note-instruction.dita"/> for an example regarding this scenario.</note>
    
    <section>
      <title>Source XML </title>
      <codeblock>

&lt;case:headnote&gt;
&lt;!--...--&gt;
  &lt;note notetype="commentary"&gt;
    &lt;pgrp&gt;
      &lt;p&gt;
        &lt;text&gt;The following Practice Direction has been issued by Sir Igor Judge, President of
          the Queens Bench Division with the agreement of the Master of the Rolls.&lt;/text&gt;
      &lt;/p&gt;
    &lt;/pgrp&gt;
  &lt;/note&gt;
&lt;/case:headnote&gt;

      </codeblock>
    </section>
      <section>
        <title>Target XML </title>
        <codeblock>

&lt;courtorder:courtorder&gt;
&lt;!--...--&gt;
  &lt;courtorder:body&gt;
    &lt;section&gt;
      &lt;bodytext&gt;
        &lt;note notetype="commentary"&gt;
          &lt;bodytext&gt;
            &lt;pgrp&gt;
              &lt;p&gt;
                &lt;text&gt;The following Practice Direction has been issued by Sir Igor Judge, President of
                  the Queens Bench Division with the agreement of the Master of the Rolls.&lt;/text&gt;
              &lt;/p&gt;
            &lt;/pgrp&gt;
          &lt;/bodytext&gt;
        &lt;/note&gt;
      &lt;/bodytext&gt;
    &lt;/section&gt;

        </codeblock>
      </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK04_CourtOrder\note-chof-case.headnote.dita  -->
	<!--<xsl:message>note-chof-case.headnote.xsl requires manual development!</xsl:message>--> 

	<xsl:template match="case:headnote/note">
				<section>
					<bodytext>
						<note>
						  <xsl:apply-templates select="@* | heading|refpt"/>
						  <xsl:if test="node() except (heading, refpt)">
						    <bodytext>
						      <xsl:apply-templates select="node() except (heading, refpt)"/>
						    </bodytext>
						  </xsl:if>
						</note>
					</bodytext>
				</section>

	</xsl:template>

  <!--<xsl:template match="case:headnote/note/@notetype">
		<xsl:attribute name="notetype">
			<xsl:value-of select="."/>
		</xsl:attribute>
	</xsl:template>-->
</xsl:stylesheet>