<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0"
    exclude-result-prefixes="dita">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK09LegalNews_level">
        <title>level <lnpid>id-UK09-29019</lnpid></title>
        <body>
            <p><sourcexml>level</sourcexml> becomes <targetxml>section</targetxml>.</p>
            <p>If <sourcexml>level</sourcexml> has a <sourcexml>@leveltype</sourcexml> attribute, it
                should be suppressed</p>
            <example>
                <title>Source XML</title>
                <codeblock> &lt;jrnl:bodytext searchtype="ARTICLE"&gt; &lt;level&gt;
                    &lt;bodytext&gt; &lt;pgrp&gt; &lt;p&gt; &lt;text&gt;It has often been said
                    &amp;#x2014; particularly by the media &amp;#x2014; that the Internet can be a
                    potentially dangerous place for children...&lt;/text&gt; &lt;/p&gt;
                    &lt;/pgrp&gt; &lt;/bodytext&gt; &lt;/level&gt; &lt;level&gt; &lt;heading&gt;
                    &lt;title&gt; &lt;emph typestyle="bf"&gt;Dangers on the Internet&lt;/emph&gt;
                    &lt;/title&gt; &lt;/heading&gt; &lt;bodytext&gt; &lt;pgrp&gt; &lt;p&gt;
                    &lt;text&gt;In addition to parents and teachers, everyone in the criminal
                    justice system should be aware of the potential dangers, and children need to
                    know how they should conduct their time spent online...&lt;/text&gt; &lt;/p&gt;
                    &lt;/pgrp&gt; &lt;/bodytext&gt; &lt;/level&gt; ... &lt;/jrnl:bodytext&gt; </codeblock>
                <title>Target XML</title>
                <codeblock> &lt;nitf:body.content&gt; &lt;bodytext&gt; &lt;section&gt;
                    &lt;bodytext&gt; &lt;pgrp&gt; &lt;p&gt; &lt;text&gt;It has often been said
                    &amp;#x2014; particularly by the media &amp;#x2014; that the Internet can be a
                    potentially dangerous place for children...&lt;/text&gt; &lt;/p&gt;
                    &lt;/pgrp&gt; &lt;/bodytext&gt; &lt;/section&gt; &lt;section&gt; &lt;heading&gt;
                    &lt;title&gt; &lt;emph typestyle="bf"&gt;Dangers on the Internet&lt;/emph&gt;
                    &lt;/title&gt; &lt;/heading&gt; &lt;bodytext&gt; &lt;pgrp&gt; &lt;p&gt;
                    &lt;text&gt;In addition to parents and teachers, everyone in the criminal
                    justice system should be aware of the potential dangers, and children need to
                    know how they should conduct their time spent online...&lt;/text&gt; &lt;/p&gt;
                    &lt;/pgrp&gt; &lt;/bodytext&gt; &lt;/section&gt; ... &lt;/bodytext&gt;
                    &lt;/nitf:body.content&gt; </codeblock>
            </example>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK09-LegalNews\UK09LegalNews_level.dita  -->
    <!--<xsl:message>UK09LegalNews_level.xsl requires manual development!</xsl:message> 
-->
    <xsl:template match="level">
        <section>
            <xsl:apply-templates select="@* | node()"/>
        </section>
        <xsl:apply-templates select="bodytext/footnotegrp[not(footnote)]"/>
    </xsl:template>
    
    <xsl:template match="footnotegrp[not(footnote)]">
        <section>
            <xsl:apply-templates select="@* | heading"/>
            <bodytext>
                <xsl:apply-templates select="node() except(heading)"/>
            </bodytext>
        </section>
    </xsl:template>
    
    <xsl:template match="@leveltype"/>
</xsl:stylesheet>
