<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" 
    xmlns:classify="http://www.lexisnexis.com/xmlschemas/content/shared/classification/1/" 
    xmlns:source_dict="http://www.lexis-nexis.com/glp/dict" xmlns:dict="urn:x-lexisnexis:content:dict:sharedservices:1"
    xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    version="2.0" exclude-result-prefixes="dita docinfo source_dict xsi">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="dictionary-Introduction">

    <title>Introduction <lnpid>id-UK10-29221</lnpid></title>
    <shortdesc>This document describes the conversion of UK dictionary content to the LexisAdvance
        dictionary 2.5 PROD schema.</shortdesc>

    <body>

        <section>
            <title>Root Element</title>
            <p>
                <sourcexml>DICTIONARYDOC</sourcexml> becomes <targetxml>dict:dictionary</targetxml>. </p>
            <p><targetxml>dict:head</targetxml>, <targetxml>dict:body</targetxml>, and
                    <targetxml>doc:metadata</targetxml> are created as required children of
                    <targetxml>dict:dictionary</targetxml>.</p>
        </section>


        <section>
            <title>Notes</title>
            <p>The following information is meant to help the user understand the conventions used
                in this document.</p>
            <p>Source elements and attributes are highlighted like this: <sourcexml>XML
                    SOURCE</sourcexml></p>
            <p>Target elements and attributes are highlighted like this: <targetxml>XML
                    TARGET</targetxml></p>
            <p>Verify content of following target attributes: <ul>
                    <li><sourcexml>@month</sourcexml> becomes <targetxml>@month</targetxml> is
                        between 01-12. Any numbers outside this range, do not output a
                            <targetxml>@month</targetxml>.</li>
                    <li><sourcexml>@day</sourcexml> becomes <targetxml>@day</targetxml> is between
                        01-31. Any numbers outside this range, do not output
                            <targetxml>@day</targetxml>.</li>
                    <li><sourcexml>@year</sourcexml> becomes <targetxml>@year</targetxml> is 4
                        digits in length. Any other lengths, do not output
                            <targetxml>@year</targetxml>.</li>
                </ul>
            </p>
        </section>
        <section>
            <title>Changes</title>
            <p>2015-01-05: <ph id="change_20150105_jm2">Updated to latest version of schema (2.5 PROD).</ph></p>
            <p>2015-01-05: <ph id="change_20150105_jm">Note that the following module has been added
                    to the Metadata section: <sourcexml>docinfo:topiccodes</sourcexml> to
                        <targetxml>classify:classification[@classscheme="docinfo:topiccodes"]</targetxml>
                    (id-CCCC-10306). Data are new for UK10 in Dec 2014 redelivery. R4.5 Content
                    Issue 2111.</ph>.</p>
            <p>2013-08-21: <ph id="change_20130821_rj">Updated to latest version of schema (2.2
                    PROD).</ph></p>
            <p>2013-07-18: <ph id="change_20130718_rj">Updated to latest version of schema (2.1
                    PROD).</ph></p>
            <p>2013-05-13: <ph id="change_20130513_rj">Updated to latest version of schema (2.0
                    PROD).</ph></p>
            <p>2013-01-30: <ph id="change_20130130_rj">Created.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK10_Dictionary\dictionary-Introduction.dita  -->
    
    
    <xsl:param name="outputSchemaLoc"
        select="'urn:x-lexisnexis:content:dict:sharedservices:1 sch_dictionary.xsd'"/>
    
    <xsl:template match="DICTIONARYDOC">
        <dict:dictionary>
            <xsl:call-template name="generateNSGlobalBindings"/>
            <xsl:attribute name="xsi:schemaLocation" select="$outputSchemaLoc"/>
            <xsl:call-template name="xml_lang"/>
            <xsl:apply-templates select="@*"/>
            <dict:head>
                <xsl:apply-templates select="source_dict:body/heading"/>
            </dict:head>
            <xsl:apply-templates select="source_dict:body"/>
            <doc:metadata>
                <xsl:apply-templates select="docinfo"/>
            </doc:metadata>
        </dict:dictionary>
        
        
    </xsl:template>
    
    
    
    <!-- suppress Rosetta-dtd specific atts -->
    
    <xsl:template match="DICTIONARYDOC/@xml:lang"/>
    <xsl:template match="DICTIONARYDOC/@version"/>
    <xsl:template match="DICTIONARYDOC/@versionminor"/>
    
    

</xsl:stylesheet>