<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
  xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  xmlns:dig="http://www.lexis-nexis.com/glp/dig" xmlns:abstract="urn:x-lexisnexis:content:abstract:sharedservices:1" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita dig">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK11_DA_references">
  <title>references <lnpid>id-UK11DA-29440</lnpid></title>
  <body>
    <section><p><sourcexml>references[@referencetype]</sourcexml> becomes
          <targetxml>abstract:body/abstract:references/bodytext/ref:relatedrefs[@referencetype]/bodytext</targetxml>.</p>
      <note>Create only one <targetxml>abstract:references/bodytext</targetxml> container for
        multiple <targetxml>ref:relatedrefs</targetxml>.</note></section>

    <pre>
              <b><i>Example</i></b>
      
<b><i>SOURCE XML</i></b>                  
&lt;dig:body&gt;
  &lt;dig:info&gt;
    &lt;references referencetype="legislation"&gt;
       &lt;h&gt;Related Legislation&lt;/h&gt;
       &lt;p&gt;
          &lt;text&gt;Family Law Reform Act 1969&lt;/text&gt;
       &lt;/p&gt;
    &lt;/references&gt;
    &lt;references referencetype="cases"&gt;
       &lt;h&gt;Related Cases&lt;/h&gt;
       &lt;p&gt;
          &lt;text&gt;E (a minor), Re [1994] 2 FCR 709&lt;/text&gt;
       &lt;/p&gt;
    &lt;/references&gt;
  &lt;/dig:info&gt;
&lt;/dig:body&gt;
 
<b><i>TARGET XML</i></b>                  

&lt;abstract:body&gt;
  &lt;abstract:references&gt;
    &lt;bodytext&gt;
      &lt;ref:relatedrefs referencetype="legislation"&gt;
         &lt;bodytext&gt;
            &lt;h&gt;Related Legislation&lt;/h&gt;
            &lt;p&gt;
               &lt;text&gt;Family Law Reform Act 1969&lt;/text&gt;
            &lt;/p&gt;
         &lt;/bodytext&gt;
      &lt;/ref:relatedrefs&gt;
      &lt;ref:relatedrefs referencetype="cases"&gt;
         &lt;bodytext&gt;
            &lt;h&gt;Related Cases&lt;/h&gt;
            &lt;p&gt;
               &lt;text&gt;E (a minor), Re [1994] 2 FCR 709&lt;/text&gt;
            &lt;/p&gt;
         &lt;/bodytext&gt;
      &lt;/ref:relatedrefs&gt;
    &lt;/bodytext&gt;
  &lt;/abstract:references&gt;
&lt;/abstract:body&gt;
 
	</pre>
    <section>
      <title>Changes</title>
      <p>2014-10-13: <ph id="change_20141013_jm">New rule. Carry through
            <sourcexml>@referencetype</sourcexml> to target. The attribute is new in Oct 2014
          redelivery. Also added note to generate only one
            <targetxml>abstract:references</targetxml> container for multiple
            <targetxml>ref:relatedrefs</targetxml>. R4.5 Board Item 1964.</ph></p>
      <p>2013-08-30: <ph id="change_20130830_jm">Rule changed to reflect recent rosetta delivery.
          Removed special mapping for
            <sourcexml>references[@referencetype="citingdocs"]/p/text/url/remotelink</sourcexml>.
          That was the anticipated xpath. Actual delivery supplies those data as
            <sourcexml>dig:subject/url/remotelink</sourcexml>. See R4.5 Post-Iterative Testing
          UK11DA Issue 356.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK11DA-Digest-Abstract\UK11_DA_references.dita  -->
 

	<xsl:template match="references[@referencetype]">
			<abstract:references>
				<bodytext>
					<ref:relatedrefs>
						<bodytext>
							<xsl:apply-templates select="@* | node()"/>
						</bodytext>
					</ref:relatedrefs>
				</bodytext>
			</abstract:references>

	</xsl:template>

  <xsl:template match="references/@referencetype"/>


	


</xsl:stylesheet>