<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
xmlns:abstract="urn:x-lexisnexis:content:abstract:sharedservices:1" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK11_DA_level">
  <title>level <lnpid>id-UK11DA-29432</lnpid></title>
  <body>
    <section>
      <p><sourcexml>level[@leveltype]</sourcexml> becomes
          <targetxml>abstract:body/section[@sectiontype]</targetxml>.</p></section>
    <note>Maintain nesting.</note>
    <note>Value of <sourcexml>@leveltype</sourcexml> should be changed to lower case for
        <targetxml>@sectiontype</targetxml>.</note>

    <pre>
              <b><i>Example: Source XML 1</i></b>
                  

&lt;dig:body&gt;
  &lt;level leveltype="Summary"&gt;
    &lt;bodytext&gt;
      &lt;p&gt;
       &lt;text&gt;The court, in refusing to...&lt;/text&gt;
      &lt;/p&gt;
    &lt;/bodytext&gt;
    &lt;level leveltype="Section"&gt;
      &lt;heading&gt;
        &lt;title&gt;Whether to grant...&lt;/title&gt;
      &lt;/heading&gt;
      &lt;level leveltype="Subsection"&gt;
        &lt;heading&gt;
          &lt;title&gt;Other creditors&lt;/title&gt;
        &lt;/heading&gt;
        &lt;bodytext&gt;
          &lt;p&gt;
            &lt;text&gt;It was argued...&lt;/text&gt;
          &lt;/p&gt;
        &lt;/bodytext&gt;
      &lt;/level&gt;
    &lt;/level&gt;
  &lt;/level&gt;
&lt;/dig:body&gt;
 
	</pre>
    <pre>
                    
              <b><i>Example: Target XML 1</i></b>
    
&lt;abstract:body&gt;
  &lt;section sectiontype="summary"&gt;
    &lt;bodytext&gt;
      &lt;p&gt;
       &lt;text&gt;The court, in refusing to...&lt;/text&gt;
      &lt;/p&gt;
    &lt;/bodytext&gt;
    &lt;section sectiontype="section"&gt;
      &lt;heading&gt;
        &lt;title&gt;Whether to grant...&lt;/title&gt;
      &lt;/heading&gt;
      &lt;section sectiontype="subsection"&gt;
        &lt;heading&gt;
          &lt;title&gt;Other creditors&lt;/title&gt;
        &lt;/heading&gt;
        &lt;bodytext&gt;
          &lt;p&gt;
            &lt;text&gt;It was argued...&lt;/text&gt;
          &lt;/p&gt;
        &lt;/bodytext&gt;
      &lt;/section&gt;
    &lt;/section&gt;
  &lt;/section&gt;
&lt;/abstract:body&gt;

    </pre>
    <section>
      <title>Changes</title>
      <p>2013-04-08: <ph id="change_20130408_jm"><sourcexml>level</sourcexml> -
            <targetxml>section</targetxml> added to Abstract schema. Removed reference to pending
          CR.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK11DA-Digest-Abstract\UK11_DA_level.dita  -->
<!--	<xsl:message>UK11_DA_level.xsl requires manual development!</xsl:message> -->

	<xsl:template match="level">
			<section>
				<xsl:apply-templates select="@* | node()"/>
			</section>

	</xsl:template>

  <xsl:template match="level/@leveltype">
		<xsl:attribute name="sectiontype">
	<xsl:value-of select="."/>
		</xsl:attribute>
  </xsl:template>


</xsl:stylesheet>