<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet 
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
  xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK11_DN_note">
  <title>note <lnpid>id-UK11DN-29619</lnpid></title>
  <body>
    <section>
      <p><sourcexml>note[@notetype="xref"]</sourcexml> becomes
          <targetxml>marginnote/bodytext</targetxml>. In addition: </p>
      <ul>
        <li><u>Merge notes:</u> If source contains multiple adjacent
            <sourcexml>note[@notetype="xref"]</sourcexml> then place contents of all into one
            <targetxml>marginnote/bodytext</targetxml>.</li>
        <li><u>Generate</u>
          <targetxml>ref:anchor[@id="" @anchortype="local"]</targetxml> as first child of
            <targetxml>marginnote</targetxml>. Value of <targetxml>@id</targetxml> must be unique
          within the document.</li>
        <li><u>Move notes:</u> Source sequence is note before associated text. Target must be
          marginnote moved to end of associated text. That is: source has <sourcexml>p</sourcexml>
          containing <sourcexml>note</sourcexml> then <sourcexml>text</sourcexml>. Target must have
            <targetxml>p</targetxml> containing <targetxml>text</targetxml> with
            <targetxml>marginnote</targetxml> placed at end of <targetxml>text</targetxml>
          content.</li>
      </ul>
    </section>
    <note>It is expected that <sourcexml>note</sourcexml> will always have
        <sourcexml>@notetype="xref"</sourcexml>. Report to Content Architecture any occurrences of
        <sourcexml>note</sourcexml> where <sourcexml>@notetype</sourcexml> is absent or has value
      other than "xref".</note>

    <pre>
              <b><i>Example: Source XML 1</i></b>
                  

&lt;level leveltype="Summary"&gt;
  &lt;bodytext&gt;
    &lt;p&gt;
      &lt;note notetype="xref"&gt;
        &lt;p&gt;
          &lt;text&gt;White v Williams...&lt;/text&gt;
        &lt;/p&gt;
      &lt;/note&gt;
      &lt;note notetype="xref"&gt;
        &lt;p&gt;
          &lt;text&gt;Affirmed in &lt;ci:cite&gt;...&lt;/ci:cite&gt;&lt;/text&gt;
        &lt;/p&gt;
      &lt;/note&gt;
      &lt;text&gt;The court declined.&lt;/text&gt;
    &lt;/p&gt;
  &lt;/bodytext&gt;
&lt;/level&gt;
 
	</pre>
    <pre>
                    
              <b><i>Example: Target XML 1</i></b>
    
&lt;section sectiontype="summary"&gt;
  &lt;bodytext&gt;
    &lt;p&gt;
      &lt;text&gt;The court declined.&lt;marginnote&gt;
          &lt;ref:anchor id="abc" anchortype="local"/&gt;
          &lt;bodytext&gt;
            &lt;p&gt;
              &lt;text&gt;White v Williams...&lt;/text&gt;
            &lt;/p&gt;
            &lt;p&gt;
              &lt;text&gt;Affirmed in &lt;lnci:cite&gt;...&lt;/lnci:cite&gt;&lt;/text&gt;
            &lt;/p&gt;
          &lt;/bodytext&gt;
        &lt;/marginnote&gt;
      &lt;/text&gt;
    &lt;/p&gt;
  &lt;/bodytext&gt;
&lt;/section&gt;

    </pre>
    <section>
      <title>Changes</title>
      <p>2014-10-16: <ph id="change_20141016_jm">Rule changes. Removed requirement to generate
            <targetxml>text</targetxml> wrapper for <targetxml>marginnote</targetxml>. Instead,
            <targetxml>marginnote</targetxml> is placed at end of <targetxml>text</targetxml>
          element which contains the associated narrative. This is done to sync with UK12-Treatise
          conversion. For description of UK12 issue, see R4.5 Board Item 1804.</ph></p>
      <p>2014-01-02: <ph id="change_20140102_jm">Rule changes. Added rules to merge adjacent notes
          and to move notes. Responds to presentation requirements for producing single marginnote
          icon and to position icon after the associated text. These changes sync the conversion
          with UK12 Treatise. Tracking: R4.5 Content Issues 958 (UK11) and 972 (UK12), Webteam
          103703 (UK12).</ph></p>
      <p>2013-04-08: <ph id="change_20130408_jm"><sourcexml>note</sourcexml> -
            <targetxml>marginnote</targetxml> added to Newsitem schema. Removed reference to pending
          CR.</ph></p>
      <p>2013-01-09: <ph id="change_20130109_jm">Added detail on expected value for
            <sourcexml>note[@notetype]</sourcexml>; per workshop</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK11DN-Digest-Newsitem\UK11_DN_note.dita  -->
  <xsl:template match="note/@notetype['xref']"/>
<xsl:template match="note[parent::p]"/>

</xsl:stylesheet>