<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK12_Treatise_references">
  <title>references <lnpid>id-UK12-29826</lnpid></title>
  <body>
    <section><p><sourcexml>references[@referencetype]</sourcexml> becomes
          <targetxml>ref:relatedrefs[@referencetype]/bodytext</targetxml>. The attribute is
        optional.</p></section>

    <pre>
              <b><i>Example</i></b>
      
<b><i>SOURCE XML</i></b>                  

&lt;references&gt;
  &lt;heading&gt;
     &lt;title&gt;
         &lt;emph typestyle="it"&gt;Read more about this from Butterworths&lt;/emph&gt;
     &lt;/title&gt;
  &lt;/heading&gt;
  &lt;p&gt;
     &lt;text&gt;
        &lt;ci:cite normcite="0ON5_884869"&gt;
            &lt;ci:content&gt;Eligibility: Tolley's Pensions Law Service, The
                Financial Assistance Scheme [L4.3]–[L4.7]&lt;/ci:content&gt;
        &lt;/ci:cite&gt;
     &lt;/text&gt;
  &lt;/p&gt;
&lt;/references&gt;
 
<b><i>TARGET XML</i></b>                  

&lt;ref:relatedrefs&gt;
  &lt;heading&gt;
     &lt;title&gt;Read more about this from Butterworths&lt;/title&gt;
  &lt;/heading&gt;
  &lt;bodytext&gt;
     &lt;p&gt;
       &lt;text&gt;
          &lt;lnci:cite normcite="0ON5_884869"&gt;
             &lt;lnci:content&gt;Eligibility: Tolley's Pensions Law Service, The
                 Financial Assistance Scheme [L4.3]–[L4.7]&lt;/lnci:content&gt;
          &lt;/lnci:cite&gt;
       &lt;/text&gt;
     &lt;/p&gt;
  &lt;/bodytext&gt;
&lt;/ref:relatedrefs&gt;
 
	</pre>
    <section>
      <title>Changes</title>
      <p>2015-03-12: <ph id="change_20150312_jm">New section. Target xpath is new. Maps
            <sourcexml>references</sourcexml> to <targetxml>ref:relatedrefs</targetxml>. Responds to
          new markup in recent UK12 rosetta delivery. R4.5 Board Item 2231.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK12-Treatise\UK12_Treatise_references.dita  -->
<!--	<xsl:message>UK12_Treatise_references.xsl requires manual development!</xsl:message> -->

	<xsl:template match="references[@referencetype]">

		<!--  Original Target XPath:  ref:relatedrefs[@referencetype]/bodytext   -->
		<ref:relatedrefs>
			<bodytext>
				<xsl:apply-templates select="@* | node()"/>
			</bodytext>
		</ref:relatedrefs>

	</xsl:template>

	<xsl:template match="references">

		<!--  Original Target XPath:  ref:relatedrefs   -->
		<ref:relatedrefs>
		  <xsl:apply-templates select="heading"/>
		  <bodytext>
			<xsl:apply-templates select="@* | node() except heading"/>
		  </bodytext>
		</ref:relatedrefs>

	</xsl:template>

</xsl:stylesheet>