<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK12_Treatise_defdesc-additional-text">
  <title>(UK12) <sourcexml>defdesc</sourcexml> followed by narrative <lnpid>id-UK12-29828</lnpid></title>
  <body>
    <section><p>This is a special additional rule for UK12 Treatises.</p>
      <p><sourcexml>defitem</sourcexml> contains <sourcexml>defdesc</sourcexml> and may contain
        additional elements, usually <sourcexml>p</sourcexml>, immediately after
          <sourcexml>defdesc</sourcexml>.</p>
      <p>Special Rule: any elements in <sourcexml>defitem</sourcexml> occurring after
          <sourcexml>defdesc</sourcexml> must be moved to become the last elements within target
          <targetxml>defdesc/bodytext</targetxml>.</p></section>


    <pre>
        <b>EXAMPLE</b>
            
<b><i>Source XML</i></b>

&lt;defitem&gt;
    &lt;defterm&gt;additional inspectors&lt;/defterm&gt;
    &lt;defdesc&gt;
        &lt;p&gt;
            &lt;text&gt;Additional inspectors are appointed by the Chief Inspector.&lt;/text&gt;
        &lt;/p&gt;
    &lt;/defdesc&gt;
    &lt;p&gt;
        &lt;text&gt;
            &lt;ci:cite type="paragraph-ref"&gt;
                &lt;ci:content&gt;B [7603]&lt;/ci:content&gt;
            &lt;/ci:cite&gt;, &lt;ci:cite type="paragraph-ref"&gt;
                &lt;ci:content&gt;B [7330]&lt;/ci:content&gt;
            &lt;/ci:cite&gt;
        &lt;/text&gt;
    &lt;/p&gt;
&lt;/defitem&gt;
 
<b><i>Target XML</i></b>

&lt;defitem&gt;
    &lt;defterm&gt;additional inspectors&lt;/defterm&gt;
    &lt;defdesc&gt;
        &lt;bodytext&gt;
            &lt;p&gt;
                &lt;text&gt;Additional inspectors are appointed by the Chief Inspector.&lt;/text&gt;
            &lt;/p&gt;
            &lt;p&gt;
                &lt;text&gt;
                    &lt;lnci:cite type="paragraph-ref"&gt;
                        &lt;lnci:content&gt;B [7603]&lt;/lnci:content&gt;
                    &lt;/lnci:cite&gt;, &lt;lnci:cite type="paragraph-ref"&gt;
                        &lt;lnci:content&gt;B [7330]&lt;/lnci:content&gt;
                    &lt;/lnci:cite&gt;
                &lt;/text&gt;
            &lt;/p&gt;
        &lt;/bodytext&gt;
    &lt;/defdesc&gt;
&lt;/defitem&gt;

                </pre>
    <section>
      <title>Changes</title>
      <p>2016-07-07: <ph id="change_20160707_jm">New section. UK12 only. Handles text occurring
          after <sourcexml>defdesc</sourcexml>. No new xpaths.</ph>.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK12-Treatise\UK12_Treatise_defdesc-additional-text.dita  -->
<!--	<xsl:message>UK12_Treatise_defdesc-additional-text.xsl requires manual development!</xsl:message> -->

    <xsl:template match="defdesc[following-sibling::p]">
        <defdesc>
            <bodytext>
                <xsl:apply-templates select="@*|node()"/>
                <xsl:apply-templates select="following-sibling::p" mode="preceeding-defdesc"/>
            </bodytext>
        </defdesc>
    </xsl:template>
    
    <xsl:template match="p[preceding-sibling::defdesc]"/>
    
    <xsl:template match="p[preceding-sibling::defdesc]" mode="preceeding-defdesc">
        <p>
            <xsl:apply-templates select="@*|node()"/>
        </p>
    </xsl:template>


</xsl:stylesheet>