<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
  xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/" version="2.0"
  exclude-result-prefixes="dita">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK14_Precedents_h">
    <title>h (the letter "h") <lnpid>id-UK14-30232</lnpid></title>
    <body>
      <section>
        <p><sourcexml>h</sourcexml> becomes <targetxml>h</targetxml> as described in General Markup
          section.</p>
        <p><b>EXCEPT:</b> When target parent is <targetxml>form:bodytext</targetxml>,
            <sourcexml>h</sourcexml> becomes <targetxml>form:h</targetxml></p>
      </section>

      <pre>
        <b>EXAMPLE</b>
            
<b><i>Source XML</i></b>

&lt;clause&gt;
  &lt;heading&gt;
    &lt;desig&gt;
      &lt;designum&gt;1&lt;/designum&gt;
    &lt;/desig&gt;
  &lt;/heading&gt;
  &lt;h&gt;Ownership&lt;/h&gt;
  &lt;p&gt;
    &lt;text&gt;The ownership of shares...&lt;/text&gt;
  &lt;/p&gt;
&lt;/clause&gt;
 
<b><i>Target XML</i></b>

&lt;form:clause&gt;
  &lt;heading&gt;
    &lt;desig&gt;1&lt;/desig&gt;
  &lt;/heading&gt;
  &lt;form:bodytext&gt;
    &lt;form:h&gt;Ownership&lt;/form:h&gt;
    &lt;form:p&gt;
      &lt;form:text&gt;The ownership of shares...&lt;/form:text&gt;
    &lt;/form:p&gt;
  &lt;/form:bodytext&gt;
&lt;/form:clause&gt;

                </pre>
      <section>
        <title>Changes</title>
        <p>2016-12-21: <ph id="change_20161221_jm">New section. Rule states condition for transform
            to <targetxml>form:h</targetxml>. Reflects markup in precedents derived from
            UK12-Commentary sources which have been added to the UK14-Precedents stream.</ph></p>
      </section>
    </body>
  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK14-Precedents\UK14_Precedents_h.dita  -->
  <!--<xsl:message>UK14_Precedents_h.xsl requires manual development!</xsl:message>-->

  <xsl:template match="h" priority="2">

    <!--  Original Target XPath:  h   -->
    <xsl:choose>
      <xsl:when test="parent::note or parent::bodytext[ancestor::level[@leveltype='chapter' or @leveltype='section' or @leveltype='subsection' or @leveltype='supplement']] or parent::blockquote or following-sibling::*[1][self::blockquote]">
        <h>
          <xsl:apply-templates select="@* | node()"/>
        </h>
      </xsl:when>
      <xsl:otherwise>
        <form:h>
          <xsl:apply-templates select="@* | node()"/>
        </form:h>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:template match="h/@l" priority="2">
    <xsl:attribute name="level">
      <xsl:value-of select="."/>
    </xsl:attribute>
  </xsl:template>

</xsl:stylesheet>
