<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK14_Precedents_sigblock">
  <title>sigblock <lnpid>id-UK14-30233</lnpid></title>
    <body>
      <section><p><sourcexml>sigblock</sourcexml> becomes <targetxml>form:sigblock</targetxml>. Children map as follows:<ul>
        <li><sourcexml>p/text</sourcexml> becomes
          <targetxml>form:line</targetxml></li>
        <li><sourcexml>p/table</sourcexml> becomes
          <targetxml>table</targetxml>, i.e. suppress <sourcexml>p</sourcexml></li>
      </ul></p></section>

        <pre>
        <b>EXAMPLE</b>
            
<b><i>Source XML</i></b>

&lt;clause&gt;
  &lt;heading&gt;
    &lt;desig&gt;
      &lt;designum&gt;1&lt;/designum&gt;
    &lt;/desig&gt;
  &lt;/heading&gt;
  &lt;p&gt;
    &lt;text&gt;The ownership of shares...&lt;/text&gt;
  &lt;/p&gt;
  &lt;sigblock&gt;
    &lt;p&gt;
       &lt;text&gt;Signature .&lt;/text&gt;
    &lt;/p&gt;
    &lt;p&gt;
       &lt;table&gt;&lt;!-- usual table markup --&gt;&lt;/table&gt;
    &lt;/p&gt;
  &lt;/sigblock&gt;
&lt;/clause&gt;
 
<b><i>Target XML</i></b>

&lt;form:clause&gt;
  &lt;heading&gt;
    &lt;desig&gt;1&lt;/desig&gt;
  &lt;/heading&gt;
  &lt;form:bodytext&gt;
    &lt;form:p&gt;
       &lt;form:text&gt;The ownership of shares...&lt;/form:text&gt;
    &lt;/form:p&gt;
    &lt;form:sigblock&gt;
       &lt;form:line&gt;Signature .&lt;/form:line&gt;
       &lt;table&gt;&lt;!-- usual table markup --&gt;&lt;/table&gt;
    &lt;/form:sigblock&gt;
  &lt;/form:bodytext&gt;
&lt;/form:clause&gt;

                </pre>
        <section>
            <title>Changes</title>
            <p>2016-12-21: <ph id="change_20161221_jm">New section. Reflects markup in precedents
                    derived from UK12-Commentary sources which have been added to the
                    UK14-Precedents stream.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK14-Precedents\UK14_Precedents_sigblock.dita  -->
	<!--<xsl:message>UK14_Precedents_sigblock.xsl requires manual development!</xsl:message>--> 

	<xsl:template match="sigblock">

		<!--  Original Target XPath:  form:sigblock   -->
		<form:sigblock>
			<xsl:apply-templates select="@* | node()" mode="sigblock"/>
		</form:sigblock>

	</xsl:template>
  
  <xsl:template match="sigblock/p/text" mode="sigblock">
    <form:line>
      <xsl:apply-templates select="@* | node()"/>
    </form:line>
  </xsl:template>
  
  <xsl:template match="sigblock/p/table" mode="sigblock">
    <table>
    <xsl:apply-templates select="@* | node()"/>
    </table>
  </xsl:template>
  
  <xsl:template match="sigblock/p" priority="2"/>

</xsl:stylesheet>