<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
  xmlns:dig="http://www.lexis-nexis.com/glp/dig"
  xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0"
  exclude-result-prefixes="dita dig">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
    id="UK15PG_DIGESTDOC_abstract_With-Forms">
    <title>abstract <lnpid>id-UK15-30431</lnpid></title>
    <body>
      <p>The element <sourcexml>abstract</sourcexml> becomes
          <targetxml>seclaw:prelim/abstract/bodytext</targetxml>: <ol>
          <li>Create the element <targetxml>seclaw:prelim</targetxml> within the
              <targetxml>seclaw:level</targetxml> created from the conversion of
              <sourcexml>dig:info</sourcexml>.</li>
          <li>Create the element <targetxml>abstract</targetxml> within
              <targetxml>seclaw:prelim</targetxml>.</li>
          <li>Create the element <targetxml>bodytext</targetxml> within
              <targetxml>abstract</targetxml> to contain the child elements converted from the
            source <sourcexml>abstract</sourcexml>. Each child element is converted as described in
            the <i>General Markup</i> section.</li>
        </ol></p>
      <note>There are two different instructions that map content to
        <targetxml>abstract</targetxml>: this topic and the topic <xref
          href="UK15PG_DIGESTDOC_dig.catchwordgrp.dita"/>. As of February 2014, there is no scenario
        in the source content where both these instructions would be applied for the same file. That
        is, there are currently no source files that have both the element
          <sourcexml>catchwordgrp</sourcexml> and the element <sourcexml>abstract</sourcexml>.
        However, if in the future a file was found that contained both, then the content of both
        source elements should be converted to the same target
          <targetxml>abstract/bodytext</targetxml> by following the instructions given. In this
        case, the element <sourcexml>catchphrase</sourcexml> would map to its own
          <targetxml>p</targetxml> within the target <targetxml>abstract</targetxml> and any source
          <sourcexml>abstract/p</sourcexml> elements would map to their own <targetxml>p</targetxml>
        within the same target <targetxml>abstract</targetxml>.</note>
      <example>
        <title>Source XML</title>
        <codeblock> &lt;dig:body&gt; &lt;dig:info&gt; &lt;dig:title&gt;Lexis
          Calculate&lt;/dig:title&gt; &lt;/dig:info&gt; &lt;abstract&gt; &lt;p&gt;
          &lt;text&gt;Speedily and accurately calculate custody and other time limits, year on year
          RPI increases for calculating the value of assets in confiscation, VAT on price and
          currency conversions. Our generic calculators also allow you to easily calculate gross to
          net salary calculations and interest on judgment debts more simply and
          accurately.&lt;/text&gt; &lt;/p&gt; &lt;/abstract&gt; &lt;/dig:body&gt; </codeblock>
        <title>Target XML</title>
        <codeblock> &lt;seclaw:level leveltype="unclassified"&gt; &lt;heading&gt; &lt;title&gt;Lexis
          Calculate&lt;/title&gt; &lt;/heading&gt; &lt;seclaw:prelim&gt; &lt;abstract&gt;
          &lt;bodytext&gt; &lt;p&gt; &lt;text&gt;Speedily and accurately calculate custody and other
          time limits, year on year RPI increases for calculating the value of assets in
          confiscation, VAT on price and currency conversions. Our generic calculators also allow
          you to easily calculate gross to net salary calculations and interest on judgment debts
          more simply and accurately.&lt;/text&gt; &lt;/p&gt; &lt;/bodytext&gt; &lt;/abstract&gt;
          &lt;/seclaw:prelim&gt; &lt;seclaw:bodytext/&gt; &lt;/seclaw:level&gt; </codeblock>
      </example>
      <section>
        <title>Changes</title>
        <p>2014-02-12: <ph id="change_20140212_JCG">Significant change in mapping requested by LBU:
            abstract is no longer suppressed, instead it becomes
              <targetxml>seclaw:level/seclaw:prelim/abstract</targetxml>. (discussion related to
            R4.5 Content Issue List issue #1048)</ph></p>
        <p>2013-10-14: <ph id="change_20131014_jm">Minor change. Clarifies suppression of
              <sourcexml>abstract</sourcexml> container. Rewording reflects move of smart-form
            content from UK11-DA to UK15-DS. Webteam #240975 and #247307.</ph></p>
      </section>
    </body>
  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK15-PracticalGuidance\UK15PG_DIGESTDOC_abstract.dita  -->
  <!--<xsl:message>UK15PG_DIGESTDOC_abstract.xsl requires manual development!</xsl:message> -->

  <xsl:template match="abstract[not(preceding-sibling::dig:info/catchwordgrp)]">
      <seclaw:prelim>
        <abstract>
          <bodytext>
            <xsl:apply-templates select="@* | node()"/>
          </bodytext>
        </abstract>
      </seclaw:prelim>    
  </xsl:template>
  
  


</xsl:stylesheet>
