<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
    xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" 
    xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/"
    xmlns:comm="http://www.lexis-nexis.com/glp/comm"
    xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    version="2.0"
    exclude-result-prefixes="dita">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK15PG_COMMENTARYDOC">
        <title>COMMENTARYDOC <lnpid>id-UK15-30408</lnpid></title>

        <body>
            <p><sourcexml>COMMENTARYDOC</sourcexml> becomes <targetxml>seclaw:seclaw</targetxml>
                with the value of <targetxml>@seclawtype</targetxml> set to "practicalguidance".</p>
            <p><targetxml>seclaw:head</targetxml>, <targetxml>seclaw:body</targetxml>, and
                    <targetxml>doc:metadata</targetxml> are created as required children of
                    <targetxml>seclaw:seclaw</targetxml>. In this conversion it is expected that
                    <targetxml>seclaw:head</targetxml> will remain an empty element.</p>
            <example>
                <title>Source XML</title>
                <codeblock> &lt;COMMENTARYDOC&gt; ... &lt;/COMMENTARYDOC&gt; </codeblock>
                <title>Target XML</title>
                <codeblock> &lt;seclaw:seclaw seclawtype="practicalguidance" xml:lang="en-GB"&gt;
                    &lt;seclaw:head/&gt; &lt;seclaw:body&gt; ... &lt;/seclaw:body&gt;
                    &lt;doc:metadata&gt; ... &lt;/doc:metadata&gt; &lt;/seclaw:seclaw&gt;
                </codeblock>
            </example>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK15-PracticalGuidance\UK15PG_COMMENTARYDOC.dita  -->
    <!--<xsl:message>UK15PG_COMMENTARYDOC.xsl requires manual development!</xsl:message>-->

    <xsl:template match="COMMENTARYDOC">
        
        <!--  Original Target XPath:  seclaw:seclaw   -->
        <seclaw:seclaw>
            
            <!--   output the LA namespace nodes onto the root element.  -->
            <xsl:for-each select="$lexisAdvNamespaces/*">
                <xsl:sort/>
                <xsl:namespace name="{substring-after(substring-before(., '='), ':')}"
                    select="substring-after(translate(., '&#034;', ''), '=')"/>
            </xsl:for-each>
            
            <!--Create @xsi:schemaLocation based on the global parameter. -->
            <xsl:attribute name="xsi:schemaLocation" select=" $outputSchemaLoc "/>
            
            <!-- Create seclaw:seclaw/@xml:lang using the global named template that uses doc-lang and doc-country. -->
            <xsl:call-template name="xml_lang"/>
            
            <!--  Process attributes of root COMMENTARYDOC element. -->
            <xsl:apply-templates select="@*"/>
            
            <!--Create the required seclaw:seclaw/@seclawtype attribute. -->    
            <xsl:variable name="tmpSelector">
                <xsl:value-of select="normalize-space(lower-case(docinfo/docinfo:selector))" />
            </xsl:variable>
            <xsl:attribute name="seclawtype">
                <xsl:choose>
                    <xsl:when test="contains($tmpSelector, 'practicalguidance')">practicalguidance</xsl:when>                    
                    <xsl:otherwise>practicalguidance</xsl:otherwise>
                </xsl:choose>
            </xsl:attribute>
            
            <seclaw:head />
            
            <!-- Rely on the template for comm:body to create the desired seclaw:body. --> 
            <!--<xsl:apply-templates select="comm:info" />--> <!-- PK: added this -->
            <xsl:apply-templates select="comm:body" /> 
            
            <doc:metadata>
                <xsl:apply-templates select="docinfo" />
            </doc:metadata>
        </seclaw:seclaw>
        
    </xsl:template>

</xsl:stylesheet>
