<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:dig="http://www.lexis-nexis.com/glp/dig"
	xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
	xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0"
	exclude-result-prefixes="dita dig ">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
		id="UK15PG_DIGESTDOC_otherinfo">
		<title>
			<sourcexml>otherinfo</sourcexml>
			<lnpid>id-UK15-30442</lnpid>
		</title>
		<body>
			<p><sourcexml>otherinfo[@infotype]/date</sourcexml> becomes
					<targetxml>seclaw:levelinfo/miscdate[@datetype]/date-text</targetxml>.</p>
			<note><targetxml>seclaw:levelinfo</targetxml> is a child of the
					<targetxml>seclaw:level</targetxml> created from
				<sourcexml>dig:info</sourcexml>.</note>
			<note>This scenario occurs in smart forms, dpsi 0JUM and 0KVS. This is alternative
				mark-up to the <sourcexml>dig:info/issue</sourcexml> element (see the topic <xref
					href="UK15PG_DIGESTDOC_issue.dita"/>). Either one or the other of these elements
				will be present in a document, both are mapped to
					<targetxml>miscdate[@datetype="form-date"]</targetxml>.</note>
			<example>
				<title>Source XML</title>
				<codeblock> &lt;dig:body&gt; &lt;dig:info&gt; &lt;otherinfo infotype="form-date"&gt;
					&lt;date&gt;2nd Edition Oct 2004&lt;/date&gt; &lt;/otherinfo&gt;
					&lt;/dig:info&gt; &lt;/dig:body&gt; </codeblock>
				<title>Target XML</title>
				<codeblock> &lt;seclaw:body&gt; &lt;seclaw:level leveltype="form"&gt;
					&lt;seclaw:levelinfo&gt; &lt;miscdate
					datetype="form-date"&gt;&lt;date-text&gt;2nd Edition Oct
					2004&lt;/date-text&gt;&lt;/miscdate&gt; &lt;/seclaw:levelinfo&gt;
					&lt;/seclaw:level&gt; &lt;/seclaw:body&gt; </codeblock>
			</example>
			<section>
				<title>Changes</title>
				<p>2014-10-27: <ph id="change_20141027_JCG">Added a note refering to the new topic
							<xref href="UK15PG_DIGESTDOC_issue.dita"/>. No change to instructions
						for the <sourcexml>otherinfo</sourcexml> element.</ph></p>
				<p>2013-10-14: <ph id="change_20131014_jm">New Rule. Supports move of smart-form
						content from UK11-DA to UK15-DS. Webteam # 240975 and #247307.</ph></p>
			</section>
		</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK15-PracticalGuidance\UK15PG_DIGESTDOC_otherinfo.dita  -->
	<!--<xsl:message>UK15PG_DIGESTDOC_otherinfo.xsl requires manual development!</xsl:message> -->

	<!--<xsl:template match="otherinfo">

		<!-\-  Original Target XPath:  seclaw:levelinfo/miscdate[@datetype]/date-text   -\->
		<seclaw:levelinfo>
			<miscdate>
				<date-text>
					<xsl:apply-templates select="@* | node()"/>
				</date-text>
			</miscdate>
		</seclaw:levelinfo>

	</xsl:template>-->
	<xsl:template match="otherinfo[@infotype]">

		<!--  Original Target XPath:  seclaw:levelinfo/miscdate[@datetype]/date-text   -->
		
			<miscdate>
				<xsl:attribute name="datetype">
					<xsl:value-of select="@infotype"/>
				</xsl:attribute>
				<xsl:apply-templates select="@* except @infotype | node() "/>
			</miscdate>

		
	</xsl:template>

	<xsl:template match="otherinfo/date" >
		<date-text>
			<xsl:apply-templates select="@*|node()"/>
		</date-text>
	</xsl:template>


</xsl:stylesheet>
