<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0"
    exclude-result-prefixes="dita">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
        id="UK15PG_COMMENTARYDOC_org_remotelink">
        <title>org/remotelink <lnpid>id-UK15-30425</lnpid></title>

        <body>
            <p><sourcexml>org/remotelink</sourcexml> becomes <targetxml>ref:lnlnk</targetxml> withe
                the value of <targetxml>@service</targetxml> set to "URL". The children of
                    <targetxml>ref:lnlink</targetxml> are populated as follows:<ul>
                    <li>Create <targetxml>ref:marker</targetxml>. The contents of
                            <sourcexml>remotelink</sourcexml> becomes the contents of
                            <targetxml>ref:marker</targetxml>.</li>
                    <li>Create <targetxml>ref:locator</targetxml>. The children of
                            <targetxml>ref:locator</targetxml> are populated as follows:<ul>
                            <li>Create <targetxml>ref:locator-key</targetxml>. The children of
                                    <targetxml>ref:locator-key</targetxml> are populated as follows:<ul>
                                    <li>Create <targetxml>ref:key-name</targetxml> with the value of
                                            <targetxml>@name</targetxml> set to "URL".</li>
                                    <li>Create <targetxml>ref:key-value</targetxml> with the value
                                        of <targetxml>@value</targetxml> set to a concatentation of
                                        "http://" and the value in
                                            <sourcexml>remotelink/@href</sourcexml>.</li>
                                </ul></li>
                        </ul></li>
                </ul></p>
            <example>
                <title>Source XML</title>
                <codeblock> &lt;comm:info&gt; &lt;contrib contribtype="author"&gt; Produced in
                    partnership with &lt;org&gt;&lt;remotelink hrefclass="http"
                    href="lexislegalintelligence.co.uk/lexispsl/tax-experts" newwindow="YES"&gt;Anne
                    Fairpo of Atlas Chambers&lt;/remotelink&gt;&lt;/org&gt;&lt;/contrib&gt;
                    &lt;/comm:info&gt; </codeblock>
                <title>Target XML</title>
                <codeblock> &lt;seclaw:body&gt; &lt;pubfm:pubfm pubfmtype="contributor"&gt;
                    &lt;byline&gt;Produced in partnership with &lt;ref:lnlink service="URL"&gt;
                    &lt;ref:marker&gt;Anne Fairpo of Atlas Chambers&lt;/ref:marker&gt;
                    &lt;ref:locator&gt; &lt;ref:locator-key&gt; &lt;ref:key-name name="URL"/&gt;
                    &lt;ref:key-value
                    value="http://lexislegalintelligence.co.uk/lexispsl/tax-experts"/&gt;
                    &lt;/ref:locator-key&gt; &lt;/ref:locator&gt; &lt;/ref:lnlink&gt;&lt;/byline&gt;
                    &lt;/pubfm:pubfm&gt; ... &lt;/seclaw:body&gt; </codeblock>
            </example>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK15-PracticalGuidance\UK15PG_COMMENTARYDOC_org_remotelink.dita  -->
    <!--	<xsl:message>UK15PG_COMMENTARYDOC_org_remotelink.xsl requires manual development!</xsl:message> -->

    <xsl:template match="org/remotelink">

        <!--  Original Target XPath:  ref:lnlnk   -->
        <ref:lnlnk>
            <xsl:attribute name="service">URL</xsl:attribute>
            <xsl:apply-templates select="@* | node()"/>
        </ref:lnlnk>

    </xsl:template>

    <xsl:template match="remotelink [parent::org]">

        <!--  Original Target XPath:  ref:marker   -->
        <xsl:element name="ref:marker">
            <xsl:value-of select="org/remotelink/text()"/>
            <xsl:apply-templates select="@* | node()"/>
        </xsl:element>

        <xsl:element name="ref:locator">
            <xsl:element name="ref:locator-key">
                <xsl:element name="ref:key-name">
                    <xsl:attribute name="name">
                        <xsl:text>URL</xsl:text>
                    </xsl:attribute>
                </xsl:element>
                <xsl:element name="ref:key-value">
                    <!--	                <xsl:variable name="http" select="'http://'"/>-->
                    <xsl:attribute name="value" select="concat('http://', ./remotelink/@href)"/>
                </xsl:element>
            </xsl:element>
            <xsl:apply-templates select="@* | node()"/>
        </xsl:element>

        <!--<ref:marker>
			<xsl:apply-templates select="@* | node()"/>
		</ref:marker>-->

    </xsl:template>

    <!--<xsl:template match="remotelink/@href">

		<!-\-  Original Target XPath:     -\->
		<!-\-  Could not determine target element or attribute name:  <>  -\->			<xsl:apply-templates select="@* | node()"/>
		<!-\-  Could not determine target element or attribute name:  </>  -\->

	</xsl:template>-->

</xsl:stylesheet>
