<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK15PG_DIGESTDOC_With-Forms">
    <title>DIGESTDOC <lnpid>id-UK15-30430</lnpid></title>

    <body>
        <p><sourcexml>DIGESTDOC</sourcexml> becomes <targetxml>seclaw:seclaw</targetxml> with the
            value of <targetxml>@seclawtype</targetxml> set to "practicalguidance".</p>
        <p><targetxml>seclaw:head</targetxml>, <targetxml>seclaw:body</targetxml>, and
                <targetxml>doc:metadata</targetxml> are created as required children of
                <targetxml>seclaw:seclaw</targetxml>. Create as empty element if necessary.</p>
        <example>
            <title>Source XML</title>
            <codeblock>

&lt;DIGESTDOC&gt;
    ...
&lt;/DIGESTDOC&gt;

           </codeblock>
            <title>Target XML</title>
            <codeblock>

&lt;seclaw:seclaw seclawtype="practicalguidance" xml:lang="en-GB"&gt;
    &lt;seclaw:head&gt;
        ...
    &lt;/seclaw:head&gt;
    &lt;seclaw:body&gt;
        ...
    &lt;/seclaw:body&gt;
    &lt;doc:metadata&gt;
        ...
    &lt;/doc:metadata&gt;
&lt;/seclaw:seclaw&gt;

           </codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>2013-10-14: <ph id="change_20131014_jm">Minor change. Removed statement that
          seclaw:head expected to be empty. Reflects move of smart-form content from UK11-DA to
          UK15-DS. Webteams #240975 and  #247307.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK15-PracticalGuidance\UK15PG_DIGESTDOC.dita  -->
	<!--<xsl:message>UK15PG_DIGESTDOC.xsl requires manual development!</xsl:message> -->

	<!--<xsl:template match="DIGESTDOC">

		<!-\-  Original Target XPath:  seclaw:seclaw   -\->
		<seclaw:seclaw>
			<xsl:apply-templates select="@* | node()"/>
		</seclaw:seclaw>

	</xsl:template>
-->
</xsl:stylesheet>