<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="level">
    <title><sourcexml>level</sourcexml>
        <lnpid>id-UK22CF-39023</lnpid>
    </title>
    <body>
        <section>
            <p><sourcexml>level</sourcexml> becomes <targetxml>primlaw:level</targetxml> and
                attribute <sourcexml>level/@leveltype</sourcexml> will become
                <targetxml>primlaw:level/@leveltype</targetxml>. </p><ul>
                <li>Outer-most (top) <sourcexml>level</sourcexml> becomes
                    <targetxml>primlaw:level</targetxml>
                </li>
                <li>Descendent (nested) <sourcexml>level</sourcexml> becomes
                    <targetxml>primlaw:level/primlaw:level</targetxml></li>
            </ul>
            If <sourcexml>level/@leveltype="annotation"</sourcexml> then target will be <targetxml>primlaw:level/@leveltype="unclassified"</targetxml>
            
            <p><sourcexml>bodytext</sourcexml> becomes
                <targetxml> primlaw:bodytext</targetxml></p>
            <p>For more confirmation please see below examples:</p>
            <b>Example: 1.</b>
            <pre>

&lt;COMMENTARYDOC&gt;
    &lt;comm:body&gt;
        &lt;level leveltype="section"&gt;
        ........
            &lt;level leveltype="annotation"&gt;
                &lt;bodytext searchtype="COMMENTARY"&gt;
                    &lt;p&gt;
                        &lt;text&gt;The following notes derive from those printed in Halsbury's Statutes Vol 06(2) (2012 reissue), title Children and Family Law.
                        &lt;/text&gt;
                    &lt;/p&gt;
                .......
            &lt;/bodytext&gt;
        &lt;/level&gt;
        ........
        &lt;/level&gt;
    &lt;/comm:body&gt;
&lt;/COMMENTARYDOC&gt;


<b>Becomes</b>
           

&lt;funddoc:fundamentallegaldocument seclawtype="form" xml:lang="en-UK"&gt;
    &lt;funddoc:body&gt;
        &lt;primlaw:level leveltype="section"&gt;
        .........
         &lt;primlaw:level leveltype="unclassified"&gt;
              &lt;primlaw:bodytext&gt;
                            &lt;p&gt;
                                &lt;text&gt;The following notes derive from those printed in Halsbury's Statutes Vol 06(2) (2012 reissue), title Children and Family Law.
                                &lt;/text&gt;
                            &lt;/p&gt;
                        
                ........
                &lt;/primlaw:bodytext&gt;
            &lt;/primlaw:level&gt;
         &lt;/primlaw:level&gt;     
     &lt;/funddoc:body&gt;
    
    ..........
&lt;/funddoc:fundamentallegaldocument&gt;

 </pre></section>
        <section>
            <title>Changes</title>
           
            <p>2016-09-19: <ph id="change_20160919_RS">Created</ph></p>
        </section>  
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK22CF\level.dita  -->
	

	<xsl:template match="level">

		<!--  Original Target XPath:  primlaw:level   -->
		<primlaw:level>
		    <xsl:attribute name="leveltype">
		        <xsl:copy-of select="@*"/>
		    </xsl:attribute>
			<xsl:apply-templates select="@* | node()"/>
		</primlaw:level>

	</xsl:template>

    <xsl:template match="level[@leveltype='annotation']">

		<!--  Original Target XPath:  primlaw:level/@leveltype   -->
		<primlaw:level>
			<xsl:attribute name="leveltype">
				<xsl:text>unclassified</xsl:text>
			</xsl:attribute>
		</primlaw:level>

	</xsl:template>

	<xsl:template match="@leveltype"/>
    <xsl:template match="@subsection"/>
    
</xsl:stylesheet>