<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.headnote_case.info_case.casename">
   <title>case:casename <lnpid>id-AU07-19215</lnpid></title>
   <body>
      <section>
         <ul><li class="- topic/li ">
                        <sourcexml class="+ topic/keyword xml-d/sourcexml ">case:headnote/case:info/case:casename</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">courtorder:head/heading/title</targetxml>.
                        The source attribute <sourcexml class="+ topic/keyword xml-d/sourcexml ">case:info/case:casename @searchtype</sourcexml> is dropped. 
                        
<pre xml:space="preserve" class="- topic/pre ">
&lt;case:headnote&gt;
    &lt;case:info&gt;
        &lt;case:casename searchtype="PRACTICE-NOTE"&gt;
            Practice Note: s 17 Appeals Costs Act 1998 Certificates&lt;/case:casename&gt;
    &lt;/case:info&gt;
&lt;/case:headnote&gt;
<b class="+ topic/ph hi-d/b ">Becomes</b>
&lt;courtorder:head&gt;   
    &lt;heading&gt;
        &lt;title&gt;Practice Note: s 17 Appeals Costs Act 1998 Certificates&lt;/title&gt;
    &lt;/heading&gt;   
&lt;/courtorder:head&gt;                
</pre>
                    
                    </li></ul>
      </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU07_courtorder\case.casename.dita  -->
	
	<xsl:template match="case:headnote/case:info/case:casename">
	    <xsl:choose>
	        <xsl:when test="not(parent::case:info/parent::caseheadnote/heading or /CASEDOC/case:body/heading)">
	            <heading xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/">
	                <title>
	                   <xsl:apply-templates select="@* | node()"/>
	                </title>
	            </heading>
	        </xsl:when>
	        <xsl:otherwise>
	            <title xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/">
	                <xsl:apply-templates select="@* | node()"/>
	            </title>
	        </xsl:otherwise>
	    </xsl:choose>		
	</xsl:template>
    
	<xsl:template match="case:casename/@searchtype"/>
	
</xsl:stylesheet>