<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
   xmlns:case="http://www.lexis-nexis.com/glp/case" 
   xmlns:compcase="urn:x-lexisnexis:content:compositecourtcase:sharedservices:1"
   version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.content">
   <title>case:content <lnpid>id-AU13-20424</lnpid></title>
   <body>
      <section>
         <ul>
            <li>
               <note>This is a container element that does not need to be carried forward in the conversion. However, all content must be converted
                  such that the order of elements is maintained whenever possible. Please see the <xref href="../../common_newest/Rosetta_Elements-LxAdv-Maintain_Sequential_Order.dita">Maintain the Order of Elements Whenever
                     Possible</xref> section for more information.</note>
               <sourcexml>case:content</sourcexml>
            </li>
         </ul>
      </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU13_composite_cases\case.content.dita  -->

	<xsl:template match="case:content">

	<compcase:body>
     <xsl:for-each-group select="*" group-starting-with="case:typeofcase">
        <compcase:caseinstance>
              <compcase:caseinstancehead>
                 <xsl:apply-templates select="current-group()/self::case:typeofcase"/>
              </compcase:caseinstancehead>           
           <compcase:caseinstancebody>
              <xsl:apply-templates select="/CASEDOC/case:body/*[1][self::heading]"/>
              <xsl:apply-templates select="current-group()/self::node() except(current-group()/self::case:typeofcase)"/>
           </compcase:caseinstancebody>
        </compcase:caseinstance>	 
     </xsl:for-each-group>  
	</compcase:body>
	</xsl:template>
</xsl:stylesheet>