<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
  xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:casesum="http://www.lexisnexis.com/xmlschemas/content/legal/case-summary/1/" 
  version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.disposition">
  <title>case:disposition <lnpid>id-AU13-20431</lnpid></title>
  <body>
    <section>
      <ul>
        <li class="- topic/li ">
          <sourcexml class="+ topic/keyword xml-d/sourcexml ">case:disposition</sourcexml> becomes 
          <targetxml class="+ topic/keyword xml-d/targetxml ">casesum:disposition</targetxml> and <targetxml class="+ topic/keyword xml-d/targetxml ">p</targetxml>
          is the required child for <targetxml class="+ topic/keyword xml-d/targetxml ">casesum:disposition.</targetxml>. Attributes are: 
          <sourcexml class="+ topic/keyword xml-d/sourcexml ">@subdoc</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">@includeintoc</targetxml> 
          and <sourcexml class="+ topic/keyword xml-d/sourcexml ">@toc-caption</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">@alternatetoccaption</targetxml>.
          <note>There are two contexts for /case:disposition in Standard
            Rosetta along with NL Xpath: <ol>
              <li>/CASEDOC/case:body/case:headnote/case:disposition, <b>NL Xpath:</b>
                /compcase:compositecourtcase/compcase:head/casesum:summaries/casesum:disposition.</li>
              <li>/CASEDOC/case:body/case:content/case:judgments/case:disposition, <b>NL Xpath:</b>
                compcase:body/compcase:caseinstance/compcase:caseinstancebody/casesum:disposition.</li>
            </ol>
          </note>
          <note>Conversion should not create consecutive <targetxml>casesum:summaries</targetxml> elements. When 2 or more sibling source elements map
            to <targetxml>casesum:summaries</targetxml>, data should be merged to a single <targetxml>casesum:summaries</targetxml> element.</note>
          <pre xml:space="preserve" class="- topic/pre ">

&lt;case:disposition&gt;Leave to appeal granted.&lt;/case:disposition&gt;
<b class="+ topic/ph hi-d/b ">Becomes:</b>


&lt;casesum:disposition&gt;
    &lt;p&gt;
      &lt;text&gt;Leave to appeal granted.&lt;/text&gt;
    &lt;/p&gt;
&lt;/casesum:disposition&gt;
</pre>
          <note>
            <p>For information on how to process the attribute @ln.user-displayed. Refer common_rosetta_ln.user_displayed for handling of
                <targetxml>@ln.user-displayed</targetxml></p>
          </note>
        </li>
      </ul>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU13_composite_cases\case.disposition.dita  -->

	<xsl:template match="case:disposition">

		<!--  Original Target XPath:  casesum:disposition   -->
		<casesum:disposition>
		  <xsl:apply-templates select="@*"/>
			<p>
			  <text>
			    <xsl:apply-templates select="node()"/>
			  </text>
			</p>
		</casesum:disposition>

	</xsl:template>

  <xsl:template match="case:disposition/@subdoc">

		<!--  Original Target XPath:  @includeintoc   -->
		<xsl:attribute name="includeintoc">
			<xsl:value-of select="."/>
		</xsl:attribute>

	</xsl:template>

  <xsl:template match="case:disposition/@toc-caption">

		<!--  Original Target XPath:  @alternatetoccaption   -->
		<xsl:attribute name="alternatetoccaption">
		  <xsl:value-of select="."/>
		</xsl:attribute>

	</xsl:template>

</xsl:stylesheet>