<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.filenum">
   <title>case:filenum <lnpid>id-CA02DS-12820</lnpid></title>
   <body>
      <section>
         <ul>
            <li class="- topic/li ">
               <sourcexml class="+ topic/keyword xml-d/sourcexml ">case:filenum</sourcexml> becomes
                  <targetxml class="+ topic/keyword xml-d/targetxml ">caseinfo:caseinfo/caseinfo:docketnum</targetxml>
               <pre xml:space="preserve" class="- topic/pre ">&lt;case:filenum&gt;No. 200301T1696&lt;/case:filenum&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>
             
&lt;caseinfo:docketnum&gt;No. 200301T1696&lt;/caseinfo:docketnum&gt;            
</pre>
            </li>
         </ul>
      </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA02-Case_Summaries\CA02DS_DIGESTDOC_to_seclaw\case.filenum.dita  -->
	 
   <!-- Vikas Rohilla : template to match the case:filenum nad creates the caseinfo:docketnum -->
	<xsl:template match="case:filenum">
		<caseinfo:docketnum>
			<xsl:apply-templates select="@* | node()"/>
		</caseinfo:docketnum>
	</xsl:template>
	
</xsl:stylesheet>