<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/" xmlns:casedigest="http://www.lexisnexis.com/xmlschemas/content/legal/case-digest/1/" xmlns:location="http://www.lexisnexis.com/xmlschemas/content/shared/location/1/" version="2.0" exclude-result-prefixes=" jurisinfo dita case location casedigest">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.courtloc">
   <title>case:courtloc <lnpid>id-CA02DC-12611</lnpid></title>
   <body>
      <section>
<ul>
   <li>
                    <sourcexml>case:courtloc</sourcexml> becomes
       <targetxml>casedigest:head/casedigest:caseinfo/jurisinfo:courtinfo/jurisinfo:jurisdiction/jurisinfo:location/location:state</targetxml>.
       
       <pre>

&lt;case:courtinfo&gt;
    &lt;case:courtloc&gt;Ontario&lt;/case:courtloc&gt;
&lt;/case:courtinfo&gt;


<b>Becomes</b>


&lt;casedigest:head&gt;
    &lt;casedigest:caseinfo&gt;
        &lt;jurisinfo:courtinfo&gt;
            &lt;jurisinfo:jurisdiction&gt;
                &lt;jurisinfo:location&gt;
                    &lt;location:state&gt;Ontario&lt;/location:state&gt;
                &lt;/jurisinfo:location&gt;
            &lt;/jurisinfo:jurisdiction&gt;
        &lt;/jurisinfo:courtinfo&gt;
    &lt;/casedigest:caseinfo&gt;
&lt;/casedigest:head&gt;

</pre>
                    
                </li>
      </ul>
</section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA02-Case_Summaries\CA02DC_DIGESTDOC_to_casedigest\case.courtloc.dita  -->
	 
    <!-- Vikas Rohilla : Updated the Template Initial -->
    <xsl:template match="case:courtloc">
    <jurisinfo:location>
    <location:state>
    <xsl:apply-templates select="@* | node()"/>
    </location:state>
    </jurisinfo:location>
    
    </xsl:template>

</xsl:stylesheet>