<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:admindecision="urn:x-lexisnexis:content:administrative-decision:sharedservices:1" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.judgment">
   <title>case:judgment <lnpid>id-CA04-13426</lnpid></title>
   <body>
      <section>
          <ul>
         <li class="- topic/li ">
             <sourcexml class="+ topic/keyword xml-d/sourcexml ">case:judgment</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">admindecision:opinion</targetxml> 
            
<pre xml:space="preserve" class="- topic/pre "> 

&lt;case:judgment&gt;
    &lt;case:judgmentbody&gt;
       &lt;p&gt;
        &lt;text align="center"&gt;DECISION&lt;/text&gt;
       &lt;/p&gt;
    &lt;p&gt;
    &lt;text&gt;OVERVIEW&lt;/text&gt;
    &lt;/p&gt;
&lt;p&gt;
    &lt;pnum count="1"&gt;1&lt;/pnum&gt;
    &lt;text&gt;This is an application for reconsideration by the employee, Gary Gurnsey, under Section 116 of the Employment Standards Act (the "Act") of a decision of the Employment Standards Tribunal on February 12, 1999.&lt;/text&gt;
&lt;/p&gt;
    &lt;/case:judgmentbody&gt;
&lt;/case:judgment&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;admindecision:opinion&gt;    
    &lt;bodytext&gt;
       &lt;p align="center"&gt;
        &lt;text&gt;DECISION&lt;/text&gt;
       &lt;/p&gt;
    &lt;p&gt;
    &lt;text&gt;OVERVIEW&lt;/text&gt;
    &lt;/p&gt;
&lt;p&gt;
    &lt;desig value="1"&gt;1&lt;/desig&gt;
    &lt;text&gt;This is an application for reconsideration by the employee, Gary Gurnsey, under Section 116 of the Employment Standards Act (the "Act") of a decision of the Employment Standards Tribunal on February 12, 1999.&lt;/text&gt;
&lt;/p&gt;
    &lt;/bodytext&gt;
&lt;/admindecision:opinion&gt;
</pre>
         </li>
          </ul>
      </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA04-Administrative_Decisions\case.judgment.dita  -->
	<!--<xsl:message>CA04-Administrative_Decisions_case.judgment.xsl requires manual development!</xsl:message> -->

	<xsl:template match="case:judgment">

		<!--  Original Target XPath:  admindecision:opinion   -->
		<admindecision:opinion>
			<xsl:apply-templates select="@* | node()"/>
		</admindecision:opinion>

	</xsl:template>

</xsl:stylesheet>