<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:admindoc="urn:x-lexisnexis:content:administrative-document:sharedservices:1" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.headnote">
   <title>case:headnote <lnpid>id-CA04-13423</lnpid></title>
   <body>
      <section>
          <ul>
         <li class="- topic/li ">
                    <sourcexml class="+ topic/keyword xml-d/sourcexml ">case:headnote</sourcexml>
                    becomes <targetxml class="+ topic/keyword xml-d/targetxml ">admindoc:admindoc/admindoc:head</targetxml>.
                    <pre xml:space="preserve" class="- topic/pre ">

&lt;case:headnote&gt;
&lt;case:info&gt;
    &lt;!-- .... --&gt;
    &lt;abbrvname display-name="Indexed as:" searchtype="SHORT-CASE-NAME"&gt;Boucher (Re)&lt;/abbrvname&gt;    
&lt;/case:info&gt;     
&lt;/case:headnote&gt; 

                  
<b class="+ topic/ph hi-d/b ">Becomes</b>
             
&lt;admindoc:head&gt;
&lt;admindecision:decisioninfo&gt;
  &lt;admindecision:caseinfo&gt;
            &lt;!-- .... --&gt;
             &lt;caseinfo:casename&gt;
                 &lt;caseinfo:shortcasename name="Indexed as:"&gt;Boucher (Re)&lt;/caseinfo:shortcasename&gt;
             &lt;/caseinfo:casename&gt;
    &lt;/admindecision:caseinfo&gt;
 &lt;admindecision:decisioninfo&gt;
&lt;/admindoc:head&gt;

</pre>
                </li>
          </ul>
      </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA04-Administrative_Decisions\case.headnote.dita  -->
	<!--<xsl:message>CA04-Administrative_Decisions_case.headnote.xsl requires manual development!</xsl:message> -->

	<xsl:template match="case:headnote">

		<!--  Original Target XPath:  admindoc:admindoc/admindoc:head   -->
	    <xsl:choose>
	        <xsl:when test="parent::case:appendix">
	            <xsl:apply-templates select="node()"/>
	        </xsl:when>
	        <xsl:otherwise>
	            <admindoc:head>
	                <xsl:apply-templates select="@* | node()"/>
	            </admindoc:head>
	        </xsl:otherwise>
	    </xsl:choose>
	   
	</xsl:template>


<xsl:template match="sub">
    <sub>
        <xsl:value-of select="@*|node()"/>
    </sub>
</xsl:template>
</xsl:stylesheet>