<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:glp="http://www.lexis-nexis.com/glp" xmlns:admindecision="urn:x-lexisnexis:content:administrative-decision:sharedservices:1" xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/" version="2.0" exclude-result-prefixes="dita case glp">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.judges">
    <title>case:judges <lnpid>id-CA04-13425</lnpid></title>
    <body>
        <section>
            <ul>
                <li class="- topic/li ">
                    <sourcexml class="+ topic/keyword xml-d/sourcexml ">case:judges</sourcexml>
                    becomes <targetxml class="+ topic/keyword xml-d/targetxml ">admindecision:panel/admindecision:adjudicators</targetxml>
                    <note class="- topic/note ">Capture PCData for judges markup as is in New Lexis
                        and always create <targetxml class="+ topic/keyword xml-d/targetxml ">person:adjudicator</targetxml> as an immediate child of
                        <targetxml class="+ topic/keyword xml-d/targetxml ">admindecision:adjudicators</targetxml>.</note>
                    <pre xml:space="preserve" class="- topic/pre ">
&lt;case:judges&gt;
    Panel: Willie Grieve, Chair; Anne Michaud,&lt;nl/&gt;Commission Member; Tudor Beattie,&lt;nl/&gt;Q.C., Commission Member
&lt;/case:judges&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;admindecision:panel&gt;
    &lt;admindecision:adjudicators&gt;
      &lt;person:adjudicator&gt;Panel: Willie Grieve, Chair; Anne Michaud, Commission Member; Tudor Beattie, Q.C., Commission Member&lt;/person:adjudicator&gt;
    &lt;/admindecision:adjudicators&gt;
&lt;/admindecision:panel&gt;    
                    </pre>
                     
                    <note class="- topic/note ">Suppress <sourcexml class="+ topic/keyword xml-d/sourcexml ">nl</sourcexml> from converison and convert them into single space character in target.</note>       
                    
                    
<pre xml:space="preserve" class="- topic/pre ">
<b>Handling of case:judges/glp:note scenario</b>
&lt;case:judges&gt;
          &lt;glp:note&gt;
              &lt;p nl="0"&gt;
                  &lt;text&gt;[Quicklaw note: Original panel decision, released July&lt;nl/&gt;17, 2000, is available at [2000] I.D.A.C.D. No. 35.]&lt;/text&gt;
              &lt;/p&gt;
          &lt;/glp:note&gt;
&lt;/case:judges&gt;
  

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;admindecision:panel&gt;
    &lt;admindecision:adjudicators&gt;
      &lt;note&gt;
         &lt;bodytext&gt;
              &lt;p&gt;
                  &lt;text&gt;[Quicklaw note: Original panel decision, released July&lt;proc:nl/&gt;17, 2000, is available at [2000] I.D.A.C.D. No. 35.]&lt;/text&gt;
              &lt;/p&gt;
           &lt;/bodytext&gt;   
          &lt;/note&gt;
    &lt;/admindecision:adjudicators&gt;
&lt;/admindecision:panel&gt; 
</pre>
                    <note>If <sourcexml>glp:note</sourcexml> within <sourcexml>case:judges</sourcexml> has information "Panel Decision on costs. The original decision is available&lt;nl/&gt;at [2000] I.D.A.C.D. No. 26 in this database.]" then conversion needs to omit them as this is a data error which LBU will fix.</note> 
              </li>
            </ul>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA04-Administrative_Decisions\case.judges.dita  -->
	<!--<xsl:message>CA04-Administrative_Decisions_case.judges.xsl requires manual development!</xsl:message> -->

	<xsl:template match="case:judges">
	    <xsl:variable name="case" select="fnr"/>
	    <xsl:choose>
	        <xsl:when test="child::glp:note">
	            <admindecision:panel>
	                <admindecision:adjudicators>
	                    <note>
	                        <bodytext>
	                            <xsl:apply-templates select="@*|node()"/>
	                        </bodytext>
	                    </note>
	                </admindecision:adjudicators>
	            </admindecision:panel>
	        </xsl:when>
	        <xsl:when test="child::fnr[@fnrtoken]">
	            <admindecision:panel>
	            <admindecision:adjudicators>
	                <xsl:choose>
	                    <xsl:when test="$case[contains(.,'*')]">
	                        <person:adjudicator>
	                            <xsl:value-of select="substring-before(.,'*')"/>
	                        </person:adjudicator>
	                        <xsl:apply-templates select="child::fnr"/>
	                        <person:adjudicator>
	                            <xsl:value-of select="substring-after(.,'*')"/>
	                        </person:adjudicator>
	                    </xsl:when>
	                    <xsl:otherwise>
	                        <person:adjudicator>
	                            <xsl:value-of select="."/>
	                        </person:adjudicator>
	                        <xsl:apply-templates select="child::fnr"/>
	                    </xsl:otherwise>
	                </xsl:choose>

	            </admindecision:adjudicators>
	            </admindecision:panel>
	        </xsl:when>
	        <xsl:otherwise>
	            <admindecision:panel>
	                <admindecision:adjudicators>
	                    <person:adjudicator>
	                        <xsl:apply-templates select="@* | node()"/>
	                    </person:adjudicator>
	                </admindecision:adjudicators>
	            </admindecision:panel>
	        </xsl:otherwise>
	    </xsl:choose>
	    
	</xsl:template>

	<!-- Awantika-2018-01-31- case:judges handle of nl. Webstar # 7104004 -->
<xsl:template match="case:judges/nl">
	<xsl:choose>
		<xsl:when test="ends-with(preceding-sibling::text()[1], ' ') or starts-with(following-sibling::text()[1], ' ')"/>
		<xsl:otherwise>
			<xsl:text> </xsl:text>
		</xsl:otherwise>
	</xsl:choose>
</xsl:template>
	
	<xsl:template match="case:judges[ancestor::case:info]/text()[following-sibling::*[1][name() = 'nl']]">
		<xsl:value-of select="normalize-space(.)"/>
	</xsl:template> 
</xsl:stylesheet>