<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" xmlns:glp="http://www.lexis-nexis.com/glp" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:admindecision="urn:x-lexisnexis:content:administrative-decision:sharedservices:1" version="2.0" exclude-result-prefixes="dita case glp">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.info">
  <title>case:info <lnpid>id-CA04-13424</lnpid></title>
  <body>
    <section>
      <ul>
        <li class="- topic/li ">
          <sourcexml class="+ topic/keyword xml-d/sourcexml ">case:info</sourcexml> becomes
            <targetxml class="+ topic/keyword xml-d/targetxml ">admindecision:decisioninfo/admindecision:caseinfo</targetxml> and children are
          described below: <pre xml:space="preserve" class="- topic/pre ">

&lt;case:headnote&gt;
           &lt;case:info&gt;
              &lt;!-- .... --&gt;
              &lt;abbrvname display-name="Indexed as:" searchtype="SHORT-CASE-NAME"&gt;Boucher (Re)&lt;/abbrvname&gt;              
          &lt;/case:info&gt; 
&lt;/case:headnote&gt; 

                    
          <b class="+ topic/ph hi-d/b ">Becomes</b>          
           
&lt;admindoc:head&gt;
           &lt;admindecision:decisioninfo&gt;
               &lt;admindecision:caseinfo&gt;
               &lt;!-- .... --&gt;
                  &lt;caseinfo:casename&gt;
                    &lt;caseinfo:shortcasename name="Indexed as:"&gt;Boucher (Re)&lt;/caseinfo:shortcasename&gt;
                  &lt;/caseinfo:casename&gt;               
              &lt;/admindecision:caseinfo&gt;
           &lt;admindecision:decisioninfo&gt;
&lt;/admindoc:head&gt;

          </pre>
          
          <pre xml:space="preserve" class="- topic/pre ">
    <b>Handling of case:info/glp:note scenario</b>
&lt;case:info&gt;
    &lt;glp:note&gt;
        &lt;p&gt;
            &lt;text&gt; [Quicklaw note: Original Award filed November 17, 1994. See &lt;ci:cite&gt;
                    &lt;ci:case&gt;
                        &lt;ci:caseref ID="cref00025966" spanref="cspan00025966"&gt;
                            &lt;ci:reporter value="BCCAA"/&gt;
                            &lt;ci:edition&gt;
                                &lt;ci:date year="1994"/&gt;
                            &lt;/ci:edition&gt;
                            &lt;ci:refnum num="423"/&gt;
                        &lt;/ci:caseref&gt;
                    &lt;/ci:case&gt;
                    &lt;ci:content&gt;
                        &lt;ci:span spanid="cspan00025966"&gt;[1994] B.C.C.A.A.A. No. 423&lt;/ci:span&gt;
                    &lt;/ci:content&gt;
            &lt;/ci:cite&gt;.] 
            &lt;/text&gt;
        &lt;/p&gt;
    &lt;/glp:note&gt;
&lt;/case:info&gt;

          </pre>
            
          <b class="+ topic/ph hi-d/b ">Becomes</b>
            
          <pre xml:space="preserve" class="- topic/pre ">
&lt;admindecision:decisioninfo&gt;
    &lt;admindecision:caseinfo&gt;
        &lt;note&gt;
            &lt;bodytext&gt;
                &lt;p&gt;
                    &lt;text&gt; [Quicklaw note: Original Award filed November 17, 1994. See &lt;lnci:cite&gt;
                            &lt;lnci:case&gt;
                                &lt;lnci:caseref ID="cref00025966"&gt;
                                    &lt;lnci:reporter value="BCCAA"/&gt;
                                    &lt;lnci:edition&gt;
                                        &lt;lnci:date year="1994"/&gt;
                                    &lt;/lnci:edition&gt;
                                    &lt;lnci:refnum num="423"/&gt;
                                &lt;/lnci:caseref&gt;
                            &lt;/lnci:case&gt;
                            &lt;lnci:content&gt; [1994] B.C.C.A.A.A. No. 423 &lt;/lnci:content&gt;
                        &lt;/lnci:cite&gt;.] &lt;/text&gt;
                &lt;/p&gt;
            &lt;/bodytext&gt;
        &lt;/note&gt;
    &lt;/admindecision:caseinfo&gt;
&lt;/admindecision:decisioninfo&gt;   
         </pre>
        </li>
      </ul>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA04-Administrative_Decisions\case.info.dita  -->
	<!--<xsl:message>CA04-Administrative_Decisions_case.info.xsl requires manual development!</xsl:message> -->

    <xsl:template match="case:info[child::case:courtinfo or  child::case:casename]">
		<admindecision:decisioninfo>
			<admindecision:caseinfo>
			    <xsl:apply-templates select="case:casename|case:courtinfo/case:filenum"/> 
			    <xsl:element name="ref:citations">
			        <xsl:apply-templates select="case:reportercite|case:parallelcite|case:courtinfo/case:courtcite"/>
			    </xsl:element>
			    <xsl:apply-templates select="case:courtinfo[child::case:judges],case:courtinfo/case:judges,/CASEDOC/case:body/case:headnote/case:info/case:pubinfo[1]"/>
			</admindecision:caseinfo>
		    <xsl:apply-templates select="case:courtinfo[1]"/>
		</admindecision:decisioninfo>
        
	</xsl:template>
    <xsl:template match="case:info[parent::case:headnote/parent::case:appendix]">
        <xsl:apply-templates select="node()"/>
    </xsl:template>
<xsl:template match="case:info/glp:note">
     <note>
         <bodytext>
             <xsl:apply-templates select="@* | node()"/>
         </bodytext>
     </note>
</xsl:template>
</xsl:stylesheet>