<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns:casehist="http://www.lexisnexis.com/xmlschemas/content/legal/case-history/1/"
    xmlns:case="http://www.lexis-nexis.com/glp/case"
    xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0"
    exclude-result-prefixes="dita casehist case">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.subhist">
        <title>case:subhist <lnpid>id-CA14-35619</lnpid></title>

        <body>
            <section>
                <p><sourcexml>case:subhist</sourcexml> becomes
                        <targetxml>seclaw:body/seclaw:digestgrp/seclaw:digest/casehist:casehist/casehist:subhist/casehist:summary</targetxml>.</p>
            </section>

            <example>
                <title>Example 1</title>
                <codeblock> &lt;dig:info&gt; &lt;case:subhist&gt; &lt;p nl="0"&gt;
                    &lt;text&gt;Supreme Court of Canada, October 2, 2003, &lt;lnci:cite&gt;
                    &lt;lnci:case&gt; &lt;lnci:caseref ID="cref00000525"&gt; &lt;lnci:reporter
                    value="CARL"/&gt; &lt;lnci:edition&gt; &lt;lnci:date year="2003"/&gt;
                    &lt;/lnci:edition&gt; &lt;lnci:refnum num="204"/&gt; &lt;/lnci:caseref&gt;
                    &lt;/lnci:case&gt; &lt;lnci:content&gt;CARL/2003-204&lt;/lnci:content&gt;
                    &lt;/lnci:cite&gt; &lt;/text&gt; &lt;/p&gt; &lt;/case:subhist&gt;
                    &lt;/dig:info&gt; </codeblock>
                <b>becomes</b>
                <codeblock> &lt;seclaw:body&gt; &lt;seclaw:digestgrp&gt; &lt;seclaw:digest&gt;
                    &lt;casehist:casehist&gt; &lt;casehist:subhist&gt; &lt;casehist:summary&gt;
                    &lt;p&gt; &lt;text&gt;Supreme Court of Canada, October 2, 2003,
                    &lt;lnci:cite&gt; &lt;lnci:case&gt; &lt;lnci:caseref ID="cref00000525"&gt;
                    &lt;lnci:reporter value="CARL"/&gt; &lt;lnci:edition&gt; &lt;lnci:date
                    year="2003"/&gt; &lt;/lnci:edition&gt; &lt;lnci:refnum num="204"/&gt;
                    &lt;/lnci:caseref&gt; &lt;/lnci:case&gt;
                    &lt;lnci:content&gt;CARL/2003-204&lt;/lnci:content&gt; &lt;/lnci:cite&gt;
                    &lt;/text&gt; &lt;/p&gt; &lt;/casehist:summary&gt; &lt;/casehist:subhist&gt;
                    &lt;/casehist:casehist&gt; &lt;/seclaw:digest&gt; &lt;/seclaw:digestgrp&gt;
                    &lt;/seclaw:body&gt; </codeblock>
            </example>
            <section>
                <title>Changes</title>
                <p>2015-03-26: <ph id="change_20150326_jm">Removed
                            <targetxml>seclaw:digestinfo</targetxml> from target xpath. Corrects a
                        typo, was not valid. RFA 12.</ph></p>
                <p>2015-02-20: <ph id="change_20150220_PS">Created.</ph></p>
            </section>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA14-Emerging_Issues\case.subhist.dita  -->
    <!--<xsl:message>CA14-Emerging_Issues_case.subhist.xsl requires manual development!</xsl:message>-->

    <!--Vikas Rohilla : Tempalte to match the case:subhist and creates the casehist:casehist/casehist:subhist/casehist:summary -->
    <xsl:template match="case:subhist">
        <casehist:casehist>
            <casehist:subhist>
                <casehist:summary>
                    <xsl:apply-templates select="@* | node()"/>
                </casehist:summary>
            </casehist:subhist>
        </casehist:casehist>
    </xsl:template>

</xsl:stylesheet>
