<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:decision="http://www.lexisnexis.com/xmlschemas/content/legal/decision/1/"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
  xmlns:case="http://www.lexis-nexis.com/glp/case"
  xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0"
  exclude-result-prefixes="dita case">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.dates">
    <title>case:dates <lnpid>id-CA14-35615</lnpid></title>
    <body>
      <section>
        <ul>
          <li>
            <sourcexml>case:dates</sourcexml> becomes
              <targetxml>seclaw:body/seclaw:digestgrp/seclaw:digest/seclaw:digestinfo/caseinfo:caseinfo/decision:dates</targetxml>
            <ul>
              <li>
                <sourcexml>case:decisiondate</sourcexml> becomes
                  <targetxml>seclaw:body/seclaw:digestgrp/seclaw:digest/seclaw:digestinfo/caseinfo:caseinfo/decision:dates/decision:decisiondate</targetxml>.<pre>
&lt;case:dates&gt;
    &lt;case:decisiondate&gt;Judgment: December 13,
        2012.&lt;/case:decisiondate&gt;
&lt;/case:dates&gt;

  <b>Becomes</b>

&lt;decision:dates&gt;
    &lt;decision:decisiondate&gt;Judgment: December 13, 2012.&lt;/decision:decisiondate&gt;
&lt;/decision:dates&gt;</pre></li>
            </ul></li>
        </ul>
        <note>
          <p>Conversion should not create consecutive <targetxml>seclaw:digestinfo</targetxml>
            elements. When 2 or more consecutive sibling source elements map to
              <targetxml>seclaw:digestinfo</targetxml>, data should be merged to a single
              <targetxml>seclaw:digestinfo</targetxml> element unless this would hamper content
            ordering.</p>
        </note>
      </section>
      <section>
        <title>Changes</title>
        <p>2015-02-20: <ph id="change_20150220_PS">Created.</ph></p>
      </section>
    </body>
  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA14-Emerging_Issues\case.dates.dita  -->
  <!--<xsl:message>CA14-Emerging_Issues_case.dates.xsl requires manual development!</xsl:message> -->

  <!--Vikas Rohilla : Template to match the case:dates and creats the decision:dates-->
  <xsl:template match="case:dates">
    <decision:dates>
      <xsl:apply-templates select="@* | node()"/>
    </decision:dates>
  </xsl:template>
  
  <!--Vikas Rohilla : Template to match the case:decisiondate and creats the decision:decisiondate -->
  <xsl:template match="case:decisiondate">
    <decision:decisiondate>
      <xsl:apply-templates select="@* | node()"/>
    </decision:decisiondate>
  </xsl:template>

</xsl:stylesheet>
