<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/"
    xmlns:case="http://www.lexis-nexis.com/glp/case"
    xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/"
    xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0"
    exclude-result-prefixes="dita case">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.constituents">
        <title>case:constituents <lnpid>id-CA14-35612</lnpid></title>
        <body>
            <section>
                <p>In Rosetta samples element <sourcexml>case:constituents</sourcexml> occurs with
                    attribute <sourcexml>case:constituents/@constituenttype</sourcexml> which
                    contains two values as given below: <ul>
                        <li>case:constituents/@constituenttype=”counsel”</li>
                        <li>case:constituents/@constituenttype=”consultant”</li>
                    </ul></p>
                <p>Based on the attribute's value we need to handle it on two different ways, see
                    below:</p>
                <p><sourcexml>case:constituents/@constituenttype=”counsel”/p/text</sourcexml>
                    becomes
                        <targetxml>seclaw:body/seclaw:digestgrp/seclaw:digest/seclaw:digestinfo/caseinfo:caseinfo/courtcase:representation/courtcase:counsel</targetxml>.</p>
            </section>
            <example>
                <title>Example 1</title>
                <codeblock> &lt;case:info&gt; &lt;case:constituents constituenttype="counsel"&gt;
                    &lt;p&gt; &lt;text&gt;No counsel mentioned.&lt;/text&gt; &lt;/p&gt;
                    &lt;/case:constituents&gt; &lt;/case:info&gt; </codeblock>
                <b>becomes</b>
                <codeblock> &lt;seclaw:body&gt; &lt;seclaw:digestgrp&gt; &lt;seclaw:digest&gt;
                    &lt;seclaw:digestinfo&gt; &lt;caseinfo:caseinfo&gt;
                    &lt;courtcase:representation&gt; &lt;courtcase:counsel&gt;No counsel
                    mentioned.&lt;/courtcase:counsel&gt; &lt;/courtcase:representation&gt;
                    &lt;/caseinfo:caseinfo&gt; &lt;/seclaw:digestinfo&gt; &lt;/seclaw:digest&gt;
                    &lt;/seclaw:digestgrp&gt; &lt;/seclaw:body&gt; </codeblock>
            </example>
            <section>
                <p><sourcexml>case:constituents/@constituenttype=”consultant”/p/text</sourcexml>
                    becomes
                        <targetxml>seclaw:body/seclaw:digestgrp/seclaw:digest/seclaw:digestinfo/caseinfo:caseinfo/courtcase:testimony/courtcase:expertwitnesses/courtcase:expertwitness</targetxml>.</p>
            </section>
            <example>
                <title>Example 1</title>
                <codeblock> &lt;case:info&gt; &lt;case:constituents constituenttype="consultant"&gt;
                    &lt;p&gt; &lt;text&gt;Dr. Kristina Dervaitis, Dr. Mundle, Dr. Radomski, Dr.
                    Holliday.&lt;/text&gt; &lt;/p&gt; &lt;/case:constituents&gt; &lt;/case:info&gt; </codeblock>
                <b>becomes</b>
                <codeblock> &lt;seclaw:body&gt; &lt;seclaw:digestgrp&gt; &lt;seclaw:digest&gt;
                    &lt;seclaw:digestinfo&gt; &lt;caseinfo:caseinfo&gt; &lt;courtcase:testimony&gt;
                    &lt;courtcase:expertwitnesses&gt; &lt;courtcase:expertwitness&gt;Dr. Kristina
                    Dervaitis, Dr. Mundle, Dr. Radomski, Dr.
                    Holliday.&lt;/courtcase:expertwitness&gt; &lt;/courtcase:expertwitnesses&gt;
                    &lt;/courtcase:testimony&gt; &lt;/caseinfo:caseinfo&gt;
                    &lt;/seclaw:digestinfo&gt; &lt;/seclaw:digest&gt; &lt;/seclaw:digestgrp&gt;
                    &lt;/seclaw:body&gt; </codeblock>
            </example>

            <section>
                <title>Changes</title>
                <p>2015-03-25: <ph id="change_20150325_jm">Not a rule change. Removed note about a
                        pending schema change. Schema now allows
                            <targetxml>caseinfo:caseinfo/courtcase:testimony</targetxml></ph></p>
                <p>2015-02-20: <ph id="change_20150220_PS">Created.</ph></p>
            </section>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA14-Emerging_Issues\case.constituents.dita  -->

    <!-- Vikas Rohilla : template to match the case:case:constituents [@constituenttype = 'counsel'] and creats the courtcase:representation/courtcase:counsel  -->
    <xsl:template match="case:constituents[@constituenttype = 'counsel']">
        <courtcase:representation>
            <courtcase:counsel>
                <xsl:apply-templates select="@* | node()"/>
            </courtcase:counsel>
        </courtcase:representation>
    </xsl:template>

    <!-- Vikas Rohilla : template to match the case:case:constituents [@constituenttype = 'consultant'] and creats the courtcase:testimony/courtcase:expertwitnesses/courtcase:expertwitness  -->
    <xsl:template match="case:constituents[@constituenttype = 'consultant']">
        <courtcase:testimony>
            <courtcase:expertwitnesses>
                <courtcase:expertwitness>
                    <xsl:apply-templates select="@* | node()"/>
                </courtcase:expertwitness>
            </courtcase:expertwitnesses>
        </courtcase:testimony>
    </xsl:template>

    <!--Vikas Rohilla : Template to match the p[parent::case:constituents] and process the childs nodes-->
    <xsl:template match="p[parent::case:constituents]">
        <xsl:apply-templates select="@* | node()"/>
    </xsl:template>

    <!--Vikas Rohilla : Template to match the text[parent::case:constituents] and process the childs nodes-->
    <xsl:template match="text[ancestor::case:constituents]">
        <xsl:apply-templates select="@* | node()"/>
    </xsl:template>

    <!--Vikas Rohilla : supressed case:constituents/@constituenttype -->
    <xsl:template match="case:constituents/@constituenttype"/>



</xsl:stylesheet>
