<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.embeddedcase-courtcase.caseexcerpt">
   <title>case:embeddedcase <lnpid>id-ST01-26234</lnpid></title>
   <body>
      <section>
<ul>
         <li class="- topic/li ">
                    <sourcexml>case:embeddedcase</sourcexml>
                    becomes <targetxml>courtcase:caseexcerpt</targetxml> and attribute <sourcexml>@id</sourcexml> becomes <targetxml>@xml:id</targetxml>. <note><targetxml>courtcase:caseexcerpt/@xml:id</targetxml> that begins with a number
                        must have an underscore added at start.</note>
                    <note>If <sourcexml>case:embeddedcase</sourcexml>
                        occurs as a child element of <sourcexml>blockquote</sourcexml> then
                        conversion need to omit tag (<sourcexml>blockquote</sourcexml>) and
                        retain content.</note>
                    <pre xml:space="preserve" class="- topic/pre ">

&lt;case:decisionsummary&gt;
  &lt;blockquote&gt;
      &lt;case:embeddedcase id="1980_QD_R_411"&gt;
            &lt;case:content&gt;
                &lt;case:judgments&gt;
                    &lt;case:judgment subdoc="true" toc-caption="Judgment 1"&gt;
                        &lt;case:judgmentbody&gt;
                            &lt;p&gt;
                                &lt;text&gt;This was an action...&lt;/text&gt;
                            &lt;/p&gt;
                        &lt;/case:judgmentbody&gt;
                    &lt;/case:judgment&gt;
                &lt;/case:judgments&gt;
            &lt;/case:content&gt;
      &lt;/case:embeddedcase&gt;
  &lt;/blockquote&gt;
&lt;/case:decisionsummary&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;casesum:decisionsummary&gt;
            &lt;courtcase:caseexcerpt xml:id="_1980_QD_R_411"&gt;
                &lt;courtcase:body&gt;
                    &lt;courtcase:opinions&gt;
                        &lt;courtcase:opinion includeintoc="true" alternatetoccaption="Judgment 1"&gt;
                            &lt;bodytext&gt;
                                &lt;p&gt;
                                    &lt;text&gt;This was an action...&lt;/text&gt;
                                &lt;/p&gt;
                            &lt;/bodytext&gt;
                        &lt;/courtcase:opinion&gt;
                    &lt;/courtcase:opinions&gt;
                &lt;/courtcase:body&gt;    
            &lt;/courtcase:caseexcerpt&gt;
&lt;/casesum:decisionsummary&gt;

</pre>
                </li>
      </ul>
      </section>
       <!--section>
           <title>Changes</title>
           <p>2012-08-23: Modified instructions to use an underscore instead of the two digit country code for <targetxml>xml:id</targetxml>.</p>
       </section-->
       
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\courtcase\case.embeddedcase-courtcase.caseexcerpt.dita  -->
	<xsl:message>case.embeddedcase-courtcase.caseexcerpt.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:embeddedcase">

		<!--  Original Target XPath:  courtcase:caseexcerpt   -->
		<courtcase:caseexcerpt>
			<xsl:apply-templates select="@* | node()"/>
		</courtcase:caseexcerpt>

	</xsl:template>

	<xsl:template match="@id">

		<!--  Original Target XPath:  @xml:id   -->
		<xsl:attribute name="xml:id">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="blockquote">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>