<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_case.length-LxAdv_doc.doclength">
    <title>case:length <lnpid>id-ST01-26218</lnpid></title>
    <body>
        <section conref="../../common_caselaw/conref_content/Rosetta_case.length-LxAdv_doc.doclength.dita#Rosetta_case.length-LxAdv_doc.doclength/mapping"/>
        <example>
            <codeblock>
&lt;case:length&gt;47 Paragraphs&lt;/case:length&gt;
       </codeblock>
            <b>becomes</b>
            <codeblock>
&lt;doc:metadata&gt;
    &lt;doc:docinfo&gt;
        ...
        &lt;doc:doclength num="47" unit="Paragraphs" source="conversion"/&gt;
        ...
    &lt;/doc:docinfo&gt;
&lt;/doc:metadata&gt;
       </codeblock>
        </example>
        <p>When we have 2 types of value in <sourcexml>case:length</sourcexml> element then
            conversion should create seperate <targetxml>doc:length</targetxml> element for each
            value.</p>
        <example>
            <codeblock>      
&lt;case:length&gt;(43 pages) (127 paras.)&lt;/case:length&gt;
        </codeblock>
            <b>becomes</b>
            <codeblock>
&lt;doc:metadata&gt;
    &lt;doc:docinfo&gt;
        &lt;dc:metadata&gt;
            ...
        &lt;/dc:metadata&gt;
        &lt;doc:doclength num="43" unit="pages" source="conversion"/&gt;
        &lt;doc:doclength num="127" unit="paras" source="conversion"/&gt;
    &lt;/doc:docinfo&gt;
&lt;/doc:metadata&gt;
        </codeblock>
        </example>
        <note>If <sourcexml>case:length</sourcexml> occurs within
                <sourcexml>case:embeddedcase</sourcexml>, then conversion should suppress
                <sourcexml>case:length</sourcexml> and its content.</note>

    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\courtcase\case.length-doc.length.dita  -->
	<xsl:message>case.length-doc.length.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:length">

		<!--  Original Target XPath:  doc:length   -->
		<doc:length>
			<xsl:apply-templates select="@* | node()"/>
		</doc:length>

	</xsl:template>

	<xsl:template match="case:embeddedcase">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>