<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="AU01_case.libnum-LxAdv_refnum-refnumscheme">
   <title>case:libnum  <lnpid>id-ST01-26207</lnpid></title>
   <body>
      <section>
<ul>
         <li class="- topic/li ">
          <sourcexml>case:libnum</sourcexml> becomes
            <targetxml>jurisinfo:courtinfo/refnum/@refnumscheme="[jx]-[country]-library-number"</targetxml>, where [jx] is the jurisdiction defined in case:juris, and [country] is the two-digit country code.
          <pre xml:space="preserve" class="- topic/pre ">

&lt;case:info&gt;
  ...
  &lt;case:courtinfo&gt;
    ...
    &lt;case:filenum&gt;No. CIV 1695 of 1993&lt;/case:filenum&gt;
    &lt;case:dates&gt;
      &lt;case:hearingdates&gt;23 September 1996&lt;/case:hearingdates&gt;
      &lt;case:decisiondate&gt;
        &lt;date day="11" month="10" year="1996"&gt;, 11 October 1996&lt; /date&gt;
      &lt;/case:decisiondate&gt;
    &lt;/case:dates&gt;
    &lt;case:libnum&gt;960591&lt;/case:libnum&gt;
    &lt;case:juris&gt;wa&lt;/case:juris&gt;
  &lt;/case:courtinfo&gt;
&lt;/case:info&gt;
<b>Becomes</b>

&lt;caseinfo:caseinfo&gt;
  ...
  &lt;caseinfo:docketnum&gt;No. CIV 1695 of 1993&lt;/caseinfo:docketnum&gt;
  &lt;jurisinfo:courtinfo&gt;
    &lt;jurisinfo:courtname&gt;SUPREME COURT OF WESTERN AUSTRALIA IN CHAMBERS&lt;/jurisinfo:courtname&gt;
    &lt;refnum refnumscheme="wa-AU-library-number"&gt;960591&lt;/refnum&gt;
  &lt;/jurisinfo:courtinfo&gt;
  &lt;decision:dates&gt;
    &lt;decision:argueddate&gt;23 September 1996&lt;/decision:argueddate&gt;
    &lt;decision:decisiondate day="11" month="10" year="1996"&gt;, 
      &lt;datetext&gt;11 October 1996&lt;/datetext&gt;
    &lt;/decision:decisiondate&gt;
  &lt;/decision:dates&gt;
&lt;/caseinfo:caseinfo&gt;

</pre>
        </li>
      </ul>
</section>
     <section>
       <title>Changes</title>
       <p>2014-07-31: <ph id="change_20140731_brt">Modified AU-specific instruction to generic instruction.</ph></p>
     </section>
     
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\courtcase\case.libnum-refnum-refnumscheme.dita  -->
	<xsl:message>case.libnum-refnum-refnumscheme.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:libnum">

		<!--  Original Target XPath:  jurisinfo:courtinfo/refnum/@refnumscheme="[jx]-[country]-library-number"   -->
		<jurisinfo:courtinfo>
			<refnum>
				<!--  Could not determine target element or attribute name:  <@refnumscheme="[jx]-[country]-library-number">  -->					<xsl:apply-templates select="@* | node()"/>
				<!--  Could not determine target element or attribute name:  </@refnumscheme="[jx]-[country]-library-number">  -->
			</refnum>
		</jurisinfo:courtinfo>

	</xsl:template>

</xsl:stylesheet>