<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:ci="http://www.lexis-nexis.com/ci" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita case ci">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.parallelcite-ref.cite4thisresource">
  <title>case:parallelcite <lnpid>id-ST01-26219</lnpid></title>
  <body>
    <section conref="../../common_caselaw/conref_content/Rosetta_case.parallelcite-LxAdv_ref.cite4thisresource.dita#Rosetta_case.parallelcite-LxAdv_ref.cite4thisresource/mapping"/>
    <example>
      <codeblock>
&lt;case:info&gt;
  &lt;case:parallelcite&gt;
    &lt;ci:cite type="cite4thisdoc"&gt;
      &lt;ci:case&gt;
        &lt;ci:caseref&gt;
          &lt;ci:reporter value="EWCACIV"/&gt;
          &lt;ci:edition&gt;
            &lt;ci:date year="2001"/&gt;
          &lt;/ci:edition&gt;
          &lt;ci:page num="33"/&gt;
        &lt;/ci:caseref&gt;
      &lt;/ci:case&gt;
      &lt;ci:content&gt;
        &lt;citefragment searchtype="CASE-CITE-REF"&gt;[2001] EWCA Civ 33&lt;/citefragment&gt;
      &lt;/ci:content&gt;
    &lt;/ci:cite&gt;
  &lt;/case:parallelcite&gt;
&lt;/case:info&gt;
    </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;caseinfo:caseinfo&gt;
  &lt;ref:citations&gt;
    &lt;ref:cite4thisresource citetype="parallel"&gt;
      &lt;lnci:cite&gt;
        &lt;lnci:case&gt;
          &lt;lnci:caseref&gt;
            &lt;lnci:reporter value="EWCACIV"/&gt;
            &lt;lnci:edition&gt;
              &lt;lnci:date year="2001"/&gt;
            &lt;/lnci:edition&gt;
            &lt;lnci:page num="33"/&gt;
          &lt;/lnci:caseref&gt;
        &lt;/lnci:case&gt;
        &lt;lnci:content&gt;[2001] EWCA Civ 33&lt;/lnci:content&gt;
      &lt;/lnci:cite&gt;
    &lt;/ref:cite4thisresource&gt;
  &lt;/ref:citations&gt;
&lt;/caseinfo:caseinfo&gt;
    </codeblock>
    </example>
    <section>
      <p>Text (PCDATA) occuring in between <sourcexml>case:parallelcite</sourcexml> and
          <sourcexml>ci:cite</sourcexml> should be moved inside a <targetxml>connector</targetxml>
        element and put in between multiple <targetxml>ref:cite4thisresource</targetxml> elements if
        needed.</p>
    </section>
    <example>
      <codeblock>
&lt;case:parallelcite&gt; (Case &lt;ci:cite searchtype="CASE-REF"&gt;
    &lt;ci:case&gt;
      &lt;ci:caseref&gt;
        &lt;ci:reporter value="C"/&gt;
        &lt;ci:edition&gt;
          &lt;ci:date year="2000"/&gt;
        &lt;/ci:edition&gt;
        &lt;ci:page num="256"/&gt;
      &lt;/ci:caseref&gt;
    &lt;/ci:case&gt;
    &lt;ci:content&gt; C-256/00 &lt;/ci:content&gt;
  &lt;/ci:cite&gt; ) &lt;/case:parallelcite&gt;
    </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;ref:citations&gt;
  &lt;connector&gt;(Case &lt;/connector&gt;
  &lt;ref:cite4thisresource citetype="parallel"&gt;
    &lt;lnci:cite&gt;
      &lt;lnci:case&gt;
        &lt;lnci:caseref&gt;
          &lt;lnci:reporter value="C"/&gt;
          &lt;lnci:edition&gt;
            &lt;lnci:date year="2000"/&gt;
          &lt;/lnci:edition&gt;
          &lt;lnci:page num="256"/&gt;
        &lt;/lnci:caseref&gt;
      &lt;/lnci:case&gt;
      &lt;lnci:content&gt; C-256/00 &lt;/lnci:content&gt;
    &lt;/lnci:cite&gt;
  &lt;/ref:cite4thisresource&gt;
  &lt;connector&gt;)&lt;/connector&gt;
&lt;/ref:citations&gt;
    </codeblock>
    </example>
  
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\courtcase\case.parallelcite-ref.cite4thisresource.dita  -->
	<xsl:message>case.parallelcite-ref.cite4thisresource.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:parallelcite">

		<!--  Original Target XPath:  connector   -->
		<connector>
			<xsl:apply-templates select="@* | node()"/>
		</connector>

	</xsl:template>

	<xsl:template match="ci:cite">

		<!--  Original Target XPath:  connector   -->
		<connector>
			<xsl:apply-templates select="@* | node()"/>
		</connector>

	</xsl:template>

</xsl:stylesheet>