<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.judgment-courtcase.opinion">
  <title>case:judgment <lnpid>id-ST01-26237</lnpid></title>
  <body>
    <section conref="../../common_caselaw/conref_content/Rosetta_case.judgment-LxAdv_courtcase.opinion.dita#Rosetta_case.judgment-LxAdv_courtcase.opinion/mapping"/>
    <section>
      <p>The optional attributes of <sourcexml>case:judgment</sourcexml> are handled as follows:<ul>
          <li><sourcexml>case:judgment/@subdoc</sourcexml> becomes
              <targetxml>courtcase:opinion/@includeintoc</targetxml>.</li>
          <li><sourcexml>case:judgment/@toc-caption</sourcexml> becomes
              <targetxml>courtcase:opinion/@alternatetoccaption</targetxml>.</li>
          <li><sourcexml>case:judgment/@searchtype</sourcexml> should be suppressed.</li>
        </ul></p>
    </section>
    <example>
      <codeblock>
&lt;case:judgment subdoc="true" toc-caption="Perram  J."&gt;
   &lt;case:judgmentbody&gt;
      &lt;p&gt;
        &lt;text&gt;&lt;emph typestyle="bf"&gt;MITCHELL, J.&lt;/emph&gt; (for the Court, allowing the appeal): This
          case concerns the interpretation of municipal bylaws and the availability of injunctive
          relief to restrain their violation.&lt;/text&gt;
      &lt;/p&gt;
      ...
    &lt;/case:judgmentbody&gt;
&lt;/case:judgment&gt;
       </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;courtcase:opinion includeintoc="true" alternatetoccaption="Perram  J."&gt;
  &lt;bodytext&gt;
      &lt;p&gt;
        &lt;text&gt;&lt;emph typestyle="bf"&gt;MITCHELL, J.&lt;/emph&gt; (for the Court, allowing the appeal): This
          case concerns the interpretation of municipal bylaws and the availability of injunctive
          relief to restrain their violation.&lt;/text&gt;
      &lt;/p&gt;
      ...
    &lt;/bodytext&gt;
&lt;/courtcase:opinion&gt;
       </codeblock>
    </example>
    <!--<section>
            <title>Changes Specific to AU01</title>
            </section>-->

  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\courtcase\case.judgment-courtcase.opinion.dita  -->
	<xsl:message>case.judgment-courtcase.opinion.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:judgment">

		<!--  Original Target XPath:  courtcase:opinion/@includeintoc   -->
		<courtcase:opinion>
			<xsl:attribute name="includeintoc">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</courtcase:opinion>

	</xsl:template>

	<xsl:template match="case:judgment/@subdoc">

		<!--  Original Target XPath:  courtcase:opinion/@includeintoc   -->
		<courtcase:opinion>
			<xsl:attribute name="includeintoc">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</courtcase:opinion>

	</xsl:template>

	<xsl:template match="case:judgment/@toc-caption">

		<!--  Original Target XPath:  courtcase:opinion/@alternatetoccaption   -->
		<courtcase:opinion>
			<xsl:attribute name="alternatetoccaption">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</courtcase:opinion>

	</xsl:template>

	<xsl:template match="case:judgment/@searchtype">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>