<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.dates">
  <title>case:dates <lnpid>id-ST05-28421</lnpid></title>
  <body>
    <section>
      <p>
        <sourcexml>case:dates</sourcexml> becomes <targetxml>/compcase:head/compcase:caseinstanceinfo/decision:dates</targetxml>
        <note>The formatting of the <targetxml>date-text</targetxml> should not be normalized to <b>YYYY-MM-DD</b>. The attributes are used for
            normalization, but the element content should remain the same but whitespace and comma should retain outside the 
          <targetxml>date-text</targetxml> element.</note>
      </p>
    </section>
    <section>
      <title>Changes</title>
      <p>2014-05-15: <ph id="change_20140515_SS">Created.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Compcase\case.dates.dita  -->
	<xsl:message>Compcase_case.dates.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:dates">

		<!--  Original Target XPath:  /compcase:head/compcase:caseinstanceinfo/decision:dates   -->
		<compcase:head xmlns:compcase="urn:x-lexisnexis:content:compositecourtcase:sharedservices:1">
			<compcase:caseinstanceinfo>
				<decision:dates xmlns:decision="http://www.lexisnexis.com/xmlschemas/content/legal/decision/1/">
					<xsl:apply-templates select="@* | node()"/>
				</decision:dates>
			</compcase:caseinstanceinfo>
		</compcase:head>

	</xsl:template>

</xsl:stylesheet>