<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.courtloc">
  <title>case:courtloc <lnpid>id-ST05-28419</lnpid></title>
  <body>
    <section>
      <ul>
        <li>
          <sourcexml>case:courtloc</sourcexml> becomes
            <targetxml>/compcase:head/compcase:caseinstanceinfo/jurisinfo:courtinfo/jurisinfo:jurisdiction/jurisinfo:location/location:city</targetxml>
        </li>
      </ul>
    </section>
    
    
    <example>
      <title>Source XML based on AU content</title>
      <codeblock>

&lt;case:courtinfo&gt;
  &lt;case:courtname&gt;FEDERAL COURT OF AUSTRALIA&lt;/case:courtname&gt;
  &lt;case:courtcode&gt;FCA&lt;/case:courtcode&gt;  - will be moved under doc:legacy-metadata.
  &lt;case:courtloc&gt;Sydney&lt;/case:courtloc&gt;
&lt;/case:courtinfo&gt;

       </codeblock>
     </example>
     
     <example>
       <title>Target XML</title>
       <codeblock>

                              
&lt;compcase:head&gt;
  &lt;compcase:caseinstanceinfo&gt;
    &lt;jurisinfo:courtinfo&gt;
      &lt;jurisinfo:courtname&gt;FEDERAL COURT OF AUSTRALIA&lt;/jurisinfo:courtname&gt;
      &lt;jurisinfo:jurisdiction&gt;
        &lt;jurisinfo:location&gt;
          &lt;location:city&gt;Sydney&lt;/location:city&gt;
        &lt;/jurisinfo:location&gt;
      &lt;/jurisinfo:jurisdiction&gt;
    &lt;/jurisinfo:courtinfo&gt;
  &lt;/compcase:caseinstanceinfo&gt;
&lt;/compcase:head&gt;

       </codeblock>
     </example>
    
          <note>Connecting punctuation and text must be captured by using
              <targetxml>connector</targetxml> within
            <targetxml>jurisinfo:location</targetxml>.</note>
    <example>
      <title>Source XML based on AU content</title>
      <codeblock>

&lt;case:courtinfo&gt;
    &lt;case:courtname&gt;COMMERCIAL TRIBUNAL OF NEW SOUTH WALES&lt;/case:courtname&gt; 
    &lt;case:courtcode&gt;NSWSC&lt;/case:courtcode&gt; 
    &lt;case:judges&gt;
        Deputy Chairman 
        &lt;case:judge&gt;Vermeesch&lt;/case:judge&gt; 
    &lt;/case:judges&gt;
    &lt;case:dates&gt;
        &lt;case:decisiondate&gt;
            &lt;date day="19" month="12" year="1994"&gt;19 December 1994&lt;/date&gt; 
        &lt;/case:decisiondate&gt;
    &lt;/case:dates&gt;
    — 
    &lt;case:courtloc&gt;Sydney&lt;/case:courtloc&gt; 
    &lt;case:juris&gt;nsw&lt;/case:juris&gt; 
&lt;/case:courtinfo&gt;


       </codeblock>
     </example>
     
     <example>
       <title>Target XML</title>
       <codeblock>


&lt;jurisinfo:courtinfo&gt;
    &lt;jurisinfo:courtname&gt;COMMERCIAL TRIBUNAL OF NEW SOUTH WALES&lt;/jurisinfo:courtname&gt;
    &lt;jurisinfo:jurisdiction&gt;
        &lt;jurisinfo:location&gt;
            &lt;connector&gt;
            —
            &lt;/connector&gt;
            &lt;location:city&gt;Sydney&lt;/location:city&gt;
        &lt;/jurisinfo:location&gt;
    &lt;/jurisinfo:jurisdiction&gt;
&lt;/jurisinfo:courtinfo&gt;


       </codeblock>
     </example>
    <section>
      <title>Changes</title>
      <p>2014-05-15: <ph id="change_20140515_SS">Created.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Compcase\case.courtloc.dita  -->
	<xsl:message>Compcase_case.courtloc.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:courtloc">

		<!--  Original Target XPath:  /compcase:head/compcase:caseinstanceinfo/jurisinfo:courtinfo/jurisinfo:jurisdiction/jurisinfo:location/location:city   -->
		<compcase:head xmlns:compcase="urn:x-lexisnexis:content:compositecourtcase:sharedservices:1">
			<compcase:caseinstanceinfo>
				<jurisinfo:courtinfo>
					<jurisinfo:jurisdiction>
						<jurisinfo:location>
							<location:city xmlns:location="http://www.lexisnexis.com/xmlschemas/content/shared/location/1/">
								<xsl:apply-templates select="@* | node()"/>
							</location:city>
						</jurisinfo:location>
					</jurisinfo:jurisdiction>
				</jurisinfo:courtinfo>
			</compcase:caseinstanceinfo>
		</compcase:head>

	</xsl:template>

</xsl:stylesheet>