<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:compcase="urn:x-lexisnexis:content:compositecourtcase:sharedservices:1" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.judgmentbody">
   <title>case:judgmentbody <lnpid>id-ST05-28432</lnpid></title>
   <body>
      <section>
          <ul>
         <li>
                    <sourcexml>case:judgmentbody</sourcexml>
                    becomes <targetxml>compcase:body/compcase:caseinstance/compcase:caseinstancebody/courtcase:opinions/courtcase:opinion/bodytext</targetxml>.</li>
          </ul>
      </section>
       <example>
           <title>Source XML based on AU content</title>
           <codeblock>

&lt;case:judgmentbody&gt;
    &lt;pgrp&gt;
        &lt;heading&gt;&lt;title&gt;Background&lt;/title&gt;&lt;/heading&gt;
        &lt;p&gt;
            &lt;pnum count="1"&gt;[1]&lt;/pnum&gt;
            &lt;text&gt;The present applicants are five individuals who at one time or another were engaged by Combined Insurance Company of America (Combined) as insurance agents. In recent times, the five have sued Combined in the Chief Industrial Magistrates&amp;amp;#x2019; Court of New South Wales claiming entitlements both to annual leave and long service leave. One of the principal issues to be resolved in those proceedings is the question of whether the agents were employees of Combined, as they contend, or rather independent contractors, as Combined contends. No doubt the resolution of that issue will involve a close consideration of a broad range of indicia. One of the matters to which Combined points is a term in its contract with each agent by which each agreed, or appears to have agreed, that his relationship with Combined was not one of employment.&lt;/text&gt;
        &lt;/p&gt;
    &lt;/pgrp&gt;
    ...
&lt;/case:judgmentbody&gt;


    </codeblock>
     </example>
     
     <example>
       <title>Target XML</title>
       <codeblock>

&lt;courtcase:opinion&gt;
    &lt;bodytext&gt;
        &lt;pgrp&gt;
            &lt;heading&gt;&lt;title&gt;Background&lt;/title&gt;&lt;/heading&gt;
            &lt;p&gt;
                &lt;desig value="1"&gt;[1]&lt;/desig&gt;
                &lt;text&gt;The present applicants are five individuals who at one time or another were engaged by Combined Insurance Company of America (Combined) as insurance agents. In recent times, the five have sued Combined in the Chief Industrial Magistrates&amp;amp;#x2019; Court of New South Wales claiming entitlements both to annual leave and long service leave. One of the principal issues to be resolved in those proceedings is the question of whether the agents were employees of Combined, as they contend, or rather independent contractors, as Combined contends. No doubt the resolution of that issue will involve a close consideration of a broad range of indicia. One of the matters to which Combined points is a term in its contract with each agent by which each agreed, or appears to have agreed, that his relationship with Combined was not one of employment.&lt;/text&gt;
            &lt;/p&gt;
        &lt;/pgrp&gt;
    ...
    &lt;/bodytext&gt;
&lt;/courtcase:opinion&gt;

    </codeblock>
     </example>
       <section>
           <title>Changes</title>
           <p>2014-05-15: <ph id="change_20140515_SS">Created.</ph></p>
       </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Compcase\case.judgmentbody.dita  -->
	<xsl:message>Compcase_case.judgmentbody.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:judgmentbody">

		<!--  Original Target XPath:  compcase:body/compcase:caseinstance/compcase:caseinstancebody/courtcase:opinions/courtcase:opinion/bodytext   -->
		<compcase:body>
			<compcase:caseinstance>
				<compcase:caseinstancebody>
					<courtcase:opinions xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/">
						<courtcase:opinion>
							<bodytext>
								<xsl:apply-templates select="@* | node()"/>
							</bodytext>
						</courtcase:opinion>
					</courtcase:opinions>
				</compcase:caseinstancebody>
			</compcase:caseinstance>
		</compcase:body>

	</xsl:template>

</xsl:stylesheet>