<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
  xmlns:location="http://www.lexisnexis.com/xmlschemas/content/shared/location/1/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="AU01_Rosetta_case.juris">
  <title>case:juris <lnpid>id-HK03-37222</lnpid>
  </title>
  <body>
    <ul id="ul_xtc_gqy_2v">
      <li>
        <sourcexml>case:juris</sourcexml> has Country code: <note>If value for
            <sourcexml>case:juris</sourcexml> is "CTH" then <sourcexml>case:juris</sourcexml> will
          become <targetxml>jurisinfo:courtinfo/jurisinfo:jurisdiction/jurisinfo:system</targetxml>
          and create <targetxml>dc:metadata/dc:coverage/location:country</targetxml> with attributes
          @codescheme="ISO-3166-1" and @countrycode="HK". </note>
        <pre xml:space="preserve">
&lt;case:juris&gt;hk&lt;/case:juris&gt;

<b>Becomes</b>
              
&lt;jurisinfo:courtinfo&gt;
  &lt;jurisinfo:jurisdiction&gt;
    &lt;jurisinfo:system&gt;hk&lt;/jurisinfo:system&gt;
  &lt;/jurisinfo:jurisdiction&gt;
&lt;/jurisinfo:courtinfo&gt;

&lt;dc:metadata&gt;
  &lt;dc:coverage&gt;
    &lt;location:country codescheme="ISO-3166-1" countrycode="HK"/&gt;
  &lt;/dc:coverage&gt;
&lt;/dc:metadata&gt;
</pre>
        <note>The ordering of the <targetxml>jurisinfo:alternatecourtcode</targetxml> and
            <targetxml>jurisinfo:jurisdiction\jurisinfo:system</targetxml> is not significant in
          terms of display.</note>
      </li>
      <li> </li>
    </ul>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-HK\HK03\HK03_Rosetta_case.juris.dita  -->
	 

	<xsl:template match="case:juris">

		<!--  Original Target XPath:  jurisinfo:courtinfo/jurisinfo:jurisdiction/jurisinfo:system   -->
		
			<jurisinfo:jurisdiction>
				<jurisinfo:system>
					<xsl:apply-templates select="@* | node()"/>
				</jurisinfo:system>
			</jurisinfo:jurisdiction>
	</xsl:template>
  
  <xsl:template match="case:courtinfo[1]/case:juris" mode="metadata">
    <dc:coverage>
      <location:country>
        <xsl:attribute name="countrycode" select="'HK'"/>
        <xsl:attribute name="codescheme">ISO-3166-1</xsl:attribute>       
      </location:country>						
    </dc:coverage>
  </xsl:template>

</xsl:stylesheet>