<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" 
  xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/"
  xmlns:ci="http://www.lexis-nexis.com/ci" version="2.0" exclude-result-prefixes="dita case ci">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="HK03_Rosetta_case.parallelcite-LxAdv_ref.cite4thisresource">
  <title>case:parallelcite <lnpid>id-HK03-37224</lnpid></title>
  <body>
    <section conref="../../common_caselaw/conref_content/Rosetta_case.parallelcite-LxAdv_ref.cite4thisresource.dita#Rosetta_case.parallelcite-LxAdv_ref.cite4thisresource/mapping"/>
    <section><note>Text occurring between <sourcexml>case:parallelcite</sourcexml> and
          <sourcexml>ci:cite</sourcexml> should be dropped since it will be handled on a
        presentation spec level.</note></section>
    <example>
      <codeblock>
&lt;case:info&gt;
    &lt;case:parallelcite&gt;Also reported at: &lt;ci:cite searchtype="CASE-REF"&gt;
        &lt;ci:case&gt;
            &lt;ci:caseref ID="cr000001" spanref="cr000001-001"&gt;
                &lt;ci:reporter value="HKLR"/&gt;
                &lt;ci:edition&gt;
                    &lt;ci:date year="1977"/&gt;
                &lt;/ci:edition&gt;
                &lt;ci:page num="226"/&gt;
            &lt;/ci:caseref&gt;
        &lt;/ci:case&gt;
        &lt;ci:content&gt;
            &lt;citefragment searchtype="CASE-CITE-REF"&gt;
                &lt;ci:span spanid="cr000001-001"&gt;[1977] HKLR 226&lt;/ci:span&gt;
            &lt;/citefragment&gt;
        &lt;/ci:content&gt;
    &lt;/ci:cite&gt;
    &lt;/case:parallelcite&gt;
&lt;/case:info&gt;
           </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;caseinfo:caseinfo&gt;
  &lt;ref:citations&gt;
    &lt;ref:cite4thisresource citetype="parallel"&gt;
      &lt;lnci:cite&gt;
        &lt;lnci:case&gt;
          &lt;lnci:caseref ID="cr000001"&gt;
            &lt;lnci:reporter value="HKLR"/&gt;            
            &lt;lnci:edition&gt;
              &lt;lnci:date year="1977"/&gt;
            &lt;/lnci:edition&gt;
            &lt;lnci:page num="226"/&gt;
          &lt;/lnci:caseref&gt;
        &lt;/lnci:case&gt;
        &lt;lnci:content&gt;[1977] HKLR 226&lt;/lnci:content&gt;
      &lt;/lnci:cite&gt;
    &lt;/ref:cite4thisresource&gt;
  &lt;/ref:citations&gt;
&lt;/caseinfo:caseinfo&gt;
           </codeblock>
    </example>
    
    <!--<section>
            <title>Changes Specific to CA01</title>
            </section>-->

  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-HK\HK03\HK03_Rosetta_case.parallelcite-LxAdv_ref.cite4thisresource.dita  -->
	 

	<xsl:template match="case:parallelcite">

	  <ref:citations>
	    <ref:cite4thisresource>
	      <xsl:attribute name="citetype">
	        <xsl:text>parallel</xsl:text>
	      </xsl:attribute>
	      <xsl:apply-templates select="@* | node()"/>
	    </ref:cite4thisresource>			
	  </ref:citations>
	</xsl:template>

  <xsl:template match="case:parallelcite[@ln.user-displayed]"/>

  <!-- Note: Text occurring between case:parallelcite and ci:cite should be dropped since it will be handled on a presentation spec level. -->

  <xsl:template match="text()[parent::case:parallelcite]"/>
    
  

</xsl:stylesheet>