<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" 
  xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" 
  xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="HK09_Rosetta_case.citations-LxAdv_ref.relatedrefs">
	  <title>case:citations <lnpid>id-HK09-39436</lnpid></title>
  <body>
    <section>
      <ul>
        <li>
          <sourcexml>case:citations</sourcexml> becomes <targetxml> compcase:head
            /ref:relatedrefs</targetxml> with an attribute 'referencetype' set to
            <targetxml>@referencetype="case-citations"</targetxml> which contains
            <sourcexml>case:citetext</sourcexml> becomes
            <targetxml>ref:relatedrefs/bodytext/p/text</targetxml>
          <pre xml:space="preserve">

&lt;case:citations&gt;
  &lt;heading&gt;
    &lt;title&gt;C&lt;emph typestyle="smcaps"&gt;ASES&lt;/emph&gt; C&lt;emph typestyle="smcaps"&gt;ITED&lt;/emph&gt;&lt;/title&gt;
  &lt;/heading&gt;
  &lt;case:citetext&gt;The following cases are cited in the judgment:&lt;nl/&gt;
    &lt;ci:cite searchtype="CASE-REF"&gt;
      &lt;ci:content&gt;
        &lt;citefragment searchtype="CASE-NAME-REF"&gt;&lt;emph typestyle="it"&gt;Allgood v Blake&lt;/emph&gt;&lt;/citefragment&gt; 
        &lt;citefragment searchtype="CASE-CITE-REF"&gt;(1873) LR 8 Exch 160&lt;/citefragment&gt;.
      &lt;/ci:content&gt;
    &lt;/ci:cite&gt;&lt;nl/&gt;
    &lt;ci:cite searchtype="CASE-REF"&gt;
      &lt;ci:content&gt;
        &lt;citefragment searchtype="CASE-NAME-REF"&gt;&lt;emph typestyle="it"&gt;Amber Holdings (Aust) Pty Ltd v Polona Pty Ltd&lt;/emph&gt;&lt;/citefragment&gt; 
        &lt;citefragment searchtype="CASE-CITE-REF"&gt;[1982] 2 NSWLR 470&lt;/citefragment&gt;.
      &lt;/ci:content&gt;
    &lt;/ci:cite&gt;&lt;nl/&gt;
  &lt;/case:citetext&gt;
&lt;/case:citations&gt;
<b>Becomes:</b>

&lt;ref:relatedrefs referencetype="case-citations"&gt;
  &lt;heading&gt;
    &lt;title&gt;C&lt;emph typestyle="smcaps"&gt;ASES&lt;/emph&gt; C&lt;emph typestyle="smcaps"&gt;ITED&lt;/emph&gt;&lt;/title&gt;
  &lt;/heading&gt;
  &lt;bodytext&gt;
    &lt;p&gt;
      &lt;text&gt;The following cases are cited in the judgment:&lt;proc:nl/&gt;
        &lt;lnci:cite type="case"&gt;
          &lt;lnci:content&gt;
            &lt;emph typestyle="it"&gt;Allgood v Blake&lt;/emph&gt; (1873) LR 8 Exch 160
          &lt;/lnci:content&gt;
        &lt;/lnci:cite&gt;&lt;proc:nl/&gt;
        &lt;lnci:cite type="case"&gt;
          &lt;lnci:content&gt;
            &lt;emph typestyle="it"&gt;Amber Holdings (Aust) Pty Ltd v Polona Pty Ltd&lt;/emph&gt; [1982] 2 NSWLR 470
          &lt;/lnci:content&gt;
        &lt;/lnci:cite&gt;&lt;proc:nl/&gt;
      &lt;/text&gt;
    &lt;/p&gt;
  &lt;/bodytext&gt;
&lt;/ref:relatedrefs&gt;
</pre>
        </li>
      </ul>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\HK09_composite_cases\HK09_Rosetta_case.citations-LxAdv_ref.relatedrefs.dita  -->
	
	<xsl:template match="case:citations">

		<!--  Original Target XPath:  compcase:head/ref:relatedrefs   -->
	  <ref:relatedrefs referencetype="case-citations">
	    <xsl:apply-templates select="@*"/>
	    <xsl:apply-templates select="refpt"/>
	    <xsl:apply-templates select="heading"/>
	    <bodytext>
	      <xsl:apply-templates select="node() except (heading, refpt)"/>
	    </bodytext>
			</ref:relatedrefs>
		

	</xsl:template>

	<xsl:template match="case:citetext">

		<!--  Original Target XPath:  ref:relatedrefs/bodytext/p/text   -->
				<p>
					<text>
						<xsl:apply-templates select="@* | node()"/>
					</text>
				</p>		
		

	</xsl:template>

</xsl:stylesheet>