<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="IN03_Rosetta_case.litigants">
    <title>case:litigants <lnpid>id-IN03-39025</lnpid></title>
    <body>
        <p><sourcexml>case:litigants</sourcexml> is a container element that should be omitted, but its content should be retained and converted as follows:</p>
        <p><sourcexml>case:party</sourcexml> becomes
            <targetxml>caseinfo:caseinfo/caseinfo:casename/caseinfo:fullcasename/caseinfo:party</targetxml>
            and create <targetxml>@partyrole="unknown"</targetxml> inside
            <targetxml>caseinfo:party</targetxml>.</p>
        <p><sourcexml>case:procphrase</sourcexml> becomes
            <targetxml>caseinfo:caseinfo/caseinfo:casename/caseinfo:fullcasename/caseinfo:procphrase</targetxml>.</p>
        
                    <pre>

&lt;case:litigants ln.user-displayed="false"&gt;
    &lt;case:party&gt;Rangasawmi Naiken&lt;/case:party&gt;
&lt;/case:litigants&gt;
&lt;case:litigants ln.user-displayed="false"&gt;
    &lt;case:procphrase&gt;v.&lt;/case:procphrase&gt;
&lt;/case:litigants&gt;
&lt;case:litigants ln.user-displayed="false"&gt;
    &lt;case:party&gt;Varadappa Naiken&lt;/case:party&gt;
&lt;/case:litigants&gt;


<b>Becomes</b>


&lt;caseinfo:caseinfo&gt;
    &lt;caseinfo:casename&gt;
        &lt;caseinfo:fullcasename&gt;
            &lt;caseinfo:party partyrole="unknown"&gt;Rangasawmi Naiken&lt;/caseinfo:party&gt;
            &lt;caseinfo:procphrase&gt;v.&lt;/caseinfo:procphrase&gt;
            &lt;caseinfo:party partyrole="unknown"&gt;Varadappa Naiken&lt;/caseinfo:party&gt;
        &lt;/caseinfo:fullcasename&gt;
    &lt;/caseinfo:casename&gt;
&lt;/caseinfo:caseinfo&gt;

</pre>
        <section>
            <title>Changes</title>
            <p>2016-08-17: <ph id="change_20160817_HP">Created</ph>.</p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-IN\IN03_Cases\IN03_Rosetta_case.litigants.dita  -->
	<xsl:message>IN03_Rosetta_case.litigants.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:litigants">

		<!--  Original Target XPath:  caseinfo:caseinfo/caseinfo:casename/caseinfo:fullcasename/caseinfo:party   -->
		<caseinfo:caseinfo>
			<caseinfo:casename>
				<caseinfo:fullcasename>
					<caseinfo:party>
						<xsl:apply-templates select="@* | node()"/>
					</caseinfo:party>
				</caseinfo:fullcasename>
			</caseinfo:casename>
		</caseinfo:caseinfo>

	</xsl:template>

	<xsl:template match="case:party">

		<!--  Original Target XPath:  caseinfo:caseinfo/caseinfo:casename/caseinfo:fullcasename/caseinfo:party   -->
		<caseinfo:caseinfo>
			<caseinfo:casename>
				<caseinfo:fullcasename>
					<caseinfo:party>
						<xsl:apply-templates select="@* | node()"/>
					</caseinfo:party>
				</caseinfo:fullcasename>
			</caseinfo:casename>
		</caseinfo:caseinfo>

	</xsl:template>

	<xsl:template match="case:procphrase">

		<!--  Original Target XPath:  caseinfo:caseinfo/caseinfo:casename/caseinfo:fullcasename/caseinfo:procphrase   -->
		<caseinfo:caseinfo>
			<caseinfo:casename>
				<caseinfo:fullcasename>
					<caseinfo:procphrase>
						<xsl:apply-templates select="@* | node()"/>
					</caseinfo:procphrase>
				</caseinfo:fullcasename>
			</caseinfo:casename>
		</caseinfo:caseinfo>

	</xsl:template>

</xsl:stylesheet>