<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:casesum="http://www.lexisnexis.com/xmlschemas/content/legal/case-summary/1/" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="IN03_Rosetta_case.disposition-LxAdv_casesum.disposition">
  <title>case:disposition <lnpid>id-IN03-39016</lnpid></title>
  <body>
    <section conref="../../common_caselaw/conref_content/Rosetta_case.disposition-LxAdv_casesum.disposition.dita#Rosetta_case.disposition-LxAdv_casesum.disposition/mapping"/>
    <section>
      <note><sourcexml>case:disposition</sourcexml> occurs in two contexts. The full mappings from
        Rosetta to NL are as follows:<ul>
          <li><sourcexml>CASEDOC/case:body/case:headnote/case:disposition</sourcexml> becomes
              <targetxml>courtcase:head/casesum:summaries/casesum:disposition</targetxml>.</li>
          <li><sourcexml>CASEDOC/case:body/case:content/case:judgments/case:disposition</sourcexml>
            becomes <targetxml>courtcase:body/courtcase:opinions/casesum:disposition</targetxml>.
          </li>
        </ul></note>
      <note>Conversion should not create consecutive <targetxml>casesum:summaries</targetxml>
        elements. When 2 or more consecutive sibling source elements map to
          <targetxml>casesum:summaries</targetxml>, target data should be merged to a single
          <targetxml>casesum:summaries</targetxml> element unless this would hamper content
        ordering.</note>
    </section>
    <example>
      <codeblock>
        
		&lt;case:disposition&gt;&amp;#x002D;&amp;#x002D;&amp;#x002D;&amp;#x002D;&amp;#x002D;Appeal dismissed.&lt;/case:disposition&gt;       
	  </codeblock>
      <b>becomes</b>
      <codeblock>&lt;casesum:disposition&gt;
    &lt;p&gt;
        &lt;text&gt;&amp;#x002D;&amp;#x002D;&amp;#x002D;&amp;#x002D;&amp;#x002D;Appeal dismissed.&lt;/text&gt;
    &lt;/p&gt;
&lt;/casesum:disposition&gt;
       </codeblock>
    </example>
    <section>
      <title>Changes</title>
      <p>2016-08-17: <ph id="change_20160817_HP">Created</ph>.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-IN\IN03_Cases\IN03_Rosetta_case.disposition-LxAdv_casesum.disposition.dita  -->
	<xsl:message>IN03_Rosetta_case.disposition-LxAdv_casesum.disposition.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:disposition">

		<!--  Original Target XPath:  courtcase:head/casesum:summaries/casesum:disposition   -->
		<courtcase:head>
			<casesum:summaries>
				<casesum:disposition>
					<xsl:apply-templates select="@* | node()"/>
				</casesum:disposition>
			</casesum:summaries>
		</courtcase:head>

	</xsl:template>

	<xsl:template match="CASEDOC/case:body/case:headnote/case:disposition">

		<!--  Original Target XPath:  courtcase:head/casesum:summaries/casesum:disposition   -->
		<courtcase:head>
			<casesum:summaries>
				<casesum:disposition>
					<xsl:apply-templates select="@* | node()"/>
				</casesum:disposition>
			</casesum:summaries>
		</courtcase:head>

	</xsl:template>

	<xsl:template match="CASEDOC/case:body/case:content/case:judgments/case:disposition">

		<!--  Original Target XPath:  courtcase:body/courtcase:opinions/casesum:disposition   -->
		<courtcase:body>
			<courtcase:opinions>
				<casesum:disposition>
					<xsl:apply-templates select="@* | node()"/>
				</casesum:disposition>
			</courtcase:opinions>
		</courtcase:body>

	</xsl:template>

</xsl:stylesheet>