<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="MY01_Rosetta_case.judgment-LxAdv_courtcase.opinion">
  <title>case:judgment <lnpid>id-IN03-39021</lnpid></title>
  <body>
    <section conref="../../common_caselaw/conref_content/Rosetta_case.judgment-LxAdv_courtcase.opinion.dita#Rosetta_case.judgment-LxAdv_courtcase.opinion/mapping"/>
    <section>
      <p>The optional attributes of <sourcexml>case:judgment</sourcexml> are handled as follows:<ul>
          <li><sourcexml>case:judgment/@subdoc</sourcexml> becomes
              <targetxml>courtcase:opinion/@includeintoc</targetxml>.</li>
          <li><sourcexml>case:judgment/@toc-caption</sourcexml> becomes
              <targetxml>courtcase:opinion/@alternatetoccaption</targetxml>.</li>
        </ul></p>
    </section>
    <example>
      <codeblock>
&lt;case:judgment subdoc="true" toc-caption="judgment"&gt;
    &lt;case:courtinfo&gt;
        &lt;case:judges&gt;Mr. Justice Munro&lt;/case:judges&gt;
    &lt;/case:courtinfo&gt;
    &lt;case:judgmentbody&gt;
        &lt;pgrp&gt;
			&lt;p&gt;&lt;text&gt;The Court delivered the following&lt;/text&gt;&lt;/p&gt;
			&lt;p&gt;&lt;text&gt;JUDGMENT: The requirement of the District Munsif is a reasonable one, and within his discretion. We decline to interfere.&lt;/text&gt;&lt;/p&gt;
		&lt;/pgrp&gt;
    &lt;/case:judgmentbody&gt;
&lt;/case:judgment&gt;</codeblock>
      <b>becomes</b>
      <codeblock>
          &lt;courtcase:opinion includeintoc="true" alternatetoccaption="judgment"&gt;
    &lt;courtcase:opinionby&gt;
        &lt;person:judge&gt;Mr. Justice Munro&lt;/person:judge&gt;
    &lt;/courtcase:opinionby&gt;
    &lt;bodytext&gt;
&lt;pgrp&gt;
			&lt;p&gt;&lt;text&gt;The Court delivered the following&lt;/text&gt;&lt;/p&gt;
			&lt;p&gt;&lt;text&gt;JUDGMENT: The requirement of the District Munsif is a reasonable one, and within his discretion. We decline to interfere.&lt;/text&gt;&lt;/p&gt;
		&lt;/pgrp&gt;
    &lt;/bodytext&gt;
&lt;/courtcase:opinion&gt;</codeblock>
    </example>
      <section>
          <title>Changes</title>
          <p>2016-08-17: <ph id="change_20160817_HP">Created</ph>.</p>
      </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-IN\IN03_Cases\IN03_Rosetta_case.judgment-LxAdv_courtcase.opinion.dita  -->
	<xsl:message>IN03_Rosetta_case.judgment-LxAdv_courtcase.opinion.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:judgment">

		<!--  Original Target XPath:  courtcase:opinion/@includeintoc   -->
		<courtcase:opinion>
			<xsl:attribute name="includeintoc">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</courtcase:opinion>

	</xsl:template>

	<xsl:template match="case:judgment/@subdoc">

		<!--  Original Target XPath:  courtcase:opinion/@includeintoc   -->
		<courtcase:opinion>
			<xsl:attribute name="includeintoc">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</courtcase:opinion>

	</xsl:template>

	<xsl:template match="case:judgment/@toc-caption">

		<!--  Original Target XPath:  courtcase:opinion/@alternatetoccaption   -->
		<courtcase:opinion>
			<xsl:attribute name="alternatetoccaption">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</courtcase:opinion>

	</xsl:template>

</xsl:stylesheet>