<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:casedigest="http://www.lexisnexis.com/xmlschemas/content/legal/case-digest/1/" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Linxplus-CaseDigest_case.constituents">
    <title>case:constituents <lnpid>id-NZ07DC-23609</lnpid></title>
    <body>
        <section>
            <p><sourcexml>case:constituents</sourcexml> becomes
                    <targetxml>casedigest:head/casedigest:caseinfo/casedigest:appearances/courtcase:representation</targetxml>.</p>
            <p>Create <targetxml>bodytext</targetxml> as a required child of <targetxml>courtcase:representation</targetxml>.</p>
            <p>Suppressed <sourcexml>@searchtype</sourcexml> attribute from target.</p>

<pre>
&lt;case:info&gt;
    &lt;case:constituents searchtype="REPRESENTATION"&gt;
        &lt;p&gt;
            &lt;text&gt;&lt;process-ignore process="kwd"&gt;&lt;emph typestyle="bf"&gt;Representation:
                    &lt;/emph&gt;&lt;/process-ignore&gt;AL Geraghty (in person), C Matsis&lt;/text&gt;
        &lt;/p&gt;
    &lt;/case:constituents&gt;
&lt;/case:info&gt;

<b>Becomes</b>

&lt;casedigest:head&gt;
    &lt;casedigest:caseinfo&gt;
        &lt;casedigest:appearances&gt;
            &lt;courtcase:representation&gt;
                &lt;bodytext&gt;
                    &lt;p&gt;
                        &lt;text&gt;&lt;emph typestyle="bf"&gt;Representation: &lt;/emph&gt;AL Geraghty (in person), C
                            Matsis&lt;/text&gt;
                    &lt;/p&gt;
                &lt;/bodytext&gt;
            &lt;/courtcase:representation&gt;
        &lt;/casedigest:appearances&gt;
    &lt;/casedigest:caseinfo&gt;
&lt;/casedigest:head&gt;
</pre>
        </section>
        <section>
            <title>Changes</title>
            <p>2013-12-09: <ph id="change_20131209">Created new DITA, Webteam #: 247347, this change directly affects NZ07-Casedigest.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ07_Linxplus\NZ07DC_Linxplus-CaseDigest\Linxplus-CaseDigest_case.constituents.dita  -->
	<!--<xsl:message>Linxplus-CaseDigest_case.constituents.xsl requires manual development!</xsl:message>--> 

    <xsl:template match="case:constituents[child::p | child::pgrp]">
        <!-- <courtcase:opinions>-->
        <casedigest:appearances>
            <courtcase:representation>
                <bodytext>
                    <xsl:apply-templates select="@* | node()"/>
                </bodytext>
            </courtcase:representation>
        </casedigest:appearances>
        <!--</courtcase:opinions>-->
    </xsl:template>

    <xsl:template match="case:constituents/@searchtype"/>

</xsl:stylesheet>