<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:casedigest="http://www.lexisnexis.com/xmlschemas/content/legal/case-digest/1/" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Linxplus-CaseDigest_case.courtcode">
    <title>case:courtcode <lnpid>id-NZ07DC-23611</lnpid></title>
    <body>
        <section>
            <p>
                <sourcexml>case:courtcode</sourcexml> becomes
                    <targetxml>casedigest:caseinfo/jurisinfo:courtinfo/jurisinfo:alternatecourtcode/@alternatecourtcode</targetxml>
                and create <targetxml>doc:legacy-metadata/meta/metaitem</targetxml> and attributes
                will be populated as <targetxml>@name="case:courtcode"</targetxml> and
                    <targetxml>@value</targetxml> will be value of
                    <sourcexml>case:courtcode</sourcexml>.</p>
            <pre xml:space="preserve">
    
        &lt;case:info&gt;
            &lt;case:courtinfo&gt;
                &lt;case:courtcode ln.user-displayed="false"&gt;NZHC&lt;/case:courtcode&gt;
            &lt;/case:courtinfo&gt;
        &lt;/case:info&gt;
   

<b>Becomes</b>

    &lt;casedigest:head&gt;
        &lt;casedigest:caseinfo&gt;
            &lt;jurisinfo:courtinfo&gt;
                &lt;jurisinfo:alternatecourtcode alternatecourtcode="NZHC"/&gt;
            &lt;/jurisinfo:courtinfo&gt;
        &lt;/casedigest:caseinfo&gt;
    &lt;/casedigest:head&gt;
    
    
    &lt;doc:legacy-metadata metadatasource="lbu-meta"&gt;
        &lt;meta&gt;
            &lt;metaitem name="case:courtcode" value="NZHC"/&gt;
        &lt;/meta&gt;
    &lt;/doc:legacy-metadata&gt;

</pre>
            <note>The ordering of the <targetxml>jurisinfo:alternatecourtcode</targetxml> and
                    <targetxml>jurisinfo:jurisdiction\jurisinfo:system</targetxml> is not
                significant in terms of display.</note>
            <note>For handling @ln.user-displayed attribute, please refer to general markup
                ln.user_displayed="false" section in the CI.</note>
            <note>Conversion should not create consecutive
                    <targetxml>casedigest:caseinfo</targetxml> elements. When 2 or more consecutive
                sibling source elements map to <targetxml>casedigest:caseinfo</targetxml>, data
                should be merged to a single <targetxml>casedigest:caseinfo</targetxml> element
                unless this would hamper content ordering.</note>
        </section>

        <section>
            <title>Changes</title>
            <p>2013-09-24 <ph id="change_20130924_WL_3">Sample updated to reflect the movement of
                    element <targetxml>casedigest:caseinfo</targetxml> along with all its children
                    to <targetxml>casedigest:caseinfo</targetxml> .
                        <targetxml>casedigest:caseinfo</targetxml> and its children will be placed
                    within <targetxml>casedigest:head</targetxml> and no longer within
                        <targetxml>casedigest:body</targetxml>. <b>WebTeam # 235783</b></ph></p>
        </section>

    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ07_Linxplus\NZ07DC_Linxplus-CaseDigest\Linxplus-CaseDigest_case.courtcode.dita  -->
	<!--<xsl:message>Linxplus-CaseDigest_case.courtcode.xsl requires manual development!</xsl:message> -->

    <xsl:template match="case:courtcode[not(@ln.user-displayed)]">
	<!--  Original Target XPath:  casedigest:caseinfo/jurisinfo:courtinfo/jurisinfo:alternatecourtcode/@alternatecourtcode   -->
			<jurisinfo:courtinfo>
				<jurisinfo:alternatecourtcode>
					<xsl:attribute name="alternatecourtcode">
						<xsl:apply-templates select="node()"/>
					</xsl:attribute>
				</jurisinfo:alternatecourtcode>
			</jurisinfo:courtinfo>
	</xsl:template>
</xsl:stylesheet>