<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:casedigest="http://www.lexisnexis.com/xmlschemas/content/legal/case-digest/1/" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Linxplus-CaseDigest_case.judges">
    <title>case:judges <lnpid>id-NZ07DC-23618</lnpid></title>
    <body>
        <section>
            <p><sourcexml>case:judges</sourcexml> becomes
                    <targetxml>casedigest:head/casedigest:caseinfo/casedigest:appearances/courtcase:panel/courtcase:judges</targetxml>.</p>
            <p><sourcexml>case:judge</sourcexml> becomes
                    <targetxml>person:judge</targetxml></p>
            <pre>
                
            &lt;case:courtinfo&gt;
                &lt;case:judges&gt;
                    &lt;case:judge&gt;Keith &amp;amp; Blanchard&lt;/case:judge&gt; JJ&lt;/case:judges&gt;
            &lt;/case:courtinfo&gt;

       <b>Becomes</b>
                
        &lt;casedigest:head&gt;
            &lt;casedigest:caseinfo&gt;
                &lt;casedigest:appearances&gt;
                    &lt;courtcase:panel&gt;
                        &lt;courtcase:judges&gt;
                            &lt;person:judge&gt;Keith &amp;#x0026; Blanchard&lt;/person:judge&gt; JJ &lt;/courtcase:judges&gt;
                    &lt;/courtcase:panel&gt;
                &lt;/casedigest:appearances&gt;
            &lt;/casedigest:caseinfo&gt;
        &lt;/casedigest:head&gt;

</pre>
        </section>
        <section>
            <title>Changes</title>
            <p>2013-09-24 <ph id="change_20130924_WL_7">Sample and XPath updated to reflect the movement of element <targetxml>casedigest:caseinfo</targetxml> along with all its children to <targetxml>casedigest:caseinfo</targetxml> . <targetxml>casedigest:caseinfo</targetxml> and its children
                will be placed within <targetxml>casedigest:head</targetxml> and no longer within  <targetxml>casedigest:body</targetxml>. <b>WebTeam # 235783</b></ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ07_Linxplus\NZ07DC_Linxplus-CaseDigest\Linxplus-CaseDigest_case.judges.dita  -->
	<!--<xsl:message>Linxplus-CaseDigest_case.judges.xsl requires manual development!</xsl:message>--> 

    <xsl:template match="case:judges[parent::case:courtinfo]">
        <xsl:choose>
            <xsl:when test="not(child::case:judge)">
                <casedigest:appearances>
                    <courtcase:panel>
                        <courtcase:judges>
                            <person:judge>
                                <xsl:apply-templates select="@* | node()"/>
                            </person:judge>
                        </courtcase:judges>
                    </courtcase:panel>
                </casedigest:appearances>
            </xsl:when>
            <xsl:otherwise>
                <casedigest:appearances>
                    <courtcase:panel>
                        <courtcase:judges>
                            <xsl:apply-templates select="@* | node()"/>
                        </courtcase:judges>
                    </courtcase:panel>
                </casedigest:appearances>
            </xsl:otherwise>
        </xsl:choose> 
    </xsl:template>

    <xsl:template match="nl[parent::case:judges]"/>
    
    <xsl:template match="case:judge">
        <person:judge>
            <xsl:apply-templates select="@* | node()"/>
        </person:judge>
    </xsl:template>
    
    <xsl:template match="case:judge/emph[@typestyle='smcaps'][parent::case:judges]">
        <xsl:apply-templates/>
    </xsl:template>
</xsl:stylesheet>