<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:casedigest="http://www.lexisnexis.com/xmlschemas/content/legal/case-digest/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Linxplus-CaseDigest_case.courtcite">
    <title>case:courtcite <lnpid>id-NZ07DC-23610</lnpid></title>
    <body>
        <p><sourcexml>case:courtcite</sourcexml> becomes
                <targetxml>casedigest:head/casedigest:caseinfo/ref:citations/ref:parallelcite/@citetype="court"</targetxml>.</p>
        <p>Drop <sourcexml>@searchtype</sourcexml> attribute.</p>
        
        <pre>
&lt;case:courtcite searchtype="ALT-CASE-NAME"&gt;
    &lt;ci:cite&gt;
        &lt;ci:content&gt;[2009] NZCA 451&lt;/ci:content&gt;
    &lt;/ci:cite&gt;
&lt;/case:courtcite&gt;

<b>becomes</b>

&lt;casedigest:head&gt;
    &lt;casedigest:caseinfo&gt;
        &lt;ref:citations&gt;
            &lt;ref:parallelcite citetype="court"&gt;
                &lt;lnci:cite&gt;
                    &lt;lnci:content&gt;[2009] NZCA 451&lt;/lnci:content&gt;
                &lt;/lnci:cite&gt;
            &lt;/ref:parallelcite&gt;
        &lt;/ref:citations&gt;
    &lt;/casedigest:caseinfo&gt;
&lt;/casedigest:head&gt;
        </pre>
        
        <section>
            <title>Changes</title>
            <p>2014-06-18: <ph id="change_20140618_PS">Updated target mapping and snippet, Webteam #: 236888.</ph></p>
            <p>2014-04-17: <ph id="change_20140417_PS">Created and WebTeam # 254568.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ07_Linxplus\NZ07DC_Linxplus-CaseDigest\Linxplus-CaseDigest_case.courtcite.dita  -->
	<!--<xsl:message>Linxplus-CaseDigest_case.courtcite.xsl requires manual development!</xsl:message>--> 
    <xsl:template match="case:courtcite">
            <ref:parallelcite citetype="court">
                <xsl:apply-templates select="node() | @*"/>
            </ref:parallelcite>
    </xsl:template>
    
    <xsl:template match="case:courtcite/@searchtype"/>

</xsl:stylesheet>