<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet  xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:casedigest="http://www.lexisnexis.com/xmlschemas/content/legal/case-digest/1/" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" version="2.0" exclude-result-prefixes="dita case casedigest caseinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Linxplus-CaseDigest_case.casename">
   <title>case:casename <lnpid>id-NZ07DC-23608</lnpid></title>
   <body>
      <section>
          <p><sourcexml>case:casename</sourcexml> becomes <targetxml>caseinfo:casename/caseinfo:fullcasename</targetxml> and populate the child as below:</p>
          <p>Create <targetxml>caseinfo:fullcasename</targetxml> as a child of <targetxml>caseinfo:casename</targetxml></p>
 
<pre xml:space="preserve">


    &lt;case:info&gt;
         &lt;case:casename&gt;Payne v Payne&lt;/case:casename&gt;
        ...
     &lt;/case:info&gt;


    <b>Becomes</b>


    &lt;casedigest:head&gt;
         &lt;casedigest:caseinfo&gt;
             &lt;caseinfo:casename&gt;
                 &lt;caseinfo:fullcasename&gt;Payne v Payne&lt;/caseinfo:fullcasename&gt;
             &lt;/caseinfo:casename&gt;
             ...
         &lt;/casedigest:caseinfo&gt;
    &lt;/casedigest:head&gt;
    
</pre>
      </section>
       <section>
           <title>Changes</title>
           <p>2013-09-24 <ph id="change_20130924_WL_1">Sample updated to reflect the movement of element <targetxml>casedigest:caseinfo</targetxml> along with all its children to <targetxml>casedigest:caseinfo</targetxml> . <targetxml>casedigest:caseinfo</targetxml> and its children
               will be placed within <targetxml>casedigest:head</targetxml> and no longer within  <targetxml>casedigest:body</targetxml>. <b>WebTeam # 235783</b></ph></p>
       </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ07_Linxplus\NZ07DC_Linxplus-CaseDigest\Linxplus-CaseDigest_case.casename.dita  -->
	<!--<xsl:message>Linxplus-CaseDigest_case.casename.xsl requires manual development!</xsl:message>--> 

	<xsl:template match="case:casename">

		<!--  Original Target XPath:  caseinfo:casename/caseinfo:fullcasename   -->
	    <caseinfo:casename>
			<caseinfo:fullcasename>
				<xsl:apply-templates select="@* | node()"/>
			</caseinfo:fullcasename>
		</caseinfo:casename>

	</xsl:template>

</xsl:stylesheet>