<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="MY01_Rosetta_case.litigants">
    <title>case:litigants <lnpid>id-MY01-16028</lnpid></title>
    <body>
        <p><sourcexml>case:litigants</sourcexml> is a container element that should be omitted, but its content should be retained and converted as follows:</p>
        <p><sourcexml>case:party</sourcexml> becomes
            <targetxml>caseinfo:caseinfo/caseinfo:casename/caseinfo:fullcasename/caseinfo:party</targetxml>
            and create <targetxml>@partyrole="unknown"</targetxml> inside
            <targetxml>caseinfo:party</targetxml>.</p>
        <p><sourcexml>case:procphrase</sourcexml> becomes
            <targetxml>caseinfo:caseinfo/caseinfo:casename/caseinfo:fullcasename/caseinfo:procphrase</targetxml>.</p>
        
        <pre>&lt;case:litigants ln.user-displayed="false"&gt;
    &lt;case:party&gt;Public Prosecutor&lt;/case:party&gt;
&lt;/case:litigants&gt;
&lt;case:litigants ln.user-displayed="false"&gt;
    &lt;case:procphrase&gt;v&lt;/case:procphrase&gt;
&lt;/case:litigants&gt;
&lt;case:litigants ln.user-displayed="false"&gt;
    &lt;case:party&gt;William Ho&lt;/case:party&gt;
&lt;/case:litigants&gt;

<b>becomes</b>

&lt;caseinfo:caseinfo&gt;
    &lt;caseinfo:casename&gt;
        &lt;caseinfo:fullcasename&gt;
            &lt;caseinfo:party partyrole="unknown"&gt;Public Prosecutor &lt;/caseinfo:party&gt;
            &lt;caseinfo:procphrase&gt;v&lt;/caseinfo:procphrase&gt;
            &lt;caseinfo:party partyrole="unknown"&gt;William Ho&lt;/caseinfo:party&gt;
        &lt;/caseinfo:fullcasename&gt;
    &lt;/caseinfo:casename&gt;
&lt;/caseinfo:caseinfo&gt;
        </pre>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY01_Cases\MY01_Rosetta_case.litigants.dita  -->
<!--	<xsl:message>MY01_Rosetta_case.litigants.xsl requires manual development!</xsl:message> -->

	<xsl:template match="case:litigants">
		<!--  Original Target XPath:  caseinfo:casename/caseinfo:fullcasename   -->
		<xsl:apply-templates/>
	</xsl:template>
	
	<xsl:template match="case:litigants/case:party">
		<caseinfo:party>
			<xsl:attribute name="partyrole">
				<xsl:text>unknown</xsl:text>
			</xsl:attribute>
			<xsl:apply-templates/>
		</caseinfo:party>
	</xsl:template>
	
	<xsl:template match="case:litigants/case:procphrase">
		<caseinfo:procphrase>
			<xsl:apply-templates/>
		</caseinfo:procphrase>
	</xsl:template>

</xsl:stylesheet>