<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_case.casename-LxAdv_caseinfo.casename_caseinfo.fullcasename">
    <title>case:casename <lnpid>id-MY01-16033</lnpid></title>
    <body>
        <section>
            <p><sourcexml>case:casename</sourcexml> becomes
                <targetxml>caseinfo:casename/caseinfo:fullcasename</targetxml>.</p>
            <p>Any <sourcexml>nl</sourcexml> elements that occur inside
                <sourcexml>case:casename</sourcexml> should be suppressed if they are preceded or followed
                by a space. Any <sourcexml>nl</sourcexml> elements that are not preceded or followed by a
                space should be converted into a single space character.</p>
            <p>Any occurrences of the attribute <sourcexml>@ln.user-displayed</sourcexml> in
                <sourcexml>case:casename</sourcexml> should be suppressed.</p>
        </section>
        
        <example>
            <title>Example: MY content</title>
            <codeblock>
&lt;case:casename&gt;PUBLIC PROSECUTOR v ANG BENG HOCK&lt;/case:casename&gt;
           </codeblock>
            <b>becomes</b>
            <codeblock>
&lt;caseinfo:casename&gt;
    &lt;caseinfo:fullcasename&gt;PUBLIC PROSECUTOR v ANG BENG HOCK&lt;/caseinfo:fullcasename&gt;
&lt;/caseinfo:casename&gt;
           </codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>2015-12-10: <ph id="change_20151210_PS">Created.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY01_Cases\MY01_Rosetta_case.casename.dita  -->
<!--	<xsl:message>MY01_Rosetta_case.casename.xsl requires manual development!</xsl:message> -->

    <xsl:template match="case:casename">
        <!--  Original Target XPath:  caseinfo:casename/caseinfo:fullcasename   -->
        <caseinfo:casename>
            <caseinfo:fullcasename>
                <xsl:choose>
                    <xsl:when test="not(@ln.user-displayed)">
                        <xsl:apply-templates select="@* | node()"/>
                    </xsl:when>
                </xsl:choose>            
            </caseinfo:fullcasename>
        </caseinfo:casename>
    </xsl:template>
    
    <xsl:template match="case:casename/nl">
        <xsl:text/>
    </xsl:template>
	
</xsl:stylesheet>