<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:ci="http://www.lexis-nexis.com/ci" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita case ci">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.reportercite">
  <title>case:reportercite <lnpid>id-MY01-16010</lnpid></title>
  <body>
    <section>
      <ul>
        <li>
          <sourcexml>case:reportercite</sourcexml> becomes <targetxml>ref:citations</targetxml> with
          child elements as described below: <ul>
            <li> Create <targetxml>caseinfo:caseinfo/ref:citations/ref:cite4thisresource</targetxml>
              with attribute <targetxml>@citetype</targetxml> defines the type of citation
              "reporter". </li>
            <li>
              <note class="- topic/note ">For handling of citation markup; kindly refer to the
                instructions for <sourcexml>ci:cite</sourcexml> in the General Markup section. </note>
              <note>Conversion should not create consecutive
                  <targetxml>caseinfo:caseinfo</targetxml> elements. When 2 or more consecutive
                sibling source elements map to <targetxml>caseinfo:caseinfo</targetxml>, data should
                be merged to a single <targetxml>caseinfo:caseinfo</targetxml> element unless this
                would hamper content ordering. </note>
            </li>
          </ul><pre xml:space="preserve" class="- topic/pre ">
&lt;case:reportercite&gt;
    &lt;ci:cite type="cite4thisdoc"&gt;
        &lt;ci:case&gt;
            &lt;ci:caseinfo&gt;
                &lt;ci:decisiondate year="1965"/&gt;
            &lt;/ci:caseinfo&gt;
            &lt;ci:caseref&gt;
                &lt;ci:reporter value="BLR"/&gt;
                &lt;ci:volume num="2"/&gt;
                &lt;ci:edition&gt;
                    &lt;ci:date year="1965"/&gt;
                &lt;/ci:edition&gt;
                &lt;ci:page num="152"/&gt;
            &lt;/ci:caseref&gt;
        &lt;/ci:case&gt;
        &lt;ci:content&gt;
            &lt;citefragment searchtype="CASE-CITE-REF"&gt; [1965-1986] 2 BLR 152&lt;/citefragment&gt;
        &lt;/ci:content&gt;
    &lt;/ci:cite&gt;
&lt;/case:reportercite&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;ref:citations&gt;
    &lt;ref:cite4thisresource citetype="reporter"&gt;
        &lt;lnci:cite&gt;
            &lt;lnci:case&gt;
                &lt;lnci:caseinfo&gt;
                    &lt;lnci:decisiondate year="1965"/&gt;
                &lt;/lnci:caseinfo&gt;
                &lt;lnci:caseref&gt;
                    &lt;lnci:reporter value="BLR"/&gt;
                    &lt;lnci:volume num="2"/&gt;
                    &lt;lnci:page num="152"/&gt;
                &lt;/lnci:caseref&gt;
            &lt;/lnci:case&gt;
            &lt;lnci:content&gt; [1965-1986&amp;] 2 BLR 152&lt;/lnci:content&gt;
        &lt;/lnci:cite&gt;
    &lt;/ref:cite4thisresource&gt;
&lt;/ref:citations&gt;
</pre>
        </li>
      </ul>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY01_Cases\case.reportercite.dita  -->
<!--	<xsl:message>MY01_Cases_case.reportercite.xsl requires manual development!</xsl:message> -->

    <xsl:template match="case:reportercite">
        <!--  Original Target XPath:  ref:citations   -->
        <ref:citations>
            <ref:cite4thisresource>
                <xsl:attribute name="citetype">
                    <xsl:text>reporter</xsl:text>
                </xsl:attribute>
                <xsl:apply-templates select="@* | node()"/>
            </ref:cite4thisresource>
        </ref:citations>
    </xsl:template>
    
    <xsl:template match="case:reportercite[@searchtype = 'BCNUM']">
        <courtcase:statusnotice>
            <courtcase:pubstatus>
                <xsl:attribute name="status">
                    <xsl:text>none</xsl:text>
                </xsl:attribute>
                <p>
                    <text>unreported case</text>
                </p>
            </courtcase:pubstatus>
        </courtcase:statusnotice>
    </xsl:template>

</xsl:stylesheet>