<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.constituents">
    <title>case:constituents <lnpid>id-AU09-19609</lnpid></title>
    <body>
        <section id="mapping">
            <p><sourcexml>case:constituents</sourcexml> becomes
                    <targetxml>courtcase:representation</targetxml> with child
                elements handled as described below.</p>
            <note>There can be multiple <sourcexml>case:constituents</sourcexml> elements at
                different locations in a file (generally before and after the
                    <sourcexml>case:judgment</sourcexml>). These elements need to be maintained in
                the same locations. The general rule remains that the content order should be
                maintained from input to output.</note>
            <p><sourcexml>case:constituent</sourcexml> becomes
                    <targetxml>courtcase:opinions/courtcase:representation/courtcase:counsel</targetxml>.</p>
            <note>If <sourcexml>person</sourcexml> occurs inside
                    <sourcexml>case:constituent</sourcexml>, kindly refer to the instructions for
                    <sourcexml>person</sourcexml> in the General Markup section for guidance on
                handling of this scenario.</note>
        </section>
        <example>
            <title>Example</title>
            <codeblock>

&lt;case:judgments&gt;
    ..........
    ..........
&lt;case:constituents&gt;
    &lt;case:constituent&gt;
        &lt;emph typestyle="it"&gt;M Todd,&lt;/emph&gt; departmental advocate, for the applicant. &lt;/case:constituent&gt;
    &lt;case:constituent&gt;The respondent appeared in person. &lt;/case:constituent&gt;
&lt;/case:constituents&gt;
&lt;/case:judgments&gt;

           </codeblock>
            <b>becomes</b>
            <codeblock>

&lt;courtcase:opinions&gt;
    ...............
    ...............
    &lt;courtcase:representation&gt;
        &lt;courtcase:counsel&gt;&lt;emph typestyle="it"&gt;M Todd,&lt;/emph&gt; departmental advocate, for the applicant.&lt;/courtcase:counsel&gt; 
        &lt;courtcase:counsel&gt;The respondent appeared in person.&lt;/courtcase:counsel&gt;
    &lt;/courtcase:representation&gt;
&lt;/courtcase:opinions&gt;

           </codeblock>
        </example>
        <section><p>Any other elements under <sourcexml>case:constituents</sourcexml> should be
                placed under
                    <targetxml>courtcase:opinions/courtcase:representation/courtcase:arguments/bodytext</targetxml>.
                For example,<ul>
                    <li><sourcexml>case:constituents/p</sourcexml> becomes
                            <targetxml>courtcase:representation/courtcase:arguments/bodytext/p</targetxml>.</li>
                    <li><sourcexml>case:constituents/pgrp</sourcexml> becomes <targetxml>
                            courtcase:opinions/courtcase:representation/courtcase:arguments/bodytext/pgrp</targetxml>.</li>
                </ul>
        </p>
        </section>
        <example>
            <title>Example</title>
            <codeblock>

&lt;case:constituents&gt;
    &lt;p&gt;
        &lt;text&gt;Solicitors: Anderssen Lawyers for the Appellants; McInnes Wilson Lawyers for the Respondent; King &amp;amp; Co Solicitors for the Second to Twelfth Respondents.  MGMW&lt;/text&gt;
    &lt;/p&gt;
&lt;/case:constituents&gt;

           </codeblock>
            <b>becomes</b>
            <codeblock>

&lt;courtcase:representation&gt;
    &lt;courtcase:arguments&gt;
        &lt;bodytext&gt;
            &lt;p&gt;
                &lt;text&gt;Solicitors: Anderssen Lawyers for the Appellants; McInnes Wilson Lawyers for the Respondent; King &amp;amp; Co Solicitors for the Second to Twelfth Respondents.  MGMW&lt;/text&gt;
            &lt;/p&gt;
        &lt;/bodytext&gt;
    &lt;/courtcase:arguments&gt;
&lt;/courtcase:representation&gt;

           </codeblock>
        </example>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU09_case_digest\case.constituents.dita  -->
	<!--<xsl:message>AU09_case_digest_case.constituents.xsl requires manual development!</xsl:message>--> 

	<xsl:template match="case:constituents">
		<courtcase:representation>
			<xsl:for-each select="child::*">
				<xsl:choose>
					<xsl:when test="self::case:constituent">
						<xsl:apply-templates select="."/>
					</xsl:when>
					<xsl:otherwise>
						<courtcase:arguments>
							<bodytext>
								<xsl:apply-templates select="." />		
							</bodytext>
						</courtcase:arguments>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:for-each>
		</courtcase:representation>
	</xsl:template>
	
	<xsl:template match="heading[parent::case:constituents]">
		<h>
			<xsl:apply-templates select="@* | node()"/>
		</h>
	</xsl:template>

	<xsl:template match="title[not( normalize-space( . ) = '' ) and parent::heading/parent::case:constituents]" priority="1">
		<xsl:apply-templates/>
	</xsl:template>
	<xsl:template match="case:constituent">
		
		<courtcase:counsel>
			<xsl:apply-templates select="@* except @constituenttype | node()"/>
		</courtcase:counsel>
	</xsl:template>
	
	
	<xsl:template match="person[parent::case:constituent]">

		<!--  Original Target XPath:  courtcase:opinions/courtcase:representation/courtcase:arguments/bodytext   -->
		<person:counselor>
						<xsl:apply-templates select="person"/>
		</person:counselor>
	</xsl:template>

</xsl:stylesheet>