<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.courtinfo_case.courtcode">
   <title>case:courtcode <lnpid>id-AU07-19217</lnpid></title>
   <body>
      <section>
         <ul><li class="- topic/li ">
             <sourcexml class="+ topic/keyword xml-d/sourcexml ">case:courtinfo/case:courtcode</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">jurisinfo:courtinfo/jurisinfo:alternatecourtcode/@alternatecourtcode</targetxml> and 
             create <targetxml class="+ topic/keyword xml-d/targetxml ">doc:legacy-metadata/meta/metaitem</targetxml> and the attributes will be populated as <targetxml>@name="case:courtcode"</targetxml> and <targetxml>@value</targetxml> will be the value of <sourcexml>case:courtcode</sourcexml>.                          
                        <pre xml:space="preserve" class="- topic/pre ">
&lt;case:headnote&gt;
    &lt;case:info&gt;
        &lt;case:courtinfo&gt;...
            &lt;case:courtcode&gt;ACTSC&lt;/case:courtcode&gt;
        &lt;/case:courtinfo&gt;
    &lt;/case:info&gt;
&lt;/case:headnote&gt;
<b class="+ topic/ph hi-d/b ">Becomes</b>
&lt;jurisinfo:courtinfo&gt;
   &lt;jurisinfo:alternatecourtcode alternatecourtcode="ACTSC"/&gt;
&lt;/jurisinfo:courtinfo&gt;

&lt;doc:legacy-metadata metadatasource="lbu-meta"/&gt;...               
    &lt;meta&gt;
        &lt;metaitem name="case:courtcode" value="ACTSC"/&gt;
    &lt;/meta&gt;
&lt;/doc:legacy-metadata&gt;                               
</pre>
                            <p class="- topic/p "/>
         </li></ul>
          <note>The ordering of the <targetxml>jurisinfo:alternatecourtcode</targetxml> and <targetxml>jurisinfo:jurisdiction\jurisinfo:system</targetxml> is not significant in terms of display.</note>
      </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU07_courtorder\case.courtcode.dita  -->

	<xsl:template match="case:courtinfo/case:courtcode">		
		<jurisinfo:alternatecourtcode>
			<xsl:attribute name="alternatecourtcode">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</jurisinfo:alternatecourtcode>
	</xsl:template>

	<!-- metaitem mapping in docinfo module -->
	
</xsl:stylesheet>