<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
  xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/"
  xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:casedigest="http://www.lexisnexis.com/xmlschemas/content/legal/case-digest/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.judges">
  <title>case:judges <lnpid>id-NZ17CC-25817</lnpid></title>
  <body>
    <section>
      <ul>
        <li class="- topic/li ">
          <sourcexml class="+ topic/keyword xml-d/sourcexml ">case:courtinfo/case:judges</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">casedigest:appearances/courtcase:panel/courtcase:judges</targetxml>
          
<pre xml:space="preserve" class="- topic/pre ">

&lt;case:courtinfo&gt;
  &lt;case:judges&gt;Oral judgment of Fisher J&lt;/case:judges&gt;
  &lt;!--...--&gt;
&lt;/case:courtinfo&gt;


<b class="+ topic/ph hi-d/b ">Becomes</b>
  

&lt;casedigest:appearances&gt;
   &lt;courtcase:panel&gt;
       &lt;courtcase:judges&gt;Oral judgment of Fisher J&lt;/courtcase:judges&gt;
  &lt;/courtcase:panel&gt;
&lt;/casedigest:appearances&gt;
            

           </pre> 
        </li>
      </ul>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ17_Case_Summaries\NZ17CC_Citatordoc_To_CaseDigest\case.judges.dita  -->

  <xsl:template match="case:judges">
    <casedigest:appearances>
      <courtcase:panel>
        <courtcase:judges>
          <xsl:apply-templates select="@* | node()"/>
        </courtcase:judges>
      </courtcase:panel>
    </casedigest:appearances>
  </xsl:template>

</xsl:stylesheet>