<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case"
	xmlns:casehist="http://www.lexisnexis.com/xmlschemas/content/legal/case-history/1/"
	xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0"
	exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_case.subhist-LxAdv_casehist.subhist">
		<title>case:subhist <lnpid>id-CCCC-12020</lnpid></title>
		<body>
			<section>
				<p><sourcexml>case:subhist</sourcexml> becomes
						<targetxml>courtcase:courtcase/courtcase:head/casehist:casehist/casehist:subhist</targetxml>.</p>
				<p>The children of <sourcexml>case:subhist</sourcexml> should be mapped to children of
						<targetxml>casehist:subhist/casehist:summary</targetxml>.</p>
			</section>
			<example>
				<title>Example: UK content</title>
				<codeblock> &lt;case:subhist&gt; &lt;pgrp&gt; &lt;p&gt; &lt;text&gt;APPEAL relating to Opposition Proceedings No
					B 247652 (Community trade mark application No 1233923)&lt;/text&gt; &lt;/p&gt; &lt;/pgrp&gt;
					&lt;/case:subhist&gt; </codeblock>
				<b>becomes</b>
				<codeblock> &lt;casehist:casehist&gt; &lt;casehist:subhist&gt; &lt;casehist:summary&gt; &lt;pgrp&gt; &lt;p&gt;
					&lt;text&gt;APPEAL relating to Opposition Proceedings No B 247652 (Community trade mark application No
					1233923)&lt;/text&gt; &lt;/p&gt; &lt;/pgrp&gt; &lt;/casehist:summary&gt; &lt;/casehist:subhist&gt;
					&lt;/casehist:casehist&gt; </codeblock>
			</example>
		</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_caselaw\Rosetta_case.subhist-LxAdv_casehist.subhist.dita  -->


	<!--Vikas Rohilla Updated the template Initilal   -->
	<xsl:template match="case:subhist">
		<casehist:casehist>
			<casehist:subhist>
				<casehist:summary>
					<xsl:apply-templates select="@* | node()"/>
				</casehist:summary>
			</casehist:subhist>
		</casehist:casehist>
	</xsl:template>

</xsl:stylesheet>
