<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_case.casename-LxAdv_caseinfo.casename_caseinfo.fullcasename">
  <title>case:casename <lnpid>id-CCCC-12009</lnpid></title>
  <body>
    <section>
      <p><sourcexml>case:casename</sourcexml> becomes
          <targetxml>caseinfo:casename/caseinfo:fullcasename</targetxml>.</p>
      <p>Any <sourcexml>nl</sourcexml> elements that occur inside
          <sourcexml>case:casename</sourcexml> should be suppressed if they are preceded or followed
        by a space. Any <sourcexml>nl</sourcexml> elements that are not preceded or followed by a
        space should be converted into a single space character.</p>
      <p>Any occurrences of the attribute <sourcexml>@ln.user-displayed</sourcexml> in
        <sourcexml>case:casename</sourcexml> should be suppressed.</p>
      
      <note>Special note for UK01-UK04, please see <xref href="../common_newest/Rosetta_UK_case.casename-Plus-case.reportercite-LxAdv-dc.title.dita"/> for an additional conversion that uses
        <sourcexml>case:info/case:casename</sourcexml>.</note>
    </section>
    <example>
      <title>Example: CA content</title>
      <codeblock>
&lt;case:casename&gt;Entre&lt;nl/&gt; Irving Oil Limited, Demanderesse, et&lt;nl/&gt; Sa Majesté la Reine, Défenderesse&lt;/case:casename&gt;
           </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;caseinfo:casename&gt;
  &lt;caseinfo:fullcasename&gt;Entre Irving Oil Limited, Demanderesse, et Sa Majesté la Reine, Défenderesse&lt;/caseinfo:fullcasename&gt;
&lt;/caseinfo:casename&gt;
           </codeblock>
    </example>
    <example>
      <title>Example: AU content</title>
      <codeblock>
&lt;case:casename&gt;Re: GOLDEN BREAD PTY. LTD.; THE QUEENSLAND &lt;nl/&gt;CO-OPERATIVE MILLING ASSOCIATION v HUTCHISON&lt;/case:casename&gt;
           </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;caseinfo:casename&gt;
  &lt;caseinfo:fullcasename&gt;Re: GOLDEN BREAD PTY. LTD.; THE QUEENSLAND CO-OPERATIVE MILLING ASSOCIATION v HUTCHISON&lt;/caseinfo:fullcasename&gt;
&lt;/caseinfo:casename&gt;
           </codeblock>
    </example>
    <example>
      <title>Example: NZ content</title>
      <codeblock>
&lt;case:casename&gt;Smith (Appellant) v Mackenzie (Respondent)&lt;/case:casename&gt;
           </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;caseinfo:casename&gt;
  &lt;caseinfo:fullcasename&gt;Smith (Appellant) v Mackenzie (Respondent)&lt;/caseinfo:fullcasename&gt;
&lt;/caseinfo:casename&gt;
           </codeblock>
    </example>
    <example>
      <title>Example: UK content</title>
      <codeblock>
&lt;case:casename&gt;Crozier v Wishart &amp;amp; Company Limited and Western Printing Services Ltd&lt;/case:casename&gt;
           </codeblock>
      <b>becomes</b>
      <codeblock>
&lt;caseinfo:casename&gt;
    &lt;caseinfo:fullcasename&gt;Crozier v Wishart &amp;#x0026; Company Limited and Western Printing Services Ltd&lt;/caseinfo:fullcasename&gt;
&lt;/caseinfo:casename&gt;
           </codeblock>
    </example>
    <section>
      <title>Changes</title>
      <p>2015-12-05: <ph id="change_20151205_PS">Added special note for UK01-UK04, RFA # 2602.</ph></p>
      <p>2013-02-20: <ph id="change_20130220_DSF">Added a note regarding the suppression of
        <sourcexml>@ln.user-displayed</sourcexml>.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_caselaw\Rosetta_case.casename-LxAdv_caseinfo.casename_caseinfo.fullcasename.dita  -->

  <!-- JD: added $streamID test for VSTS Bug 379082: all casenames should be combined under a single wrapper. -->
	<xsl:template match="case:casename[$streamID='UK01']">
		<!--  Original Target XPath:  caseinfo:casename/caseinfo:fullcasename   -->
<!--		<caseinfo:casename>-->
	    <caseinfo:fullcasename>
				<xsl:apply-templates select="@* | node()"/>
			  <xsl:apply-templates select="following-sibling::fnr[1]"/>
			</caseinfo:fullcasename>		
		  <xsl:if test="following-sibling::*[1][self::case:casename]">
		    <caseinfo:fullcasename>
		      <xsl:apply-templates select="following-sibling::*[1][self::case:casename]/node()"/>
		    </caseinfo:fullcasename>
		  </xsl:if>
		  <xsl:apply-templates select="parent::case:info/child::abbrvname"/>
		<!--</caseinfo:casename>-->
	</xsl:template>

  <!-- MDS 2017-07-27 - Added following-sibling::fnr[1] to address input in AU13 -->
  <!-- Awantika:2017-10-31- Added the [not(preceding-sibling::*[1][self::case:casename][$streamID='AU01'])] condition to resolve the ambiguity between two case:casename on line 99 and 116-->
  <xsl:template match="case:casename[$streamID!='UK01'][not(preceding-sibling::*[1][self::case:casename][$streamID=('AU01', 'AU13')])]">
    <!--  Original Target XPath:  caseinfo:casename/caseinfo:fullcasename   -->
 		<caseinfo:casename>
      <caseinfo:fullcasename>
        <xsl:apply-templates select="@* | node()"/>
        <xsl:apply-templates select="following-sibling::fnr[1]"/>
      </caseinfo:fullcasename>		
      <xsl:if test="following-sibling::*[1][self::case:casename]">
        <caseinfo:fullcasename>
          <xsl:apply-templates select="following-sibling::*[1][self::case:casename]/node()"/>
        </caseinfo:fullcasename>
      </xsl:if>
      <xsl:apply-templates select="parent::case:info/child::abbrvname"/>
    </caseinfo:casename>
  </xsl:template>
  

  <xsl:template match="case:casename[preceding-sibling::*[1][self::case:casename]]"/>
  
  <xsl:template match="case:casename/nl[starts-with(following-sibling::*[1][self::node()],' ') or ends-with(preceding-sibling::*[1][self::node()],' ')][$streamID='CA01']" priority="2"/>
    
  <xsl:template match="case:casename/nl[$streamID='CA01']" priority="1">
    <xsl:text xml:space="preserve"> </xsl:text>
  </xsl:template>
  
  <!-- Awantika: 2018-02-02- Updated for space issue with nl. W*7104004 -->
  <xsl:template match="case:casename/text()[following-sibling::*[name() = 'nl']]">
    <xsl:value-of select="normalize-space(.)"/>
  </xsl:template>
  
  <xsl:template match="case:casename/nl">
    <xsl:choose>
      <xsl:when test="ends-with(preceding-sibling::text()[1], ' ') or starts-with(following-sibling::text()[1], ' ')">
        <xsl:text> </xsl:text>
      </xsl:when>
      <xsl:otherwise>
        <!--<xsl:text> </xsl:text>-->
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
  
  <xsl:template match="case:casename/@ln.user-displayed"/>
  <xsl:template match="case:casename/@searchtype"/>
 

</xsl:stylesheet>