<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:ci="http://www.lexis-nexis.com/ci" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita case ci">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_case.parallelcite-LxAdv_ref.cite4thisresource">
  <title>case:parallelcite <lnpid>id-CCCC-12045</lnpid></title>
  <body>
    <section id="mapping">
      <p><sourcexml>case:parallelcite</sourcexml> becomes
          <targetxml>ref:citations/ref:cite4thisresource</targetxml> with the value of
          <targetxml>ref:cite4thisresource/@citetype</targetxml> set to "parallel".</p>
      <p>Any occurrences of the attribute <sourcexml>@ln.user-displayed</sourcexml> in
          <sourcexml>case:parallelcite</sourcexml> should be suppressed.</p>
      <p>For the handling of citation markup, please refer to the instructions for
          <sourcexml>ci:cite</sourcexml> in the General Markup Section.</p>
    </section>
    <section id="changes">
      <title>Common Changes</title>
      <p>2013-02-20: <ph id="change_20130220_DSF">Added a note regarding the suppression of
            <sourcexml>@ln.user-displayed</sourcexml>.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_caselaw\conref_content\Rosetta_case.parallelcite-LxAdv_ref.cite4thisresource.dita  -->
<!--	<xsl:message>Rosetta_case.parallelcite-LxAdv_ref.cite4thisresource.xsl requires manual development!</xsl:message> -->

<!--Vikas Rohilla : Updated the template-->
	<xsl:template match="case:parallelcite">
		<ref:citations>
		  <xsl:for-each-group select="child::node()" group-adjacent="if(not(*)) then 1 else 0">
		    <xsl:choose>
		      <xsl:when test="current-grouping-key()=1">
		        <connector>
		          <xsl:apply-templates select="current-group()"/>
		        </connector> 
		      </xsl:when>
		      <xsl:otherwise>
		        <ref:cite4thisresource>
		          <xsl:attribute name="citetype" select="'parallel'"/>
		          <xsl:apply-templates select="current-group()"/>
		        </ref:cite4thisresource>      
		      </xsl:otherwise>
		    </xsl:choose>
		  </xsl:for-each-group>
			
		</ref:citations>

	</xsl:template>

	<xsl:template match="case:parallelcite/@ln.user-displayed"/>

	

</xsl:stylesheet>