<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:casehist="http://www.lexisnexis.com/xmlschemas/content/legal/case-history/1/" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_case.priorhist-to-LexisAdvance_casehist.priorhist">
  <title>case:priorhist-to-casehist:priorhist <lnpid>id-UK03-27434</lnpid></title>
  <body>
    <section>
      <p>
        <sourcexml>case:embeddedcase/case:headnote/case:priorhist</sourcexml> becomes
        <targetxml>courtcase:caseexcerpt/courtcase:head/casehist:casehist/casehist:priorhist/casehist:summary</targetxml>.
        
        The children can be converted as follows : 
        
        <ul>
          <li>
            <sourcexml>case:embeddedcase/case:headnote/case:priorhist/pgrp</sourcexml> becomes
            <targetxml>courtcase:caseexcerpt/courtcase:head/casehist:casehist/casehist:priorhist/casehist:summary/pgrp</targetxml>.
          </li>
          <li>
            <sourcexml>case:embeddedcase/case:headnote/case:priorhist/p</sourcexml> becomes
            <targetxml>courtcase:caseexcerpt/courtcase:head/casehist:casehist/casehist:priorhist/casehist:summary/p</targetxml>.
          </li>
          <li>
            <sourcexml>case:embeddedcase/case:headnote/case:priorhist/h</sourcexml> becomes
            <targetxml>courtcase:caseexcerpt/courtcase:head/casehist:casehist/casehist:priorhist/casehist:summary/h</targetxml>.
          </li>
          <li>
            <sourcexml>case:embeddedcase/case:headnote/case:priorhist/page</sourcexml> becomes
            <targetxml>courtcase:caseexcerpt/courtcase:head/casehist:casehist/casehist:priorhist/casehist:summary/ref:page</targetxml>.
          </li>
          <li>
            <sourcexml>case:embeddedcase/case:headnote/case:priorhist/blockquote</sourcexml> becomes
            <targetxml>courtcase:caseexcerpt/courtcase:head/casehist:casehist/casehist:priorhist/casehist:summary/blockquote</targetxml>.
          </li>
          <li>
            <sourcexml>case:embeddedcase/case:headnote/case:priorhist/table</sourcexml> becomes
            <targetxml>courtcase:caseexcerpt/courtcase:head/casehist:casehist/casehist:priorhist/casehist:summary/table</targetxml>.
          </li>
          <li>
            <sourcexml>case:embeddedcase/case:headnote/case:priorhist/l</sourcexml> becomes
            <targetxml>courtcase:excerpt/courtcase:head/casehist:casehist/casehist:priorhist/casehist:summary/list</targetxml>.
          </li>
          <li>
            <sourcexml>case:embeddedcase/case:headnote/case:priorhist/footnotegrp</sourcexml> becomes
            <targetxml>courtcase:caseexcerpt/courtcase:head/casehist:casehist/casehist:priorhist/casehist:summary/p/text/footnotegrp</targetxml>.
          </li>
        </ul>        
        
        
      </p>
    </section>
    <section>
      <title>Created</title>
      <p>2015-08-12</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK03_CaseDigest\Rosetta_case.priorhist-to-LexisAdvance_casehist.priorhist.dita  -->
	
	<!-- Vikas Rohilla : Template to match the case:priorhist  -->
	<xsl:template match="case:priorhist">
		<casehist:casehist>
			<casehist:priorhist>
				<casehist:summary>
					<xsl:apply-templates select="@* | node()"/>
				</casehist:summary>
			</casehist:priorhist>
		</casehist:casehist>
	</xsl:template>

</xsl:stylesheet>