<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:decision="http://www.lexisnexis.com/xmlschemas/content/legal/decision/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_case.publishdate-to-LexisAdvance_decision.releaseddate">
  <title>case:publishdate-to-decision:releaseddate <lnpid>id-UK03-27435</lnpid></title>
  <body>
    <p>
      <sourcexml>case:publishdate</sourcexml> becomes 
      <targetxml>decision:dates/decision:releaseddate</targetxml>.
      
<pre>
&lt;case:dates&gt;
   &lt;case:publishdate&gt;Published 24 August 2006&lt;/case:publishdate&gt;
&lt;/case:dates&gt;

<b>Becomes</b>
&lt;decision:dates&gt;
  &lt;decision:releaseddate&gt;Published 24 August 2006&lt;/decision:releaseddate&gt;
&lt;/decision:dates&gt;

</pre>
    </p>
    <section>
      <title>Created</title>
      <p>2015-08-12</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK03_CaseDigest\Rosetta_case.publishdate-to-LexisAdvance_decision.releaseddate.dita  -->
	 
	<!-- Vikas Rohilla :  Template match case:publishdate and creates the decision:releaseddate -->
	<xsl:template match="case:publishdate">
			<decision:releaseddate>
				<xsl:apply-templates select="@* | node()"/>
			</decision:releaseddate>

	</xsl:template>

</xsl:stylesheet>