<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
  xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" 
  xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_case.author-to-LexisAdvance_note-byline">
  <title>case:author-to-note/byline <lnpid>id-UK03-27412</lnpid></title>
  <body>
    <section>
      <p>
        <sourcexml>case:author</sourcexml> becomes <targetxml>note/byline</targetxml>.
        The children can be converted as follows:
        
        <ul>
          <li>
            <sourcexml>case:author/person/name.text</sourcexml> becomes 
            <targetxml>note/byline/person:contributor @contributor-type="author"/person:person/person:name.text</targetxml>.
          </li>
        </ul>
        
<pre>
&lt;DIGESTDOC&gt;
  &lt;dig:body&gt;
    &lt;level&gt;
      &lt;bodytext&gt;
        &lt;case:embeddedcase&gt;
          &lt;case:content&gt;
            &lt;case:author&gt;
              &lt;person&gt;
                &lt;name.text&gt;Caroline Stomberg Barrister&lt;/name.text&gt;
              &lt;/person&gt;
            &lt;/case:author&gt;
          &lt;/case:content&gt;
        &lt;/case:embeddedcase&gt;
      &lt;/bodytext&gt;
    &lt;/level&gt;
  &lt;/dig:body&gt;
&lt;/DIGESTDOC&gt;

<b>Becomes</b>
&lt;casedigest:casedigest&gt;
  &lt;casedigest:body&gt;
    &lt;section&gt;
      &lt;bodytext&gt;
        &lt;courtcase:caseexcerpt&gt;
          &lt;courtcase:body&gt;
            &lt;note&gt;
              &lt;byline&gt;
                &lt;person:contributor contributor-type="author"&gt;
                  &lt;person:person&gt;
                    &lt;person:name.text&gt;Caroline Stomberg Barrister&lt;/person:name.text&gt;
                  &lt;/person:person&gt;
                &lt;/person:contributor&gt;
              &lt;/byline&gt;
            &lt;/note&gt;
          &lt;/courtcase:body&gt;
        &lt;/courtcase:caseexcerpt&gt;
      &lt;/bodytext&gt;
    &lt;/section&gt;
  &lt;/casedigest:body&gt;  
&lt;/casedigest:casedigest&gt;
</pre>    
      </p>
    </section>
    <section>
      <title>Created</title>
      <p>2012-10-08</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK03_CaseDigest\Rosetta_case.author-to-LexisAdvance_note-byline.dita  -->
	 
<!-- Vikas Rohilla : updated the Template Initial -->
	<xsl:template match="case:author">
	
		<note>
			<byline>
				<xsl:apply-templates select="@* | node()"/>
			</byline>
		</note>

	</xsl:template>
  
  <xsl:template match="case:author[parent::case:content]">
    
    <note>
      <byline>
        <person:contributor contributor-type="author">
        <xsl:apply-templates select="@* | node()"/>
        </person:contributor>
      </byline>
    </note>
    
  </xsl:template>

<!-- MDS 2017-06-15 - This template is not required as it handled in the person module.  -->
<!--	<xsl:template match="case:author/person/name.text">
	  <person:name.text>
	    <xsl:apply-templates select="@* | node()"/>
	  </person:name.text>
	</xsl:template>-->  
  
<!-- MDS 2017-06-29 - This template is now included in the byling_person.contributor module. -->
<!--  <xsl:template match="case:author/person">
    <person:contributor contributor-type='author'>
      <person:person>
        <xsl:apply-templates select="@*|node()"/>
      </person:person>
    </person:contributor>
  </xsl:template>-->
  
</xsl:stylesheet>