<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:ci="http://www.lexis-nexis.com/ci" xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" version="2.0" exclude-result-prefixes="dita case ci">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="courtorder-case.casename">
  <title><sourcexml>case:casename</sourcexml>  <lnpid>id-UK04-27609</lnpid></title>
  <body>
    <p>The element <sourcexml>case:info/case:name</sourcexml> becomes <targetxml>courtorder:head/heading/title</targetxml>. 
    </p>
    <note>Please see <xref href="../../common_newest/Rosetta_UK_case.casename-Plus-case.reportercite-LxAdv-dc.title.dita"/> for an additional conversion that uses <sourcexml>case:info/case:casename</sourcexml>.</note>
    <section>
      <title>Source XML </title>
      <codeblock>

  &lt;case:body&gt;
    &lt;case:headnote&gt;
      &lt;case:info&gt;
        &lt;!--...--&gt;
        &lt;case:casename&gt;Practice Direction; (Expediting Decree Absolute)&lt;/case:casename&gt;

      </codeblock>
    </section>
    <section>
      <title>Target XML </title>
      <codeblock>

  &lt;courtorder:head&gt;
    &lt;!--...--&gt;
    &lt;heading&gt;
      &lt;title&gt;Practice Direction; (Expediting Decree Absolute)&lt;/title&gt;
    &lt;/heading&gt;

        </codeblock>
    </section>
    <section>
      <title>Changes</title>
      <p>2016-02-01: <ph id="change_20160201_JCG">Added note regarding additional conversion described in the topic <xref href="../../common_newest/Rosetta_UK_case.casename-Plus-case.reportercite-LxAdv-dc.title.dita"/>. Requested in UXRs for these streams during November 2015.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK04_CourtOrder\case.casename.dita  -->
<!--	<xsl:message>UK04_CourtOrder_case.casename.xsl requires manual development!</xsl:message> -->

	<xsl:template match="case:casename">
			<heading>
				<title>
					<xsl:apply-templates select="@* | node()"/>
				</title>
			</heading>
	</xsl:template>

	<!-- Generating dc:title -->
  
  <xsl:template match="case:casename" mode="title">
    <xsl:choose>
      <xsl:when test="/CASEDOC/case:body/case:headnote/case:info/case:reportercite/ci:cite[@type='cite4thisdoc']/ci:content">
        <dc:title>
        <xsl:value-of select="concat(/CASEDOC/case:body/case:headnote/case:info/case:casename, ' ',/CASEDOC/case:body/case:headnote/case:info/case:reportercite/ci:cite[@type='cite4thisdoc']/ci:content)"/>
        </dc:title>
      </xsl:when>
      <xsl:otherwise>
        <dc:title>
          <xsl:value-of select="."/>
        </dc:title>
      </xsl:otherwise>
    </xsl:choose>
    
  </xsl:template>


</xsl:stylesheet>