<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.litigants">
   <title>case:litigants <lnpid>id-UK04-27624</lnpid></title>
   <body>
      <section>
        <p>The element <sourcexml>case:headnote/case:info/case:litigants</sourcexml> is a container
        element that has the child container elements
          <sourcexml>case:constituents/case:constituent/person</sourcexml> as well. The child
        element that contains the text naming the litigants is
          <sourcexml>case:headnote/case:info/case:litigants/case:constituents/case:constituent/person/name.text</sourcexml>,
        and this may contain an actual litigant name or, more often, a sentence indicating there are
        no litigants. Since it would be extremely difficult to parse which of these is the case due
        to an open-ended list of variations, this element is simply mapped to
          <targetxml>caseinfo:party</targetxml>, as is done for other case-releated CIs.</p>
        <p>Therefore, the start-tag and end-tag of all the parent container elements
          (<sourcexml>case:litigants/case:constituents/case:constituent/person</sourcexml>) are
        dropped and
          <sourcexml>case:headnote/case:info/case:litigants/case:constituents/case:constituent/person/name.text</sourcexml>
        becomes
          <targetxml>courtorder:head/caseinfo:caseinfo/caseinfo:casename/caseinfo:fullcasename/caseinfo:party/@partyrole="unknown"</targetxml>.
        (The attribute <targetxml>caseinfo:party@partyrole</targetxml> is set to "unknown".)</p>
      </section>

     <example>
       <title>Source XML</title>
       <codeblock>

&lt;case:headnote&gt;
    &lt;case:info&gt;
      &lt;!-- ... --&gt;
      &lt;case:litigants&gt;
        &lt;case:constituents&gt;
          &lt;case:constituent&gt;
            &lt;person&gt;
              &lt;name.text&gt;None stated at original source&lt;/name.text&gt;
            &lt;/person&gt;
          &lt;/case:constituent&gt;
        &lt;/case:constituents&gt;
      &lt;/case:litigants&gt;
      &lt;!-- ... --&gt;
    &lt;/case:info&gt;
    &lt;!-- ... --&gt;
&lt;/case:headnote&gt;

    </codeblock>
     </example>
     
     <example>
       <title>Target XML</title>
       <codeblock>

&lt;courtorder:head&gt;
    &lt;!-- ... --&gt;
    &lt;caseinfo:caseinfo&gt;
        &lt;caseinfo:casename&gt;
            &lt;caseinfo:fullcasename&gt;
                &lt;caseinfo:party partyrole="unknown"&gt;None stated at original source&lt;/caseinfo:party&gt;
            &lt;/caseinfo:fullcasename&gt;
        &lt;/caseinfo:casename&gt;
    &lt;/caseinfo:caseinfo&gt;
    &lt;!-- ... --&gt;
&lt;/courtorder:head&gt;

    </codeblock>
     </example>

   <section>
     <title>Changes</title>
     <p>2013-05-29: <ph id="change_20130529_JCG">Added this entirely new instruction to handle new XPath appearing in redelivered content.</ph></p>
   </section>
     
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK04_CourtOrder\case.litigants.dita  -->
	<!--<xsl:message>UK04_CourtOrder_case.litigants.xsl requires manual development!</xsl:message> -->

	<xsl:template match="case:litigants">
			<xsl:apply-templates select="@* | node()"/>
	</xsl:template>

  <xsl:template match="case:litigants/case:constituents">
    <xsl:apply-templates select="@* | node()"/>
  </xsl:template>
	
  <xsl:template match="case:litigants/case:constituents/case:constituent" priority="25">
    <xsl:apply-templates select="@* | node()"/>
  </xsl:template>
  
  <xsl:template match="case:litigants/case:constituents/case:constituent/person">
    <xsl:apply-templates select="@*|node()"/>
  </xsl:template>
  
  <xsl:template match="case:litigants/case:constituents/case:constituent/person/name.text">
    <caseinfo:caseinfo>
      <caseinfo:casename>
        <caseinfo:fullcasename>
          <caseinfo:party partyrole="unknown">
            <xsl:apply-templates select="@*|node()"/>
          </caseinfo:party>
        </caseinfo:fullcasename>
      </caseinfo:casename>
    </caseinfo:caseinfo>
  </xsl:template>
</xsl:stylesheet>