<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:leg="http://www.lexis-nexis.com/glp/leg"
    xmlns:source_cttr="http://www.lexis-nexis.com/glp/cttr"
    xmlns:cttr="urn:x-lexisnexis:content:citator:sharedservices:1" version="2.0" exclude-result-prefixes="dita case source_cttr cttr leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK11_DA_citations.use">
    <title>*:citations <lnpid>id-UK11DA-29411</lnpid></title>
    <body>
        <section>
            <ul id="ul_xym_akl_ti">
                <li><sourcexml>case:citations</sourcexml> becomes
                        <targetxml>cttr:caseinfo/cttr:citations</targetxml>.</li>
                <li><sourcexml>leg:citations</sourcexml> becomes
                        <targetxml>cttr:legisinfo/cttr:citations</targetxml>.<ul id="ul_ooz_zim_ti">
                        <li>drop <sourcexml>case:citetext</sourcexml> and
                                <sourcexml>leg:citetext</sourcexml>, but process child elements as
                            instructed.</li>
                    </ul></li>
            </ul>
        </section>

        <pre>
              <b><i>Example: Source XML 1</i></b>
                  

&lt;dig:body&gt;
...
  &lt;cttr:annotations annotationtype="consideredcases"&gt;
    &lt;heading&gt;
        &lt;title&gt;Cases considered in this article&lt;/title&gt;
    &lt;/heading&gt;
    &lt;cttr:annot&gt;
      &lt;cttr:use-group&gt;
          &lt;cttr:use signal="positive"&gt;Positive&lt;/cttr:use&gt;
      &lt;/cttr:use-group&gt;
      ...
      &lt;case:citations&gt;
          ...
      &lt;/case:citations&gt;
    &lt;/cttr:annot&gt;
  &lt;/cttr:annotations&gt;
  &lt;cttr:annotations annotationtype="consideredleg"&gt;
    &lt;heading&gt;
        &lt;title&gt;Legislation considered in this article&lt;/title&gt;
    &lt;/heading&gt;
    &lt;cttr:annot leg-signal="in-force-commenced-amend"&gt;
      &lt;cttr:use-group&gt;
          &lt;cttr:use&gt;In force with commencement&lt;/cttr:use&gt;
      &lt;/cttr:use-group&gt;
      ...
      &lt;leg:citations&gt;
          ...
      &lt;/leg:citations&gt;
    &lt;/cttr:annot&gt;
  &lt;/cttr:annotations&gt;
&lt;/dig:body&gt;
 
	</pre>
        <pre>
                    
              <b><i>Example: Target XML 1</i></b>
    
&lt;abstract:body&gt;
  &lt;cttr:refs&gt;
    &lt;cttr:refsection reftype="considered-cases"&gt;
      &lt;heading&gt;
          &lt;title&gt;Cases considered in this article&lt;/title&gt;
      &lt;/heading&gt;
      &lt;cttr:refitem&gt;
          &lt;cttr:consideredcase treatment="unspecified"&gt;
          ...
            &lt;cttr:usagegroup&gt;
                &lt;cttr:usage usagetype="positive"&gt;
                    &lt;text&gt;Positive&lt;/text&gt;
                &lt;/cttr:usage&gt;
            &lt;/cttr:usagegroup&gt;
            &lt;cttr:caseinfo&gt;
                  ...
                  &lt;cttr:citations&gt;
                      ...
                  &lt;/cttr:citations&gt;
                  ...
            &lt;/cttr:caseinfo&gt;
          &lt;/cttr:consideredcase&gt;
      &lt;cttr:refitem&gt;
    &lt;/cttr:refsection&gt;
    &lt;cttr:refsection reftype="considered-legislation"&gt;
      &lt;heading&gt;
          &lt;title&gt;Legislation considered in this article&lt;/title&gt;
      &lt;/heading&gt;
      &lt;cttr:refitem&gt;
          &lt;cttr:consideredlegis&gt;
            ...
            &lt;cttr:legisinfo&gt;
                &lt;cttr:citations&gt;
                   ...
                &lt;/cttr:citations&gt;
                &lt;legisinfo:status statuscode="in-force-commenced-amend"&gt;
                  &lt;legisinfo:statustext&gt;In force with commencement&lt;/legisinfo:statustext&gt;
                &lt;/legisinfo:status&gt;
            &lt;/cttr:legisinfo&gt;
          &lt;/cttr:consideredlegis&gt;
      &lt;cttr:refitem&gt;
    &lt;/cttr:refsection&gt;
  &lt;cttr:refs&gt;
&lt;/abstract:body&gt;

                </pre>
        <section>
            <title>Changes</title>
            <p>2013-07-31: <ph id="change_20130731_jm">Expanded example to include
                    considered-legislation. No change to rules</ph>.</p></section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK11DA-Digest-Abstract\UK11_DA_citations.dita  -->
<!--	<xsl:message>UK11_DA_citations.xsl requires manual development!</xsl:message> -->
    
    <xsl:template match="case:citations">
            <cttr:citations>
                <xsl:apply-templates select="@* | node()"/>
            </cttr:citations>
    </xsl:template>
    
    <xsl:template match="leg:citations">
        <cttr:legisinfo>
            <cttr:citations>
                <xsl:apply-templates select="@* | node()"/>
            </cttr:citations>
            <xsl:apply-templates select="parent::source_cttr:annot/source_cttr:use-group"/>
        </cttr:legisinfo>
    </xsl:template>
    
    <xsl:template match="case:citetext">
        <xsl:apply-templates select="@* | node()"/>        
    </xsl:template>
    
    <xsl:template match="leg:citetext">
        <xsl:apply-templates select="@* | node()"/>
    </xsl:template>

</xsl:stylesheet>