<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:frm="http://www.lexis-nexis.com/glp/frm"
	xmlns:case="http://www.lexis-nexis.com/glp/case"
	xmlns:leg="http://www.lexis-nexis.com/glp/leg"
	xmlns:casesum="http://www.lexisnexis.com/xmlschemas/content/legal/case-summary/1/"
	xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
	xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/"
	xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/"
	xmlns:annot="http://www.lexisnexis.com/xmlschemas/content/shared/annotations/1/"
	xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/"
	xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/"
	xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/"
	xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0"
	exclude-result-prefixes="dita frm case leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
		id="UK12_case.embeddedcase"> 
		<title>case:embeddedcase <lnpid>id-UK12-29835</lnpid> </title>
		<body>
			<section>
				<ul>
					<li>
						<sourcexml>case:embeddedcase</sourcexml> becomes
						<targetxml>courtcase:caseexcerpt</targetxml>. <note>
							<sourcexml>case:embeddedcase</sourcexml> occurs under
							<sourcexml>level/bodytext</sourcexml> becomes
							<targetxml>seclaw:level/seclaw:bodytext/seclaw:digestgrp/seclaw:digest/courtcase:caseexcerpt</targetxml>
							The children can be converted as follows: <ul id="ul_rvf_41q_pz">
								<li>
									<sourcexml>case:embeddedcase/case:headnote</sourcexml> becomes
									<targetxml>courtcase:caseexcerpt/courtcase:head</targetxml></li>
							</ul></note>
						<pre>
<![CDATA[
<level leveltype="section">
    <bodytext>
        <case:embeddedcase>
            <case:headnote>
            ..........
            ..........
            </case:headnote>
        </case:embeddedcase>
    </bodytext>
</level>
]]>

<b>Becomes</b>   

<![CDATA[
<seclaw:level leveltype="section">
    <seclaw:bodytext>
        <seclaw:digestgrp>
            <seclaw:digest>
                <courtcase:caseexcerpt>
                    <courtcase:head>
                    ..........
                    ..........
                    </courtcase:head>
                </courtcase:caseexcerpt>
            </seclaw:digest>
        </seclaw:digestgrp>
    </seclaw:bodytext>
</seclaw:level>
]]></pre>
					</li>
				</ul>
			</section>
			
			<section>
				<title>Changes</title>
				<p>2017-04-18:<ph id="change_20170418_RS">Created. VSTS Issue 272255</ph></p>
			</section>
		</body>
		
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK/UK12-Treatise/UK12_case.embeddedcase.dita -->
<!--	<xsl:message>UK12_case.embeddedcase.xsl requires manual development!</xsl:message> -->
	
	<!-- Vikas Rohilla : template match for the case:embeddedcase-->
	<xsl:template match="case:embeddedcase">
		<seclaw:digestgrp>
			<seclaw:digest>
		<courtcase:caseexcerpt>
			<xsl:apply-templates select="@*|node()"/>
		</courtcase:caseexcerpt>
			</seclaw:digest>
			
		</seclaw:digestgrp>
	</xsl:template>
	
	<xsl:template match="case:headnote">
		<courtcase:head>
			<xsl:apply-templates select="@*|node() except catchwordgrp"/>
		</courtcase:head>
	</xsl:template>

<xsl:template match="prelim">
	<courtcase:prelim>
		<bodytext>
			<xsl:apply-templates select="node()"/>
		</bodytext>
	</courtcase:prelim>
	
</xsl:template>

	<xsl:template match="case:disposition">
		<casesum:summaries>
		<casesum:disposition>
			<p>
				<text>
					<xsl:apply-templates/>		
				</text>
			</p>			
		</casesum:disposition>
		</casesum:summaries>
	</xsl:template>
	
	<xsl:template match="case:disposition[parent::case:judgments]">
		<casesum:disposition>
			<p>
				<text>
					<xsl:apply-templates/>		
				</text>
			</p>			
		</casesum:disposition>
	</xsl:template>

</xsl:stylesheet>
