<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:frm="http://www.lexis-nexis.com/glp/frm" 
	xmlns:case="http://www.lexis-nexis.com/glp/case"
	xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
	xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/"
	xmlns:leg="http://www.lexis-nexis.com/glp/leg"
	xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/"
	xmlns:annot="http://www.lexisnexis.com/xmlschemas/content/shared/annotations/1/"
	xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/"
	xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/"
	xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0"
	exclude-result-prefixes="dita frm case leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
	  id="UK12_case.judgments-to-LexisAdvance_courtcase.opinions"> 
	  <title>case:judgments-to-courtcase:opinions <lnpid>id-UK12-29837</lnpid> </title>
	  <body>
	    <section>
	      <p>
	        <sourcexml>case:embeddedcase/case:content/case:judgments</sourcexml>
	        becomes
	        <targetxml>courtcase:caseexcerpt/courtcase:body/courtcase:opinions</targetxml>.
	        The children can be converted as follows: <ul>
	          <li>
	            <sourcexml>case:embeddedcase/case:content/case:judgments/case:judgment</sourcexml>
	            becomes
	            <targetxml>courtcase:caseexcerpt/courtcase:body/courtcase:opinions/courtcase:opinion</targetxml>.
	            The source attributes <sourcexml>case:judgment/@subdoc</sourcexml> becomes
	            <targetxml>courtcase:opinion/@includeintoc</targetxml> and
	            <sourcexml>case:judgment/@toc-caption</sourcexml> becomes
	            <targetxml>courtcase:opinion/@alternatetoccaption</targetxml>. The children can be
	            converted as follows: 
	            <ul>
	              <li>
	                <sourcexml>case:embeddedcase/case:content/case:judgments/case:judgment/case:judgmentbody</sourcexml>
	                becomes
	                <targetxml>courtcase:caseexcerpt/courtcase:body/courtcase:opinions/courtcase:opinion/bodytext</targetxml>.
	                The children can be converted as follows: 
	                <ul>
	                  <li>
	                    <sourcexml>case:judgments/case:judgment/case:judgmentbody/p</sourcexml>
	                    becomes
	                    <targetxml>courtcase:opinions/courtcase:opinion/bodytext/p</targetxml>. </li>
	                  
	                  <li>
	                    <sourcexml>case:judgments/case:judgment/case:judgmentbody/h</sourcexml>
	                    becomes
	                    <targetxml>courtcase:opinions/courtcase:opinion/bodytext/h</targetxml>. 
	                    
	                    <pre>       
<![CDATA[  
<case:judgments>
        <case:judgment>
            <case:judgmentbody>
                <h l="1">Key extracts from judgment</h>
                <p>
                    <text><emph typestyle="bf">THE HONOURABLE MR JUSTICE COLLINS
                        (PRESIDENT):</emph></text>
                </p>
            </case:judgmentbody>
       </case:judgment>
</case:judgments>
]]>
<b>Becomes</b>
<![CDATA[              
<courtcase:opinions>
   <courtcase:opinion>
       <bodytext>
           <h level="1">Key extracts from judgment</h>
           <p>
               <text><emph typestyle="bf">THE HONOURABLE MR JUSTICE COLLINS
                   (PRESIDENT):</emph></text>
           </p>
       </bodytext>
   </courtcase:opinion>
</courtcase:opinions>
]]>
</pre>
	                  </li>
	                  
	                </ul>
	              </li>
	            </ul>
	          </li>
	        </ul>
	      </p>
	    </section>
	    
	    
	    
	    <section>
	      <title>Changes</title>
	      <p>2017-04-24: <ph id="change_20170424_RS">Created. VSTS Issue 272255</ph></p>
	    </section>
	  </body>
	  
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK/UK12-Treatise/UK12_case.judgments-to-LexisAdvance_courtcase.opinions.dita -->
<!--  <xsl:message>UK12_case.judgments-to-LexisAdvance_courtcase.opinions.xsl requires manual development!</xsl:message> -->
		
	<xsl:template match="case:content">
		<courtcase:body>
			<xsl:apply-templates select="@*|node()"/>
		</courtcase:body>
	</xsl:template>
		
	<xsl:template match="case:content[normalize-space(.)='']"/>
		
	
	<xsl:template match="case:judgments">
	<courtcase:opinions>
		<xsl:apply-templates select="@*|node()"/>
	</courtcase:opinions>
	</xsl:template>
	
	<xsl:template match="case:judgment">
		<courtcase:opinion>
			<xsl:apply-templates select="@*|node()"/>
		</courtcase:opinion>
	</xsl:template>
	
	<xsl:template match="case:judgment/@toc-caption">
		<xsl:attribute name="alternatetoccaption">
			<xsl:value-of select="."/>
		</xsl:attribute>
	</xsl:template>
	
	<xsl:template match="case:judgmentbody">
		<bodytext>
			<xsl:apply-templates select="@*|node()"/>
		</bodytext>
	</xsl:template>
	


	

</xsl:stylesheet>
