<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:lnv="http://www.lexis-nexis.com/lnv" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0" exclude-result-prefixes="dita lnv">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="RU02-lnv_LOAD-DATE_lnvxe_date">
    <title>lnv:LOAD-DATE/lnvxe:date <lnpid>id-RU02-32042</lnpid>
    </title>

    <body>
        <p>
            <sourcexml>lnv:LOAD-DATE/lnvxe:date</sourcexml> becomes
                <targetxml>dc:metadata/dc:date[@lnmeta:datetype="load-date"].</targetxml>. </p>

        <note><b>Note:</b> The format of the content of all dc:date elements must be in
            'YYYY-MM-DD'.</note>

        <example>
            <title>Source XML</title>
            <codeblock>
&lt;lnv:LOAD-DATE&gt;
      &lt;lnvxe:date day="26" month="09" year="2013"&gt;September 26, 2013&lt;/lnvxe:date&gt;
&lt;/lnv:LOAD-DATE&gt;

	</codeblock>
        </example>

        <example>
            <title>Target XML </title>
            <codeblock>
&lt;doc:docinfo doc-content-country="RU"&gt;
    &lt;dc:metadata&gt;
        &lt;dc:date lnmeta:datetype="load-date"&gt;2013-09-26&lt;/dc:date&gt;
    &lt;/dc:metadata&gt;
&lt;/doc:docinfo&gt;

	</codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>Created.</p>
        </section>
    </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\RU02\RU02-lnv_LOAD-DATE_lnvxe_date.dita  -->
	<xsl:message>RU02-lnv_LOAD-DATE_lnvxe_date.xsl requires manual development!</xsl:message> 

	<xsl:template match="lnv:LOAD-DATE/lnvxe:date">

		<!--  Original Target XPath:  dc:metadata/dc:date[@lnmeta:datetype="load-date"].   -->
		<dc:metadata>
			<dc:date>
				<xsl:apply-templates select="@* | node()"/>
			</dc:date>
		</dc:metadata>

	</xsl:template>

</xsl:stylesheet>