<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:lnvxe="http://www.lexis-nexis.com/lnvxe" version="2.0" exclude-result-prefixes="dita lnvxe">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="RU02-lnvxe_title">
    <title>lnvxe:title <lnpid>id-RU02-32036</lnpid>
    </title>

    <body>
        <p>
            <sourcexml>lnvxe:title</sourcexml> becomes <targetxml>title</targetxml>. </p>

        <example>
            <title>Source XML</title>
            <codeblock>
&lt;lnv:HIER&gt;
    &lt;lnvxe:hierlev role="me"&gt;
        &lt;lnvxe:heading inline="false"&gt;
                &lt;lnvxe:title&gt;ARTICLE 137. ANIMALS&lt;/lnvxe:title&gt;
        &lt;/lnvxe:heading&gt;
    &lt;/lnvxe:hierlev&gt;
&lt;/lnv:HIER&gt;

	</codeblock>
        </example>

        <example>
            <title>Target XML </title>
            <codeblock>
&lt;doc:hier&gt;
    &lt;doc:hierlev&gt;
        &lt;heading inline="false"&gt;
            &lt;title&gt;ARTICLE 137. ANIMALS&lt;/title&gt;
        &lt;/heading&gt;
    &lt;/doc:hierlev&gt;
&lt;/doc:hier&gt;

	</codeblock>
        </example>
        <section>
            <title>Changes</title>
            <p>Created.</p>
        </section>
    </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\RU02\RU02-lnvxe_title.dita  -->
	<xsl:message>RU02-lnvxe_title.xsl requires manual development!</xsl:message> 

	<xsl:template match="lnvxe:title">

		<!--  Original Target XPath:  title   -->
		<title>
			<xsl:apply-templates select="@* | node()"/>
		</title>

	</xsl:template>

</xsl:stylesheet>