<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:source_cttr="http://www.lexis-nexis.com/glp/cttr" xmlns:abstract="urn:x-lexisnexis:content:abstract:sharedservices:1" xmlns:cttr="urn:x-lexisnexis:content:citator:sharedservices:1" version="2.0" exclude-result-prefixes="dita source_cttr cttr">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK11_DA_cttr.annotations">
  <title>cttr:annotations <lnpid>id-UK11DA-29415</lnpid></title>
  <body>
    <section>
      <p><sourcexml>cttr:annotations</sourcexml> becomes
          <targetxml>abstract:body/cttr:refs/cttr:refsection</targetxml>. If
          <sourcexml>cttr:annotations</sourcexml> exists, create a <targetxml>cttr:refs</targetxml>.
        Then each occurence of <sourcexml>cttr:annotations</sourcexml> becomes a
          <targetxml>cttr:refsection</targetxml> child of <targetxml>cttr:refs</targetxml>. <ul>
          <li><sourcexml>cttr:annotations[@annotationtype="consideredcases"]</sourcexml> becomes
              <targetxml>cttr:refsection[@reftype="considered-cases"]</targetxml>.</li>
          <li><sourcexml>cttr:annotations[@annotationtype="consideredleg"]</sourcexml> becomes
              <targetxml>cttr:refsection[@reftype="considered-legislation"]</targetxml></li>
        </ul></p></section>

    <pre>
              <b><i>Example: Source XML 1</i></b>
                  

&lt;dig:body&gt;
...
  &lt;cttr:annotations annotationtype="consideredcases"&gt;
    &lt;heading&gt;
        &lt;title&gt;Cases considered in this article&lt;/title&gt;
    &lt;/heading&gt;
    ...
  &lt;/cttr:annotations&gt;
  &lt;cttr:annotations annotationtype="consideredleg"&gt;
    &lt;heading&gt;
        &lt;title&gt;Legislation considered in this article&lt;/title&gt;
    &lt;/heading&gt;
    ...
  &lt;/cttr:annotations&gt;
&lt;/dig:body&gt;
 
	</pre>
    <pre>
                    
              <b><i>Example: Target XML 1</i></b>
    
&lt;abstract:body&gt;
  &lt;cttr:refs&gt;
    &lt;cttr:refsection reftype="considered-cases"&gt;
      &lt;heading&gt;
          &lt;title&gt;Cases considered in this article&lt;/title&gt;
      &lt;/heading&gt;
      ...
    &lt;/cttr:refsection&gt;
    &lt;cttr:refsection reftype="considered-legislation"&gt;
      &lt;heading&gt;
          &lt;title&gt;Legislation considered in this article&lt;/title&gt;
      &lt;/heading&gt;
      ...
    &lt;/cttr:refsection&gt;
  &lt;cttr:refs&gt;
&lt;/abstract:body&gt;

                </pre>
    <section>
      <title>Changes</title>
      <p>2013-07-31: <ph id="change_20130731_jm">Expanded example to show two
            <sourcexml>cttr:annotations</sourcexml>. No change to rules.</ph></p>
      <p>2013-04-08: <ph id="change_20130408_jm"><sourcexml>cttr:annotations</sourcexml> -
            <targetxml>cttr:refs</targetxml> added to Abstract schema. Removed reference to pending
          CR.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK11DA-Digest-Abstract\UK11_DA_cttr.annotations.dita  -->
<!--	<xsl:message>UK11_DA_cttr.annotations.xsl requires manual development!</xsl:message> -->

  <xsl:template match="source_cttr:annotations[@annotationtype='consideredcases']">
	  <cttr:refs>
				<cttr:refsection>
				  <xsl:attribute name="reftype" select="'considered-cases'"/> 
					<xsl:apply-templates select="@* | node()"/>
				</cttr:refsection>
			</cttr:refs>
	</xsl:template>
  
  <xsl:template match="source_cttr:annotations[@annotationtype='consideredleg']">
    <cttr:refs>
      <cttr:refsection>
        <xsl:attribute name="reftype" select="'considered-legislation'"/> 
        <xsl:apply-templates select="@* | node()"/>
      </cttr:refsection>
    </cttr:refs>
  </xsl:template>
  
  
  
  <xsl:template match="source_cttr:annotations/@annotationtype"/>


</xsl:stylesheet>