<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
  xmlns:dig="http://www.lexis-nexis.com/glp/dig"
  xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/"
  xmlns:index="urn:x-lexisnexis:content:publicationindex:sharedservices:1"
  xmlns:pubfm="http://www.lexisnexis.com/xmlschemas/content/shared/publication-front-matter/1/"
  xmlns:pubup="http://www.lexisnexis.com/xmlschemas/content/shared/publication-update/1/"
  xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0"
  exclude-result-prefixes="dita dig">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Body">
    <title>Body <lnpid>id-CA02DS-12809</lnpid></title>

    <body>
      <p>
        <sourcexml>dig:body</sourcexml> becomes <targetxml>seclaw:body</targetxml>
      </p>

      <p>
        <targetxml>seclaw:body</targetxml> element requires at least one of the following child
        elements: </p>

      <p>
        <targetxml>seclaw:level</targetxml>, <targetxml>seclaw:appendix</targetxml>,
          <targetxml>seclaw:digestgrp</targetxml>, <targetxml>seclaw:supplement</targetxml>,
          <targetxml>form:form</targetxml>, <targetxml>toc</targetxml>,
          <targetxml>unitscope</targetxml>, <targetxml>pubfm:pubfm</targetxml>,
          <targetxml>pubup:pubup</targetxml> and <targetxml>index:index</targetxml>. </p>

    </body>

  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA02-Case_Summaries\CA02DS_DIGESTDOC_to_seclaw\Body.dita  -->
  <!--<xsl:message>CA02DS_DIGESTDOC_to_seclaw_Body.xsl requires manual development!</xsl:message>-->


  <!-- Vikas Rohilla : Template to match the dig:body and create seclaw:body   -->
  <xsl:template match="dig:body">
    <seclaw:body>
      <xsl:apply-templates select="@* | node()"/>
    </seclaw:body>
  </xsl:template>

</xsl:stylesheet>
