<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:dig="http://www.lexis-nexis.com/glp/dig" xmlns:casedigest="http://www.lexisnexis.com/xmlschemas/content/legal/case-digest/1/" version="2.0" exclude-result-prefixes="dita dig">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Linxplus-CaseDigest_dig_body">
    <title>dig:body <lnpid>id-NZ07DC-23623</lnpid></title>

  <body>
    <p><sourcexml>dig:body</sourcexml> becomes <targetxml>casedigest:casedigest/casedigest:body</targetxml></p>
      
     
<pre xml:space="preserve">
&lt;DIGESTDOC&gt;
    &lt;dig:body&gt;
        ...
    &lt;/dig:body&gt;
    ...
&lt;/DIGESTDOC&gt;

<b>Becomes</b>

&lt;casedigest:casedigest&gt;
    &lt;casedigest:body&gt;
        ...
    &lt;/casedigest:body&gt;
    ...
&lt;/casedigest:casedigest&gt;
</pre>
</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ07_Linxplus\NZ07DC_Linxplus-CaseDigest\Linxplus-CaseDigest_dig_body.dita  -->
	<!--<xsl:message>Linxplus-CaseDigest_dig_body.xsl requires manual development!</xsl:message> -->

	<xsl:template match="dig:body">
			<casedigest:body>
			    <xsl:call-template name="decisiontype"/>
				<xsl:apply-templates select="@* | node()"/>
			</casedigest:body>
	</xsl:template>

</xsl:stylesheet>