<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
  xmlns:dig="http://www.lexis-nexis.com/glp/dig" 
  xmlns:classify="http://www.lexisnexis.com/xmlschemas/content/shared/classification/1/"
  xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita dig">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK11_DN_dig.subject">
  <title>dig:subject <lnpid>id-UK11DN-29612</lnpid></title>
  <body>
    <section>
      <p><sourcexml>dig:subject</sourcexml> becomes
          <targetxml>doc:metadata/doc:docinfo/classify:classification[@classscheme="jurisdictionAffected"]/classify:classitem/classify:classitem-identifier/classify:classname</targetxml>.</p></section>

    <pre>
              <b><i>Example: Source XML 1</i></b>
                  

&lt;dig:body&gt;
  &lt;dig:info&gt;
    &lt;dig:subject&gt;England; Wales&lt;/dig:subject&gt;
  &lt;/dig:info&gt;
&lt;/dig:body&gt;
 
	</pre>
    <pre>
                    
              <b><i>Example: Target XML 1</i></b>
    
&lt;doc:metadata&gt;
  &lt;doc:docinfo&gt;
    &lt;classify:classification classscheme="jurisdictionAffected"&gt;
      &lt;classify:classitem&gt;
        &lt;classify:classitem-identifier&gt;
          &lt;classify:classname&gt;England; Wales&lt;/classify:classname&gt;
        &lt;/classify:classitem-identifier&gt;
      &lt;/classify:classitem&gt;
    &lt;/classify:classification&gt;
  &lt;/doc:docinfo&gt;
&lt;/doc:metadata&gt;

                </pre>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK11DN-Digest-Newsitem\UK11_DN_dig.subject.dita  -->
	 

	<xsl:template match="dig:subject">

		<!--  Original Target XPath:  doc:metadata/doc:docinfo/classify:classification[@classscheme="jurisdictionAffected"]/classify:classitem/classify:classitem-identifier/classify:classname   -->
		
				<classify:classification>
				  <xsl:attribute name="classscheme">
				    <xsl:text>jurisdictionAffected</xsl:text>
				  </xsl:attribute>
					<classify:classitem>
						<classify:classitem-identifier>
							<classify:classname>
								<xsl:apply-templates select="node()"/>
							</classify:classname>
						</classify:classitem-identifier>
					</classify:classitem>
				</classify:classification>

	</xsl:template>

</xsl:stylesheet>