<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
    xmlns:leg="http://www.lexis-nexis.com/glp/leg"
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:dig="http://www.lexis-nexis.com/glp/dig" xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/" version="2.0" exclude-result-prefixes="dita dig">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK11_DN_dig.body">
    <title>dig:body <lnpid>id-UK11DN-29609</lnpid></title>
    <shortdesc>This section describes <sourcexml>dig:body</sourcexml> and its descendants. Handle in
        document order unless specifically stated otherwise. Refer to General Markup Section for
        handling of children (including mixed content).</shortdesc>
    <body>
        <section>
            <title>dig:body</title>
            <p><sourcexml>dig:body</sourcexml> becomes
            <targetxml>nitf:body</targetxml>.</p></section>
        <pre>
              <b><i>Example: Source XML 1</i></b>
                  

&lt;DIGESTDOC&gt;
  &lt;dig:body&gt;...&lt;/dig:body&gt;
&lt;/DIGESTDOC&gt;
 
	</pre>
        <pre>
                    
              <b><i>Example: Target XML 1</i></b>
                  

&lt;newsitem:newsitem&gt;
  &lt;nitf:body&gt;...&lt;/nitf:body&gt;
&lt;/newsitem:newsitem&gt;


                </pre>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK11DN-Digest-Newsitem\UK11_DN_dig.body.dita  -->
	 

	<xsl:template match="dig:body">

		<!--  Original Target XPath:  nitf:body   -->
		<nitf:body>
		    <xsl:apply-templates select="@*"/>
		    <nitf:body.head>
		        <xsl:apply-templates select="dig:info/dig:title | contrib/org | abstract | dig:info/dig:type"/>
		    </nitf:body.head>
		    <nitf:body.content>
		        <bodytext>
		        <xsl:apply-templates select="dig:info/references | dig:info/leg:info | level"/>
		        </bodytext>
		    </nitf:body.content>			
		    
		</nitf:body>	    

	</xsl:template>

</xsl:stylesheet>