<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" 
  xmlns:dig="http://www.lexis-nexis.com/glp/dig" 
  xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/"
  xmlns:newsitem="http://www.lexisnexis.com/xmlschemas/content/news/newsitem/1/" version="2.0" exclude-result-prefixes="dita dig ref">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK11_DN_dig.cite">
  <title>dig:cite <lnpid>id-UK11DN-29610</lnpid></title>
  <body>
    <section>
      <p><sourcexml>dig:cite</sourcexml> becomes
          <targetxml>newsitem:head/ref:citations/ref:cite4thisresource</targetxml>.</p></section>
    <note><targetxml>newsitem:head</targetxml> is a required child of
        <targetxml>newsitem:newsitem</targetxml>. If <sourcexml>dig:cite</sourcexml> is not present,
      create <targetxml>newsitem:head</targetxml> as an empty element.</note>
    <pre>
              <b><i>Example: Source XML 1</i></b>
                  

&lt;dig:body&gt;
  &lt;dig:info&gt;
    &lt;dig:cite&gt;
      &lt;ci:cite&gt;
          &lt;ci:content&gt;LNB News 05/12/2005 15&lt;/ci:content&gt;
      &lt;/ci:cite&gt;
    &lt;/dig:cite&gt;
  &lt;/dig:info&gt;
&lt;/dig:body&gt;
 
	</pre>
    <pre>
                    
              <b><i>Example: Target XML 1</i></b>
    
&lt;newsitem:head&gt;
  &lt;ref:citations&gt;
    &lt;ref:cite4thisresource&gt;
      &lt;lnci:cite&gt;
         &lt;lnci:content&gt;LNB News 05/12/2005 15&lt;/lnci:content&gt;
      &lt;/lnci:cite&gt;
    &lt;/ref:cite4thisresource&gt;
  &lt;/ref:citations&gt;
&lt;/newsitem:head&gt;

                </pre>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK11DN-Digest-Newsitem\UK11_DN_dig.cite.dita  -->
	 

	<xsl:template match="dig:cite">

		<!--  Original Target XPath:  newsitem:head/ref:citations/ref:cite4thisresource   -->
		
			<ref:citations>
				<ref:cite4thisresource>
					<xsl:apply-templates select="@* | node()"/>
				</ref:cite4thisresource>
			</ref:citations>
		

	</xsl:template>

</xsl:stylesheet>