<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"
    xmlns:dig="http://www.lexis-nexis.com/glp/dig"
    xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0"
    exclude-result-prefixes="dita dig doc">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK15PG_DIGESTDOC_dig.body">
        <title>dig:body <lnpid>id-UK15-30434</lnpid></title>

        <body>
            <p><sourcexml>dig:body</sourcexml> becomes <targetxml>seclaw:body</targetxml>.</p>
            <example>
                <title>Source XML</title>
                <codeblock> &lt;DIGESTDOC&gt; ... &lt;dig:body&gt; ... &lt;/dig:body&gt;
                    &lt;/DIGESTDOC&gt; </codeblock>
                <title>Target XML</title>
                <codeblock> &lt;seclaw:seclaw&gt; ... &lt;seclaw:body&gt; ... &lt;/seclaw:body&gt;
                    ... &lt;/seclaw:seclaw&gt; </codeblock>
            </example>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK15-PracticalGuidance\UK15PG_DIGESTDOC_dig.body.dita  -->
    <!--<xsl:message>UK15PG_DIGESTDOC_dig.body.xsl requires manual development!</xsl:message> -->

    <xsl:template match="dig:body">
        <seclaw:head> 
            <xsl:apply-templates select="dig:info/dig:cite"/>
        </seclaw:head>
       
        
            <xsl:apply-templates select="dig:info"/>
        
        <doc:metadata>
            <xsl:apply-templates select="dig:info/pubdate"/>
            <xsl:apply-templates select="preceding-sibling::docinfo"/>
        </doc:metadata>
    </xsl:template>

</xsl:stylesheet>
