<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns:dig="http://www.lexis-nexis.com/glp/dig"
    xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"
    xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0"
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/"
    exclude-result-prefixes="dita dig docinfo ref">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
        id="UK15PG_DIGESTDOC_dig.info_With-Forms">
        <title>dig:info <lnpid>id-UK15-30437</lnpid></title>

        <body>
            <p><sourcexml>dig:info</sourcexml> becomes <targetxml>seclaw:level</targetxml>. Value of
                    <targetxml>@leveltype</targetxml> is determined as follows:</p>
            <ul>
                <li>If source has <sourcexml>docinfo:selector</sourcexml> with content "SmartForm"
                    (without quotes), then
                    <targetxml>seclaw:level[@leveltype="form"]</targetxml>.</li>
                <li>Otherwise, <targetxml>seclaw:level[@leveltype="unclassified"]</targetxml>.</li>
            </ul>
            <note><targetxml>seclaw:bodytext</targetxml> must be created as a mandatory child of
                    <targetxml>seclaw:level</targetxml> even if it remains an empty element.</note>
            <example>
                <title>Source XML. "form"</title>
                <codeblock> &lt;docinfo&gt; ...
                    &lt;docinfo:selector&gt;SmartForm&lt;/docinfo:selector&gt; ... &lt;/docinfo&gt;
                    &lt;dig:body&gt; &lt;dig:info&gt; &lt;dig:title&gt;Instructions from
                    Client&lt;/dig:title&gt; &lt;/dig:info&gt; &lt;/dig:body&gt; </codeblock>
                <title>Target XML. "form"</title>
                <codeblock> &lt;seclaw:level leveltype="form"&gt; &lt;heading&gt;
                    &lt;title&gt;Instructions from Client&lt;/title&gt; &lt;/heading&gt;
                    &lt;seclaw:bodytext/&gt; &lt;/seclaw:level&gt; </codeblock>
            </example>
            <example>
                <title>Source XML. All others</title>
                <codeblock> &lt;dig:body&gt; &lt;dig:info&gt; &lt;dig:title&gt;Medical
                    diagrams&lt;/dig:title&gt; &lt;/dig:info&gt; &lt;/dig:body&gt; </codeblock>
                <title>Target XML. All others</title>
                <codeblock> &lt;seclaw:level leveltype="unclassified"&gt; &lt;heading&gt;
                    &lt;title&gt;Medical diagrams&lt;/title&gt; &lt;/heading&gt;
                    &lt;seclaw:bodytext/&gt; &lt;/seclaw:level&gt; </codeblock>
            </example>
            <section>
                <title>Changes</title>
                <p>2014-04-17: <ph id="change_20140417_JCG">Source
                            <sourcexml>docinfo:selector</sourcexml> content value changed in
                        redelivered data to "SmartForm" to indicate a
                            <targetxml>seclaw:level[@leveltype="form"]</targetxml> should be used.
                        The old value was "digest-form-placeholder". (Responds to issue #1321 on
                        R4.5 post-initial launch issue list for UK15ds.)</ph></p>
                <p>2013-07-14: <ph id="change_20130714_DSF">Added directions and example for the
                        scenario when note[@notetype="xref"] is a child of p.</ph></p>
                <p>2013-05-31: <ph id="change_20130531_DSF">Added directions and example for the
                        scenario when note[@notetype="xref"] is a descendant of text. (Responds to
                        issue #1389 on R4.5 post-initial launch issue list for UK15cs.)</ph></p>
                <p>2013-10-14: <ph id="change_20131014_jm">Added rule for setting
                            <targetxml>seclaw:level[@leveltype]</targetxml> to "form". Previously
                        always set to "unclassified". Supports move of smart-form content from
                        UK11-DA to UK15-DS. Webteam # 240975 and #247307.</ph></p>
            </section>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK15-PracticalGuidance\UK15PG_DIGESTDOC_dig.info.dita  -->
    <!--<xsl:message>UK15PG_DIGESTDOC_dig.info.xsl requires manual development!</xsl:message> -->

    <xsl:template match="dig:info">

        <!--  Original Target XPath:  seclaw:level   -->
      <seclaw:body>
        <seclaw:level leveltype="form">
            <xsl:attribute name="leveltype">
                <xsl:choose>
                    <xsl:when test="parent::dig:body/preceding-sibling::docinfo/child::docinfo:selector='SmartForm'">
                        <xsl:text>form</xsl:text>
                    </xsl:when>
                    <xsl:otherwise>
                        <xsl:text>unclassified</xsl:text>
                    </xsl:otherwise>
                </xsl:choose>
            </xsl:attribute>
            
            <xsl:apply-templates select="following-sibling::level/child::bodytext/child::refpt"/>
            <xsl:apply-templates select="dig:title"/>
            
            <xsl:if test="otherinfo or issue or classification">
                <seclaw:levelinfo>
                    <xsl:apply-templates select="otherinfo"/>
                    <xsl:apply-templates select="issue"/>
                    <xsl:apply-templates select="classification[child::classitem[@classscheme!='topic:topicReference']]"/>   
                </seclaw:levelinfo>
            </xsl:if>
                    <xsl:apply-templates select="catchwordgrp"/>
                    <xsl:apply-templates select ="following-sibling::abstract"/>
           
           
            <seclaw:bodytext> 
                <xsl:apply-templates select="following-sibling::level"/>
            </seclaw:bodytext>
            
        </seclaw:level>
      </seclaw:body>
    </xsl:template>

    
    <xsl:template match="refpt" priority="35">
      
            <!--  Original Target XPath:  ref:anchor   -->
            <ref:anchor>
                <xsl:apply-templates select="@* | node()"/>
            </ref:anchor>
            
    </xsl:template>
    <xsl:template match="refpt/@type" priority="35">
       <!-- suppressed-->
    </xsl:template>
    
    
</xsl:stylesheet>
