<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:frm="http://www.lexis-nexis.com/glp/frm" xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/" version="2.0" exclude-result-prefixes="dita frm">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK14_Precedents_alt-opt-elements">
  <title>frm:alternate, frm:optional <lnpid>id-UK14-30225</lnpid></title>
  <body>
    <note>This instruction has two components. Conversion of the source elements and generation of
      container for each direct child.</note>
    <p><sourcexml>frm:alternate[@id]</sourcexml> becomes
        <targetxml>form:alternatecontent[@xml:id]</targetxml>.</p>
    <p><sourcexml>frm:optional[@id]</sourcexml> becomes
        <targetxml>form:optionalcontent[@xml:id]</targetxml>.</p>
    <p><b><u>And also</u></b> generate container for each direct child. Generate
        <targetxml>form:div[@divtype="direct-child"]/form:bodytext</targetxml>. The child elements
      convert as described elsewhere in these Conversion Instructions.</p>
    <p>For example: Source <sourcexml>frm:alternate</sourcexml> contains child
        <sourcexml>clause</sourcexml> and child <sourcexml>p</sourcexml>. Target
        <targetxml>form:alternatecontent</targetxml> will contain child
        <targetxml>form:div[@divtype="direct-child"]/form:bodytext/form:clause</targetxml> and child
        <targetxml>form:div[@divtype="direct-child"]/form:bodytext/form:p</targetxml>.</p>

    <pre>
        <b>EXAMPLE</b>
            
<b><i>Source XML</i></b>

&lt;frm:alternate id="alt-1234"&gt;
   &lt;clause&gt;
      &lt;p&gt;
         &lt;text&gt;Go into a part of a restricted zone of an aerodrome ...&lt;/text&gt;
      &lt;/p&gt;
      &lt;p&gt;
         &lt;text&gt;Go onto a part of a restricted zone of an air navigation ...&lt;/text&gt;
      &lt;/p&gt;
   &lt;/clause&gt;
   &lt;p&gt;
      &lt;text&gt;Enter any area designated as ...&lt;/text&gt;
   &lt;/p&gt;
&lt;/frm:alternate&gt;

&lt;frm:optional id="opt-9876"&gt;
   &lt;clause&gt;
      &lt;p&gt;
         &lt;text&gt;Having been granted permission to ...&lt;/text&gt;
      &lt;/p&gt;
   &lt;/clause&gt;
&lt;/frm:optional&gt;
 
<b><i>Target XML</i></b>

&lt;form:alternatecontent xml:id="alt-1234"&gt;
  &lt;form:div divtype="direct-child"&gt;
    &lt;form:bodytext&gt;
      &lt;form:clause&gt;
        &lt;form:bodytext&gt;
          &lt;form:p&gt;
             &lt;form:text&gt;Go into a part of a restricted zone of an aerodrome ...&lt;/form:text&gt;
          &lt;/form:p&gt;
          &lt;form:p&gt;
             &lt;form:text&gt;Go onto a part of a restricted zone of an air navigation ...&lt;/form:text&gt;
          &lt;/form:p&gt;
        &lt;/form:bodytext&gt;
      &lt;/form:clause&gt;
    &lt;/form:bodytext&gt;
  &lt;/form:div&gt;
  &lt;form:div divtype="direct-child"&gt;
    &lt;form:bodytext&gt;
      &lt;form:p&gt;
         &lt;form:text&gt;Enter any area designated as ...&lt;/form:text&gt;
      &lt;/form:p&gt;
    &lt;/form:bodytext&gt;
  &lt;/form:div&gt;
&lt;/form:alternatecontent&gt;

&lt;form:optionalcontent xml:id="opt-9876"&gt;
  &lt;form:div divtype="direct-child"&gt;
    &lt;form:bodytext&gt;
      &lt;form:clause&gt;
        &lt;form:bodytext&gt;
          &lt;form:p&gt;
             &lt;form:text&gt;Having been granted permission to ...&lt;/form:text&gt;
          &lt;/form:p&gt;
        &lt;/form:bodytext&gt;
      &lt;/form:clause&gt;
    &lt;/form:bodytext&gt;
  &lt;/form:div&gt;
&lt;/form:optionalcontent&gt;

                </pre>
    <section>
      <title>Changes</title>
      <p>2016-10-05: <ph id="change_20161005_jm">Added rule. Generate form:div container for each
          direct child within alternate and optional markup. New Xpaths. The consistent child
          container supports special features associated with alternate and optional
        material.</ph></p>
      <p>2016-03-27: <ph id="change_20160327_jm">New section. New xpaths.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK14-Precedents\UK14_Precedents_alt-opt-elements.dita  -->
	<!--<xsl:message>UK14_Precedents_alt-opt-elements.xsl requires manual development!</xsl:message>--> 


	<xsl:template match="frm:optional[@id]">

		<!--  Original Target XPath:  form:optionalcontent[@xml:id]   -->
		<form:optionalcontent>
		  <xsl:apply-templates select="@*"/>
		  <xsl:for-each select="*">
		    <form:div divtype="direct-child">
		      <form:bodytext>
			      <xsl:apply-templates select="."/>
		      </form:bodytext>
		    </form:div>
		  </xsl:for-each>
		</form:optionalcontent>

	</xsl:template>
  
  <xsl:template match="frm:optional/@id">
    <xsl:attribute name="xml:id">
      <xsl:value-of select="."/>
    </xsl:attribute>
  </xsl:template>

	<xsl:template match="frm:alternate">

		<!--  Original Target XPath:  form:alternatecontent   -->
		<form:alternatecontent>
		  <xsl:apply-templates select="@*"/>
		  <xsl:for-each select="*">
		    <form:div divtype="direct-child">
		      <form:bodytext>
			<xsl:apply-templates select="."/>
		      </form:bodytext>
		    </form:div>
		  </xsl:for-each>
		</form:alternatecontent>

	</xsl:template>

<!--	<xsl:template match="clause">

		<!-\-  Original Target XPath:  form:alternatecontent   -\->
		<form:alternatecontent>
			<xsl:apply-templates select="@* | node()"/>
		</form:alternatecontent>

	</xsl:template>-->

<!--	<xsl:template match="p">

		<!-\-  Original Target XPath:  form:alternatecontent   -\->
		<form:alternatecontent>
			<xsl:apply-templates select="@* | node()"/>
		</form:alternatecontent>

	</xsl:template>-->

</xsl:stylesheet>