<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Compcase-change-log">
    <title>Change Log for Standard Courtcase</title>
    <body>
        <section>
            <title>Courtcase 9.8 PROD </title>
            <p>2014-07-31
                <ul>
                    <li>
                        <xref href="../../../Rosetta/DITA-Standard/courtcase/case.libnum-refnum-refnumscheme.dita">2014-07-31 - case:libnum id-ST01-26207: Modified AU-specific instruction to generic instruction.</xref>
                    </li>
                    <li>
                        <xref href="../../../Rosetta/DITA-Standard/courtcase/case.decisionsummary-casesum.decisionsummary.dita">2014-07-31 - case:decisionsummary id-ST01-26227: Modified NZ-specific note to generic instructions.</xref>
                    </li>
                    <li>
                        <xref href="../../../Rosetta/common_newest/Rosetta_leg.num_ln.user-displayed-LxAdv-classify.classification.dita">2014-07-30 - leg:num[@ln.user-displayed="false"] to classify:classification: Added a note for handling "solsak"
                            scenario means it should be placed above the first
                            <targetxml>legisinfo:officialtitle</targetxml> instead of the last element
                            in the <targetxml>*:head</targetxml> section</xref>
                    </li>   
                </ul>       
            </p>
        </section>
        <section>
            <title>Courtcase 9.8 PROD </title>
            <p>2014-07-29
                <ul>
                    <li>
                        <xref href="../../../Rosetta/DITA-Standard/courtcase/case.info_abbrvname-caseinfo.shortcasename.dita">2014-07-25 - case:info//abbrvname id-ST01-26214: Modified instructions.</xref>
                    </li>
                    <li>
                        <xref href="../../../Rosetta/common_caselaw/Rosetta_case.references-LxAdv_ref.relatedrefs.dita">2014-07-24 - case:references id-CCCC-12019: Added  "LEGISLATION:" to table with @referencetype legislation. R4.5 DB Item #1278.</xref>
                    </li>
                </ul>   
            </p>
        </section>
        <section>
            <title>Courtcase 9.8 PROD </title>
            <p>2014-07-21 - Created 
               
            </p>
      </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\courtcase\Change-Log.dita  -->
	<xsl:message>courtcase_Change-Log.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>