<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="citator-change-log">
   <title>Change Log for Citator</title>
   <body>
      <section>
         <title>Citator 1.17_PROD</title>
         <p>2016-08-18: Created</p>
      </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-IN\IN04-Citator\change-log.dita  -->
	<xsl:message>IN04-Citator_change-log.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>