<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="dictionary-change-log">
   <title>Change Log for Dictionary</title>
   <body>
      <section>
         <title>Dictionary 2.5 PROD</title>
         <p>2016-07-06: <ph id="change_20160706_RS">First Draft Created.</ph></p>         
      </section>
     
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-IN\IN07-Dictionary\change-log.dita  -->
	<xsl:message>IN07-Dictionary_change-log.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>