<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="MX03_Statcode-change-log">
  <title>MX03 Statcode - Change Log</title>
  <body>
    <section>
      <p>2014-11-18
      <ul>
        <li>
          <xref href="../../../Rosetta/DITA-GPL/MX03-Statcode/leg.officialname.dita">2014-11-18 - leg:officialname id-MX03-34217: Added a note to prepend <sourcexml>leg:officialname/@display-name</sourcexml> in target <targetxml>legisinfo:officialtitle</targetxml>  
          </xref>
        </li>
        <li>
          <xref href="../../../Rosetta/common_newest/Rosetta_figure-LxAdv-figure.dita">2014-10-28 - figure to figure id-CCCC-10320: Moved instruction regarding the XPath XPath <sourcexml>caption/note</sourcexml> into a separate topic. Not a rule change, just a minor reorganization of the instructions.</xref>
        </li>
        <li>
          <xref href="../../../Rosetta/common_newest/Rosetta_figure-LxAdv-figure.dita">2014-10-24 - figure to figure id-CCCC-10320: Added instructions and example to handle the new XPath <sourcexml>caption/note</sourcexml>. (R4.5 Content Issue List #1993)</xref>
        </li>
      </ul>
      </p>
    </section>
    <section>
      <title>2014-10-13 (Statutory Code Schema - 4.1_PROD)</title>
      <ul>
        <li><p>First Release.</p></li>
        </ul>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\MX03-Statcode\MX03_Statcode-change-log.dita  -->
	<xsl:message>MX03_Statcode-change-log.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>