<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:comm="http://www.lexis-nexis.com/glp/comm" xmlns:admindoc="urn:x-lexisnexis:content:administrative-document:sharedservices:1" version="2.0" exclude-result-prefixes="dita comm">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="AU19_CA_ASX_Body">
 <title>Body <lnpid>id-AU19CA-21607</lnpid></title>
 <shortdesc>All of the following are descendants of <targetxml>comm:body</targetxml>. Handle in
  document order unless specifically stated otherwise. Refer to General Markup Section for handling
  of children (including mixed content).</shortdesc>
 <body>
  <section>
   <title>comm:body</title>
   <p><sourcexml>comm:body</sourcexml> becomes <targetxml>admindoc:body</targetxml> and children as
    described below: <note>Highlighted below are some of the major xpaths you may incur. However
     please reference the common general markup elements on the handling of other element not
     specifically outlined in this section. </note>
   </p>
  </section>
 </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU19CA_ASX\AU19_CA_ASX_Body.dita  -->
	<!--<xsl:message>AU19_CA_ASX_Body.xsl requires manual development!</xsl:message> -->

	<xsl:template match="comm:body">

		<!--  Original Target XPath:  admindoc:body   -->
		<admindoc:body>
			<xsl:apply-templates select="@* | node()"/>
		</admindoc:body>

	</xsl:template>

</xsl:stylesheet>