<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:comm="http://www.lexis-nexis.com/glp/comm" xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0" exclude-result-prefixes="dita comm">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK14_Precedents_comm.body">
    <title>comm:body <lnpid>id-UK14-30208</lnpid></title>
    <shortdesc>This section describes <sourcexml>comm:body</sourcexml> and its descendants. Handle
        in document order unless specifically stated otherwise. Refer to General Markup Section for
        handling of children (including mixed content).</shortdesc>
    <body>
        <section>
            <title>comm:body</title>
            <p><sourcexml>comm:body</sourcexml> becomes
            <targetxml>seclaw:body</targetxml>.</p></section>
        <pre>
        <b>EXAMPLE</b>
            
<b><i>Source XML</i></b>

&lt;COMMENTARYDOC&gt;
  &lt;comm:body&gt;...&lt;/comm:body&gt;
&lt;/COMMENTARYDOC&gt;
 
<b><i>Target XML</i></b>

&lt;seclaw:seclaw&gt;
  &lt;seclaw:body&gt;...&lt;/seclaw:body&gt;
&lt;/seclaw:seclaw&gt;

                </pre>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK14-Precedents\UK14_Precedents_comm.body.dita  -->
	<!--<xsl:message>UK14_Precedents_comm.body.xsl requires manual development!</xsl:message> -->

	<xsl:template match="comm:body">

		<!--  Original Target XPath:  seclaw:body   -->
		
			<xsl:apply-templates select="@* | node()"/>
		

	</xsl:template>

</xsl:stylesheet>