<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    xmlns:comm="http://www.lexis-nexis.com/glp/comm"
    xmlns:pubfm="http://www.lexisnexis.com/xmlschemas/content/shared/publication-front-matter/1/"
    xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0"
    exclude-result-prefixes="dita comm">

    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
        id="UK15PG_COMMENTARYDOC_comm.info">
        <title>comm:info <lnpid>id-UK15-30412</lnpid></title>

        <body>
            <p><sourcexml>comm:info</sourcexml> becomes
                    <targetxml>seclaw:body/pubfm:pubfm</targetxml> with the value of
                    <targetxml>pubfm:pubfm/@pubfmtype</targetxml> set to "contributor".</p>
            <example>
                <title>Source XML</title>
                <codeblock> &lt;comm:info&gt; &lt;contrib contribtype="author"&gt; Produced in
                    partnership with &lt;org&gt;&lt;remotelink hrefclass="http"
                    href="lexislegalintelligence.co.uk/lexispsl/tax-experts" newwindow="YES"&gt;Anne
                    Fairpo of Atlas Chambers&lt;/remotelink&gt;&lt;/org&gt;&lt;/contrib&gt;
                    &lt;/comm:info&gt; </codeblock>
                <title>Target XML</title>
                <codeblock> &lt;seclaw:body&gt; &lt;pubfm:pubfm pubfmtype="contributor"&gt;
                    &lt;byline&gt; Produced in partnership with &lt;ref:lnlink service="URL"&gt;
                    &lt;ref:marker&gt;Anne Fairpo of Atlas Chambers&lt;/ref:marker&gt;
                    &lt;ref:locator&gt; &lt;ref:locator-key&gt; &lt;ref:key-name name="URL"/&gt;
                    &lt;ref:key-value
                    value="http://lexislegalintelligence.co.uk/lexispsl/tax-experts"/&gt;
                    &lt;/ref:locator-key&gt; &lt;/ref:locator&gt; &lt;/ref:lnlink&gt;&lt;/byline&gt;
                    &lt;/pubfm:pubfm&gt; ... &lt;/seclaw:body&gt; </codeblock>
            </example>
        </body>
    </dita:topic>

    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK15-PracticalGuidance\UK15PG_COMMENTARYDOC_comm.info.dita  -->
    <!--	<xsl:message>UK15PG_COMMENTARYDOC_comm.info.xsl requires manual development!</xsl:message> -->

    <xsl:template match="comm:info">
        <!--<seclaw:body>

            <xsl:apply-templates select="@* | node()"/>

        </seclaw:body>-->
        <pubfm:pubfm>
            <xsl:attribute name="pubfmtype">contributor</xsl:attribute>
        <xsl:apply-templates select="@* | node()"/>
        </pubfm:pubfm>
    </xsl:template>

</xsl:stylesheet>
