<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Introduction">
  <title>Introduction <lnpid>id-AR01-34408</lnpid></title>
  <shortdesc>This Conversion Instructions describes the conversion of the Rosetta LEGDOC DTD to
      <b>Legislation Schema Version 9.1 PROD</b>.</shortdesc>
  <body>
    
    <p>Argentina Legislation samples are identified using the root element <sourcexml>LEGDOC</sourcexml>
      along with attribute <sourcexml>@legtype</sourcexml> which contains value
        <sourcexml>act</sourcexml> and <sourcexml>docinfo:selector</sourcexml> markup having value <sourcexml>legislation</sourcexml>.</p>

    <section> Root element <sourcexml>LEGDOC</sourcexml> becomes <targetxml>legis:legis</targetxml>
      which is the root element of Legislation Schema. The source attribute
        <sourcexml>@xml:lang</sourcexml>, if present, can be dropped, as a separate rule has been
      defined to populate <targetxml>legis:legis/@xml:lang</targetxml>.</section>
    <section>
      <note>The attribute <sourcexml>@searchtype</sourcexml> will be suppressed from the conversion except citation markup.</note>
      <pre>

&lt;LEGDOC&gt;
  ...
  &lt;docinfo:doc-lang lang="es"/&gt;
  &lt;docinfo:doc-country iso-cc="AR"/&gt;
  ...          
&lt;/LEGDOC&gt;


          <b>Becomes</b>


&lt;legis:legis xml:lang="es-AR"&gt;
  ...
&lt;/legis:legis&gt;

      </pre>
      
      <note>Elements <targetxml>legis:head</targetxml>, <targetxml>legis:body</targetxml> and
          <targetxml>doc:metadata</targetxml> are created as required children of root element
          <targetxml>legis:legis</targetxml> during conversion.</note>
      <p><b>Note:</b></p>
      <p>Source elements and attributes are highlighted like this:
        <sourcexml>SOURCEXML</sourcexml></p>
      <p>Target elements and attributes are highlighted like this:
        <targetxml>TARGETXML</targetxml></p>
      <p>Copy source attributes to target attributes unless otherwise specified.</p>
      <p>Every example is represented like EXAMPLE in all the Conversion Instructions
        and is captured under <pre>pre</pre> tag.</p>
    </section>
  </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\AR01-Legislation\Introduction.dita  -->
	<xsl:message>AR01-Legislation_Introduction.xsl requires manual development!</xsl:message> 

	<xsl:template match="LEGDOC">

		<!--  Original Target XPath:  legis:legis   -->
		<legis:legis>
			<xsl:apply-templates select="@* | node()"/>
		</legis:legis>

	</xsl:template>

	<xsl:template match="@legtype">

		<!--  Original Target XPath:  legis:legis   -->
		<legis:legis>
			<xsl:apply-templates select="@* | node()"/>
		</legis:legis>

	</xsl:template>

	<xsl:template match="act">

		<!--  Original Target XPath:  legis:legis   -->
		<legis:legis>
			<xsl:apply-templates select="@* | node()"/>
		</legis:legis>

	</xsl:template>

	<xsl:template match="docinfo:selector">

		<!--  Original Target XPath:  legis:legis   -->
		<legis:legis>
			<xsl:apply-templates select="@* | node()"/>
		</legis:legis>

	</xsl:template>

	<xsl:template match="legislation">

		<!--  Original Target XPath:  legis:legis   -->
		<legis:legis>
			<xsl:apply-templates select="@* | node()"/>
		</legis:legis>

	</xsl:template>

	<xsl:template match="@xml:lang">

		<!--  Original Target XPath:  legis:legis/@xml:lang   -->
		<legis:legis>
			<xsl:attribute name="xml:lang">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</legis:legis>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:  legis:head   -->
		<legis:head>
			<xsl:apply-templates select="@* | node()"/>
		</legis:head>

	</xsl:template>

	<xsl:template match="SOURCEXML">

		<!--  Original Target XPath:  TARGETXML   -->
		<TARGETXML>
			<xsl:apply-templates select="@* | node()"/>
		</TARGETXML>

	</xsl:template>

</xsl:stylesheet>