<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.juris">
    <title>leg:juris <lnpid>id-AR02-35015</lnpid></title>
    <body>
        <section>
            <p>When <sourcexml>leg:juris</sourcexml> become
                    <targetxml>legis:head/jurisinfo:legisbodyinfo/jurisinfo:jurisdiction/jurisinfo:system</targetxml>
                and create <targetxml>dc:metadata/dc:coverage/location:country</targetxml> with
                attributes <targetxml>@codescheme="ISO-3166-1"</targetxml> and value of
                    <sourcexml>leg:juris</sourcexml> also becomes
                    <targetxml>@countrycode</targetxml> attribute value.</p>
            <pre>
&lt;leg:juris ln.user-displayed="false"&gt;AR&lt;/leg:juris&gt;
              
<b>Becomes</b>
              
&lt;jurisinfo:legisbodyinfo&gt;
    &lt;jurisinfo:jurisdiction&gt;
        &lt;jurisinfo:system&gt;AR&lt;/jurisinfo:system&gt;
    &lt;/jurisinfo:jurisdiction&gt;
&lt;/jurisinfo:legisbodyinfo&gt;

&lt;dc:coverage&gt;
    &lt;location:country countrycode="AR" codescheme="ISO-3166-1"/&gt;
&lt;/dc:coverage&gt;             
                  </pre>
        </section>
        <section>Change Log</section>
        <p>2014-12-05: <ph id="change_20141205_PS">Created.</ph></p>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\AR02-Statcode\leg.juris.dita  -->
	<xsl:message>AR02-Statcode_leg.juris.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:juris">

		<!--  Original Target XPath:  legis:head/jurisinfo:legisbodyinfo/jurisinfo:jurisdiction/jurisinfo:system   -->
		<legis:head>
			<jurisinfo:legisbodyinfo xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/">
				<jurisinfo:jurisdiction>
					<jurisinfo:system>
						<xsl:apply-templates select="@* | node()"/>
					</jurisinfo:system>
				</jurisinfo:jurisdiction>
			</jurisinfo:legisbodyinfo>
		</legis:head>

	</xsl:template>

</xsl:stylesheet>