<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:frm="http://www.lexis-nexis.com/glp/frm" 
	xmlns:leg="http://www.lexis-nexis.com/glp/leg"
	xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/"
	xmlns:annot="http://www.lexisnexis.com/xmlschemas/content/shared/annotations/1/"
	xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/"
	xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/"
	xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0"
	exclude-result-prefixes="dita frm leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
		id="AU14_refpt-Chof-heading-LxAdv-ref.anchor">
		<title>
			<sourcexml>refpt</sourcexml> child of <sourcexml>heading</sourcexml> to <targetxml>ref:anchor</targetxml> <lnpid>id-AU14-20628</lnpid>
		</title>
		<body>
			<section>
				<p>If <sourcexml>refpt</sourcexml> occurs under <sourcexml>heading</sourcexml> then
					<targetxml>ref:anchor</targetxml> will move up one level to become the first child of the target version
					of the source element containing the heading.</p>
				<note>All occurrences of <sourcexml>refpt[@type="ext"]</sourcexml> should map to <targetxml>ref:anchor[@anchortype="global"]</targetxml>. If value of <sourcexml>refpt[@type="local"</sourcexml>, or is omitted or any other value the mapping should be <targetxml>ref:anchor[@anchortype="local"]</targetxml>.</note>
			</section>
			<pre>
        <b>EXAMPLE</b>
            
<b><i>Source XML</i></b>
<![CDATA[

<level subdoc="true" toc-caption="[1633]  Crimes Legislation Further Amendment Act 2003 No 85">
<heading>
    <edpnum>[1633] </edpnum>
    <title>
        <ci:cite searchtype="LEG-REF"><ci:content>
            <citefragment searchtype="LEG-NAME-REF">Crimes Legislation Further Amendment Act 2003 No 85</citefragment></ci:content>
        </ci:cite>
    </title>
    <refpt id="CLN.1633" type="ext">
    </refpt>
</heading>
........
........
</level>
]]> 

<b><i>Target XML</i></b>
<![CDATA[

<section includeintoc="true" alternatetoccaption="[1633]  Crimes Legislation Further Amendment Act 2003 No 85">
   <ref:anchor id="_CLN_1633" anchortype="global"/>
   <heading>
    <desig>[1633] </desig>
    <title>
        <lnci:cite type="legislation">
            <lnci:content>Crimes Legislation Further Amendment Act 2003 No 85</lnci:content>
        </lnci:cite>
    </title>
</heading>
    
.........
.........
</section>
]]> 

   </pre>
			
			<section>
				<title>Changes</title>
				<p>2017-02-20: <ph id="change_20170220_RS">Created.</ph></p>
			</section>
		</body>	
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC/AU14_Journal-Newsletter-Bulletins/refpt-Chof-heading-LxAdv-ref.anchor.dita  -->
	<xsl:message>AU14_refpt-Chof-heading-LxAdv-ref.anchor.xsl requires manual development!</xsl:message> 
	

	
	


	

</xsl:stylesheet>
