<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:cttr="urn:x-lexisnexis:content:citator:sharedservices:1" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Citator_Head">
  <title>Citator - Head <lnpid>id-AU20-22214</lnpid></title>
  <body>
    <p>
      <b>The following conversion instruction is specific to AU Citator:</b>
      <ul>
        <li>
          <sourcexml>case:info</sourcexml> becomes <targetxml>cttr:citeddecision/cttr:caseinfo</targetxml> and the children are
        described below : 
        </li>
      </ul>
    </p>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU20_Legislative_Citator\Citator_Head.dita  -->
	<xsl:message>AU20_Legislative_Citator_Citator_Head.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:info">

		<!--  Original Target XPath:  cttr:citeddecision/cttr:caseinfo   -->
		<cttr:citeddecision>
			<cttr:caseinfo>
				<xsl:apply-templates select="@* | node()"/>
			</cttr:caseinfo>
		</cttr:citeddecision>

	</xsl:template>

</xsl:stylesheet>