<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.judgment">
   <title>case:judgment <lnpid>id-CA02CC-12423</lnpid></title>
   <body>
      <section>
          <ul>
         <li class="- topic/li ">
                    <sourcexml class="+ topic/keyword xml-d/sourcexml ">case:judgment</sourcexml>
                    becomes <targetxml class="+ topic/keyword xml-d/targetxml ">courtcase:opinions/courtcase:opinion</targetxml>.
                    <pre xml:space="preserve" class="- topic/pre "> 
&lt;case:judgments&gt;
    &lt;case:judgment&gt;
        &lt;case:judgmentbody&gt;
            &lt;p i="2" indent="1st-line"&gt;
                            &lt;text&gt;Accused was originally charged with driving over 80, contrary to
                                s. 236 of the Criminal Code, and had been served with a certificate
                                of analysis and notice of intention to produce the certificate.
                                Subsequently, the Crown had laid a new information alleging care and
                                control rather than driving. Certificate and notice had not been
                                re-served. Accused had been acquitted by Provincial Court judge on
                                the basis that the certificate was inadmissible because of the
                                manner in which the solution used was described. On a trial de novo,
                                Q.B. judge had ruled that description of the solution was adequate
                                and had rejected accused's argument that he should be acquitted
                                because original certificate and notice had not been re-served.
                                Section 237(5) of the Code provided that no certificate was to be
                                received pursuant to paragraphs (1) (d), (e) or (f) unless before
                                trial the Crown had given reasonable notice of its intention to
                                produce it.&lt;/text&gt;
                        &lt;/p&gt;
        &lt;/case:judgmentbody&gt;
    &lt;/case:judgment&gt;
&lt;/case:judgments&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;courtcase:opinions&gt;
    &lt;courtcase:opinion&gt;
        &lt;bodytext&gt;
            &lt;p indent="1st-line"&gt;
                            &lt;text&gt;Accused was originally charged with driving over 80, contrary to
                                s. 236 of the Criminal Code, and had been served with a certificate
                                of analysis and notice of intention to produce the certificate.
                                Subsequently, the Crown had laid a new information alleging care and
                                control rather than driving. Certificate and notice had not been
                                re-served. Accused had been acquitted by Provincial Court judge on
                                the basis that the certificate was inadmissible because of the
                                manner in which the solution used was described. On a trial de novo,
                                Q.B. judge had ruled that description of the solution was adequate
                                and had rejected accused's argument that he should be acquitted
                                because original certificate and notice had not been re-served.
                                Section 237(5) of the Code provided that no certificate was to be
                                received pursuant to paragraphs (1) (d), (e) or (f) unless before
                                trial the Crown had given reasonable notice of its intention to
                                produce it.&lt;/text&gt;
                        &lt;/p&gt;
        &lt;/bodytext&gt;
    &lt;/courtcase:opinion&gt;
&lt;/courtcase:opinions&gt;</pre>
                </li>
          </ul>
      </section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA02-Case_Summaries\CA02CC_CASEDOC\case.judgment.dita  -->
	<xsl:message>CA02CC_CASEDOC_case.judgment.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:judgment">

		<!--  Original Target XPath:  courtcase:opinions/courtcase:opinion   -->
		<courtcase:opinions>
			<courtcase:opinion>
				<xsl:apply-templates select="@* | node()"/>
			</courtcase:opinion>
		</courtcase:opinions>

	</xsl:template>

</xsl:stylesheet>