<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="refnum">
   <title> refnum <lnpid>id-CA02DC-12640</lnpid>   </title>
   <body>
      <section>
         <p><sourcexml>refnum</sourcexml> becomes <targetxml>caseinfo:caseinfo/jurisinfo:courtinfo/refnum</targetxml>.</p>
         <p>The content of <sourcexml>refnum</sourcexml> should become the content of <targetxml>refnum</targetxml>, unless
               <sourcexml>@ln.user-displayed="false"</sourcexml> is present in <sourcexml>refnum</sourcexml>.</p>
         <p>The attributes of <targetxml>refnum</targetxml> are populated as follows:<ul>
               <li><sourcexml>refnum/@refnumtype</sourcexml> becomes <targetxml>refnum/@refnumscheme</targetxml>.</li>
               <li>The content of <sourcexml>refnum</sourcexml> is placed in <targetxml>refnum/@num</targetxml>
                  <i>regardless</i> of the value of <sourcexml>@ln.user-displayed</sourcexml> in the source. .</li>
            </ul></p>
      </section>
      <example>
         <title>Mapping of <sourcexml>refnum</sourcexml> with <sourcexml>@ln.user-displayed="false"</sourcexml></title>
         <codeblock>

&lt;refnum refnumtype="UCN" ln.user-displayed="false"&gt;00770463&lt;/refnum&gt;

           </codeblock>
         <b>becomes</b>
         <codeblock>

&lt;jurisinfo:courtinfo&gt;
   &lt;refnum refnumscheme="UCN" num="00770463"/&gt;
&lt;/jurisinfo:courtinfo&gt;

           </codeblock>
      </example>
      <example>
         <title>Mapping of <sourcexml>refnum</sourcexml> with <sourcexml>@ln.user-displayed="true"</sourcexml></title>
         <codeblock>

&lt;refnum refnumtype="UCN" ln.user-displayed="true"&gt;00770463&lt;/refnum&gt;

           </codeblock>
         <b>becomes</b>
         <codeblock>

&lt;jurisinfo:courtinfo&gt;
   &lt;refnum refnumscheme="UCN" num="00770463"&gt;00770463&lt;/refnum
&lt;/jurisinfo:courtinfo&gt;

           </codeblock>
      </example>
      <example>
         <title>Mapping of <sourcexml>refnum</sourcexml> without <sourcexml>@ln.user-displayed</sourcexml></title>
         <codeblock>

&lt;refnum refnumtype="UCN"&gt;00770463&lt;/refnum&gt;

           </codeblock>
         <b>becomes</b>
         <codeblock>

&lt;jurisinfo:courtinfo&gt;
   &lt;refnum refnumscheme="UCN" num="00770463"&gt;00770463&lt;/refnum
&lt;/jurisinfo:courtinfo&gt;

           </codeblock>
      </example>
      <section><p>2014-05-09<ph id="change_20140509_AS">UCN suggested mapping added for refnum... DB #192</ph></p></section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA02-Case_Summaries\CA02DC_DIGESTDOC_to_casedigest\refnum.dita  -->
	<xsl:message>CA02DC_DIGESTDOC_to_casedigest_refnum.xsl requires manual development!</xsl:message> 

	<xsl:template match="refnum">

		<!--  Original Target XPath:  caseinfo:caseinfo/jurisinfo:courtinfo/refnum   -->
		<caseinfo:caseinfo>
			<jurisinfo:courtinfo xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/">
				<refnum>
					<xsl:apply-templates select="@* | node()"/>
				</refnum>
			</jurisinfo:courtinfo>
		</caseinfo:caseinfo>

	</xsl:template>

	<xsl:template match="@ln.user-displayed=&#34;false&#34;">

		<!--  Original Target XPath:  refnum   -->
		<refnum>
			<xsl:apply-templates select="@* | node()"/>
		</refnum>

	</xsl:template>

	<xsl:template match="refnum/@refnumtype">

		<!--  Original Target XPath:  refnum/@refnumscheme   -->
		<refnum>
			<xsl:attribute name="refnumscheme">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</refnum>

	</xsl:template>

	<xsl:template match="@ln.user-displayed">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="@ln.user-displayed=&#34;true&#34;">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>