<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0"
  exclude-result-prefixes="#all">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Namespaces">
    <title>Namespaces <lnpid>id-CA09-14411</lnpid></title>
    <body>
      <ul>
        <li>xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"</li>
        <li>xmlns:admincode="http://www.lexisnexis.com/xmlschemas/content/legal/administrative-code/1/"</li>
        <li>xmlns:annot="http://www.lexisnexis.com/xmlschemas/content/shared/annotations/1/"</li>
        <li>xmlns:annotinfo="http://www.lexisnexis.com/xmlschemas/content/shared/annotations-info/1/"</li>
        <li>xmlns:base="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"</li>
        <li>xmlns:classify="http://www.lexisnexis.com/xmlschemas/content/shared/classification/1/"</li>
        <li>xmlns:contact="http://www.lexisnexis.com/xmlschemas/content/shared/contact/1/"</li>
        <li>xmlns:core="http://www.lexisnexis.com/namespace/sslrp/core"</li>
        <li>xmlns:courtrule="http://www.lexisnexis.com/xmlschemas/content/legal/courtrule/1/"</li>
        <li>xmlns:datetime="http://exslt.org/dates-and-times"</li>
        <li>xmlns:dc="http://purl.org/dc/elements/1.1/"</li>
        <li>xmlns:dcterms="http://purl.org/dc/terms/"</li>
        <li>xmlns:di="http://www.lexisnexis.com/namespace/sslrp/di"</li>
        <li>xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"</li>
        <li>xmlns:em="http://www.lexisnexis.com/namespace/sslrp/em"</li>
        <li>xmlns:fm="http://www.lexisnexis.com/namespace/sslrp/fm"</li>
        <li>xmlns:fn="http://www.lexisnexis.com/namespace/sslrp/fn"</li>
        <li>xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/"</li>
        <li>xmlns:glph="http://www.lexisnexis.com/namespace/sslrp/glph"</li>
        <li>xmlns:in="http://www.lexisnexis.com/namespace/sslrp/in"</li>
        <li>xmlns:index="urn:x-lexisnexis:content:publicationindex:sharedservices:1"</li>
        <li>xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/"</li>
        <li>xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/"</li>
        <li>xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/"</li>
        <li>xmlns:lnci="http://www.lexisnexis.com/xmlschemas/content/shared/citations/1/"</li>
        <li>xmlns:lndocmeta="http://www.lexisnexis.com/xmlschemas/content/shared/lndocmeta/1/"</li>
        <li>xmlns:lnmeta="http://www.lexisnexis.com/xmlschemas/content/shared/lexisnexis-metadata/1/"</li>
        <li>xmlns:location="http://www.lexisnexis.com/xmlschemas/content/shared/location/1/"</li>
        <li>xmlns:notOutregister="http://www.lexisnexis.com/xmlschemas/content/legal/notOutregister/1/"</li>
        <li>xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/"</li>
        <li>xmlns:pnfo="http://www.lexisnexis.com/namespace/sslrp/pnfo"</li>
        <li>xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/"</li>
        <li>xmlns:primlawhist="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-history/1/"</li>
        <li>xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/"</li>
        <li>xmlns:proc="http://www.lexisnexis.com/xmlschemas/content/shared/process-elements/1/"</li>
        <li>xmlns:ps="http://www.lexisnexis.com/namespace/sslrp/ps"</li>
        <li>xmlns:pu="http://www.lexisnexis.com/namespace/sslrp/pu"</li>
        <li>xmlns:pubfm="http://www.lexisnexis.com/xmlschemas/content/shared/publication-front-matter/1/"</li>
        <li>xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/"</li>
        <li>xmlns:pubup="http://www.lexisnexis.com/xmlschemas/content/shared/publication-update/1/"</li>
        <li>xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"</li>
        <li>xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/"</li>
        <li>xmlns:register="http://www.lexisnexis.com/xmlschemas/content/legal/register/1/"</li>
        <li>xmlns:registerinfo="http://www.lexisnexis.com/xmlschemas/content/legal/register-info/1/"</li>
        <li>xmlns:se="http://www.lexisnexis.com/namespace/sslrp/se"</li>
        <li>xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/"</li>
        <li>xmlns:statcode="http://www.lexisnexis.com/xmlschemas/content/legal/statutorycode/1/"</li>
        <li>xmlns:tr="http://www.lexisnexis.com/namespace/sslrp/tr"</li>
        <li>xmlns:xs="http://www.w3.org/2001/XMLSchema"</li>
        <li>xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"</li>
      </ul>
    </body>
  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA09-Precedents_Forms\Namespaces.dita  -->
  <!--<xsl:message>CA09-Precedents_Forms_Namespaces.xsl requires manual development!</xsl:message> -->

  <xsl:variable name="lexisAdvNamespaces" as=" element() ">
    <lexisAdvNamespaces>
      <lexisAdvNamespace>xmlns:tei="http://www.tei-c.org/ns/1.0/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:admincode="http://www.lexisnexis.com/xmlschemas/content/legal/administrative-code/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:annot="http://www.lexisnexis.com/xmlschemas/content/shared/annotations/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:annotinfo="http://www.lexisnexis.com/xmlschemas/content/shared/annotations-info/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:base="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:classify="http://www.lexisnexis.com/xmlschemas/content/shared/classification/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:contact="http://www.lexisnexis.com/xmlschemas/content/shared/contact/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:core="http://www.lexisnexis.com/namespace/sslrp/core"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:courtrule="http://www.lexisnexis.com/xmlschemas/content/legal/courtrule/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:datetime="http://exslt.org/dates-and-times"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:dc="http://purl.org/dc/elements/1.1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:dcterms="http://purl.org/dc/terms/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:di="http://www.lexisnexis.com/namespace/sslrp/di"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:em="http://www.lexisnexis.com/namespace/sslrp/em"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:fm="http://www.lexisnexis.com/namespace/sslrp/fm"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:fn="http://www.lexisnexis.com/namespace/sslrp/fn"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:glph="http://www.lexisnexis.com/namespace/sslrp/glph"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:in="http://www.lexis-nexis.com/glp/in"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:index="urn:x-lexisnexis:content:publicationindex:sharedservices:1"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:legis="http://www.lexisnexis.com/xmlschemas/content/legal/legislation/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:lnci="http://www.lexisnexis.com/xmlschemas/content/shared/citations/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:lndocmeta="http://www.lexisnexis.com/xmlschemas/content/shared/lndocmeta/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:lnmeta="http://www.lexisnexis.com/xmlschemas/content/shared/lexisnexis-metadata/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:location="http://www.lexisnexis.com/xmlschemas/content/shared/location/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:notOutregister="http://www.lexisnexis.com/xmlschemas/content/legal/notOutregister/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:pnfo="http://www.lexisnexis.com/namespace/sslrp/pnfo"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:primlawhist="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-history/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:proc="http://www.lexisnexis.com/xmlschemas/content/shared/process-elements/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:ps="http://www.lexisnexis.com/namespace/sslrp/ps"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:pu="http://www.lexisnexis.com/namespace/sslrp/pu"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:pubfm="http://www.lexisnexis.com/xmlschemas/content/shared/publication-front-matter/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:pubup="http://www.lexisnexis.com/xmlschemas/content/shared/publication-update/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:register="http://www.lexisnexis.com/xmlschemas/content/legal/register/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:registerinfo="http://www.lexisnexis.com/xmlschemas/content/legal/register-info/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:se="http://www.lexisnexis.com/namespace/sslrp/se"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:statcode="http://www.lexisnexis.com/xmlschemas/content/legal/statutorycode/1/"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:tr="http://www.lexisnexis.com/namespace/sslrp/tr"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:xs="http://www.w3.org/2001/XMLSchema"</lexisAdvNamespace>
      <lexisAdvNamespace>xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"</lexisAdvNamespace>
    </lexisAdvNamespaces>
  </xsl:variable>

</xsl:stylesheet>
