<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:abstract="urn:x-lexisnexis:content:abstract:sharedservices:1" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="CaseSummaries_Introduction">
  <title>Introduction <lnpid>id-NZ17CA-25612</lnpid></title>

  <body>
    <p>This Conversion Instruction describes the conversion of Rosetta CITATORDOC DTD to Abstract
      4.1_BETA schema in the document.</p>
        
    <p>Case Summaries documents are identified using the root element <sourcexml>CITATORDOC</sourcexml> with attribute
      <sourcexml>@journalarticle="true"</sourcexml>, the value of <sourcexml>docinfo:hier/docinfo:hierlev/heading/title</sourcexml> should be <b>Articles</b>, 
      <sourcexml>docinfo:doc-country/@iso-cc=”NZ”</sourcexml> and the value of <sourcexml>docinfo:selector</sourcexml> should be <b>Digest</b>.</p>
    
    <p><sourcexml>CITATORDOC[journalarticle="true"]</sourcexml> becomes <targetxml>abstract:abstract</targetxml>. It's a root element for Case Summaries. The source 
      attribute <sourcexml>@citatordoctype</sourcexml> should be suppressed from conversion.
   </p>
    
    <note>The attribute <sourcexml>@searchtype</sourcexml> will be suppressed from the conversion except citation markup.</note>

<pre>

&lt;CITATORDOC citatordoctype="bcl" journalarticle="true" xml:lang="en-NZ"&gt;
        ...
        &lt;docinfo:doc-lang lang="en"/&gt;
        &lt;docinfo:doc-country iso-cc="NZ"/&gt;
        ...
&lt;/CASEDOC&gt;
<b>Becomes</b>

&lt;abstract:abstract xml:lang="en-NZ"&gt;
      
      &lt;abstract:head&gt;...&lt;/abstract:head&gt;

      &lt;abstract:body&gt;...&lt;/abstract:body&gt;

      &lt;doc:metadata&gt;...&lt;/doc:metadata&gt;
      
&lt;/abstract:abstract&gt;
</pre>

    <p><targetxml>abstract:head</targetxml>, <targetxml>abstract:body</targetxml>, and <targetxml>doc:metadata</targetxml> are created as required 
      children of <targetxml>abstract:abstract</targetxml>.</p>

    <section>
      <title>Note:</title>
      <p>Source elements and attributes are highlighted like this: <sourcexml>SOURCEXML</sourcexml></p>
      <p>Target elements and attributes are highlighted like this: <targetxml>TARGETXML</targetxml></p>
      <p>Copy source attributes to target attributes unless otherwise specified.</p>
      <p>Every example is represented like "EXAMPLE" in all the dita's and is captured under <pre>pre</pre>  tag.</p>
    </section>
  </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ17_Case_Summaries\NZ17CA_Citatordoc_To_Abstract\CaseSummaries_Introduction.dita  -->
	<xsl:message>CaseSummaries_Introduction.xsl requires manual development!</xsl:message> 

	<xsl:template match="CITATORDOC">

		<!--  Original Target XPath:  abstract:abstract   -->
		<abstract:abstract>
			<xsl:apply-templates select="@* | node()"/>
		</abstract:abstract>

	</xsl:template>

	<xsl:template match="@journalarticle=&#34;true&#34;">

		<!--  Original Target XPath:  abstract:abstract   -->
		<abstract:abstract>
			<xsl:apply-templates select="@* | node()"/>
		</abstract:abstract>

	</xsl:template>

	<xsl:template match="docinfo:hier/docinfo:hierlev/heading/title">

		<!--  Original Target XPath:  abstract:abstract   -->
		<abstract:abstract>
			<xsl:apply-templates select="@* | node()"/>
		</abstract:abstract>

	</xsl:template>

	<xsl:template match="docinfo:doc-country/@iso-cc=”NZ”">

		<!--  Original Target XPath:  abstract:abstract   -->
		<abstract:abstract>
			<xsl:apply-templates select="@* | node()"/>
		</abstract:abstract>

	</xsl:template>

	<xsl:template match="docinfo:selector">

		<!--  Original Target XPath:  abstract:abstract   -->
		<abstract:abstract>
			<xsl:apply-templates select="@* | node()"/>
		</abstract:abstract>

	</xsl:template>

	<xsl:template match="CITATORDOC[journalarticle=&#34;true&#34;]">

		<!--  Original Target XPath:  abstract:abstract   -->
		<abstract:abstract>
			<xsl:apply-templates select="@* | node()"/>
		</abstract:abstract>

	</xsl:template>

	<xsl:template match="@citatordoctype">

		<!--  Original Target XPath:  abstract:head   -->
		<abstract:head>
			<xsl:apply-templates select="@* | node()"/>
		</abstract:head>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:  abstract:head   -->
		<abstract:head>
			<xsl:apply-templates select="@* | node()"/>
		</abstract:head>

	</xsl:template>

	<xsl:template match="SOURCEXML">

		<!--  Original Target XPath:  TARGETXML   -->
		<TARGETXML>
			<xsl:apply-templates select="@* | node()"/>
		</TARGETXML>

	</xsl:template>

</xsl:stylesheet>