<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:caseinfo="http://www.lexisnexis.com/xmlschemas/content/legal/case-information/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="case.casename">
    <title>casename <lnpid>id-MY10-18009</lnpid></title>
    <body>
        <section>
            <ul>
                <li>
                    <sourcexml>case:casename</sourcexml> becomes
                        <targetxml>caseinfo:casename/caseinfo:fullcasename</targetxml>
                    <ul>
                        <li> Both the tags <sourcexml>emph</sourcexml>, its attributes and
                                <sourcexml>refpt</sourcexml> are omitted. </li>
                    </ul>
                    <pre xml:space="preserve">
&lt;case:casename&gt;
    &lt;emph typestyle="ro"&gt;&lt;refpt id="10957" type="ext"/&gt;&lt;/emph&gt;Queensland Wire Industries Pty
    Ltd v Broken Hill Proprietary Co Ltd
&lt;/case:casename&gt;
<b class="+ topic/ph hi-d/b ">Becomes</b>
    &lt;caseinfo:casename&gt;
        &lt;caseinfo:fullcasename&gt;Queensland Wire Industries Pty Ltd v Broken Hill Proprietary Co Ltd&lt;/caseinfo:fullcasename&gt;
    &lt;/caseinfo:casename&gt;
                
</pre>
                </li>
            </ul>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY10_Citator\casename.dita  -->
	<xsl:message>casename.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:casename">

		<!--  Original Target XPath:  caseinfo:casename/caseinfo:fullcasename   -->
		<caseinfo:casename>
			<caseinfo:fullcasename>
				<xsl:apply-templates select="@* | node()"/>
			</caseinfo:fullcasename>
		</caseinfo:casename>

	</xsl:template>

	<xsl:template match="emph">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="refpt">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>