<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:source_dict="http://www.lexis-nexis.com/glp/dict" xmlns:tei="http://www.tei-c.org/ns/1.0/" version="2.0" exclude-result-prefixes="dita dict">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="dict.topicname">
    <title><sourcexml>dict:topicname</sourcexml> to <targetxml>tei:usg</targetxml> <lnpid>id-UK10-29217</lnpid></title>
    <body>
        <section>
            <p>The element <sourcexml>dict:topicname</sourcexml> becomes
                    <targetxml>tei:usg</targetxml>. Set <targetxml>tei:usg[@type]</targetxml> to the
                text from <sourcexml>dict:topicname</sourcexml> (converted to lower-case with spaces
                removed).</p>
        </section>
        <example>
            <title>Source XML 1</title>
            <codeblock>

&lt;dict:topicname&gt;&lt;emph typestyle="bf"&gt;Definition&lt;/emph&gt;&lt;/dict:topicname&gt;

	</codeblock>
        </example>
        <example>
            <title>Target XML 1</title>
            <codeblock>

&lt;tei:usg type="definition"&gt;&lt;emph typestyle="bf"&gt;Definition&lt;/emph&gt;&lt;/tei:usg&gt;

	</codeblock>
            
        </example>
        <!--<section>
            <title>Changes</title>
            <p>2012-11-01: Created.</p>
        </section>-->
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK10_Dictionary\dict.topicname.dita  -->
	<xsl:message>dict.topicname.xsl requires manual development!</xsl:message> 

	<xsl:template match="dict:topicname"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  tei:usg   -->
		<tei:usg>
			<xsl:apply-templates select="@* | node()"/>
		</tei:usg>

	</xsl:template>

</xsl:stylesheet>