<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:source_dict="http://www.lexis-nexis.com/glp/dict" xmlns:tei="http://www.tei-c.org/ns/1.0/" version="2.0" exclude-result-prefixes="dita dict">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="dict.definition">
    <title><sourcexml>dict:definition</sourcexml> to <targetxml>tei:def</targetxml> <lnpid>id-UK10-29210</lnpid></title>
    <body>
        <section>
            <p><sourcexml>dict:definition</sourcexml> becomes <targetxml>tei:def</targetxml>.</p>
        </section>
        <example>
            <title>Source XML 1</title>
            <codeblock>

&lt;dict:term-entry&gt;
    &lt;defterm&gt;...&lt;/defterm&gt;
    &lt;dict:definition&gt;
        ...
    &lt;/dict:definition&gt;
&lt;/dict:term-entry&gt;

	</codeblock>
        </example>
        <example>
            <title>Target XML 1</title>
            <codeblock>

&lt;dict:defitem&gt;
            &lt;tei:entry&gt;
                &lt;tei:form&gt;
                    &lt;tei:orth&gt;...&lt;/tei:orth&gt;
                &lt;/tei:form&gt;
                &lt;tei:def&gt;
                    ...
                &lt;/tei:def&gt;
            &lt;/tei:entry&gt;
        &lt;/dict:defitem&gt;

	</codeblock>
            
        </example>
        <!--<section>
            <title>Changes</title>
            <p>2012-11-01: Created.</p>
        </section>-->
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK10_Dictionary\dict.definition.dita  -->
	<xsl:message>dict.definition.xsl requires manual development!</xsl:message> 

	<xsl:template match="dict:definition"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  tei:def   -->
		<tei:def>
			<xsl:apply-templates select="@* | node()"/>
		</tei:def>

	</xsl:template>

</xsl:stylesheet>