<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita case docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="doc.docinfo_doc-content-country">
    <title><sourcexml>docinfo:doc-country[@iso-cc]</sourcexml> to
            <targetxml>doc:docinfo[@doc-content-country]</targetxml>
        <lnpid>id-HK08-37625</lnpid></title>
    <body>
        <section>
            <title>Instructions <i>[common element]</i></title>
            <p>Check the value of
                    <sourcexml>case:headnote/case:info/case:courtinfo//case:juris</sourcexml>. If
                    <sourcexml>case:juris="NZ"</sourcexml>, set
                    <targetxml>doc:docinfo[@doc-content-country="NZ"]</targetxml>, otherwise,
                    <sourcexml>docinfo:doc-country[@iso-cc]</sourcexml> becomes
                    <targetxml>doc:docinfo[@doc-content-country]</targetxml>.<note>@doc-content-country
                    is required.</note>
                <note><sourcexml>docinfo:doc-country[@iso-cc]</sourcexml> is used to specify the
                    country in the source document and also becomes part of
                        <targetxml>@xml:id</targetxml> as described in the instructions for <xref href="../../common_newest/Rosetta_docinfo.doc-lang-and-doc-country-LxAdv-ROOT_xml.lang.dita">Target @xml:lang</xref>.</note>
            </p>
        </section>
        
        <example>
            <title>Source XML</title>
            <codeblock>
&lt;docinfo&gt;
          ....
       &lt;docinfo:doc-country iso-cc="AU"/&gt;
       ....
       &lt;/docinfo&gt;


	</codeblock>
        </example>
        
        <example>
            <title>Target XML</title>
            <codeblock>
&lt;doc:docinfo doc-content-country="AU"&gt;
         ...
        &lt;/doc:docinfo&gt;


	</codeblock>
        </example>
        
        <example>
            <title>Source XML - AU example with case:juris="NZ"</title>
            <codeblock>


&lt;CITATORDOC&gt;
 &lt;docinfo&gt;
   ....
   &lt;docinfo:doc-country iso-cc="AU"/&gt;
    ....
 &lt;/docinfo&gt;
 &lt;cttr:body&gt;
    &lt;case:headnote&gt;
        &lt;case:info&gt;
        ...........
            &lt;case:courtinfo&gt;
            .........
                 &lt;case:juris ln.user-displayed="false"&gt;NZ&lt;/case:juris&gt;
            &lt;/case:courtinfo&gt;
        &lt;/case:info&gt;
    &lt;/case:headnote&gt;
  &lt;/cttr:body&gt;
&lt;/CITATORDOC&gt;

	</codeblock>
        </example>
        
        <example>
            <title>Target XML - AU example with case:juris="NZ" </title>
            <codeblock>
&lt;doc:docinfo doc-content-country="NZ"&gt;
         ...
        &lt;/doc:docinfo&gt;


	</codeblock>
        </example>
        
    
        <section>
            <title>Changes</title>
            <p>2014-11-13: <ph id="change_20141113_BRT"> Created - replaces common topic.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-HK\HK08_CaseCitator\doc.docinfo_doc-content-country.dita  -->
	<xsl:message>doc.docinfo_doc-content-country.xsl requires manual development!</xsl:message> 

	<xsl:template match="docinfo:doc-country[@iso-cc]">

		<!--  Original Target XPath:  doc:docinfo[@doc-content-country]   -->
		<doc:docinfo>
			<xsl:apply-templates select="@* | node()"/>
		</doc:docinfo>

	</xsl:template>

	<xsl:template match="case:headnote/case:info/case:courtinfo//case:juris">

		<!--  Original Target XPath:  doc:docinfo[@doc-content-country="NZ"]   -->
		<doc:docinfo>
			<xsl:apply-templates select="@* | node()"/>
		</doc:docinfo>

	</xsl:template>

	<xsl:template match="case:juris=&#34;NZ&#34;">

		<!--  Original Target XPath:  doc:docinfo[@doc-content-country="NZ"]   -->
		<doc:docinfo>
			<xsl:apply-templates select="@* | node()"/>
		</doc:docinfo>

	</xsl:template>

</xsl:stylesheet>