<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:entity="http://www.lexisnexis.com/xmlschemas/content/shared/identified-entities/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="IN05_Rosetta_company">
  <title>company <lnpid>id-IN05-38815</lnpid></title>
  
  <body>
    <p>
      <ul>
        <li><sourcexml>company</sourcexml> becomes <targetxml>entity:company</targetxml>.                  
        </li>       
      </ul>     
    </p>    
    
    <pre><b>Source XML</b>

&lt;p&gt;
    &lt;text&gt;In addition, tax concessions given to industry to provide
        resources for future development should not be utilized for
        payment of larger bonuses to employees; on the other hand,
        it should be ensured by law if the existing tax law and
        regulations do not sufficiently safeguard this, that amounts
        involved in such tax concessions are in fact used only for
        the purposes for which the tax concessions are given.
        Further, subsidies paid by Government to certain concerns
        like the &lt;company&gt;Hindustan &amp;#x0028;Shipyard&lt;/company&gt;
        should not be taken into account in working out the gross
        profits for the purpose of payment of bonus.&lt;/text&gt;
&lt;/p&gt;



<b>Becomes</b>


&lt;p&gt;
    ...
    &lt;text&gt;In addition, tax concessions given to industry to provide
        resources for future development should not be utilized for
        payment of larger bonuses to employees; on the other hand,
        it should be ensured by law if the existing tax law and
        regulations do not sufficiently safeguard this, that amounts
        involved in such tax concessions are in fact used only for
        the purposes for which the tax concessions are given.
        Further, subsidies paid by Government to certain concerns
        like the &lt;entity:company&gt;Hindustan &amp;#x0028;Shipyard&lt;/entity:company&gt;
        should not be taken into account in working out the gross
        profits for the purpose of payment of bonus.&lt;/text&gt;
    ...
&lt;/p&gt;

</pre>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-IN\IN05-Articles\IN05_Rosetta_company.dita  -->
	<xsl:message>IN05_Rosetta_company.xsl requires manual development!</xsl:message> 

	<xsl:template match="company">

		<!--  Original Target XPath:  entity:company   -->
		<entity:company>
			<xsl:apply-templates select="@* | node()"/>
		</entity:company>

	</xsl:template>

</xsl:stylesheet>