<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journal-Newsletter-Bulletins_bio">
  <title>bio <lnpid>id-NZ08-24007</lnpid></title>

  <body>
   
    <p><sourcexml class="+ topic/keyword xml-d/sourcexml ">contrib/bio</sourcexml> becomes <targetxml>person:contributor[@contributor-type="undetermined"]/person:person/person:bio/person:bio.text/bodytext</targetxml>.</p>





    <p><sourcexml class="+ topic/keyword xml-d/sourcexml ">@contribtype</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">@contributor-type</targetxml></p>
    
    <note>Conversion need to create <targetxml class="+ topic/keyword xml-d/targetxml ">@contributor-type="undetermined"</targetxml> in <targetxml class="+ topic/keyword xml-d/targetxml ">person:contributor</targetxml>.</note>

<pre xml:space="preserve" class="- topic/pre ">&lt;contrib&gt;
  &lt;bio&gt;
    &lt;p&gt;&lt;text&gt;It has for a long time been conveyancing practice, on the presentation of an assignment of lease for the...&lt;/text&gt;&lt;/p&gt;
  &lt;/bio&gt;
&lt;/contrib&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;person:contributor contributor-type="undetermined"&gt;
	&lt;person:person&gt;
		&lt;person:bio&gt;
		    &lt;person:bio.text&gt;
                &lt;bodytext&gt;
                    &lt;p&gt;&lt;text&gt;It has for a long time been conveyancing practice, on the presentation of an assignment of lease for the...&lt;/text&gt;&lt;/p&gt;
                &lt;/bodytext&gt;
            &lt;/person:bio.text&gt;
        &lt;/person:bio&gt;
	&lt;/person:person&gt;
&lt;/person:contributor&gt;
</pre>
    
    <note class="- topic/note ">Handling of <sourcexml class="+ topic/keyword xml-d/sourcexml ">bodytext/contrib/bio/p/text</sourcexml> will become <targetxml class="+ topic/keyword xml-d/targetxml ">bodytext/note/byline/person:contributor[@contributor-type="undetermined"]/person:person/person:bio/person:bio.text/bodytext/p/text</targetxml>.</note>
   
  </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ08_NewsLetter_and_Journals\Journal-Newsletter-Bulletins_bio.dita  -->
	<xsl:message>Journal-Newsletter-Bulletins_bio.xsl requires manual development!</xsl:message> 

	<xsl:template match="contrib/bio">

		<!--  Original Target XPath:  person:contributor[@contributor-type="undetermined"]/person:person/person:bio/person:bio.text/bodytext   -->
		<person:contributor>
			<person:person>
				<person:bio>
					<person:bio.text>
						<bodytext>
							<xsl:apply-templates select="@* | node()"/>
						</bodytext>
					</person:bio.text>
				</person:bio>
			</person:person>
		</person:contributor>

	</xsl:template>

	<xsl:template match="@contribtype">

		<!--  Original Target XPath:  @contributor-type   -->
		<xsl:attribute name="contributor-type">
			<xsl:apply-templates select="node()"/>
		</xsl:attribute>

	</xsl:template>

	<xsl:template match="bodytext/contrib/bio/p/text">

		<!--  Original Target XPath:  bodytext/note/byline/person:contributor[@contributor-type="undetermined"]/person:person/person:bio/person:bio.text/bodytext/p/text   -->
		<bodytext>
			<note>
				<byline>
					<person:contributor>
						<person:person>
							<person:bio>
								<person:bio.text>
									<bodytext>
										<p>
											<text>
												<xsl:apply-templates select="@* | node()"/>
											</text>
										</p>
									</bodytext>
								</person:bio.text>
							</person:bio>
						</person:person>
					</person:contributor>
				</byline>
			</note>
		</bodytext>

	</xsl:template>

</xsl:stylesheet>