<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journal-Newsletter-Bulletins_bodytext">
  <title>bodytext <lnpid>id-NZ08-24008</lnpid></title>

  <body>
    <p><sourcexml class="+ topic/keyword xml-d/sourcexml ">bodytext</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">bodytext</targetxml></p>

      <p>If input document is having <sourcexml class="+ topic/keyword xml-d/sourcexml ">/JOURNALDOC/jrnl:body/jrnl:bodytext/level/bodytext</sourcexml> then it becomes <targetxml class="+ topic/keyword xml-d/targetxml ">/newsitem:newsitem/nitf:body/nitf:body.content/bodytext/section/bodytext</targetxml>.</p>

<pre xml:space="preserve" class="- topic/pre ">&lt;jrnl:body&gt;
    &lt;jrnl:bodytext&gt;
        &lt;level subdoc="true" toc-caption="Introduction"&gt;
            &lt;heading&gt;&lt;title&gt;&lt;refpt id="BCB_NOVEMBER2001-1-0-1-0-1"&gt;&lt;/refpt&gt;Introduction&lt;/title&gt;&lt;/heading&gt;
            &lt;bodytext&gt;
                &lt;p&gt;&lt;text&gt;This is a judgment of some significance for daily conveyancing practice.&lt;/text&gt;&lt;/p&gt;
            &lt;/bodytext&gt;
        &lt;/level&gt;
    &lt;/jrnl:bodytext&gt;
&lt;/jrnl:body&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;nitf:body&gt;
  &lt;nitf:body.content&gt;
      &lt;bodytext&gt;
          &lt;section includeintoc="true" alternatetoccaption="Introduction"&gt;
              &lt;ref:anchor id="BCB_NOVEMBER2001-1-0-1-0-1" anchortype="global"/&gt;
              &lt;heading&gt;&lt;title&gt;Introduction&lt;/title&gt;&lt;/heading&gt;
              &lt;bodytext&gt;
                  &lt;p&gt;
                      &lt;text&gt;This is a judgment of some significance for daily conveyancing practice.&lt;/text&gt;
                  &lt;/p&gt;
              &lt;/bodytext&gt;
          &lt;/section&gt;
      &lt;/bodytext&gt;
  &lt;/nitf:body.content&gt;  
&lt;/nitf:body&gt;
</pre>
</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ08_NewsLetter_and_Journals\Journal-Newsletter-Bulletins_bodytext.dita  -->
	<xsl:message>Journal-Newsletter-Bulletins_bodytext.xsl requires manual development!</xsl:message> 

	<xsl:template match="bodytext">

		<!--  Original Target XPath:  bodytext   -->
		<bodytext>
			<xsl:apply-templates select="@* | node()"/>
		</bodytext>

	</xsl:template>

	<xsl:template match="/JOURNALDOC/jrnl:body/jrnl:bodytext/level/bodytext">

		<!--  Original Target XPath:  /newsitem:newsitem/nitf:body/nitf:body.content/bodytext/section/bodytext   -->
		<newsitem:newsitem xmlns:newsitem="http://www.lexisnexis.com/xmlschemas/content/news/newsitem/1/">
			<nitf:body xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/">
				<nitf:body.content>
					<bodytext>
						<section>
							<bodytext>
								<xsl:apply-templates select="@* | node()"/>
							</bodytext>
						</section>
					</bodytext>
				</nitf:body.content>
			</nitf:body>
		</newsitem:newsitem>

	</xsl:template>

</xsl:stylesheet>