<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:jrnl="http://www.lexis-nexis.com/glp/jrnl" xmlns:nitf="http://iptc.org/std/NITF/2006-10-18/" version="2.0" exclude-result-prefixes="dita jrnl">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journal-Newsletter-Bulletins_jrnl_prelim">
  <title>jrnl:prelim <lnpid>id-AU14-20621</lnpid></title>

  <body>
    <p><sourcexml class="+ topic/keyword xml-d/sourcexml ">jrnl:prelim</sourcexml> conversion need to omit this element.</p>
    
      <p><sourcexml class="+ topic/keyword xml-d/sourcexml ">jrnl:prelim/heading/title</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">nitf:hedline/nitf:hl1</targetxml></p>
      
      <p>Drop <sourcexml>@searchtype</sourcexml> attribute from <sourcexml>heading</sourcexml> element.</p>
    
<pre xml:space="preserve" class="- topic/pre ">
  &lt;jrnl:body&gt;
      &lt;jrnl:prelim&gt;
          &lt;heading&gt;
              &lt;title&gt;Carter's Criminal Law News Queensland&lt;/title&gt;
          &lt;/heading&gt;
          &lt;contrib&gt;Editor: 
              &lt;person&gt;
                  &lt;name.text&gt;&lt;emph typestyle="bf"&gt;S Ryan&lt;/emph&gt;&lt;/name.text&gt;
              &lt;/person&gt; BCom LLB (HONS) Barrister, Legal Aid Queensland
          &lt;/contrib&gt;
      &lt;/jrnl:prelim&gt;
  &lt;/jrnl:body&gt;

<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;nitf:body&gt;
    &lt;nitf:body.head&gt;
        &lt;nitf:hedline&gt;
            &lt;nitf:hl1&gt;Carter's Criminal Law News Queensland&lt;/nitf:hl1&gt;
        &lt;/nitf:hedline&gt;
        &lt;nitf:byline&gt;
            &lt;person:contributor&gt;Editor: &lt;person:person&gt;
                    &lt;person:name.text&gt;&lt;emph typestyle="bf"&gt;S Ryan&lt;/emph&gt;&lt;/person:name.text&gt;
                &lt;/person:person&gt; BCom LLB (HONS) Barrister, Legal Aid Queensland
            &lt;/person:contributor&gt;
        &lt;/nitf:byline&gt;
    &lt;/nitf:body.head&gt;
&lt;/nitf:body&gt;
</pre>

      <p><sourcexml class="+ topic/keyword xml-d/sourcexml ">jrnl:prelim/heading/subtitle</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">nitf:hedline/nitf:hl2</targetxml></p>
<pre>&lt;jrnl:prelim&gt;
    &lt;heading searchtype="JOURNAL-HEADING"&gt;&lt;title&gt;Making the right decision &amp;mdash; The right way&lt;/title&gt;
        &lt;subtitle&gt;&lt;emph typestyle="bf"&gt;&lt;emph typestyle="it"&gt;Christine Deborah Anderson v&amp;nbsp;The Council of the City of Lismore&lt;/emph&gt;&lt;/emph&gt;&lt;/subtitle&gt;
    &lt;/heading&gt;
    ...
&lt;/jrnl:prelim&gt;
    
<b class="+ topic/ph hi-d/b ">Becomes</b>
    
&lt;nitf:hedline&gt;
    &lt;nitf:hl1&gt;Making the right decision &amp;mdash; The right way&lt;/nitf:hl1&gt;
    &lt;nitf:hl2&gt;
        &lt;emph typestyle="bf"&gt;
            &lt;emph typestyle="it"&gt;Christine Deborah Anderson v&amp;nbsp;The Council of the City of Lismore&lt;/emph&gt;
        &lt;/emph&gt;
    &lt;/nitf:hl2&gt;
&lt;/nitf:hedline&gt;</pre>
  </body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU14_Journal-Newsletter-Bulletins\Journal-Newsletter-Bulletins_jrnl_prelim.dita  -->
	<xsl:message>Journal-Newsletter-Bulletins_jrnl_prelim.xsl requires manual development!</xsl:message> 

	<xsl:template match="jrnl:prelim">

		<!--  Original Target XPath:  nitf:hedline/nitf:hl1   -->
		<nitf:hedline>
			<nitf:hl1>
				<xsl:apply-templates select="@* | node()"/>
			</nitf:hl1>
		</nitf:hedline>

	</xsl:template>

	<xsl:template match="jrnl:prelim/heading/title">

		<!--  Original Target XPath:  nitf:hedline/nitf:hl1   -->
		<nitf:hedline>
			<nitf:hl1>
				<xsl:apply-templates select="@* | node()"/>
			</nitf:hl1>
		</nitf:hedline>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:  nitf:hedline/nitf:hl2   -->
		<nitf:hedline>
			<nitf:hl2>
				<xsl:apply-templates select="@* | node()"/>
			</nitf:hl2>
		</nitf:hedline>

	</xsl:template>

	<xsl:template match="heading">

		<!--  Original Target XPath:  nitf:hedline/nitf:hl2   -->
		<nitf:hedline>
			<nitf:hl2>
				<xsl:apply-templates select="@* | node()"/>
			</nitf:hl2>
		</nitf:hedline>

	</xsl:template>

	<xsl:template match="jrnl:prelim/heading/subtitle">

		<!--  Original Target XPath:  nitf:hedline/nitf:hl2   -->
		<nitf:hedline>
			<nitf:hl2>
				<xsl:apply-templates select="@* | node()"/>
			</nitf:hl2>
		</nitf:hedline>

	</xsl:template>

</xsl:stylesheet>