<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" xmlns:primlawinfo="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.officialnum_leg.year">
  <title>leg:officialnum/leg:year <lnpid>id-IN01-15423</lnpid></title>
  <body>
    <section>
      <p><sourcexml>leg:officialnum/leg:year</sourcexml> becomes <targetxml>primlaw:levelinfo/primlawinfo:primlawinfo/primlawinfo:dates/primlawinfo:enactdate</targetxml> with attribute <targetxml>@year</targetxml></p> 
      <note><sourcexml>leg:year</sourcexml> input PCDATA transforms only to target attribute
          <targetxml>primlawinfo:enactdate[@year]</targetxml> and there should be no PCDATA in
        output.</note>
    </section>
    <example>
      <title>Mapping of <sourcexml>leg:year</sourcexml></title>
      <codeblock>

&lt;leg:officialnum searchtype="LEGISLATION" ln.user-displayed="false"&gt;
                &lt;leg:year searchtype="LEGISLATION" ln.user-displayed="false"&gt;2006&lt;/leg:year&gt;
                &lt;leg:seriesnum searchtype="LEGISLATION" ln.user-displayed="false"&gt;35&lt;/leg:seriesnum&gt;
&lt;/leg:officialnum&gt;

      </codeblock>
      <b>becomes</b>
      <codeblock>

&lt;primlaw:levelinfo&gt;
 &lt;primlawinfo:primlawinfo&gt;
    &lt;primlawinfo:dates&gt;
      &lt;primlawinfo:enactdate year="2006"/&gt;
    &lt;/primlawinfo:dates&gt;
    &lt;primlawinfo:identifier idtype="officialnum" source="editoriallyassigned"&gt;
        &lt;primlawinfo:identifier-component type="seriesnum"&gt;35&lt;/primlawinfo:identifier-component&gt;
    &lt;/primlawinfo:identifier&gt;
 &lt;/primlawinfo:primlawinfo&gt;
 &lt;/primlaw:levelinfo&gt;

       </codeblock>
    </example>  
    <note>For handling <b>@ln.user-displayed</b> attribute, refer the
      general markup <xref href="../../common_newest/Rosetta_leg.year_ln.user-displayed.dita">ln.user_displayed="false"</xref> section in the CI.</note>
    <note>The <sourcexml>@searchtype</sourcexml> attribute will be suppressed from conversion except for the citation element.</note>
 <section>
       <title>Changes</title>
       <p>2014-03-21: <ph id="change_20131114_SS">Created</ph>.</p>
</section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\IN01_Legislation\leg.officialnum_leg.year.dita  -->
	<xsl:message>leg.officialnum_leg.year.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:officialnum/leg:year">

		<!--  Original Target XPath:  primlaw:levelinfo/primlawinfo:primlawinfo/primlawinfo:dates/primlawinfo:enactdate   -->
		<primlaw:levelinfo>
			<primlawinfo:primlawinfo>
				<primlawinfo:dates>
					<primlawinfo:enactdate>
						<xsl:apply-templates select="@* | node()"/>
					</primlawinfo:enactdate>
				</primlawinfo:dates>
			</primlawinfo:primlawinfo>
		</primlaw:levelinfo>

	</xsl:template>

	<xsl:template match="leg:year">

		<!--  Original Target XPath:  primlawinfo:enactdate[@year]   -->
		<primlawinfo:enactdate>
			<xsl:apply-templates select="@* | node()"/>
		</primlawinfo:enactdate>

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>