<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/" xmlns:frm="http://www.lexis-nexis.com/glp/frm"
  xmlns:leg="http://www.lexis-nexis.com/glp/leg"
  xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0"
  exclude-result-prefixes="dita leg">

  <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="leg.endmatter-sigblock">
    <title>leg:endmatter/sigblock <lnpid>id-UK07-28235</lnpid></title>
    <body>
      <section>
        <p>If <sourcexml>sigblock</sourcexml> comes under the <sourcexml>leg:endmatter</sourcexml>
          markup in source then target conversion needs to convert
            <targetxml>primlaw:level[@leveltype="endnote"]/primlaw:bodytext/sigbock</targetxml> and
          all other sub-child elements converted through the common module.</p>
      </section>
      <example>
        <title>Source XML 1</title>
        <codeblock> &lt;leg:body&gt; &lt;!-- ETC. --&gt; &lt;leg:endmatter&gt; &lt;sigblock&gt;
          &lt;p&gt;&lt;text&gt;In witness whereof the common seal of the Building
          ...&lt;/text&gt;&lt;/p&gt; &lt;/sigblock&gt; &lt;/leg:endmatter&gt; &lt;/leg:body&gt;
        </codeblock>
      </example>
      <example>
        <title>Target XML 1</title>
        <codeblock> &lt;legis:body&gt; &lt;!-- ETC. --&gt; &lt;primlaw:level leveltype="endnote"&gt;
          &lt;primlaw:bodytext&gt; &lt;sigblock&gt; &lt;p&gt;&lt;text&gt;In witness whereof the
          common seal of the Building ...&lt;/text&gt;&lt;/p&gt; &lt;/sigblock&gt;
          &lt;/primlaw:bodytext&gt; &lt;/primlaw:level&gt; &lt;/legis:body&gt; </codeblock>
      </example>
      <section>
        <title>Changes</title>
        <p>2016-09-27 <ph id="change_20160927_SS">Created the instruction for handling input
              <sourcexml>leg:endmatter/sigblock</sourcexml>.</ph></p>
      </section>
    </body>
  </dita:topic>

  <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
  <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK07-Regulations\leg.endmatter-sigblock.dita  -->
  <!--This is initial chaged by the Chaitanya for UK07-Regulation	-->
  <xsl:template match="sigblock">
    <primlaw:bodytext>
    <sigblock>
      <xsl:apply-templates select="@* | node()"/>
    </sigblock>
      </primlaw:bodytext>
  </xsl:template>

  <xsl:template match="sigblock[parent::leg:endmatter]">
    <primlaw:bodytext>
      <sigblock>
        <xsl:apply-templates select="@* | node()"/>
      </sigblock>
    </primlaw:bodytext>
  </xsl:template>


  <xsl:template match="sigblock[ancestor::frm:div | ancestor::frm:body]">
    <form:sigblock>
      <xsl:apply-templates select="@* | node()"/>
    </form:sigblock>
  </xsl:template>



</xsl:stylesheet>
