<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:source_cttr="http://www.lexis-nexis.com/glp/cttr" xmlns:cttr="urn:x-lexisnexis:content:citator:sharedservices:1" xmlns:primlawhist="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw-history/1/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita cttr">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Leg_Citator_AUNZ_History_cttr.content">
  <title>cttr:body/cttr:content <lnpid>id-AU20-22282</lnpid></title>
  
  <body>
    <section>
      <p>For <sourcexml>cttr:body/cttr:content</sourcexml> output <targetxml>cttr:body/cttr:history</targetxml>.</p>
      <p>Create <targetxml>cttr:history/primlawhist:primlawhist</targetxml>.</p>
      <p>Create <targetxml>ref:anchor[@id="ref-history"]</targetxml> within 
        <targetxml>primlawhist:primlawhist</targetxml>.</p>
      <p>For whole-act documents, the source normally contains <sourcexml>cttr:annotations/heading/title</sourcexml>; 
        map to <targetxml>primlawhist:primlawhist/heading/title</targetxml>.</p>
      <p>For provision documents, the source may not include a title of History, and it is possible that 
        a title may have been omitted from a whole-act document. If the source document does not contain
        <sourcexml>cttr:annotations/heading/title</sourcexml>, conversion should create one:  
        Create <targetxml>primlawhist:primlawhist/heading/title</targetxml> containing "History".</p>
      <!-- <p>The content of <sourcexml>cttr:annotsummary</sourcexml> maps to <targetxml>primlawhist:histitem/bodytext</targetxml></p> -->
    </section>
    <example>
      <title>Example 1: Source History annotations - Whole Act</title>
      <codeblock>
        &lt;cttr:content&gt;
            &lt;cttr:annotations&gt;
            &lt;heading&gt;
               &lt;title&gt;History&lt;/title&gt;
            &lt;/heading&gt;
       
        </codeblock>

      <title>Example 1: Target History annotations - Whole Act and Provision</title>
      <codeblock>
          &lt;cttr:history&gt;
            &lt;primlawhist:primlawhist&gt;
                &lt;ref:anchor id="ref-history"/&gt;
                &lt;heading&gt;
                    &lt;title&gt;History&lt;/title&gt;
                &lt;/heading&gt;      
        </codeblock>
    </example>
    
    <section>
      <title>
        Changes:
      </title>
      <p>2016-11-07: <ph id="change_20161107_snb">Modified wording to always create 
        <targetxml>primlawhist:primlawhist/heading/title</targetxml> containing "History" when the source 
        does not contain <sourcexml>cttr:annotations/heading/title</sourcexml>.</ph>
      </p>
      <p>2015-12-11: <ph id="change_20151211a_snb">Changed <targetxml>cttr:body/cttr:refs</targetxml> to be 
        <targetxml>cttr:body/cttr:history</targetxml>. Added specification of the title that should be created 
        for provision documents to be "History". Added creation of <targetxml>ref:anchor[@id="ref-history"]</targetxml> 
        (was in example but not text instruction). Changed <sourcexml>cttr:annotations/heading/title</sourcexml> 
        contains "history" to be contains "History". Changed to create <targetxml>cttr:history/primlawhist:primlawhist</targetxml> 
        and <targetxml>ref:anchor[@id="ref-history"]</targetxml> always (was based upon a test). Moved 
        <targetxml>@xml:id="HI1-History"</targetxml> to the "cttr:content/cttr:annotations/heading/title containing History - 
        with cttr:annotsummary/table" section as <targetxml>primlawhist:histgrp/@grptype</targetxml> since it only 
        applies to that section.</ph>
      </p>
    </section>
    
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU20_Legislative_Citator\Leg_Citator_AUNZ_History_cttr.content.dita  -->
	<xsl:message>Leg_Citator_AUNZ_History_cttr.content.xsl requires manual development!</xsl:message> 

	<xsl:template match="cttr:body/cttr:content"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  cttr:body/cttr:history   -->
		<cttr:body>
			<cttr:history>
				<xsl:apply-templates select="@* | node()"/>
			</cttr:history>
		</cttr:body>

	</xsl:template>

	<xsl:template match="cttr:annotations/heading/title"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  primlawhist:primlawhist/heading/title   -->
		<primlawhist:primlawhist>
			<heading>
				<title>
					<xsl:apply-templates select="@* | node()"/>
				</title>
			</heading>
		</primlawhist:primlawhist>

	</xsl:template>

</xsl:stylesheet>