<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Leg_Citator_AUNZ_History_p-blockquote-legfragment">
  <title>p/blockquote/legfragment to p/primlaw:excerp <lnpid>id-AU20-22284</lnpid></title>
  
  <body>
    <section>
      <p>
        <sourcexml>p/blockquote/legfragment</sourcexml> within the open <targetxml>p</targetxml>,
        create a child element <targetxml>primlaw:excerpt</targetxml>
      </p>
    </section>

    <example>
      <title>Example 1: Source p/blockquote/legfragment</title>
      <codeblock>
&lt;cttr:annotations id="HI15"&gt;
 &lt;heading id="HI14"&gt;
  &lt;title&gt;Amending Legislation&lt;/title&gt; 
  
   &lt;note&gt;
     &lt;p&gt;
      &lt;text&gt;Part 2 revoked on 1 July 1993 by &lt;link refpt="1991R196:1993R182" dpsi="006A"&gt;Adult Adoption Information (Fees) Regulations 1991, 
      Amendment No 1 SR 1993/182/2(b)&lt;/link&gt;.&lt;/text&gt;
     &lt;/p&gt;
     &lt;p&gt;
      &lt;text&gt;The revoked Part is listed below for reference.&lt;/text&gt; 
      &lt;blockquote&gt;
        &lt;legfragment&gt;
          &lt;p&gt;
           &lt;text&gt;PART 2&lt;/text&gt; 
          &lt;/p&gt;
          ...
        &lt;/legfragment&gt;
      &lt;/blockquote&gt;
    ...&lt;/p&gt;
      
  ...&lt;/note&gt;         
        </codeblock>

      <title>Example 1: Target p/primlaw:excerpt</title>
      <codeblock>
        
        &lt;primlawhist:primlawhist xml:id="HI14"&gt;
         	&lt;primlawhist:histgrp xml:id="HI15" &gt;
            &lt;heading&gt;
               &lt;title&gt;Amending Legislation&lt;/title&gt;
            &lt;/heading&gt;
            
            &lt;primlawhist:histitem&gt;
                 &lt;bodytext&gt;
                   &lt;p&gt;
                    &lt;text&gt;Part 2 revoked on 1 July 1993 by 
                       &lt;ref:lnlink&gt;
                          &lt;ref:marker&gt;Adult Adoption Information (Fees) Regulations 1991, Amendment No 1 SR 1993/182/2(b)&lt;/ref:marker&gt;
                             &lt;ref:locator anchoridref="1991R196:1993R182"/&gt;
                       &lt;/ref:lnlink&gt;.&lt;/text&gt;
                    &lt;/p&gt;
                    &lt;p&gt;
                     &lt;text&gt;The revoked Part is listed below for reference.&lt;/text&gt; 
                     &lt;primlaw:excerpt&gt;
                        
                        &lt;primlaw:bodytext&gt;
                           &lt;p&gt;
                            &lt;text&gt;PART 2&lt;/text&gt; 
                          &lt;/p&gt;
                          ...
                        &lt;/primlaw:bodytext&gt;
                      &lt;/primlaw:excerpt&gt;
                    ...&lt;/p&gt;
                   &lt;/bodytext&gt;
              &lt;/primlaw:histitem&gt;
        </codeblock>
    </example>
    
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU20_Legislative_Citator\Leg_Citator_AUNZ_History_p-blockquote-legfragment.dita  -->
	<xsl:message>Leg_Citator_AUNZ_History_p-blockquote-legfragment.xsl requires manual development!</xsl:message> 

	<xsl:template match="p/blockquote/legfragment">

		<!--  Original Target XPath:  p   -->
		<p>
			<xsl:apply-templates select="@* | node()"/>
		</p>

	</xsl:template>

</xsl:stylesheet>