<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:source_cttr="http://www.lexis-nexis.com/glp/cttr" xmlns:cttr="urn:x-lexisnexis:content:citator:sharedservices:1" version="2.0" exclude-result-prefixes="dita cttr">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Leg_Citator_AUNZ_Cases_table_p-limited-idCI4">
  <title>table/p-limited[@id="CI4"] <lnpid>id-AU20-22277</lnpid></title>
  
  <body>

    <section>
      <p>When found in case references documents, this <sourcexml>p-limited</sourcexml> element should be mapped to 
        <targetxml>cttr:refssummaryitem @documenttype="note" @value="CI4"</targetxml> following the last <targetxml>cttr:refssummarygroup</targetxml>.</p>
    </section>
    <example>
      <title>Example 1: Sample with <sourcexml>table/p-limited[@id="CI4"]</sourcexml>
      </title>
      <codeblock>
        ...&lt;row&gt;...&lt;/row&gt;
           &lt;/tbody&gt;
          &lt;/tgroup&gt;
         
            &lt;p-limited id="CI4"&gt;The cases included are editorially selected, based on whether there is consideration of the relevant legislative item within the judgment.&lt;/p-limited&gt;
        &lt;/table&gt;
      </codeblock>

      <title>Example 1: Target with <sourcexml>cttr:refssummaryitem @documenttype="note" @value="CI4"</sourcexml>
      </title>
      <codeblock>
        ...
             &lt;cttr:refssummaryitem documenttype="case" value="caseReported"
                     &gt;0&lt;/cttr:refssummaryitem&gt;
             &lt;/cttr:refssummarygroup&gt;
              &lt;cttr:refssummaryitem documenttype="note" value="CI4"&gt;
                  A case is included if the relevant legislative item is considered within the judgment. Case coverage is aligned with CaseBase.
              &lt;/cttr:refssummaryitem&gt;
         &lt;/cttr:refssummary&gt;
         ...
              
      </codeblock>
    </example>
    <section>
      <title>
        Changes:
      </title>
    </section>

  </body>
  
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU20_Legislative_Citator\Leg_Citator_AUNZ_Cases_table_p-limited-idCI4.dita  -->
	<xsl:message>Leg_Citator_AUNZ_Cases_table_p-limited-idCI4.xsl requires manual development!</xsl:message> 

	<xsl:template match="p-limited"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  cttr:refssummaryitem@documenttype="note"@value="CI4"   -->
		<cttr:refssummaryitem>
			<xsl:apply-templates select="@* | node()"/>
		</cttr:refssummaryitem>

	</xsl:template>

	<xsl:template match="table/p-limited[@id=&#34;CI4&#34;]"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="cttr:refssummaryitem @documenttype=&#34;note&#34; @value=&#34;CI4&#34;"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  cttr:refssummarygroup   -->
		<cttr:refssummarygroup>
			<xsl:apply-templates select="@* | node()"/>
		</cttr:refssummarygroup>

	</xsl:template>

</xsl:stylesheet>