<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:source_cttr="http://www.lexis-nexis.com/glp/cttr" xmlns:cttr="urn:x-lexisnexis:content:citator:sharedservices:1" version="2.0" exclude-result-prefixes="dita cttr">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Leg_Citator_AUNZ_Cases_cttr.annotsummary-CaseTotals">
  <title>cttr:annotations/cttr:annotsummary[@display-name="Totals"] - Case Totals <lnpid>id-AU20-22273</lnpid></title>
  
  <body>

    <section>
      <p>When <sourcexml>cttr:annotsummary</sourcexml> contains an attribute <sourcexml>@display-name="Totals"</sourcexml> 
        containing a <sourcexml>table</sourcexml>, the conversion should
        NOT create a <targetxml>table</targetxml>. It should instead create 
        <targetxml>cttr:refssummarygroup[@grouptype="CaseTotals"]</targetxml>. If  
        <targetxml>cttr:refssummary[@xml:id="CI2"][@summarytype="subseqcases"]</targetxml> is created by the previous 
        instructions for <sourcexml>cttr:annotations/cttr:annotsummary[@display-name="Cases by Court and Year"][@id="CI2"]</sourcexml>, 
        insert this <targetxml>cttr:refssummarygroup[@grouptype="CaseTotals"]</targetxml> as a child of that existing 
        <targetxml>cttr:refssummary[@xml:id="CI2"]</targetxml>, after both <targetxml>cttr:refssummarygroup[@grouptype="Court"]</targetxml> 
        and <targetxml>cttr:refssummarygroup[@grouptype="Year"]</targetxml> siblings if they exist, and before 
        any sibling <targetxml>cttr:refssummaryitem</targetxml>.</p>
      <p>For each <sourcexml>table/tgroup/tbody/row</sourcexml> create 
        <targetxml>cttr:refssummarygroup/cttr:refssummaryitem[@documenttype="case"]</targetxml> as add content 
        as follows:
        <ul>
          <li>If <sourcexml>row/entry[2]/@id</sourcexml> = "CI5" or <sourcexml>row/entry[1]/text()</sourcexml> 
            contains "TOTAL CASES", create <targetxml>cttr:refssummaryitem/@value="caseTotal"</targetxml>, and map 
            <sourcexml>row/entry[@id="CI5"]/text()</sourcexml> to <targetxml>cttr:refssummaryitem/text()</targetxml>.</li>
          <li>If <sourcexml>row/entry[2]/@id</sourcexml> = "CI6" or <sourcexml>row/entry[1]/text()</sourcexml> 
            contains "LAST 12 MONTHS", create <targetxml>cttr:refssummaryitem/@value="case12mos"</targetxml>, and map 
            <sourcexml>row/entry[@id="CI6"]/text()</sourcexml> to <targetxml>cttr:refssummaryitem/text()</targetxml>.</li>
          <li>If <sourcexml>row/entry[2]/@id</sourcexml> = "CI7" or <sourcexml>row/entry[1]/text()</sourcexml> 
            contains "REPORTED", create <targetxml>cttr:refssummaryitem/@value="caseReported"</targetxml>, and map 
            <sourcexml>row/entry[@id="CI7"]/text()</sourcexml> to <targetxml>cttr:refssummaryitem/text()</targetxml>.</li>
        </ul>
      </p>
    </section>
    <example>
      <title>Example 1: Source Case Totals</title>
      <codeblock>
&lt;cttr:annotsummary display-name="Totals"&gt;
	&lt;table&gt;
		&lt;tgroup cols="2"&gt;
			&lt;tbody&gt;
				&lt;row&gt;
					&lt;!-- CI5 CP4 TOTAL CASES --&gt;
					&lt;entry&gt;TOTAL CASES&lt;/entry&gt;
					&lt;entry id="CI5"&gt;68&lt;/entry&gt;
				&lt;/row&gt;
				&lt;!-- CI6 CP5 Summary Stats - Last 12 months --&gt;
				&lt;row&gt;
					&lt;entry&gt;LAST 12 MONTHS&lt;/entry&gt;
					&lt;entry id="CI6"&gt;0&lt;/entry&gt;
				&lt;/row&gt;
				&lt;!-- CI7 CP6 Summary Stats - Reported --&gt;
				&lt;row&gt;
					&lt;entry&gt;REPORTED&lt;/entry&gt;
					&lt;entry id="CI7"&gt;62&lt;/entry&gt;
				&lt;/row&gt;
			&lt;/tbody&gt;
		&lt;/tgroup&gt;
	&lt;/table&gt;
&lt;/cttr:annotsummary&gt;
        </codeblock>

      <title>Example 1: Target Case Totals</title>
      <codeblock>
&lt;cttr:refssummary xml:id="CI2" summarytype="subseqcases"&gt;
	&lt;cttr:refssummarygroup grouptype="Year"&gt;
		...
	&lt;/cttr:refssummarygroup&gt;
	&lt;cttr:refssummarygroup grouptype="Court"&gt;
		...
	&lt;/cttr:refssummarygroup&gt;
	&lt;cttr:refssummarygroup grouptype="CaseTotals"&gt;
		&lt;cttr:refssummaryitem documenttype="case" value="caseTotal"&gt;68&lt;/cttr:refssummaryitem&gt;
		&lt;cttr:refssummaryitem documenttype="case" value="case12mos"&gt;0&lt;/cttr:refssummaryitem&gt;
		&lt;cttr:refssummaryitem documenttype="case" value="caseReported"&gt;62&lt;/cttr:refssummaryitem&gt;
	&lt;/cttr:refssummarygroup&gt;
	&lt;cttr:refssummaryitem documenttype="note" value="CI4"&gt;...&lt;/cttr:refssummaryitem&gt;
&lt;/cttr:refssummary&gt;
        </codeblock>
    </example>
    <section>
      <title>
        Changes:
      </title>
      <p>2015-12-11: <ph id="change_20151211e_snb">Created a new section for "Case Totals".</ph>
      </p>
    </section>

  </body>
  
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU20_Legislative_Citator\Leg_Citator_AUNZ_Cases_cttr.annotsummary-CaseTotals.dita  -->
	<xsl:message>Leg_Citator_AUNZ_Cases_cttr.annotsummary-CaseTotals.xsl requires manual development!</xsl:message> 

	<xsl:template match="cttr:annotsummary"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  table   -->
		<table>
			<xsl:apply-templates select="@* | node()"/>
		</table>

	</xsl:template>

	<xsl:template match="@display-name=&#34;Totals&#34;"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  table   -->
		<table>
			<xsl:apply-templates select="@* | node()"/>
		</table>

	</xsl:template>

	<xsl:template match="table"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  table   -->
		<table>
			<xsl:apply-templates select="@* | node()"/>
		</table>

	</xsl:template>

	<xsl:template match="cttr:annotations/cttr:annotsummary[@display-name=&#34;Cases by Court and Year&#34;][@id=&#34;CI2&#34;]"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  cttr:refssummarygroup[@grouptype="CaseTotals"]   -->
		<cttr:refssummarygroup>
			<xsl:apply-templates select="@* | node()"/>
		</cttr:refssummarygroup>

	</xsl:template>

	<xsl:template match="table/tgroup/tbody/row"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  cttr:refssummarygroup/cttr:refssummaryitem[@documenttype="case"]   -->
		<cttr:refssummarygroup>
			<cttr:refssummaryitem>
				<xsl:apply-templates select="@* | node()"/>
			</cttr:refssummaryitem>
		</cttr:refssummarygroup>

	</xsl:template>

	<xsl:template match="row/entry[2]/@id"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  cttr:refssummaryitem/@value="caseTotal"   -->
		<cttr:refssummaryitem>
			<xsl:attribute name="value">
				<xsl:text>caseTotal</xsl:text>
			</xsl:attribute>
		</cttr:refssummaryitem>

	</xsl:template>

	<xsl:template match="row/entry[1]/text()"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  cttr:refssummaryitem/@value="caseTotal"   -->
		<cttr:refssummaryitem>
			<xsl:attribute name="value">
				<xsl:text>caseTotal</xsl:text>
			</xsl:attribute>
		</cttr:refssummaryitem>

	</xsl:template>

	<xsl:template match="row/entry[@id=&#34;CI5&#34;]/text()"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  cttr:refssummaryitem/text()   -->
		<cttr:refssummaryitem>
			<!--  Could not determine target element or attribute name:  <text()>  -->				<xsl:apply-templates select="@* | node()"/>
			<!--  Could not determine target element or attribute name:  </text()>  -->
		</cttr:refssummaryitem>

	</xsl:template>

	<xsl:template match="row/entry[@id=&#34;CI6&#34;]/text()"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  cttr:refssummaryitem/text()   -->
		<cttr:refssummaryitem>
			<!--  Could not determine target element or attribute name:  <text()>  -->				<xsl:apply-templates select="@* | node()"/>
			<!--  Could not determine target element or attribute name:  </text()>  -->
		</cttr:refssummaryitem>

	</xsl:template>

	<xsl:template match="row/entry[@id=&#34;CI7&#34;]/text()"><!--  TODO:  correct match pattern to prepend "source_" in front of appropriate ns prefixes!!  -->

		<!--  Original Target XPath:  cttr:refssummaryitem/text()   -->
		<cttr:refssummaryitem>
			<!--  Could not determine target element or attribute name:  <text()>  -->				<xsl:apply-templates select="@* | node()"/>
			<!--  Could not determine target element or attribute name:  </text()>  -->
		</cttr:refssummaryitem>

	</xsl:template>

</xsl:stylesheet>