<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="navaid-separate-levels-source">
            <title>Source XML</title>
            <body>
<codeblock>

&lt;docinfo&gt;
&lt;!-- ... --&gt;
  &lt;docinfo:doc-id&gt;DEEMED-REGS-ARCHIVE-ALPHA&lt;/docinfo:doc-id&gt;
&lt;!-- ... --&gt;
&lt;/docinfo&gt;
&lt;comm:body&gt;
  &lt;level id="DEEMED-REGS-ARCHIVE-ALPHA" leveltype="comm.chap"&gt; &lt;!-- This is the top &lt;level&gt; start-tag, 
                                                                                                                   this start-tag is ALWAYS dropped 
                                                                                                                   for landing pages.
                                                                                                             --&gt;
    &lt;heading searchtype="COMMENTARY"&gt;
      &lt;title&gt;&lt;refpt type="ext" id="DEEMED-REGS-ARCHIVE-ALPHA"/&gt;Deemed Regulations &amp;mdash;
        Alphabetical&lt;/title&gt;
    &lt;/heading&gt;
    &lt;bodytext searchtype="COMMENTARY"&gt;
    &lt;!-- ...1... --&gt;
    &lt;/bodytext&gt;
    &lt;level id="DEEMED-ARCHIVE-LAND-TRANSPORT" leveltype="group" toc-caption="Land Transport Rules"
      subdoc="true"&gt;
      &lt;heading searchtype="COMMENTARY"&gt;
        &lt;title&gt;&lt;refpt type="ext" id="DEEMED-ARCHIVE-LAND-TRANSPORT"/&gt;Land Transport Rules&lt;/title&gt;
      &lt;/heading&gt;
      &lt;bodytext searchtype="COMMENTARY"&gt;
        &lt;p&gt;
          &lt;text&gt;(Land Transport Rules are displayed under the authority of the Land Transport
            Safety Authority)&lt;/text&gt;
        &lt;/p&gt;
        &lt;p&gt;
          &lt;text&gt;
            &lt;remotelink refpt="LTR31001" dpsi="02IO" remotekey1="REFPTID" docidref="EXAMPLE_DOCID1" service="DOC-ID"&gt;Land
              Transport Rule 31001: Passenger Service Vehicles 1999&lt;/remotelink&gt;
          &lt;/text&gt;
        &lt;/p&gt;
        &lt;p&gt;
          &lt;text&gt;
            &lt;remotelink refpt="LTR31002" dpsi="02IO" remotekey1="REFPTID" docidref="EXAMPLE_DOCID2" service="DOC-ID"&gt;Land
              Transport Rule 31002: Heavy Vehicles 2004&lt;/remotelink&gt;
          &lt;/text&gt;
        &lt;/p&gt;
        &lt;!-- ...2... --&gt;
      &lt;/bodytext&gt;
    &lt;/level&gt;
    &lt;level id="DEEMED-ARCHIVE-MARINE" leveltype="group" toc-caption="Marine Protection Rules"
      subdoc="true"&gt;
      &lt;heading searchtype="COMMENTARY"&gt;
        &lt;title&gt;&lt;refpt type="ext" id="DEEMED-ARCHIVE-MARINE"/&gt;Marine Protection Rules&lt;/title&gt;
      &lt;/heading&gt;
      &lt;bodytext searchtype="COMMENTARY"&gt;
        &lt;p&gt;
          &lt;text&gt;
            &lt;remotelink refpt="MPR100" dpsi="02IO" remotekey1="REFPTID" docidref="EXAMPLE_DOCID3" service="DOC-ID"&gt;Marine
              Protection Rules: Part 100-Port Reception Facilities-Oil, Noxious Liquid Substances,
              and Garbage&lt;/remotelink&gt;
          &lt;/text&gt;
        &lt;/p&gt;
        &lt;p&gt;
          &lt;text&gt;
            &lt;remotelink refpt="MPR101A" dpsi="02IO" remotekey1="REFPTID" docidref="EXAMPLE_DOCID4" service="DOC-ID"&gt;Marine
              Protection Rules: Part 101A-Surveys and Inspections-Oil&lt;/remotelink&gt;
          &lt;/text&gt;
        &lt;/p&gt;
        &lt;!-- ...3... --&gt;
      &lt;/bodytext&gt;
    &lt;/level&gt;
    &lt;!-- ...4... --&gt;
  &lt;/level&gt; &lt;!-- This is the top &lt;level&gt; end-tag, 
                       this end-tag is ALWAYS dropped for landing pages. 
                 --&gt;
&lt;/comm:body&gt;
            
</codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU16_navaid\navaid-separate-levels-source.dita  -->
	

</xsl:stylesheet>