<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="navaid-separate-levels-target">
            <title>Target XML</title>
            <body>
<codeblock>

&lt;!-- ... --&gt;
&lt;navaid:landingpagebody&gt;
  &lt;ref:anchor id="DEEMED-REGS-ARCHIVE-ALPHA" anchortype="global"/&gt;
  &lt;heading&gt;
    &lt;title&gt;Deemed Regulations -- Alphabetical&lt;/title&gt;
  &lt;/heading&gt;
  &lt;!-- ...1... --&gt;
  &lt;navaid:list style="default"&gt;
    &lt;ref:anchor id="DEEMED-ARCHIVE-LAND-TRANSPORT" anchortype="global"/&gt;
    &lt;title&gt;Land Transport Rules&lt;/title&gt;
    &lt;note&gt;
      &lt;bodytext&gt;
        &lt;p&gt;
          &lt;text&gt;(Land Transport Rules are displayed under the authority of the Land Transport
            Safety Authority)&lt;/text&gt;
        &lt;/p&gt;
      &lt;/bodytext&gt;
    &lt;/note&gt;
    &lt;index:entry&gt;
      &lt;index:locator&gt;&lt;ref:lnlink service="DOCUMENT"&gt;
        &lt;ref:marker&gt;Land Transport Rule 31001: Passenger Service Vehicles 1999&lt;/ref:marker&gt;
        &lt;ref:locator anchoridref="LTR31001"&gt;
          &lt;ref:locator-key&gt;
            &lt;ref:key-name name="DOC-ID"/&gt;
            &lt;ref:key-value value="02IO-EXAMPLE_DOCID1"/&gt;
          &lt;/ref:locator-key&gt;
        &lt;/ref:locator&gt;
      &lt;/ref:lnlink&gt;&lt;/index:locator&gt;
    &lt;/index:entry&gt;
    &lt;index:entry&gt;
      &lt;index:locator&gt;&lt;ref:lnlink service="DOCUMENT"&gt;
        &lt;ref:marker&gt;Land Transport Rule 31002: Heavy Vehicles 2004&lt;/ref:marker&gt;
        &lt;ref:locator anchoridref="LTR31002"&gt;
          &lt;ref:locator-key&gt;
            &lt;ref:key-name name="DOC-ID"/&gt;
            &lt;ref:key-value value="02IO-EXAMPLE_DOCID2"/&gt;
          &lt;/ref:locator-key&gt;
        &lt;/ref:locator&gt;
      &lt;/ref:lnlink&gt;&lt;/index:locator&gt;
    &lt;/index:entry&gt;
    &lt;!-- ...2... --&gt;
  &lt;/navaid:list&gt;
  &lt;navaid:list style="default"&gt;
    &lt;ref:anchor id="DEEMED-ARCHIVE-MARINE" anchortype="global"/&gt;
    &lt;title&gt;Marine Protection Rules&lt;/title&gt;
    &lt;index:entry&gt;
      &lt;index:locator&gt;&lt;ref:lnlink service="DOCUMENT"&gt;
        &lt;ref:marker&gt;Marine Protection Rules: Part 100-Port Reception Facilities-Oil, Noxious
          Liquid Substances, and Garbage&lt;/ref:marker&gt;
        &lt;ref:locator anchoridref="MPR100"&gt;
          &lt;ref:locator-key&gt;
            &lt;ref:key-name name="DOC-ID"/&gt;
            &lt;ref:key-value value="02IO-EXAMPLE_DOCID3"/&gt;
          &lt;/ref:locator-key&gt;
        &lt;/ref:locator&gt;
      &lt;/ref:lnlink&gt;&lt;/index:locator&gt;
    &lt;/index:entry&gt;
    &lt;index:entry&gt;
      &lt;index:locator&gt;&lt;ref:lnlink service="DOCUMENT"&gt;
        &lt;ref:marker&gt;Marine Protection Rules: Part 101A-Surveys and Inspections-Oil&lt;/ref:marker&gt;
        &lt;ref:locator anchoridref="MPR101A"&gt;
          &lt;ref:locator-key&gt;
            &lt;ref:key-name name="DOC-ID"/&gt;
            &lt;ref:key-value value="02IO-EXAMPLE_DOCID4"/&gt;
          &lt;/ref:locator-key&gt;
        &lt;/ref:locator&gt;
      &lt;/ref:lnlink&gt;&lt;/index:locator&gt;
    &lt;/index:entry&gt;
    &lt;!-- ...3... --&gt;
  &lt;/navaid:list&gt;
  &lt;!-- ...4... --&gt;
&lt;/navaid:landingpagebody&gt;

</codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\AU16_navaid\navaid-separate-levels-target.dita  -->
	

</xsl:stylesheet>