<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Journal-Newsletter-Bulletins_date">
  <title>date <lnpid>id-NZ08-24010</lnpid></title>

  <body>
    <p><sourcexml class="+ topic/keyword xml-d/sourcexml ">date</sourcexml> becomes <targetxml class="+ topic/keyword xml-d/targetxml ">pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate</targetxml></p>

    <p><targetxml class="+ topic/keyword xml-d/targetxml ">@year</targetxml> and <targetxml class="+ topic/keyword xml-d/targetxml ">@month</targetxml> are created as attribute of
            <targetxml class="+ topic/keyword xml-d/targetxml ">pubinfo:pubdate</targetxml>
         element.</p>

<pre xml:space="preserve" class="- topic/pre ">
    &lt;pubdate&gt;
       &lt;date month="02" year="2009"/&gt;
    &lt;/pubdate&gt;


<b class="+ topic/ph hi-d/b ">Becomes</b>

   &lt;pubinfo:dates&gt;
      &lt;pubinfo:pubdate month="02" year="2009"/&gt;
   &lt;/pubinfo:dates&gt;
</pre>

     <p>If input documents is having scenario <sourcexml class="+ topic/keyword xml-d/sourcexml ">pubdate@ln.user-displayed="false"/date</sourcexml> then it becomes <targetxml class="+ topic/keyword xml-d/targetxml ">pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate</targetxml></p>
     
     <p><targetxml class="+ topic/keyword xml-d/targetxml ">@year</targetxml> and <targetxml class="+ topic/keyword xml-d/targetxml ">@month</targetxml> are created as attribute of
        <targetxml class="+ topic/keyword xml-d/targetxml ">pubinfo:pubdate</targetxml>
        element.</p>
     <note>When <b>ln.user-displayed="false"</b> appears on any date element (i.e. <b>pubdate
            ln.user-displayed="false"</b>), that element is translated into the target but with the
         element content omitted.</note>
     
     <pre xml:space="preserve" class="- topic/pre ">
&lt;pubdate ln.user-displayed="false"&gt;
   &lt;date month="11" year="2001"&gt;November 2001&lt;/date&gt;
&lt;/pubdate&gt;


<b class="+ topic/ph hi-d/b ">Becomes</b>

&lt;pubinfo:dates&gt;
   &lt;pubinfo:pubdate month="11" year="2001"/&gt;
&lt;/pubinfo:dates&gt;
</pre>
     
     
</body>

	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ08_NewsLetter_and_Journals\Journal-Newsletter-Bulletins_date.dita  -->
	<xsl:message>NZ08_NewsLetter_and_Journals_Journal-Newsletter-Bulletins_date.xsl requires manual development!</xsl:message> 

	<xsl:template match="date">

		<!--  Original Target XPath:  pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate   -->
		<pubinfo:pubinfo>
			<pubinfo:dates>
				<pubinfo:pubdate>
					<xsl:apply-templates select="@* | node()"/>
				</pubinfo:pubdate>
			</pubinfo:dates>
		</pubinfo:pubinfo>

	</xsl:template>

	<xsl:template match="pubdate@ln.user-displayed=&#34;false&#34;/date">

		<!--  Original Target XPath:  pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate   -->
		<pubinfo:pubinfo>
			<pubinfo:dates>
				<pubinfo:pubdate>
					<xsl:apply-templates select="@* | node()"/>
				</pubinfo:pubdate>
			</pubinfo:dates>
		</pubinfo:pubinfo>

	</xsl:template>

</xsl:stylesheet>