<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:glp="http://www.lexis-nexis.com/glp" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:annot="http://www.lexisnexis.com/xmlschemas/content/shared/annotations/1/" xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/" version="2.0" exclude-result-prefixes="dita glp leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Comm-Form-Pre_leg.comntry3">
  <title><sourcexml>glp:note</sourcexml> as direct child of <sourcexml>leg:comntry/level</sourcexml> <lnpid>id-NZ09-24215</lnpid></title>
  <body>
    <section>
      <p>NL schema is not allowed <targetxml>note</targetxml> as direct child of <targetxml>annot:annotation</targetxml> and <targetxml>annot:annotationlevel</targetxml>. Please refer to below list for handling <sourcexml>glp:note</sourcexml> scenarios:
        <ul>
          <li><sourcexml>leg:comntry/level/glp:note</sourcexml> becomes <targetxml>primlaw:excerpt/primlaw:level/annot:annotations/annot:annotation-grp[@grptype="COMMENTARY"]/annot:annotation/bodytext/note</targetxml></li>
          <li><sourcexml>leg:comntry/level/level/glp:note</sourcexml> becomes <targetxml>primlaw:excerpt/primlaw:level/annot:annotations/annot:annotation-grp[@grptype="COMMENTARY"]/annot:annotation/annot:annotationlevel/annot:bodytext/note</targetxml></li>
        </ul>
      </p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-PAC\NZ09_Comm_Form_Prec_Text\Comm-Form-Pre_leg.comntry3.dita  -->
	<xsl:message>NZ09_Comm_Form_Prec_Text_Comm-Form-Pre_leg.comntry3.xsl requires manual development!</xsl:message> 

	<xsl:template match="glp:note">

		<!--  Original Target XPath:  note   -->
		<note>
			<xsl:apply-templates select="@* | node()"/>
		</note>

	</xsl:template>

	<xsl:template match="leg:comntry/level">

		<!--  Original Target XPath:  note   -->
		<note>
			<xsl:apply-templates select="@* | node()"/>
		</note>

	</xsl:template>

	<xsl:template match="leg:comntry/level/glp:note">

		<!--  Original Target XPath:  primlaw:excerpt/primlaw:level/annot:annotations/annot:annotation-grp[@grptype="COMMENTARY"]/annot:annotation/bodytext/note   -->
		<primlaw:excerpt>
			<primlaw:level>
				<annot:annotations>
					<annot:annotation-grp>
						<annot:annotation>
							<bodytext>
								<note>
									<xsl:apply-templates select="@* | node()"/>
								</note>
							</bodytext>
						</annot:annotation>
					</annot:annotation-grp>
				</annot:annotations>
			</primlaw:level>
		</primlaw:excerpt>

	</xsl:template>

	<xsl:template match="leg:comntry/level/level/glp:note">

		<!--  Original Target XPath:  primlaw:excerpt/primlaw:level/annot:annotations/annot:annotation-grp[@grptype="COMMENTARY"]/annot:annotation/annot:annotationlevel/annot:bodytext/note   -->
		<primlaw:excerpt>
			<primlaw:level>
				<annot:annotations>
					<annot:annotation-grp>
						<annot:annotation>
							<annot:annotationlevel>
								<annot:bodytext>
									<note>
										<xsl:apply-templates select="@* | node()"/>
									</note>
								</annot:bodytext>
							</annot:annotationlevel>
						</annot:annotation>
					</annot:annotation-grp>
				</annot:annotations>
			</primlaw:level>
		</primlaw:excerpt>

	</xsl:template>

</xsl:stylesheet>