<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="person">
  <title>person <lnpid>id-MY02-16224</lnpid></title>
  
<body>
    <p>
      <ul>
        <li><sourcexml>person</sourcexml> becomes <targetxml>person:person</targetxml> and attribute
                        <sourcexml>@searchtype="AUTHOR"</sourcexml> within
                        <sourcexml>person</sourcexml> becomes
                        <targetxml>@contributor-type="author"</targetxml> in
                        <targetxml>person:contributor</targetxml>
                </li>       
      </ul>     
    </p>    
    
<pre> 

&lt;jrnl:prelim&gt;   
    &lt;contrib&gt;        
        &lt;person searchtype="AUTHOR"&gt;&lt;name.text&gt;Andrew Stewart*&lt;/name.text&gt;&lt;/person&gt;        
    &lt;/contrib&gt;
&lt;/jrnl:prelim&gt;


<b>Becomes</b>


&lt;nitf:body.head&gt;
    &lt;nitf:byline&gt;
        &lt;person:contributor contributor-type="author"&gt; 
            &lt;person:person&gt;
                &lt;person:name.text&gt;Andrew Stewart*&lt;/person:name.text&gt;
            &lt;/person:person&gt;
        &lt;/person:contributor&gt;
&lt;/nitf:body.head&gt;

</pre>
    <section>
        <title>Changes</title>
        <p>2014-11-14: <ph id="change_20141114_PS">Change <targetxml>person:contributor/@contributor-type</targetxml> attribute value from Upper to lower case in the target.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY02_Journals\person.dita  -->
	<xsl:message>person.xsl requires manual development!</xsl:message> 

	<xsl:template match="person">

		<!--  Original Target XPath:  person:person   -->
		<person:person>
			<xsl:apply-templates select="@* | node()"/>
		</person:person>

	</xsl:template>

	<xsl:template match="@searchtype=&#34;AUTHOR&#34;">

		<!--  Original Target XPath:  @contributor-type="author"   -->
		<xsl:attribute name="contributor-type">
			<xsl:text>author</xsl:text>
		</xsl:attribute>

	</xsl:template>

</xsl:stylesheet>