<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:frm="http://www.lexis-nexis.com/glp/frm" 
	xmlns:leg="http://www.lexis-nexis.com/glp/leg"
	xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/"
	xmlns:annot="http://www.lexisnexis.com/xmlschemas/content/shared/annotations/1/"
	xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/"
	xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/"
	xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0"
	exclude-result-prefixes="dita frm leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
	    id="Rosetta_ci.cite-Chof-body-LxAdv-lnci.cite-normcite">
	    <title>ci:cite within the body of the document *:body  <lnpid>id-CCCC-10558</lnpid> </title>
	    <body>
	        <section>
	            <p> If <targetxml>lnci:cite</targetxml> is the child or descendent of
	                <targetxml>*:body</targetxml> (i.e.
	                <targetxml>courtcase:body//lnci:cite</targetxml>) and
	                <targetxml>lnci:cite</targetxml> converted without
	                <targetxml>@normcite</targetxml> attribute in NewLexis target conversion then
	                conversion needs to add/create this attribute
	                <b>'<targetxml>@normcite</targetxml>'</b> within
	                <targetxml>lnci:cite</targetxml>. <codeblock>
      Before attempting to create <targetxml>lnci:cite@normcite</targetxml>, these x-paths must exist:
      <targetxml>[lnci:case/lnci:caseref/lnci:reporter/@value]</targetxml>
      <targetxml>[lnci:case/lnci:caseref/lnci:volume/@num]</targetxml>
      <targetxml>[lnci:case/lnci:caseref/lnci:edition/lnci:date/@year]</targetxml>
      <targetxml>[lnci:case/lnci:caseref/lnci:pinpoint[targettype="page"]/@num]</targetxml> 
      And, this x-path cannot exist:  
      <targetxml>[lnci:case/lnci:caseref/lnci:page/@num]</targetxml>
    </codeblock>
	                <targetxml>@normcite</targetxml> attribute value should be generated from first
	                occcurances of below xpaths in same <targetxml>lnci:cite</targetxml> markup and
	                refer examples for better understanding:
	                <codeblock>
        <targetxml>lnci:case/lnci:caseref/lnci:edition/lnci:date/@year)[1]</targetxml> (i.e. (1957))
        <targetxml>lnci:case/lnci:caseref/lnci:volume/@num)[1]</targetxml> (i.e. 96)
        <targetxml>lnci:case/lnci:caseref/lnci:reporter/@value)[1]</targetxml> (i.e. ALR)
        <targetxml>lnci:case/lnci:caseref/lnci:pinpoint[targettype="page"]/@num)[1]</targetxml> (i.e. 171)
      </codeblock>
	            </p>
	        </section>
	        <example>
	            <title>Source: Generated lnci:cite without @normcite Attribute.</title>
	            <codeblock>
  <![CDATA[
<lnci:cite>
    <lnci:case>
        <lnci:caseinfo>
            <lnci:decisiondate year="1957"/>
        </lnci:caseinfo>
        <lnci:caseref ID="cr000019">
            <lnci:volume num="96"/>
        </lnci:caseref>
        <lnci:caseref ID="cr000020">
            <lnci:reporter value="ALR"/>
            <lnci:edition>
                <lnci:date year="1957"/>
            </lnci:edition>
        </lnci:caseref>
        <lnci:caseref anaphref="cr000020">
            <lnci:pinpoint num="171" targettype="page"/>
        </lnci:caseref>
    </lnci:case>
</lnci:cite>

          ]]>
          </codeblock>
	        </example>
	        <example>
	            <title>Target: Converted lnci:cite with @normcite Attribute.</title>
	            <codeblock>
          <![CDATA[
<lnci:cite normcite="(1957) 96 ALR 171">
    <lnci:case>
        <lnci:caseinfo>
            <lnci:decisiondate year="1957"/>
        </lnci:caseinfo>
        <lnci:caseref ID="cr000019">
            <lnci:volume num="96"/>
        </lnci:caseref>
        <lnci:caseref ID="cr000020">
            <lnci:reporter value="ALR"/>
            <lnci:edition>
                <lnci:date year="1957"/>
            </lnci:edition>
        </lnci:caseref>
        <lnci:caseref anaphref="cr000020">
            <lnci:pinpoint num="171" targettype="page"/>
        </lnci:caseref>
    </lnci:case>
</lnci:cite>
          ]]>
          </codeblock>
	        </example>
	        <section>
	            <title>Changes</title>
	            <p>2017-02-28: <ph id="change_20170228_RS">Instruction Added for lnci:cite and it's converted
	                <targetxml>@normcite</targetxml> in target. Webstar #5258288 and #6449604</ph>.</p>
	            
	        </section>
	    </body>
	    
	 </dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest/Rosetta_ci.cite-Chof-body-LxAdv-lnci.cite-normcite.dita -->
    <xsl:message>Rosetta_ci.cite-Chof-body-LxAdv-lnci.cite-normcite.xsl requires manual development!</xsl:message> 
	

	
	


	

</xsl:stylesheet>
