<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:proc="http://www.lexisnexis.com/xmlschemas/content/shared/process-elements/1/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_lnlink_service_TRAVERSE-LxAdv-ref.lnlink">
  <title><sourcexml>lnlink[@service="TRAVERSE"]</sourcexml> to
    <targetxml>ref:lnlink[@service="TRAVERSE"]</targetxml> <lnpid>id-CCCC-10528</lnpid></title>
  <body>
    <section>
      <p><sourcexml>lnlink[@service="TRAVERSE"]</sourcexml> becomes <targetxml>ref:lnlink[@service="TRAVERSE"]</targetxml>, 
           and its child elements are transformed as follows:
          <ul>
              <li>The attribute <sourcexml>lnlink/@status</sourcexml> is always suppressed, 
                it is never output to the target document.</li>
              <li><sourcexml>lnlink/marker</sourcexml> becomes <targetxml>ref:lnlink/ref:marker</targetxml>, 
                with attribute <sourcexml>marker/@role</sourcexml> becoming <targetxml>ref:marker/@role</targetxml> if present.</li>
              <li>Create <targetxml>ref:lnlink/ref:locator</targetxml> and populate as follows:<ul>
                  <li><sourcexml>key-name/@name</sourcexml>, if present, becomes 
                    <targetxml>ref:locator/ref:locator-key/ref:key-name/@name</targetxml>.</li>
                  <li><sourcexml>key-value/@value</sourcexml>, if present, becomes 
                    <targetxml>ref:locator/ref:locator-key/ref:key-value/@value</targetxml>.</li>
                  <li>Create <targetxml>ref:locator/ref:locator-params/proc:param[@name="normprotocol"]</targetxml>. If 
                    <sourcexml>lnlink/api-params/param[@name="normprotocol"]</sourcexml> exists, then the 
                    corresponding <sourcexml>param/@value</sourcexml> becomes <targetxml>proc:param/@value</targetxml>. 
                    Otherwise <targetxml>proc:param/@value</targetxml> is populated with "lexsee" (this value is
                    hard-coded when the source contains no normprotocol value).</li>             
                  <li><sourcexml>lnlink/api-params</sourcexml>, if present, becomes
                    <targetxml>ref:locator/ref:locator-params</targetxml>, and its child elements are
                    transformed as follows:<ul>
                       <li>all <sourcexml>api-params/param</sourcexml> elements become
                           <targetxml>ref:locator-params/proc:param</targetxml>, with attribute
                           <sourcexml>param/@name</sourcexml> becoming
                           <targetxml>proc:param/@name</targetxml> and attribute
                           <sourcexml>param/@value</sourcexml> becoming
                           <targetxml>proc:param/@value</targetxml>.</li>
                     </ul>
                   </li>
                </ul>
            </li>
          </ul>
      </p>
    </section>
    <example>
      <title>Source XML</title>
      <codeblock>

&lt;lnlink service="TRAVERSE"&gt;
	&lt;key-name name="normcite"/&gt;
	&lt;key-value value="LexisNexis Forms Form 219-8.22-7"/&gt;
	&lt;marker role="label"&gt;Notice of Commencement Of Case Under Chapter 11 of the Bankruptcy Code, Meeting of Creditors, and Deadlines--Chapter 11 Corporation/Partnership Case; Official Form 9F &lt;/marker&gt;
&lt;/lnlink&gt;
                
       </codeblock>
    </example>
    <example>
      <title>Target XML</title>
      <codeblock>

&lt;ref:lnlink service="TRAVERSE"&gt;
	&lt;ref:marker role="label"&gt;Notice of Commencement Of Case Under Chapter 11 of the Bankruptcy Code, Meeting of Creditors, and Deadlines--Chapter 11 Corporation/Partnership Case; Official Form 9F &lt;/ref:marker&gt;
	&lt;ref:locator&gt;
		&lt;ref:locator-key&gt;
			&lt;ref:key-name name="normcite"/&gt;
			&lt;ref:key-value value="LexisNexis Forms Form 219-8.22-7"/&gt;
		&lt;/ref:locator-key&gt;
		&lt;ref:locator-params&gt;
			&lt;proc:param name="normprotocol" value="lexsee"/&gt;
		&lt;/ref:locator-params&gt;
	&lt;/ref:locator&gt;
&lt;/ref:lnlink&gt;
                
      </codeblock>
    </example>
    <section>
      <title>Changes</title>
      <p>2015-09-03: <ph id="change_20150903_snb">Added topic for <sourcexml>lnlink[@service="TRAVERSE"]</sourcexml>.</ph></p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_lnlink_service_TRAVERSE-LxAdv-ref.lnlink.dita  -->
	<xsl:message>Rosetta_lnlink_service_TRAVERSE-LxAdv-ref.lnlink.xsl requires manual development!</xsl:message> 

	<xsl:template match="lnlink[@service=&#34;TRAVERSE&#34;]">

		<!--  Original Target XPath:  ref:lnlink[@service="TRAVERSE"]   -->
		<ref:lnlink>
			<xsl:apply-templates select="@* | node()"/>
		</ref:lnlink>

	</xsl:template>

	<xsl:template match="lnlink/@status">

		<!--  Original Target XPath:  ref:lnlink/ref:marker   -->
		<ref:lnlink>
			<ref:marker>
				<xsl:apply-templates select="@* | node()"/>
			</ref:marker>
		</ref:lnlink>

	</xsl:template>

	<xsl:template match="lnlink/marker">

		<!--  Original Target XPath:  ref:lnlink/ref:marker   -->
		<ref:lnlink>
			<ref:marker>
				<xsl:apply-templates select="@* | node()"/>
			</ref:marker>
		</ref:lnlink>

	</xsl:template>

	<xsl:template match="marker/@role">

		<!--  Original Target XPath:  ref:marker/@role   -->
		<ref:marker>
			<xsl:attribute name="role">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</ref:marker>

	</xsl:template>

	<xsl:template match="key-name/@name">

		<!--  Original Target XPath:  ref:locator/ref:locator-key/ref:key-name/@name   -->
		<ref:locator>
			<ref:locator-key>
				<ref:key-name>
					<xsl:attribute name="name">
						<xsl:apply-templates select="node()"/>
					</xsl:attribute>
				</ref:key-name>
			</ref:locator-key>
		</ref:locator>

	</xsl:template>

	<xsl:template match="key-value/@value">

		<!--  Original Target XPath:  ref:locator/ref:locator-key/ref:key-value/@value   -->
		<ref:locator>
			<ref:locator-key>
				<ref:key-value>
					<xsl:attribute name="value">
						<xsl:apply-templates select="node()"/>
					</xsl:attribute>
				</ref:key-value>
			</ref:locator-key>
		</ref:locator>

	</xsl:template>

	<xsl:template match="lnlink/api-params/param[@name=&#34;normprotocol&#34;]">

		<!--  Original Target XPath:  proc:param/@value   -->
		<proc:param>
			<xsl:attribute name="value">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</proc:param>

	</xsl:template>

	<xsl:template match="param/@value">

		<!--  Original Target XPath:  proc:param/@value   -->
		<proc:param>
			<xsl:attribute name="value">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</proc:param>

	</xsl:template>

	<xsl:template match="lnlink/api-params">

		<!--  Original Target XPath:  ref:locator/ref:locator-params   -->
		<ref:locator>
			<ref:locator-params>
				<xsl:apply-templates select="@* | node()"/>
			</ref:locator-params>
		</ref:locator>

	</xsl:template>

	<xsl:template match="api-params/param">

		<!--  Original Target XPath:  ref:locator-params/proc:param   -->
		<ref:locator-params>
			<proc:param>
				<xsl:apply-templates select="@* | node()"/>
			</proc:param>
		</ref:locator-params>

	</xsl:template>

	<xsl:template match="param/@name">

		<!--  Original Target XPath:  proc:param/@name   -->
		<proc:param>
			<xsl:attribute name="name">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</proc:param>

	</xsl:template>

</xsl:stylesheet>