<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:frm="http://www.lexis-nexis.com/glp/frm" xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/" version="2.0" exclude-result-prefixes="dita frm">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_frm.block-LxAdv-form.block">
	<title><sourcexml>frm:block</sourcexml> to <targetxml>form:block</targetxml> <lnpid>id-CCCC-10556</lnpid></title>
    <body>
      <section>
      	<p><sourcexml>frm:block</sourcexml> becomes <targetxml>form:block</targetxml>. 
      		<sourcexml>frm:block/@align</sourcexml> maps to <targetxml>form:block/@align</targetxml>, 
      		<sourcexml>frm:block/@valign</sourcexml> maps to <targetxml>form:block/@valign</targetxml>, and 
      		<sourcexml>frm:block/@block-type</sourcexml> maps to <targetxml>form:block/@blocktype</targetxml>. 
      		Children map as follows:
          <ul>
              <li><sourcexml>p</sourcexml> becomes
                <targetxml>form:p</targetxml></li>
            <li><sourcexml>p/text</sourcexml> becomes
            	<targetxml>form:p/form:text</targetxml></li>
          	<li><sourcexml>table</sourcexml> becomes
          		<targetxml>table</targetxml></li>
            <li><sourcexml>p/table</sourcexml> becomes
              <targetxml>table</targetxml>, i.e. suppress <sourcexml>p</sourcexml></li>
          </ul>
        </p>
      </section>

      <example>
        <title>Source sigblock</title>
        <codeblock>
          
&lt;frm:block block-type="notice-provision" align="right"&gt;
	&lt;p&gt;
		&lt;text&gt;Notices to Franchisor: Best Pizza Franchise, LLC&lt;/text&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;text&gt;123 Pizza Lane&lt;/text&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;text&gt;Springfield, DE, 123456&lt;/text&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;text&gt;Attn: &lt;frm:prompt prompttype="longname"&gt;[insert name]&lt;/frm:prompt&gt;
		&lt;/text&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;text&gt;Notices to Franchisee: &lt;frm:prompt prompttype="longname"&gt;[insert name]&lt;/frm:prompt&gt;
		&lt;/text&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;text&gt;
			&lt;frm:prompt prompttype="longname"&gt;[insert address]&lt;/frm:prompt&gt;
		&lt;/text&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;text&gt;
			&lt;frm:prompt prompttype="longname"&gt;[insert address]&lt;/frm:prompt&gt;
		&lt;/text&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;text&gt;Attn: &lt;frm:prompt prompttype="longname"&gt;[insert name]&lt;/frm:prompt&gt;
		&lt;/text&gt;
	&lt;/p&gt;
&lt;/frm:block&gt;

        </codeblock>
        
        <title>Target form:sigblock</title>
        <codeblock>
 
&lt;form:block blocktype="notice-provision" align="right"&gt;
	&lt;form:p&gt;
		&lt;form:text&gt;Notices to Franchisor: Best Pizza Franchise, LLC&lt;/form:text&gt;
	&lt;/form:p&gt;
	&lt;form:p&gt;
		&lt;form:text&gt;123 Pizza Lane&lt;/form:text&gt;
	&lt;/form:p&gt;
	&lt;form:p&gt;
		&lt;form:text&gt;Springfield, DE, 123456&lt;/form:text&gt;
	&lt;/form:p&gt;
	&lt;form:p&gt;
		&lt;form:text&gt;Attn: &lt;form:prompt formcharuse="longname"&gt;[insert name]&lt;/form:prompt&gt;
		&lt;/form:text&gt;
	&lt;/form:p&gt;
	&lt;form:p&gt;
		&lt;form:text&gt;Notices to Franchisee: &lt;form:prompt formcharuse="longname"&gt;[insert name]&lt;/form:prompt&gt;
		&lt;/form:text&gt;
	&lt;/form:p&gt;
	&lt;form:p&gt;
		&lt;form:text&gt;
			&lt;form:prompt formcharuse="longname"&gt;[insert address]&lt;/form:prompt&gt;
		&lt;/form:text&gt;
	&lt;/form:p&gt;
	&lt;form:p&gt;
		&lt;form:text&gt;
			&lt;form:prompt formcharuse="longname"&gt;[insert address]&lt;/form:prompt&gt;
		&lt;/form:text&gt;
	&lt;/form:p&gt;
	&lt;form:p&gt;
		&lt;form:text&gt;Attn: &lt;form:prompt formcharuse="longname"&gt;[insert name]&lt;/form:prompt&gt;
		&lt;/form:text&gt;
	&lt;/form:p&gt;
&lt;/form:block&gt;

        </codeblock>
      </example>
      
      <section>
            <title>Changes</title>
          <p>2017-02-07: <ph id="change_20170207_snb">LPA 2016 enhancements: New section. 
            Reflects new markup in precedents for notice provisions.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_frm.block-LxAdv-form.block.dita  -->
	<xsl:message>Rosetta_frm.block-LxAdv-form.block.xsl requires manual development!</xsl:message> 

	<xsl:template match="frm:block">

		<!--  Original Target XPath:  form:block   -->
		<form:block>
			<xsl:apply-templates select="@* | node()"/>
		</form:block>

	</xsl:template>

	<xsl:template match="frm:block/@align">

		<!--  Original Target XPath:  form:block/@align   -->
		<form:block>
			<xsl:attribute name="align">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</form:block>

	</xsl:template>

	<xsl:template match="frm:block/@valign">

		<!--  Original Target XPath:  form:block/@valign   -->
		<form:block>
			<xsl:attribute name="valign">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</form:block>

	</xsl:template>

	<xsl:template match="frm:block/@block-type">

		<!--  Original Target XPath:  form:block/@blocktype   -->
		<form:block>
			<xsl:attribute name="blocktype">
				<xsl:apply-templates select="node()"/>
			</xsl:attribute>
		</form:block>

	</xsl:template>

	<xsl:template match="p">

		<!--  Original Target XPath:  form:p   -->
		<form:p>
			<xsl:apply-templates select="@* | node()"/>
		</form:p>

	</xsl:template>

	<xsl:template match="p/text">

		<!--  Original Target XPath:  form:p/form:text   -->
		<form:p>
			<form:text>
				<xsl:apply-templates select="@* | node()"/>
			</form:text>
		</form:p>

	</xsl:template>

	<xsl:template match="table">

		<!--  Original Target XPath:  table   -->
		<table>
			<xsl:apply-templates select="@* | node()"/>
		</table>

	</xsl:template>

	<xsl:template match="p/table">

		<!--  Original Target XPath:  table   -->
		<table>
			<xsl:apply-templates select="@* | node()"/>
		</table>

	</xsl:template>

</xsl:stylesheet>