<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_Treatise_footnote-type-editorial-to-LexisAdvance-footnote">
  <title>footnote with @type="editorial" <lnpid>id-UK03-27461</lnpid></title>
  <body>
    <section><p>This section presents a special rule for handling value "editorial" in
          <sourcexml>footnote[@type]</sourcexml>.</p><p>For full conversion instructions on
        footnotes, see General Markup section.</p></section>
    <section><p><sourcexml>footnote[@type="editorial"]</sourcexml> becomes
          <targetxml>footnote</targetxml>. That is, suppress
          <sourcexml>[@type="editorial"]</sourcexml>.</p></section>


    <pre>
        <b>EXAMPLE</b>
            
<b><i>Source XML</i></b>

&lt;footnote type="editorial" fntoken="d30e36"&gt;
    &lt;fnlabel&gt;•&lt;/fnlabel&gt;
    &lt;fnbody&gt;
        &lt;p&gt;
            &lt;text&gt;The words used in the judgment, as reported, are...&lt;/text&gt;
        &lt;/p&gt;
    &lt;/fnbody&gt;
&lt;/footnote&gt;
 
<b><i>Target XML</i></b>

  &lt;footnote&gt;
    &lt;ref:anchor id="d30e36"/&gt;
    &lt;ref:returnreference&gt;
      &lt;ref:locator anchortype="local"/&gt;
    &lt;/ref:returnreference&gt;
    &lt;label&gt;•&lt;/label&gt;
    &lt;bodytext&gt;
      &lt;p&gt;
        &lt;text&gt;The words used in the judgment, as reported, are...&lt;/text&gt;
      &lt;/p&gt;
    &lt;/bodytext&gt;
  &lt;/footnote&gt;


                </pre>
    <section>
      <title>Changes</title>
      <p>2015-12-23: <ph id="change_20151223_ss">Create the instruction for suppressed the
            <sourcexml>@role</sourcexml> attribute in target
            [<sourcexml>footnote[@type="editorial"]</sourcexml></ph>.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK03_CaseDigest\Rosetta_Treatise_footnote-type-editorial-to-LexisAdvance-footnote.dita  -->
	<xsl:message>Rosetta_Treatise_footnote-type-editorial-to-LexisAdvance-footnote.xsl requires manual development!</xsl:message> 

	<xsl:template match="footnote[@type]">

		<!--  Original Target XPath:  footnote   -->
		<footnote>
			<xsl:apply-templates select="@* | node()"/>
		</footnote>

	</xsl:template>

	<xsl:template match="footnote[@type=&#34;editorial&#34;]">

		<!--  Original Target XPath:  footnote   -->
		<footnote>
			<xsl:apply-templates select="@* | node()"/>
		</footnote>

	</xsl:template>

	<xsl:template match="[@type=&#34;editorial&#34;]">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="@role">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>