<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:dig="http://www.lexis-nexis.com/glp/dig" xmlns:casedigest="http://www.lexisnexis.com/xmlschemas/content/legal/case-digest/1/" version="2.0" exclude-result-prefixes="dita dig">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_dig.injury-duration-to-LexisAdvance_casedigest.injury-textitem">
  <title>dig:injury-duration-to-casedigest:injury/textitem <lnpid>id-UK03-27447</lnpid></title>
  <body>
    <section>
      <p>
        <sourcexml>dig:cause-of-action/dig:action-facts/dig:injury-duration</sourcexml> becomes 
        <targetxml>casedigest:facts/casedigest:causeofaction/casedigest:injury/textitem/duration</targetxml>.
      </p>      
    </section>
<pre>
&lt;DIGESTDOC&gt;
  &lt;dig:body&gt;
    &lt;dig:cause-of-action&gt;
      &lt;dig:action-facts display-name="Duration and Prognosis"&gt;
        &lt;dig:injury-duration&gt;Claimant sustained serious head injuries and would continue to
          be affected by psychiatric symptoms on a permanent basis. He was also left with
          permanent nerve damage in his shoulder, although this would not overly affect
          his day-to-day activities.
        &lt;/dig:injury-duration&gt;
      &lt;/dig:action-facts&gt;
    &lt;/dig:cause-of-action&gt;
  &lt;/dig:body&gt;    
&lt;/DIGESTDOC&gt;

<b>Becomes</b>
&lt;casedigest:casedigest&gt;
  &lt;casedigest:body&gt;
    &lt;casedigest:facts&gt;
      &lt;casedigest:causeofaction&gt;
        &lt;casedigest:injury&gt;
          &lt;textitem&gt;
              &lt;duration&gt;Claimant sustained serious head injuries and would continue to
                  be affected by psychiatric symptoms on a permanent basis. He was also left with
                  permanent nerve damage in his shoulder, although this would not overly affect
                  his day-to-day activities.
              &lt;/duration&gt;
          &lt;/textitem&gt;
        &lt;/casedigest:injury&gt;
      &lt;/casedigest:causeofaction&gt;
    &lt;/casedigest:facts&gt;
  &lt;/casedigest:body&gt;  
&lt;/casedigest:casedigest&gt;
</pre>                
    <section>
      <title>Changes</title>
      <p>2017-04-19: <ph id="change_20170419_CN">Added multiple paragraphs to "Facts" example.
        [VSTS - 243138]</ph>
      </p>
      <p>2016-03-08: <ph id="change_20160308_SS">Remove the change request number
          [DADB2012101213525400] inside the CI because this CR have already updated inside the target
          schema for <targetxml>duration</targetxml> allowing within
          <targetxml>textitem</targetxml>.</ph></p>
    </section>             
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK03_CaseDigest\Rosetta_dig.injury-duration-to-LexisAdvance_casedigest.injury-textitem.dita  -->
<!--	<xsl:message>Rosetta_dig.injury-duration-to-LexisAdvance_casedigest.injury-textitem.xsl requires manual development!</xsl:message> 

	<xsl:template match="dig:cause-of-action/dig:action-facts/dig:injury-duration">

		<!-\-  Original Target XPath:  casedigest:facts/casedigest:causeofaction/casedigest:injury/textitem/duration   -\->
		<casedigest:facts>
			<casedigest:causeofaction>
				<casedigest:injury>
					<textitem>
						<duration>
							<xsl:apply-templates select="@* | node()"/>
						</duration>
					</textitem>
				</casedigest:injury>
			</casedigest:causeofaction>
		</casedigest:facts>

	</xsl:template>-->
  
  <!-- Vikas Rohilla : Template to mtch the dig:injury-duration-->
  <xsl:template match="dig:injury-duration">
    <casedigest:injuryduration>
      <duration>
        <xsl:apply-templates select="@* | node()"/>
      </duration>
    </casedigest:injuryduration>
  </xsl:template>
  

</xsl:stylesheet>