<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:case="http://www.lexis-nexis.com/glp/case" xmlns:courtcase="http://www.lexisnexis.com/xmlschemas/content/legal/courtcase/1/" version="2.0" exclude-result-prefixes="dita case">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_case.judgment-LxAdv_courtcase.opinion">
    <title>case:judgment <lnpid>id-CCCC-12041</lnpid></title>
    <body>
        <section id="mapping">
            <p><sourcexml>case:judgment</sourcexml> becomes <targetxml>courtcase:opinion</targetxml>.</p>
        </section>
      <section id="changes">
        <title>Common Changes</title>
      </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_caselaw\conref_content\Rosetta_case.judgment-LxAdv_courtcase.opinion.dita  -->
	<xsl:message>Rosetta_case.judgment-LxAdv_courtcase.opinion.xsl requires manual development!</xsl:message> 

	<xsl:template match="case:judgment">

		<!--  Original Target XPath:  courtcase:opinion   -->
		<courtcase:opinion>
			<xsl:apply-templates select="@* | node()"/>
		</courtcase:opinion>

	</xsl:template>

</xsl:stylesheet>