<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_CA_admindecisions_docinfo.custom.metafields">
    <title><sourcexml>docinfo:custom-metafields</sourcexml> to <targetxml>doc:legacy-metadata[@metadatasource="lbu-meta"]</targetxml> <lnpid>id-CA04-13438</lnpid></title>
    <body>
        <section>
            <p><sourcexml>docinfo:custom-metafields</sourcexml> should be omitted and its children should be handled as follows: <ul>
                    <li><sourcexml>docinfo:custom-metafield[@searchtype = "CITED-COUNT"]</sourcexml> maps to
                            <targetxml>doc:legacy-metadata[@metadatasource="lbu-meta"]/meta/metaitem</targetxml> with its attributes populated as
                        follows: <ul>
                            <li>Place "CITED-COUNT" in <targetxml>metaitem/@name</targetxml>.</li>
                            <li>Place the content of <sourcexml>docinfo:custom-metafield[@searchtype = "CITED-COUNT"]</sourcexml> in
                                    <targetxml>metaitem/@value</targetxml></li>
                        </ul>
                    </li>
                    <li>All other <sourcexml>docinfo:custom-metafield</sourcexml> elements (where <sourcexml>@searchtype</sourcexml> does <b>not</b>
                        have a value of "CITED-COUNT") should be suppressed.</li>
                </ul></p>
            <p>If <sourcexml>docinfo:custom-metafields</sourcexml> does <b>not</b> have <sourcexml>docinfo:custom-metafield[@searchtype =
                    "CITED-COUNT"]</sourcexml> as a child, then <sourcexml>docinfo:custom-metafields</sourcexml> and all its children should be
                suppressed.</p>
        </section>

        <example>
            <title>Source XML (<sourcexml>docinfo:custom-metafields</sourcexml> with <sourcexml>docinfo:custom-metafield[@searchtype =
                    "CITED-COUNT"]</sourcexml> as a child)</title>
            <codeblock>

&lt;docinfo:custom-metafields&gt;
    &lt;docinfo:custom-metafield name="date"&gt;20010417&lt;/docinfo:custom-metafield&gt;
    &lt;docinfo:custom-metafield name="country"&gt;1&lt;/docinfo:custom-metafield&gt;
    &lt;docinfo:custom-metafield name="juris"&gt;20&lt;/docinfo:custom-metafield&gt;
    &lt;docinfo:custom-metafield name="court"&gt;135&lt;/docinfo:custom-metafield&gt;
    &lt;docinfo:custom-metafield searchtype="COURT-CLASSIFY"&gt;ABEnvAppBd&lt;/docinfo:custom-metafield&gt;
    &lt;docinfo:custom-metafield searchtype="JURIS-CLASSIFY"&gt;AB&lt;/docinfo:custom-metafield&gt;
    &lt;docinfo:custom-metafield searchtype="CITED-COUNT"&gt;0&lt;/docinfo:custom-metafield&gt;
&lt;/docinfo:custom-metafields&gt;

            </codeblock>
            <title>Target XML (<sourcexml>docinfo:custom-metafields</sourcexml> has <sourcexml>docinfo:custom-metafield[@searchtype =
                    "CITED-COUNT"]</sourcexml> as a child)</title>
            <codeblock>

&lt;doc:legacy-metadata metadatasource="lbu-meta"&gt;
    &lt;meta&gt;
        ...
        &lt;metaitem name="CITED-COUNT" value="0"/&gt;
        ...
    &lt;/meta&gt;
&lt;/doc:legacy-metadata&gt;

            </codeblock>
        </example>

        <example>
            <title>Source XML (<sourcexml>docinfo:custom-metafields</sourcexml>
                <b>without</b>
                <sourcexml>docinfo:custom-metafield[@searchtype = "CITED-COUNT"]</sourcexml> as a child)</title>
            <codeblock>

&lt;docinfo:custom-metafields&gt;
    &lt;docinfo:custom-metafield name="COURT-CLASSIFY"&gt;ABEnvAppBd&lt;/docinfo:custom-metafield&gt;
&lt;/docinfo:custom-metafields&gt;

            </codeblock>
            <p>The above elements should be dropped.</p>
        </example>        
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA04-Administrative_Decisions\Rosetta_CA-admindecisions_docinfo.custom-metafields.dita  -->
	<xsl:message>Rosetta_CA-admindecisions_docinfo.custom-metafields.xsl requires manual development!</xsl:message> 

	<xsl:template match="docinfo:custom-metafields">

		<!--  Original Target XPath:  doc:legacy-metadata[@metadatasource="lbu-meta"]   -->
		<doc:legacy-metadata>
			<xsl:apply-templates select="@* | node()"/>
		</doc:legacy-metadata>

	</xsl:template>

	<xsl:template match="docinfo:custom-metafield[@searchtype = &#34;CITED-COUNT&#34;]">

		<!--  Original Target XPath:  doc:legacy-metadata[@metadatasource="lbu-meta"]/meta/metaitem   -->
		<doc:legacy-metadata>
			<meta>
				<metaitem>
					<xsl:apply-templates select="@* | node()"/>
				</metaitem>
			</meta>
		</doc:legacy-metadata>

	</xsl:template>

	<xsl:template match="docinfo:custom-metafield">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="@searchtype">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="docinfo:custom-metafield[@searchtype =&#xA;                    &#34;CITED-COUNT&#34;]">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>