<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="ST11_Commentary_form">
  <title><sourcexml>form</sourcexml> <lnpid>id-ST11-37812</lnpid></title>
  <body>
    <section>
      <p><sourcexml>form</sourcexml> becomes <targetxml>form:form</targetxml> and children described as below:
        <ul>
          <li>Create <targetxml>form:document</targetxml> with <targetxml>[@annotated="false"]</targetxml>, <targetxml>[@official="false"]</targetxml> and <targetxml>[@typeofdoc="unnamed"]</targetxml>. All these attributes are required in <targetxml>form:document</targetxml>. Attribute <targetxml>@annotated</targetxml> and <targetxml>@official</targetxml> have boolean value. Attribute <targetxml>@typeofdoc</targetxml> have tokenized value.</li>
          <li><sourcexml>bodytext</sourcexml> becomes <targetxml>form:bodytext</targetxml>.</li>
          <li><sourcexml>p</sourcexml> becomes <targetxml>form:p</targetxml>.</li>
          <li><sourcexml>text</sourcexml> becomes <targetxml>form:text</targetxml></li>
          <li><sourcexml>l</sourcexml> becomes <targetxml>form:list</targetxml></li>
        </ul>
      </p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Seclaw\ST11_Commentary_form.dita  -->
	<xsl:message>ST11_Commentary_form.xsl requires manual development!</xsl:message> 

	<xsl:template match="form">

		<!--  Original Target XPath:  form:form   -->
		<form:form>
			<xsl:apply-templates select="@* | node()"/>
		</form:form>

	</xsl:template>

	<xsl:template match="bodytext">

		<!--  Original Target XPath:  form:bodytext   -->
		<form:bodytext>
			<xsl:apply-templates select="@* | node()"/>
		</form:bodytext>

	</xsl:template>

	<xsl:template match="p">

		<!--  Original Target XPath:  form:p   -->
		<form:p>
			<xsl:apply-templates select="@* | node()"/>
		</form:p>

	</xsl:template>

	<xsl:template match="text">

		<!--  Original Target XPath:  form:text   -->
		<form:text>
			<xsl:apply-templates select="@* | node()"/>
		</form:text>

	</xsl:template>

	<xsl:template match="l">

		<!--  Original Target XPath:  form:list   -->
		<form:list>
			<xsl:apply-templates select="@* | node()"/>
		</form:list>

	</xsl:template>

</xsl:stylesheet>