<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="ST11_Commentary_level4-target">
  <title>Target XML</title>
  <body>
    <codeblock>

&lt;seclaw:level xml:id="HLA_5.1" leveltype="unclassified" includeintoc="false"&gt;
 &lt;ref:anchor id="HLA_5" anchortype="global"/&gt;
 &lt;heading&gt;
  &lt;desig&gt;5 &amp;#x2014;&lt;/desig&gt;
  &lt;title&gt;Aboriginals and Torres Strait Islanders&lt;/title&gt;
 &lt;/heading&gt;
 &lt;seclaw:prelim xml:id="PRELIM_5" alternatetoccaption="About this Title" includeintoc="false"&gt;
  &lt;pubfm:narrative narrativetype="prelim"&gt;
   &lt;pgrp&gt;
    &lt;heading&gt;&lt;title&gt;Contributors&lt;/title&gt;&lt;/heading&gt;
    &lt;p&gt;&lt;text&gt;Dr H A Amankwah BA LLB&amp;#x0028;UGhana&amp;#x0029; LLM&amp;#x0028;Cornell&amp;#x0029; SJD&amp;#x0028;NYU&amp;#x0029;&lt;/text&gt;&lt;/p&gt;
    &lt;!-- ETC. --&gt;
   &lt;/pgrp&gt;
  &lt;/pubfm:narrative&gt;
 &lt;/seclaw:prelim&gt;
 &lt;seclaw:bodytext/&gt;&lt;!-- &lt;targetxml&gt;seclaw:bodytext&lt;/targetxml&gt; is required element in &lt;targetxml&gt;seclaw:level&lt;/targetxml&gt;. --&gt;
&lt;/seclaw:level&gt;
    </codeblock>
    <note><targetxml>seclaw:bodytext</targetxml> is required element in <targetxml>seclaw:level</targetxml>.</note>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-Standard\Seclaw\ST11_Commentary_level4-target.dita  -->
	<xsl:message>ST11_Commentary_level4-target.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>