<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK01_Rosetta_remotelink-service-query">
  <title>remotelink @service="QUERY" <lnpid>id-UK01-27041</lnpid></title>
  <shortdesc>This is a special rule for <sourcexml>remotelink</sourcexml> with
      <sourcexml>@service="QUERY"</sourcexml>. This rule supersedes the General Markup instruction
    to entirely suppress "QUERY" links.</shortdesc>
  <body>
    <section><title>Special Rule</title>
      <p>Convert the pcdata of <sourcexml>remotelink[@service="QUERY"]</sourcexml>. Suppress the
          <sourcexml>remotelink</sourcexml> tag and its attributes. The
          <sourcexml>remotelink</sourcexml> always occurs within an element where pcdata is
        allowed.</p>
    </section>
    <note>Later iterations of rosetta data may use ci:cite or other markup instead of these "QUERY"
      links. In the meantime, this special rule captures the pcdata.</note>
    <pre>
              <b><i>Example: Source XML 1</i></b>


&lt;p&gt;
    &lt;text&gt;Consultation Paper: The Award of Costs from Central Funds in Criminal
        Cases - &lt;remotelink service="QUERY"
            remotekey1="DIGEST-CITATION(LNB News 06/11/2008 25)"
            remotekey2="All Subscribed Current Awareness Sources" cmd="f:exp"
            alttext="References to"&gt;LNB News 06/11/2008 25&lt;/remotelink&gt;; &lt;/text&gt;
&lt;/p&gt;

    </pre>
    <pre>
              <b><i>Example: Target XML 1</i></b>


&lt;p&gt;
    &lt;text&gt;Consultation Paper: The Award of Costs from Central Funds in Criminal
        Cases - LNB News 06/11/2008 25; &lt;/text&gt;
&lt;/p&gt;

    </pre>
    <section>
      <title>Changes</title>
      <p>2013-06-05: <ph id="change_20130605_jm"><sourcexml>remotelink[@service="QUERY"]</sourcexml>
          - Created special rule to capture pcdata</ph>.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK01_CaseLaw\UK01_Rosetta_remotelink-service-query.dita  -->
	<xsl:message>UK01_Rosetta_remotelink-service-query.xsl requires manual development!</xsl:message> 

	<xsl:template match="remotelink">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="@service=&#34;QUERY&#34;">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="remotelink[@service=&#34;QUERY&#34;]">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>