<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:frm="http://www.lexis-nexis.com/glp/frm" 
	xmlns:leg="http://www.lexis-nexis.com/glp/leg"
	xmlns:person="http://www.lexisnexis.com/xmlschemas/content/shared/person/1/"
	xmlns:annot="http://www.lexisnexis.com/xmlschemas/content/shared/annotations/1/"
	xmlns:form="http://www.lexisnexis.com/xmlschemas/content/shared/form/1/"
	xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/"
	xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" version="2.0"
	exclude-result-prefixes="dita frm leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
		id="UK03_ci.cite-ChOf-ci.content">
		<title>ci:cite within ci:content <lnpid>id-UK03-27464</lnpid> </title>
		<body>
			<section><p><b>Use case:</b>
				<sourcexml>ci:cite</sourcexml> wrapped in inappropriate
				<sourcexml>ci:cite/ci:content</sourcexml>. <b>Summary of Action:</b> suppress
				wrapping tags and convert remaining content according to usual rules.</p></section>
			<section><p>Applies when the xpath <sourcexml>ci:cite/ci:content/ci:cite</sourcexml> occurs.
				Suppress the parent <sourcexml>ci:cite/ci:content</sourcexml> and process content.
				Content may include pcdata along with one/more <sourcexml>ci:cite</sourcexml>. The
				use case occurs in places where target can accommodate pcdata and
				<targetxml>lnci:cite</targetxml>.</p></section>
			
			<pre>
<b>Source XML</b>
                  
<![CDATA[

     <case:parallelcite>
       <ci:cite>
         <ci:content>
           <ci:cite searchtype="CASE-REF">
              <ci:case>
                 <ci:caseref>
                     <ci:reporter value="ALLERD"/>
                       <ci:volume num="06"/>
                         <ci:edition>
                             <ci:date year="2008"/>
                         </ci:edition>
                     <ci:page num="380"/>
                  </ci:caseref>
               </ci:case>
               <ci:content>[2008] All ER (D) 380 (Jun)</ci:content>
            </ci:cite>
          </ci:content>
       </ci:cite>
     </case:parallelcite>
 
]]> 
	</pre>
			<pre>
                    
<b>Target XML</b>
<![CDATA[
    <ref:citations>
         <ref:parallelcite>
                <lnci:cite>
                    <lnci:case>
                        <lnci:caseref>
                            <lnci:reporter value="ALLERD" />
                            <lnci:volume num="06" />
                            <lnci:edition>
                                <lnci:date year="2008" />
                            </lnci:edition>
                            <lnci:page num="380" />
                        </lnci:caseref>
                    </lnci:case>
                    <lnci:content>[2008] All ER (D) 380 (Jun)</lnci:content>
               </lnci:cite>
         </ref:parallelcite>
     </ref:citations> 
]]>
                </pre>
			<section>
				<title>Changes</title>
				<p>2017-02-23: <ph id="change_20170223_RS">Created 
					<sourcexml>ci:cite/ci:content</sourcexml> with child
					<sourcexml>ci:cite</sourcexml>.</ph></p>
			</section>
		</body>
		
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK/UK03_CaseDigest/UK03_ci.cite-ChOf-ci.content.dita -->
	<xsl:message>UK03_ci.cite-ChOf-ci.content.xsl requires manual development!</xsl:message> 
	

	
	


	

</xsl:stylesheet>
