<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK06_LawsActsBillsMeasures-leg.levelinfo-source">
  <title>Source XML</title>
  <body>
    <codeblock>

&lt;leg:levelinfo&gt;
 &lt;classification classscheme="analysis-type"&gt;
  &lt;classitem&gt;
   &lt;classitem-identifier&gt;
    &lt;classname&gt;non-halsbury&lt;/classname&gt;
   &lt;/classitem-identifier&gt;
  &lt;/classitem&gt;
 &lt;/classification&gt;
 &lt;leg:aboutreference&gt;
  &lt;ci:cite searchtype="LEG-REF" normcite="UK_ACTS 2006 46"/&gt;
 &lt;/leg:aboutreference&gt;
&lt;/leg:levelinfo&gt;

    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK06-LawsActsBillsMeasures\UK06_LawsActsBillsMeasures-leg.levelinfo-source.dita  -->
	<xsl:message>UK06_LawsActsBillsMeasures-leg.levelinfo-source.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>