<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK06_LawsActsBillsMeasures-leg.effdate-target3">
  <title>Target XML 3 : <sourcexml>leg:dates/leg:effdate</sourcexml> occurs <b>after</b>
    <sourcexml>leg:longtitle</sourcexml></title>
  <body>
    <codeblock>

&lt;legis:head&gt;
  &lt;!-- ETC. --&gt;
&lt;/legis:head&gt;
&lt;legis:body&gt;
 &lt;!-- ETC. --&gt;
 &lt;primlaw:prelim&gt;
  &lt;primlaw:synopsis&gt;
   &lt;bodytext&gt;
    &lt;p&gt;&lt;text&gt;&lt;emph typestyle="it"&gt;AN ACT TO establish...&lt;/emph&gt;&lt;/text&gt;&lt;/p&gt;
   &lt;/bodytext&gt;
  &lt;/primlaw:synopsis&gt;
  &lt;primlawinfo:primlawinfo&gt;
   &lt;primlawinfo:dates&gt;
    &lt;primlawinfo:enactdate&gt;date day="18" month="03" year="2010" normdate="2010-03-18"&gt;Passed on &lt;date-text&gt;3rd April 2010&lt;/date-text&gt;&lt;/primlawinfo.enactdate&gt;
   &lt;/primlawinfo.dates&gt;
  &lt;/primlawinfo:primlawinfo&gt;
  &lt;p&gt;&lt;text&gt;&lt;proc:nl/&gt;BE IT ENACTED by the Queen's most Excellent Majesty...&lt;/text&gt;&lt;/p&gt;
 &lt;/primlaw:prelim&gt;
&lt;/legis:body&gt;

    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK06-LawsActsBillsMeasures\UK06_LawsActsBillsMeasures-leg.effdate-target3.dita  -->
	<xsl:message>UK06_LawsActsBillsMeasures-leg.effdate-target3.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:dates/leg:effdate">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

	<xsl:template match="leg:longtitle">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>