<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK06_LawsActsBillsMeasures-leg.officialnum1-target">
  <title>Target XML</title>
  <body>
    <codeblock>

&lt;legis:body&gt;
 &lt;primlaw:level leveltype="unclassified"&gt;
  &lt;primlaw:levelinfo&gt;
   &lt;primlawinfo:primlawinfo&gt;
    &lt;legisinfo:legisinfo&gt;
     &lt;!-- ETC. --&gt;
     &lt;primlawhist:primlawhist&gt;
      &lt;primlawhist:histgrp&gt;
       &lt;primlawhist:histitem&gt;
        &lt;bodytext&gt;
         &lt;p&gt;&lt;text&gt;This Act was repealed as follows: ss 1, 5, Schs 1, 4 repealed by the Customs and Excise Act 1952, s 320, Sch 12, Pt I; ss 2&amp;#x2013;4, Schs 2, 3 repealed by the Finance &amp;#x0028;No 2&amp;#x0029; Act 1947, s 9, Sch 6; s 6, Sch 5 repealed by the 
         &lt;lnci:cite type="legislation" status="valid"&gt;
          &lt;lnci:sesslaw&gt;
           &lt;lnci:sesslawinfo&gt;
            &lt;lnci:sesslawnum num="1952_33a"/&gt;
            &lt;lnci:hierpinpoint&gt;
             &lt;lnci:hierlev label="section" num="76"/&gt;
            &lt;/lnci:hierpinpoint&gt;
           &lt;/lnci:sesslawinfo&gt;
           &lt;lnci:sesslawref&gt;
            &lt;lnci:standardname normpubcode="UK_ACTS"/&gt;
           &lt;/lnci:sesslawref&gt;
          &lt;/lnci:sesslaw&gt;
          &lt;lnci:content&gt;Finance Act 1952, s 76&amp;#x0028;8&amp;#x0029;&lt;/lnci:content&gt;
         &lt;/lnci:cite&gt;, 
         &lt;!-- ETC. --&gt;
        &lt;/text&gt;
       &lt;/p&gt;
      &lt;/bodytext&gt;
     &lt;/primlawhist:histitem&gt;
    &lt;/primlawhist:histgrp&gt;
   &lt;/primlawhist:primlawhist&gt;
  &lt;/legisinfo:legisinfo&gt;
  &lt;primlawinfo:identifier idtype="officialnum"&gt;
   &lt;primlawinfo:identifier-component type="year"&gt;1943&lt;/primlawinfo:identifier-component&gt; CHAPTER
   &lt;primlawinfo:identifier-component type="seriesnum"&gt;28&lt;/primlawinfo:identifier-component&gt;
  &lt;/primlawinfo:identifier&gt;
 &lt;/primlawinfo:primlawinfo&gt;
 &lt;/primlaw:levelinfo&gt;
&lt;/primlaw:level&gt;
 &lt;!-- ETC. --&gt;
&lt;/legis:body&gt;
    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK06-LawsActsBillsMeasures\UK06_LawsActsBillsMeasures-leg.officialnum1-target.dita  -->
	<xsl:message>UK06_LawsActsBillsMeasures-leg.officialnum1-target.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>