<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK06_LawsActsBillsMeasures-leg.status-source2">
  <title>Source XML 2: Handling of Multiple leg:status</title>
  <body>
    <codeblock>

&lt;leg:body&gt;
 &lt;leg:info subseqdoc="false"&gt;
  &lt;!-- ETC. --&gt;
  &lt;leg:status&gt;&lt;nl/&gt;And whereas the Board have acquired and are now managing and carrying on the said undertakings and are supplying water within an area which comprises the whole of the administrative county of London and parts of the counties of Middlesex Surrey Kent Essex and Hertford:&lt;/leg:status&gt;
  &lt;leg:status&gt;&lt;nl/&gt;And whereas it is provided by the Act of 1902 that the Board shall within three years after the appointed day referred to in that Act (namely the twenty-fourth day of June one thousand nine hundred and four) introduce into Parliament a Bill providing for uniform scales of charges applicable throughout their limits of supply:&lt;/leg:status&gt;
  &lt;leg:status&gt;&lt;nl/&gt;And whereas it is expedient to provide for such uniform scales of charges and that the provisions contained in this Act relating to the supply of water should be made:&lt;/leg:status&gt;
  &lt;leg:status&gt;&lt;nl/&gt;And whereas the purposes of this Act cannot be effected without the authority of Parliament:&lt;/leg:status&gt;
  &lt;leg:status&gt;&lt;nl/&gt;May it therefore please Your Majesty that it may be enacted and be it enacted by the King's most Excellent Majesty by and with the advice and consent of the Lords Spiritual and Temporal and Commons in this present Parliament assembled and by the authority of the same as follows (that is to say):&amp;#x2014;&lt;/leg:status&gt;
  &lt;!-- ETC. --&gt;
 &lt;/leg:info&gt;
 &lt;!-- ETC. --&gt;
&lt;/leg:body&gt;

    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK06-LawsActsBillsMeasures\UK06_LawsActsBillsMeasures-leg.status-source2.dita  -->
	<xsl:message>UK06_LawsActsBillsMeasures-leg.status-source2.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>