<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK06_LawsActsBillsMeasures-leg.level-source">
  <title>Source XML</title>
  <body>
    <codeblock>

&lt;leg:body&gt;
 &lt;leg:level&gt;
  &lt;leg:level-vrnt leveltype="sched"&gt;
   &lt;leg:levelbody&gt;
    &lt;leg:level&gt;
     &lt;leg:level-vrnt leveltype="prov1"&gt;
      &lt;leg:levelbody&gt;
       &lt;leg:bodytext&gt;
        &lt;leg:heading align="left" searchtype="LEGISLATION"&gt;
         &lt;desig inline="true" searchtype="PROV-NUM"&gt;
          &lt;designum&gt;&lt;emph typestyle="bf"/&gt;&lt;/designum&gt;
         &lt;/desig&gt;
         &lt;title searchtype="PROV-TITLE"&gt;&lt;emph typestyle="bf"&gt;Distresses of the Exchequer. The owner may feed his cattle impounded. Sale of distress. No distress shall be taken of ploughing cattle, or sheep. Distress shall be reasonable.&lt;/emph&gt;&lt;/title&gt;
        &lt;/leg:heading&gt;
       &lt;/leg:bodytext&gt;
       &lt;leg:level&gt;
        &lt;leg:level-vrnt leveltype="prov2" searchtype="LEGISLATION"&gt;
         &lt;leg:levelbody&gt;
          &lt;leg:bodytext searchtype="LEGISLATION"&gt;
           &lt;!-- ETC. --&gt;
          &lt;/leg:bodytext&gt;
         &lt;/leg:levelbody&gt;
        &lt;/leg:level-vrnt&gt;
       &lt;/leg:level&gt;
       &lt;leg:comntry searchtype="ANNOTATIONS"&gt;
        &lt;level leveltype="comm30"&gt;
         &lt;bodytext&gt;
          &lt;heading searchtype="ANNOTATIONS"&gt;
           &lt;title&gt;&lt;emph typestyle="bf"&gt;NOTES&lt;/emph&gt;&lt;/title&gt;
          &lt;/heading&gt;
         &lt;/bodytext&gt;
         &lt;level leveltype="comm32"&gt;
          &lt;heading searchtype="ANNOTATIONS"&gt;
           &lt;title&gt;&lt;emph typestyle="bf"&gt;Amendment&lt;/emph&gt;&lt;/title&gt;
          &lt;/heading&gt;
          &lt;bodytext&gt;
           &lt;!-- ETC. --&gt;
          &lt;/bodytext&gt;
         &lt;/level&gt;
        &lt;/level&gt;
       &lt;/leg:comntry&gt;
      &lt;/leg:levelbody&gt;
     &lt;/leg:level-vrnt&gt;
    &lt;/leg:level&gt;
   &lt;/leg:levelbody&gt;
  &lt;/leg:level-vrnt&gt;
 &lt;/leg:level&gt;
&lt;/leg:body&gt;

    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK06-LawsActsBillsMeasures\UK06_LawsActsBillsMeasures-leg.level-source.dita  -->
	<xsl:message>UK06_LawsActsBillsMeasures-leg.level-source.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>