<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK06_LawsActsBillsMeasures-leg.comntry-source5">
 <title>Source XML 5 : <sourcexml>leg:comntry/bodytext/form</sourcexml></title>
  <body>
    <codeblock>

&lt;leg:comntry&gt;
 &lt;bodytext&gt;
  &lt;form&gt;
   &lt;frm:body&gt;
    &lt;!-- ETC. --&gt;
    &lt;p&gt;&lt;text&gt;**     &lt;emph typestyle="it"&gt;Variations in this and subsequent forms to be made, if required, for leasehold land, &amp;#x005B;or for giving effect to special arrangements&amp;#x005D;&lt;/emph&gt;.&lt;sup&gt;1a&lt;/sup&gt;&lt;/text&gt;&lt;/p&gt;
   &lt;/frm:body&gt;
  &lt;/form&gt;
 &lt;/bodytext&gt;
&lt;/leg:comntry&gt;

    </codeblock>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK06-LawsActsBillsMeasures\UK06_LawsActsBillsMeasures-leg.comntry-source5.dita  -->
	<xsl:message>UK06_LawsActsBillsMeasures-leg.comntry-source5.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:comntry/bodytext/form">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>