<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK12_Treatise_footnote-type-editorial">
  <title>footnote with @type="editorial" <lnpid>id-UK12-29813</lnpid></title>
  <body>
    <section><p>This section presents a special rule for handling value "editorial" in
          <sourcexml>footnote[@type]</sourcexml>.</p><p>For full conversion instructions on
        footnotes, see General Markup section.</p></section>
    <section><p><sourcexml>footnote[@type="editorial"]</sourcexml> becomes
          <targetxml>footnote</targetxml>. That is, suppress
          <sourcexml>[@type="editorial"]</sourcexml>.</p></section>


    <pre>
        <b>EXAMPLE</b>
            
<b><i>Source XML</i></b>

  &lt;footnote type="editorial"
      fntoken="37355F62636C735F62696E6465725F30335F63745F303030375F31_1"
      fnrtokens="37355F62636C735F62696E6465725F30335F63745F303030375F31_REF_1"&gt;
      &lt;fnlabel&gt;1&lt;/fnlabel&gt;
      &lt;fnbody&gt;
        &lt;p&gt;
          &lt;text&gt;See Code Committee Response...&lt;/text&gt;
        &lt;/p&gt;
      &lt;/fnbody&gt;
  &lt;/footnote&gt;
 
<b><i>Target XML</i></b>

  &lt;footnote&gt;
    &lt;ref:anchor id="37355F62636C735F62696E6465725F30335F63745F303030375F31_1"/&gt;
    &lt;ref:returnreference&gt;
      &lt;ref:locator 
          anchoridref="37355F62636C735F62696E6465725F30335F63745F303030375F31_REF_1" 
          anchortype="local"/&gt;
    &lt;/ref:returnreference&gt;
    &lt;label&gt;1&lt;/label&gt;
    &lt;bodytext&gt;
      &lt;p&gt;
        &lt;text&gt;See Code Committee Response...&lt;/text&gt;
      &lt;/p&gt;
    &lt;/bodytext&gt;
  &lt;/footnote&gt;


                </pre>
    <section>
      <title>Changes</title>
      <p>2013-07-12: <ph id="change_20130712_jm">Added section with special rule for
            <sourcexml>footnote[@type="editorial"]</sourcexml></ph>.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK12-Treatise\UK12_Treatise_footnote-type-editorial.dita  -->
<!--	<xsl:message>UK12_Treatise_footnote-type-editorial.xsl requires manual development!</xsl:message> -->

	<xsl:template match="footnote[@type]">

		<!--  Original Target XPath:  footnote   -->
		<footnote>
			<xsl:apply-templates select="@* | node()"/>
		</footnote>

	</xsl:template>

	<xsl:template match="footnote[@type=&#34;editorial&#34;]">

		<!--  Original Target XPath:  footnote   -->
		<footnote>
			<xsl:apply-templates select="@* | node()"/>
		</footnote>

	</xsl:template>

	<xsl:template match="[@type=&#34;editorial&#34;]">

		<!--  Original Target XPath:     -->
		<!--  Could not determine target element or attribute name:  <>  -->			<xsl:apply-templates select="@* | node()"/>
		<!--  Could not determine target element or attribute name:  </>  -->

	</xsl:template>

</xsl:stylesheet>