<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:cttr="urn:x-lexisnexis:content:citator:sharedservices:1" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="LegislativeCitator_Introduction">
  <title>Introduction <lnpid>id-UK16-38613</lnpid></title>
  <prolog><metadata><prodinfo>
    <prodname>UK16 Rosetta CITATORDOC-to-LexisAdvance cttr:citator</prodname>
    <vrmlist>
      <vrm version=""/>
    </vrmlist>
  </prodinfo></metadata></prolog>
  <body>
    <p>This Conversion Instruction describes the conversion of Citator schema in the document.</p>
    
    <p>UK LegislativeCitator Citator documents are identified using the root element
        <sourcexml>CITATORDOC</sourcexml>, the value of
        <sourcexml>docinfo:doc-country/@iso-cc="GB"</sourcexml> and the value of
        <sourcexml>docinfo:selector</sourcexml> should be "LegislativeCitator" or
      "StatutoryInstrumentCitator".</p>
    
    <p>The root element <sourcexml>CITATORDOC</sourcexml> becomes <targetxml>cttr:citator</targetxml>. </p>
    
    <p>
      <targetxml>cttr:body</targetxml> and <targetxml>doc:metadata</targetxml> are created as required children of
      <targetxml>cttr:citator</targetxml>. <targetxml>cttr:head</targetxml> is an optional child of <targetxml>cttr:citator</targetxml>. 
      The source attributes are described below:
    </p>   
    
    
    <pre>
&lt;CITATORDOC&gt;
<b>Becomes</b>
&lt;cttr:citator&gt;
  &lt;cttr:head&gt;...&lt;/cttr:head&gt;
  &lt;cttr:body&gt;...&lt;/cttr:body&gt;
  &lt;doc:metadata&gt;...&lt;/doc:metadata&gt;
&lt;/cttr:citator&gt;
</pre>
    
    
    
    <section>
      <title>Note:</title>
      <p>Source elements and attributes are highlighted in BLUE like this: <sourcexml>XML
        SOURCE</sourcexml></p>
      <p>Target elements and attributes are highlighted in GREEN like this: <targetxml>XML
        TARGET</targetxml></p>
      <p>COPY SOURCE ATTRIBUTES TO TARGET ATTRIBUTES UNLESS OTHERWISE SPECIFIED.</p>
      <p>Every example is represented like "EXAMPLE" in all the dita's and is
        coming under <pre> pre </pre> tag.</p>      
    </section> 
    
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK16_LegislativeCitator\Introduction.dita  -->
	<xsl:message>UK16_LegislativeCitator_Introduction.xsl requires manual development!</xsl:message> 

	<xsl:template match="CITATORDOC">

		<!--  Original Target XPath:  cttr:citator   -->
		<cttr:citator>
			<xsl:apply-templates select="@* | node()"/>
		</cttr:citator>

	</xsl:template>

	<xsl:template match="docinfo:doc-country/@iso-cc=&#34;GB&#34;">

		<!--  Original Target XPath:  cttr:citator   -->
		<cttr:citator>
			<xsl:apply-templates select="@* | node()"/>
		</cttr:citator>

	</xsl:template>

	<xsl:template match="docinfo:selector">

		<!--  Original Target XPath:  cttr:citator   -->
		<cttr:citator>
			<xsl:apply-templates select="@* | node()"/>
		</cttr:citator>

	</xsl:template>

	<xsl:template match="XML&#xA;        SOURCE">

		<!--  Original Target XPath:  XMLTARGET   -->
		<XMLTARGET>
			<xsl:apply-templates select="@* | node()"/>
		</XMLTARGET>

	</xsl:template>

</xsl:stylesheet>