<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/" xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK17WEBINAR_DIGESTDOC_selfCite">
  <title>Document Heading &amp; Self-Citation <lnpid>id-UK17-30610</lnpid></title>
  <body>
    <p>Every output document should have a way to be cited. This is accomplished using <targetxml>seclaw:head/ref:citations/ref:cite4thisresource</targetxml>. However, not every document is citable. In this case, it is not. Hence, &lt;ref:nonciteidentifier&gt; is used:</p>
    <p>Inside <targetxml>seclaw:head</targetxml> output <targetxml>ref:citations/ref:cite4thisresource/ref:nonciteidentifier[@normprotocol='unspecified']</targetxml> with text value derived from <targetxml>normalize-space(/DIGESTDOC/docinfo/docinfo:doc-heading)</targetxml>.</p>
    <example>
      <title>Source XML</title>
      <codeblock>...
&lt;docinfo:doc-heading&gt;Test video (Vimeo)  &lt;/docinfo:doc-heading&gt;
...           </codeblock>
      <title>Target XML</title>
      <codeblock>&lt;seclaw:head&gt;
   &lt;ref:citations&gt;
      &lt;ref:cite4thisresource&gt;
         &lt;ref:nonciteidentifier normprotocol="unspecified"&gt;Test video (Vimeo)&lt;/ref:nonciteidentifier&gt;
      &lt;/ref:cite4thisresource&gt;
   &lt;/ref:citations&gt;
&lt;/seclaw:head&gt;           </codeblock>
    </example>
    <section>
      <title>Changes</title>
      <p/>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK17-CLE_materials\UK17WEBINAR_DIGESTDOC_heading.dita  -->
	<xsl:message>UK17WEBINAR_DIGESTDOC_heading.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>