<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK17_Webinar_Introduction">
  <title>Introduction <lnpid>id-UK17-30612</lnpid></title>

  <body>
    <p>These instructions describe the conversion of Webinar documents from the Rosetta DIGESTDOC DTD to the NewLexis Seclaw Schema.</p>
    <section>
      <title>General Notes</title>
      <p>Source elements and attributes are highlighted like this: <sourcexml>XML
        SOURCE</sourcexml></p>
      <p>Target elements and attributes are highlighted like this: <targetxml>XML
        TARGET</targetxml></p>
      <p>Namespace declarations have been omitted from examples to conserve space.</p>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK17-CLE_materials\UK17WEBINAR_DIGESTDOC_introduction.dita  -->
	<xsl:message>UK17WEBINAR_DIGESTDOC_introduction.xsl requires manual development!</xsl:message> 

	<xsl:template match="XML&#xA;        SOURCE">

		<!--  Original Target XPath:  XMLTARGET   -->
		<XMLTARGET>
			<xsl:apply-templates select="@* | node()"/>
		</XMLTARGET>

	</xsl:template>

</xsl:stylesheet>