<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="UK17_WEBINAR_namespaces">
  <title>Namespaces <lnpid>id-UK17-30615</lnpid></title>
  <body>
    <section>
      <title>Target Namespaces</title>
      <ul>
        <li>xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"</li>
        <li>xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/"</li>
        <li>xmlns:ref="http://www.lexisnexis.com/xmlschemas/content/shared/reference/1/"</li>
        <li>xmlns:guid="urn:x-lexisnexis:content:guid:global:1"</li>
        <li>xmlns:jurisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/jurisdiction-info/1/"</li>
        <li>xmlns:globalentity="urn:x-lexisnexis:content:identified-entities:global:1"</li>
        <li>xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"</li>
        <li>xmlns:lnci="http://www.lexisnexis.com/xmlschemas/content/shared/citations/1/"</li>
        <li>xmlns:classify="http://www.lexisnexis.com/xmlschemas/content/shared/classification/1/"</li>
        <li>xmlns:proc="http://www.lexisnexis.com/xmlschemas/content/shared/process-elements/1/"</li>
        <li>xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/"</li>
        <li>xmlns:lnmeta="http://www.lexisnexis.com/xmlschemas/content/shared/lexisnexis-metadata/1/"</li>
        <li>xmlns:ci="http://www.lexis-nexis.com/ci"</li>
        <li>xmlns:dc="http://purl.org/dc/elements/1.1/"</li>
      </ul>
    </section>
    <section>
      <title>Source Namespaces</title>
      <ul>
        <li>xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"</li>
        <li>xmlns:ci="http://www.lexis-nexis.com/ci"</li>
        <li>xmlns:dig="http://www.lexis-nexis.com/glp/dig"</li>
      </ul>
    </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK17-CLE_materials\UK17_Webinar_namespaces.dita  -->
	<xsl:message>UK17_Webinar_namespaces.xsl requires manual development!</xsl:message> 

</xsl:stylesheet>