<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" version="2.0" exclude-result-prefixes="dita">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legis-leg.preamble">
 <title>leg:preamble <lnpid>id-UK22CS-36418</lnpid></title>
 <body>
  <section>
   <p><sourcexml>/COMMENTARYDOC/comm:body/level/bodytext/legfragment/leg:preamble</sourcexml>
    becomes
     <targetxml>/seclaw:seclaw/seclaw:body/seclaw:level/seclaw:bodytext/primlaw:excerpt/primlaw:level</targetxml>
    with attribute <targetxml>@leveltype="preamble"</targetxml>.</p>
  </section>
  <example>
   <codeblock>

&lt;leg:preamble&gt;
        &lt;leg:bodytext&gt;
            &lt;p&gt;
                &lt;text&gt;A draft of this Order was laid before the House of Commons in accordance with section 173(7) of the Finance Act 2006 and approved by a resolution of that House.&lt;/text&gt;
            &lt;/p&gt;
            &lt;p&gt;
                &lt;text&gt;Accordingly, Her Majesty, in exercise of the powers conferred upon Her by section 173(1) of the Finance Act 2006, by and with the advice of Her Privy Council, orders as follows—&lt;/text&gt;
            &lt;/p&gt;
        &lt;/leg:bodytext&gt;
    &lt;/leg:preamble&gt;

   </codeblock>
   <b>Becomes</b>
   <codeblock>

&lt;primlaw:level leveltype="preamble"&gt;
        &lt;primlaw:bodytext&gt;
            &lt;p&gt;
                &lt;text&gt;A draft of this Order was laid before the House of Commons in accordance with section 173(7) of the Finance Act 2006 and approved by a resolution of that House.&lt;/text&gt;
            &lt;/p&gt;
            &lt;p&gt;
                &lt;text&gt;Accordingly, Her Majesty, in exercise of the powers conferred upon Her by section 173(1) of the Finance Act 2006, by and with the advice of Her Privy Council, orders as follows—&lt;/text&gt;
            &lt;/p&gt;
        &lt;/primlaw:bodytext&gt;
    &lt;/primlaw:level&gt;

   </codeblock></example>
  <section>
   <title>Changes</title>
   <p>2015-10-13: <ph id="change_20151013_HP">Created</ph></p>
  </section>
 </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK22CS\legis-leg.preamble.dita  -->
	<xsl:message>UK22CS_legis-leg.preamble.xsl requires manual development!</xsl:message> 

	<xsl:template match="/COMMENTARYDOC/comm:body/level/bodytext/legfragment/leg:preamble">

		<!--  Original Target XPath:  /seclaw:seclaw/seclaw:body/seclaw:level/seclaw:bodytext/primlaw:excerpt/primlaw:level   -->
		<seclaw:seclaw xmlns:seclaw="http://www.lexisnexis.com/xmlschemas/content/legal/secondary-law/1/">
			<seclaw:body>
				<seclaw:level>
					<seclaw:bodytext>
						<primlaw:excerpt xmlns:primlaw="http://www.lexisnexis.com/xmlschemas/content/legal/primarylaw/1/">
							<primlaw:level>
								<xsl:apply-templates select="@* | node()"/>
							</primlaw:level>
						</primlaw:excerpt>
					</seclaw:bodytext>
				</seclaw:level>
			</seclaw:body>
		</seclaw:seclaw>

	</xsl:template>

</xsl:stylesheet>