<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:leg="http://www.lexis-nexis.com/glp/leg" xmlns:legisinfo="http://www.lexisnexis.com/xmlschemas/content/legal/legislation-info/1/" version="2.0" exclude-result-prefixes="dita leg">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="legis-leg.officialname">
  <title>leg:officialname <lnpid>id-UK22CS-36416</lnpid></title>
  <body>
   <section>
       <p><sourcexml>leg:officialname</sourcexml> becomes
                    <targetxml>/legisinfo:legisinfo/legisinfo:names/legisinfo:officialtitle[@source="editoriallyassigned"]</targetxml>
                <note>If <sourcexml>emph</sourcexml> occurs within
                        <sourcexml>leg:officialname</sourcexml> with the attribute's value
                        <sourcexml>emph/@typestyle="it"</sourcexml> or
                        <sourcexml>emph/@typestyle="un"</sourcexml> will be retained and all other
                        <sourcexml>emph</sourcexml> will be omitted from the NL conversion.</note>
                <note>For handling <b>@ln.user-displayed</b> attribute, refer the general markup
                        <xref href="../../common_newest/Rosetta_leg.officialnum_ln.user-displayed-LxAdv-primlawinfo.identifier_source.dita">ln.user_displayed="false"</xref> section in the CI.</note>
            </p>
   </section>
   <example>
            <codeblock>

&lt;leg:info&gt;
        &lt;leg:officialnum&gt;SI 1955/156 &lt;leg:year&gt;1955 &lt;/leg:year&gt;
            &lt;leg:seriesnum&gt;156 &lt;/leg:seriesnum&gt;
        &lt;/leg:officialnum&gt;
        &lt;leg:officialname&gt;Consular Conventions (Income Tax) (Kingdom of Norway) Order 1955 &lt;/leg:officialname&gt;
        &lt;leg:dates&gt;
            &lt;leg:enactdate&gt;Made &lt;date day="01" month="02" year="1955"&gt;1 February 1955 &lt;/date&gt;
            &lt;/leg:enactdate&gt;
        &lt;/leg:dates&gt;
    &lt;/leg:info&gt;

    </codeblock>
            <b>Becomes</b>
            <codeblock>
&lt;primlaw:levelinfo&gt;
        &lt;primlawinfo:primlawinfo&gt;
            &lt;primlawinfo:identifier idtype="officialnum"&gt;SI 1955/156
                &lt;primlawinfo:identifier-component type="1955"&gt;1955&lt;/primlawinfo:identifier-component&gt;
                &lt;primlawinfo:identifier-component type="156"&gt;156&lt;/primlawinfo:identifier-component&gt;
            &lt;/primlawinfo:identifier&gt;
            &lt;legisinfo:legisinfo&gt;
                &lt;legisinfo:names&gt;
                    &lt;legisinfo:officialtitle source="editoriallyassigned"
                        &gt;Consular Conventions (Income Tax) (Kingdom of Norway)
                        Order 1955 &lt;/legisinfo:officialtitle&gt;
                &lt;/legisinfo:names&gt;
            &lt;/legisinfo:legisinfo&gt;
            &lt;primlawinfo:dates&gt;
                &lt;primlawinfo:enactdate day="01" month="02" year="1955"&gt;Made
                    &lt;date-text&gt;1 February 1955 &lt;/date-text&gt;
                &lt;/primlawinfo:enactdate&gt;
            &lt;/primlawinfo:dates&gt;
        &lt;/primlawinfo:primlawinfo&gt;
    &lt;/primlaw:levelinfo&gt;
    </codeblock>
        </example>
   <section>
    <title>Changes</title>
       <p>2016-02-22: <ph id="change_20160222_HP">Added a instruction for handling input scenario
           <sourcexml>leg:officialname</sourcexml> to
           <targetxml>legisinfo:officialtitle[@source="editoriallyassigned"]</targetxml>. [<b>RFA
               #2760</b>]</ph></p>
    <p>2015-10-08: <ph id="change_20151008_HP">Created</ph></p>
   </section>
  </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-UK\UK22CS\legis-leg.officialname.dita  -->
	<xsl:message>UK22CS_legis-leg.officialname.xsl requires manual development!</xsl:message> 

	<xsl:template match="leg:officialname">

		<!--  Original Target XPath:  /legisinfo:legisinfo/legisinfo:names/legisinfo:officialtitle[@source="editoriallyassigned"]   -->
		<legisinfo:legisinfo>
			<legisinfo:names>
				<legisinfo:officialtitle>
					<xsl:apply-templates select="@* | node()"/>
				</legisinfo:officialtitle>
			</legisinfo:names>
		</legisinfo:legisinfo>

	</xsl:template>

	<xsl:template match="emph">

		<!--  Original Target XPath:  legisinfo:officialtitle[@source="editoriallyassigned"]   -->
		<legisinfo:officialtitle>
			<xsl:apply-templates select="@* | node()"/>
		</legisinfo:officialtitle>

	</xsl:template>

	<xsl:template match="emph/@typestyle=&#34;it&#34;">

		<!--  Original Target XPath:  legisinfo:officialtitle[@source="editoriallyassigned"]   -->
		<legisinfo:officialtitle>
			<xsl:apply-templates select="@* | node()"/>
		</legisinfo:officialtitle>

	</xsl:template>

	<xsl:template match="emph/@typestyle=&#34;un&#34;">

		<!--  Original Target XPath:  legisinfo:officialtitle[@source="editoriallyassigned"]   -->
		<legisinfo:officialtitle>
			<xsl:apply-templates select="@* | node()"/>
		</legisinfo:officialtitle>

	</xsl:template>

</xsl:stylesheet>