<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet	version="2.0" 
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
    
    xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"
    
    xmlns:classify="http://www.lexisnexis.com/xmlschemas/content/shared/classification/1/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/"
    xmlns:lnmeta="http://www.lexisnexis.com/xmlschemas/content/shared/lexisnexis-metadata/1/"
    
    exclude-result-prefixes="dita docinfo">
    
    <dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_docinfo.doc-id-to-LexisAdvance_dcidentifier_lnmetaidentifier-scheme">
        <title><sourcexml>docinfo:doc-id</sourcexml> to
            <targetxml>dc:identifier[@lnmeta:identifier-scheme]</targetxml>
            <lnpid>id-CCCC-10550</lnpid></title>
        <body>
            <section>
                <title>Instructions <i>[common element]</i></title>
                <p>Identifies the normalization scheme (e.g. URI, LNI, ISSN, et al.) used for the
                    identifier. <sourcexml>docinfo:doc-id</sourcexml> becomes
                    <targetxml>dc:metadata/dc:identifier[@lnmeta:identifier-scheme]</targetxml>.
                    Capture dpsi value from the LBU manifest file and prepend the value, followed by
                    hyphen, to create globally unique identifier.  </p>
                <p>Also create new element
                    <targetxml>dc:metadata/dc:source[@lnmeta:sourcescheme]</targetxml> which
                    contains ONLY the DPSI value from the manifest file.</p>
            </section>
            
            <example>
                <title>Source XML - Example with Manifest File</title>
                <codeblock>
                    
                    &lt;docinfo:doc-id&gt;5B323030395D2D312D41432E3131&lt;/docinfo:doc-id&gt;
                    
                </codeblock>
            </example>
            
            <example>
                <title>Target XML - Example with Manifest File</title>
                <codeblock>
                    
                    &lt;dc:identifier lnmeta:identifier-scheme="DOC-ID"&gt;0GNE-5B323030395D2D312D41432E3131&lt;/dc:identifier&gt;
                    ......
                    &lt;dc:source lnmeta:sourcescheme="DataProductSourceIdentifier"&gt;0GNE&lt;/dc:identifier&gt;
                    
                </codeblock>
            </example>
            
            <note>In the above example <b>0GNE</b> is the dpsi value, which will be captured from LBU
                manifest file.</note>
            
            <section>
                <title>Changes</title>
                <p>2016-08-03: <ph id="change_20160803_AS">Created the rule to, Check manifest file for
                    DPSI value and create new element
                    <targetxml>dc:metadata/dc:source[@lnmeta:sourcescheme]</targetxml></ph></p>
            </section>
        </body>
    </dita:topic>
    
    <!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
    <!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_PAC_docinfo.doc-id-LxAdv-dcidentifier_lnmetaidentifier-scheme.dita  -->
    
    <!-- 20170516:  MCJ:  This is turned into a do-nothing module... assuming that the handling of doc-id to dc:identifier is already handled elsewhere. -->
    
    <xsl:template match="docinfo:doc-id"/>
    
</xsl:stylesheet>