<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="docinfo.subtype">
    <title>docinfo:subtype <lnpid>id-CA02DS-12834</lnpid></title>
   <body>
      <section>
<ul>
         <li class="- topic/li ">
          <sourcexml class="+ topic/keyword xml-d/sourcexml ">docinfo:subtype</sourcexml> becomes
            <targetxml>doc:legacy-metadata/meta/metaitem</targetxml> with attributes
            <targetxml>@name="docinfo:subtype"</targetxml> and <targetxml>@value</targetxml> will
          keep the data from the <sourcexml>docinfo:subtype</sourcexml>.<pre xml:space="preserve" class="- topic/pre ">

&lt;docinfo:subtype&gt;card&lt;/docinfo:subtype&gt;

                    </pre>
          <b class="+ topic/ph hi-d/b ">Not Targeted yet</b>
          <pre xml:space="preserve" class="- topic/pre ">
&lt;doc:legacy-metadata metadatasource="lbu-meta"&gt;
         &lt;meta&gt;
              &lt;metaitem name="docinfo:subtype" value="card"/&gt;
         &lt;/meta&gt;
&lt;/doc:legacy-metadata&gt;    

               </pre>
        </li>
    
      </ul>
</section>
   </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA02-Case_Summaries\CA02DS_DIGESTDOC_to_seclaw\docinfo.subtype.dita  -->
	 
  <!-- Vikas Rohilla : Templtate to match the docinfo:subtype create the metaitem-->
	<xsl:template match="docinfo:subtype">
				<metaitem>
					<xsl:apply-templates select="@* | node()"/>
				</metaitem>
	</xsl:template>

</xsl:stylesheet>