<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns="http://www.lexisnexis.com/xmlschemas/content/shared/base/1/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="CA10_docinfo.custom-metafield-QLDBGRP-to-pubinfo.aggregationname">
    <title><sourcexml>docinfo:custom-metafield[@name="QLDBGRP"]</sourcexml> to
            <targetxml>pubinfo:aggregationname</targetxml>
        <lnpid>id-CA10-14620</lnpid></title>
    <body>
        <section><p><b>Note: This is a special rule for CA10 Treatise-Textbook-Forms. Specific for
                    the value <sourcexml>"QLDBGRP"</sourcexml>, as described
            below.</b></p></section>
        <section><p><sourcexml>docinfo:custom-metafields/docinfo:custom-metafield[@name="QLDBGRP"]</sourcexml>
                becomes
                <targetxml>doc:metadata/pubinfo:pubinfo/pubinfo:aggregationname</targetxml>.</p></section>
        <note>The attribute <sourcexml>@name="QLDBGRP"</sourcexml> is used only to identify the
            data. The attribute and value do not convert.</note>

        <example>
            <title>Source XML</title>
            <codeblock>

&lt;docinfo:custom-metafields&gt;
  &lt;docinfo:custom-metafield name="QLDBGRP"&gt;Halsbury's Laws of Canada&lt;/docinfo:custom-metafield&gt;
&lt;/docinfo:custom-metafields&gt;

	</codeblock>
        </example>
        <example>
            <title>Target XML</title>
            <codeblock>

&lt;doc:metadata&gt;
    &lt;pubinfo:pubinfo&gt;
        &lt;pubinfo:aggregationname&gt;Halsbury's Laws of Canada&lt;/pubinfo:aggregationname&gt;
    &lt;/pubinfo:pubinfo&gt;
&lt;/doc:metadata&gt;

	</codeblock>
        </example>
        <section><title>Changes</title>
            <p>2014-08-13: <ph id="change_20140813_jm">New rule. Maps new source data
                        <sourcexml>docinfo:custom-metafield[@name="QLDBGRP"]</sourcexml> to new
                    target <targetxml>pubinfo:aggregationname</targetxml>. Specific for CA10. R4.5 Content Issue
                    1725.</ph></p></section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-CAN\CA10-Treatise_Textbook_Forms\CA10_docinfo.custom-metafield-QLDBGRP-to-pubinfo.aggregationname.dita  -->
	<!--<xsl:message>CA10_docinfo.custom-metafield-QLDBGRP-to-pubinfo.aggregationname.xsl requires manual development!</xsl:message> -->

	<xsl:template match="docinfo:custom-metafields/docinfo:custom-metafield[@name='QLDBGRP']" mode="head">

		<!--  Original Target XPath:  pubinfo:aggregationname   -->
		<!-- apply this template inside pubinfo body -->
		<pubinfo:aggregationname>
			<xsl:value-of select="normalize-space(.)"/>
		</pubinfo:aggregationname>

	</xsl:template>

	<xsl:template match="docinfo:custom-metafields/docinfo:custom-metafield/@name"/>
	
	<xsl:template match="docinfo:custom-metafield[@name='QLDBGRP']">
		<metaitem>
			<xsl:attribute name="name">QLDBGRP</xsl:attribute>
			<xsl:attribute name="value">
				<xsl:value-of select="normalize-space(.)"/>
			</xsl:attribute>
		</metaitem>
	</xsl:template>

</xsl:stylesheet>