<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" xmlns:pubinfo="http://www.lexisnexis.com/xmlschemas/content/shared/publication-info/1/" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="docinfo.topiccode-pubinfo.pubdate">
    <title><sourcexml>docinfo:topiccode</sourcexml> to <targetxml>pubinfo:pubdate</targetxml> <lnpid>id-CN01-15210</lnpid></title>
    <body>
        <section>
            <title>Instructions</title>
            <p><sourcexml>docinfo/docinfo:topiccodes/docinfo:topiccode[@scheme="source-by-date"]</sourcexml> becomes
                <targetxml>doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate</targetxml>.</p>
        </section>

        <example>
            <title>Source XML</title>
            <codeblock>

&lt;docinfo&gt;
..........
&lt;docinfo:topiccodes&gt;
    &lt;docinfo:topiccode scheme="source-by-date"&gt;2006-08-27&lt;/docinfo:topiccode&gt;
&lt;/docinfo:topiccodes&gt;
&lt;/docinfo&gt;

	</codeblock>
        </example>

        <example>
            <title>Target XML</title>
            <codeblock>

&lt;doc:metadata&gt;
    &lt;pubinfo:pubinfo&gt;
         &lt;pubinfo:dates&gt;
            &lt;pubinfo:pubdate year="2006" day="27" month="08"&gt;2006-08-27&lt;/pubinfo:pubdate&gt;
         &lt;/pubinfo:dates&gt;
      &lt;/pubinfo:pubinfo&gt;
&lt;/doc:metadata&gt;

	</codeblock>
        </example> 
      </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-GPL\CN01-Legislation\docinfo.topiccode-pubinfo.pubdate.dita  -->
	<xsl:message>docinfo.topiccode-pubinfo.pubdate.xsl requires manual development!</xsl:message> 

	<xsl:template match="docinfo:topiccode">

		<!--  Original Target XPath:  pubinfo:pubdate   -->
		<pubinfo:pubdate>
			<xsl:apply-templates select="@* | node()"/>
		</pubinfo:pubdate>

	</xsl:template>

	<xsl:template match="docinfo/docinfo:topiccodes/docinfo:topiccode[@scheme=&#34;source-by-date&#34;]">

		<!--  Original Target XPath:  doc:metadata/pubinfo:pubinfo/pubinfo:dates/pubinfo:pubdate   -->
		<doc:metadata>
			<pubinfo:pubinfo>
				<pubinfo:dates>
					<pubinfo:pubdate>
						<xsl:apply-templates select="@* | node()"/>
					</pubinfo:pubdate>
				</pubinfo:dates>
			</pubinfo:pubinfo>
		</doc:metadata>

	</xsl:template>

</xsl:stylesheet>