<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:doc="http://www.lexisnexis.com/xmlschemas/content/shared/document-level-metadata/1/" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="doc.docinfo_doc-content-country">
    <title><sourcexml>docinfo:doc-country[@iso-cc]</sourcexml> to
            <targetxml>doc:docinfo[@doc-content-country]</targetxml>
        <lnpid>id-IN04-38807</lnpid></title>
    <body>
        <section>
            <title>Instructions <i>[common element]</i></title>
            <p><sourcexml>docinfo:doc-country[@iso-cc]</sourcexml> becomes
                    <targetxml>doc:docinfo[@doc-content-country]</targetxml>.
                        <note><targetxml>@doc-content-country</targetxml> is required.</note>
                <note><sourcexml>docinfo:doc-country[@iso-cc]</sourcexml> is used to specify the
                    country in the source document and also becomes part of
                        <targetxml>@xml:id</targetxml> as described in the instructions for <xref href="../../common_newest/Rosetta_docinfo.doc-lang-and-doc-country-LxAdv-ROOT_xml.lang.dita">Target <targetxml>@xml:lang</targetxml></xref>.</note>
            </p>
        </section>
        
        <example>
            <title>Source XML</title>
            <codeblock>
&lt;docinfo&gt;
    ....
    &lt;docinfo:doc-country iso-cc="IN"/&gt;
    ....
&lt;/docinfo&gt;


	</codeblock>
        </example>
        
        <example>
            <title>Target XML</title>
            <codeblock>
&lt;doc:docinfo doc-content-country="IN"&gt;
         ...
&lt;/doc:docinfo&gt;

	</codeblock>
        </example>  
        <section>
            <title>Changes</title>
             <p>2016-08-18: <ph id="change_20160818_SS">Created.</ph></p>
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-IN\IN04-Citator\doc.docinfo_doc-content-country.dita  -->
	<xsl:message>IN04-Citator_doc.docinfo_doc-content-country.xsl requires manual development!</xsl:message> 

	<xsl:template match="docinfo:doc-country[@iso-cc]">

		<!--  Original Target XPath:  doc:docinfo[@doc-content-country]   -->
		<doc:docinfo>
			<xsl:apply-templates select="@* | node()"/>
		</doc:docinfo>

	</xsl:template>

</xsl:stylesheet>