<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="GPL_IN01_Rosetta_docinfo.ipowner">
    <title>docinfo:ipowner <lnpid>id-MY01-16032</lnpid></title>
    <body>
        <section>
            <p>Suppressed <sourcexml>docinfo:ipowner</sourcexml> from target mapping.</p>
<codeblock>

       &lt;docinfo:ipowner ipowner="India" trackid="IN0IT2"/&gt;

</codeblock>
            <p>becomes</p>
<codeblock>

         &lt;!-- Suppressed from target --&gt;

</codeblock>
            
        </section>
    </body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated.  Remove this comment after manual development complete! @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\DITA-MY\MY01_Cases\MY01_Rosetta_docinfo.ipowner.dita  -->
<!--	<xsl:message>MY01_Rosetta_docinfo.ipowner.xsl requires manual development!</xsl:message> -->

	<xsl:template match="docinfo:ipowner"/>


</xsl:stylesheet>