<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:dita="http://dita.oasis-open.org/architecture/2005/" xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo" xmlns:classify="http://www.lexisnexis.com/xmlschemas/content/shared/classification/1/" version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/" id="Rosetta_docinfo.lbu-indexing-terms-to-LexisAdvance_classify.classification_classscheme_lbu-subj-scheme">
    <title><sourcexml>docinfo:lbu-indexing-terms</sourcexml> to  <targetxml>classify:classification[@classscheme="lbu-subj"]</targetxml> <lnpid>id-CCCC-10299</lnpid></title>
    

<body>
	<section>
	    <title>Instructions <i>[common element]</i></title>
		<p><sourcexml>docinfo:lbu-indexing-terms/docinfo:lbu-subj</sourcexml> becomes 
		    <targetxml>classify:classification[@classscheme="lbu-subj"]/classify:classitem/classify:classitem-identifier/classify:classcode[@normval]</targetxml>. 
		    The content of <sourcexml>docinfo:lbu-subj</sourcexml> becomes the value for <targetxml>classify:classcode[@normval]</targetxml>.
		</p>
	</section>
    
<example>
    <title>Source XML</title>
		<codeblock>

&lt;docinfo:lbu-indexing-terms&gt;
    &lt;docinfo:lbu-subj&gt;lawnow160&lt;/docinfo:lbu-subj&gt;
&lt;/docinfo:lbu-indexing-terms            

	</codeblock>
    </example>
	
    <example>
		<title>Target XML</title>
		<codeblock>

&lt;classify:classification classscheme="lbu-subj"&gt;
    &lt;classify:classitem&gt;
        &lt;classify:classitem-identifier&gt;
            &lt;classify:classcode normval="lawnow160"/&gt;
        &lt;/classify:classitem-identifier&gt;
    &lt;/classify:classitem&gt;
&lt;/classify:classification&gt;

	</codeblock>
    </example>
    <note>If source document having multiple <sourcexml>docinfo:lbu-subj</sourcexml> within <sourcexml>docinfo:lbu-indexing-terms</sourcexml>, then each subsequent occurrence of the element  <sourcexml>docinfo:lbu-subj</sourcexml> will <b>becomes</b> <targetxml>classify:classitem/classify:classitem-identifier/classify:classcode[@normval]</targetxml> element.</note>
    <example>
        <title>Source XML</title>
        <codeblock>

&lt;docinfo:lbu-indexing-terms&gt;
    &lt;docinfo:lbu-subj&gt;lawnowl60&lt;/docinfo:lbu-subj&gt;
    &lt;docinfo:lbu-subj&gt;lawnow295&lt;/docinfo:lbu-subj&gt;
&lt;/docinfo:lbu-indexing-terms&gt;            

	</codeblock>
    </example>
    
    <example>
        <title>Target XML</title>
        <codeblock>

&lt;classify:classification classscheme="lbu-subj"&gt;
    &lt;classify:classitem&gt;
        &lt;classify:classitem-identifier&gt;
            &lt;classify:classcode normval="lawnow160"/&gt;
        &lt;/classify:classitem-identifier&gt;
    &lt;/classify:classitem&gt;
    &lt;classify:classitem&gt;
        &lt;classify:classitem-identifier&gt;
            &lt;classify:classcode normval="lawnow295"/&gt;
        &lt;/classify:classitem-identifier&gt;
    &lt;/classify:classitem&gt;
&lt;/classify:classification&gt;

	</codeblock>
    </example>  
    <section>
        <title>Changes</title>
        <p>2012-08-30: Created.</p>
    </section>
    
    
</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated (although the DITA file already has embedded XSLT).  Remove this comment after manual development complete!  (also remove the embedded XSLT within the DITA above) @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_docinfo.lbu-indexing-terms-LxAdv-classify.classification_classscheme_lbu-subj-scheme.dita  -->
	<!--<xsl:message>Rosetta_docinfo.lbu-indexing-terms-LxAdv-classify.classification_classscheme_lbu-subj-scheme.xsl requires manual development!</xsl:message> -->

            <!-- CSN: Added docinfo:lbu-indexing-terms from base.xsl. -->
    
            <xsl:template 
                match="docinfo:lbu-indexing-terms">
                <xsl:if test="child::docinfo:lbu-juris">
                    <xsl:element name="classify:classification">
                        <xsl:attribute name="classscheme">docinfo:lbu-juris</xsl:attribute>
                            <xsl:apply-templates select="child::docinfo:lbu-juris"/>
                        </xsl:element>
                    </xsl:if>
                <xsl:if test="child::docinfo:lbu-subj">
                    <xsl:element name="classify:classification">
                        <xsl:attribute name="classscheme">lbu-subj</xsl:attribute>
                        <xsl:apply-templates select="child::docinfo:lbu-subj"/>
                    </xsl:element>
                </xsl:if>
            </xsl:template>
    
        <xsl:template match="docinfo:lbu-subj">
                <xsl:element name="classify:classitem">
                    <xsl:element name="classify:classitem-identifier">
                        <xsl:element name="classify:classcode">
                            <xsl:attribute name="normval">
                                <xsl:value-of select="."/>
                            </xsl:attribute>
                        </xsl:element>
                    </xsl:element>
                </xsl:element>
            </xsl:template>
    
            <xsl:template match="docinfo:lbu-juris[not($streamID='CA01')]">
                <xsl:element name="classify:classitem">
                    <xsl:element name="classify:classitem-identifier">
                        <xsl:element name="classify:classcode">
                            <xsl:attribute name="normval">
                                <xsl:value-of select="."/>
                            </xsl:attribute>
                        </xsl:element>
                    </xsl:element>
                </xsl:element>
            </xsl:template>
    
<!-- Vikas Rohilla : Updated as per the $streamID CA01    -->
    <xsl:template match="docinfo:lbu-juris[$streamID='CA01'][.!='CA' or .!='UK' or .!='NZ']">
        <xsl:element name="classify:classitem">
            <xsl:element name="classify:classitem-identifier">
                <xsl:element name="classify:classname">
                        <xsl:value-of select="."/>
                </xsl:element>
            </xsl:element>
        </xsl:element>
    </xsl:template>
        
</xsl:stylesheet>