<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:dita="http://dita.oasis-open.org/architecture/2005/"
	xmlns:docinfo="http://www.lexis-nexis.com/glp/docinfo"
	xmlns:classify="http://www.lexisnexis.com/xmlschemas/content/shared/classification/1/"
	version="2.0" exclude-result-prefixes="dita docinfo">

	<dita:topic xmlns="http://dita.oasis-open.org/architecture/2005/"
		id="Rosetta_docinfo.topiccodes-to-LexisAdvance_classify.classification_classscheme_docinfo-topiccodes">
		<title><sourcexml>docinfo:topiccodes</sourcexml> to
				<targetxml>classify:classification[@classscheme="docinfo:topiccodes"]</targetxml>
			<lnpid>id-CCCC-10306</lnpid></title>
		<body>
			<section>
				<title>Instructions <i>[common element]</i></title>
				<p><sourcexml>docinfo:topiccodes/docinfo:topiccode</sourcexml> becomes
						<targetxml>classify:classification[@classscheme="docinfo:topiccodes"]/classify:classitem/classify:classitem-identifier/classify:classcode/@normval</targetxml>.
					The content of <sourcexml>docinfo:topiccode</sourcexml> becomes the value for
						<targetxml>classify:classcode/@normval</targetxml>. A single
						<targetxml>classify:classification[@classscheme="docinfo:topiccodes"]</targetxml>
					is created for each unique value of <targetxml>@classscheme</targetxml>. Within
					this single element, create multiple <targetxml>classify:classitem</targetxml>
					elements. Only create additional <targetxml>classify:classification</targetxml>
					wrapper elements when the
						<targetxml>classify:classification[@classscheme]</targetxml> has different
					values. </p>
			</section>

			<example>
				<title>Source XML</title>
				<codeblock> &lt;docinfo:topiccodes&gt;
					&lt;docinfo:topiccode&gt;#PA#CODE#&lt;/docinfo:topiccode&gt;
					&lt;docinfo:topiccode&gt;#PA#BUSM#&lt;/docinfo:topiccode&gt;
					&lt;/docinfo:topiccodes&gt; </codeblock>
			</example>

			<example>
				<title>Target XML</title>
				<codeblock> &lt;classify:classification classscheme="docinfo:topiccodes"&gt;
					&lt;classify:classitem&gt; &lt;classify:classitem-identifier&gt;
					&lt;classify:classcode normval="#PA#CODE#"/&gt;
					&lt;/classify:classitem-identifier&gt; &lt;/classify:classitem&gt;
					&lt;classify:classitem&gt; &lt;classify:classitem-identifier&gt;
					&lt;classify:classcode normval="#PA#BUSM#"/&gt;
					&lt;/classify:classitem-identifier&gt; &lt;/classify:classitem&gt;
					&lt;/classify:classification&gt; </codeblock>
			</example>
			<section>
				<note><b>Applied for UK07 Regulation contents only:</b> When element
						<sourcexml>docinfo:topiccode</sourcexml> contains attribute
						<sourcexml>@scheme="source-by-date"</sourcexml>, then conversion will
					suppress it including its contents as well. Please see below input and output
					examples for more details:</note>
			</section>
			<example>
				<title>Source XML:</title>
				<codeblock> &lt;docinfo:topiccodes&gt; &lt;docinfo:topiccode
					scheme="source-by-date"&gt;2012-08-02&lt;/docinfo:topiccode&gt;
					&lt;docinfo:topiccode&gt;#PA#CODE#&lt;/docinfo:topiccode&gt;
					&lt;/docinfo:topiccodes&gt; </codeblock>
			</example>
			<example>
				<title>Target XML(Only second <sourcexml>docinfo:topiccode</sourcexml>)
					converted</title>
				<codeblock> &lt;classify:classification classscheme="docinfo:topiccodes"&gt;
					&lt;classify:classitem&gt; &lt;classify:classitem-identifier&gt;
					&lt;classify:classcode normval="#PA#CODE#"/&gt;
					&lt;/classify:classitem-identifier&gt; &lt;/classify:classitem&gt;
					&lt;/classify:classification&gt; </codeblock>
			</example>
			<section>
				<title>Changes</title>
				<p>2014-02-03: <ph id="change_20140203_PY">Added a special rule for UK07 contents,
						When element <sourcexml>docinfo:topiccode</sourcexml> contains attribute
							<sourcexml>@scheme="source-by-date"</sourcexml>, then conversion will
						suppress it including its contents as well. Phase 5 UK discussion-defect
						tracking: issue #156. </ph></p>
				<p>2012-08-30: Created.</p>
			</section>



		</body>
	</dita:topic>

	<!--  @@@ This file has been autogenerated (although the DITA file already has embedded XSLT).  Remove this comment after manual development complete!  (also remove the embedded XSLT within the DITA above) @@@  -->
	<!--    Original DITA file location:  DITA\ConversionInstructions\Rosetta\common_newest\Rosetta_docinfo.topiccodes-to-LxAdv-classify.classification_classscheme_docinfo-topiccodes.dita  -->

	<!-- CSN: Added docinfo:topiccodes and docinfo:topiccode from base.xsl. -->
	<xsl:template match="docinfo:topiccodes">
		<xsl:element name="classify:classification">
			<xsl:attribute name="classscheme">docinfo:topiccodes</xsl:attribute>
			<xsl:apply-templates/>
		</xsl:element>
	</xsl:template>

	<xsl:template match="docinfo:topiccode">
		<xsl:element name="classify:classitem">
			<xsl:element name="classify:classitem-identifier">
				<xsl:element name="classify:classcode">
					<xsl:attribute name="normval">
						<xsl:value-of select="."/>
					</xsl:attribute>
				</xsl:element>
			</xsl:element>
		</xsl:element>
	</xsl:template>

</xsl:stylesheet>
